### ISSUE TITLE
Investigate possible race condition in replicator cluster stability check

### ISSUE THREAD

**Issue by nickva** [apache/couchdb#1002]
User reported inserting a document when the cluster was not yet stable. That document update was never processed by the replicator. The replicator 'stable' even was issued before the 'update was ignored because cluster is unstable` log message.

## Expected Behavior

User updates replicator documents at any time, eventually they are all noticed and processed by the replicator.

## Current Behavior

Inserting a document at a particular time, leads to replicator ignoring it.

## Steps to Reproduce (for bugs)
...

## Your Environment

2 node cluster, version 2.1.0

**Comment by nickva** [comment]
Order of cluster setup:

Start state is empty data dir, stopped couchdb service on both cluster nodes

Each is then started and basic dbs created (_users, _replicator etc)

Then the cluster setup is done on an arbitrary node

 `PUT /_nodes/nodename`


"One thing I'm unsure of, I'm using port 5986 for cluster setup, is that still necessary?"

Also in case it's relevant, I do get some log errors initially: 
``` 
[error] 2017-11-16T22:15:43.405527Z couchdb@1 <0.454.0> xxx Request to create N=2 DB but only 1 node(s)

[error] 2017-11-16T22:15:44.524321Z couchdb@1 <0.486.0> xxx Request to create N=2 DB but only 1 node(s)

[error] 2017-11-16T22:15:45.655681Z couchdb@1 Request to create N=2 DB but only 1 node(s) 
```

**Comment by wohali** [comment]
Invalid bug - the _users/_replicator DBs are being created prior to the cluster being joined together, right?

**Comment by nickva** [comment]
User switched the order of cluster setup, but the issue was still there. After looking at this over the weekend noticed that it's possible there is a bug in 2.1.0 which could cause this behavior.

The good news is it seems in 2.1.1 this bug was fixed inadvertently when the module was refactored.

Notice the clustering module in 2.1.0:

https://github.com/apache/couchdb/blob/2.1.0/src/couch_replicator/src/couch_replicator_clustering.erl#L211 `is_stable` calls ends up checking if the quiet time has expired by using `os:timestamp()` result.

This means if `os:timestamp()` doesn't return monotonic results, (and in fact it is not guaranteed to) then this sequence of events is possible:

 * Cluster stability check fires https://github.com/apache/couchdb/blob/2.1.0/src/couch_replicator/src/couch_replicator_clustering.erl#L168 and notifies document processor that cluster is stable. 

 * Document processor starts processing replication documents. On first update it calls `is_stable()`. However if `os:timestamp()` return a timestamp which is less than the previous one, the `is_stable()` call could return `false`.

 * Document update is skipped.

 * However cluster `stable` event already fired and there won't be another one until cluster membership changes and another quiet period passes afterward.

I had a test script to check if os:timestamp() would move backwards, however I couldn't find any VMs or machines I had access to where this would happen. But it is entirely possible based on reading docs the behavior experience by the user.

The good news is that this particular bug was inadvertently when clustering module was refactored such that it has an explicit `stable` flag in the state:

https://github.com/apache/couchdb/blob/master/src/couch_replicator/src/couch_replicator_clustering.erl#L73

This means that after notifier gen_event fires with a stable event, any calls to `is_stable` will read the state from that flag instead of going to `os:timestamp()`

Contacted the user to ask them to try using the latest version 2.1.1. For now closing the issue again as it is fixed.
