### ISSUE TITLE
Failed to configure single node and can not load _replicator and _global_changes databases after upgrade from 2.0.0 to 2.1.1

### ISSUE THREAD

**Issue by goddyZhao** [apache/couchdb#1009]
1. I upgrade from 2.0.0 to 2.1.1 and specify the database_dir to the one for 2.0.0
2. I started the couchdb
3. From the web dashboard, it asked me to create admin account (I created in 2.0.0 but have no idea why it asked me to create again), and I created one with the same credentials
4. After I created the admin account, I login with it again to dashboard, but I found that `_global_changes` and `_replicator` databases are not able to be load (it said disabled to load database)
5. Then I tried to `configure single node`, after I fill the form, it shows a message on the page like `Apache CouchDB is configured for production usage as a unknown node!`, from the log, it looks like it failed to configure the single node
6. I tried to add a user to _users database, it raised server_internal_error, actually from the couchdb log, I did not see some details about the error

Anyone knows how to fix that? Thanks so much

**Comment by wohali** [comment]
http://docs.couchdb.org/en/2.1.1/whatsnew/2.1.html#upgrade-notes and read the first bullet point carefully.
