### ISSUE TITLE
Cannot build from tar archive

### ISSUE THREAD

**Issue by sergey-safarov** [apache/couchdb#1016]
I want build source from archive but this not possible.

## Expected Behavior
```
wget https://github.com/apache/couchdb/archive/master.tar.gz
tar xzf master.tar.gz
cd couchdb-master
export COUCHDB_VERSION=2.1.0
./configure --disable-docs
make
```
As result compiled CouchDB source

## Current Behavior
I got error
```
Compiled src/couch_epi_app.erl
Compiled src/couch_epi_codechange_monitor.erl
Compiled src/couch_epi.erl
ERROR: sh(git describe --always --tags)
failed with return code 128 and the following output:
fatal: Not a git repository (or any of the parent directories): .git

ERROR: compile failed while processing /home/build/qq/couchdb-master/src/couch_epi: rebar_abort
make: *** [Makefile:69: couch] Error 1
```

## Possible Solution
I not know

## Steps to Reproduce (for bugs)
already described at section "Expected Behavior"

## Context
I want package CouchdDB using Alpine package manager. usage of source archives is preferred by package manager rather than  git repository. Now i cannot package CouchDB using standard way.

## Your Environment
alpine linux 3.6

**Comment by wohali** [comment]
That is not the correct way to download our released source code, as GitHub does not have the prebuilt source tarball.

Instead please use our official source code repository:

https://dist.apache.org/repos/dist/release/couchdb/source/

or a mirror.
