### ISSUE TITLE
CouchDB 2.1 OAuth2 Authentication method

### ISSUE THREAD

**Issue by oleksmir** [apache/couchdb#1018]
According to [this](https://github.com/apache/couchdb/issues/656) issue, OAuth 1.0 was removed from CouchDB starting from version 2.1. But Is there a way to implement OAuth authentication still? Maybe version OAuth2 (by using some plugins etc.). Will oauth return to the CouchDB in future versions?

**Comment by wohali** [comment]
CouchDB's OAuth implementation was outdated, unmaintained and (in some regards) faulty.

CouchDB 2.x implements a proxy authentication mechanism. Using this, you can have any external process handle authentication for you and pass on the appropriate credentials.

CouchDB Documentation: http://docs.couchdb.org/en/latest/api/server/authn.html#proxy-authentication

One implementation of OAuth 2.0 that is known to work is using Apache HTTP Server as a reverse proxy in front of CouchDB. You can use something like [mod_auth_openidc](https://github.com/zmartzone/mod_auth_openidc) to add this support.

I don't know what is coming to CouchDB in the future, but for now, this is your best option. I do know that there are real customers using the proxy auth solution in production.
