### ISSUE TITLE
On Mac: Local.ini file location? couchdb 2.1.1

### ISSUE THREAD

**Issue by sensiblearts** [apache/couchdb#1020]
**UPDATE**: Ignore this, see comment questions below.

I broke Fauxton by I tried to config bind to **192.168.1.6** (instead of 127.0.0.1) in the config. 

Aside: I tried to do this because another (windows) computer was getting "connection refused" from the Mac (with an open Mac firewall), _but connection was not refused when I had it bind to 192.168.1.6._

But that broke Fauxton -- which is auto-launching repeatedly and looking for 127.0.0.1.

So where is  local.ini hiding? Or, how/where is Fauxton saving config state?

The local.ini file in the Application pkg folder seems to be a template -- it is not being changed, even though Fauxton is saving state. I looked all over.

OS X 10.11.6

**Comment by sensiblearts** [comment]
Well, it seems to have fixed itself in the 30 minutes I spent looking for local.ini.


**BUT** I still cannot figure out where Fauxton is saving its config state? File path...?

**Comment by sensiblearts** [comment]
Nor can I find the log files. Locations in the online docs or given in Google searches lead to folders that don't exist.

**Comment by sensiblearts** [comment]
I still don't know where the ini file is on Mac, but I finally got it working on Windows/WSL.

**Comment by brendand** [comment]
I'd also like to know this. I looked in `~/Library/Application Support/CouchDB2/etc/couchdb`, but there was no `local.ini` file there, even though the changes saved in the Fauxton configuration UI are being saved somewhere.

**Comment by aal89** [comment]
For everyone who is still figuring this out. It should be in your users Library folder under Preferences.

```
# cd ~/Library/Preferences/couchdb2-local.ini
```

**Comment by brendand** [comment]
Oh yes! It's there. Weird. Thanks!

**Comment by jhau** [comment]
I tried setting config option in ~/Library/Preferences/couchdb2-local.ini and ~/Library/Application\ Support/CouchDB2/etc/couchdb/local.ini but neither file has any effect, the only config file that seems to work is /Applications/Apache\ CouchDB.app/Contents/Resources/couchdbx-core/etc/default.ini

**Comment by intersides** [comment]
Under MacOS, For some reason **~/Library/Preferences/couchdb2-local.ini** did not had any effects (Usually it does).
I had to manually change **/Applications/Apache CouchDB.app/Contents/Info.plist** ip address and restart   couchdb

**Comment by marklindsay24** [comment]
I have tried for two days trying to figure out how to override DB location when running the Mac App. 

Done of following works:
~/Library/Preferences/couchdb2-local.ini
/Applications/Apache\ CouchDB.app/Contents/Resources/couchdbx-core/etc/default.ini

Please HELP!

**Comment by wohali** [comment]
@marklindsay24 the repository containing the script used to build the Mac app is here: https://github.com/janl/build-couchdb-mac

My guess is that you have to edit that Info.plist file as previously mentioned in this thread - I don't use a Mac so I'm at the limits of my ability to help you here.

**Comment by xpagesbeast** [comment]
I installed couchDB with Homebrew
Then started couchDB
Experienced the error with not having a Admin user setup.

`vi /usr/local/Cellar/couchdb/3.2.0/etc/local.ini`

```
[admins]
admin = mysecretpassword
```

Then tried couchDB using the terminal again, and it started.
I found the path by search Hombrew 
` % brew list couchDB | grep ini    `
