### ISSUE TITLE
CouchDB, how to use uuid? can i get timestamp from this uuid?

### ISSUE THREAD

**Issue by anlexN** [apache/couchdb#1024]
## Your Environment

* Version used: 2.1.1
* Browser Name and version: the latest chrome, firefox
* Operating System and version (desktop or mobile): windows 10 x64

*where is source code about uuid generated by couchdb?*
![default](https://user-images.githubusercontent.com/8686739/33311551-15dffc36-d460-11e7-9ec9-70699b18835d.PNG)

**Comment by jaydoane** [comment]
@anlexN I believe the source code for uuid generation is https://github.com/apache/couchdb/blob/master/src/couch/src/couch_uuids.erl
but AFAIK you cannot get a timestamp from it.

If you want a timestamp in your document, I suggest adding one explicitly. For that matter, you're probably better off choosing your `_id` in a more meaningful way as well.
