### ISSUE TITLE
why user is not_found?

### ISSUE THREAD

**Issue by anlexN** [apache/couchdb#1036]
## Your Environment

* Version used: 2.1.1
* Browser Name and version: google, firefox and other latest
* Operating System and version (desktop or mobile): win10 x64 pro

### I follow your document:
![default](https://user-images.githubusercontent.com/8686739/33465311-2af57474-d682-11e7-8468-e6089b698dc5.PNG)

### i use [httpie](https://httpie.org/), make sure correctly installed ! but your couchdb is problem
![1](https://user-images.githubusercontent.com/8686739/33465390-9c387960-d682-11e7-8576-01d02abed1ac.PNG)

### my Faxtion gui, and login in my admin, i make sure _user/org.couchdb.user:jan is alive!
![2](https://user-images.githubusercontent.com/8686739/33465461-f4a1b5f8-d682-11e7-99d2-062c622f5601.PNG)

**Comment by wohali** [comment]
I cannot reproduce this bug, I'm sorry. I followed all of the steps above and my httpie request succeeds (as it does with curl, too):

```
C:\Windows\system32>http http://127.0.0.1:5984/_users/org.couchdb.user:jan
HTTP/1.1 200 OK
Cache-Control: must-revalidate
Content-Length: 255
Content-Type: application/json
Date: Tue, 16 Jan 2018 20:09:03 GMT
ETag: "1-31fab2c5c45cdc28307da2535a97c5c7"
Server: CouchDB/2.1.1 (Erlang OTP/18)
X-Couch-Request-ID: 4a19d8425c
X-CouchDB-Body-Time: 0

{
    "_id": "org.couchdb.user:jan",
    "_rev": "1-31fab2c5c45cdc28307da2535a97c5c7",
    "derived_key": "af0230f9854e1515959100d71a661498d194e3bc",
    "iterations": 10,
    "name": "jan",
    "password_scheme": "pbkdf2",
    "roles": [],
    "salt": "1c75841706e7e67bbe7be0d5e15bcb11",
    "type": "user"
}
```

In Fauxton, click on _users, then org.couchdb.user:jan, then click on the JSON link at the top right. That should open the exact URL in your browser and you should see the correct data being returned.

If your httpie request fails, look at `C:\CouchDB\var\log\couchdb.log` and see if you can see why the request failed. Perhaps the URL is being mangled somehow by httpie.
