### ISSUE TITLE
add a node , wrong!

### ISSUE THREAD

**Issue by anlexN** [apache/couchdb#1037]
## Your Environment

* Version used: 2.1.1
* Browser Name and version: chrome , firefox, and other latest
* Operating System and version (desktop or mobile): win10 x64 pro

![default](https://user-images.githubusercontent.com/8686739/33471539-d21188da-d6a8-11e7-85fd-38ae8a82b7ec.PNG)
![1](https://user-images.githubusercontent.com/8686739/33471541-d320a13e-d6a8-11e7-8cb1-de1ddd546aaf.PNG)
![2](https://user-images.githubusercontent.com/8686739/33471576-03421668-d6a9-11e7-8619-fc90088e062e.PNG)

### i have setup a single nod in faxtion gui, but how to setup single node or cluster in command? i have read more three times [your document](http://docs.couchdb.org/en/2.1.1/cluster/nodes.html). i still can't do it! i try to rename my admin name "anlex N" to "anlex", i still can't!

**Comment by wohali** [comment]
Note that the PUT has to be to port 5986, not port 5984, for editing _nodes.
