### ISSUE TITLE
Expire X-Auth-CouchDB-Token manually?

### ISSUE THREAD

**Issue by phuczeero** [apache/couchdb#1041]
I have a Rest API store users in MongoDB, I want to use Couch-Pouch as synchronize DBs to keep user files structure.

I follow _Proxy Authentication_ section to implement this case:

- When users login, the API authenticate them via MongoDB.
- After that generate a **token** by hashing (hmac_sha1) the user id (already exist in `_users` db) then return to the client.
- When Pouch sync to Couch, I set X-Auth-CouchDB-Token & X-Auth-CouchDB-UserName headers to the request.

But when the users change their password, I want to expire previous generated **token**, how can I do that?

**Comment by kocolosk** [comment]
This is not possible for a specific user today. The only way to invalidate a token associated with a given username is to change the value of the `[couch_httpd_auth] secret` configuration setting, but this would invalidate *all* of your tokens.

The point of the token in the proxy authentication handler is to prove that the system sending the HTTP request should be trusted by CouchDB. It's specifically not intended to be a user-specific password.
