### ISSUE TITLE
it is bug? i can not compact my database through curl

### ISSUE THREAD

**Issue by anlexN** [apache/couchdb#1043]
## Expected Behavior

i follow [your compaction document](http://docs.couchdb.org/en/2.1.1/maintenance/compaction.html) i want to compact my database

## Current Behavior

But compact is still false
![default](https://user-images.githubusercontent.com/8686739/33589864-624acac8-d9b6-11e7-8793-551ba30d2c93.PNG)
![1](https://user-images.githubusercontent.com/8686739/33589866-628ecae8-d9b6-11e7-976e-93958b4fae68.PNG)

## Your Environment

* Version used: 2.1.1
* Browser Name and version: latest
* Operating System and version (desktop or mobile): all

**Comment by kocolosk** [comment]
Hi @anlexN , your database is very small so compaction would have completed almost instantaneously. You could check the logs for indications of each shard file in the database being compacted.

I'm going to close this issue for now but please feel free to re-open if you have questions.

**Comment by anlexN** [comment]
please add this imformation in your document
