### ISSUE TITLE
view is not clean up, it is a bug?

### ISSUE THREAD

**Issue by anlexN** [apache/couchdb#1044]
## Expected Behavior

i follow you [view document](http://docs.couchdb.org/en/2.1.1/maintenance/compaction.html#views-cleanup), i want to clean up my view
## Current Behavior

view is still alive
![default](https://user-images.githubusercontent.com/8686739/33592124-4287ae46-d9c4-11e7-82c8-9c447db24583.PNG)
![1](https://user-images.githubusercontent.com/8686739/33592125-42d24c80-d9c4-11e7-9d9d-85cbcacc2602.PNG)

## Your Environment

* Version used: 2.1.1
* Browser Name and version: chrome, firefox latest
* Operating System and version (desktop or mobile): all

**Comment by wohali** [comment]
"View cleanup" is a compaction process, which reduces the space the view takes up on disk.

If you want to **delete** the view, you need to use the view deletion function:

`curl -X DELETE http://anlex_N:n@localhost:5984/hello-world/_design/price`

Or, in Fauxton:

![mwsnap 2018-01-16 15_14_20](https://user-images.githubusercontent.com/112292/35010189-0fe953e0-fad0-11e7-9684-6dfbc26c2a66.png)
