### ISSUE TITLE
how to give Erlang four threads in the windows

### ISSUE THREAD

**Issue by anlexN** [apache/couchdb#1045]
i follow your [performance document](http://docs.couchdb.org/en/2.1.1/maintenance/performance.html#disk-and-file-system-performance)
![default](https://user-images.githubusercontent.com/8686739/33594099-8398c128-d9cd-11e7-8017-8e1b053bbfdc.PNG)

## Your Environment

* Version used: 2.1.1
* Browser Name and version: latest chrome
* Operating System and version (desktop or mobile): windows x64 pro

**Comment by kocolosk** [comment]
So this is really a general question about setting environment variables on Windows.

For what it's worth, in modern versions of CouchDB we already automatically activate the thread pool (and set it to 16 threads).

**Comment by anlexN** [comment]
@kocolosk  can you tell me how to set this manually?

**Comment by wohali** [comment]
You can edit the line

```
+A 16
```

in the file `C:\CouchDB\etc\vm.args`, then restart the CouchDB service. As you can see, @kocolosk confirmed we already set this to 16 by default.
