### ISSUE TITLE
CouchDB 1.6.1 not working in https

### ISSUE THREAD

**Issue by abhishekkhatter** [apache/couchdb#1046]
I have configured CouchDB 1.6.1 for https, but it is not working.

It is executed in IE Browser but giving below error when I am trying to execute it via Curl
**curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 192.168.100.6
7:6984**

**Comment by wohali** [comment]
CouchDB 1.6.1 only supports SSL3.

Try upgrading to 1.7.1 (also addresses a serious security issue!) or:

https://stackoverflow.com/questions/19384161/curl-error-35-unknown-ssl-protocol-error-in-connection-to-api-rkd-reuters-com

You may be able to specify `-3` or `--sslv3` on the CLI for curl.
