### ISSUE TITLE
why fail to restart  the CouchDB instance through curl

### ISSUE THREAD

**Issue by anlexN** [apache/couchdb#1047]
## Expected Behavior

i follow your [restart document](http://docs.couchdb.org/en/2.1.1/api/server/common.html#restart), hope restart my couchdb through curl!
## Current Behavior

succeed to log in, but database is not exist?
![default](https://user-images.githubusercontent.com/8686739/33611294-d12617f2-da08-11e7-9a47-acffb4b18f78.PNG)

## Your Environment

* Version used: 2.1.1
* Browser Name and version: all
* Operating System and version (desktop or mobile): windows x64 pro

**Comment by wohali** [comment]
Thanks for reporting this, this is a bug. CouchDB no longer supports the `/_restart` endpoint.

You will need to restart CouchDB using the Windows Services control panel, or using the `sc` command from an Administrator Command Prompt:

```
C:\Windows\system32>sc stop "Apache CouchDB"

SERVICE_NAME: Apache CouchDB
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 3  STOP_PENDING
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x1
        WAIT_HINT          : 0xdac

C:\Windows\system32>sc query "Apache CouchDB"

SERVICE_NAME: Apache CouchDB
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

C:\Windows\system32>sc start "Apache CouchDB"

SERVICE_NAME: Apache CouchDB
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 2  START_PENDING
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x7d0
        PID                : 7724
        FLAGS              :

C:\Windows\system32>sc query "Apache CouchDB"

SERVICE_NAME: Apache CouchDB
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```

**Comment by anlexN** [comment]
Execuse me. please review and update your document very often!
# I am willing to be your contributor. But i think i don't master couchdb. Could you please train me?
@Couchdb team

**Comment by wohali** [comment]
Thanks for expressing interest in contributing!

Do you want to help with our documentation? That's a great place to start. You can help fix the bug that you identified, and you don't have to be a coder at all.

First, read this: https://github.com/apache/couchdb/blob/master/CONTRIBUTING.md
We also have a code of conduct: https://couchdb.apache.org/conduct.html

Then, if you know GitHub, you can fork the [apache/couchdb-documentation](https://github.com/apache/couchdb-documentation) repository, create a branch (we recommend starting the branch name with the bug #, so something like 231-remove-restart), editing the right file (probably [this one](https://github.com/apache/couchdb-documentation/blob/7f8c3abc8882e2ff171ac304a8d9584b7e638845/src/api/server/common.rst), though there are other references that should be removed as well), checking in your code, pushing it to GitHub, and opening a Pull Request (PR).

As for training on CouchDB, you might want to start by reading our backlog of mailing list messages: [couchdb-user](https://lists.apache.org/list.html?user@couchdb.apache.org) and [couchdb-dev](https://lists.apache.org/list.html?dev@couchdb.apache.org). There's a lot of valuable information in there.

Once again, so happy to have you working with us!
