### ISSUE TITLE
●5 Couch Db and Couch Base Lite Syncing Data to Android App, List view not refreshing sometime With LiveQuery

### ISSUE THREAD

**Issue by VipulDamor** [apache/couchdb#1050]
**I am new to couchDB and trying to pull the data from CouchDB to My Devices using CouchSync Gateway. i achieved 80% success ratio that out of 10 , 8 times my data synchronized and i got the data on my other devices, but can i raise to 100%. is their any way or any settings that can help me out.**
**heare is link i posted question** 

(https://stackoverflow.com/questions/47667678/couch-db-and-couch-base-lite-syncing-data-to-android-app-list-view-not-refreshi)

**Comment by wohali** [comment]
We do not support CouchSync Gateway, it is entirely supported by the commercial entity known as CouchBase.

**Comment by chintan-mishra** [comment]
Also, Couchbase-Lite 2.0 doesn't support CouchDB based DBs. Please refer to [this link](https://developer.couchbase.com/documentation/mobile/2.0/references/couchbase-lite/release-notes/index.html) related to Release Notes of latest Couchbase-Lite 2.0
