### ISSUE TITLE
Couch return unknown_error / function_clause when create a user with non-string password

### ISSUE THREAD

**Issue by phuczeero** [apache/couchdb#1051]
## Expected Behavior
Explicit error response

## Current Behavior
```
{
    "message": "function_clause",
    "error": "unknown_error",
    "reason": "function_clause",
    "ref": 1648166316,
    "scope": "couch",
    "statusCode": 500,
    "request": {
        "method": "POST",
        "headers": {
            "content-type": "application/json",
            "accept": "application/json"
        },
        "uri": "http://couchdb:5984/_users",
        "body": {
            "_id": "org.couchdb.user:test",
            "name": "test",
            "password": 123,
            "roles": [],
            "type": "user"
        }
    }
}
```

## Your Environment

* Version used: 2.1.1

**Comment by kocolosk** [comment]
Yes this is a bug -- the `couch_passwords` hashing module is rightly checking that the password is the correct datatype before proceeding, but we can be smarter about bubbling up a good error message.

**Comment by jiangphcn** [comment]
PR #1087 was merged to address this issue.

**Comment by wohali** [comment]
@jiangphcn when you merge a PR to fix a bug, please put

"Fixes #1051"

in your PR commit message, that will auto-close the issue. :)

**Comment by jiangphcn** [comment]
@wohali thanks a lot for your tip. Will do later.

**Comment by jareware** [comment]
We're on the (new) IBM-hosted Cloudant, and have randomly gotten a few:

```
{ error: 'unknown_error', 
  reason: 'function_clause', 
  ref: 687197157, 
  name: 'unknown_error', 
  status: 500, 
  message: 'function_clause' } 
```

on our logs. It's from a `_changes` listener, so shouldn't have anything to do with password hashing.

Any ideas..?

**Comment by dynamite-ready** [comment]
I'm not entirely sure if this is directly related to this issue, but I suspect it is, and possibly a few others.
This code - https://github.com/apache/couchdb/blob/deba7575a1a67fe06850959e99af3e0e9c704443/src/couch/include/couch_erl_functions.hrl#L32 - 

```
true -> throw({forbidden, <<"Only admins may delete other user docs.">>})
```

Will throw an `unknown_error` to the log, and return a `500` status code to the frontend.

If instead, I do:

```
true -> {[{ <<"forbidden">>, <<"Only admins may delete other user docs.">> }]}
```

Then no error appears in the log, but a `403` is returned to the frontend, along with the contents of the second element in the tuple.

This appears to match the clause in the case statement found here - https://github.com/apache/couchdb/blob/master/src/couch/src/couch_query_servers.erl#L379

Might this be related?
