### ISSUE TITLE
CouchDB as a proxy over chttpd not working

### ISSUE THREAD

**Issue by endyjasmi** [apache/couchdb#1054]
## Expected Behavior
When setting up CouchDB as a proxy using [this](http://docs.couchdb.org/en/2.1.1/config/proxying.html) as a guide. It should work on port 5984.

I remember a while back when authentication facing the same issue of not working on port 5984. Maybe it's the same problem?

## Current Behavior
Currently, after I have set the httpd_global_handlers, the proxy is working on port 5986 but not working on port 5984.

## Possible Solution
Migrate the proxy handler code to chttpd side?

## Steps to Reproduce (for bugs)
Setup CouchDB as a proxy and try to access the proxy endpoint prefix using port 5984.

## Context
I'm trying to use CouchDB as a front facing web server to reduce the number of service needed in the production. *Currently using a reverse proxy in front*

## Your Environment
* Version used: CouchDB 2.1.1 (docker-couchdb)
* Browser Name and version: Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Windows 10 Pro (Desktop)

**Comment by kocolosk** [comment]
Yes that looks right to me @endyjasmi , and your proposed solution is a good one. Leaving this here for now to see if anyone wants to try their hand at a patch. Thanks for the report.

**Comment by johs** [comment]
Thanks for this endyjasmi, I stuggled a lot to configure http_global_handlers without any luck. Using  port 5986 as a workaround helps.
Hope this bug can be fixed!

**Comment by johs** [comment]
@wohali  thanks, Joan. I updated https://github.com/apache/couchdb/issues/1407 This bug is a dealbreaker for us for upgrading to 2.1.1.

**Comment by janl** [comment]
See https://github.com/apache/couchdb/issues/1407
