### ISSUE TITLE
Update documentation to describe q as configurable field for peruser dbs

### ISSUE THREAD

**Issue by jiangphcn** [apache/couchdb#1055]
In the `[couch_peruser]` config section, introduced new config field `q` for peruser-created databases. The change was reflected on `default.ini` and `local.ini` in PR https://github.com/apache/couchdb/pull/1030. However, this also needs to be documented.

Related issues: https://github.com/apache/couchdb/issues/875 https://github.com/apache/couchdb/pull/1030

**Comment by wohali** [comment]
Moved to apache/couchdb-documentation#234
