### ISSUE TITLE
Update documentation to describe queries support for _all_docs etc

### ISSUE THREAD

**Issue by jiangphcn** [apache/couchdb#1056]
Need to document support of allowing to POST to `/{db}/_all_docs` and specify a queries list in the body, the same way we can do with a regular MapReduce view. This also can work against `/{db}/_design_docs` and `/{db}/_local_docs` endpoints.

Related issues: https://github.com/apache/couchdb/issues/820 https://github.com/apache/couchdb/pull/1032

**Comment by wohali** [comment]
Moving this to apache/couchdb-documentation#233.
