### ISSUE TITLE
No way of Paginating List function results?

### ISSUE THREAD

**Issue by nlangcoy** [apache/couchdb#1057]
Hello! I'm developing an app which needs to make use of a list function that accepts a couple of conditions. I am looking for a way to paginate the results of the list function but I haven't found a way. 
Currently, pagination works by setting the limit and skip parameters of the view, right?

## Expected Behavior

I'm trying to invoke a list function against a view like this: https://localhost:6984/mydb/_design/mydesigndoc/_list/myList/mydesigndoc/myView?limit=50 and get 50 items.

## Current Behavior

Currently, the query above retrieves 50 items from myView and then those 50 items are fed into the list function. But if any of those 50 items don't satisfy the conditions I have inside the list function, I'll end up receiving < 50 items.

## Possible Solution

Since the number of output documents a list function generates is controlled by the creator(of the function), there's no one way of doing the pagination that will work for everybody, but I suggest a function **getRow(index)** 
 or an **offset(index)** callable inside a list function that lets us jump to/ start iterating from a certain row. That way, the actual pagination is left to the creator by specifying some parameters (e.g. page, pagesize) of his own and control the # of output.

## Context

I'm trying to list items of a view but filter these items against a specific Date-Time range.

**Comment by wohali** [comment]
There's no built-in way, but: your list function receives the `req` object. You should be able to implement your own pagination if desired.

Prototype: `function(head, req) {... }`

More info: http://guide.couchdb.org/draft/transforming.html

Paging @flimzy this is a good one for us to consider adding to the documentation.

**Comment by wohali** [comment]
Because of how lists are implemented, we must stream all of the data to the `couchjs` process. There is no way we can allow you to "jump ahead," but you can easily loop over (and discard) rows until you reach the desired row yourself.
