### ISSUE TITLE
[Question] Periodic performance degradation

### ISSUE THREAD

**Issue by style95** [apache/couchdb#1065]
I am benchmarking bulk API to inserts bunch of documents against CouchDB cluster.
I am batching 500 documents into one request and my setup is comprised of 3 CouchDB nodes.

I am facing periodic performance degradation.

I think this is because CouchDB should periodically synchronize its pending changes.
I could observe many `pending_changes` logs.
```
[warning] 2017-12-13T07:22:48.173767Z couchdb@10.113.130.93 <0.294.0> -------- mem3_sync shards/a0000000-bfffffff/lambda-bmt_activations.1513147731 couchdb@10.113.130.92 {pending_changes,54247}
```

I already looked into this guide, but it did not help me
http://docs.couchdb.org/en/2.1.1/maintenance/performance.html#disk-and-file-system-performance

Once performance is dropped, it took about 30s ~ 60s to get back to the stable state.

![image](https://user-images.githubusercontent.com/3447251/33930291-bb84fbe8-e02f-11e7-9691-5f995d532750.png)

Is there any way to alleviate this problem?

**Comment by kocolosk** [comment]
Hi @style95, CouchDB is configured to ~continuously cross-check the replicas of each database shard for consistency. The warning messages you observed are emitted when one of the replicas falls behind in its cross-checks, which can definitely be a side-effect of maxing out the incoming write load on the cluster. The cross-checks are not scheduled at any particular interval; rather, they are queued up whenever writes are committed.

I'm not sure those warning messages are directly related to your observed throughput degradation though. Performance degradation that recovers on its own while the load is still applied is an interesting case. Do you have automatic compactions configured or anything like that? I think we may need a fair bit more detail to offer much constructive advice here.

**Comment by style95** [comment]
@kocolosk Thanks

I have this configuration.

```
[compaction_daemon]
check_interval = 300
min_file_size = 131072

[compactions]
_default = [{db_fragmentation, "70%"}, {view_fragmentation, "60%"}]
```

I think, to minimize the impact of `cross-check`, it might be better to reduce the check interval.
Then side effects might be distributed across time.

Could I just reduce that `check_interval` value to get what I described above?

**Comment by kocolosk** [comment]
OK, it may be the case that the server is triggering compactions and the competition for resources is what is slowing you down in those intervals. When the compaction finishes your throughput is restored. You can determine if this is the case by checking the Active Tasks in the dashboard (or use the `_active_tasks` endpoint).

Changing the `check_interval` might defer things a bit, but you'd still have the possibility of a compaction running during your benchmark. There are many other settings you can apply to tune the compactor's resource utilization:

http://docs.couchdb.org/en/2.1.1/config/compaction.html

You could also disable compaction during the test, but note that compaction does need to run periodically even if your database never updates individual documents.

Note that compaction is a separate process from the one generating the `pending_changes` messages. I think those are less likely to be related to the changes in throughput personally.

I'm going to go ahead and close this issue for now but by all means re-open if you have further questions :)

**Comment by style95** [comment]
@kocolosk Thank you for the answer. But I am still curious.
AFAIK, compaction is the progress of deleting old revisions.
In my benchmark, I always insert new documents with bulk insertion.
In this case, there could be compaction which affects performance such tremendously?

Is there any interval to synchronize(internally and across node) bunch of bulk-inserted documents?

**Comment by kocolosk** [comment]
A very fair question.

It turns out that compaction cleans up more than just old document revisions. Any time a document is written CouchDB needs to update a pair of Btree indexes that help to quickly locate the document on disk. Like everything else in CouchDB, these indexes are maintained in a purely copy-on-write fashion. This means that the database file accumulates a lot of old Btree nodes, even when the database is only seeing new inserts.  Eventually the volume of old Btree nodes alone is enough to trip the db_fragmentation threshold.

**Comment by style95** [comment]
Very clear.
Thank you very much @kocolosk : )
