### ISSUE TITLE
Can't create user in CouchDB - nonode@nohost is down

### ISSUE THREAD

**Issue by qualisign** [apache/couchdb#1084]
I'm trying to create a new admin user in CouchDB. A comment left on a blog states that I should create a new admin like this:

`curl -X PUT $HOST/_node/nonode@nohost/_config/admins/root -d '"super_secret"'`

When I run this command I get the following error:

`{"error":"nodedown","reason":"nonode@nohost is down"}`

What could be causing this, and what can I do to create a new admin if this doesn't work?

I expect to see a sussess message. 

When I view the list of current nodes I get the following:

```
curl http://localhost:5984//_membership
{"all_nodes":["couchdb@localhost"],"cluster_nodes":["couchdb@localhost"]}
```

**Comment by wohali** [comment]
Replace `nonode@nohost` with `couchdb@localhost` and this will work.
