### ISSUE TITLE
Upgrading couchdb to 1.6.1

### ISSUE THREAD

**Issue by sajeeval** [apache/couchdb#1086]
Hello,
We have couch 1.3.1 and 1.4.1 installed on ubuntu 12 and 14 servers. We need to migrate/upgrade all in to couch 1.6.1 and ubuntu 16.04.
Kindly let us know the best way to do this with minimum downtime. 
Thank you.

**Comment by wohali** [comment]
0. You actually want CouchDB 1.7.1, see [this post](https://blog.couchdb.org/2017/11/11/1-7-1/)
1. Backup all of your data.
2. Install CouchDB 1.7.1 and Ubuntu 16.04 on a new machine
3. Copy over your ini file changes (if any) and restart CouchDB
4. Test that CouchDB works
5. Copy over your entire data directory to the new servers
6. Test that your databases present correctly, as expected. Test your application against it
7. Block client/user access to the old CouchDB servers
8. Replicate any changes from the old servers to the new ones.
9. Swap the new servers in for the old ones

**Comment by sajeeval** [comment]
Hello Wohali,
Thank you for your reply. I have one more question.
Directly copying the data directory from an older version to a newer version will not introduce any compatibility issues?
Don't database files include version specific metadata? If we take a database file, it can be copied to another couchdb instance regardless of the version?

**Comment by wohali** [comment]
CouchDB knows how to update that metadata on first open. You can safely upgrade from anything newer than I think 1.0.2 to any newer 1.x version.

But it is not "regardless of the version," you need to be careful about upgrading to 2.x. We have documentation about the process for 2.x here: http://docs.couchdb.org/en/2.1.1/install/upgrading.html

**Comment by sajeeval** [comment]
Hi,
Thank you for your reply. One more question:
In case we want to rollback to an older version, say from 1.7.1 to 1.3.1, is that possible by copying the data directory?

**Comment by wohali** [comment]
No. You will have to replicate back. File formats are not reverse compatible.

**Comment by sajeeval** [comment]
Thanks Wohali
