### ISSUE TITLE
cpu usage 100% caused by silence and fs-manager

### ISSUE THREAD

**Issue by barbalex** [apache/couchdb#1088]
## Expected Behavior
Usually CPU usage should be below 10%.

## Current Behavior
CPU usage is at 100% 95% of the time.

On 5 different production servers I have noticed that cpu usage has been at 100% for most of the time during at least the last 30 days.

From running `top` it seems that most often Silence is the main culprit, using 98% of the cpu. Sometimes `fs-manager` and `Silence` both use 49% each. And on one server it seems that `fs-manager` uses 98%.

There are no active tasks running.

Two of these servers couches contain very low number of docs (a few hundred). The others have about 30'000 docs.

What could cause this behaviour?
How problematic is it?
How can I prevent it?

## Your Environment

* Version used: 1.6.1
* Operating System and version (desktop or mobile): ubuntu 14.04, ubuntu 16.04.02
* Link to your project: https://github.com/FNSKtZH/artendb_v1, https://github.com/barbalex/bb2, https://github.com/barbalex/brexit
![ae_top](https://user-images.githubusercontent.com/669783/34561395-076e4886-f14a-11e7-8dec-441ad96975d4.jpg)
![artdaten_top](https://user-images.githubusercontent.com/669783/34561396-0789414a-f14a-11e7-843b-f97e6282d8a7.jpg)
![bb_top](https://user-images.githubusercontent.com/669783/34561397-07a46fba-f14a-11e7-9028-74b35a9432b4.jpg)
![brexit_top](https://user-images.githubusercontent.com/669783/34561398-07c2f368-f14a-11e7-84db-d5dcdd995725.jpg)

**Comment by garrensmith** [comment]
From the other reports I've seen on the dev mailing list, your couchdb instance has been hacked and someone has installed a bitcoin mining instance on your service.

**Comment by barbalex** [comment]
@garrensmith Yep, you were right. These were crypto miners. I found a mailing list mail from Sinan Gabel explaining how to turn off the miner. Unfortunately I do not know how to link to Sinan's mail so here is the gist:

I needed to remove a cron job created from user couchdb:

```
sudo -i
su couchdb
crontab -e

// Then remove the line in the cron
// save and reboot
```

So thanks a lot to you and Sinan Gabel.

Of course I will also have to rebuild my servers now.

My biggest concern now is: How to prevent this from happening again, as these couch instances were not in admin mode.

**Comment by barbalex** [comment]
@garrensmith: thanks a lot for your great help!

**Comment by paulocoghi** [comment]
I was also hit by this invasion. I am using the CouchDB 1.6.1 from stable ppa https://launchpad.net/~couchdb/+archive/ubuntu/stable

How can I update it to solve this security vulnerability? Or there is an available workaround?

**Comment by paulocoghi** [comment]
Found a solution: https://github.com/apache/couchdb/issues/787

**Comment by barbalex** [comment]
I would not update. Eliminating the cron job is not enough. In my case the
problem reappeared inside minutes.

I rebuilt the servers with v2.1.1, then synced my DB. Don't know if syncing
could even be risky...

But so far it works.

vom Handy

Am 12.01.2018 9:23 nachm. schrieb "Paulo Coghi" <notifications@github.com>:

**Comment by paulocoghi** [comment]
> In my case the problem reappeared inside minutes.

@barbalex , this happened in which version?

I upgraded to version 2.1.1 after using 1.6.1 and experiencing this problem. I used `couchup` to migrate data from the old version to the new one.

So far, everything working perfectly. The only detail was that `couchup` did not migrate the users, and I had to re-create them manually.

**Comment by paulocoghi** [comment]
@barbalex , just removing the cron jobs is certainly not enough since the vulnerability remains open if you do not upgrade.

**Comment by barbalex** [comment]
@paulocoghi 

This was during the short period before I rebuilt the servers. So still with version 1.6.1.

And you may be better off not migrating the users: The "bad guys" added a few users. And also a few db's (with only one document each).

**Comment by wotaen** [comment]
Just for reference if anyone is looking for the process name. It's 'supsplk' in my case. It's stored in `/var/tmp/`

**Comment by AlbertDavid94** [comment]
I've had the same problem. A Monero miner was installed through a curl request to 192.99.142.232:8220/logo3.jpg which is in turn a bash script. When it starts with 192., doesn't it refer to a local network?

**Comment by wohali** [comment]
@AlbertDavid94 No, the private IP space is only `192.168.0.0 - 192.168.255.255`. Addresses outside this range are publicly routeable, including `192.99.142.232`.

The full set of private IP space blocks is documented in [RFC 1918](http://www.faqs.org/rfcs/rfc1918.html).
