### ISSUE TITLE
apt-get install/upgrade couchdb on debian stretch fails

### ISSUE THREAD

**Issue by elwin1234** [apache/couchdb#1094]
## Expected Behavior
Using the predefined binaries I expect a successful install. I followed the installation guide @ http://docs.couchdb.org/en/master/install/unix.html#installation-using-the-apache-couchdb-convenience-binary-packages

## Current Behavior
The output gives the following
```bash
Do you want to continue? [Y/n] Y
Setting up couchdb (2.1.1-1~stretch) ...
dpkg: error processing package couchdb (--configure):
 subprocess installed post-installation script returned error exit status 7
Errors were encountered while processing:
 couchdb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
## Your Environment
* Couchdb 2.1.1.1~stretch
* Debian 9.3

**Comment by wohali** [comment]
Can you provide more logfiles? I cannot reproduce this locally.

Try editing `/var/lib/dpkg/info/couchdb.postinst` so that the first line is `#!/bin/sh +x` and see if that gives us more to go on.

**Comment by elwin1234** [comment]
Hi,

Thanks for your reply!

I had to make a `#!/bin/sh -x` (instead of `#!/bin/sh +x`) line in order to see output.

This is the end of it:
```
+ ip=127.0.0.1
+ [ ! -z  ]
+ url=http://127.0.0.1:5984
+ grep -q _users
+ curl -s http://127.0.0.1:5984/_users
+ curl -s -X PUT http://127.0.0.1:5984/_users
dpkg: error processing package couchdb (--configure):
 subprocess installed post-installation script returned error exit status 7
Errors were encountered while processing:
 couchdb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

It seems like the 5984 port in the couchdb.postinst script is hardcoded instead of being read from config files. I use a different (non-default) port for couch2. After changing this port in the postinst script (for now) it seems to complete successfully.

**Comment by wohali** [comment]
Thanks, this is good. I've opened apache/couchdb-pkg#18 for this. If you can help me with my questions over there, I'd appreciate it.

**Comment by wohali** [comment]
This has been worked around with: https://github.com/apache/couchdb-pkg/commit/066661ec8f0ab7b6e9258c89df695b06a0fe39cf

We don't try to extract the port (because a simple grep is challenging), but if we can't auto-create the system databases, we print a warning and tell you to do it yourself now.
