### ISSUE TITLE
Lost data from CouchDB

### ISSUE THREAD

**Issue by victor201801** [apache/couchdb#1099]
Couchdb lost its all databases.

## Test Case
For CouchDB 1.5.0
1. I created two databases.
2. I created four documents into each database
3. Exists an application that makes 50 request by day
4. The application didn't work because the couchDB's database is lost or it was deleted unexpectedly
5. I was enter to the  couchDB by browser and I did not find the databases.

## Your Environment

* Version used: CouchDB 1.5.0
* Browser Name and version: Google Chrome Versión 63
* Operating System and version (desktop or mobile):  Linux Ubuntu 14.04

**Comment by davisp** [comment]
Thanks for your report. CouchDB is not known to accidentally lose databases so I'm running on the assumption that something in your environment changed or you perhaps accidentally deleted them. Some things to check:

1. Did you restart CouchDB at any point? Perhaps it picked up a different configuration that changed where its storing databases?
2. If you remember either database name, can you try `locate dbname.couch` to see if those files exist somewhere?
3. Can you check your logs to see if there are any DELETE requests?

**Comment by victor201801** [comment]
Thanks for helping us.

## Answers:
1. We don't restart the CouchDB. This happened on three different servers at the same time.
2. We have recreated the database with the same name and _id.
3. There aren't the words DELETE in logs.

## Question and suggestion
1. You know if there is any configuration to autoclean by default in couchdb's config?
2. We have a screenshot when we lost the databases. [image-couchdb](https://www.dropbox.com/s/k9748rzpk07lhmi/Captura-couchdb-2.PNG?dl=0)

**Comment by penkeysuresh** [comment]
So for whatever it's worth, I went through the screenshot attached in the above issue and noticed that the 'Admin Party' is on. So theoretically anyone with the url could have went there and deleted the databases. @victor201801 you should check this out http://guide.couchdb.org/draft/security.html#party.

**Comment by wohali** [comment]
Since there has been no response from the requester in 30 days, I'm closing this out. Feel free to request a re-open should more information become available.
