### ISSUE TITLE
Build couchdb 2.1.1 fails because npm dependencies missing

### ISSUE THREAD

**Issue by orolle** [apache/couchdb#1102]
I need to build couchdb 2.1.1 to fix the huge security whole in my deployment. 
npm fails, because babel v7.0.0-beta.36 is not available via npm.
npm http 404 https://registry.npmjs.org/babel/code-frame/7.0.0-beta.36
npm http 404 https://registry.npmjs.org/babel/traverse/7.0.0-beta.36
npm http 404 https://registry.npmjs.org/babel/types/7.0.0-beta.36

## Expected Behavior
> ./configure && make release

Executing make should build couchdb.
 
## Current Behavior
Executing make fails.

```
...
Building Fauxton
npm WARN package.json couchapp@0.11.0 No repository field.
npm WARN package.json urls@0.0.4 No repository field.
npm http GET https://registry.npmjs.org/babel-eslint
npm http 304 https://registry.npmjs.org/babel-eslint
npm WARN engine babel-eslint@8.2.1: wanted: {"node":">=4"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm http GET https://registry.npmjs.org/babel/code-frame/7.0.0-beta.36
npm http GET https://registry.npmjs.org/babel/traverse/7.0.0-beta.36
npm http GET https://registry.npmjs.org/babel/types/7.0.0-beta.36
npm http GET https://registry.npmjs.org/babylon/7.0.0-beta.36
npm http GET https://registry.npmjs.org/eslint-scope
npm http GET https://registry.npmjs.org/eslint-visitor-keys
npm http 304 https://registry.npmjs.org/eslint-scope
npm http 304 https://registry.npmjs.org/babylon/7.0.0-beta.36
npm http 304 https://registry.npmjs.org/eslint-visitor-keys
npm http 404 https://registry.npmjs.org/babel/code-frame/7.0.0-beta.36
npm ERR! 404 'babel' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.13.0-137-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--production"
npm ERR! cwd /home/couchdb/couchdb-git/src/fauxton
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code E404
npm http 404 https://registry.npmjs.org/babel/traverse/7.0.0-beta.36
npm http 404 https://registry.npmjs.org/babel/types/7.0.0-beta.36
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/couchdb/couchdb-git/src/fauxton/npm-debug.log
npm ERR! not ok code 0
make: *** [share/www] Error 1
```

## Possible Solution
make babel v7.0.0-beta-36 available via npm.

## Steps to Reproduce (for bugs)
1. Follow the build and install instruction in the README
2. execute make fails.

## Context
Need to fix a security whole as soon as possible.

## Your Environment
* Version used: 2.1.1
* Operating System and version (desktop or mobile):desktop & server, ubuntu 14.04

**Comment by orolle** [comment]
Fix: remove `^` at version of babel packages from `src/fauxton/package.json `. In that way npm must match the babel versions exactly. `^1.2.3` means to match latest version compatible to version `1.2.3`. Removing `^` will match version `1.2.3` exactly.

**Comment by wohali** [comment]
"Please note that node.js and npm is required. Specifically, Fauxton requires at least Node 6 and npm 3."

From your paste:
```
npm WARN engine babel-eslint@8.2.1: wanted: {"node":">=4"} (current: {"node":"v0.10.25","npm":"1.3.10"})
```

https://github.com/apache/couchdb-fauxton/blob/master/readme.md
