### ISSUE TITLE
Running CouchDB 2 on the Raspberry Pi

### ISSUE THREAD

**Issue by ericclack** [apache/couchdb#1103]
Can I help get CouchDB working on the Raspberry Pi?

I've written a few small web apps on the Raspberry Pi using Couch 1.2, which came as part of the Weezy Raspbian repo - CouchDB was an easy choice because it was easy to install, was lightweight enough and had the right features. E.g.: https://github.com/ericclack/clojure-photo-bank

After upgrading to Raspbian Stretch I see that CouchDB is no longer in the Raspbian repo, and I can't work out how to build it without errors (Segmentation Faults, Illegal Instructions) -- see post here: https://raspberrypi.stackexchange.com/questions/77511/how-to-install-couchdb-2-on-raspberry-pi

I see from other GitHub posts that one of the problems is that you don't have an ARM computer to test your builds on. I can't donate a computer, but would be happy to donate some of my time to investigate and report problems on my Pi. 

I don't have any experience with Erlang, but do have a programming background (in Python, Clojure and many years ago C and C++), so I would probably need to pair with someone.

(Note: If I understand other posts correctly it may be that the problems are with Erlang or Rebar on the Pi, in which case I would be happy to follow that up with the right group.)

Let me know what you think...
-Eric.

**Comment by wohali** [comment]
Your StackExchange post makes it sound like Erlang isn't running correctly on your device - your error 139 is a segmentation fault. Without a RPi to test on, I can't help further.

Feel free to use this ticket to collect others who can help, or to describe any patches/changes required to get your build to work.

PRs welcome!

**Comment by ericclack** [comment]
From the blog posts I followed the recommendation was to install Erlang from packages.erlang-solutions.com, rather than the Raspian (Debian) repos. 

```
wget http://packages.erlang-solutions.com/debian/erlang_solutions.asc
sudo apt-key add erlang_solutions.asc
sudo apt-get update
sudo apt-get install -y erlang-nox erlang-dev erlang-reltool
sudo apt-get install -y build-essential
sudo apt-get install -y libmozjs185-1.0 libmozjs185-dev
sudo apt-get install -y libcurl4-openssl-dev libicu-dev 

```
So I think my first step is to try Erlang from Raspian and see if that makes a difference. 

If you can give me any advice on how to report the errors I see, and where to raise them (e.g. the Erlang team) that would be much appreciated.

Many thanks, 
-Eric.

**Comment by wohali** [comment]
The Erlang team won't take reports if they are packaging related. 

If you're fairly sure that you have an Erlang bug, you'll need to compile Erlang from scratch and reproduce it before reporting it.

https://github.com/erlang/otp/wiki/Bug-reports has the instructions on how to do it.

**Comment by ericclack** [comment]
A progress update: I've tried the Erlang version from the Debian Stretch repo and then installing CouchDB from source and all seems to work well, so perhaps there is a problem with the Erlang package from Erlang Solutions repository?

**Comment by janl** [comment]
Is there anything else we can do here? Please re-open if yes.

**Comment by ericclack** [comment]
No, nothing more needed. Many thanks for your help.
