### ISSUE TITLE
"rewrite" documentation has confusing headings

### ISSUE THREAD

**Issue by nkronlage** [apache/couchdb#1107]
http://docs.couchdb.org/en/2.1.1/api/ddoc/rewrites.html#rewrite-section-a-is-stringified-function

This page says 'Rewrite section a is stringified function'.  Is that supposed to be 'Rewrite section is a stringified function'?  

I'm also not sure what a 'section' is. Is that just the value of the rewrite field?

**Comment by wohali** [comment]
Please re-file this ticket over at https://github.com/apache/couchdb-documentation/issues , please :)

Right before that, it says: "The rewrite rules are defined in array or string field of the design document called rewrites." So, the two sections are referring to the differences between whether the rewrites key-value pair is an array or a string.

Any PR against apache/couchdb-documentation is welcome :)
