### ISSUE TITLE
Add multi-platform support to CI configuration

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#1121]
There are now requests for multi-platform support for CouchDB in our Docker images. As far as I'm aware, none of the CouchDB team regularly builds or runs CouchDB on any platform other than `amd64`, and in the past, `i386` (though we discourage `i386` use at this time).

As a prerequisite to us publishing any sort of alternative platform binaries, we need to be running our full CI workflow on those platforms on a regular basis.

The additional platforms being requested, in descending order of popularity, seem to be:

```
arm64v8
ppc64le
arm32v8
arm32v7
sparc
s390x
```

We have been warned by the Docker project that relying on `qemu` for emulation in a CI context is not recommended [[1]](https://github.com/docker-library/official-images/pull/3851#issuecomment-358507869), especially when compute resources are heavily constrained (as they are in Travis CI). So, ideally, we'd be doing this on Jenkins CI, which means we need real hardware donations, or we need partners like [WorksOnArm](https://www.worksonarm.com/).

As of 2018-01-22 the ASF has only `amd64` and `arm64v8` build platforms. The `ppc64le` build systems the ASF maintains are earmarked only for Hadoop build use.

## Expected Behaviour
CouchDB is tested on and runs correctly on a variety of hardware platforms.

## Current Behaviour
CouchDB is not tested on anything other than `amd64`.

## Context
At least one sister Apache project (OpenWhisk, incubating) has [requested `ppc64le` Docker images from the project](https://github.com/apache/couchdb-docker/pull/60). There has also been interest from the Docker project to add support for `arm32v7` support.

**Comment by sarveshtamba** [comment]
@wohali Tested CouchDB v2.3(current master) with Erlang v21 and Elixir v1.8 on **ppc64le**, the build completes successfully and the entire test suite executes successfully with no test failures. Please advise on the way forward/next steps to support CouchDB CI on ppc64le platform.

**Comment by wohali** [comment]
@sarveshtamba Thanks, we'll take this from here.

Now that we have multiplatform support in the CI file (for arm), we can close this.
