### ISSUE TITLE
Is the ID generate by CouchDB replication or map/reduce on _local database are configurable ?

### ISSUE THREAD

**Issue by olivenvrac** [apache/couchdb#1124]
## Context :
I have a mobile application using PouchDB that initiate a synchronisation whith a couchdb which reside in my intranet
I have a equipement (datapower) which filtering some caracters in the URL that coming from internet to my CouchDB instance.
the double dot (..) is in the filters rules.
The problem is that pouchdb try to get a document with this URI : http://url/mydatabase/_local/s85e4Fy_7zQP_oKC..7Ghw%3D%3D?&_nonce=1516643981622
which contain a double dot in the URI. So the Get does not work.
NB : The application does not create this ID docs and I think it is provide by the replication.
I read that the replication algorithm use _local to store checkpoints, and map/reduce uses them to keep track of what's been emit

## My questions: 
this ID is generated by Couchdb or PouchDB ?
is it configurable or not to prohibit the doucle dot ? I don't saw anything about this in the configuration file of CouchDB.

Thanks for your help.

## Possible Solution
modifie the filters rules of the "datapower"

## Your Environment

* Version used: CouchDB 2.0
* Browser Name and version: Google Chrome 61.0.3163.100
* Operating System and version (serveur : Linux RHEL7 and mobile : Iphone 6):

**Comment by wohali** [comment]
No, this is not something you can change. You will need to correct your "datapower" machine configuration.
