### ISSUE TITLE
CouchDb 2.1.1 can NOT create a View document

### ISSUE THREAD

**Issue by ToanP** [apache/couchdb#1133]
The latest  COuchDB 2.1.1 for MACOS can not create a simple view. 

## Expected Behavior

View Document worked well on CouchDB 2.1.0 but CouchDB 2.1.1. 
Here is log:

couchdb@localhost <0.882.0> -------- OS Process Error <0.25075.1> :: {os_process_error,{exit_status,134}}

## Steps to Reproduce (for bugs)

1. Create a Fruit dabase
2. Add some documents
{
    "_id" : "bc2a41170621c326ec68382f846d5764",
     "item" : "apple",
    "prices" : {
        "Fresh Mart" : 1.59,
        "Price Max" : 5.99,
        "Apples Express" : 0.79
    }
}
{
    "_id" : "bc2a41170621c326ec68382f846d5764",
     "item" : "orange",
    "prices" : {
        "Fresh Mart" : 1.99,
        "Price Max" : 3.19,
        "Citrus Circus" : 1.09
    }
}
{
    "_id" : "bc2a41170621c326ec68382f846d5764",
     "item" : "banana",
    "prices" : {
        "Fresh Mart" : 1.99,
        "Price Max" : 0.79,
        "Banana Montana" : 4.22
    }
}
3. Create a View from design document
function (doc) {
   var store, price, value;
    if (doc.item && doc.prices) {
        for (store in doc.prices) {
            price = doc.prices[store];
            value = [doc.item, store];
            emit(price, value);
        }
    }
}

4. Save Document and Build index

## Your Environment

* Version used: CouchDB 2.1.1
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): MACOS High Sierra
* Link to your project: NA

**Comment by ToanP** [comment]
Thank you nickva. I am using CouchDB2.1.0 and it works. I will check your downloadable zip when I am free.

Thanks again

**Comment by Crispy1975** [comment]
I would like to add to this issue, I am seeing the exact same issues, however I am running CouchDB 2.1.1 on Debian Jessie, as installed by the Apache repo at: [https://apache.bintray.com/couchdb-deb](https://apache.bintray.com/couchdb-deb)

The full version is: ` 2.1.1-1~jessie`

When views are created either via an application or via Fauxton this results in the following log:

```
[info] 2018-02-04T12:22:49.560045Z couchdb@127.0.0.1 <0.211.0> -------- couch_proc_manager <0.3865.0> died normal
[error] 2018-02-04T12:22:49.560146Z couchdb@127.0.0.1 <0.3195.0> -------- OS Process Error <0.3865.0> :: {os_process_error,"OS process timed out."}
[info] 2018-02-04T12:22:54.575971Z couchdb@127.0.0.1 <0.211.0> -------- couch_proc_manager <0.4000.0> died normal
[error] 2018-02-04T12:22:54.576041Z couchdb@127.0.0.1 <0.3195.0> -------- OS Process Error <0.4000.0> :: {os_process_error,"OS process timed out."}
[info] 2018-02-04T12:22:59.595031Z couchdb@127.0.0.1 <0.211.0> -------- couch_proc_manager <0.4087.0> died normal
[error] 2018-02-04T12:22:59.595142Z couchdb@127.0.0.1 <0.3195.0> -------- OS Process Error <0.4087.0> :: {os_process_error,"OS process timed out."}
[info] 2018-02-04T12:23:04.614970Z couchdb@127.0.0.1 <0.211.0> -------- couch_proc_manager <0.4175.0> died normal
[error] 2018-02-04T12:23:04.615046Z couchdb@127.0.0.1 <0.3195.0> -------- OS Process Error <0.4175.0> :: {os_process_error,"OS process timed out."}
[error] 2018-02-04T12:23:09.530943Z couchdb@127.0.0.1 <0.3193.0> -------- fabric_worker_timeout update_docs,'couchdb@127.0.0.1',<<"shards/80000000-9fffffff/test_accounts.1517357717">>
[notice] 2018-02-04T12:23:09.531226Z couchdb@127.0.0.1 <0.842.0> ab6dbafccb 127.0.0.1:59840 127.0.0.1 undefined PUT /test_accounts/_design/accounts 500 ok 60005
[info] 2018-02-04T12:23:09.633011Z couchdb@127.0.0.1 <0.211.0> -------- couch_proc_manager <0.4262.0> died normal
[error] 2018-02-04T12:23:09.633083Z couchdb@127.0.0.1 <0.3195.0> -------- OS Process Error <0.4262.0> :: {os_process_error,"OS process timed out."}
[info] 2018-02-04T12:23:14.654966Z couchdb@127.0.0.1 <0.211.0> -------- couch_proc_manager <0.4341.0> died normal
[error] 2018-02-04T12:23:14.655034Z couchdb@127.0.0.1 <0.3195.0> -------- OS Process Error <0.4341.0> :: {os_process_error,"OS process timed out."}
[info] 2018-02-04T12:23:19.672990Z couchdb@127.0.0.1 <0.211.0> -------- couch_proc_manager <0.4428.0> died normal
[error] 2018-02-04T12:23:19.673073Z couchdb@127.0.0.1 <0.3195.0> -------- OS Process Error <0.4428.0> :: {os_process_error,"OS process timed out."}
```

This results in processes spawning infinitely until CPU is used up and the machine grinds to a halt. Interestingly I also have a manual install of CouchDB 2.1.0-05d2e1e which does not suffer from this issue.

I feel like this is very similar to what is happening on the macOS version.

**Comment by wohali** [comment]
@Crispy1975 It's not.

The macOS bug is specifically related to a missing shared library, which was added in the 2.1.1.1 download. People were able to work around it successfully by installing the shared library using the `brew` tool on their own.

Your issue is that the view is taking too long to calculate. The default amount of time to wait for the external process is 5 seconds. That error, `{os_process_error,"OS process timed out."}` doesn't say the process couldn't run at all.

Try increasing the `[couchdb] os_process_timeout` value in your `local.ini` file to `10000` or higher. The value is in milliseconds.

**Comment by Crispy1975** [comment]
Many thanks for the reply @wohali I tried increasing the timeout value but to no avail. The DB is tiny, only 14 documents and 3 views. It's really odd that the error is triggering for such a small DB. As mentioned on a local machine with 2.1.0 (manual install) there are no issues. Are there any other areas I should perhaps investigate? Never had this error in the past.

**Comment by Crispy1975** [comment]
With the logs I then get what seems to be an infinite amount of processes spawning and taking up CPU time...

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND   
22711 couchdb   20   0  107340   4748   3236 R  62.1  0.0   0:05.39 ./bin/couchjs ./share/server/main.js                                                                                                          
22726 couchdb   20   0  108364   4752   3240 R  61.4  0.0   0:02.78 ./bin/couchjs ./share/server/main.js                                                                                                          
22618 couchdb   20   0  107344   4752   3236 R  58.0  0.0   0:29.20 ./bin/couchjs ./share/server/main.js                                                                                                          
22621 couchdb   20   0  108364   4752   3236 R  58.0  0.0   0:24.80 ./bin/couchjs ./share/server/main.js                                                                                                          
22629 couchdb   20   0  108364   4748   3232 R  58.0  0.0   0:19.61 ./bin/couchjs ./share/server/main.js                                                                                                          
22628 couchdb   20   0  107344   4748   3236 R  56.7  0.0   0:19.30 ./bin/couchjs ./share/server/main.js                                                                                                          
22622 couchdb   20   0  107348   4748   3232 R  56.0  0.0   0:24.52 ./bin/couchjs ./share/server/main.js                                                                                                          
22654 couchdb   20   0  107344   4756   3236 R  56.0  0.0   0:14.07 ./bin/couchjs ./share/server/main.js                                                                                                          
22727 couchdb   20   0  106316   4744   3236 R  56.0  0.0   0:02.39 ./bin/couchjs ./share/server/main.js                                                                                                          
22617 couchdb   20   0  106316   4748   3232 R  54.7  0.0   0:29.46 ./bin/couchjs ./share/server/main.js                                                                                                          
22695 couchdb   20   0  107340   4744   3236 R  54.0  0.0   0:09.09 ./bin/couchjs ./share/server/main.js                                                                                                          
22696 couchdb   20   0  108368   4748   3236 R  52.6  0.0   0:09.24 ./bin/couchjs ./share/server/main.js                                                                                                          
22710 couchdb   20   0  108364   4752   3240 R  52.0  0.0   0:05.35 ./bin/couchjs ./share/server/main.js
```

**Comment by Crispy1975** [comment]
Even the view check from the verify installation option causes the timeout. Might need to roll back to 2.1.0, but would prefer to use the latest version.

**Comment by wohali** [comment]
Try running `couchjs` by hand and see if it works. You can also try `ldd /path/to/couchjs` and validate that all of the shared libraries are installed correctly.

**Comment by matt-jarrett** [comment]
I'm seeing this problem too. I'm on 2.1.1 on Mac 10.13.3

Any update?

**Comment by wohali** [comment]
@matt-jarrett Have you tried the 2.1.1-1.zip download that was uploaded and updated in January of this year?

**Comment by matt-jarrett** [comment]
I put in a request to get that software. It sounds like that will fix the trouble I'm seeing.

**Comment by rvaldepenas** [comment]
I'm not sure if this is the correct place to request help on CouchDB2.0. We have a server that replicates several dbases to other servers. It appears that one of the dbases that has attachments, doesn't replicate and the error log doesn't help: Here's what I see on the target server:
[notice] 2019-07-30T21:59:32.046000Z couchdb@localhost <0.4194.1> f44aa67d54 targetServer:5984 10.57.170.117 undefined PUT /lists/sites%2Fhotel%2Ffoodandbeverage.southern-europe.249.json?new_edits=false 500 ok 24
[error] 2019-07-30T21:59:32.059000Z couchdb@localhost <0.4209.1> ecbb156525 req_err(3685245358) badmatch : ok

**Comment by rvaldepenas** [comment]
Can you help me with this issue?
I'm not sure if this is the correct place to request help on CouchDB2.0. We have a server that replicates several dbases to other servers. It appears that one of the dbases that has attachments, doesn't replicate and the error log doesn't help: Here's what I see on the target server:
[notice] 2019-07-30T21:59:32.046000Z couchdb@localhost <0.4194.1> f44aa67d54 targetServer:5984 10.57.170.117 undefined PUT /lists/sites%2Fhotel%2Ffoodandbeverage.southern-europe.249.json?new_edits=false 500 ok 24
[error] 2019-07-30T21:59:32.059000Z couchdb@localhost <0.4209.1> ecbb156525 req_err(3685245358) badmatch : ok

**Comment by wohali** [comment]
@rvaldepenas Please don't hijack this issue - you can create a new one, but better yet:

If you are looking for general support with using CouchDB, please try one of these other options:

* The user mailing list. Signup instructions are [here](http://couchdb.apache.org/#mailing-lists)
* The Slack/IRC chat room. Joining instructions are [here](http://couchdb.apache.org/#chat)

**Comment by rvaldepenas** [comment]
Thank you.
I don’t think I see instructions on how to sign up for posting questions on CouchDB from the “here” link sent to me below.


  *   The user mailing list. Signup instructions are here<https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fcouchdb.apache.org%2F%23mailing-lists&data=02%7C01%7Crvaldepenas%40hollandamericagroup.com%7C904f6d58828a4081ab3308d715714aea%7C9e37b9e905de4906b089536f19689074%7C0%7C0%7C637001448639687723&sdata=6pBZzLKTf4icN5jpSL0f%2BgKAakqX%2FXplqNWHJke9so0%3D&reserved=0>
  *   The Slack/IRC chat room. Joining instructions are here<https://nam02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fcouchdb.apache.org%2F%23chat&data=02%7C01%7Crvaldepenas%40hollandamericagroup.com%7C904f6d58828a4081ab3308d715714aea%7C9e37b9e905de4906b089536f19689074%7C0%7C0%7C637001448639697714&sdata=rcDlRCvUg5NZDE4casPhCSvDfCDaic%2BFhTQEi1FzeQA%3D&reserved=0>

Thanks,

[cid:_1_0B56DEE40B56DC78000574A188257E67]
Rolando Valdepeñas
SharePoint Administrator/Developer | Holland America Group
Phone: 206-626-7556. Email: rvaldepenas@hollandamericagroup.com<mailto:rvaldepenas@hollandamericagroup.com>

**Comment by wohali** [comment]
Click the "Subscribe" list next to "User List" and subscribe to the list. Then you can email to it with your question.
