### ISSUE TITLE
Execution of queries takes a lot of time

### ISSUE THREAD

**Issue by PascalPuchtler** [apache/couchdb#1137]
In my database I like to run requests data over a view. After the Request the database takes a long time to update the index, but the index has no changes. This takes about 6 minutes.
When the index is ready the execution of the reduce step takes about 1 minute.

## Expected Behavior
The index schoul only update if changes happened or should be everytime up to date.
The request should execute faster.

## Current Behavior
The index updates when no changes happened.
The request should execute very long.

## Possible Solution
No Idea.

## Steps to Reproduce (for bugs)
Its not so easy, because of the "big" amount of data.

## Context
**Request:**
    "ids": {
      "map": "function (doc) {    emit([doc.Header.Serialnumber, doc.Header.Parameter, doc.Header.Time],1);  }",
      "reduce": "_count"
    }

**Data:**
The size of the database is 5GB with 100k documents.

## Your Environment

* Version used: v2.1.1
* Browser Name and version: Firefox 52.1.2 (64-Bit)
* Operating System and version (desktop or mobile): Windows 10 Enterprise 2015 LTSB
* CPU: Intel i5
* RAM: 16GB

**Comment by wohali** [comment]
Changing a design document (the definition of a "map" or a "reduce") will force a recalculation of the index on the next time you access that view. CouchDB determines if the definition has changed by performing a checksum on _the entire design document_.

On subsequent accesses to the index (without updating the design document) access should be rapid.

If you need many different kinds of map or reduce functions, add additional views to the same design document, or create multiple design documents.
