### ISSUE TITLE
Different replication recovery scenarios 

### ISSUE THREAD

**Issue by sajeeval** [apache/couchdb#1138]
Hello,

I just want to understand the difference in replication recovery mechanisms (Unidirectional) for following three scenarios. 

1. Replication fails due to a network failure. Master gets updated during the network outage. Network connectivity is back after **1 hour**; 
- Does replication resume where it left off? How it finds where it should start from? If the master was highly active and there were lot of changes, does the replication starts from the beginning or it just resumes? 

2. If the network outage is 1 day
- Does the replication resume, or restart from the scratch (copy whole database)? 

3. Stop couchdb slave. Upgrade OS. Upgrade couchdb version. Start couch service
- Does the replication resume or restart (start from the beginning) ?

Actually we have couchdb instances which are significantly large in size. So it is important for us to know what happens for above scenarios. I think if the replication restarts from the scratch (without resuming ) resource utilization would be much higher; which is not preferred. 

Thank you.
Sajeeva

**Comment by wohali** [comment]
This is not a bug report.

In the future, please take these sorts of requests to our IRC/Slack channel, or to our user mailing list. Information on both is available at https://couchdb.apache.org/ .

1. Yes, replication resumes based on private "checkpoint documents" the replicator stores. It doesn't matter if there were a lot of new changes or not.
1. Same thing.
1. Same thing.

Try it yourself! It's an easy thing to experiment with.
