### ISSUE TITLE
compaction damon died, strategy to restart?

### ISSUE THREAD

**Issue by obi458** [apache/couchdb#1140]
[error] 2018-02-02T10:11:08.207000Z couchdb@localhost <0.9294.0> -------- gen_server couch_compaction_daemon terminated with reason: {compaction_loop_died,{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{...},...]},...]}}
  last msg: {'EXIT',<0.9296.0>,{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{file,"src/couch_db.erl"},{line,1284}]},{couch_compaction_daemon,db_ddoc_names,1,[{file,"src/couch_compaction_daemon.erl"},{line,239}]}]}}
     state: {state,<0.9296.0>,[]}
[error] 2018-02-02T10:11:08.207000Z couchdb@localhost <0.9294.0> -------- CRASH REPORT Process couch_compaction_daemon (<0.9294.0>) with 0 neighbors exited with reason: {compaction_loop_died,{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{...},...]},...]}} at gen_server:terminate/7(line:826) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_compaction_daemon,init,['Argument__1']}, ancestors: [couch_secondary_services,couch_sup,<0.198.0>], messages: [], links: [<0.8590.0>], dictionary: [], trap_exit: true, status: running, heap_size: 1598, stack_size: 27, reductions: 7336
[error] 2018-02-02T10:11:08.207000Z couchdb@localhost <0.8590.0> -------- Supervisor couch_secondary_services had child compaction_daemon started with couch_compaction_daemon:start_link() at <0.9294.0> exit with reason {compaction_loop_died,{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{...},...]},...]}} in context child_terminated
[error] 2018-02-02T10:11:08.254000Z couchdb@localhost emulator -------- Error in process <0.9308.0> on node couchdb@localhost with exit value:
{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{file,"src/couch_db.erl"},{line,1284}]},{couch_compaction_daemon,db_ddoc_names,1,[{file,"src/couch_compaction_daemon.erl"},{line,239}]}]}

[error] 2018-02-02T10:11:08.254000Z couchdb@localhost <0.9306.0> -------- gen_server couch_compaction_daemon terminated with reason: {compaction_loop_died,{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{...},...]},...]}}
  last msg: {'EXIT',<0.9308.0>,{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{file,"src/couch_db.erl"},{line,1284}]},{couch_compaction_daemon,db_ddoc_names,1,[{file,"src/couch_compaction_daemon.erl"},{line,239}]}]}}
     state: {state,<0.9308.0>,[]}
[error] 2018-02-02T10:11:08.254000Z couchdb@localhost <0.9306.0> -------- CRASH REPORT Process couch_compaction_daemon (<0.9306.0>) with 0 neighbors exited with reason: {compaction_loop_died,{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{...},...]},...]}} at gen_server:terminate/7(line:826) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_compaction_daemon,init,['Argument__1']}, ancestors: [couch_secondary_services,couch_sup,<0.198.0>], messages: [], links: [<0.8590.0>], dictionary: [], trap_exit: true, status: running, heap_size: 1598, stack_size: 27, reductions: 7340
[error] 2018-02-02T10:11:08.254000Z couchdb@localhost <0.8590.0> -------- Supervisor couch_secondary_services had child compaction_daemon started with couch_compaction_daemon:start_link() at <0.9306.0> exit with reason {compaction_loop_died,{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{...},...]},...]}} in context child_terminated
[error] 2018-02-02T10:11:08.317000Z couchdb@localhost emulator -------- Error in process <0.9320.0> on node couchdb@localhost with exit value:
{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{file,"src/couch_db.erl"},{line,1284}]},{couch_compaction_daemon,db_ddoc_names,1,[{file,"src/couch_compaction_daemon.erl"},{line,239}]}]}

[error] 2018-02-02T10:11:08.317000Z couchdb@localhost <0.9318.0> -------- gen_server couch_compaction_daemon terminated with reason: {compaction_loop_died,{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{...},...]},...]}}
  last msg: {'EXIT',<0.9320.0>,{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{file,"src/couch_db.erl"},{line,1284}]},{couch_compaction_daemon,db_ddoc_names,1,[{file,"src/couch_compaction_daemon.erl"},{line,239}]}]}}
     state: {state,<0.9320.0>,[]}
[error] 2018-02-02T10:11:08.317000Z couchdb@localhost <0.9318.0> -------- CRASH REPORT Process couch_compaction_daemon (<0.9318.0>) with 0 neighbors exited with reason: {compaction_loop_died,{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{...},...]},...]}} at gen_server:terminate/7(line:826) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_compaction_daemon,init,['Argument__1']}, ancestors: [couch_secondary_services,couch_sup,<0.198.0>], messages: [], links: [<0.8590.0>], dictionary: [], trap_exit: true, status: running, heap_size: 1598, stack_size: 27, reductions: 7336
[error] 2018-02-02T10:11:08.317000Z couchdb@localhost <0.8590.0> -------- Supervisor couch_secondary_services had child compaction_daemon started with couch_compaction_daemon:start_link() at <0.9318.0> exit with reason {compaction_loop_died,{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{...},...]},...]}} in context child_terminated
[error] 2018-02-02T10:11:08.379000Z couchdb@localhost emulator -------- Error in process <0.9332.0> on node couchdb@localhost with exit value:
{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{file,"src/couch_db.erl"},{line,1284}]},{couch_compaction_daemon,db_ddoc_names,1,[{file,"src/couch_compaction_daemon.erl"},{line,239}]}]}

[error] 2018-02-02T10:11:08.379000Z couchdb@localhost <0.9330.0> -------- gen_server couch_compaction_daemon terminated with reason: {compaction_loop_died,{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{...},...]},...]}}
  last msg: {'EXIT',<0.9332.0>,{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{file,"src/couch_db.erl"},{line,1284}]},{couch_compaction_daemon,db_ddoc_names,1,[{file,"src/couch_compaction_daemon.erl"},{line,239}]}]}}
     state: {state,<0.9332.0>,[]}
[error] 2018-02-02T10:11:08.379000Z couchdb@localhost <0.9330.0> -------- CRASH REPORT Process couch_compaction_daemon (<0.9330.0>) with 0 neighbors exited with reason: {compaction_loop_died,{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{...},...]},...]}} at gen_server:terminate/7(line:826) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_compaction_daemon,init,['Argument__1']}, ancestors: [couch_secondary_services,couch_sup,<0.198.0>], messages: [], links: [<0.8590.0>], dictionary: [], trap_exit: true, status: running, heap_size: 1598, stack_size: 27, reductions: 7336
[error] 2018-02-02T10:11:08.379000Z couchdb@localhost <0.8590.0> -------- Supervisor couch_secondary_services had child compaction_daemon started with couch_compaction_daemon:start_link() at <0.9330.0> exit with reason {compaction_loop_died,{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{...},...]},...]}} in context child_terminated
[error] 2018-02-02T10:11:08.442000Z couchdb@localhost emulator -------- Error in process <0.9344.0> on node couchdb@localhost with exit value:
{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{file,"src/couch_db.erl"},{line,1284}]},{couch_compaction_daemon,db_ddoc_names,1,[{file,"src/couch_compaction_daemon.erl"},{line,239}]}]}

[error] 2018-02-02T10:11:08.442000Z couchdb@localhost <0.9342.0> -------- gen_server couch_compaction_daemon terminated with reason: {compaction_loop_died,{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{...},...]},...]}}
  last msg: {'EXIT',<0.9344.0>,{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{file,"src/couch_db.erl"},{line,1284}]},{couch_compaction_daemon,db_ddoc_names,1,[{file,"src/couch_compaction_daemon.erl"},{line,239}]}]}}
     state: {state,<0.9344.0>,[]}
[error] 2018-02-02T10:11:08.442000Z couchdb@localhost <0.9342.0> -------- CRASH REPORT Process couch_compaction_daemon (<0.9342.0>) with 0 neighbors exited with reason: {compaction_loop_died,{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{...},...]},...]}} at gen_server:terminate/7(line:826) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_compaction_daemon,init,['Argument__1']}, ancestors: [couch_secondary_services,couch_sup,<0.198.0>], messages: [], links: [<0.8590.0>], dictionary: [], trap_exit: true, status: running, heap_size: 1598, stack_size: 27, reductions: 7336
[error] 2018-02-02T10:11:08.442000Z couchdb@localhost <0.8590.0> -------- Supervisor couch_secondary_services had child compaction_daemon started with couch_compaction_daemon:start_link() at <0.9342.0> exit with reason {compaction_loop_died,{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{...},...]},...]}} in context child_terminated
[error] 2018-02-02T10:11:08.536000Z couchdb@localhost <0.9354.0> -------- gen_server couch_compaction_daemon terminated with reason: {compaction_loop_died,{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{...},...]},...]}}
  last msg: {'EXIT',<0.9357.0>,{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{file,"src/couch_db.erl"},{line,1284}]},{couch_compaction_daemon,db_ddoc_names,1,[{file,"src/couch_compaction_daemon.erl"},{line,239}]}]}}
     state: {state,<0.9357.0>,[]}
[error] 2018-02-02T10:11:08.536000Z couchdb@localhost <0.9354.0> -------- CRASH REPORT Process couch_compaction_daemon (<0.9354.0>) with 0 neighbors exited with reason: {compaction_loop_died,{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{...},...]},...]}} at gen_server:terminate/7(line:826) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_compaction_daemon,init,['Argument__1']}, ancestors: [couch_secondary_services,couch_sup,<0.198.0>], messages: [], links: [<0.8590.0>], dictionary: [], trap_exit: true, status: running, heap_size: 1598, stack_size: 27, reductions: 7336
[error] 2018-02-02T10:11:08.536000Z couchdb@localhost <0.8590.0> -------- Supervisor couch_secondary_services had child compaction_daemon started with couch_compaction_daemon:start_link() at <0.9354.0> exit with reason {compaction_loop_died,{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{...},...]},...]}} in context child_terminated
[error] 2018-02-02T10:11:08.536000Z couchdb@localhost <0.8590.0> -------- Supervisor couch_secondary_services had child compaction_daemon started with couch_compaction_daemon:start_link() at <0.9354.0> exit with reason reached_max_restart_intensity in context shutdown
[error] 2018-02-02T10:11:08.536000Z couchdb@localhost emulator -------- Error in process <0.9357.0> on node couchdb@localhost with exit value:
{{badmatch,{error,corrupted_data}},[{couch_compress,decompress,1,[{file,"src/couch_compress.erl"},{line,65}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,158}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,stream_node,8,[{file,"src/couch_btree.erl"},{line,751}]},{couch_btree,stream_kp_node,8,[{file,"src/couch_btree.erl"},{line,819}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_db,enum_docs,5,[{file,"src/couch_db.erl"},{line,1284}]},{couch_compaction_daemon,db_ddoc_names,1,[{file,"src/couch_compaction_daemon.erl"},{line,239}]}]}

[error] 2018-02-02T10:11:08.536000Z couchdb@localhost <0.8690.0> -------- gen_server <0.8690.0> terminated with reason: killed
  last msg: {'EXIT',<0.8688.0>,killed}
     state: {st,<0.8688.0>,couch_mrview_index,nil}
[error] 2018-02-02T10:11:08.536000Z couchdb@localhost <0.8690.0> -------- CRASH REPORT Process  (<0.8690.0>) with 0 neighbors exited with reason: killed at gen_server:terminate/7(line:826) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_index_updater,init,['Argument__1']}, ancestors: [<0.8688.0>,<0.8687.0>], messages: [], links: [], dictionary: [], trap_exit: true, status: running, heap_size: 610, stack_size: 27, reductions: 484
[error] 2018-02-02T10:11:08.536000Z couchdb@localhost <0.8675.0> -------- gen_server <0.8675.0> terminated with reason: killed
  last msg: {'EXIT',<0.8672.0>,killed}
     state: {st,<0.8672.0>,couch_mrview_index,undefined}
[error] 2018-02-02T10:11:08.536000Z couchdb@localhost <0.8675.0> -------- CRASH REPORT Process  (<0.8675.0>) with 0 neighbors exited with reason: killed at gen_server:terminate/7(line:826) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_index_compactor,init,['Argument__1']}, ancestors: [<0.8672.0>,<0.8671.0>], messages: [], links: [], dictionary: [], trap_exit: true, status: running, heap_size: 610, stack_size: 27, reductions: 492
[error] 2018-02-02T10:11:08.536000Z couchdb@localhost <0.8674.0> -------- gen_server <0.8674.0> terminated with reason: killed
  last msg: {'EXIT',<0.8672.0>,killed}
     state: {st,<0.8672.0>,couch_mrview_index,nil}
[error] 2018-02-02T10:11:08.536000Z couchdb@localhost <0.8691.0> -------- gen_server <0.8691.0> terminated with reason: killed
  last msg: {'EXIT',<0.8688.0>,killed}
     state: {st,<0.8688.0>,couch_mrview_index,undefined}
[error] 2018-02-02T10:11:08.536000Z couchdb@localhost <0.8674.0> -------- CRASH REPORT Process  (<0.8674.0>) with 0 neighbors exited with reason: killed at gen_server:terminate/7(line:826) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_index_updater,init,['Argument__1']}, ancestors: [<0.8672.0>,<0.8671.0>], messages: [], links: [], dictionary: [], trap_exit: true, status: running, heap_size: 610, stack_size: 27, reductions: 500
[error] 2018-02-02T10:11:08.536000Z couchdb@localhost <0.8691.0> -------- CRASH REPORT Process  (<0.8691.0>) with 0 neighbors exited with reason: killed at gen_server:terminate/7(line:826) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_index_compactor,init,['Argument__1']}, ancestors: [<0.8688.0>,<0.8687.0>], messages: [], links: [], dictionary: [], trap_exit: true, status: running, heap_size: 610, stack_size: 27, reductions: 504
[error] 2018-02-02T10:11:08.536000Z couchdb@localhost <0.8683.0> -------- gen_server <0.8683.0> terminated with reason: killed
  last msg: {'EXIT',<0.8680.0>,killed}
     state: {st,<0.8680.0>,couch_mrview_index,undefined}
[error] 2018-02-02T10:11:08.536000Z couchdb@localhost <0.8682.0> -------- gen_server <0.8682.0> terminated with reason: killed
  last msg: {'EXIT',<0.8680.0>,killed}
     state: {st,<0.8680.0>,couch_mrview_index,nil}
[error] 2018-02-02T10:11:08.536000Z couchdb@localhost <0.8682.0> -------- CRASH REPORT Process  (<0.8682.0>) with 0 neighbors exited with reason: killed at gen_server:terminate/7(line:826) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_index_updater,init,['Argument__1']}, ancestors: [<0.8680.0>,<0.8679.0>], messages: [], links: [], dictionary: [], trap_exit: true, status: running, heap_size: 610, stack_size: 27, reductions: 468
[error] 2018-02-02T10:11:08.536000Z couchdb@localhost <0.8683.0> -------- CRASH REPORT Process  (<0.8683.0>) with 0 neighbors exited with reason: killed at gen_server:terminate/7(line:826) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_index_compactor,init,['Argument__1']}, ancestors: [<0.8680.0>,<0.8679.0>], messages: [], links: [], dictionary: [], trap_exit: true, status: running, heap_size: 610, stack_size: 27, reductions: 516
[error] 2018-02-02T10:11:08.551000Z couchdb@localhost <0.199.0> -------- Supervisor couch_sup had child couch_secondary_services started with couch_secondary_sup:start_link() at <0.8590.0> exit with reason shutdown in context child_terminated
[error] 2018-02-02T10:11:08.551000Z couchdb@localhost <0.199.0> -------- Supervisor couch_sup had child couch_secondary_services started with couch_secondary_sup:start_link() at <0.8590.0> exit with reason reached_max_restart_intensity in context shutdown
[error] 2018-02-02T10:11:08.551000Z couchdb@localhost <0.470.0> -------- Supervisor received unexpected message: {'DOWN',#Ref<0.0.2.515>,process,<0.540.0>,killed}

[info] 2018-02-02T10:11:08.551000Z couchdb@localhost <0.7.0> -------- Application couch exited with reason: shutdown
[error] 2018-02-02T10:11:08.567000Z couchdb@localhost <0.1657.0> -------- gen_server <0.1657.0> terminated with reason: killed
  last msg: {'EXIT',<0.548.0>,killed}
     state: {state,106596,couch_replicator_doc_processor,nil,<<"_replicator">>,#Ref<0.0.2.14649>,nil,[],true}
[error] 2018-02-02T10:11:08.567000Z couchdb@localhost <0.1657.0> -------- CRASH REPORT Process  (<0.1657.0>) with 0 neighbors exited with reason: killed at gen_server:terminate/7(line:826) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_multidb_changes,init,['Argument__1']}, ancestors: [<0.548.0>,couch_replicator_sup,<0.465.0>], messages: [], links: [], dictionary: [], trap_exit: true, status: running, heap_size: 4185, stack_size: 27, reductions: 6552

**Comment by wohali** [comment]
Your error log says: `{error,corrupted_data}`. Your on-disk data is corrupted.

This is not a CouchDB error. You should restore from backup.
