### ISSUE TITLE
Inconsistent sum and sumsqr aggregates of floating point numbers

### ISSUE THREAD

**Issue by arekdygas** [apache/couchdb#1152]
## Expected Behavior
Running a query with reduce against a view should always return the same aggregated value, if involved documents values didn't change.

Assuming we have four documents containing property with following values: -0.2, -0.1, 0.1, 0.2, then running _sum_ against these values should always return 0.0 (or other floating point number close to 0.0, but always the same).

## Current Behavior
Aggregated values for _sum_ and _sumsqr_ might give different results on multiple view queries.

For sample document values -0.2, -0.1, 0.1, 0.2, returned sum is one of the following:
-0.0000000000000000277555756156
0
0.0000000000000000277555756156

## Possible Solution
I don't know how it works internally, so no idea.

## Steps to Reproduce (for bugs)
1. Create new database _aaa_
2. Create design document:
```
{
  "_id": "_design/dd",
  "views": {
    "v": {
      "reduce": "_sum",
      "map": "function (doc) {\n  emit(doc._id, doc.num);\n}"
    }
  },
  "language": "javascript"
}
```
3. Add two documents with `num` property. For first document set it to -0.1, for second to 0.1.
4. Execute http://127.0.0.1:5984/aaa/_design/dd/_view/v?reduce=true a few times. Result should be always 0 (which is ok)
5. Add next 2 documents, this time with `num` set to -0.2 and 0.2
6. Execute above query again, after some tries two non 0 value should be returned.
7. Add next 2 documents (-0.3, 0.3). Running a query might now return four non-zero values.
8. Modify design document, by replacing `emit(doc._id, doc.num)` with `emit(doc._id, doc.num + 1.0)`.
9. Execute query again. 6 will be returned all the times (which is ok).
10. Modify design document, by replacing `emit(doc._id, doc.num + 1.0)` with `emit(doc._id, doc.num + 0.0)`.
11. Execute query again. Results are the same as in point 7.
12. Delete all documents except single one (doesn't matter which) and modify design doc by replacing `emit(doc._id, doc.num + 0.0)` with
```
emit("-3", -0.3);
emit("-2", -0.2);
emit("-1", -0.1);
emit("1", 0.1);
emit("2", 0.2);
emit("3", 0.3);
```
13. Execute query again. The returned value will always be the same (for me it was -2.7755575615628914e-17).

As a side note: I created documents with `num` property from within Fauxton, leaving their default _id. When I did this again, this time creating documents with custom _id ("1" for num 0.1, "-1" for -0.1, "2" for 0.2, etc.), the results were different. For example, in p. 7 above, I got eight non-zero results instead of four...

## Context
I'm trying to get consistent data on each request, without having to round the values returned. Additionally, seeing these aggregates changing on subsequent request makes me worrying, if it doesn't mean there's something wrong with aggregate index persistence...

## Your Environment
* Version used: tested on 2.1.1 (custom build) and 2.1.1 (official installer); also tested on CouchDB 1.5.1 and Cloudant - in both cases this works as expected (always return the same value)
* Browser Name and version: Chrome 63.0.3239.132
* Operating System and version (desktop or mobile): Windows 7 Pro SP1; Windows Server 2012 R2 Standard
* Link to your project: ---

Best regards,
Arek

**Comment by arekdygas** [comment]
I did additional tests, and found out that this behaviour is due to sharding, even for a single node setup. For single node with one shard this works as expected.

If I'm correct, and this is by design, then please close the issue.

**Comment by rnewson** [comment]
clustered map/reduce definitely works in couchdb 2.x so there's something curious here. Can you retry with integers just in case we're in some funky IEEE 754 area?

**Comment by arekdygas** [comment]
Integers work ok in CouchDB 2.1.1 (single node with 8 shards).

Out of curiosity I did some tests in JS engine used by Chrome:
-0.1-0.2+0.1+0.2 = -2.7755575615628914e-17
0.1+0.2-0.1-0.2 = 2.7755575615628914e-17
other combinations = 0

which are exact results from my test case.

I don't really know how CouchDB internally works, but I think it reads aggregates from shards and then calculates final aggregate. That would explain this issue, if shards results are returned in random order. But it looks that in Cloudant they are always returned in the same order, making the result the same across multiple requests.

**Comment by nickva** [comment]
Floating point numbers, as most languages implement them, are not associative. That is a+(b+c) doesn't equal to (a+b)+c. 

Printing the number is not enough, it's best to do the comparison:

Python
```
In [1]: x = -0.1-0.2+0.1+0.2
In [2]: y = 0.1+0.2-0.1-0.2
In [3]: x == y
Out[3]: False
```

JS (Chrome Dev Console)
```
x = -0.1-0.2+0.1+0.2
-2.7755575615628914e-17
y = 0.1+0.2-0.1-0.2
2.7755575615628914e-17
x == y
false
```

The sum is a reducer in this case. For it to work properly the operation has to be associative, such that it doesn't matter what order the keys are presented to it, it will produce the same result. Or, alternatively, the keys always have to be presented in the same order.

Notice that with q=1,n=1 or in CouchDB 1.x the second part is true, the keys are processed in the same order (but you don't get any benefits of sharding).

**Comment by rnewson** [comment]
cloudant's clustered reduce is line for line the same as couchdb's. I suspect you got lucky and that each copy of the shard has the same ordering. plausible given how few documents are in play.

**Comment by arekdygas** [comment]
That might be the case. I'll do some additional tests tomorrow, with more documents and will post the results.

Out of curiosity. Under this link:
https://quabase.sei.cmu.edu/mediawiki/index.php/CouchDB_Data_Distribution_Features
I found out the following info:

> Merging Query Results from Multiple Shards: When a query returns multiple data objects from multiple shards, the query coordinator in the database must somehow merge the results and return them to the requesting clients. Different databases offer different capabilities to clients when performing this result set merge, including options for sorting of results and returning the complete results in pages or as a whole. In CouchDB, the following options are available: sorted order, not supported.

Is this info valid? If yes, then is there any official doc I can read about these options?

**Comment by wohali** [comment]
No clue what they're on about there, sorry.

All options for view result sorting/etc are [here](http://docs.couchdb.org/en/latest/api/ddoc/views.html#db-design-design-doc-view-view-name). It doesn't matter if you have 1 shard or 192, the options are the same.

**Comment by arekdygas** [comment]
After additional tests I was able to reproduce this in Cloudant, so I can confirm this is related to reading data from shards in random order. Switching to q=1 is perfectly ok for me, so that's my workaround.

I'm leaving the issue open, because I don't know if the shards random read order is intended or not. If yes, then please close it.

Thank you all for your insights!

**Comment by wohali** [comment]
Intentional.
