### ISSUE TITLE
win msi download identified as virus by Kaspersky Labs 

### ISSUE THREAD

**Issue by unruledboy** [apache/couchdb#1154]
From the official website: http://couchdb.apache.org/

Download "Windows (x64)": https://dl.bintray.com/apache/couchdb/win/2.1.1/couchdb-2.1.1.msi

Our security software stopped the msi file because it says:

CAS (Version 1.3.7.5(201666)) - http://www.bluecoat.com 
Antivirus Vendor: Kaspersky Labs 
Scan Engine Version: 8.2.5.17 
Pattern File Version: 180208 (Timestamp: 2018/02/08) 

Virus/PUS: "PUS:RiskTool.Win64.NSSM.a" found! 
URL: https://akamai.bintray.com/8b/8bcb072593d089a2bf7ee9cae04451dcd15170123c27b8253217753f8b496088?__gda__=exp=1518047289~hmac=ed2f622acbadfde14cff2ae24e5dbfa6983c3915c42e90b26887b25e6ef5d7f4&response-content-disposition=attachment%3Bfilename%3D%22couchdb-2.1.1.msi%22&response-content-type=application%2Fx-ms-installer&requestInfo=U2FsdGVkX19qAp7j7ycQNtVQ-5ZRlWOr6qelO-L-QeXC-mUSCoH0q3BBtjQG1_h1aYAmaVQPEw6ejiYJy0U7I-1W9edMC8VFv_13K9HXz-PI1QwMNugnUwderWf55kH2&response-X-Checksum-Sha1=a64c55f3b317209b0b396f9964c06f64aec29491&response-X-Checksum-Sha2=8bcb072593d089a2bf7ee9cae04451dcd15170123c27b8253217753f8b496088

**Comment by wohali** [comment]
False positive - we use NSSM legitimately.

Please report this to Kaspersky Labs, not us.

**Comment by dch** [comment]
On Thu, 8 Feb 2018, at 04:51, Joan Touzet wrote:
> Closed #1154.

FWIW I submitted this as a false positive to Kapersky, and now we come up clean again:

The link https://dl.bintray.com/apache/couchdb/win/2.1.1/couchdb-2.1.1.msi is safe according to the reputation data of Kaspersky VirusDesk.
—
  Dave Cottlehuber
  dch@apache.org
  Sent from my Couch

**Comment by gambolputty** [comment]
In case anybody has the same issue: also "GDATA Internet Security" has a problem with the file "nssm.exe" inside the `C:\CouchDB\bin` folder and recognizes it as Junkware. I submitted it as a false positive to GDATA.
