### ISSUE TITLE
shared secrete for proxy authentication

### ISSUE THREAD

**Issue by gramsa49** [apache/couchdb#1174]
Extend CouchDB to allow for the use of a shared secret to authenticate external proxies that provide authentication services to CouchDB consumers via proxy based authentication.

## Expected Behavior
This enhancement allows the authenticating proxy to authenticate itself to CouchDB by sending a shared secrete known to the authenticating proxy and CouchDB.  This is an extension of the existing proxy authentication implementation.  The new capabilities do not impact existing proxy authentication configurations or capabilities and will be disabled by default.

When both proxy based authentication and the shared secret capabilities outlined in this enhancement are enabled (config:couch_httpd_auth:proxy_use_shared_secret), the proxy must send a shared secret in an HTTP request header (config:couch_httpd_auth:shared_secret) that matches the shared secret known by CouchDB (config:couch_httpd_auth:shared_secret).

Create new configuration parameters for CouchDB:

**[couch_httpd_auth]**

> **proxy_use_shared_secret**

When this option is set to true, the couch_httpd_auth/shared_secret option is required for Proxy Authentication.
```
[couch_httpd_auth]
proxy_use_shared_secret = false
```
> **shared_secret**

The shared secret used for Proxy Authentication.

```
[couch_httpd_auth]
shared_secret = 92de07df7e7a3fe14808cef90a7cc0d91
```

> **x_auth_shared_secret**

The HTTP header name (X-Auth-CouchDB-Shared-Secret by default) containing the token used to authenticate the proxy. This token is a static value, as defined in couch_httpd_auth/shared_secret. The secret key should be the same on the proxy and the CouchDB node. This token is optional if the value of the couch_httpd_auth/proxy_use_shared_secret option is not true. Used for Proxy Authentication.

```
[couch_httpd_auth]
x_auth_shared_secret = X-Auth-CouchDB-Shared-Secret
```

## Current Behavior
The current secret/token configuration is not compatible with external systems such as httpd, nginx, haproxy, and the likes because the token must be generated for each user.  The capabilities outlined in this enhancement differ from the existing secret/token based validation for proxy authentication because the secret used to authenticate the proxy is based on a static shared secret known to CouchDB and the proxy versus the existing capabilities which use a sha1-hmac of a secret and the username.

Using the current capabilities of proxy authentication, assume the following configuration parameters for CouchDB:

```
[chttpd]
authentication_handlers = {couch_httpd_auth, proxy_authentication_handler}, {chttpd_auth, default_authentication_handler}
require_valid_user = true

[couch_httpd_auth]
proxy_use_secret = true
secret = s3cr3t
require_valid_user = true
x_auth_roles = X-Auth-CouchDB-Roles
x_auth_token = X-Auth-CouchDB-Token
x_auth_username = X-Auth-CouchDB-UserName
```

The following headers must be passed for user1:
```
X-Auth-CouchDB-Roles: role1
X-Auth-CouchDB-Token: 5350d04e1e71b5651ac44339e211c17faece36ce
X-Auth-CouchDB-UserName: user1
```

The following headers must be passed for user2:
```
X-Auth-CouchDB-Roles: role1
X-Auth-CouchDB-Token: b54fe2ef8cd5e013eea692063f99365b1e1773b9
X-Auth-CouchDB-UserName: user1
```

There is not a good way to generate the sha1-hmac using software like Apache httpd, nginx, HAProxy, and other software that provide proxy, authentication, and authorization services.

## Possible Solution
With the proposed enhancement, assume the following configuration for CouchDB:

```
[chttpd]
authentication_handlers = {couch_httpd_auth, proxy_authentication_handler}, {chttpd_auth, default_authentication_handler}
require_valid_user = true

[couch_httpd_auth]
proxy_use_secret = false
proxy_use_shared_secret = true
shared_secret = s3cr3t
require_valid_user = true
x_auth_roles = X-Auth-CouchDB-Roles
x_auth_shared_secret = X-Auth-CouchDB-Shared-Secret
x_auth_username = X-Auth-CouchDB-UserName
```

the following HTTP headers would be passed to CouchDB by the proxy:

for user1:
```
X-Auth-CouchDB-Roles: role1
X-Auth-CouchDB-Shared-Secret: s3cr3t
X-Auth-CouchDB-UserName: user1
```

for user2:
```
X-Auth-CouchDB-Roles: role1
X-Auth-CouchDB-Shared-Secret: s3cr3t
X-Auth-CouchDB-UserName: user1
```

## Context
This is a common implementation pattern for software that integrates with external authentication systems.  This extends the capabilities of CouchDB proxy based authentication to work with common proxy services that provide authentication and authorization services, such as Apache httpd, nginx, and HAProxy.

This closes an issue when using proxy authentication with software like Apache httpd.  Currently, when CouchDB is configured for proxy authentication and Apache httpd is used to provide authentication services, it is not possible to configure securely.  The existing token based authentication requires capabilities that Apache httpd cannot provide (sha1-hmac to generate the token).  Deployments of CouchDB that use proxy based authentication with Apache httpd as a proxy are generally open to identity spoofing since proxy_use_secret cannot be used.  Anyone with network access to CouchDB can impersonate users in this scenario.  This can be partly mitigated by configuring CouchDB to listen on the loopback interface, but even this does not guard against local unprivileged users.

Without the ability to authenticate the proxy in CouchDB, anyone with access to the CouchDB network endpoint can impersonate any user at will, including the admin user.

My specific use case is as follows:
* Users authenticate to Apache httpd using a client certificate
* Apache httpd validates the Issuer of the client certificate
* Apache httpd extracts the CN from the client certificate
* Apache httpd sets http header 'X-Auth-CouchDB-UserName' to the CN from the client certificate
* Apache httpd proxies the http request to couchdb

## Your Environment
* Version used: Couchdb 2.1.1
* Browser Name and version: curl 7.52.1
* Operating System and version (desktop or mobile): debian 9.3
* Link to your project: n/a
* Proxy: apache httpd 2.4.25

**Comment by rnewson** [comment]
Are you working on a pull request?

**Comment by gramsa49** [comment]
I have not started a pull request.  My energy is focused on building a solution using CouchDB, but I can if that's needed.

**Comment by rnewson** [comment]
I'm just saying that creating an issue here is unlikely to make this appear unless you do the work, though you'll also need to be clearer as to why the existing proxy authentication handler in CouchDB is unsuitable to your needs.

**Comment by gramsa49** [comment]
Thanks for the guidance.  I'll work on a pull request and refine the details.

**Comment by gramsa49** [comment]
I updated the description.  Let me know if this looks ok and is a useful enhancement.  If all looks good, I wills start on a pull request.  Thanks

**Comment by wohali** [comment]
You should review the former `proxy_use_secret` functionality, which has not been working since 2.0.0, and determine if you can address your concern by fixing this functionality rather than proposing something new.

**Comment by wohali** [comment]
@gramsa49 Can you see #1183 and see if that fixes your problem? I think this issue is invalid.
