### ISSUE TITLE
intermediate certs cut out of cert_file

### ISSUE THREAD

**Issue by artin-phares** [apache/couchdb#1179]
I'm configuring https access to couchdb using letsencrypt certificates.  

```
[ssl]
port = 6984
cert_file = /etc/letsencrypt/live/mydomain/fullchain.pem
key_file = /etc/letsencrypt/live/mydomain/privkey.pem
```

It works when I'm requesting couchdb from browser, but does not work when requesting from nodejs.  
```
RequestError: Error: unable to verify the first certificate
```

Which means couchdb strips intermediate certificates from full chain.  
I've ensured that with `openssl s_client -connect mydomain:6984 -showcerts`  

So browser has all intermediate certificates in its trusted certs store, while nodejs lacks some and therefore it fails to verify the chain.  

I've managed to get it working with `cacert_file` option, passing chain explicitly.  

```
[ssl]
port = 6984
cert_file = /etc/letsencrypt/live/mydomain/cert.pem
cacert_file = /etc/letsencrypt/live/mydomain/chain.pem
key_file = /etc/letsencrypt/live/mydomain/privkey.pem
```

Is there any way couchdb can accept fullchain.pem's right in `cert_file`, without need to specify `cacert_file `?

It would be bit easier and closer to nodejs, where we can pass full chain to cert:
```
https.createServer({key: ...'privkey.pem', cert: ...'fullchain.pem'})
```

**Comment by wohali** [comment]
I know that native SSL support in CouchDB is almost entirely provided by the underlying Erlang implementation. If Erlang doesn't support the full chain in the main cert file, we can't either.

**Comment by artin-phares** [comment]
@wohali Yeah, that's what I expected to hear. No big deal.  

Anyway, maybe someone will find the fix for `RequestError: Error: unable to verify the first certificate` here.
