### ISSUE TITLE
How to find All 

### ISSUE THREAD

**Issue by nxycdl** [apache/couchdb#1180]
how to find all db ;
I use this cmd but only return id , rev , I want all fileds 
curl -X GET http://127.0.0.1:5984/account/_all_docs 

for Example in Oralce we use select * from account

**Comment by jiangphcn** [comment]
try  curl http://localhost:15984/account/_all_docs?include_docs=true

**Comment by jiangphcn** [comment]
In addition, I didn't think that this is proper place to raise such question. May try in slack or IRC.
