### ISSUE TITLE
CouchDB macOS High Sierra Autostart

### ISSUE THREAD

**Issue by vielhuber** [apache/couchdb#1191]
Hello!

What's the recommened way of automatically running CouchDB after system start on macOS (High Sierra)?

When I click on the couch symbol in the navbar and choose "Automatically start at login", the setting does not get saved. Also in the official documentation there is nothing mentionned.

I don't simply want to put "Apache CouchDB.app" into bootup because then everytime the browser is opening with Fauxton opened.

Thanks for clarification.

**Comment by janl** [comment]
Heya @vielhuber, this is best added here: https://github.com/janl/couchdb-mac-app — a PR there is very welcome, too.

**Comment by vielhuber** [comment]
Should I reopen this issue on the other repo?

**Comment by wohali** [comment]
@vielhuber yes please, the CouchDB mac app isn't technically part of this repo.
