### ISSUE TITLE
[questions] Recommended way to delete huge number of documents.

### ISSUE THREAD

**Issue by style95** [apache/couchdb#1202]
What is the most desirable way to delete a huge number of documents?

For example, let's say I want to delete 500K ~ 1000K documents.
Since there are too many documents, I cannot query/delete them using one request.(request is timed out.)
So what I am trying is, first query the number of documents, and send bulk deletion request multiple times with `limit` parameter.

e.g) If counts are 500K, then calculate the required number of requests, first.

```
500k / 2000(limit value) = 250   // So I need to send 250 requests to delete documents.
```

But with this approach, my `count` query also hung and timed out.
(If `_count` reduce function has never been called)

So what is the recommended way to delete huge number of documents?

**Comment by janl** [comment]
In a case of “this isn’t really what you’re asking for”, I’d recommend to re-think the need for this.

1. if you want to clean up a database that has lots of docs you want to get rid of, but do it only once, I’d recommend doing a filtered replication of the docs that you want to keep and then delete the old database.
2. if you want to keep a “current” set of documents in the db, say delete everything older than 30/60/90 days, I’d recommend using a database per $interval.
3. if you do need to do this regularly, preparing for CouchDB performance getting asymptotically worse. In this scenario, deleting in batches is the way to go.
