### ISSUE TITLE
Investigate why 413 error is not delivered reliably

### ISSUE THREAD

**Issue by nickva** [apache/couchdb#1211]
There is a test to reproduce the issue (currently commented out):

https://github.com/apache/couchdb/commit/4a73d035dc77c4074f5e3c8d8bcf900138c91eb6

Then run with:

`make eunit apps=couch_replicator suites=couch_replicator_small_max_request_size_target`

This is related to issue #745 but breaking it out there to focus specifically on 413 response and socket handling.

The hope was that updating Mochiweb to 2.17 would fix the socket closing race condition but it doesn't seem to be the case. The above eunit test run reproduces the issues in about 10-15 runs locally on my setup (Erlang 19, master sha: cd598d892faeb14cf2b23542e73ebc1c262b2f95, macOS).

**Comment by wohali** [comment]
Closed by #1234.
