### ISSUE TITLE
when did the processes  of the couchjs launch by the beam process(couchdb)？ 

### ISSUE THREAD

**Issue by mudanzha** [apache/couchdb#1220]
i installed couchdb in 3 different VM, and make them into a cluster using Haproxy as a proxy agent。But the processes  of  their  are different. Two of their did not launch couchjs  process and the last one launched in the next day.  i  can not understand  when the couchjs launched by couchdb_beam, and please tell me how to launch couchjs processes.

**Comment by wohali** [comment]
`couchjs` processes are launched as needed by CouchDB for processing JavaScript.

You can adjust parameters of how these processes are launched via settings in your `local.ini` file. You want the settings under the `[query_server_config]` section. [Here's our documentation](http://docs.couchdb.org/en/2.1.1/config/query-servers.html#query-servers-configuration) on those settings.
