### ISSUE TITLE
Help with extension installation (ext-couchbase) PHP

### ISSUE THREAD

**Issue by marcelogarbin** [apache/couchdb#1224]
## Expected Behavior
I would like to install the extension in PHP (ext-couchbase), without errors or alerts in Linux, more precisely using laravel/homestead.

## Current Behavior
`PHP Warning:  PHP Startup: Unable to load dynamic library 'couchbase.so' (tried: /usr/lib/php/20170718/couchbase.so (/usr/lib/php/20170718/couchbase.so: undefined symbol: json_globals), /usr/lib/php/20170718/couchbase.so.so (/usr/lib/php/20170718/couchbase.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

## Possible Solution
Some way / tutorial to correctly install the extension for PHP. Because I could not do it by looking at the documentation. Maybe I might be doing something wrong too.

## Steps to Reproduce
1. `sudo add-apt-repository ppa:couchdb/stable -y`
2. `sudo apt-get update`
3. `sudo apt-get remove couchdb couchdb-bin couchdb-common libcouchbase-dev libcouchbase2-bin build-essential -yf`
4. `sudo apt-get install couchdb -y`
5. `curl localhost:5984` (I receive the welcome message... After that, I try to install the PHP extension)
6.  Install C SDK (Debian and Ubuntu) https://developer.couchbase.com/server/other-products/release-notes-archives/c-sdk
7. `sudo apt-get install libcouchbase-dev libcouchbase2-bin build-essential`
8. `sudo pecl install couchbase`
9. I edit the php.ini (/etc/php/7.2/cli/php.ini) file and add at the end of it the line `extension=couchbase.so` (I tried to use only: `extension=couchbase`, but I got the same warning.)
10. Restart all services

## Context
I was trying to install the package https://packagist.org/packages/ytake/laravel-couchbase, however to install it is required ext-couchbase.

## Your Environment
* Operating System and version (desktop or mobile): Win10 64 | Laravel Homestead 5.2 | Ubuntu 16.04.4 Xenial
* PHP: 7.2.3

**Comment by wohali** [comment]
You are asking for help with a Couchbase extension, which is a commercial offering from the Couchbase company.

This is the Apache CouchDB project. We can't help you.

**Comment by marcelogarbin** [comment]
My mistake. I'm new to the subject and honestly had not noticed the difference! Sorry for the inconvenience. I will try to find another CouchDB package that works with Laravel, if you have any indication I would appreciate it. Sorry for the inconvenience. :disappointed:

**Comment by popojargo** [comment]
https://github.com/robsonvn/laravel-couchdb
