### ISSUE TITLE
The beam.smp epmd processes stop and respawn continuously after a fresh Ubuntu install

### ISSUE THREAD

**Issue by vibl** [apache/couchdb#1229]
The beam.smp epmd processes stop and respawn continuously after a fresh Ubuntu install from the official repo (`deb https://apache.bintray.com/couchdb-deb xenial main`).
The only thing I did after the installation was setting up my admin password on http://127.0.0.1:5984/_utils#setup

Just after that, I couldn't access the server on http://127.0.0.1:5984 (blank page).

I tried reinstalling Couchdb, but there's an error at the end of the install process (with apt-get): `Errors were encountered while processing: couchdb` and then the same happens with the beam.smp and epmd processes.

I'm on Kubuntu 17.10 and I installed the Xenial version.

**Comment by vibl** [comment]
I found the problem: I had set the bind_address to the Fauxton address: 127.0.0.1:5984

This was solved when I purged the config, reinstalled again, and set bind_address to 127.0.0.1 without port.

**Comment by nickva** [comment]
Glad you found the misconfiguration issue. Yeah CouchDB will restart its subsystems on error sometimes. That is usually a good thing but it can also be confusing as well.
