### ISSUE TITLE
Idea: Bring back all_or_nothing

### ISSUE THREAD

**Issue by ondra-novak** [apache/couchdb#1235]
The conflict resolution is not atomic. Even if all conflicts are deleted along with updated document by a single _bulk_docs request, the data might be corrupted as result. There is a problem with validation function. If the validation fails for the updated document, conflicts are deleted, but main document is not updated. If the sender is unable to solve such situation immediately, the data from the conflicted documents are lost.

Please bring back all_or_nothing, or a similar feature. It should just process validation for the all updated documents before they are processed normally. The implementation should be easy, the validation functions should be available on all nodes, so there is no barrier to validate these documents on any of these nodes.

**Comment by rnewson** [comment]
This would require a distributed transaction and is not something we anticipate bringing to CouchDB.

**Comment by ondra-novak** [comment]
Nonsense. Where you see requirement of distributed transaction? I only need to perform validation which doesn't need to be distributed. Please reopen.

**Comment by rnewson** [comment]
Because the docs in the request will map to different shards on different nodes. We can’t do the old school all or nothing  semantics without some consistency protocol. 

The current all or nothing semantics is as good as it’ll get.

**Comment by ondra-novak** [comment]
This is totally untrue or not understood correctly. So let's change the name of the feature: "pre-validation".

Any of the shard just received the _bulk_docs request:

 As the first, It performs validation through all validation functions. This must be at least done on all shards, so the validation functions must be available on all shards as well. So the validation functions must be also available on the current shard. The validation functions are called for the all documents in _bulk_docs request - one by one - there is no mapping to shards. It just perform validation. 

Now, if there is a validation error, whole request is rejected.

After passing the "pre-validation", the request continues normally.

(pre-validation feature is opional similar to all_or_nothing]

**Comment by rnewson** [comment]
Perhaps we're talking past each other.

CouchDB's original all_or_nothing semantic was that all the updates would be applied to the database or none would be. This was possible because there was a single file and an atomic operation to update the b+trees.

When we added clustering, this semantic could no longer be honored without a consistency protocol / distributed transaction.

The current all_or_nothing behaviour is that the changes will be written even if they introduce conflicts. Not an obvious semantic.

Your point about validate_doc_update functions is separate, the all_or_nothing behaviour worked whether there were VDU's or not. Perhaps there's a case for not processing a _bulk_docs request if any item fails the validation but it runs against our explicit choice of availability (for reads _and_ for writes) over consistency, and the long-held position that the unit of consistency is the individual document. It's also not guaranteed to be the case that all the writes would succeed if the validate_doc_update functions pass for every document in the _bulk_docs request.

In your original comment;

```
If the validation fails for the updated document, conflicts are deleted, but main document is not updated. If the sender is unable to solve such situation immediately, the data from the conflicted documents are lost.
```

I don't recognise that behavior for CouchDB. CouchDB does not discard successful writes after the fact, so if you want to expand on what you observed there perhaps there's something to learn.

**Comment by ondra-novak** [comment]
Okaj, let's assume that this is about a new feature.

1. We have a document with conflicts.  There is main revision and the one or more conflicted revisions (deleted conflicts are not included)
2.  Let there is some automate process which is able to merge the most of conflicts
3. The automate process creates a new main document and then a set of delete requests for conflicted revisions. The conflicted revision is deleted by simple putting _deleted flag into it.
4. The _bulk_docs request is prepared and send to couchdb
5.  - question of the ordering? Is it better to put main revision as the first or as the last? With clustered database, this is hard to decide. In my code, i always put the main revision as the last, because if the changes are applied in the order - it is single document mapped to single shard(?) - the changes feed will contain deleted conflicts as the first and then the updated main revision.
6. Now, we have VDU. The purpose of  VDU is also to detected malformed merged documents. 
7. however, the VDU rejects the malformed document, but it cannot reject deletion of the conflict. 
8. As the result, the conflicted revisions are deleted (and lost after compaction). The main revision is not updated, so updates are also lost.

The workaround is to reconstruct conflicted documents back using the data temporary stored in the memory of that automated process -  but this is very ugly solution. It would be better to call VDU on the main revision and test it before the write

Hmm, other workaround is to send main revision as the single request and delete conflicts only if the requests passes. This has other issues. It needs two request. The new revision of the main document can be replicated and it still looks like conflicted, because conflicts has not been deleted yet. There can be also another process (for instance on other replica) which will try to merge conflicts with already updated revision. So this is the reason, why I am sending  updated document as the last item

To improve the work with conflicts i have just another suggestion, the field "_merged", but this will need an another ticket and looks more complicated than above suggestion.

**Comment by rnewson** [comment]
We have considered a (fundamental) change within CouchDB that would allow a revision to have multiple parents. This would change conflict resolution from what you describe (posting a new merged revision and then deleting the unwanted siblings) to a single doc update, which (should it pass all the VDU's) would apply the 'merged' update and resolve all the conflicts.

Are we describing the same problem now?

**Comment by ondra-novak** [comment]
Sounds promising. I agree. It describing the same problem and your proposal would solve it definitely.

----

 Actually I have come up with a similar thought when thinking about the problem. The purpose of the "_merged" field would be to specify multiple parents. Once the document with such field is received, the database would "purge" opened revisions that are mentioned in the list. This would also solve problem with multiplication of deleted conflicts that are still considered as opened.

The main benefit of such idea is that removing conflicts along with the document update would be atomic and no more deleted conflicts would be left opened.
