### ISSUE TITLE
Support triggered one-time replications in the scheduler

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#1256]
## Expected Behaviour
As an alternative to continuous replications, the replication scheduler could provide a repeatable, triggered one-time replication, keyed off of an internal global changes feed. Parameters would exist to set maximum frequency of recurrence, and perhaps minimum changes to accrue before triggering.

The idea is to provide a choice between continuous replication, which can be expensive, and one-shot replication, which must be triggered by an external process.

## Current Behaviour
Only continuous replications are possible. You can build the above using an external process and `/_db_updates` if desired.

## Context
See above.

**Comment by nickva** [comment]
We have a more general fair-share mechanism now in https://docs.couchdb.org/en/stable/whatsnew/3.2.html#features-and-enhancements to be able to configure replication priorities. Users would create one-shot replications and put in them in low priority (with very few shares) `_replicator` dbs.
