### ISSUE TITLE
Support replication scheduler priority queue

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#1257]
## Expected Behaviour
In tandem with #1256, it could be nice to add an exposed `priority` field to any replication scheduler job. This would reflect the user's priority, not necessarily the internal priority. Actual priority (a combination of user's requested priority + the replicator's internal priority queue) could be exposed through `/_replicator/jobs`.

The idea is to provide a way to rank the priority of seemingly-identical replications.

## Current Behaviour
If you want priority, you need an external process that monitors `/_db_changes`, implements business logic, and schedules with prejudice.

## Context
See above.

**Comment by nickva** [comment]
We fixed this with the Fair Share replicator. Thanks for the original idea @wohali! 

Out in 3.2.0 https://docs.couchdb.org/en/stable/whatsnew/3.2.html#features-and-enhancements

**Comment by kocolosk** [comment]
A quick followup to see if I understand the feature correctly. A user who wanted to create priority queues for different classes of replications would create e.g. `highpriority/_replicator`, `standard/_replicator`, `lowpriority/_replicator`, etc. and then configure `[replicator.shares]` in the server settings to allocate shares to each of these databases. It's not possible to define priority at the level of an individual document, right?

Seems like that meets the need, and requiring server admin privileges to commandeer resources like that makes sense.

**Comment by nickva** [comment]
@kocolosk yeah, that's how it would work. It's not per-individual replication job but per _replicator db.

It would would be possible to make it per-job and add another level to the share algorithm. Shares would then be hierarchically distributed per-db, then per-job.  But for now, perhaps, the existing (per db) implementation can be adequate. We can always re-open the issue for enhancements.
