### ISSUE TITLE
Couchdb 1 cannot replicate to couchdb2 & couchdb3

### ISSUE THREAD

**Issue by azcrusher** [apache/couchdb#1261]
Version: couchdb-1.6.1
Client OS: CentOS release 6.9 (Final) : couchdb-1.6.1
Server: CentOS release 6.9 (Final) : couchdb-1.6.1
Hi all,

i have a some problem, please help for fix the problem.

i cannot replication from couchdb1 cannot replicate to couchdb2 & couchdb3,

i use script for replication, by python:
https://pastebin.com/4NpAeVRR

my error is, when running script is:
https://pastebin.com/skUeBF9p

database, from couchdb1 (master):

[root@couchdb1 couchdb]# curl http://admin:*****@localhost:5984/_all_dbs
["_replicator","_users","testing1","testing7"]

and this is error log couchdb:
https://pastebin.com/7eH4XwWA

Kindly need your assist for fix ASAP my problem.

Thank you,

**Comment by eiri** [comment]
The error clearly says that you don't have a target database you are trying to replicate into. Create database `testing7` on the nodes `couchdb2` and `couchdb3` before replication or add an attribute `create_target: true` in your replication payload as [specified in documentation](http://docs.couchdb.org/en/2.1.0/api/server/common.html#post--_replicate)
