### ISSUE TITLE
How to get uuid secret and [httpd_global_handlers]

### ISSUE THREAD

**Issue by azcrusher** [apache/couchdb#1262]
Hi everybody,

Apache CouchDB 1.6.1

#vi local.ini
_google = {couch_httpd_proxy, handle_proxy_req, <<"http://www.google.com">>}
_fti = {couch_httpd_proxy, handle_proxy_req, <<"http://127.0.0.1:5985">>}

[couch_httpd_auth]
secret = fc87dfd3f8cd1a3bc9a74df0ab94f1a1

How to get uuid secret and [httpd_global_handlers] like above?

kindly need your assist for fix my problem.

Thank you,

**Comment by janl** [comment]
I’m not sure what the question here is. On first start, CouchDB will create a uuid and set this value, if it doesn't exist.
