### ISSUE TITLE
Processes piling up in fabric_doc_attachments:receive_unchunked_attachment/2

### ISSUE THREAD

**Issue by davisp** [apache/couchdb#1264]
Working ops I noticed that a particular cluster had a bunch of processes stuck in this function at [1]. Something somewhere must be orphaning processes here that then leaves them forever in the VM to accumulate until they slowly use up all available RAM. The particular cluster I was looking at took about 45 days to use up about 7G of RAM so its not a super pressing issue I don't think.

I figured I'd open a ticket as a note that I'd seen this.

**Comment by eiri** [comment]
I assume `[1]` should point to a code line?

**Comment by davisp** [comment]
[1] https://github.com/apache/couchdb/blob/02c9429d738e21f5dc5a92c33059e491e551a2f7/src/fabric/src/fabric_doc_attachments.erl#L93

**Comment by nickva** [comment]
Maybe the easiest fix is that middleman process in `after Timeout` kills the receiver process:

```
    after Timeout ->
        exit(Receiver, kill),
        ok
```

Also timeout is the `[fabric] request_timeout = 60000` maybe we really want that to be `[fabric] attachment_timeout = 600000`

**Comment by davisp** [comment]
+1 after swapping that timeout config as you suggest
