### ISSUE TITLE
Improve CouchDB "plugin" architecture for geo/search

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#1269]
We've had multiple discussions on the mailing lists and IRC previously about this problem: right now, you need to recompile CouchDB from scratch if you want to add search (dreyfus) or geo (hastings) support.

This isn't great, and makes things like Docker images that include references to those things unwieldy (since you can't just add another layer on top of the existing `couchdb` image.)

@davisp you said you had some specific ideas here, can you elaborate in this issue? Thanks!

**Comment by wohali** [comment]
From the merged #1516:

Once #1515 is done, this should be easy.

@janl:
>* deeeper clouseau/dreyfus integration
>* elasticsearch?

@davisp:
> At least a clear example of how to bundle and include Clouseau/Dreyfus.
> Just had someone ask how to use Dreyfus/Clouseau with CouchDB and I had to google for instructions and came across this:
>
>https://developer.ibm.com/dwblog/2015/text-search-apache-couchdb/
>
>Definitely Exhibit A on needing better integration. That's a lot of difficult steps for getting full text set up.

**Comment by homerjam** [comment]
Any more updates on this? It would be so wonderful not to be reliant on IBM! They can't even seem to handle billing 🤦🏻‍♂️

**Comment by wohali** [comment]
If there's progress, you'll see it linked here. As there is no update, there has been no progress.

**Comment by wohali** [comment]
Part of this merged with #2037 .

**Comment by dsebastien** [comment]
I'm curious about the status of this feature.
In my current project we're using CouchDB as the main data store and are starting to look at search scenarios. FTS would clearly help us.

Is there anything I/we can do to help this move forward?

**Comment by lucidNTR** [comment]
@dsebastien as far as i understood @wohali last month it will be part of couchdb 3.

**Comment by dsebastien** [comment]
@lucidNTR Indeed, i just saw the details through this recent talk: https://www.youtube.com/watch?v=SjXyVZZFkBg

**Comment by nickva** [comment]
Dreyfus / clouseau is now part of couchdb as part of 3.x+

Geo hasn't gotten much support and demand at Cloudant and as such, is now removed. There a few remnants of it in the Apache CouchDB code but we should probably remove those.
