### ISSUE TITLE
DB hangs while replicating

### ISSUE THREAD

**Issue by mamendoz** [apache/couchdb#1274]
I have two machines running CouchDB 1.6.1

I have continious replication jobs running on both of them.

```
Machine A:
   Continious replication job:
      source: mydb
      target:  https://B/mydb
Machine B:
    Continious replication job:
       source: mydb
       target: https://A/mydb
```

This works well for about a month, but after some time, machine B gets restarted, and when the replication job starts again ... CouchDB appears to be hanging. Whenever I try to insert, or read from `mydb` database I get read timeout. 

I am able to recreate the issue with the database files, but I don't know what is causing it to be in this state. Other databases in the same server are unaffected. (I am not able share the database files as it contains customer sensitive information)

I've tried removing and re-adding `mydb` database in machine B, then re-starting the replication job, but still end up the same state. I've also tried removing and readding the database in machine A, but it looks like the data from B get immediately replicated to A, then I end up again in same state. The only way I've found that gets me unstuck is to remove and recreate `mydb` in both A and B simultaneously.

Could you give me some hints direction on how I would go about troubleshooting this? Looking at the couch.log I don't see any errors. How can I know where couchdb is getting stuck causing the requests requests to read/write to `mydb` to timeout?

## Your Environment
* Version used: 1.6.1
* Operating System: `Linux x86_64`

**Comment by wohali** [comment]
Can you try upgrading to 1.7.1 first? 1.6.1 has known security issues, for a start.
