### ISSUE TITLE
Couchdb 1st node in a cluster is on a looping restart sequence.

### ISSUE THREAD

**Issue by petekun** [apache/couchdb#1279]
On starting couchdb it goes on an infinite restart loop.  Below is a slice of the couchdblog

[error] 2018-04-12T15:30:37.698834Z couchdb@couchdb.company.com <0.264.0> -------- Supervisor couch_secondary_services had child compaction_daemon started with couch_compaction_daemon:start_link() at undefined exit with reason {'EXIT',{undef,[{couch_compaction_daemon,start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,358}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,341}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,307}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}} in context start_error

Seeing this error when trying to access a couchdoc

"Error: nodedown progress not possible"

couchdb version we are running is as below

HTTP/1.1 200 OK
Cache-Control: must-revalidate
Content-Length: 91
Content-Type: application/json
Date: Thu, 12 Apr 2018 15:39:31 GMT
Server: CouchDB/2.0.0 (Erlang OTP/18)
X-Couch-Request-ID: 7bb6cc6faf
X-CouchDB-Body-Time: 0

{"couchdb":"Welcome","version":"2.0.0","vendor":{"name":"The Apache Software Foundation"}}

**Comment by wohali** [comment]
1. CouchDB 2.0.0 is outdated and has serious security holes, upgrade to 2.1.1 as soon as possible
2. Looks like your `default.ini` file is outdated, be sure to update to the latest as shipped with the product. You should never modify `default.ini` yourself. Always only update `etc/local.ini` or  `etc/local.d.*.ini` files.

If the above doesn't solve your problem, request a reopen of this issue and post additional detail.
