### ISSUE TITLE
Possibility to apply a maximum log size value for couch.log (Logging feature in couch_log erlang)

### ISSUE THREAD

**Issue by cwmichi** [apache/couchdb#1284]
Hello,

I just looked into the documentation for CouchDB 2.1.1 to limit the log level to maybe (warning, info, error, etc.) but is there also a possibility to limit the file size for the growth of the couch.log and not to get bigger than 1 GB ?

**Comment by eiri** [comment]
No there are not such functionality in couch_log. This is traditionally done with external tools, e.g. [logrotate](https://manpages.debian.org/jessie/logrotate/logrotate.8.en.html).
