### ISSUE TITLE
[Question]GET /db/_all_docs is slow, which index is it using?

### ISSUE THREAD

**Issue by smartheye** [apache/couchdb#1290]
Hi, I am using couchdb 2.1.1. It's found that when query /db/_all_doc interface, it took time to respond and used high cpu. I understood that it's rebuilding index so a lot of time and cpu must be used.
But I cannot find which index is /db/_all_doc using. 
If I know the index I could warm it by query it after data update
## Expected Behavior

It might not be a bug. Can you tell me which index is /db/_all_doc using? 
And, what's mrview? is it related?
## Current Behavior

query /db/_all_doc is using high cpu and a lot of time.
some of them would take more than 30 seconds, it caused application timeout
## Possible Solution

tell me which index is /db/_all_doc using.
## Steps to Reproduce (for bugs)

1. changed a lot of data in couchdb
2. query GET /db/_all_docs
3. it took a lot of time
4.

## Context

when the data changed, query /_all_docs would trigger a rebuild of view, which took a lot of time (more than 30 seconds at max, most of them were 10~20 seconds)
the query would timeout.
So I just want to rewarm the index but I cannot find what index /_all_docs used.
And I found mrview occured in the log but I don't know what it is

## Your Environment

* Version used: 2.1.1
* Browser Name and version: Chrome/Firefox
* Operating System and version (desktop or mobile): ubuntu 1604
* Link to your project: http://github.com/hyperledger/fabric

**Comment by jiangphcn** [comment]
if you query against `_all_docs` endpoint, the traffic will be directed to id tree. This is not additional index. Is it possible to build map-reduce view or other index to facilitate your query?

**Comment by smartheye** [comment]
Thanks @jiangphcn 
Correct me if I am wrong
I am using query as GET /{db}/_all_docs?startkey=<start value>&endkey=<end value>&limit=1000&inclusive_end=false&include_docs=true
Currently there is max 300 queries  per seconds using above query string. The Server is  a 4 core, frequency 2.4G and 8G memory PC. most of queries will cost more than 10 seconds.
Accoding to your answer and some search results from google, I found there is no index used by _all_docs view. _all_docs view changes when key changes. So there's no need to warm _all_docs view.

I am just wondering that, if I use ONLY key to do queries, _all_docs view will always be faster than any other map-reduce view because _all_docs view will always be updated.

And... why queries cost too much time? CPU or disk IO or other things are the bottleneck? I am currently thinking of using nginx as cache and reducing json size. But I am not sure. Sorry to ask a so hard question, any experience/advice would help.

**Comment by jiangphcn** [comment]
@smartheye glad to provide assistance. However, as I mentioned, did you try to check with map-reduce view to see whether it helps? The view is built/updated once there is document update in database. However, during your query, there is no additional cost to build index (given view index was already built before). Thus, the query scope will be narrowed down. The corresponding resource will extremely used.

**Comment by jiangphcn** [comment]
hey @smartheye, is there more needed from couchdb side? If not, I plan to close this case by the end of this week.
