### ISSUE TITLE
Mango query uses a certain index but not when that index is specified in use_index

### ISSUE THREAD

**Issue by garbados** [apache/couchdb#1294]
## Expected Behavior

When an index is specified using `use_index`, that index should be used if it can satisfy the query.

## Current Behavior

A query uses a particular index by default, but when that index is specified with `use_index`, CouchDB reports this error:

`_design/${name} was not used because it does not contain a valid index for this query.`

## Steps to Reproduce (for bugs)

Consider this index:

```json
{
  "index": {
    "fields": [
      "name"
    ]
  },
  "name": "names",
  "type": "json"
}
```

...and a document like this:

```json
{ "name": "Diana" }
```

Running the query against `/{db}/_explain` without `use_index` confirms that CouchDB has selected our index to satisfy this query:

```
$ curl -X POST -H 'content-type:application/json' $COUCH_URL/contacts/_explain -d '{ "selector": { "name": "Diana" } }'

{
  "dbname": "contacts",
  "index": {
    "ddoc": "_design/e989afba40865ef0c0cb81babca885c21e33cd49",
    "name": "names",
    "type": "json",
    "def": {
      "fields": [
        {
          "name": "asc"
        }
      ]
    }
  },
  "selector": {
    "name": {
      "$eq": "Diana"
    }
  },
  "opts": {
    "use_index": [],
    "bookmark": "nil",
    "limit": 25,
    "skip": 0,
    "sort": {},
    "fields": "all_fields",
    "r": [
      49
    ],
    "conflicts": false,
    "stale": false,
    "update": true,
    "stable": false,
    "execution_stats": false
  },
  "limit": 25,
  "skip": 0,
  "fields": "all_fields",
  "mrargs": {
    "include_docs": true,
    "view_type": "map",
    "reduce": false,
    "start_key": [
      "Diana"
    ],
    "end_key": [
      "Diana",
      "<MAX>"
    ],
    "direction": "fwd",
    "stable": false,
    "update": true
  }
}
```

But running it with `use_index` elicits a warning about a lack of suitable index:

```
$ curl -X POST -H 'content-type:application/json' $COUCH_URL/contacts/_find -d '{ "selector": { "name": "Diana" }, "use_index": "names" }'

{"docs":[
{"_id":"efec58378ab329ede55d286425000af8","_rev":"1-257b9c40d13a455e1a5c1141b97d68d5","name":"Diana"
],
"bookmark": "g2wAAAACaAJkAA5zdGFydGtleV9kb2NpZG0AAAAgZWZlYzU4Mzc4YWIzMjllZGU1NWQyODY0MjUwMDBhZjhoAmQACHN0YXJ0a2V5bAAAAAFtAAAABURpYW5hamo",
"warning": "_design/names was not used because it does not contain a valid index for this query."}
```

## Context

I encountered this issue while trying to develop a working example of [partial indexes](http://docs.couchdb.org/en/2.1.1/api/database/find.html#find-partial-indexes) for a Mango tutorial. While I first encountered the issue on an index with a partial index, I was able to reproduce it without the partial index.

## Your Environment

* Version used: CouchDB 2.2.0-0e92688
* Browser Name and version: curl 7.47.0 (x86_64-pc-linux-gnu) [libcurl/7.47.0, GnuTLS/3.4.10, zlib/1.2.8, libidn/1.32, librtmp/2.3]
* Operating System and version (desktop or mobile): Ubuntu 16.04.4 LTS, desktop
* Link to your project:

**Comment by willholley** [comment]
@garbados I think the issue here is that the design document is `_design/e989afba40865ef0c0cb81babca885c21e33cd49` rather than `_design/name`. You can control the design document name at index creation time by specifying `"ddoc"` but the default will just be a uuid.

According to the documentation:, `"use_index"` should be specified as `"<design_document>" or ["<design_document>", "<index_name>"]`, so do you get the expected result if you do:

```
$ curl -X POST -H 'content-type:application/json' $COUCH_URL/contacts/_find -d '{ "selector": { "name": "Diana" }, "use_index": "_design/e989afba40865ef0c0cb81babca885c21e33cd49" }'
```
?

**Comment by garbados** [comment]
That works! My bad for misunderstanding the docs. Thank you for the help :)
