### ISSUE TITLE
bcrypt support breaks couchdb on single proc platforms

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#1296]
In analysis for #1293 I ran across this issue while testing in a VM that has only a single processor.

We enable bcrypt support in `test/javascript/tests/users_db_security.js` for testing purposes. However, on a single-processor machine, this test fails.

Looking at `dev/logs/node1.log` I see the following, then a crash:

```
enif_send: env==NULL on non-SMP VM
```

First hit on a web search was [this bug](https://github.com/basho/eleveldb/issues/120) which says that `enif_send` does not work on the non-SMP BEAM VM.

Confirmed on the erlang mailing list:

```
> On Tuesday, March 21, 2017 10:28 AM, Sverker Eriksson <[hidden email]> wrote:
> enif_send can be called from a non scheduler thread in an SMP enabled VM
> (beam.smp)
> but not in a non-SMP VM (beam). 
```

Our choices are:

1. Eliminate our single call to `enif_send` [here](https://github.com/apache/couchdb-erlang-bcrypt/blob/master/c_src/bcrypt_nif.c#L126) somehow
1. Put `-smp enable` in `vm.args` everywhere

/cc @janl @davisp 

As this breaks us on a lot of machines, I'm adding this to the 2.2.0 milestone to ensure we don't release without fixing this problem.

**Comment by dch** [comment]
+1 for  `-smp enable` everywhere. IIRC its soon to be the non-configurable default in OTP anyway. This has been around for a long time so I'd expect it doesn't break compatibility & I'm not aware of any downside on single-processor platforms.
