### ISSUE TITLE
Error compacting database _global_changes: noproc

### ISSUE THREAD

**Issue by jvegaseg** [apache/couchdb#1300]
Today starting with this error:

`[error] 2018-04-30T09:41:02.982915Z couchdb@XX.XX.XX.XX <0.237.0> -------- Compaction daemon - an error ocurred while compacting the database 'shards/30000000-3fffffff/_global_changes.1510390507': noproc`

## Configuration
We use default settings except:

local.ini
```
[cluster]
q = 16

[log]
level = warning
```

vm.args
```
-name couchdb@X.X.X.120
-setcookie XXXXXXXXXXXXXX
-kernel inet_dist_listen_min 9100
-kernel inet_dist_listen_max 9200

-kernel error_logger silent
-sasl sasl_error_logger false

+K true
+A 16
+Bd -noinput
```

sys.config

```
[
    {lager, [
        {error_logger_hwm, 1000},
        {error_logger_redirect, true},
        {handlers, [
            {lager_console_backend, [debug, {
                lager_default_formatter,
                [
                    date, " ", time,
                    " [", severity, "] ",
                    node, " ", pid, " ",
                    message,
                    "\n"
                ]
            }]}
        ]},
        {inet_dist_listen_min, 9100},
        {inet_dist_listen_max, 9200}
    ]}
].
```

## Environment
Software is running on virtualized Centos 7 using OpenVZ 7.
Each node has same configuration.
Each node has 16 cores.

**Comment by jvegaseg** [comment]
More errors:

```
[error] 2018-04-30T11:50:51.329107Z couchdb@XX.XX.XX.XX <0.235.0> -------- gen_server couch_compaction_daemon terminated with reason: {compaction_loop_died,{timeout,{gen_server,call,[<0.26734.6754>,compactor_pid]}}}
  last msg: {'EXIT',<0.237.0>,{timeout,{gen_server,call,[<0.26734.6754>,compactor_pid]}}}
     state: {state,<0.237.0>,[<<"shards/30000000-3fffffff/_global_changes.1510390507">>]}
[error] 2018-04-30T11:50:52.598514Z couchdb@XX.XX.XX.XX <0.235.0> -------- CRASH REPORT Process couch_compaction_daemon (<0.235.0>) with 0 neighbors exited with reason: {compaction_loop_died,{timeout,{gen_server,call,[<0.26734.6754>,compactor_pid]}}} at gen_server:terminate/7(line:826) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_compaction_daemon,init,['Argument__1']}, ancestors: [couch_secondary_services,couch_sup,<0.201.0>], messages: [], links: [<0.210.0>], dictionary: [], trap_exit: true, status: running, heap_size: 1598, stack_size: 27, reductions: 269937
[error] 2018-04-30T11:50:52.601815Z couchdb@XX.XX.XX.XX <0.210.0> -------- Supervisor couch_secondary_services had child compaction_daemon started with couch_compaction_daemon:start_link() at <0.235.0> exit with reason {compaction_loop_died,{timeout,{gen_server,call,[<0.26734.6754>,compactor_pid]}}} in context child_terminated
[error] 2018-04-30T11:51:00.966927Z couchdb@XX.XX.XX.XX <0.362.6773> -------- Compaction daemon - an error ocurred while compacting the database `shards/30000000-3fffffff/_global_changes.1510390507`: noproc
```

**Comment by wohali** [comment]
Are there any other errors around this line?

```
[error] 2018-04-30T09:41:02.982915Z couchdb@XX.XX.XX.XX <0.237.0> -------- Compaction daemon - an error ocurred while compacting the database 'shards/30000000-3fffffff/_global_changes.1510390507': noproc
```

**Comment by jvegaseg** [comment]
No.

I have added this configuration param in local.ini and it seams that the problem has disappear.

```
[httpd]
max_http_request_size = 4294967296

```

**Comment by jvegaseg** [comment]
Sorry, the problem arises again (just now):

05-02T16:32:50.495655Z couchdb@X.X.X.X <0.289.0> -------- Compaction daemon - an error ocurred while compacting the database `shards/30000000-3fffffff/_global_changes.1510390507`: noproc

**Comment by jvegaseg** [comment]
Additional info:
[error] 2018-05-02T23:01:08.904899Z couchdb@X.X.X.X <0.287.0> -------- CRASH REPORT Process couch_compaction_daemon (<0.287.0>) with 0 neighbors exited with reason: {compaction_loop_died,{timeout,{gen_server,call,[<0.19381.138>,start_compact]}}} at gen_server:terminate/7(line:826) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_compaction_daemon,init,['Argument__1']}, ancestors: [couch_secondary_services,couch_sup,<0.252.0>], messages: [], links: [<0.262.0>], dictionary: [], trap_exit: true, status: running, heap_size: 1598, stack_size: 27, reductions: 9291

**Comment by jvegaseg** [comment]
Any clue on this? Server is generating a lot of errors.

**Comment by jvegaseg** [comment]
More:

[error] 2018-05-04T04:21:10.794610Z couchdb@x.X.X.x <0.228.263> -------- Supervisor couch_secondary_services had child compaction_daemon started with couch_compaction_daemon:start_link() at <0.5292.273> exit with reason {compaction_loop_died,{timeout,{gen_server,call,[<0.24241.217>,compactor_pid]}}} in context child_terminated

**Comment by jvegaseg** [comment]
More (hundred of errors):

[error] 2018-05-04T04:21:10.794014Z couchdb@X.X.X.X<0.5292.273> -------- gen_server couch_compaction_daemon terminated with reason: {compaction_loop_died,{timeout,{gen_server,call,[<0.24241.217>,compactor_pid]}}}

**Comment by jvegaseg** [comment]
When compaction crash, cpu iowait is very high.

**Comment by wohali** [comment]
Hi @jvegaseg , if your cpu iowait is very high then I once again suspect your storage subsystem is at fault. I can't help with the rest of the errors, but you should check for other processes on the system overtaxing the storage, or problems with your OpenVZ setup. Check storage subsystem metrics at both the host and guest level.

**Comment by jvegaseg** [comment]
This VPS is the only machine in hardware host.
Is there any configuration param in order to increase this timeout?

**Comment by jvegaseg** [comment]
I confirm you that the process which is generation high iops is beam.smp

**Comment by wohali** [comment]
We have seen something similar to this in other production environments where disk latency is high. It is entirely possible to have high IOPS but also high operation latency, see: 

    https://www.datadoghq.com/blog/aws-ebs-latency-and-iops-the-surprising-truth/index.html

Are you able to monitor your disk operation latency under load at all?

**Comment by jvegaseg** [comment]
The node with hight IOPS have just died. One of the disk is broken. Cluster is working as expected.
Is there any document or help in order to replace a broken node? In help there are documents for adding or deleting nodes but not I have not seen how to replace a node.
Please help.

**Comment by wohali** [comment]
@jvegaseg this GH issue really isn't the place, but to replace a node, just reinstall a new machine with the same IP, same version of CouchDB, and same ini files, then join it to the cluster. Internal replication will re-replicate all data to that node.

**Comment by jvegaseg** [comment]
@wohali, I would appreciate if you can tell me how to join the new machine to the cluster. I am not sure how to do it. I do not want to break nothing more ;->

Remember we have a cluster with 6 nodes X.X.X.120 to X.X.X.125 and the broken machine is X.X.X.125.

In documentation explains how to add a machine to a cluster but current nodes already have the IP X.X.X.125 joined. So, what command have I to execute in new machine?
Please, help me on this.

**Comment by janl** [comment]
@jvegaseg this should help http://docs.couchdb.org/en/2.1.2/cluster/index.html
