### ISSUE TITLE
Help nssm.exe flagged as PUA/Riskware in F-secure

### ISSUE THREAD

**Issue by LarsVoith** [apache/couchdb#1302]
We have reported to F-secure that nssm.exe is a false positive but they have replied back that
"Our analysis indicates that the file you submitted is indeed PUA/Riskware and is already detected as ?Application.NSSM in the latest database update.".   We must run F-secure and have no chance to remove it, we really need some help here, can anyone shed some light on this please!

**Comment by wohali** [comment]
Add CouchDB to your list of exceptions in F-Secure.

We need NSSM to install the CouchDB service.

This is not our problem?

**Comment by wohali** [comment]
The work necessary to install CouchDB as a service without nssm is extremely low priority. I'll open a separate enhancement request to track this request, but please understand that it may be years before it gets addressed.

You'll need to add nssm.exe as an exception in your F-Secure install or group policy.

Pull requests are welcome.

**Comment by snapo** [comment]
Hi,
Additional alerts from 8 other vendors:
https://www.virustotal.com/gui/file/eee9c44c29c2be011f1f1e43bb8c3fca888cb81053022ec5a0060035de16d848/detection

Best regards
