### ISSUE TITLE
Make default `httpd.max_http_request_size` consistent

### ISSUE THREAD

**Issue by garethbowen** [apache/couchdb#1304]
The `httpd.max_http_request_size` [defaults to 64MB](https://github.com/apache/couchdb/blob/master/rel/overlay/etc/default.ini#L147). However if the value is unset it defaults to 4GB [1](https://github.com/apache/couchdb/blob/master/src/couch/src/couch_httpd_external.erl#L66), [2](https://github.com/apache/couchdb/blob/master/src/chttpd/src/chttpd.erl#L632), [3](https://github.com/apache/couchdb/blob/master/src/couch/src/couch_httpd.erl#L454), [4](https://github.com/apache/couchdb/blob/master/src/chttpd/src/chttpd_external.erl#L96), [5](https://github.com/apache/couchdb/blob/master/src/couch/src/couch_httpd_external.erl#L66). Also I interpreted [the documentation](http://docs.couchdb.org/en/2.1.1/config/http.html#httpd/max_http_request_size) to say it defaults to 4GB (though the default isn't explicitly stated).

## Expected Behavior
Users expectations are met.

## Current Behavior
Users get surprised by the _actual_ default value.

## Possible Solution
Either:
1. the default.ini should be updated to 4GB (or commented out) to be consistent with the fallback values and documentation, or
2. the fallback values and documentation should be updated to 64MB to be consistent with the default.ini value

## Your Environment
* Version used: 2.11
* Link to your project: https://github.com/medic/medic-webapp/issues/3257#issuecomment-385306461

**Comment by wohali** [comment]
We're resolving this differently in 2.2.0 - the entire semantic will change because of underlying issues.

See #1200 and #1253 on what is changing.

**Comment by wohali** [comment]
FYI you should never modify `default.ini`, this file is intentionally updated with each release and sometimes doesn't match defaults set in the code.

This is why the default is 64MB in the ini file but different in the actual code...

**Comment by garethbowen** [comment]
@wohali Thanks for that. Do you think it'd be worth updating the documentation? It looks like this value will continue to default to 64MB through v3.0 and it would be helpful to specify that instead of 4GB as it does currently.

**Comment by wohali** [comment]
@garethbowen #1253 is tagged to be resolved in 2.2.0 in some form. I will make sure that we update the documentation as part of that effort in some regard, since this is a big change with forward-looking ramifications.
