### ISSUE TITLE
Enabling require_valid_user blocks login to Fauxton

### ISSUE THREAD

**Issue by greenais** [apache/couchdb#1305]
## Expected Behavior
Admin can log to Fauxton with require_valid_user = true

## Current Behavior
Once require_valid_user is enabled opening http://localhost:5984/_utils/#login brings on white page:
{"error":"unauthorized","reason":"Authentication required."}. No login form, no further actions possible.

## Possible Solution
Keep require_valid_user disabled? 

## Steps to Reproduce (for bugs)
1. fresh install according to docs, cors enabled, admin user and one test Db created 
2. set require_valid_user = true in local.ini
3. open http://localhost:5984/_utils/#login
4. disable require_valid_user => Fauxton opens login with no issues

## Context
Doesn't depend on browser used - the same in Crome, Opera, FF...

## Your Environment
* Version used: 2.1.1
* Browser Name and version: all latest Chrome, Opera, FF
* Operating System and version (desktop or mobile): Windows 8.1, desktop

**Comment by wohali** [comment]
There is a note in the local.ini file that reads:

```
; If you set this to true, you should also uncomment the WWW-Authenticate line
; above. If you don't configure a WWW-Authenticate header, CouchDB will send
; Basic realm="server" in order to prevent you getting logged out.
```

You have to do both, otherwise you don't get the browser popup window for realm authentication. A correct configuration for CouchDB 2.1.1 is:

```
[httpd]
WWW-Authenticate = Basic realm="administrator"
[chttpd]
require_valid_user = true
```

I have tested this locally and this resolves the problem.

It helps to read the fine documentation we've written ;)

**Comment by greenais** [comment]
Shame on me, it really helps. 
Don't know where were my eyes - now I remember that notification string which lost somehow during moving significant stuff from default.ini to local.ini in order to keep them on upgrade...
Thank you for gread DB and support and sorry fo disturbing.

**Comment by ThibaultJanBeyer** [comment]
That is not written in `fauxton`. Also I don’t seem to find `WWW-Authenticate` in `fauxton`.
On MacOS, editing the `couchdb2-local.ini` in `~/Library/Preferences/couchdb2-local.ini` to include:
```
[httpd]
www-authenticate = Basic realm="administrator"
```
Still gives me `error: "unauthorized",  reason: "Authentication required."`


**Environment**

    Version used: 2.1.1
    Browser Name and version: all latest FF
    Operating System and version (desktop or mobile): MacOS 10.13.5 (17F77), desktop

**Comment by newtewt** [comment]
Also on OSX and having same issue. 

The response from curl. 

"Basic realm=\"administrator\""

Content of ~/Library/Preferences/couchdb2-local.ini

```

[couchdb]
database_dir = /Users/ewt/Library/Application Support/CouchDB2/var/lib/couchdb
view_index_dir = /Users/ewt/Library/Application Support/CouchDB2/var/lib/couchdb
uri_file = /Users/ewt/Library/Application Support/CouchDB2/var/run/couchdb/couch.uri
uuid = 58e82549b52c230185de7c2c8fee903d

[cluster]
n = 1
q = 2

[log]
writer = file
file = /Users/ewt/Library/Logs/CouchDB2.log

[admins]
admin = <admin_details>

[httpd]
www-authenticate = Basic realm="administrator"

[chttpd]
require_valid_user = true
bind_address = 0.0.0.0
port = 5984

[couch_httpd_auth]
secret = <secret_details>
```

**Comment by wohali** [comment]
@newtewt That may no longer be the correct place for local.ini, and I have no experience with the OSX packaging contributed by @janl , so I can't help.

What I can say is that the settings linked in the documentation work on Linux and Windows, so I am thinking this is something specific to the OSX binary.

We don't support this binary within the Apache project.  You'll want to report the bug over at https://github.com/janl/build-couchdb-mac , sorry.

**Comment by ktaragorn** [comment]
I encountered this issue as well, having set this field via fauxton, and now I am locked out. Luckily i have ssh access to the server and I can hopefully fix this. But it should not work this way. I tried to login by adding user:pass@ to the url and it doesnt work either.

**Comment by wohali** [comment]
@ktaragorn Can you confirm the OS on which you are experiencing this?

**Comment by ktaragorn** [comment]
@wohali This is couchdb 2.1.1 installed on Ubuntu 16.04 LTS. I changed this option via fauxton, and now am locked out of admin panel. Still figuring out where fauxton stores the config so I can go undo it.

**Comment by ktaragorn** [comment]
Installed using your cookbook https://supermarket.chef.io/cookbooks/couchdb

**Comment by wohali** [comment]
I'll reopen for now. Someone will have to try to reproduce this on `master`.

**Comment by ktaragorn** [comment]
> There is a note in the local.ini file that reads:
> 
> ```
> ; If you set this to true, you should also uncomment the WWW-Authenticate line
> ; above. If you don't configure a WWW-Authenticate header, CouchDB will send
> ; Basic realm="server" in order to prevent you getting logged out.
> ```
> 
> You have to do both, otherwise you don't get the browser popup window for realm authentication. A correct configuration for CouchDB 2.1.1 is:
> 
> ```
> [httpd]
> WWW-Authenticate = Basic realm="administrator"
> [chttpd]
> require_valid_user = true
> ```
> 
> I have tested this locally and this resolves the problem.
> 
> It helps to read the fine documentation we've written ;)

It is now working as expected once I followed this config. But neither the cookbook or the fauxton UI mentions this.

**Comment by wohali** [comment]
The cookbook isn't intended to cover every possible configuration approach, nor is Fauxton.

**Comment by papswell** [comment]
Hi there, 

On macOS, i finally managed to resolve this with the following config : 
```
# ~/Library/Preferences/couchdb2-local.ini

[httpd]
WWW-Authenticate = Basic realm="Welcome to the Couch!"
```

Found in the [official documentation](https://docs.couchdb.org/en/stable/config/http.html#httpd/WWW-Authenticate) :)

Hope this helps,
Regards

**Comment by robsonvn** [comment]
Just to add that if you're using the helm chart you need to use the following:

```
couchdbConfig:
  httpd:
    WWW-Authenticate: "Basic realm=\"administrator\""
  chttpd:
    require_valid_user: true
```

**Comment by nkev** [comment]
In case it helps someone else, in Windows 10 with CouchDB 3.1.1 I had to modify `C:\Program Files\Apache CouchDB\etc\default.ini` (not local.ini because all settings in local.ini are commented out). Also, the setting `WWW-Authenticate: "Basic realm=\"administrator\""` was missing so I added it manually (see below). Then I restarted the `Apache CouchDB` Windows service which allowed me to get back in.

![image](https://user-images.githubusercontent.com/5410916/107894670-6e30f300-6f84-11eb-9c3f-f3ef7bd2709a.png)

**Comment by FoxUSA** [comment]
> [httpd]
> WWW-Authenticate = Basic realm="administrator"

@wohali 
Is this changing? I see folks link to documents that do not have this noted.


> Hi there,
> 
> On macOS, i finally managed to resolve this with the following config :
> 
> ```
> # ~/Library/Preferences/couchdb2-local.ini
> 
> [httpd]
> WWW-Authenticate = Basic realm="Welcome to the Couch!"
> ```
> 
> Found in the [official documentation](https://docs.couchdb.org/en/stable/config/http.html#httpd/WWW-Authenticate) :)
> 
> Hope this helps, Regards

When using the [Docker image](https://hub.docker.com/_/couchdb), you don't see this note in the ini and it is not [noted on the documentation](https://docs.couchdb.org/en/stable/config/auth.html#chttpd/require_valid_user) for the `require_valid_user` field.

So the only way to know about this is to hit it from what I can see.
