### ISSUE TITLE
CouchDB should always report its git hash at runtime

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#1309]
## Current and expected behaviour
Currently, if you are running a CouchDB master build, you will see the matching git version when performing a `GET /`:
```
{"couchdb":"Welcome","version":"2.2.0-47a38d3d0","features":["pluggable-storage-engines","scheduler"],"vendor":{"name":"The Apache Software Foundation"}}
```

And you see it in the log output at the `info` level:
```
[info] 2018-05-02T18:33:16.364837Z node1@127.0.0.1 <0.237.0> -------- Apache CouchDB 2.2.0-47a38d3d0 is starting.
```

When building a release, this information vanishes:
```
{"couchdb":"Welcome","version":"2.1.1","features":["scheduler"],"vendor":{"name":"The Apache Software Foundation"}}
```

It's not even in the log anymore:
```
[info] 2018-05-02T18:54:01.657777Z couchdb@127.0.0.1 <0.204.0> -------- Apache CouchDB 2.1.1 is starting.
```

This makes build audits painful, and makes release candidates impossible to distinguish from one actual releases. This, in turn, has lead to actual problems in the field, where people install an RC that has serious problems but it looks like it's an actual release.

## Proposal
1. Change the version number response as follows:
    1. When a build is built off of a release-like tag (regex: `^[0-9]+\.[0-9]\.[0-9]+(-RC[0-9]+)?$$`), give the build the version number `X.Y.Z`.
    1. When the regex doesn't match, label the build `X.Y.Z-dev`.
1. Always return the above version number, as well as the git hash (short or long, long might be better) info on `GET /` as a subkey. Examples:
```json
{"couchdb":"Welcome","version":"2.2.0-dev","git_hash":"47a38d3d0","features":["pluggable-storage-engines","scheduler"],"vendor":{"name":"The Apache Software Foundation"}}
{"couchdb":"Welcome","version":"2.1.1","git_hash":"f84faa532","features":["scheduler"],"vendor":{"name":"The Apache Software Foundation"}}
```
5. Always print the version number and the git hash at info level into the log on startup. Examples:
```
[info] 2018-05-02T18:33:16.364837Z node1@127.0.0.1 <0.237.0> -------- Apache CouchDB 2.2.0-dev (git hash 47a38d3d0) is starting.
[info] 2018-05-02T18:54:01.657777Z couchdb@127.0.0.1 <0.204.0> -------- Apache CouchDB 2.1.1 (git hash f84faa532) is starting.
```

## Context
As a release manager, I want to ensure that any and all builds of CouchDB are traceable to the exact source code used to build them. This extends to and includes all development builds, release candidate builds, and official release builds.

**Comment by wohali** [comment]
I've revised the proposal to clarify how the output should differ between a dev build and a release candidate/actual release.

With the above proposal, the goals of distinguishing between dev builds, RCs and actual releases are met.

**Comment by dch** [comment]
sounds good to me. If we add this info to the version field via `default.*/local.*` it would allow people who wish not to display it (e.g. naked couch on the internet, not that we advise it) to hide it.

**Comment by dch** [comment]
or should this be something available only to admins under `/_config/` ?

**Comment by wohali** [comment]
I don't really see the point of hiding it or making hiding configurable.

We've been showing the specific version number since time immemorial. It's used by the replicator and PouchDB to determine compatibility for various things. For 99.99% of the people out there (anyone running a release, not a dev version) that version number maps to a well-known git hash - so for all these people, the version number and the hash should be synonymous. A mismatch would be an indication that someone is running the wrong thing.

Up until now `GET /` on a master build will return the next version # to be released + the git hash, so hiding it would be a new feature.

If you want to hide the field, you could do filtering at your reverse proxy - which is our standard recommended deployment architecture anyway, right? :)

**Comment by janl** [comment]
I think we need to leave the `version` field in `/` untouched, I’d be worried about breaking things there. It is derived from the Erlang app version of CouchDB, as are the log entries. As such, going with the additional `git_hash`-field for `/` is I think the best option. For logs, we’d have to adjust couch_log to include the hash specifically.

**Comment by wohali** [comment]
Since the PR may not land, I am reopening this one.

We need a way to distinguish RCs from release builds, and it would be best if the build itself can report its own git hash. Somehow. But probably not the way we currently do it.
