### ISSUE TITLE
couchdb_http_proxy_tests:306: should_refuse_connection_to_backend...*timed out*

### ISSUE THREAD

**Issue by dch** [apache/couchdb#1312]
## Expected Behavior

100% of eunit tests pass 100% of the time on 100% of even the most obscure OS and versions?

## Current Behavior

> gmake check
> ...
> couchdb_http_proxy_tests:306: should_refuse_connection_to_backend...*timed out*

## Possible Solution

Likely this is a race condition on my excessively fast desktop 🗡 

## Steps to Reproduce (for bugs)

1. `gmake check`

## Context

- 100% repeatable failure in eunit tests during RC testing on FreeBSD 12.0-CURRENT amd64.

## Your Environment

* Version used: 2.1.x branch
* Operating System and version (desktop or mobile): FreeBSD 12.0-CURRENT amd64

**Comment by wohali** [comment]
FYI this fails in Travis too. I saw it just a few days ago.

**Comment by johs** [comment]
See https://github.com/apache/couchdb/issues/1054
Same issue?

**Comment by janl** [comment]
Can’t reproduce on a beefy CPU-optimised quad-core DigitalOcean VM running FreeBSD 11.2.

@dch might you be able to give me ssh access to your box?

**Comment by wohali** [comment]
Just saw this again today with @dch on his box. I can't reproduce either. He's getting there via 

```
/configure -c --skip-deps --disable-docs --disable-fauxton
gmake check
```

**Comment by dch** [comment]
@janl I'll pm you the details

**Comment by dch** [comment]
@janl I'll pm you the details

**Comment by wohali** [comment]
Too old to act on; removing it unless we see recurrence.
