### ISSUE TITLE
Unbalanced load with cluster when load comes from replication

### ISSUE THREAD

**Issue by irishmark** [apache/couchdb#1313]
I am currently load testing a couchDB 2.1.1 3-node cluster. The load upon this cluster comes from two calls, a replication call (for a single table) and a REST call for an indexed document. By far the majority of the CPU load on the cluster comes from the replication call. (it's also called at the highest rate)

When we load test we observe that a single node gets 95% of the load. Immediately repeating the test causes a different node to receive all the load (the cluster is n=3)

Doing some investigation if I ask each node for the first 10 records of the replication call I get a different lastSEQ value for each node. 
Is this expected?

It seems to me that the unbalancing is because the SEQ chain it adopts for the replication only seems to be valid for a single node and this is the overloaded node. (all our clients are pre-seeded with a partially replicated DB and a single "lastSEQ" value, which appears to only be valid for a single node)

So, I'm trying to work out if this is how it's supposed to work or if we have something wrong in our setup which is causing us to have differing SEQ chains on each node. Or perhaps something else is causing our uneven load?

Could this behaviour be caused by an un-matched uuid or admin hash? I don't think these match in our cluster

**Comment by wohali** [comment]
Each replication request is mediated by a single node on the cluster. If you start 2 replications, they should each be mediated by different nodes on the cluster. With multiple replications happening at the same time, the load will be spread acceptably across the entire cluster.

The seq value contains information about the node from which you made the query. This is also completely normal.

If you are replicating documents with attachments, or using SSL, there are known bugs in 2.1.1 that will be addressed in the forthcoming 2.2.0 release.
