### ISSUE TITLE
Different behavior "sorting" in the couchdb in version 2.1.0 and 2.1.1

### ISSUE THREAD

**Issue by glonco** [apache/couchdb#1315]
When we are using query with sort by field which is missing in the record, so in the verison 2.1.0 records are returned without sorting (It is fine because field which was using for sort, is missing) but in the version 2.1.1 any records are not returned.

## Expected Behavior
It should be work same in the both version of couch db.

## Current Behavior
Different behaviour for two version of couch db.

## Steps to Reproduce (for bugs)
Precondition:
Exist record e.g.: 
`{
  "_id": "e936c533a3bb0bc923c648a9c3f37c42",
  "_rev": "2-ad45658e502c44ba8e1d45c363f9d9f0",
  "name": "test1"
}`
1. Execute query `{
   "selector": {
      "name": {
         "$eq": "test1"
      }
   },
   "limit": 100,
   "sort": [
      {
         "test": "desc"
      }
   ]
}`

Current
2.1.0 - record is returned.
2.1.1 - record is not returned.

Expected
2.1.0 - record is returned.
2.1.1 - record is returned.

**Comment by popojargo** [comment]
My guess: It was an actual bug.

You can simply rewrite your query to check if **test** $exists in your object or if it's greater than null.

**Comment by wohali** [comment]
There have been a couple of bugs related to selectors that have been recently fixed.

What happens if you use the `GET /{db}/_explain` endpoint on your queries?

See: https://github.com/apache/couchdb/pull/866 and https://github.com/apache/couchdb/pull/962

These fixes will be in CouchDB 2.2.0.

**Comment by willholley** [comment]
@glonco just to confirm, this change was intentional (see the [release notes](http://docs.couchdb.org/en/latest/whatsnew/2.1.html#mango)). 

That said, I'm a bit curious how your query used to work, since `sort` requires an index, and a document would only be included in the index if the field you're sorting on exists. I'd like to see the output of `_explain` from both CouchDB versions as well.

**Comment by glonco** [comment]
I created index for field "test" in both version of couch db.
Here you can see explain from both versions of couch db:
v2.1.0 ->
`
{
    "dbname": "test",
    "index": {
        "ddoc": null,
        "name": "_all_docs",
        "type": "special",
        "def": {
            "fields": [
                {
                    "_id": "asc"
                }
            ]
        }
    },
    "selector": {
        "name": {
            "$eq": "test1"
        }
    },
    "opts": {
        "use_index": [],
        "bookmark": "nil",
        "limit": 100,
        "skip": 0,
        "sort": {
            "test": "desc"
        },
        "fields": "all_fields",
        "r": [
            49
        ],
        "conflicts": false,
        "stale": false,
        "update": true,
        "stable": false
    },
    "limit": 100,
    "skip": 0,
    "fields": "all_fields",
    "range": {
        "start_key": null,
        "end_key": "\ufffd"
    }
}`
v2.1.1 ->
`{
    "error": "error",
    "reason": "{invalid_object,{<<\"\ufffd\ufffd\ufffd\ufffd\">>}}"
}`
Here it is error.

So It is bug in the version 2.1.1 or it was bug in the version2.1.0 ?

**Comment by janl** [comment]
It was a bug in 2.1.0 that was fixed in 2.1.1.

Just goes to show: one person’s bug fix is another’s breaking change :/

Sorry for the trouble!
