### ISSUE TITLE
cannot disable 'Launch Admin Console at Start'

### ISSUE THREAD

**Issue by sdahlbac** [apache/couchdb#1318]
## Expected Behavior

In the CouchDB menu, there is an option 'Launch Admin Console at Start' that is checked.
When clicking it I would expect that it would get unchecked, and the next time I start CouchDB another browser tab would *not* get opened.
But, the item remains checked and the Admin Console is automatically opened 😞 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 2.1.1
* Browser Name and version:
* Operating System and version (desktop or mobile): OS X 10.13.4
* Link to your project:

**Comment by wohali** [comment]
Technically, the macOS download is only a convenience binary and not built using official Apache CouchDB assets.

You can find the repository used for those builds here: https://github.com/janl/couchdb-mac-app

You might want to open the issue there, not here.
