### ISSUE TITLE
Missing total_rows using _find

### ISSUE THREAD

**Issue by skycult** [apache/couchdb#1323]
Hi there,

there is a workaround to obtain the field total_rows using _find?
Thank you very much.

**Comment by felix9ia** [comment]
@janl This does not seem to be the way to solve this problem, total_rows is the number of all documents that meet the conditions, the official can give us a demo to handle total_rows, and not chained

**Comment by felix9ia** [comment]
I created a view and the result is the total_rows field. Is this correct?

**Comment by wohali** [comment]
@felix9ia The question is asking about using `_find`, not views.

**Comment by skycult** [comment]
Hi there nothing about this question?
Any suggestion is appreciated.

**Comment by garrensmith** [comment]
At this point its not really possible to work out the `total_rows` for a mango query. A mango query could use the _all_docs index for a query so then `total_rows` would be all the documents in your database. Or it could use a specific index which is then a different number of `total_rows`. Even if mango uses a specific index it will do some in memory processing of the query to reduce the number of documents that are returned so again `total_rows` would be different. Ideally we need to add in aggregation support to mango that it would be possible to run a count for a specific query and know how many docs would be returned for a query.
