### ISSUE TITLE
Log index-less mango queries to couchdb.log

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#1324]
As the title says. If people are running mango queries that have no index, mention it in couchdb.log for forensic performance analysis later. The warning in the JSON response gets lost in the client and often ignored.

**Comment by garrensmith** [comment]
This is a nice idea. The big thing is what do we want to log without exposing too much user information? Would logging the fields in the selector without the values be ok?

**Comment by nickva** [comment]
This was implemented in https://github.com/apache/couchdb/pull/4483. We emit log reports which include in-indexed mango queries.

There are additional mango metrics, too: https://github.com/apache/couchdb/pull/2410
