### ISSUE TITLE
Invalid bind_address issue on version 2.1.1 on mac

### ISSUE THREAD

**Issue by navneet21sharma** [apache/couchdb#1325]
I am having CouchDB 2.1.1 for mac and having same issue. When I start couchDB then it start opening new tab with address http://127.0.0.1:5984/_utils/ and refused to connect. It continue to open until I force quit it.
Please find crash log file
[CouchDB2.log](https://github.com/apache/couchdb/files/1997786/CouchDB2.log)

I tried to locate local.ini file to change address to 127.0.0.1 or 0.0.0.0 . I find local.ini  at /Applications/Apache\ CouchDB.app/Contents/Resources/couchdbx-core/etc/local.ini 
I looked at [chttpd] bind_address , It was already 127.0.0.1 so I tried with 0.0.0.0 but still facing the same issue.
Please find local.ini file and default.ini file and let me know what is wrong with it.

[ini_files.zip](https://github.com/apache/couchdb/files/1997790/ini_files.zip)

**Comment by navneet21sharma** [comment]
I reinstalled this software but again getting the same issue.

**Comment by wohali** [comment]
@navneet21sharma you closed this issue so I presume you found the problem?

**Comment by cmit-emrekorpe** [comment]
@navneet21sharma how did you find solution?
