### ISSUE TITLE
"os_mon: Missing application directory."}

### ISSUE THREAD

**Issue by sayakpaul** [apache/couchdb#1327]
Couch DB 2.1.1 installation is getting failed at the last step of rel (generate) on Red Hat Linux 7.3. The compilation was fully successful. Following is the full trace of what I get in the error:

ERROR: generate failed while processing /home/1251148/apache-couchdb-2.1.1/rel: {'EXIT',{{badmatch,{error,"os_mon: Missing application directory."}},
         [{rebar_reltool,generate,2,
                         [{file,"src/rebar_reltool.erl"},{line,53}]},
          {rebar_core,run_modules,4,[{file,"src/rebar_core.erl"},{line,493}]},
          {rebar_core,execute,6,[{file,"src/rebar_core.erl"},{line,418}]},
          {rebar_core,maybe_execute,8,
                      [{file,"src/rebar_core.erl"},{line,302}]},
          {rebar_core,process_dir1,7,[{file,"src/rebar_core.erl"},{line,261}]},
          {rebar_core,process_each,5,[{file,"src/rebar_core.erl"},{line,351}]},
          {rebar_core,process_dir1,7,[{file,"src/rebar_core.erl"},{line,253}]},
          {rebar_core,process_commands,2,
                      [{file,"src/rebar_core.erl"},{line,93}]}]}}
make: *** [release] Error 1

**Comment by wohali** [comment]
This says that you do not have the os_mon Erlang application correctly installed.

Try reinstalling Erlang - especially, use the erlang packages provided here: https://packages.erlang-solutions.com/ .
