### ISSUE TITLE
can't get current statics by _stats

### ISSUE THREAD

**Issue by taicao88** [apache/couchdb#1335]
Can't get current request time by _stats
config stats_collector failed

**Comment by wohali** [comment]
The endpoint moved to `/_node/_local/_stats` in 2.x

**Comment by taicao88** [comment]
Dear Vohali

{"value":7258,"type":"counter","desc":"number of HTTP requests"}

can't get value current only show sum value in 2.1.1

**Comment by wohali** [comment]
```
$ curl localhost:15984/_node/_local/_stats | jq .couchdb.httpd.requests
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13920  100 13920    0     0   937k      0 --:--:-- --:--:-- --:--:--  970k
{
  "value": 17,
  "type": "counter",
  "desc": "number of HTTP requests"
}
```

**Comment by taicao88** [comment]
Dear Wohali, 

How to get the same below

"httpd": {
  "requests": {
    "description": "number of HTTP requests",
    "current": 191458567.0,
    "sum": 191458567.0,
    "mean": 71.150999999999996248,
    "stddev": 102.38500000000000512,
    "min": 0,
    "max": 1197
  }
}

**Comment by wohali** [comment]
current and sum are the same. You have to calculate the rest yourself. In a CouchDB 2.x cluster these are better gathered at the load balancer.

a much more valuable statistic for performance management is the httpd.request_time section which includes all the types of measures you're asking for, but on how long it takes CouchDB to respond for each particular request.
