### ISSUE TITLE
Add official support of Couchdb  for Ubuntu 18.04

### ISSUE THREAD

**Issue by codeyash** [apache/couchdb#1343]
Hello,

Please add this task in your 2.2.0 milestone. 

https://github.com/apache/couchdb/issues/1314 (Duplicate of this but it's closed and task is still open)

**Comment by wohali** [comment]
@codeyash The convenience binaries for CouchDB are only semi-official.

Whether that ticket is open or not, the work is ongoing.

**Comment by codeyash** [comment]
Any expected date please?

**Comment by FgfdCBVCbnsebtgf** [comment]
Hello,
I cannot install the couchdb 2.1.1 in Ubuntu 18.04. I use this url:
https://apache.bintray.com/couchdb-deb/dists/bionic/main/

But it returns an error. Any suggestions?  Thank you.

**Comment by wohali** [comment]
Please see https://github.com/apache/couchdb/issues/1314
