### ISSUE TITLE
Auto sharding for CouchDB?

### ISSUE THREAD

**Issue by endyjasmi** [apache/couchdb#1344]
Provide auto sharding and elastic scaling to CouchDB.

## Expected Behavior
It should work somewhat like Amazon Dynamo paper.

## Current Behavior
 Currently CouchDB only support preshard.

## Possible Solution
Maybe we can use [Riak Core](https://github.com/basho/riak_core)? It's in Erlang by the way.

## Context
With this, CouchDB will become more elastically scalable.

**Comment by janl** [comment]
This is a nice feature request, but without a concrete proposal on how to implement it, this is too vague to keep open like this. Please re-open (or send a new PR) with a proposal on how this could be implemented, copious of code references, or a patch would be best :)

We’d likely accept a patch that implements this, if we can agree on an implementation approach. It has been tried before but hasn’t made it into a PR yet. So any progress here would be appreciated.
