### ISSUE TITLE
CentOS package install issue with js library

### ISSUE THREAD

**Issue by leiz340** [apache/couchdb#1350]
centos 7.2
when I exec yum install couchdb ，found error cannot install success
--> Finished Dependency Resolution
Error: Package: couchdb-2.1.1-2.el7.centos.x86_64 (bintray-apache-couchdb-rpm)
           Requires: js = 1:1.8.5
           Installing: 1:couch-js-1.8.5-21.el7.x86_64 (bintray-apache-couchdb-rpm)
               js = 1.8.5-21.el7
           Available: 1:js-1.8.5-20.el7.i686 (base)
               js = 1:1.8.5-20.el7
Error: Package: couchdb-2.1.1-2.el7.centos.x86_64 (bintray-apache-couchdb-rpm)
           Requires: js = 1:1.8.5
           Available: 1:couch-js-1.8.5-21.el7.x86_64 (bintray-apache-couchdb-rpm)
               js = 1.8.5-21.el7
           Available: 1:js-1.8.5-20.el7.i686 (base)
               js = 1:1.8.5-20.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by wohali** [comment]
I was hoping I'd fix this before anyone noticed :)

I'm working on fixing #1293. This problem will be resolved in a few hours. Sorry for the inconvenience.

**Comment by wohali** [comment]
Backed out the changes due to lack of time. This should be resolved for now.

**Comment by leiz340** [comment]
thanks @wohali 
it fine now
