### ISSUE TITLE
[js] reduce_builtin.js: emfile error (ppc64le)

### ISSUE THREAD

**Issue by abdasgupta** [apache/couchdb#1351]
To port couchdb on ppc64le platform, first we need to pass all the test cases. But while executing the command, following error is appearing after few test cases passed.
```
test/javascript/tests/reduce_builtin.js                        
    Error: emfile
Trace back (most recent call first):
    
 551: test/javascript/couch.js
      CouchError([object Object])
 514: test/javascript/couch.js
      ([object CouchHTTP])
 180: test/javascript/couch.js
      ("(function (doc) {emit(doc.keys, [1, 1]);})/* avoid race cond 1527498
 165: test/javascript/tests/reduce_builtin.js
      ()
  37: test/javascript/cli_runner.js
      runTest()
  48: test/javascript/cli_runner.js
      
fail
=======================================================
JavaScript tests complete.
  Failed: 1.  Skipped or passed: 40.
Makefile:140: recipe for target 'javascript' failed
make[1]: *** [javascript] Error 1
make[1]: Leaving directory '/home/abdasgupta/couchdb'
Makefile:103: recipe for target 'check' failed
make: *** [check] Error 2
```
## Expected Behavior

The test case `test/javascript/tests/reduce_builtin.js` should pass.

## Steps to Reproduce (for bugs)

1. Run `make check`
2.
3.
4.

## Your Environment

* Version used: upstream master branch
* Browser Name and version:
* Operating System and version (desktop or mobile): Ubuntu 16.04.4 LTS on ppc64le
* Link to your project:

**Comment by wohali** [comment]
emfile often means too many open files. Can you try increasing your ulimit for files (`ulimit -n`) beyond the default 4096?

**Comment by abdasgupta** [comment]
Hi @wohali 

All test cases are passing now after increasing the ulimit to 188898 . I am closing this issue as it is resolved. Thank you.
