### ISSUE TITLE
Restore /{db}/purge endpoint

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#1352]
Work is ongoing to restore purge functionality in a clustered database: https://github.com/apache/couchdb/commit/5230cf01d847705171ab28d8219dbef1c2d6f2a6

This ticket is to track these PRs landing.

It'd be ideal if these can land in 2.2.0, but if the work is going to take a while, let's push out to 2.2.1 or 2.3.0.

/cc @davisp @jiangphcn

**Comment by janl** [comment]
@wohali I’ve been closing issues that have corresponding PRs, feel free to open, if you want a unified place for multiple PRs

**Comment by jiangphcn** [comment]
Added reference to https://github.com/apache/couchdb/pull/1370
