### ISSUE TITLE
Numbers in documents get rounded down without explaination.

### ISSUE THREAD

**Issue by Panossa** [apache/couchdb#1372]
I don't know whether it's a feature or a bug. But if it's meant to be this way it's not obvious why and I never saw anyone writing about this:
When I save the following document:
{"server_id": 369553424691494913}

## Expected Behavior
I expect when I open up the document (after saving it) in Futon or I'm getting it via GET I get this:
{"server_id": 369553424691494913} //without "" around the number

## Current Behavior
Response:
{"server_id": 369553424691494900} //btw it rounds down on 1-2 decimals every time, not only with this number

## Possible Solution
Either showing a warning about precision or save it the right way.

## Steps to Reproduce (for bugs)
1. Saving e.g. the document {"server_id": 369553424691494900}
2. GETting it.

## Context
I'm saving server ids in the database as numbers so I can use them without converting them back from strings to numbers.

## Your Environment
* Version used: 2.1.1
* Browser Name and version: Chrome Canary 69.0.3448.0 (64 bit)
* Operating System and version (desktop or mobile): Win7 64bit Home Pr.

**Comment by wohali** [comment]
This is a limitation of integers in JavaScript/JSON, and is not limited to CouchDB. For instance, if I open the console in my Firefox 60.0.1 browser:

```
q = 369553424691494913
369553424691494900
q
369553424691494900
```

If you want to ensure the number is stored verbatim, store it as a string, and perform string-to-long-integer conversion in your application.
