### ISSUE TITLE
Possibility of running CouchDB in same BEAM as Erlang/Elixir app? 

### ISSUE THREAD

**Issue by Qqwy** [apache/couchdb#1381]
We are building an application using Elixir, and we are wondering how difficult it would be to talk to CouchDB directly, because it feels like a shame to run it seoarately in its own BEAM and perform serialization/deserialization of data structures all the time.

Is this in any way possible, or is CouchDB currently just not built for that?

**Comment by wohali** [comment]
Currently not built for that.

Pull requests welcome :)
