### ISSUE TITLE
Couchdb documentation for json index definition is unclear on support for indexing array fields

### ISSUE THREAD

**Issue by worldspawn** [apache/couchdb#1388]
The documentation here http://docs.couchdb.org/en/2.1.1/api/database/find.html#db-index says 

>Index object format for JSON type indexes
>The index object is a JSON array of field names following the sort syntax. Nested fields are also allowed, e.g. “person.name”.

It doesn't explicitly state that indexing array fields is allowed. It doesnt' provide an example of how to do it if it is.

To clarify, given: 
```{
  "_id": "theid",
  "results": [
    { "type": "sometype" }
  ]
}
```

I know i can query that with the $elemMatch selector but can it be indexed too? I've read a few examples suggesting that a notation like "results[].type" or "results.[].type" can be used but in my own tests I always get a warning stating that no matching index could be found.

**Comment by wohali** [comment]
You specifically mean indexing a subfield of an object in an array, correct? Not just the elements of the array itself?

**Comment by worldspawn** [comment]
Yes, indexing a field on an element (at an unknown index) of an array.
