### ISSUE TITLE
View with wrong result, filtering by year month date

### ISSUE THREAD

**Issue by touy** [apache/couchdb#1389]
I have create a view to filter data by year , month, day , code as below
function (doc) {
     var d = new Date(doc.gpstime); 
if (d != null) {
 var key = [d.getFullYear(),d.getMonth()+1,d.getDate()
];
emit([key,doc.imei], null);
} 
}
- couchdb 2.0 and 2.1.1 ( I thought it was about the version then I upgrade from 2.0 to 2.1, but it's not)
- nodejs V10
- Centos 6.5
which above code , working perfectly on Windows ( I guessed!) because I download backup from Centos server 6.5 and re insert to couchdb on Windows , 
above code is to call all data with specific year , month and date, then I would put them in to array for processing , 
there are processes that I call that function 
- auto by timer , every 5 minutes
- and manually 
by the way , there are some data from the next date shown, as i queried for 2018,6,14  but there are some data from 2018,6,15 
, then I tried to search data on browser with id that shown on 2018,6,14 , and found  it is not exist 
 on 2018,6,15 
, then I updated that data  ( just changed some text value) , then I search on webrowser again on 2018,6,14 then I could not found it there , but I found on 2018,6,14 so this is the solution to fix this issue 
why it has this strange behavior , the result of view was wrong ? 
I didn't config any clusters on my server

the result on the console right hand side
![image](https://user-images.githubusercontent.com/122671/41471653-73941d42-70de-11e8-82fa-639d56bb37eb.png)
![image](https://user-images.githubusercontent.com/122671/41471668-7c2ddff6-70de-11e8-80e0-14eaac7d751a.png)

I query on webbrowser 

![image](https://user-images.githubusercontent.com/122671/41471683-89eef0b2-70de-11e8-8373-f4d6723a665c.png)

**Comment by wohali** [comment]
Hi @touy, I'm having trouble understanding you.

Can you share the exact values of `doc.gpstime` that are not being emitted in your view correctly?

I suspect you may be running into timezone issues - is the time zone on all of your machines UTC? (This is highly recommended for servers.)

**Comment by touy** [comment]
yes, doc.gpstime is : 2018-06-16T01:00:54+07:00
from raw data before I insert to the database 
 deviceinfo.gpstime = moment.utc(util.format("20%s-%s-%s %s:%s:%s", _year, _month, _date, _hour, _minute, _second), 'YYYY-MM-DD HH:mm:ss');
deviceinfo.gpstime = this.convertTZ(deviceinfo.gpstime);
 
# my timezone conversion as below:
convertTZ(fromTZ) {
        process.env.TZ = 'Asia/Vientiane'; 
        return moment.tz(fromTZ, "Asia/Vientiane").toDate();
}
value not from view : "gpstime": "2018-05-17T12:40:37+07:00",

it's true that I sometime have a problem when I want to convert to timzone, sometime correct sometime is not correct ( reverse value)
my laptop is +7 , 
my server +00:00 UTC 
so it's about timezone ?  I thought I convert all value to +7 timezone which it could avoid the issue, any recommend lease ?

**Comment by wohali** [comment]
Happy to keep discussing this, but this is not a CouchDB bug.

**Comment by touy** [comment]
no, I expected "2018 06 16", per my time data , with new Date() which it convert to UTC and I need to convert back to my time zone right , which method is the best here ?

**Comment by touy** [comment]
so I need to put 
doc.gpstime=doc.gpstime.replace('+07:00',''); 
which it works accordingly , think you
