### ISSUE TITLE
Unexpected CouchDB crash

### ISSUE THREAD

**Issue by gnujeremie** [apache/couchdb#1391]
## Current Behavior
Couchdb randomly crashes, with no error in couchdb logs.

## Context
Server was running, no requests were sent. We noticed it crashed when we tried to use it several days later.

## Your Environment

* Version used: couchdb 2.1.1
* Browser Name and version:
* Operating System and version (desktop or mobile): Ubuntu 14.04, 32bits, built from sources.

## Crash log

```/var/log/apport.log.1``` : 
```
ERROR: apport (pid 25334) Fri Jun 15 17:08:48 2018: called for pid 3790, signal 6, core limit 0, dump mode 1
ERROR: apport (pid 25334) Fri Jun 15 17:08:48 2018: executable: /opt/couchdb/erts-5.10.4/bin/beam.smp (command line "/opt/couchdb/bin/../erts-5.10.4/bin/beam.smp -K true -A 16 -Bd -- -root /opt/couchdb/bin/.. -progname couchdb -- -home /home/couchdb -- -boot /opt/couchdb/bin/../releases/2.1.1/couchdb -name couchdb@127.0.0.1 -setcookie monster -kernel error_logger silent -sasl sasl_error_logger false -noshell -noinput -config /opt/couchdb/bin/../releases/2.1.1/sys.config")
ERROR: apport (pid 25334) Fri Jun 15 17:08:48 2018: is_closing_session(): no DBUS_SESSION_BUS_ADDRESS in environment
ERROR: apport (pid 25334) Fri Jun 15 17:17:32 2018: wrote report /var/crash/_opt_couchdb_erts-5.10.4_bin_beam.smp.106.crash
```

I have the crash dump from ```/var/crash/_opt_couchdb_erts-5.10.4_bin_beam.smp.106.crash```, can I post it somewhere ? (I mean, I checked the file and it does not seem to have confidential informations like credentials or something, but I just want to be sure).

**Comment by wohali** [comment]
That log is an error from apport, not couchdb, and won't help us much. You can fix the DBUS_SESSION_BUS_ADDRESS with https://stackoverflow.com/questions/41242460/how-to-export-dbus-session-bus-address before you launch X.

You can post the crash dump here or in a gist, but I'm not sure it will have anything useful.

Can you try running couchdb in a terminal, or screen/tmux session rather than as a daemon, then see what errors it turns up in that session?

**Comment by gnujeremie** [comment]
There is no X server running on the machine running couchdb.
I'll start it again in a tmux session, and see what happens.

The crash dump is 330Mo~, I'll post it somewhere and add the link here after.

**Comment by gnujeremie** [comment]
Here the crash dump, if it can help : https://framadrop.org/r/r_FeDWz5o6#Qw8+XI0wjZHXJFmE6bWK2vpijbNc9bUwfVfJjt4iuNg=

**Comment by wohali** [comment]
The log is not useful. As it contains a coredump, I've removed the link.

We need to see the stdout/stderr output to diagnose further.

**Comment by janl** [comment]
please reopen with more info
