### ISSUE TITLE
query view with multiple key values, but get wrong result

### ISSUE THREAD

**Issue by altairlee** [apache/couchdb#1395]
I create a view with the Map function:

    function(doc) {
        if (doc.market == "m_warehouse") {
            emit([doc.logTime,doc.dbName,doc.tableName], 1);
        }
    }

and using the api to query :

    http://10.23.244.33:8080/org1channel_access%24record/_design/_v_select_data/_view/new-view/?limit=10&skip=0&include_docs=false&reduce=false&descending=true&startkey=["2018-06-19T09:16:47,527","stage"]&endkey=["2018-06-19T09:16:43,717","stage"]

&startkey=["2018-06-19T09:16:47,527","stage"]&endkey=["2018-06-19T09:16:43,717","stage"]

but I got the result : 

    {
    "total_rows": 248133,
    "offset": 248129,
    "rows": [
        {
            "id": "01CGBPYVXVD88FPDVR3NP50VJW",
            "key": [
                "2018-06-19T09:16:47,527",
                "ods",
                "o_ad_dsp_pvlog_realtime"
            ],
            "value": 1
        },
        {
            "id": "01CGBQ6JMEBR8KBMB8T7Q7CZY3",
            "key": [
                "2018-06-19T09:16:44,824",
                "stage",
                "s_ad_ztc_realpv_base_indirect"
            ],
            "value": 1
        },
        {
            "id": "01CGBQ4BKT8S2VDMT2RGH1FQ71",
            "key": [
                "2018-06-19T09:16:44,707",
                "stage",
                "s_ad_ztc_realpv_base_indirect"
            ],
            "value": 1
        },
        {
            "id": "01CGBQ18CBHQX3F28649YH66B9",
            "key": [
                "2018-06-19T09:16:43,717",
                "stage",
                "s_ad_ztc_realpv_base_indirect"
            ],
            "value": 1
        }
      ]
    }
-------------

the key `ods` should not in the result.

did I do something wrong ?

**Comment by wohali** [comment]
No, this is valid.

`["2018-06-19T09:16:47,527","stage"] > ["2018-06-19T09:16:47,527", "ods"]` (try it in a JavaScript console!) and since you specified `descending=true`, the key is emitted.

You can avoid emitting that key by changing your view code, or specifying a startkey of something like `["2018-06-19T09:16:47,527","aaa"]`.

**Comment by wohali** [comment]
@altairlee if you want to do the query you asked, the doc.dbName will have to be first in the key.

You can alternately look at using Mango to do this.

**Comment by altairlee** [comment]
@wohali 
Thanks for the reply. I have used Mango to do this.
