### ISSUE TITLE
Build with Erlang 21

### ISSUE THREAD

**Issue by nickva** [apache/couchdb#1396]
## Expected Behavior

CouchDB should build and run with Erlang 21

## Current Behavior

Main repo and snappy dependency prevent building with Erlang 21

Also unit tests fails

## Possible Solution

Update deps and fix tests

**Comment by nickva** [comment]
PR to update snappy to build with Erlang 21 https://github.com/apache/couchdb-snappy/pull/7

**Comment by davisp** [comment]
I'll take a look at the couch_log test failures today.

**Comment by davisp** [comment]
Well this might have something to do with it:

```
OTP-13295    Application(s): erts, kernel, sasl, stdlib

               A new logging API is added to Erlang/OTP, see the
               logger(3) manual page, and section Logging in the
               Kernel User's Guide.

               Calls to error_logger are automatically redirected to
               the new API, and legacy error logger event handlers can
               still be used. It is, however, recommended to use the
               Logger API directly when writing new code.
```

**Comment by davisp** [comment]
Working through eunit failures. We'll need to merge this branch to mochiweb as well:

https://github.com/apache/couchdb-mochiweb/compare/master...cloudant:fix-parameterized-module-errors

**Comment by davisp** [comment]
My unit test work is on this branch:

https://github.com/apache/couchdb/compare/fix-erlang-21-eunit-failures

Now getting errors from the test suite in couch and I have a hunch its related to the new fully async link/monitor/send primitives which aught to make fixing these super duper fun.

**Comment by davisp** [comment]
Also that's a dirty diff cause I wasn't careful about removing auto-whitespace trimmed hunks. Will clean it up later.

**Comment by davisp** [comment]
Also this change:

```
OTP-14901    Application(s): erts

               Optimized the common case of monitor followed by send
               to the same local process. The monitor signal is now
               delayed in order to be piggybacked with the sent
               message and thereby only get one lock operation on the
               message queue of the receiver. A delayed monitor signal
               is flushed if no send has been done at the latest when
               the process is scheduled out.
```
