### ISSUE TITLE
backoff after replication failure should be configurable

### ISSUE THREAD

**Issue by nerdvegas** [apache/couchdb#1399]
I have multiple remote clusters connected via bidirectional replication jobs. Sometimes there are extended outages preventing one cluster from seeing another, and I would like replication to start working again in short order once the outage is resolved. However, it seems I can't set the backoff factor, and replication can take a long time to retry. If I manually restart my nodes, everything works, ie replication starts working again. It seems that I just need this to be configurable - I would like crashing replication jobs to retry at least once per 5 minutes.

## Expected Behavior
See above - crashing replication jobs should retry after a max configurable delay, rather than exponentially backing off with no control over the backoff params.

## Current Behavior
No control over how long it takes for a crashing replication job to retry.

## Context
This is a problem for me currently, I have to work around it by implementing my own systemd timer which checks for crashing replication jobs every 5 mins and restarts the couch node in order to force replication retry.

## Your Environment
Couchdb v2.1.0, Cent 7.

**Comment by wohali** [comment]
@nickva has anything changed on this front since 2.1.0?

**Comment by nickva** [comment]
Can try to adjust these two `[replicator]` settings:

`retries_per_request = 5` : increase this to say 15, this way on a temporary failure requests will be retried without crashing the job

`max_history = 20` : decrease this to 7. This limits the length of history of crashed events for each job and determines how long the backoff will be. The longer the history, the longer the consecutive failure count, the larger the delay.  The base delay is 30 seconds, then there are pairs of start, stop or crash events. So with 7 the max delay would be `30*2^(7/2)` which is about 4 minutes.

**Comment by nickva** [comment]
@nerdvegas did max_history and retries_per_request help solve the problem?
