### ISSUE TITLE
500 internal server error on most of the actions on v2.1.1

### ISSUE THREAD

**Issue by rambhavaraju** [apache/couchdb#1400]
While creating, deleting or verifying the couchdb installation v 2.1.1 I'm seeing 500 internal server error. We have set up couchdb in cluster mode having two nodes. Issue over here is that the dbs or the document which are created on one node aren't getting replicated on the other

## Expected Behavior
We are testing 2.1.1 to run on cluster mode. After the set up we are having quite a few issues and most of the time what we see is 500 internal server error for most of the actions. Expected behavior is that any new db, update to db, create doc, update doc should be replicated across the nodes.

## Current Behavior
Error log while verifying installation
[notice] 2018-06-22T11:14:16.943528Z couchdb@127.0.0.1 <0.7285.3> 964b764704 104.211.231.107:5984 49.206.247.114 undefined GET /verifytestdb_replicate 404 ok 1
[notice] 2018-06-22T11:14:16.943697Z couchdb@127.0.0.1 <0.7286.3> 71adb2bb16 104.211.231.107:5984 49.206.247.114 undefined GET /verifytestdb 404 ok 2
[notice] 2018-06-22T11:14:17.016987Z couchdb@127.0.0.1 <0.7286.3> ef43a04ff2 104.211.231.107:5984 49.206.247.114 undefined PUT /verifytestdb 500 ok 49
[notice] 2018-06-20T10:25:32.755698Z couchdb@127.0.0.1 <0.26596.1> 05771e5351 10.4.0.10:5984 10.4.0.5 undefined POST /_replicate 500 ok 12425
[notice] 2018-06-20T10:26:27.503335Z couchdb@127.0.0.1 <0.28085.1> cd2aa5b896 10.4.0.10:5984 10.4.0.5 undefined POST /_replicate 500 ok 7791
[notice] 2018-06-21T10:35:20.666224Z couchdb@127.0.0.1 <0.29146.1> 5b6f1f0fb7 localhost:5984 127.0.0.1 undefined POST /_session 500 ok 1
[notice] 2018-06-22T06:50:02.435660Z couchdb@127.0.0.1 <0.2370.0> 9d73c575b4 104.211.231.107:5984 49.206.247.114 undefined PUT /sk0v 500 ok 56
[notice] 2018-06-22T06:53:17.557656Z couchdb@127.0.0.1 <0.4183.0> 87c44232e9 104.211.231.107:5984 49.206.247.114 undefined PUT /testreplication 500 ok 62
[notice] 2018-06-22T07:09:37.425648Z couchdb@127.0.0.1 <0.29141.0> 4a41aaa3b0 104.211.231.107:5984 49.206.247.114 undefined PUT /sks 500 ok 60
[notice] 2018-06-22T07:39:33.505077Z couchdb@127.0.0.1 <0.3340.2> c8b3f7ab75 104.211.231.107:5984 49.206.247.114 undefined PUT /test3 500 ok 51
[notice] 2018-06-22T07:45:26.334366Z couchdb@127.0.0.1 <0.11053.2> 3ed6480ea1 104.211.231.107:5984 49.206.247.114 undefined GET /_cluster_setup 500 ok 1
[notice] 2018-06-22T07:47:49.639692Z couchdb@127.0.0.1 <0.13403.2> 51a6141a94 104.211.231.107:5984 49.206.247.114 undefined GET /_cluster_setup 500 ok 1
[notice] 2018-06-22T07:48:31.360295Z couchdb@127.0.0.1 <0.15162.2> 69a217f125 104.211.231.107:5984 49.206.247.114 undefined DELETE /sks 500 ok 30
[notice] 2018-06-22T07:48:40.523655Z couchdb@127.0.0.1 <0.15353.2> 258808ba5f 104.211.231.107:5984 49.206.247.114 undefined GET /_cluster_setup 500 ok 1
[notice] 2018-06-22T07:49:46.581600Z couchdb@127.0.0.1 <0.16461.2> cf937d8735 104.211.231.107:5984 49.206.247.114 undefined GET /_cluster_setup 500 ok 10
[notice] 2018-06-22T07:52:01.994985Z couchdb@127.0.0.1 <0.16462.2> 835de0165f 104.211.231.107:5984 49.206.247.114 undefined GET /_cluster_setup 500 ok 1
[notice] 2018-06-22T08:51:15.595177Z couchdb@127.0.0.1 <0.20890.4> 9854e779bc 104.211.231.107:5984 49.206.247.114 undefined DELETE /pjalice 500 ok 16
[notice] 2018-06-22T08:51:21.612303Z couchdb@127.0.0.1 <0.21036.4> ec0aab2c6d 104.211.231.107:5984 49.206.247.114 undefined DELETE /pjtest3 500 ok 22
[notice] 2018-06-22T08:51:31.294286Z couchdb@127.0.0.1 <0.21068.4> 26d6ce2b46 104.211.231.107:5984 49.206.247.114 undefined DELETE /sk 500 ok 17
[notice] 2018-06-22T08:51:37.555270Z couchdb@127.0.0.1 <0.21614.4> c4cdb66ad5 104.211.231.107:5984 49.206.247.114 undefined DELETE /sk0c 500 ok 21
[notice] 2018-06-22T08:51:42.984399Z couchdb@127.0.0.1 <0.21742.4> e5251ad0ac 104.211.231.107:5984 49.206.247.114 undefined DELETE /sk0v 500 ok 20
[notice] 2018-06-22T08:51:48.521926Z couchdb@127.0.0.1 <0.21742.4> aa6e728460 104.211.231.107:5984 49.206.247.114 undefined DELETE /sk0x 500 ok 23
[notice] 2018-06-22T08:51:54.106140Z couchdb@127.0.0.1 <0.21982.4> 3fc1e320d2 104.211.231.107:5984 49.206.247.114 undefined DELETE /sk1 500 ok 18
[notice] 2018-06-22T08:51:59.392684Z couchdb@127.0.0.1 <0.21982.4> 330e078922 104.211.231.107:5984 49.206.247.114 undefined DELETE /sk2 500 ok 24
[notice] 2018-06-22T08:52:42.195806Z couchdb@127.0.0.1 <0.23005.4> 3468ebe4f8 104.211.231.107:5984 49.206.247.114 undefined GET /_cluster_setup 500 ok 1
[notice] 2018-06-22T08:59:15.208870Z couchdb@127.0.0.1 <0.29772.4> 1e0db43058 104.211.231.107:5984 49.206.247.114 undefined DELETE /a08bff453daa133c55178ea0196b15dfd29e38424 500 ok 27
[notice] 2018-06-22T08:59:20.808063Z couchdb@127.0.0.1 <0.29772.4> 7726be0340 104.211.231.107:5984 49.206.247.114 undefined DELETE /a38440af1fb090697f01d0c8c611258a1d97c5d4e 500 ok 19
[notice] 2018-06-22T08:59:25.603676Z couchdb@127.0.0.1 <0.29772.4> c800817ebb 104.211.231.107:5984 49.206.247.114 undefined DELETE /af1a67363903a6dc3e79924ededab6c0358e4a2f0 500 ok 19
[notice] 2018-06-22T08:59:33.336862Z couchdb@127.0.0.1 <0.30700.4> efb061d841 104.211.231.107:5984 49.206.247.114 undefined DELETE /test3 500 ok 17
[notice] 2018-06-22T08:59:38.034494Z couchdb@127.0.0.1 <0.30700.4> 38177e14a4 104.211.231.107:5984 49.206.247.114 undefined DELETE /testreplication 500 ok 17
[notice] 2018-06-22T09:00:12.592583Z couchdb@127.0.0.1 <0.30700.4> 0999e10873 104.211.231.107:5984 49.206.247.114 undefined GET /_cluster_setup 500 ok 1
[notice] 2018-06-22T09:04:37.004999Z couchdb@127.0.0.1 <0.1357.5> cd83fa611d 104.211.231.107:5984 49.206.247.114 undefined GET /_cluster_setup 500 ok 1
[notice] 2018-06-22T09:12:00.690514Z couchdb@127.0.0.1 <0.3920.5> 90f7082f86 104.211.231.107:5984 49.206.247.114 undefined GET /_cluster_setup 500 ok 1
[notice] 2018-06-22T09:13:31.372597Z couchdb@127.0.0.1 <0.14171.5> dc249809c7 104.211.231.107:5984 49.206.247.114 undefined GET /_cluster_setup 500 ok 1
[notice] 2018-06-22T09:20:49.675008Z couchdb@127.0.0.1 <0.21266.5> 67c2cf2055 104.211.231.107:5984 49.206.247.114 undefined GET /_cluster_setup 500 ok 1
[notice] 2018-06-22T09:25:18.637572Z couchdb@127.0.0.1 <0.26413.5> eca7033cef 104.211.231.107:5984 49.206.247.114 undefined GET /_cluster_setup 500 ok 1
[notice] 2018-06-22T09:27:45.987168Z couchdb@127.0.0.1 <0.26413.5> 12f265a16b 104.211.231.107:5984 49.206.247.114 undefined GET /_cluster_setup 500 ok 1
[notice] 2018-06-22T09:44:00.521708Z couchdb@127.0.0.1 <0.12709.6> cc006961bc 104.211.231.107:5984 49.206.247.114 undefined GET /_cluster_setup 500 ok 1
[notice] 2018-06-22T09:44:58.406102Z couchdb@127.0.0.1 <0.13720.6> a2f939ce12 104.211.231.107:5984 49.206.247.114 undefined GET /_cluster_setup 500 ok 1
[notice] 2018-06-22T11:09:44.254837Z couchdb@127.0.0.1 <0.6539.3> bcfd561c20 104.211.231.107:5984 49.206.247.114 undefined PUT /testdb 500 ok 74
[notice] 2018-06-22T11:14:17.016987Z couchdb@127.0.0.1 <0.7286.3> ef43a04ff2 104.211.231.107:5984 49.206.247.114 undefined PUT /verifytestdb 500 ok 49
[notice] 2018-06-22T11:20:35.088864Z couchdb@127.0.0.1 <0.18652.3> c32b65dc8c 104.211.231.107:5984 49.206.247.114 undefined PUT /cc 500 ok 63

## Your Environment

* Version used: 2.1.1
* Browser Name and version: chrome  67.0.3396.87
* Operating System and version (desktop or mobile): ubuntu 16.04
* Link to your project:

**Comment by wohali** [comment]
I'm afraid there's not enough detail in the log here. Are there any tracebacks in the logfile? When you get a 500 back, what does the JSON say?

Can you describe how you're performing the cluster setup?

Are the nodes able to communicate with each other over all ports, or is there any firewall?

Generally we recommend a 3-node cluster as the smallest cluster size, not 2-node, but a 2-node cluster should work.

**Comment by rambhavaraju** [comment]
Hi @wohali thanks for your response,
I'm afraid whatever i had put in the issue over is exact logs what we have. 
I followed the instructions given on the website for the cluster set up i.e. opening up port 9100-9200 for erlang nodes to talk to each other. I had tested and verified the same. All the ports are open and communication is happening between both the nodes.
Rest of the set up for cluster is done through the couchdb admin portal once the couchdb was up. After doing all of that i started seeing that the data isn't being replicated so when i dug deep i found out i was getting this exceptions in the log.

**Comment by wohali** [comment]
This is unusual, CouchDB should work fine and should be logging more info for a 500 error than this.

Try increasing your logging level to debug and try again. What errors do you see?

**Comment by ondra-novak** [comment]
Getting error 500 when there is poor connection between nodes.  It also causes, that simple GET /db/doc takes about 1 minute to return a value or error (which breaks my common timeout 30 sec per common/stale-view operation)

This issue also happen, when the cluster is configured in mirror-only configuration (all nodes has the same content). When connection to other node is lost (VPN, tunnel connection is broken), the current node need more then 1 minute to switch cluster to unstable mode. During this period, many 500 erros can appear.
