### ISSUE TITLE
CouchDB not working on Windows Linux Subsystem

### ISSUE THREAD

**Issue by peter17ji** [apache/couchdb#1402]
CouchDB can't be started after installing from Launchpad PPA.

## Expected Behavior

This is my first time installing CouchDB.  I'm trying to start the service after installation.

## Current Behavior

peter@DESKTOP:/mnt/c/Users/peter$ sudo add-apt-repository ppa:couchdb/stable -y
gpg: keyring `/tmp/tmpp9604qin/secring.gpg' created
gpg: keyring `/tmp/tmpp9604qin/pubring.gpg' created
gpg: requesting key C17EAB57 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpp9604qin/trustdb.gpg: trustdb created
gpg: key C17EAB57: public key "Launchpad PPA for Apache CouchDB" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
peter@DESKTOP:/mnt/c/Users/peter$ sudo apt update
Hit:1 http://mirrors.163.com/ubuntu xenial InRelease
Hit:2 http://mirrors.163.com/ubuntu xenial-security InRelease
Hit:3 http://mirrors.163.com/ubuntu xenial-updates InRelease
Hit:4 http://mirrors.163.com/ubuntu xenial-proposed InRelease
Hit:5 http://mirrors.163.com/ubuntu xenial-backports InRelease
Get:6 http://ppa.launchpad.net/couchdb/stable/ubuntu xenial InRelease [17.6 kB]
Get:7 http://ppa.launchpad.net/couchdb/stable/ubuntu xenial/main amd64 Packages [1,139 B]
Get:8 http://ppa.launchpad.net/couchdb/stable/ubuntu xenial/main Translation-en [849 B]
Fetched 19.5 kB in 7s (2,648 B/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
peter@DESKTOP-43HDKBI:/mnt/c/Users/peter$ sudo apt install couchdb -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  couchdb-bin couchdb-common erlang-asn1 erlang-base-hipe erlang-crypto erlang-eunit erlang-inets erlang-mnesia
  erlang-os-mon erlang-public-key erlang-runtime-tools erlang-snmp erlang-ssl erlang-syntax-tools erlang-tools
  erlang-webtool erlang-xmerl libmozjs185-1.0 libnspr4 libsctp1
Suggested packages:
  erlang erlang-manpages erlang-doc erlang-edoc erlang-gs erlang-observer lksctp-tools
The following NEW packages will be installed:
  couchdb couchdb-bin couchdb-common erlang-asn1 erlang-base-hipe erlang-crypto erlang-eunit erlang-inets
  erlang-mnesia erlang-os-mon erlang-public-key erlang-runtime-tools erlang-snmp erlang-ssl erlang-syntax-tools
  erlang-tools erlang-webtool erlang-xmerl libmozjs185-1.0 libnspr4 libsctp1
0 upgraded, 21 newly installed, 0 to remove and 0 not upgraded.
Need to get 21.3 MB of archives.
Processing triggers for ureadahead (0.100.0-19) ...
Setting up couchdb-common (1.6.1-0ubuntu6ppa2~xenial1) ...
Setting up erlang-base-hipe (1:18.3-dfsg-1ubuntu3.1) ...
Searching for services which depend on erlang and should be started...none found.
Setting up erlang-crypto (1:18.3-dfsg-1ubuntu3.1) ...
Setting up erlang-eunit (1:18.3-dfsg-1ubuntu3.1) ...
Setting up erlang-mnesia (1:18.3-dfsg-1ubuntu3.1) ...
Setting up erlang-runtime-tools (1:18.3-dfsg-1ubuntu3.1) ...
Setting up erlang-asn1 (1:18.3-dfsg-1ubuntu3.1) ...
Setting up erlang-public-key (1:18.3-dfsg-1ubuntu3.1) ...
Setting up erlang-ssl (1:18.3-dfsg-1ubuntu3.1) ...
Setting up erlang-inets (1:18.3-dfsg-1ubuntu3.1) ...
Setting up erlang-snmp (1:18.3-dfsg-1ubuntu3.1) ...
Setting up erlang-os-mon (1:18.3-dfsg-1ubuntu3.1) ...
Setting up erlang-syntax-tools (1:18.3-dfsg-1ubuntu3.1) ...
Setting up erlang-webtool (1:18.3-dfsg-1ubuntu3.1) ...
Setting up erlang-tools (1:18.3-dfsg-1ubuntu3.1) ...
Setting up erlang-xmerl (1:18.3-dfsg-1ubuntu3.1) ...
Setting up libnspr4:amd64 (2:4.13.1-0ubuntu0.16.04.1) ...
Setting up libmozjs185-1.0 (1.8.5-1.0.0+dfsg-4.5) ...
Setting up couchdb-bin (1.6.1-0ubuntu6ppa2~xenial1) ...
Setting up couchdb (1.6.1-0ubuntu6ppa2~xenial1) ...
invoke-rc.d: unknown initscript, /etc/init.d/couchdb not found.
invoke-rc.d: could not determine current runlevel
Setting up libsctp1:amd64 (1.0.16+dfsg-3) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Processing triggers for ureadahead (0.100.0-19) ...
peter@DESKTOP:/mnt/c/Users/peter$ sudo service couchdb start
[sudo] password for peter:
couchdb: unrecognized service
peter@DESKTOP:/mnt/c/Users/peter$ sudo start couchdb
sudo: start: command not found
peter@DESKTOP:/mnt/c/Users/peter$ uname -a
Linux DESKTOP 4.4.0-17134-Microsoft #112-Microsoft Thu Jun 07 22:57:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
## Possible Solution

Maybe properly write to /etc/init.d path?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by wohali** [comment]
We no longer support the Launchpad PPA or 1.x packages.

For CouchDB 2.x, we provide our own repository. Installation instructions are here:

http://docs.couchdb.org/en/2.1.1/install/unix.html#installation-using-the-apache-couchdb-convenience-binary-packages
