### ISSUE TITLE
Rewrite as function in 1.7.1

### ISSUE THREAD

**Issue by johs** [apache/couchdb#1410]
### Rewrite section a is stringified function
‘Rewrite using JS’ feature was introduced in CouchDB 1.7. If the rewrites field is a stringified function, query server is used to pre-process and route a request.
http://docs.couchdb.org/en/2.1.1/api/ddoc/rewrites.html

## Current Behavior

Installed CouchDB 1.7.1 from source on both Ubuntu and OSX, rewrite seems to be working like 1.6 version, reporting 

    {"error":"rewrite_error","reason":"Rewrite rules are a String. They must be a JSON Array."}

... when served design document with rewrite function that works fine in 2.1.1

**Comment by wohali** [comment]
Hi @johs ,

https://github.com/apache/couchdb/blob/f1545b979de47e6e4484b85e6e6b40b396cfd934/share/doc/src/whatsnew/1.7.rst doesn't show that this feature was introduced in 1.7.0. 

The source shows the same thing: https://github.com/apache/couchdb/blob/f1545b979de47e6e4484b85e6e6b40b396cfd934/src/couchdb/couch_httpd_rewrite.erl#L134-L140

Is this a 1.x enhancement request?

**Comment by johs** [comment]
Hi, @wohali this was strange; @kxepal prepared with the help of @ermouth and I remember it as the big feature of 1.7.0 (as noted in the documentation). 
J

**Comment by ermouth** [comment]
@johs, I’ve asked @kxepal about the topic already. The comment was like there wasn’t enough time for it since 1.7.x were both rolled out under CVE threat circumstances.

Also as far as I can remember there were no publicly available JS rewrite implementation for 1.6, so there is no for 1.7. The version we both use was my private initiative, since it received at least cold reception over PMC.

**Comment by johs** [comment]
Thanks,
I just wrote you another mail about this

With the proxy bug in 2.1.1 we are still on your 1.6:)

johs

**Comment by kxepal** [comment]
@ermouth said it right: there wasn't enough of time to adopt that feature for 1.7 with all the rest things. Sorry, for that /:

**Comment by wohali** [comment]
Closed per user request.
