### ISSUE TITLE
Enhance replication/scheduler with new modes

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#1412]
It was clearly a win for CouchDB overall to land scheduling of replication jobs. But as always with schedulers, one size does not fit all. 

It'd be nice to be able to specify different scheduling algorithms.

One that came up recently with a client:
* Allow the scheduler to perform a series of triggered one-shot replications rather than continuous replication.
  * This could replace `{"continuous": true}` in the replication document, or could be a setting in the replication scheduler to treat continuous replications differently.
  * It could specify a frequency of replication, or
  * a delay value between replications, or
  * a "wait until a certain # of changes in the seq value to replicate" (i.e., we've fallen X behind the last checkpoint..)

One situation where this would be useful is when total # of jobs exceeds max_jobs, and max_jobs can't be raised practically speaking (CPU limitations, for instance).

I'm sure there are other replication modes that would be valuable, but I'm failing to think of them right now.

**Comment by nickva** [comment]
Fair share job scheduling https://docs.couchdb.org/en/stable/replication/replicator.html#fair-share-job-scheduling would cover the majority of the cases. One shot replications could be placed in replicator dbs with a low number of shares. Fair share configuration would indirectly configure frequency and delays between replication jobs.
