### ISSUE TITLE
 mango $regex Search with special character throw a bad request when input a string contains "+++" 

### ISSUE THREAD

**Issue by pttien** [apache/couchdb#1415]
## Steps to Reproduce (for bugs)

1.create a document content "+++" in 1 field, 
2. use mango search by regex 

![image](https://user-images.githubusercontent.com/8980287/41960814-eb7fe5b2-7a1a-11e8-9048-16b97fcc2871.png)

and see the error
![image](https://user-images.githubusercontent.com/8980287/41960955-48435608-7a1b-11e8-9349-626258db7bd6.png)

**Comment by wohali** [comment]
You've specified an invalid regex. `+` is a special character in regex syntax meaning "1 or more of the preceding token." Multiple `+` in a row is invalid without escaping the character.

Try `"$regex": "(?i)F4647868\+\+\+" and it should work fine.
