### ISSUE TITLE
when one member of a cluster is restarted, it won't rejoin to the cluster automatically

### ISSUE THREAD

**Issue by jiangpengcheng** [apache/couchdb#1421]
just as the title said, this can be annoy as we have to rejoin the node to cluster by manual

## Expected Behavior
when restart a node, it should rejoin the cluster automatically

## Current Behavior
it's expected to rejoin the old cluster without any extra operations

## Possible Solution
~I have no idea here~

## Steps to Reproduce (for bugs)
1. I'm using CouchDB for this project [OpenWhisk](https://github.com/apache/incubator-openwhisk), to deploy a CouchDB cluster:
```shell
git clone https://github.com/apache/incubator-openwhisk
cd incubator-openwhisk/ansible
# edit the inventory file ansible/environments/distributed/hosts, add 3 nodes under the [db] section
ansible-playbook -i environments/distributed/hosts couchdb.yml
```
2. restart the 3rd node or any other node else
3. call the `_membership` API againt node1/node2, it will show result like below:
```
{"all_nodes":["couchdb@x.x.x.x","couchdb@y.y.y.y"],"cluster_nodes":["couchdb@x.x.x.x","couchdb@y.y.y.y","couchdb@z.z.z.z"]}
```

and the node3 will return:

```
{"all_nodes":["couchdb@z.z.z.z"],"cluster_nodes":["couchdb@x.x.x.x","couchdb@y.y.y.y","couchdb@z.z.z.z"]}
```

So the node3 left the cluster, and doesn't go back

## Your Environment
the version of CouchDB is 2.1
it's running in docker, and its image is `apache/couchdb:2.1`: https://hub.docker.com/_/couchdb/

**Comment by style95** [comment]
@jiangpengcheng Did you configure the cookie for the cluster?

**Comment by wohali** [comment]
This sounds like a problem with the OpenWhisk ansible playbook - you'll need to talk to them, sorry.

I guarantee you people are deploying CouchDB clusters with the Docker image and not having this problem.

**Comment by jiangpengcheng** [comment]
## Steps to Reproduce (for bugs)
1. ~I'm using CouchDB for this project [OpenWhisk](https://github.com/apache/incubator-openwhisk), to deploy a CouchDB cluster~ Now I use docker only, create couchdb containers on 3 nodes:

    ```shell
    # node1
    docker run -d --name couchdb -e COUCHDB_USER=couch_user -e COUCHDB_PASSWORD=couch_password -e NODENAME=192.168.253.137 -p 5984:5984 -p 4369:4369 -p 9100:9100 apache/couchdb:2.1

    # node2
    docker run -d --name couchdb -e COUCHDB_USER=couch_user -e COUCHDB_PASSWORD=couch_password -e NODENAME=192.168.253.138 -p 5984:5984 -p 4369:4369 -p 9100:9100 apache/couchdb:2.1

    # node3
    docker run -d --name couchdb -e COUCHDB_USER=couch_user -e COUCHDB_PASSWORD=couch_password -e NODENAME=192.168.253.139 -p 5984:5984 -p 4369:4369 -p 9100:9100 apache/couchdb:2.1
    ```

2. setup the cluster

    I follow this [guide](http://docs.couchdb.org/en/2.1.1/cluster/setup.html#the-cluster-setup-api), and use node1 as the “setup coordination node”

    Below command returned an error, so I skipped this command:
    ```shell
    curl -X POST -H "Content-Type: application/json" http://couch_user:couch_password@127.0.0.1:5984/_cluster_setup -d '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "couch_user", "password":"couch_password", "node_count":"3"}'
    {"error":"bad_request","reason":"Cluster is already enabled"}
    ```

    ```shell
    # add node2 to cluster
    curl -X POST -H "Content-Type: application/json" http://couch_user:couch_password@127.0.0.1:5984/_cluster_setup -d '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "couch_user", "password":"couch_password", "port": 5984, "node_count": "3", "remote_node": "192.168.253.138", "remote_current_user": "couch_user", "remote_current_password": "couch_password" }'
    {"ok":true}

    curl -X POST -H "Content-Type: application/json" http://couch_user:couch_password@127.0.0.1:5984/_cluster_setup -d '{"action": "add_node", "host":"192.168.253.138", "port": "5984", "username": "couch_user", "password":"couch_password"}'
    {"ok":true}

    # add node3 to cluster
    curl -X POST -H "Content-Type: application/json" 
    http://couch_user:couch_password@127.0.0.1:5984/_cluster_setup -d '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "couch_user", "password":"couch_password", "port": 5984, "node_count": "3", "remote_node": "192.168.253.139", "remote_current_user": "couch_user", "remote_current_password": "couch_password" }'
    {"ok":true}

    curl -X POST -H "Content-Type: application/json" 
    http://couch_user:couch_password@127.0.0.1:5984/_cluster_setup -d '{"action": "add_node", "host":"192.168.253.139", "port": "5984", "username": "couch_user", "password":"couch_password"}'
    {"ok":true}

    # finish cluster
    curl -X POST -H "Content-Type: application/json" http://couch_user:couch_password@127.0.0.1:5984/_cluster_setup -d '{"action": "finish_cluster"}'
    {"ok":true}
    ```

    the cluster was formed correctly:
    ```shell
    curl -X GET http://couch_user:couch_password@127.0.0.1:5984/_membership
    {"all_nodes":["couchdb@192.168.253.137","couchdb@192.168.253.138","couchdb@192.168.253.139"],"cluster_nodes":["couchdb@192.168.253.137","couchdb@192.168.253.138","couchdb@192.168.253.139"]}
    ```

3. restart the 3rd node

4. call the `_membership` API againt node1/node2, the result was:
    ```
    {"all_nodes":["couchdb@192.168.253.137","couchdb@192.168.253.138"],"cluster_nodes":["couchdb@192.168.253.137","couchdb@192.168.253.138","couchdb@192.168.253.139"]}
    ```
    and the node3 returned:
    ```
    {"all_nodes":["couchdb@192.168.253.139"],"cluster_nodes":["couchdb@192.168.253.137","couchdb@192.168.253.138","couchdb@192.168.253.139"]}
    ```
    we can see that the node3 has left the cluster


## Context

A strange thing is that when I restarted the node1, it can rejoin the cluster, seems there is something special in the “setup coordination node”.

So I cleaned the env, recreated 3 couchdb containers and use node2 as the “setup coordination node” this time, and find out that the node2 can rejoin the cluster automatically while node1 and node3 can not, this is confusing


@wohali Could you please check this when you have some time? Many thanks

**Comment by wohali** [comment]
How are you restarting the container?

If you are not externalising the `etc/local.d` and `data/` directories, as explained in the Docker README, the node will lose its configuration.

Please share the contents of your *.ini files on all 3 nodes.

**Comment by jiangpengcheng** [comment]
I use command `docker restart couchdb`

I didn't mount any configuration files to containers, so the `default.ini` and `local.ini` are identical in all three nodes, below are contentns of `local.d/local.ini`:

```shell
#node1
[chttpd]
bind_address = any
[httpd]
bind_address = any
[admins]
couch_user = -pbkdf2-aa811c26cee3d5b8392e2c022b8a3f23b5558e6a,c2ee49b331678afc5489e68227c83ce5,10
[couchdb]
uuid = 54fcccdf6afdfd1ca16fc6992f72085a

#node2
[chttpd]
bind_address = any
[httpd]
bind_address = any
[admins]
couch_user = -pbkdf2-e835df2896881bcdac7961176e8f9e8eb0072df1,9fe22744e324c2337f4552eae646411a,10
[couchdb]
uuid = ba8ae822d83b5747749327c7c0658cba

#node3
[chttpd]
bind_address = any
[httpd]
bind_address = any
[admins]
couch_user = -pbkdf2-85e99acc676e998f801922cadfe0b46f703e8b9e,f28bbc54fab83e0d921a24cf63e5653d,10
[couchdb]
uuid = 67d9b8603d12b487f6ff600842a7c4a0
```

the only difference is the `couch_user` option

**Comment by jiangpengcheng** [comment]
Now I get it, need configure this https://github.com/apache/couchdb/blob/master/rel/overlay/etc/vm.args#L34

**Comment by jiangpengcheng** [comment]
should we add this option(https://github.com/apache/couchdb/blob/master/rel/overlay/etc/vm.args#L34) to the docker image? or make it configurable via env?

**Comment by wohali** [comment]
Glad your problem is solved!

FYI, you can already persist this setting with CouchDB - you need to mount the `etc/vm.args` file via a `-v` flag to `docker run`.

We're not going to support any more runtime options other than the basics via the init script / by env, the proper way to configure the CouchDB docker image is via external files you mount in. You want to persist these, anyway.

If you have any other ideas for the Docker image, use the tracker at https://github.com/apache/couchdb-docker/issues instead. Thanks!
