### ISSUE TITLE
Access to CouchDB view return timeout

### ISSUE THREAD

**Issue by jliu1970** [apache/couchdb#1429]
In a smart database, with a dozen documents. Try to access the documents through a view, but got timeout.
## Expected Behavior

view shall work consistently.

## Current Behavior

Got following log:

[notice] 2018-07-10T01:20:03.528895Z nonode@nohost <0.16472.0> b79e4ff8d5 10.6.164.106:5984 10.44.0.90 undefined GET /_session 200 ok 0
[notice] 2018-07-10T01:20:03.570971Z nonode@nohost <0.16472.0> 8bfba30bc1 10.6.164.106:5984 10.44.0.90 undefined GET /radio-db/_all_docs?startkey=%22_design%2F%22&endkey=%22_design0%22&include_docs=true&limit=501 200 ok 4
[info] 2018-07-10T01:20:03.598983Z nonode@nohost <0.2352.1> -------- Starting index update for db: shards/a0000000-bfffffff/radio-db.1531157665 idx: _design/RadioDbWrapper
[info] 2018-07-10T01:20:03.599258Z nonode@nohost <0.2350.1> -------- Starting index update for db: shards/20000000-3fffffff/radio-db.1531157665 idx: _design/RadioDbWrapper
[error] 2018-07-10T01:20:08.604416Z nonode@nohost <0.12434.1> -------- CRASH REPORT Process  (<0.12434.1>) with 1 neighbors exited with reason: bad return value {os_process_error,"OS process timed out."} at gen_server:init_it/6(line:334) <= proc_lib:init_p_do_apply/3(line:237); initial_call: {couch_os_process,init,['Argument__1']}, ancestors: [<0.12433.1>], messages: [], links: [<0.12433.1>], dictionary: [], trap_exit: false, status: running, heap_size: 987, stack_size: 27, reductions: 264
[error] 2018-07-10T01:20:08.604566Z nonode@nohost <0.12436.1> -------- CRASH REPORT Process  (<0.12436.1>) with 1 neighbors exited with reason: bad return value {os_process_error,"OS process timed out."} at gen_server:init_it/6(line:334) <= proc_lib:init_p_do_apply/3(line:237); initial_call: {couch_os_process,init,['Argument__1']}, ancestors: [<0.12435.1>], messages: [], links: [<0.12435.1>], dictionary: [], trap_exit: false, status: running, heap_size: 987, stack_size: 27, reductions: 264
[info] 2018-07-10T01:20:08.604618Z nonode@nohost <0.206.0> -------- couch_proc_manager <0.12433.1> died {bad_return_value,{os_process_error,"OS process timed out."}}
[info] 2018-07-10T01:20:08.604709Z nonode@nohost <0.206.0> -------- couch_proc_manager <0.12435.1> died {bad_return_value,{os_process_error,"OS process timed out."}}
sh: echo: I/O error
sh: echo: I/O error
[error] 2018-07-10T01:20:50.146640Z nonode@nohost <0.7797.1> 0d8f3d5d7a rexi_server: from: nonode@nohost(<0.7760.1>) mfa: fabric_rpc:map_view/5 exit:timeout [{rexi,init_stream,1,[{file,"src/rexi.erl"},{line,256}]},{rexi,stream2,3,[{file,"src/rexi.erl"},{line,204}]},{fabric_rpc,view_cb,2,[{file,"src/fabric_rpc.erl"},{line,308}]},{couch_mrview,finish_fold,2,[{file,"src/couch_mrview.erl"},{line,642}]},{couch_mrview,query_view,5,[{file,"src/couch_mrview.erl"},{line,263}]},{rexi_server,init_p,3,[{file,"src/rexi_server.erl"},{line,139}]}]
[error] 2018-07-10T01:20:50.150847Z nonode@nohost <0.7800.1> 0d8f3d5d7a rexi_server: from: nonode@nohost(<0.7760.1>) mfa: fabric_rpc:map_view/5 exit:timeout [{rexi,init_stream,1,[{file,"src/rexi.erl"},{line,256}]},{rexi,stream2,3,[{file,"src/rexi.erl"},{line,204}]},{fabric_rpc,view_cb,2,[{file,"src/fabric_rpc.erl"},{line,308}]},{couch_mrview,map_fold,3,[{file,"src/couch_mrview.erl"},{line,511}]},{couch_mrview_util,fold_fun,4,[{file,"src/couch_mrview_util.erl"},{line,398}]},{couch_btree,stream_kv_node2,8,[{file,"src/couch_btree.erl"},{line,848}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_mrview_util,fold,4,[{file,"src/couch_mrview_util.erl"},{line,393}]}]
[error] 2018-07-10T01:20:50.150901Z nonode@nohost <0.7804.1> 0d8f3d5d7a rexi_server: from: nonode@nohost(<0.7760.1>) mfa: fabric_rpc:map_view/5 exit:timeout [{rexi,init_stream,1,[{file,"src/rexi.erl"},{line,256}]},{rexi,stream2,3,[{file,"src/rexi.erl"},{line,204}]},{fabric_rpc,view_cb,2,[{file,"src/fabric_rpc.erl"},{line,308}]},{couch_mrview,map_fold,3,[{file,"src/couch_mrview.erl"},{line,511}]},{couch_mrview_util,fold_fun,4,[{file,"src/couch_mrview_util.erl"},{line,398}]},{couch_btree,stream_kv_node2,8,[{file,"src/couch_btree.erl"},{line,848}]},{couch_btree,fold,4,[{file,"src/couch_btree.erl"},{line,222}]},{couch_mrview_util,fold,4,[{file,"src/couch_mrview_util.erl"},{line,393}]}]
[error] 2018-07-10T01:20:50.151555Z nonode@nohost <0.7801.1> 0d8f3d5d7a rexi_server: from: nonode@nohost(<0.7760.1>) mfa: fabric_rpc:map_view/5 exit:timeout [{rexi,init_stream,1,[{file,"src/rexi.erl"},{line,256}]},{rexi,stream2,3,[{file,"src/rexi.erl"},{line,204}]},{fabric_rpc,view_cb,2,[{file,"src/fabric_rpc.erl"},{line,308}]},{couch_mrview,finish_fold,2,[{file,"src/couch_mrview.erl"},{line,642}]},{couch_mrview,query_view,5,[{file,"src/couch_mrview.erl"},{line,263}]},{rexi_server,init_p,3,[{file,"src/rexi_server.erl"},{line,139}]}]
[error] 2018-07-10T01:20:50.151909Z nonode@nohost <0.7802.1> 0d8f3d5d7a rexi_server: from: nonode@nohost(<0.7760.1>) mfa: fabric_rpc:map_view/5 exit:timeout [{rexi,init_stream,1,[{file,"src/rexi.erl"},{line,256}]},{rexi,stream2,3,[{file,"src/rexi.erl"},{line,204}]},{fabric_rpc,view_cb,2,[{file,"src/fabric_rpc.erl"},{line,308}]},{couch_mrview,finish_fold,2,[{file,"src/couch_mrview.erl"},{line,642}]},{couch_mrview,query_view,5,[{file,"src/couch_mrview.erl"},{line,263}]},{rexi_server,init_p,3,[{file,"src/rexi_server.erl"},{line,139}]}]
[error] 2018-07-10T01:20:50.152250Z nonode@nohost <0.7805.1> 0d8f3d5d7a rexi_server: from: nonode@nohost(<0.7760.1>) mfa: fabric_rpc:map_view/5 exit:timeout [{rexi,init_stream,1,[{file,"src/rexi.erl"},{line,256}]},{rexi,stream2,3,[{file,"src/rexi.erl"},{line,204}]},{fabric_rpc,view_cb,2,[{file,"src/fabric_rpc.erl"},{line,308}]},{couch_mrview,finish_fold,2,[{file,"src/couch_mrview.erl"},{line,642}]},{couch_mrview,query_view,5,[{file,"src/couch_mrview.erl"},{line,263}]},{rexi_server,init_p,3,[{file,"src/rexi_server.erl"},{line,139}]}]
[notice] 2018-07-10T01:21:00.321772Z nonode@nohost <0.13321.1> 8acd9d2c09 couchdb:5984 172.19.2.3 undefined GET /radio-db/1-1-100 304 ok 5
[notice] 2018-07-10T01:21:00.338758Z nonode@nohost <0.13321.1> 444a6a9324 couchdb:5984 172.19.2.3 undefined GET /radio-db/1-1-105 304 ok 4
[notice] 2018-07-10T01:21:00.350756Z nonode@nohost <0.13321.1> 85091a0619 couchdb:5984 172.19.2.3 undefined GET /radio-db/1-1-104 304 ok 5
[notice] 2018-07-10T01:21:00.356521Z nonode@nohost <0.13321.1> e24faeb037 couchdb:5984 172.19.2.3 undefined GET /radio-db/1-1-101 304 ok 1
[notice] 2018-07-10T01:21:00.375041Z nonode@nohost <0.13321.1> ba8f67a335 couchdb:5984 172.19.2.3 undefined GET /radio-db/1-1-106 304 ok 13
[notice] 2018-07-10T01:21:00.383460Z nonode@nohost <0.13321.1> 08c17847b6 couchdb:5984 172.19.2.3 undefined GET /radio-db/1-1-107 304 ok 4
[notice] 2018-07-10T01:21:00.393758Z nonode@nohost <0.13321.1> 53cf48a0c2 couchdb:5984 172.19.2.3 undefined GET /radio-db/1-1-15 304 ok 1
[notice] 2018-07-10T01:21:00.400013Z nonode@nohost <0.13321.1> 6f8e7780fd couchdb:5984 172.19.2.3 undefined GET /radio-db/1-1-16 304 ok 1
[error] 2018-07-10T01:21:03.599101Z nonode@nohost <0.12364.1> 00f6e1794f fabric_worker_timeout map_view,nonode@nohost,<<"shards/20000000-3fffffff/radio-db.1531157665">>
[error] 2018-07-10T01:21:03.599158Z nonode@nohost <0.12364.1> 00f6e1794f fabric_worker_timeout map_view,nonode@nohost,<<"shards/a0000000-bfffffff/radio-db.1531157665">>
[notice] 2018-07-10T01:21:03.599582Z nonode@nohost <0.12364.1> 00f6e1794f 10.6.164.106:5984 10.44.0.90 undefined GET /radio-db/_design/RadioDbWrapper/_view/t_radioaliases_by_agency?include_docs=true&limit=21&reduce=false&skip=0 500 ok 60002

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

retrieve record through view

## Your Environment

* Version used: V2.1.1
* Browser Name and version:
* Operating System and version (desktop or mobile): Docker
* Link to your project:

**Comment by wohali** [comment]
Can you try adding more CPUs to your Docker instance? Views are run in a separate process, so you need more than 1 CPU core.

**Comment by jliu1970** [comment]
Thanks a lot for the quick response, Wohali. Could you help to provide information on how do I determine the number of CPU cores used by the database? Our couchdb runs on its own docker container, shared with a few other containers on a server with 8 cores. We will try to tune the resource allocation to ensure sufficient resource is allocated to the database. Thanks again for the quick response.

**Comment by jliu1970** [comment]
Sorry, can you advise on how many CPUs should be allocated to the couchdb? In our case, the database is fairly small with a capacity of around 200k simple documents (each document is probably around 1k in size). Thanks, Jimmy

**Comment by jliu1970** [comment]
Thanks a lot for the update, Joan. Can you also recommend how many CPUs
should we allocate to the CouchDB container in our case? We maintain a
fairly small database, with a couple of document types, and a maximum of
200 k of documents. Each document is less than 1 k in size.

Thanks
Jimmy

**Comment by wohali** [comment]
Can you confirm that adding a CPU core fixed your problem?

Erlang itself will run fine on 1 CPU. It comes down to your number of simultaneously building JavaScript views. Each building view will use a separate `couchjs` process. If you build them sequentially in your client app, you can get away with 2 cores. If you expect to build _e.g._ 5 at once then you need 1+5 = 6 cores. The number of documents & size doesn't enter into it, except that it affects how long it takes to build each view.

**Comment by jliu1970** [comment]
Thanks again for the quick response, Joan.

We have a couple of Docker containers running on one 4 core machine.
CouchDb has its own container. We try to raise the cpu-share of the CouchDB
to a much higher number than the rest of the containers. Can you advise on
what I should monitor in the couchDB log to verify that it is allocated to
more than one 1 CPU?

Thanks again,
Jimmy

**Comment by wohali** [comment]
There's nothing in the logs to indicate how many CPUs couch is using.

You can monitor `GET /_active_tasks` with a metrics tool to see how many views are building at once - any JavaScript view that is building will be a separate process.

The core of CouchDB (in Erlang) will always allocate itself across all cores provided.

**Comment by jliu1970** [comment]
Thanks for the update, Joan. I will monitor the cpu usage as you suggested
and let you know.

Jimmy
