### ISSUE TITLE
Fix the Windows build

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#1449]
#1346 broke the build for Windows.

* `rebar.config` for hyper needs updating
* there are C99-isms in `hyper_carray.c` that fail as well as attempts at pointer arithmetic on a `void *`

**Comment by janl** [comment]
what needs doing here? cc @davisp @kocolosk

**Comment by wohali** [comment]
Partially addressed by https://github.com/apache/couchdb-hyper/pull/4

Turns out `bcrypt` won't compile now, that's the next step.

**Comment by wohali** [comment]
https://github.com/apache/couchdb/pull/1456 will fix the hyper issue.

Backing `bcrypt` out of master with +1s from  @rnewson and @janl, see https://github.com/apache/couchdb/pull/1160#issuecomment-405986847

**Comment by wohali** [comment]
bcrypt has been removed, now this is holding things up:

https://github.com/apache/couchdb-fauxton/issues/1105

/cc @popojargo @Antonio-Maranhao

**Comment by wohali** [comment]
Building without Fauxton, all CouchDB tests now pass. \o/
