### ISSUE TITLE
Cut 2.2.0 release

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#1453]
To complete the 2.2.0 release, the following tasks must be completed:

~~#1449~~
~~#1462~~
~~#1464~~
~~apache/couchdb-fauxton#1104~~
~~apache/couchdb-fauxton#1105~~
~~apache/couchdb-fauxton#1106~~
~~apache/couchdb-fauxton#1108~~
~~apache/couchdb-documentation#292~~
~~apache/couchdb-documentation#268~~

and unfortunately not these: :
~~#1407~~ #wontfix 
~~apache/couchdb-documentation#275~~ needs too much work

This ticket serves to track the completion of these across multiple repos, then to track the RC process, for those who are not subscribed to the dev@couchdb.apache.org mailing list.

**Comment by wohali** [comment]
We're down to a Fauxton tagged release and the release notes. Woo hoo!

Don't forget to check all the versions in master's `rebar.config.script`, @wohali.

**Comment by wohali** [comment]
We have a tagged Fauxton release, so #1464 has been added to the milestone. Once the release notes and #1462 are resolved one way or the other, I can tag `couchdb-documentation` as 2.2.0, bump `rebar.config.script` and cut our first 2.2.0 release candidate! :D

**Comment by wohali** [comment]
@janl you asked about my process for creating release notes - I wrote it up - maybe this will help you:

-----------

Get a list of things to care about:
`git show-branch --sha1-name master X.X.X|more`
* use this to find common ancestor (very last thing in the output)
* use this to make sure everything on X.X.X has been pulled fwd to master
* use this to eliminate anything that "looks the same" on X.X.X branch and master
    * cannot use sha-1s because they will be different on each branch
    * research if there is a way to auto-validate cherry picked stuff?

For each remaining commit on master:
1. use GH web UI to find the commit's related PRs or issues and write up
   something nice
1. sort by GH issue/PR number
1. any issues that merge without a useful GH/PR number should go either at the
   very top or bottom of the list, depending on importance of issue
1. do not explicitly list out things like Jenkins/Travis/rebar.config changes
   unless they are significant in some fashion

Now do the same thing as above, but for documentation and fauxton. Pull out only
the big-ticket items.

**Comment by wohali** [comment]
Ready to go - just bumping the docs dependency now, then I'll make the 2.2.x branch.

**Comment by wohali** [comment]
done

> Dear community,
> 
> I would like to release Apache CouchDB 2.2.0-RC1.
> 
> Changes since last round:
> 
>  * https://github.com/apache/couchdb/compare/2.1.2...2.2.0-RC1
> 
> Release notes:
> 
>  * http://docs.couchdb.org/en/latest/whatsnew/2.2.html
> 
> This is a big release, so your attention to detail is very much appreciated.
> 
> We encourage the whole community to download and test these release artefacts so that any critical issues can be resolved before the release is made. Everyone is free to vote on this release, so dig right in!
> 
> The release artefacts we are voting on are available here:
> 
>     https://dist.apache.org/repos/dist/dev/couchdb/source/2.2.0/rc.1/
> 
> There, you will find a tarball, a GPG signature, and SHA256/SHA512 checksums.
> 
> Please follow the test procedure here:
> 
>     https://cwiki.apache.org/confluence/display/COUCHDB/Testing+a+Source+Release
> 
> Please remember that "RC1" is an annotation. If the vote passes, these artefacts will be released as Apache CouchDB 2.2.0.
> Please cast your votes now.
> 
> Thanks,
> Joan "release all the things!" Touzet
> Apache CouchDB PMC

**Comment by wohali** [comment]
binaries are up for windows rc1

https://dist.apache.org/repos/dist/dev/couchdb/binary/win/2.2.0/rc.1/

**Comment by janl** [comment]
and mac: https://dist.apache.org/repos/dist/dev/couchdb/binary/mac/2.2.0/rc.1/
