### ISSUE TITLE
Replaced broken node uses more data storage than expected

### ISSUE THREAD

**Issue by jvegaseg** [apache/couchdb#1460]
We have a 6-node cluster configured with q=16.
We are using version 2.1.1

We lost one of the nodes and we replace it with a new one.
Before being replaced, the directory /opt/couchd/data had a disk space size of 3,3Tb.

After the replacement, same directory has a disk space  size of 5,6 Tb.

Why this extra disk space?

## Expected Behavior
Node replaced should have similar data space than previous one.

## Current Behavior
There are more disk space for data than expected.

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)
Replacing a broken node.

## Your Environment
Software is running on virtualized Centos 7 using OpenVZ 7.
Each node has same configuration.
Each node has 16 cores and  10 Tb of disk space.

**Comment by janl** [comment]
how do things look when you compact all shards and view indexes and cleanup all old view indexes on that node?

**Comment by jvegaseg** [comment]
I mean that space used in data directory was almost twice times greater than previous node.
It is a new replaced node, so it should not need any cleanup (I suppose). I am not using indexes (we only store mail attachments and always are retrieved by key).

As an example, the same shard has a very different size in two different nodes for same database:

Node1: 396 Gb
Node2: 511 Gb

Regards,

**Comment by jvegaseg** [comment]
And in the third node is has 301 Gb

**Comment by janl** [comment]
@jvegaseg we can't help if you don't answer our questions :)

**Comment by jvegaseg** [comment]
Sorry @janl but I have no answer for your question because I am compacting nothing. I would expect from couchdb "be relaxed" and not having to do maintenance tasks.

It has no sense a new replication having more data than needed, it is a waste of resources, performance and time to complete.

**Comment by janl** [comment]
If you want us to help find out what the issue is, we need more information. I’m closing this issue until we have that info.

**Comment by jvegaseg** [comment]
After compacting, space was reduced more than 50%.
Is there a way to run only one active compacting task on each node (or running compacting sequentially for each shard)? 
Running several in parallel need too much space for compacting.

**Comment by wohali** [comment]
If you leave it up to the compaction daemon, it won't run more than one at a time. If you do it manually, it's up to you to ensure that only one is running at once, by looking at the output of `GET /_active_tasks` or similar.

**Comment by jvegaseg** [comment]
@wohali, I am referring to compact only one shard at same time on same database. When you compact a database with 16 shards, it starts compacting several shards at a same time in each node. That way of doing it requires too much disk space.
For example, if each shard has a size of 500G and it starts compacting 3 shards at same time on same node, it needs 1,5 Tb for compacting.
If it would compact only one shard at same time, it would only need 500Gb of disk space. It saves 66% of needed space.

**Comment by wohali** [comment]
@jvegaseg Sorry, my misunderstanding.

Unfortunately db file has a unique value that specifies when the database was initialized. This value (effectively a coordinated datetime stamp, you can see it in the filename of the shard) is consistent across all shards on either side of the compaction process, meaning it is changed post compaction. The value is only specified once in the `_dbs` system database, which is aggressively forced to be consistent across all nodes. There's no way to say that, for node X, for shard 00-1f, use the updated shard, but for nodes Y and Z (in a standard `n=3` database) keep using the original shard since they are not yet done compacting. Things would get messy quickly.

I can see the value in what you're proposing, but in a cluster I don't see how what you suggest can be made to work without significant difficulty.

**Comment by wohali** [comment]
@jvegaseg I do not know if this is possible. I will ask someone else to comment.

**Comment by wohali** [comment]
Seems I am wrong about the filename changing, so the contents of the `_dbs` database don't need special handling.

We're looking into the compaction process now to see what's up with multiple shards compacting at once. We'll get back to you soon.

**Comment by janl** [comment]
@jvegaseg: yes, you can compact shards one by one.

**Comment by wohali** [comment]
@jvegaseg also a reminder that the compaction daemon will always compact one shard at a time. It will not compact all at once like your compaction on port 5984 does.

**Comment by jvegaseg** [comment]
Ok thanks a lot
