### ISSUE TITLE
setting a different direction indexes is impossible

### ISSUE THREAD

**Issue by jooskim1** [apache/couchdb#1461]
CouchDB with Hyperledger fabric seems not support setting a index with multiple fields with different directions. 
## Expected Behavior

I think CouchDB supports multiple directions find and indexing

## Current Behavior

I cannot make complex index with two fields, one direction is asc and another is desc.
[This is my stackoverflow question](https://stackoverflow.com/questions/51478771/can-i-use-hyperledger-couchdb-mixed-ordering/51479963#51479963)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I need to complex sorting logic to my hyperledger application to implements different direction sorting supported by other NoSQL like Mongodb.
## Your Environment

* Version used: 2.1.1
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Hyperledger fabric(1.2) couchDB
* Link to your project: n/a

**Comment by rnewson** [comment]
Hi, That's correct, CouchDB indexes only support a single sort order, hence the accurate error message you received.
