### ISSUE TITLE
CouchDb Clustering : Impossible to set it up

### ISSUE THREAD

**Issue by nicolas15000** [apache/couchdb#1471]
I'm following this documentation :

http://docs.couchdb.org/en/latest/cluster/setup.html#the-cluster-setup-api

The 11.1 part : The Cluster Setup API

I have 3 ubuntu machines with couchdb and Curl installed, with the following ips :

192.168.219.138, 192.168.219.139 ,192.168.219.140

First step, as the doc says, i'm entering the following commands on each of the 3 machines (admin password have been set.) :
```

> curl -X POST -H "Content-Type: application/json"
> http://admin:password@127.0.0.1:5984/_cluster_setup -d '{"action":
> "enable_cluster", "bind_address":"0.0.0.0", "username": "admin",
> "password":"password", "node_count":"3"}'
```

it says this on each machines :

`{"ok":true}`

Second step, i go on the 192.168.219.139 (setup coordination node) and try adding the nodes, so I'm entering theses commands, just like the doc is mentionning :

```
`curl -X POST -H "Content-Type: application/json" http://admin:password@127.0.0.1:5984/_cluster_setup -d '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "admin", "password":"password", "port": 15984, "node_count": "3", "remote_node": "192.168.219.138", "remote_current_user": "admin", "remote_current_password": "password" }'`
curl -X POST -H "Content-Type: application/json" http://admin:password@127.0.0.1:5984/_cluster_setup -d '{"action": "add_node", "host":"192.168.219.138", "port": 5684, "username": "admin", "password":"password"}'
curl -X POST -H "Content-Type: application/json" http://admin:password@127.0.0.1:5984/_cluster_setup -d '{"action": "enable_cluster", "bind_address":"0.0.0.0", "username": "admin", "password":"password", "port": 15984, "node_count": "3", "remote_node": "192.168.219.140", "remote_current_user": "admin", "remote_current_password": "password" }'
curl -X POST -H "Content-Type: application/json" http://admin:password@127.0.0.1:5984/_cluster_setup -d '{"action": "add_node", "host":"192.168.219.140", "port": 5684, "username": "admin", "password":"password"}'
```

Then, i do this command to check if my cluster is ok :

`curl http://admin:password@127.0.0.1:5984/_membership`

And this is the answer, all the nodes are missing, i only see localhost under "all_nodes" :

```
    {
    "all_nodes": [
        "couchdb@localhost"
    ],
    "cluster_nodes": [
        "couchdb@192.168.219.138",
        "couchdb@192.168.219.140",
        "couchdb@locahost"
    ]
}
```

Please notice, the doc says i'me supposed to get this :

```
{
    "all_nodes": [
        "couchdb@couch1",
        "couchdb@couch2",
         "couchdb@couch3"
    ],
    "cluster_nodes": [
        "couchdb@couch1",
        "couchdb@couch2",
         "couchdb@couch3"
    ]
}

```
I guess my cluster is not functionnal, could you please tell me what am i doing wrong ?

For example, then i go to the 192.168.219.139, add a new database called 'establishments' and nothing happens on both 2 others nodes,  i guess it is not working !!

I can't access any of the 4 vm.args files, even with root rights, i cant edit them !

Thank you .

**Comment by wohali** [comment]
@nicolas15000 you can't combine using short-name syntax and long-name syntax. You also can't use "localhost" because the other nodes can't reach the current node by that name.

I don't know why you can't edit the `vm.args` files, but you need access to those to be able to set the correct node names on the `-name` line first. Without this step you will be unsuccessful.

If you are installing via debian/ubuntu/redhat package, you should be able to edit that file as root or the couchdb user. Once edited, restart the process.

**Comment by nicolas15000** [comment]
Hello and thank you, I've done sudo root, then i still can't access vm.args, i have to abandon, there is no structured explanation on how to simply do a cluster with couchdb

**Comment by wohali** [comment]
There are literally tens of thousands of CouchDB clusters out there. Editing vm.args usually works fine. I'm sorry that we can't help you - you might want to try stopping by the IRC or Slack channels for more immediate support.
