### ISSUE TITLE
Support "revs" for views/_all_docs (partial/custom replication speed-up)

### ISSUE THREAD

**Issue by ondra-novak** [apache/couchdb#1481]
Enhancement

Making custom replication of the set of the documents specified by their IDs. Replication needs to have the structure `"_revisions":{"ids":[],"start":#}` presented in the document. 

Unfortunately, i can retrieve this field only when requesting single document at once through the `GET /db/doc` request. This flag is not supported on queries while `include_docs=true` is active

Supporting `revs` can improve speed of custom replication, because documents are read as the batch.

## Context
Custom replication can be provided through the `filter`. However the filter is stateless, so there are many tasks, where the filtered replication is not possible. For example if one needs to replicate only documents that are in relation with other documents (referenced documents, transitive). 

So custom replication generates sets of the document's IDs and then it asks one by one to retrieve the content of the documents including their "_revisions". This is very slow and only way to speed this up is using multiple threads. To retrieve documents through the 

`_all_docs?keys=[...]&include_docs=true&revs=true`

would help to improve performance, but this is currently not supported.

### The best resolution

Support all revision related flags on views while include_docs=true is active
`open_revs`,`rev`,`revs`,`revs_info`

Thank you

**Comment by wohali** [comment]
@ondra-novak have you checked the new `POST /{db}/_all_docs/queries` endpoint to see if it helps?

**Comment by ondra-novak** [comment]
No, but i have found another endpoint `_bulk_get`. It is still not the what I need exactly, but it is much better than requesting documents one by one.

Apparently this endpoint is new in 2.x , i cannot find it on my old installation with 1.7.x

TY!
