### ISSUE TITLE
DELETE database with invalid name returns 404 NOT FOUND instead of 400 BAD REQUEST

### ISSUE THREAD

**Issue by hytano** [apache/couchdb#1485]
DELETE http://127.0.0.1/_db 

## Expected Behavior

Respons Status Code  400 BAD REQUEST 

## Current Behavior

Respons Status Code 404 NOT FOUND

`{
"error": "not_found",
"reason": "Database does not exist."
}`

## Possible solution
Return 400 BAD REQUEST or "adjust" documentation ;-) [http://docs.couchdb.org/en/2.1.2/api/database/common.html#delete--db](url)

## Setup

CouchDB 2.1.2
Windows 7

**Comment by wohali** [comment]
There are a number of these minor inconsistencies in the documentation. Pull requests welcome.
