### ISSUE TITLE
DB becomes public if member.* is empty

### ISSUE THREAD

**Issue by ceremcem** [apache/couchdb#1490]
Unless something is declared in `member.names` or `member.roles` db becomes PUBLIC.

### Expected Behaviour

Following `_security` document should suffice: 

```json 
{
  "_id": "_security",
  "couchdb_auth_only": true,
  "admins": {
    "names": [
      "foo"
    ],
    "roles": []
  },
  "members": {
    "names": [],
    "roles": []
  }
}
```

## Version 

Including 2.2.0-RC2

**Comment by wohali** [comment]
This is "normal" per the CouchDB 1.x-2.x security model.

We will be changing how security works in the 3.x release.

**Comment by ceremcem** [comment]
Is there any reference/*warning* to this *normal* behaviour in the documentation?

**Comment by wohali** [comment]
Yes:

http://docs.couchdb.org/en/2.1.2/api/database/security.html

If both the names and roles fields of either the admins or members properties are empty arrays, or are not existent, it means the database has no admins or members.

Having no admins, only server admins (with the reserved _admin role) are able to update design document and make other admin level changes.

Having no members, any user can write regular documents (any non-design document) and read documents from the database.

**Comment by ceremcem** [comment]
Apparently it was written. It's just unobtrusive IMHO and still seems like a wrong design decision, thus a bug by design. 

If something is only reachable by explicitly specified members, if a db is unreachable for a member that I just removed, this means if I remove all members, then db becomes unreachable to any user, can't be magically public.

Where is the 3.x security design discussion taking place?

**Comment by wohali** [comment]
@ceremcem you can adopt the 3.0 default now:

https://github.com/apache/couchdb/blob/master/rel/overlay/etc/default.ini#L26-L31

set this to `admin_only`.

**Comment by ceremcem** [comment]
That's very handy for preventing db to become public by a typo. Thank you.
