### ISSUE TITLE
Fauxton decides replication db address wrongly if server under subfolder

### ISSUE THREAD

**Issue by ceremcem** [apache/couchdb#1491]
When creating a replication, following scenario ends up broken if CouchDB is served under a folder, like http//example.com/db: 

1. Select "Remote database" as source
2. Write the address 
3. Select "Local database" as target 
4. Select the existing database `foo1` (or create a new one)
5. Create the replication document 
6. See the replication document is created with the url: `http//example.com/foo1` instead of `http//example.com/db/foo1`. 

### Workaround 

Select "New remote database" as target and write the url by hand. 

### Version 

2.2.0-RC2

**Comment by popojargo** [comment]
You should move this issue to https://github.com/apache/couchdb-fauxton

**Comment by ceremcem** [comment]
Sorry, my mistake. Moved to https://github.com/apache/couchdb-fauxton/issues/1118
