### ISSUE TITLE
Performance testing & benchmark suite

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#1520]
Cloudant has done some great things behind closed doors (looking at @kocolosk @garrensmith @tonysun83 ) but it'd be nice to have a "performance team" we can look to, to help with improving CouchDB performance, and a standard *open source* performance suite we can run on a regular basis.

@janl:
>We need a team to comprehensive look at CouchDB performance. There is a lot of low-hanging fruit like Robert Kowalski showed a while back, we should get back into this. I’m mostly [inspired by SQLite](https://web.archive.org/web/20160305085922/http://permalink.gmane.org/gmane.comp.db.sqlite.general/90549) who’ve done a release a while back that only focussed on 1-2% performance improvements, but got like 20-30 of those and made the thing a lot faster across the board. I can’t remember where I read about this, but I’ll update this once I find the link.

@nolanlawson:
>Here's that [SQLite article you mentioned](https://web.archive.org/web/20150905173925/http://permalink.gmane.org/gmane.comp.db.sqlite.general/90549).
>
>We have some perf tests in PouchDB that can absolutely be pointed at CouchDB (in fact, they work on Couch today). Due to being tuned for Pouch rather than Couch, though, many of them will probably be network-bound rather than CPU-bound.

**Comment by janl** [comment]
cc @chewbranca

**Comment by nickva** [comment]
We have been looking at performance improvements lately and have released a bunch in 3.3:  https://docs.couchdb.org/en/stable/whatsnew/3.3.html#highlights

Some details in https://github.com/apache/couchdb/issues/4308:
 * https://github.com/apache/couchdb/pull/4238
 * https://github.com/apache/couchdb/pull/4201
 * https://github.com/apache/couchdb/pull/4193
 * https://github.com/apache/couchdb/pull/4185
 * https://github.com/apache/couchdb/pull/4179
 * https://github.com/apache/couchdb/pull/4163
 * https://github.com/apache/couchdb/pull/4144
 * https://github.com/apache/couchdb/pull/4059
 * https://github.com/apache/couchdb/pull/4056
 * https://github.com/apache/couchdb/pull/4052
 
There is even a simple built-in diagnostic fabric_bench module: https://github.com/apache/couchdb/pull/4601

However, in general, a dedicated Apache CouchDB perf team hasn't happened in 5 years. It's mostly noticing regressions, bottlenecks, and lock contentions and fixing accordingly by contributors.

In light of that, let's close the issue. If we want to revive it, and there is suddenly some interest we can re-open it.
