### ISSUE TITLE
Synthetic load test suite

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#1521]
@janl:
> This one is for end users. I’d like to be able to say: My app produces mostly 10-20kb-sized docs, but millions of those in a single database, or across 1000s of databases, with these views etc. and then run this on target hardware so I’d know, e.g. how many nodes I need for a cluster with my estimated workload. I know this can only be done in approximation, but I think this could make a big difference in CouchDB adoption and feed back into Perf Team mentioned above.

@wohali:
> Neighbourhoodie has some harnesses like this now - we may be able to open source them?

**Comment by nickva** [comment]
Implemented in https://github.com/apache/couchdb/pull/4601
