### ISSUE TITLE
Support Elixir for CouchDB internals (not just the test suite)

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#1522]
@janl:
>I’d like it very much if we elevate Elixir as a prime target language for writing CouchDB internals. I believe this would get us an influx of new developers that we badly need to get all the things I’m listing here done. Somebody might be looking into the technical aspects of this already, but we need to decide as a project if we are okay with that.

@rnewson:
>I think it would be a mistake to mix two languages within, say, fabric, or couch_db_* modules. I'm not even sure it's wise or healthy to have some applications within the couchdb release tarball that are wholly elixir when all the current ones are wholly erlang. I obviously accept that erlang syntax is a barrier to many, and while I feel that's unreasonable (all syntax is weird) it does seem to be an accepted truth. So, for me, there's a discussion on how we would handle the mixed case. Perhaps there's even a discussion on whether we should, at least in principle, plan on fully migrating to elixir (over time / releases). The reason to do this is predicated on the assertion that there's a larger (compared to erlang) crowd of developers that would work on or with couchdb if we did so. That's obviously speculative, but it's the question to answer. If we would gain no more visibility, no more developer / contributor activity within the project or surrounding it, then it would be a spectacular waste of time. I daresay we might lose existing contributors in the push. I'll say, for my part, that I would learn and develop in Elixir if that was the consensus of the CouchDB community.

@davisp:
> On Elixir I mostly agree. I haven't used it personally but it does look like it could be a productivity enhancement. While Erlang's syntax is weird (and that's not an execuse), Erlang unquestionably has a very dense standard library which I find to be the hardest part of learning "Erlang". Heck, I've been writing Erlang full time for five years and I still have to reference the lists module documentation almost daily because argument ordering is so willy nilly. And then beyond that there's the depth of knowledge to use OTP correctly. From what I've seen Elixir has a more consistent design and fixes a number of things of that nature. Whether or not that gets us more devs or not I couldn't say for sure but I'd be more than willing to give it a try and hope that it just becomes obvious one way or the other whether its worth it.

We now have a huge push for Elixir for CouchDB test suite that will land imminently - it's a first step and will build more familiarity with the language in the core team. Yay!

**Comment by janl** [comment]
let’s get the test suite down before considering this again, closing in the meantime,
