### ISSUE TITLE
Retire the node-local interface (port 5986)

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#1523]
This can be done in two phases:

1. Move relevant 5986 port functions under `/_node/<nodename>/...` such as:
    * _dbs
    * _nodes
    * per-shard DB operations (all)
1. Actually eliminate `couch_httpd`.

@davisp thought this might go under the new HTTP/2 API/internals but I think they're distinct efforts.

**Comment by denib** [comment]
@rnewson took over the WIP PR: https://github.com/apache/couchdb/pull/2092
This is in progress.
