### ISSUE TITLE
list functions in v2.2.0

### ISSUE THREAD

**Issue by wactbprot** [apache/couchdb#1544]
after the upgrade from v2.1.x to v2.2.0 we observe that our list functions 
frequently (~half of repeated requests to the same url) return with:

```
error: "render_error",
reason: "function raised error: (new TypeError("req.query is undefined", "lists.sum", 5)) stacktrace: ([object Object],"noproc")@lists.sum:5 runList(function (head, req) { ...
```

As can be seen above: the request object ``req`` in the list-``function(head, req) {..}`` turns to the string ``noproc``. We toke care of cache issues etc. and found the problem occur with different browsers and even curl.

* Version used: 2.2.0 (2.2 rc2 worked as I remember, same problem in rc3)
* Browser Name and version: several browsers and also curl shows the problem
* Operating System and version (desktop or mobile): desktop, openSuse

**Comment by janl** [comment]
> 2.2 rc2 worked as I remember

@wactbprot could you verify that’s the case?

**Comment by wactbprot** [comment]
We rebuild rc1, rc2 and rc3: I remembered wrong, all the same. The problem is introduced with 2.2.0-rc1.
During the tests we noticed that maybe the request header plays a role: the GETs with good old w3m work. I'll do some research on this...

**Comment by janl** [comment]
@wactbprot thanks!

**Comment by wohali** [comment]
@wactbprot Are you using `eval` in your function? This was disabled by default in 2.1.1:

https://github.com/apache/couchdb/pull/916

From the release notes:

> #916: couchjs now disables eval() and the Function() constructor by default. To restore the original behaviour, add the `--eval` flag to the definition of the javascript query server in your `local.ini` file.

**Comment by wohali** [comment]
FYI I just tested a very basic `list` function and it worked fine here.

**Comment by wactbprot** [comment]
What we have so far is this: 
- we tried firefox with a simple list function; the following header (shift+page reload) work 100%:
```
Host: localhost:5984
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Pragma: no-cache
Cache-Control: no-cache
```
without the last two params (normal page reload)  our list returns the error above in ~40%. 

- with chromium neither:
```
Host: localhost:5984
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
DNT: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
```
nor:
```
Host: localhost:5984
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Upgrade-Insecure-Requests: 1
DNT: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
```
works 100%.

**Comment by wactbprot** [comment]
> @wactbprot Are you using eval in your function? This was disabled by default in 2.1.1:

no, no ``eval()`` in use

**Comment by wohali** [comment]
@wactbprot Can you provide a complete example, including the request being issued? Ideally if you can reproduce this with `curl` and not a browser, I'd appreciate it.

**Comment by rnewson** [comment]
we need the actual list function please. I've also tested a simple list function with 2.2.0 and it works as expected.

**Comment by janl** [comment]
and sample docs

**Comment by rnewson** [comment]
I've also tested with req.query itself, and that worked too;

curl foo:bar@localhost:15984/db1/_design/foo -XPUT -d '{"_id":"_design/foo","_rev":"3-3b014c7cc4ce97cb961af560fba50e27","views":{"bar":{"map":"function(doc){emit(doc._id);}"}},"lists":{"baz":"function(head,req){start();while(row=getRow()){send(toJSON(req.query));}}"}}'

curl 'foo:bar@localhost:15984/db1/_design/foo/_list/baz/bar?foo=bar'
{"foo":"bar"}{"foo":"bar"}{"foo":"bar"}{"foo":"bar"}%

**Comment by wactbprot** [comment]
- first: no ``eval()`` but ``require()`` ...? 
> Can you provide a complete example, including the request being issued?
hm, I'll try if the error occurs on a empty database

**Comment by wactbprot** [comment]
I can not reproduce the error with new created list functions. The problem remains with the old ones.
I deleted and re-deployed the old function; same behavior. I striped down the old list function to a 
``start()`` and ``send()`` and get (sometimes):
```{
error: "render_error",
reason: "function raised error: (new TypeError("req.query is undefined", "lists.sum", 19)) stacktrace: ([object Object],"noproc")@lists.sum:19 
runList(function (head, req) {start({headers: {'Content-type': "text/html; charset=utf-8"}});send(req.query.startkey);},[object Object],[object Array])@./share/server/main.js:998 (function (head, req) {start({headers: {'Content-type': "text/html; charset=utf-8"}});send(req.query.startkey);},[object Object],[object Array])@./share/server/main.js:1064 ("_design/az",[object Array],[object Array])@./share/server/main.js:1537 ()@./share/server/main.js:1582 ()@./share/server/main.js:1603 @./share/server/main.js:1 "
}```

**Comment by wohali** [comment]
@wactbprot Please share:

* Your OS & version
* How you installed CouchDB (docker, packages, Windows/Mac binary, from source, etc.)
* How you installed SpiderMonkey 1.8.5 (Apache packages, vendor packages, from source, etc.)
* A full list and view function that replicates this problem if you please

**Comment by rolfn** [comment]
I am a co-worker of wactbprot and can give some answer:

> Your OS & version

openSUSE 42.3 and openSUSE tumbleweed

> How you installed CouchDB

I created a rpm file similar to the Fedora rpm file. This worked in the past from 2.0.0 to 2.1.2 without errors.

> How you installed SpiderMonkey 1.8.5

I created a rpm file `couch-js` with the source files from [/apache/couchdb-pkg/tree/master/js/rpm](/apache/couchdb-pkg/tree/master/js/rpm)

**Comment by wohali** [comment]
Hi @rofln,

Yes, Ubuntu 16.04 packages for 2.2.0 are available right now. Please test and let us know if you see the problem there as well. My guess is something about your openSUSE build of `couchjs` is interfering, but I can't be sure.

You can also test whether or not adding the `--eval` flag to the definition of the javascript query server in your local.ini file helps, though if you're not using `eval()` or `Function()` it shoudln't. This was a change in 2.1.1, #916 , so you should have seen the effect already, but it's worth validating.

**Comment by rolfn** [comment]
> My guess is something about your openSUSE build of couchjs is interfering, but I can't be sure.

I don't think that this can be the reason. We use the same (!) `couchjs` code for CouchDB 2.1.2 too without any problems.

More tests will be following.

**Comment by wactbprot** [comment]
The Ubuntu 16.04 packages for 2.2.0 shows the same erroneous behavior as the opensuse packages "compiled" by us. ``--eval`` doesn't change anything. Once again: the problem definitive occurs with ``2.2.0-rc1``. We are not able to provide a simple example for testing etc; we belive, that a certain degree of complexity is part of the problem.

**Comment by wactbprot** [comment]
Any ideas what we can do or test? So far we have to stay at 2.1.

**Comment by wohali** [comment]
@wactbprot Thanks for the confirmation that you see the same issue in 2.2.0 as we build it.

We need a reproducible test case. Please provide us with documents and a list function that reproduce the problem. We'll be more than happy to fix the problem once we have a way to reproduce it.

Looking at the source code, nothing obvious has changed in our couchjs or _list implementations between the releases:

https://github.com/apache/couchdb/tree/master/src/couch/priv/couch_js
https://github.com/apache/couchdb/tree/master/share/server
https://github.com/apache/couchdb/blob/master/src/chttpd/src/chttpd_show.erl

so there's no "smoking gun" here.

**Comment by wactbprot** [comment]
> We need a reproducible test case. Please provide us with documents and a list function that reproduce the problem. We'll be more than happy to fix the problem once we have a way to reproduce it.

We really understand that. However:  

> We are not able to provide a simple example for testing etc;

 I spend several hours with the attempt. We were not even able to find a pattern of request fails.

Only one example: 
If I use chromium the request fails in half of the requests as reported. If I use curl with the same request header (chrom has the opportunity to generate the curl equivalent) the request works 100%.

**Comment by wohali** [comment]
Hm, that is interesting.

Do you have any sort of reverse web proxy in front of CouchDB? This might be an incompatibility with e.g. nginx, which is commonly misconfigured. We recommend HAProxy for best compatibility - it's what most of the CouchDB clusters at scale use.

**Comment by wohali** [comment]
Follow-up question: Are you using CouchDB's native SSL support (httpsd)?

**Comment by wactbprot** [comment]
No proxy no SSL, in most of the tests I use a simple request to localhost w/o auth.

May I ask the other way around: can you try to find out or imagine under which conditions the second parameter of the anonymous list function catn become noproc? Is noproc a Erlang atom?

**Comment by wohali** [comment]
@wactbprot I'm just the issue triager, someone else will be along in a bit to dig deeper on this.

**Comment by wactbprot** [comment]
great!

**Comment by wohali** [comment]
The trimmed-down list function:

```
function (head, req) {start({headers: {'Content-type': "text/html; charset=utf-8"}});send(req.query.startkey);
```

Any sort of document will do for this.

**Comment by wohali** [comment]
One last idea - if you turn up couchdb logging to debug level, do you see anything useful in the logs when this fails?

**Comment by wohali** [comment]
@wactbprot here is my current test case. The [above doc](https://github.com/apache/couchdb/issues/1544#issuecomment-411790429) is stored into `/abc/_design/lists-1544`.

I have a file `headers.txt` with the following content:

```
Host: localhost:5984
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Connection: keep-alive
Upgrade-Insecure-Requests: 1
```

I'm then issuing the following command (note: my couchdb is running on port 15984)

```bash
while true; do curl -v -H "$(cat headers.txt)" localhost:15984/abc/_design/lists-1544/_list/results/variants?startkey=\"abc\" 2>&1 | grep render_error; done
```

So far every request is succeeding. Are you able to confirm whether the above fails for you at all?

**Comment by wohali** [comment]
OK, I ran the test like that for 40 minutes, with no reproduction. @rnewson ran tests too. Neither one of us were able to reproduce with this harness. Sorry :(

**Comment by ermouth** [comment]
We were able to reproduce more or less reliably in this way:

* make a VM, we use Parallels, 2 cores, 2GB, Xenial in this case
* build 2.2 cluster from sources and run, 1 machine with 3 nodes, default cfg
* log in using browser outside of VM; we use Photon to log in, however it seems insignificant
* create a bucket, no security
* replicate some docs into new bucket (we put 250 docs, about 15 Mb JSON in total)
* make a ddoc with a simple list (very similar to the above) and a view, emitting all docs under same key with full body, like `emit('abc', doc);` 
* tap view to build the index
* put request string with _list into browser address bar
* run list in browser tab
* log out
* **put VM on pause for 5+ minutes** – key point
* wake up VM
* reload page with list several times.

Very likely you will see error message like in the issue, often several times. Eventually things become ok.

Not sure, but seems longer VM pauses somehow increase probability of seeing error.

Hope it helps.

**Comment by wohali** [comment]
@ermouth are you able to upload a `couch.log` file of this, preferably running at debug level, that captures the problem?

**Comment by ermouth** [comment]
Another one [log2.log](https://github.com/apache/couchdb/files/2275839/log2.log)

Here I reload Photon, and then immediately have errors several times, and then finally have expected response.

**Comment by ermouth** [comment]
`OS Process #Port<0.29670> Input  :: ["ddoc","_design/lists2",["lists","results"],[{"total_rows":260,"offset":0},"noproc"]]`

Here I see noproc msg instead of req obj. Seems it’s the only place able to return `"noproc"` string instead of req obj is https://github.com/apache/couchdb/blob/2.2.x/src/couch_mrview/src/couch_mrview_show.erl#L367-L377. However, I can’t see how it happens because I don’t clearly understand what this code does.

**Comment by wactbprot** [comment]
We found the region where the problem is introduced:
```
f6a771147ba488f80a7d29491263d19088d0eefb (t13) Implement pluggable storage engines
8e34ce382dcdf16a2d68a0f0ac45f300c91e6844 (t12) Add legacy storage engine implementation
fb2b046b288405f60a261552cacd57584fce72fd (t16) Add couch_db_engine module
364ea209250df169f0c7425cf0003e20a5a2d28d (t15) Remove old rolling reboot upgrade code
083239353e919e897b97e8a96ee07cb42ca4eccd (t14) Prevent chttpd multipart zombie processes
6d959a7acab7d0ff110c7799f3295b6193f45c2f (t17) Avoid unconditional retries in replicator's http client
302bd8b8b193186b920c56c918bb2bb7edc4be8a (t11) feat: update mochiweb to 2.17.0
49
```
* branch t11 works
* branch t13 don't
* the branches in between don't compile

**Comment by rnewson** [comment]
@wactbprot @ermouth Can you try the above patch (https://github.com/apache/couchdb/pull/1553)?

I think what's happening is that an error from somewhere _else_ is getting swapped for the req.query value. The patch above should ensure we wait for the right 'DOWN' message.

I expect a) you no longer get the error reported b) your log shows a _new_ error that I would very much like to see.

**Comment by mtabb13** [comment]
I have come across a bug in v2.1.2 querying _changes.  It doesn't fail every time, maybe once or twice a day.  The application code calling this endpoint runs on a 30 second polling interval.  The same code worked in 2.0 and 2.1.1 without problems.  I get the following error:

`fabric_rpc:changes/3 error:{badmatch,{'EXIT',noproc}} [{couch_file,pread_binary,2,[{file,"src/couch_file.erl"},{line,169}]},{couch_file,pread_term,2,[{file,"src/couch_file.erl"},{line,157}]},{couch_btree,get_node,2,[{file,"src/couch_btree.erl"},{line,434}]},{couch_btree,reduce_stream_node,11,[{file,"src/couch_btree.erl"},{line,619}]},{couch_btree,fold_reduce,4,[{file,"src/couch_btree.erl"},{line,81}]},{couch_db,count_changes_since,2,[{file,"src/couch_db.erl"},{line,1407}]},{fabric_rpc,changes,4,[{file,"src/fabric_rpc.erl"},{line,80}]},{rexi_server,init_p,3,[{file,"src/rexi_server.erl"},{line,139}]}]`

**Comment by ermouth** [comment]
@rnewson We‘ll test the patch on Tuesday. Could you please explain shortly what that code intended to do? Particularly, why so tricky way to call a fn is used?

**Comment by wactbprot** [comment]
>I expect a) you no longer get the error reported b) your log shows a new error that I would very much like to see.

@rnewson  patch fixes our list issues completely.
 on b) don't observe any error messages  related to our list requests (log level debug)

@couchdbteam Thanks a lot for your work!

**Comment by wohali** [comment]
@wactbprot Thanks for the confirmation. We'll get this update into the very next release of CouchDB.

**Comment by ermouth** [comment]
I also confirm that the issue seems to be fixed with the patch.
