### ISSUE TITLE
adduser: gecos group doesn't exist

### ISSUE THREAD

**Issue by nicolas15000** [apache/couchdb#1545]
Hello , Im following 
http://docs.couchdb.org/en/master/install/unix.html

When i hit this command :+1: 

adduser --system \
        --shell /bin/bash \
        --group --gecos \
        "CouchDB Administrator" couchdb

This is the error :+1: 
adduser : le groupe « --gecos » n'existe pas

in english :+1: 
gecos group doesnt exist, 

im bloqued please help

**Comment by nicolas15000** [comment]
I cant create the couchdb user, please help, geco group doesnt exist, why did you add --geco ?

**Comment by wohali** [comment]
@nicolas15000 Looks like your adduser command has a different syntax.

For GNU adduser, `--system --group` will create a group with the same name and ID as the system user.

Which OS are you on?

**Comment by wohali** [comment]
On Ubuntu bionic (18.04):

```
root@67bec2d34961:/# adduser --system --group foo
Adding system user `foo' (UID 102) ...
Adding new group `foo' (GID 103) ...
Adding new user `foo' (UID 102) with group `foo' ...
Creating home directory `/home/foo' ...
```

**Comment by nicolas15000** [comment]
Hello, finally, its is because when you install couchdb from the ubuntu installation graphic app, it puts it inside a readonly directory called snap, then you cant change anything

**Comment by wohali** [comment]
@nicolas15000 Thanks for the info. As mentioned, the snap is outdated and unsupported, we've unpublished it from the snapcraft store.

**Comment by andreheringer** [comment]
Hi, I'm experiencing the same behaviour described above, but on Fedora 31. Runnig the command `sudo adduser --system --home /usr/local/var/lib/couchdb --no-create-home --shell /bin/bash --group --gecos "CouchDB Administrator" couchdb`

Returns "group --gecos does not exists"

Any ideias?

**Comment by MayurGavali** [comment]
Hi, I'm experiencing the same behaviour described above, but on Fedora 31. Runnig the command sudo adduser --system --home /usr/local/var/lib/couchdb --no-create-home --shell /bin/bash --group --gecos "CouchDB Administrator" couchdb

Returns "group --gecos does not exists"

Any ideias?
The same issue is getting for me as well...
