### ISSUE TITLE
couchDb not present in /home

### ISSUE THREAD

**Issue by nicolas15000** [apache/couchdb#1546]
Hello, 
I'm following the following doc : 

http://docs.couchdb.org/en/master/install/unix.html

I have done this command on cent os 7 : 
 sudo yum -y install epel-release && yum install couchdb

Then, when i hit this command, for a first start, it doesnt work :+1: 
sudo -i /home/couchdb/bin/couchdb

**couchdb doesnt exists in home.**

it doesnt work.

**Comment by janl** [comment]
The packages take care of setting up CouchDB properly and not in `/home`, but in `/opt/couchdb`. The instructions you’re seeing are for a manual set up without the epel packages.
