### ISSUE TITLE
Ubuntu snap installer creates uneditable vm.args

### ISSUE THREAD

**Issue by nicolas15000** [apache/couchdb#1547]
Hello, 
I've got ubuntu 18.0 

When i'm installing couchdb with the ubuntu software graphic application,  couch db get installed inside a **'snap' directory,** then i can't change the vm.args file .
How can i do now ?  i need to change the vm.args file, and it is read only.

thank you

**Comment by wohali** [comment]
@nicolas15000 the "snap" installer is currently out of date and unsupported.

You should try the .deb package, it's super easy to install. Please follow these instructions:

http://docs.couchdb.org/en/2.2.0/install/unix.html#installation-using-the-apache-couchdb-convenience-binary-packages

**Comment by wohali** [comment]
The outdated 2.0.0 unsupported CouchDB snap package has been unpublished. Thanks for the nudge.
