### ISSUE TITLE
Ubuntu ./configure not working

### ISSUE THREAD

**Issue by nicolas15000** [apache/couchdb#1548]
Hello, i've followed the couchdb setup to download couchdb on my ubuntu 18 (chapter 2.1.3.1 Debian based system) :+1: 

Then, i type this :+1: 

`./configure 
`
This is the unbutu response :+1: 
`bash : ./configure: no such file or directory `

It doesnt work , ./configure doesnt exist.

**Comment by janl** [comment]
@nicolas15000 can you paste the exact steps you’ve followed from download to `./configure`?

**Comment by nicolas15000** [comment]
Im on nicolas2@nicolas2-virtual-machine:/$ 


**part 1 :** ive done that :+1: 

Debian/Ubuntu: Run the command:

$ echo "deb https://apache.bintray.com/couchdb-deb {distribution} main" \
    | sudo tee -a /etc/apt/sources.list

and replace {distribution} with the appropriate choice for your OS version:

**Part 2** 

Debian/Ubuntu: First, install the repository key:

$ curl -L https://couchdb.apache.org/repo/bintray-pubkey.asc \
    | sudo apt-key add -

Then update the repository cache and install the package:

$ sudo apt-get update && sudo apt-get install couchdb

**part 3** 

2.1.3.1. Debian-based Systems

You can install the dependencies by running:

sudo apt-get --no-install-recommends -y install \
    build-essential pkg-config erlang \
    libicu-dev libmozjs185-dev libcurl4-openssl-dev


then finally i type 

./configure
This is the unbutu response +1
bash : ./configure: no such file or directory

It doesnt work , ./configure doesnt exist.

**Comment by nicolas15000** [comment]
Ho i think i just have somthing, doing this seems to work :+1: 
$ sudo apt-get install couchdb

from the part 2 , please notice i  have removed 
$ sudo apt-get update &&

**Comment by janl** [comment]
@nicolas15000 after `apt-get install couchdb` CouchDB will be installed and you should be able to start it with `server couchdb start` or a variant thereof. You don’t have to do any more steps, especially not `./configure`. You’re mixing up instructions for installing CouchDB from source and CouchDB as a binary package. Stick to the latter one,

**Comment by nicolas15000** [comment]
Thank you, it is working now, the problem was coming because i was installing from the graphical interface, should have installed with apt get
