### ISSUE TITLE
I need help with some queries

### ISSUE THREAD

**Issue by strelok1010** [apache/couchdb#1552]
I have a database with more than 400.000 documents.
The problem is that making queries in that database takes between 16-22 seconds even using indexes.
The structure of the documents is like this:

```
{
  "_id": "http://www.domain.com/product/,
  "_rev": "1-1edcfd45_my_revision,
  "lastscan": 1498424497,
  "title": "Title page",
  "name": "category"
}

```
The strcture of the index is like this:

```
{
  "_id": "_design/index_mydb_myindex",
  "_rev": "1-1a0cd_my_revision",
  "language": "query",
  "views": {
    "index_mydb_myindex": {
      "map": {
        "fields": {
          "name": "asc"
        },
        "partial_filter_selector": {}
      },
      "reduce": "_count",
      "options": {
        "def": {
          "fields": [
            "name"
          ]
        }
      }
    }
  }
}
```

The goal is to filter by "name". It is possible that my indices are badly created, is the only explanation that I consider probable to explain the slowness of the consultations.

The query I do uses regular expressions with $ regex
`$regex = "(?i)(?:".$data["data1"]."|"										.$data["data2"].".*".$data["data3"]."|".$data["data3"].".*".$data["data2"]."|" 									.$data["data2"]. ".*".$data["data4"]."|".$data["data4"].".*".$data["data2"].")";`

I need help, please.

**Comment by detroitenglish** [comment]
See documentation section [10.3.6.1.8. Condition Operators](http://docs.couchdb.org/en/stable/api/database/find.html#condition-operators):

> Warning
> Regular expressions do not work with indexes, so they should not be used to filter large data sets.

**Comment by wohali** [comment]
Exactly what @detroitenglish said - `$regex` will always do a full database scan. You can tell your query isn't using an index by making the same query against the `/dbname/_explain` endpoint, which will show which indexes are being used (and, I believe in 2.2, warns about the `$regex` operator...but I might be wrong.)

Your options are:

1. Create partial indexes using `$regex` and then query those with exact operators,
1. Use `$or` to search each of the fields via an exact, `$eq` based approach
1. Consider using the `$in` operator, but keep in mind this will still have to fully scan all documents in an index (thus, being faster than `$regex`, but will be slower than an exact-based search)
1. Build a custom CouchDB that includes the dreyfus/clouseau support (which is Apache Lucene based) and do a full-text search using the `$text` operator

Hopefully one of these options will help.

**Comment by strelok1010** [comment]
Could you help me install dreyfus / clouseau ?. I tried to install lucence, more than 1 week ago I am trying, but without positive results. My current level is not enough to understand how to install lucence, maybe the ones you recommend are simpler to install (dreyfus / clouseau) could you help me please?

**Comment by wohali** [comment]
@strelok1010 dreyfus/clouseau include Lucene as a dependency. The best installation instructions of which I'm aware are here:

https://github.com/cloudant-labs/dreyfus/wiki/Introduce-dreyfus-into-couchdb

Older instructions that are easier to read but are no longer 100% accurate are here: https://developer.ibm.com/dwblog/2015/text-search-apache-couchdb/#.WB9FOZNS1-U
