### ISSUE TITLE
Is it the right way to load balance couchdb with nginx?

### ISSUE THREAD

**Issue by nicolas15000** [apache/couchdb#1555]
So i have this 3 machine couchdb cluster working very well . Each are ubuntu 18.0 versions.

So now, my goal is to add a 4th machine, with NGINX as a load balancer .

I 've edited my following file nginx-config-directory/sites-available/defaut

And have added this :

```
upstream couchDbCluster {
   server 10.1.0.101:5984; 
   server 10.1.0.102:5984;
   server 10.1.0.103:5984;
}


location /couchdb {
    rewrite /couchdb/(.*) /$1 break;
    proxy_pass http://couchDbCluser;
    proxy_redirect off;
    proxy_buffering off;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

```
Do you think it is the right syntax ?

i wonder if one gentle person could tell me if that is the right way to load balance inside my couchdb ?

What is strange is that i would like to separate when it is a GET or a PUT for example, and this code doesn't seem to care about this . How could i do faster GET queries ?

Do I have to change another file ?

Thanks you a lot for your help, have a nice day !

**Comment by wohali** [comment]
Through experience, CouchDB developers recommend using [HAProxy](https://www.haproxy.org/) as a load balancer. We provide a default configuration that just works™ here: https://github.com/apache/couchdb/blob/master/rel/haproxy.cfg

We do [document our recommended Nginx configuration](http://docs.couchdb.org/en/stable/best-practices/nginx.html) as well. Getting it right is difficult, and there are specific issues with configuring Nginx properly as a reverse proxy for CouchDB when you are using replication, so be sure to review our documentation.

At present, CouchDB does not natively have the concept of "read-only replicas," so there is no need to separate `GET` and `PUT` requests.

Finally, remember that in a 2.x CouchDB cluster, additional nodes don't participate in requests for databases you've already created unless you move shards to those new nodes. See the new 2.2.0 documentation on [shard management](http://docs.couchdb.org/en/stable/cluster/sharding.html) for more details.
