### ISSUE TITLE
Replication not working in the new version 2.2.0

### ISSUE THREAD

**Issue by HilmiDEV** [apache/couchdb#1561]
I tried to use the new version of couchDB 2.2.0 and I failed to replicate my databases from couchDb 1.6.0 to 2.2.0 (I tried fauxton GUI and also the CLI with curl).

Additionally, I use pouchdb for the mobile purpose to replicate couchDB databases but the replication in this case also failed.

Also I tried to find another versions bit I dind not find the other realeases for couchDB.

So is couchDB changed its replication API or is it a bug in this version ?  

OS : Ubuntu 18.04 
browser chrome version 66.0.3359.181

**Comment by willholley** [comment]
@HilmiDEV replication between older CouchDB versions/PouchDB and 2.2.0 should work just fine.

Are there any errors in your CouchDB or PouchDB logs that suggest why it's failing?

**Comment by HilmiDEV** [comment]
I found the solution, the problem seems to be in this issue
https://github.com/apache/couchdb/issues/1550

You must active the option **auth_plugins** in the file /opt/couchdb/etc/default.ini

```
[replicator]
auth_plugins = couch_replicator_auth_noop
```
And now it is working
