### ISSUE TITLE
Couch 2.x cluster returning inconsistent _all_docs

### ISSUE THREAD

**Issue by arifcse019** [apache/couchdb#1564]
We have a three node couchDB 2.x (one 2.1.1 and two 2.1.2) cluster which is returning inconsistent number of _all_docs when we hit _all_docs endpoint on any db that has more documents in addition to two _design docs (i.e logDocs and permissions).

## Expected Behavior
_all_docs response should be consistent among calls to a <db>/_all_docs endpoint

## Current Behavior
cluster which is returning inconsistent number of _all_docs when we hit _all_docs endpoint on any db that has more documents in addition to two _design docs (i.e logDocs and permissions).

Following are some error messages from the log file 

[error] 2018-08-16T18:16:15.150627Z couchdb@trinary.couchcluster.internal <0.16547.1789> -------- Error opening view group `permissions` from database `shards/55555554-71c71c6f/shadow_4495.1514409098`: {'EXIT',{{{badmatch,{error,emfile}},[{couch_file,init,1,[{file,"src/couch_file.erl"},{line,398}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,304}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]},{gen_server,call,[couch_index_server,{get_index,{couch_mrview_index,{mrst,<<62,130,60,42,67,131,172,12,24,212,229,116,19,90,91,8>>,nil,undefined,<<"shards/55555554-71c71c6f/shadow_4495.1514409098">>,<<"_design/permissions">>,<<"javascript">>,[],false,false,{[]},[],nil,nil,0,0,undefined,undefined,undefined,undefined,undefined,nil},<<"shards/55555554-71c71c6f/shadow_4495.1514409098">>,<<62,130,60,42,67,131,172,12,24,212,229,116,19,90,91,8>>}},infinity]}}}

[error] 2018-08-16T18:15:00.068553Z couchdb@secondary.couchcluster.internal <0.26642.4837> -------- CRASH REPORT Process couch_index_server (<0.26642.4837>) with 1 neighbors exited with reason: no match of right hand value {error,emfile} at couch_file:init/1(line:398) <= gen_server:init_it/6(line:304) <= proc_lib:init_p_do_apply/3(line:239) at gen_server:terminate/6(line:744) <= proc_lib:init_p_do_apply/3(line:239); initial_call: {couch_index_server,init,['Argument__1']}, ancestors: [couch_secondary_services,couch_sup,<0.204.0>], messages: [], links: [<0.4278.4837>,<0.19436.4831>], dictionary: [], trap_exit: true, status: running, heap_size: 6772, stack_size: 27, reductions: 1050564

## Possible Solution
 N/A

## Steps to Reproduce (for bugs)
1. curl -v -X GET http://127.0.0.1:5984/<db>/_all_docs --user <user-name>:<password>
2. Run the above command again. Two responses are different

## Context

Please note, we recently replaced two nodes in the cluster. The nodes got replaced were named like couchdb@ip-address whereas the nodes replaced them are named as couchdb@fqdn . Following is a high level process we followed:

- Stop couchDB process in the outgoing node
- Add the incoming node to the cluster
- Update cluster metadata for all databases replacing the outgoing node with the incoming one (in both by_node and by_range dictionaries)
- Wait until all shards have arrived at the new node
- Delete the old node from the cluster

## Your Environment
* Version used: 2.1.1. on one node and 2.1.2 on the other two
* Browser Name and version: Chrome and curl
* Operating System and version (desktop or mobile): Ubuntu 14.04.5 LTS 
* Link to your project:

**Comment by wohali** [comment]
@arifcse019 Are you following our new documentation on shard management? The documentation is accurate, even if you are not on 2.2.0.

Link: http://docs.couchdb.org/en/stable/cluster/sharding.html

**Comment by arifcse019** [comment]
The issue got resolved by restarting one node in our cluster.

I used this documentation http://docs.couchdb.org/en/2.1.2/cluster/sharding.html. I did not manually copy shard files to the new node instead I let the internal replication do that job for me after I have updated the cluster metadata for all _dbs using a script. 
 
Please note, there were never an inconsistency for any individual document. The inconsistency was limited only to the _all_docs view

However, I never took the cluster offline while moving shards using internal replication. Can that cause the  inconsistency? I mean there could have been write operations in progress when the cluster metadata got updated for a particular DB. That would mean write is going to the old node and a stale version of shard is coming to the new node?

Anyway, thanks for responding

**Comment by wohali** [comment]
@arifcse019 Yes,  you need to keep the node that's being updated in `maintenance_mode` until it's fully caught up with internal replication (or you finish copying around the shards manually).

Thanks for updating us!
