### ISSUE TITLE
very slow (scrypt) calculation since CouchDB2.2

### ISSUE THREAD

**Issue by linacs** [apache/couchdb#1575]
Since I updated CouchDB from 2.1 to 2.2, CouchJS calculation with an implementation of Scrypt algorithm has become very slow (2 to 3 times more computation time).

## Expected Behavior
Scrypt is used by my webapp (CouchApp) for password hash. Usually, it took 5 seconds to compute.

## Current Behavior
Most of the time, the login request sends back a 500 error (timeout).
I had to raise os_process_timetout to 20000 and it is still failing sometimes. It has become very long to log in. Performance depends on the machine. On AWS, it takes around 12 seconds to log in, now. On Scaleway (ATOM CPU) it fails most of the time.

## Possible Solution
Except from increasing CPU performance (which is very complicated: most of the time you can get more CPUs, but they are all the same, and the JS algorithm is of course not threaded), I see only one solution for me right now: put the scrypt hash checking (and JWT generation) outside of my CouchApp. I already saw two years ago that NodeJS was way quicker than CouchJS to compute...
Otherwise, I will have to use another password hash algorithm (with the risk of being as slow), and so to ask all my users to change their password with an email campaign...

## Steps to Reproduce (for bugs)
This may be complicated.
I use this implementation: https://github.com/tonyg/js-scrypt
I had to adapt it to work with couchJS. I can send the file.
However, I guess this is not due to this specific algorithm but that it reveals a global problem of performance whenever a CouchApp is computing a lot...

## Context
The time for hashing must not be too long for my users, but it must be long enough to ensure strong security. My main users are school administrators. They can download (for backup) the whole database concerning their school (i.e. a Json document), which includes the hashed passwords. So there's a risk of a leak, hence the strong security.
This is really annoying for my users who now have to wait a lot more to log in (and using my failover cluster has become almost impossible to log in).

## Your Environment
* Version used: 2.2
* Browser Name and version: whatever browser
* Operating System and version (server): Debian Jessy
* Link to your project: www.omniscol.com (I can provide a full test account on a dedicated preprod server with more info if anyone can help me with this, but for security+business reason, I cannot put anything more precise publicly)

Thanks!
Gilles

**Comment by ermouth** [comment]
Could you please provide exact JS code you are running, as a JSON ddoc with instructions? We test perf of new versions, and experienced no serious speed degradation of JS query server from version to version.

BTW how many cores do your have?

**Comment by ermouth** [comment]
@linacs Please, send zipped json with instructions to ermouth at gmail dot com. Also I forgot to ask: do you use cluster or single node mode?  

BTW As I know t2 instances use Xeon able to burst up to 3.5Ghz. For sure, you can’t utilize its full power continuously using t2.small, which is throttled to 20% of a single core computational capacity on average. However if your app is nearly idle most of the time (which is very likely), you are still able to have full CPU power bursts for short periods.

**Comment by linacs** [comment]
It's a cluster for both: 9 VMs on AWS, 3 on Scaleway. I activated T2 Unlimited, indeed, but I didn't see an impact. Maybe it's because it's too fast for the system to de-overcommit or something...
I send you the email. Thanks!

**Comment by wohali** [comment]
Closing as no action for >1 year.
