### ISSUE TITLE
CRASH REPORT  with 0 neighbors exited with reason normal ...

### ISSUE THREAD

**Issue by jvegaseg** [apache/couchdb#1584]
Today this error:

`[[error] 2018-08-28T11:01:05.565470Z couchdb@XX.XX.XX.XX<0.6971.959> -------- gen_server <0.6971.959> terminated with reason: {normal,{gen_server,call,[<0.3369.959>,close,infinity]}} at gen_server:call/3(line:212) <= couch_index:terminate/2(line:122) <= gen_server:try_terminate/3(line:643) <= gen_server:terminate/7(line:809) <= proc_lib:init_p_do_apply/3(line:240)
  last msg: {'DOWN',#Ref<0.0.41418755.187124>,process,<0.6479.959>,killed}
     state: {st,couch_mrview_index,{mrst,<<62,130,60,42,67,131,172,12,24,212,229,116,19,90,91,8>>,<0.3369.959>,#Ref<0.0.41418755.187123>,<<"shards/80000000-8fffffff/_replicator.1510390507">>,<<"_design/_replicator">>,<<"javascript">>,[],false,false,{[]},[],{btree,<0.3369.959>,nil,undefined,undefined,undefined,nil,snappy},nil,0,0,undefined,undefined,undefined,undefined,undefined,nil},<0.31807.958>,<0.31747.958>,[],true,false}
[error] 2018-08-28T11:01:05.596171Z couchdb@XX.XX.XX.XX <0.6971.959> -------- CRASH REPORT Process  (<0.6971.959>) with 0 neighbors exited with reason: {normal,{gen_server,call,[<0.3369.959>,close,infinity]}} at gen_server:terminate/7(line:814) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_index,init,['Argument__1']}, ancestors: [<0.956.959>], messages: [], links: [<0.31747.958>,<0.31807.958>,<0.238.0>], dictionary: [], trap_exit: false, status: running, heap_size: 2586, stack_size: 27, reductions: 1903
[error] 2018-08-28T11:01:05.596388Z couchdb@XX.XX.XX.XX <0.31807.958> -------- gen_server <0.31807.958> terminated with reason: {normal,{gen_server,call,[<0.3369.959>,close,infinity]}}
  last msg: {'EXIT',<0.6971.959>,{normal,{gen_server,call,[<0.3369.959>,close,infinity]}}}
     state: {st,<0.6971.959>,couch_mrview_index,nil}
[error] 2018-08-28T11:01:05.596663Z couchdb@XX.XX.XX.XX <0.31807.958> -------- CRASH REPORT Process  (<0.31807.958>) with 0 neighbors exited with reason: {normal,{gen_server,call,[<0.3369.959>,close,infinity]}} at gen_server:terminate/7(line:826) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_index_updater,init,['Argument__1']}, ancestors: [<0.6971.959>,<0.956.959>], messages: [], links: [], dictionary: [], trap_exit: true, status: running, heap_size: 376, stack_size: 27, reductions: 127
[error] 2018-08-28T11:01:05.596852Z couchdb@XX.XX.XX.XX <0.31747.958> -------- gen_server <0.31747.958> terminated with reason: {normal,{gen_server,call,[<0.3369.959>,close,infinity]}}
  last msg: {'EXIT',<0.6971.959>,{normal,{gen_server,call,[<0.3369.959>,close,infinity]}}}
     state: {st,<0.6971.959>,couch_mrview_index,undefined}
[error] 2018-08-28T11:01:05.597107Z couchdb@XX.XX.XX.XX <0.31747.958> -------- CRASH REPORT Process  (<0.31747.958>) with 0 neighbors exited with reason: {normal,{gen_server,call,[<0.3369.959>,close,infinity]}} at gen_server:terminate/7(line:826) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_index_compactor,init,['Argument__1']}, ancestors: [<0.6971.959>,<0.956.959>], messages: [], links: [], dictionary: [], trap_exit: true, status: running, heap_size: 376, stack_size: 27, reductions: 135`

## Configuration
We use default settings except:

local.ini
```
[cluster]
q = 16

[log]
level = warning
```

vm.args
```
-name couchdb@X.X.X.X
-setcookie XXXXXXXXXXXXXX
-kernel inet_dist_listen_min 9100
-kernel inet_dist_listen_max 9200

-kernel error_logger silent
-sasl sasl_error_logger false

+K true
+A 16
+Bd -noinput
```

sys.config

```
[
    {lager, [
        {error_logger_hwm, 1000},
        {error_logger_redirect, true},
        {handlers, [
            {lager_console_backend, [debug, {
                lager_default_formatter,
                [
                    date, " ", time,
                    " [", severity, "] ",
                    node, " ", pid, " ",
                    message,
                    "\n"
                ]
            }]}
        ]},
        {inet_dist_listen_min, 9100},
        {inet_dist_listen_max, 9200}
    ]}
].
```

## Environment
Software is running on virtualized Centos 7 using OpenVZ 7.
Each node has same configuration.
Each node has 16 cores.
CouchDB: 2.1.1

**Comment by wohali** [comment]
@jvegaseg Did this result in any poor behaviour on the server, or just a logged error message? Couch can throw a lot of error messages even during normal operation, it can be noisy that way.

**Comment by wohali** [comment]
Terminated with reason normal - this is normal behaviour, just a very noisy log message.

**Comment by danieltaylor-nz** [comment]
We are having trouble with our installation of CouchDB and this ticket is the only one I can find with the same error message. We are having several crashes per day with errors like so:
```
[error] 2019-01-21T02:36:46.517675Z nonode@nohost <0.27332.3> -------- CRASH REPORT Process (<0.27332.3>) with 0 neighbors exited with reason: killed at gen_server:terminate/7(line:812) <= proc_lib:init_p_do_apply/3(line:247); initial_call: {couch_index_updater,init,['Argument__1']}, ancestors: [<0.27329.3>,<0.27328.3>], messages: [], links: [], dictionary: [], trap_exit: true, status: running, heap_size: 376, stack_size: 27, reductions: 126
```

```
[error] 2019-01-21T11:44:36.456408Z nonode@nohost <0.29674.15> -------- CRASH REPORT Process (<0.29674.15>) with 0 neighbors exited with reason: killed at gen_server:terminate/7(line:812) <= proc_lib:init_p_do_apply/3(line:247); initial_call: {couch_index_compactor,init,['Argument__1']}, ancestors: [<0.29671.15>,<0.29670.15>], messages: [], links: [], dictionary: [], trap_exit: true, status: running, heap_size: 376, stack_size: 27, reductions: 126
```

I would like to know if based on this, someone can give us some feedback. We are running inside a docker container on a GCE instance 2 vCPUs, 3.75 GB memory, AND CPU usage is always about 3% before a crash.

**Comment by wohali** [comment]
@danieltaylor-nz This is not the same issue.

CouchDB will in normal operation generate some "CRASH REPORTs" in the logfiles. Unless you are having client issues, this is not a problem.

If CouchDB is actually crashing, forcing a process restart, open a new ticket and we'll investigate.
