### ISSUE TITLE
Request: Include cookie expiry time in Set-Cookie header

### ISSUE THREAD

**Issue by flimzy** [apache/couchdb#1598]
When writing CouchDB clients that use Cookie auth, it would be very beneficial to have some idea when the authentication is about to expire, or already has expired, so that authentication can be re-done to refresh the cookie.

At present, CouchDB doesn't give any such clues to the client.  Example (with CouchDB 2.2.20):

    $ curl -v -X POST http://localhost:6004/_session -H 'Content-Type: application/json' -d '{"name":"admin","password":"abc123"}'
    Note: Unnecessary use of -X or --request, POST is already inferred.
    *   Trying ::1...
    * TCP_NODELAY set
    * Connected to localhost (::1) port 6004 (#0)
    > POST /_session HTTP/1.1
    > Host: localhost:6004
    > User-Agent: curl/7.52.1
    > Accept: */*
    > Content-Type: application/json
    > Content-Length: 36
    > 
    * upload completely sent off: 36 out of 36 bytes
    < HTTP/1.1 200 OK
    < Cache-Control: must-revalidate
    < Content-Length: 46
    < Content-Type: application/json
    < Date: Fri, 07 Sep 2018 12:48:28 GMT
    < Server: CouchDB/2.2.0 (Erlang OTP/19)
    < Set-Cookie: AuthSession=YWRtaW46NUI5MjczOUM68IYzw6QYhBU0nLMTM-XQjuRdcrs; Version=1; Path=/; HttpOnly
    < 
    {"ok":true,"name":"admin","roles":["_admin"]}

My request is that we add a `Max-Age` or `Expires` value to the `Set-Cookie` header. This should be set based on the session timeout value.

**Comment by eiri** [comment]
Ah, this is already possible, just under documented 😞  There are also a configuration for cookie domain, for what it's worth.

The configuration looks like this:
```ini
[couch_httpd_auth]
allow_persistent_cookies = true
timeout = 600
cookie_domain = .asgard.org
```
and this gives:
```bash
$ curl -v http://127.0.0.1:15984/_session -H 'Content-Type: application/json' -d '{"name":"odin","password":"asgard"}'
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 15984 (#0)
> POST /_session HTTP/1.1
...
< Set-Cookie: AuthSession=b2Rpbjo1QjkyODYzQzpzHjxQ0b7aKwit3CnK7cCJ3Gt8PA; Version=1; Expires=Fri, 07-Sep-2018 14:17:56 GMT; Max-Age=600; Domain=.asgard.org; Path=/; HttpOnly
```

**Comment by flimzy** [comment]
Oh thanks, I'll see about creating a PR to highlight this in the documentation.

**Comment by nickva** [comment]
We switched allow_persistent to true by default to help with session refresh issues in the replicator:

https://github.com/apache/couchdb/pull/1619/files#diff-f51079d3c7e7925e0f9684f81e5785c7R214

So expiry and max-age should be returned now in the cookie
