### ISSUE TITLE
Request to re-adopt the right terms for master-slave relation between nodes

### ISSUE THREAD

**Issue by nextime** [apache/couchdb#1599]
The lobby of americans biggots that are asking everywhere to change nomenclature from master-slave to something else wrongly assume to have the right to appropriate the terms and linking it only with the background they choose, in this case the slavery in the american culture.

But in other context those names aren't offensive at all, and they have no linking to that history. In the BDSM community the master-slave terms are used to indicate a consensual sexual behaviour in relationships between adult people, and we, masters and slaves of the BDSM community, find highly offensive to be associated with the american history of slavery.

In the same manner, in the software history master-slave has ever been used in a different meaning, a non-offensive one, and censuring that term only to follow a biggot american sub-culture is highly offensive for everyone that isn't in that culture and feel the appropriation of the terms like an abuse by them.

**Comment by garrensmith** [comment]
No!
