### ISSUE TITLE
I have a problem with a view

### ISSUE THREAD

**Issue by strelok1010** [apache/couchdb#1618]
I don't speak english,  but I will try. 

I have a database "db_logs_prices" with 455 documents and 227.7 MB, too it have a view with this estucture (and reduce is "sum"):
```
function (doc) {
    emit(doc._id, 1);
}
```
**¿When is the problem?** 
my server freezes because the view consumes all the RAM, it returns an error that says
`{"error":"timeout","reason":"The request could not be processed in a reasonable amount of time."}`
The ID format is: 2018-12-24_10-12

The same view in other databases with much more documents works perfectly well

**Comment by wohali** [comment]
Remove your reduce of `sum` and make it blank. CouchDB cannot sum values of the form `2018-12-24_10-12`.

**Comment by wohali** [comment]
What happens if you remove the `sum` from your reduce?

**Comment by strelok1010** [comment]
I can try, but ¿It's "sum" necessary for the result that I want? I want count all documents from this data base.

**Comment by wohali** [comment]
@strelok1010 Then try replacing `sum` with `count` for me? It's just a test. Also test without any reduce at all. Trying to narrow down the problem.

**Comment by strelok1010** [comment]
I will try, after tell you :)

**Comment by strelok1010** [comment]
I have changed the reduction from "_sum" to "_count" and the problem persists.
I have also tried to eliminate the reduction, why?

**Comment by big-r81** [comment]
Closing this old ticket. Please reopen if your problem exists with the newest version of CouchDB.
