### ISSUE TITLE
Black matter in shard files

### ISSUE THREAD

**Issue by adrienverge** [apache/couchdb#1621]
Hello,

Yesterday we did a post-mortem examination of a server (in a 3-node cluster) that crashed because its disk was full. It has CouchDB 2.1.2 with little data (1 GB), but `/var/lib/couchdb/` weighted 26 GB.

It looks like there is black matter in shard files.

For example, we have a small database `demo` (19 documents, it's never updated, but often replicated to create clone databases). When looking at one of its shard files, it's incredibly big:

    1,4M /var/lib/couchdb/shards/00000000-1fffffff/demo.1520354435.couch

As its metadata says, its **uncompressed data size is 23 kB**, but its **"active" size is 11311 kB**!

```
$ curl localhost:5984/demo
{
  "db_name": "demo",
  "update_seq": "79-g1AAAAKjeJ...",
  "sizes": {
    "file": 11679510,
    "external": 23705,
    "active": 11311270
  },
  "other": {
    "data_size": 23705
  },
  "disk_size": 11679510,
  "data_size": 11311270,
  ...
}
```
([full-output.json](https://github.com/apache/couchdb/files/2410386/full-output.json.txt))

We've tried compacting it, and also reduced `_rev_limits`, it had no effect.  Also, when replicating this database to a new one, the new size is normal:

    8,2K /var/lib/couchdb/shards/00000000-1fffffff/demo-copy.1537540293.couch

It looks like this extra size comes from many `_local` documents (there are 17995 in this database -- but we created none).

Example local files:
```json
{
  "id": "_local/0098b2317762223afc9a21b9e9ed894b",
  "key": "_local/0098b2317762223afc9a21b9e9ed894b",
  "value": {
    "rev": "0-1"
  },
  "doc": {
    "session_id": "4549feee1de3724118b38b56ac47acbe",
    "source_last_seq": "19-g1AAAASteJzN0lFKxDAQBuCwVXRPsV4gJUnTtAXBvY...",
    "replication_id_version": 4,
    "history": [
      {
        "session_id": "4549feee1de3724118b38b56ac47acbe",
        "start_time": "Wed, 27 Jun 2018 06:56:43 GMT",
        "end_time": "Wed, 27 Jun 2018 08:56:47 GMT",
        "start_last_seq": 0,
        "end_last_seq": "19-g1AAAASteJzN0lFKxDAQBuCwVXRPsV4gJUnTtAXBv...",
        "recorded_seq": "19-g1AAAASteJzN0lFKxDAQBuCwVXRPsV4gJUnTtAXBv...",
        "missing_checked": 19,
        "missing_found": 19,
        "docs_read": 19,
        "docs_written": 19,
        "doc_write_failures": 0
      }
    ]
  }
}
```
or:
```json
{
  "id": "_local/shard-sync-5WNtkwE5tM3B2A8XgrARtA-xrMMaaBJQHXoLx6HrvkN9w",
  "key": "_local/shard-sync-5WNtkwE5tM3B2A8XgrARtA-xrMMaaBJQHXoLx6HrvkN9w",
  "value": {
    "rev": "0-1"
  },
  "doc": {
    "seq": 9,
    "target_uuid": "e41c58518830b41c2c908ce3d68dedb3",
    "history": {
      "couchdb@cluster-node-1.com": [
        {
          "target_node": "couchdb@cluster-node-2.com",
          "target_uuid": "e41c58518830b41c2c908ce3d68dedb3",
          "target_seq": 11,
          "source_node": "couchdb@cluster-node-3.com",
          "source_uuid": "33f52231d93c3f99a2b683de7de4d111",
          "source_seq": 9,
          "timestamp": "2018-09-24T07:59:03.786497Z"
        },
        {
          "target_node": "couchdb@cluster-node-2.com",
          "target_uuid": "e41c58518830b41c2c908ce3d68dedb3",
          "target_seq": 8,
          "source_node": "couchdb@cluster-node-3.com",
          "source_uuid": "33f52231d93c3f99a2b683de7de4d111",
          "source_seq": 3,
          "timestamp": "2018-06-02T05:10:44.108378Z"
        }
      ]
    }
  }
}
```
(Note that timestamps are more than 3 months old.)

- Are these `_local` files the cause of the extra weight (× 26 compared to a fresh replicated server with the same contents)?
- Are these `_local` files needed? Is it normal that they stay on disk for months?
- How to prevent creation of this black matter?

Thanks in advance for helping us debugging this strange behavior. I'd be happy to provide more info if needed.

**Comment by nickva** [comment]
@adrienverge 

Thanks for your report. A lot of local documents could increase the file size like that.

Do you know which type you have more of _local/<id> or _local/shard-sync-<id>?

If it is the first kind (_local/<id>), then those are the result of using the database as a replication endpoint.  CouchDB writes _local checkpoint documents on the source and target, so next time it restarts the replication between source and target it will resume from changes feed from the checkpointed value and not from the very beginning. 

However that means that each {source, target} pair (along with a few other thing like if there a filter) generates a _local document. If say source is used for a public demo, then there could be a very large number of {source, target} pairs generated and thus a large number of _local/<id> documents present. 

There is an option to avoid this http://docs.couchdb.org/en/stable/config/replicator.html#replicator/use_checkpoints and it could help in these cases. Read additional info and the warning regarding using that option, but it sounds like it might help your case.

If you see more of the second kind (_local/shard-sync-<id>), then it is hard to say without more debugging why that's happening.

**Comment by wohali** [comment]
Also, just to confirm: have you deleted any documents in this database? What is the full output of `GET /{dbname}/`? So-called "document tombstones" might be taking up a lot of space, too; depending on how the documents were deleted, they may actually still contain the prior document data.

**Comment by adrienverge** [comment]
Hi @nickva @wohali, thank you for answering.

@wohali what you ask is in my first post, see `curl localhost:5984/demo` and `"doc_del_count": 0`. No documents were deleted.

@nickva thanks a lot for the detailed explanation: it is hard to find technical info on where do these strange files come from. In our servers:
- 79% (around 4000000 docs) are like `_local/002b9f5977bdb93052d1134208d7458d`,
- 20% (around 1000000 docs) are like `_local/shard-sync-0hbIroIo7GAdeFZTS--0Fw-JTBmB5z2AIBLtN3dFM_ryQ`,
- 0.8% (around 40000 docs) are like `_local/Jqbpr4ZvrEGCtSLLtWcpHw==`.

The last kind of docs come from [PouchDB](https://github.com/pouchdb/pouchdb).
For the other types, can we safely delete them on a daily basis? Is there a risk of breaking CouchDB by "corrupting" ongoing replications?

**Comment by nickva** [comment]
@adrienverge 

1. If the replications are finished and not expected to be resumed anymore or if you don't mind them reprocessing the _changes feed when they are resumed, you can delete the `_local/<id>` ones.

2. It's a bit concerning that there are 1M _local/shard-sync-<id> documents. Those are created by the internal replicator which synchronizes shard copies in a cluster. Say a document write with w=2 updates the shard copy on node1 and node2 only. Then internal replicator will notice and eventually replicate the update to node3 as well. 

The reason you can't delete them is because internal replication works on individual shards and so deleting those via the clustered interface won't always work. You can still delete them with via the local port `:5986/shards.../`. But it would be good to figure out why there are so many to start with.

Wonder if any of these happen in your case:

 * Cluster membership changes so that nodes are added and removed constantly

 * Cluster node names change?

* Any individual shard manipulation taking place, say another tool opens, creates, encrypts, moves shard files around? This might include operating on shards via the local (:5986) interface

 * Rapid creation / deletion of databases?

(cc: @davisp What do you think ^, this is an odd occurrence. What could cause so many shard sync checkpoints)

**Comment by adrienverge** [comment]
Hi @nickva, thanks for following up.

To answer your questions:
\- Cluster don't change (always the same 3 nodes); nodes names (or IPs) don't change (more generally, we don't touch `vm.args` nor `/_membership` nor `/_nodes` nor `:5986` at all.
\- No other tool or process that touch `/var/lib/couchdb` (except us when debugging, but only rarely and in read-only: `du`, `df`, `scp`...)
\- Databases are not rapidly created (around 250 new DBs per day), and never deleted.

**Here is more info on the shard-sync issue:**
We've set up a new cluster, and replicated from the (dying) old one. Three nodes, `q=8`, `n=3`.
For a database chosen at random, there are **32** `_local/shard-sync` docs on first node 
([download them all here](https://github.com/apache/couchdb/files/2423565/local_docs.json.txt)), among which some look redundant (same `source_node` and `target_node`, but different UUIDs). Example:

```json
{
  "_id": "_local/shard-sync-1MHFZMU82CR6nTRw6IB5ig-MAqWsRU1KdFyVAmQyHUkqg",
  "seq": 68,
  "target_uuid": "147ecd8ddf1ba86c3e8d7117587141b1",
  "history": {
    "couchdb@node1.com": [
      {
        "target_node": "couchdb@node2.com",
        "target_uuid": "147ecd8ddf1ba86c3e8d7117587141b1",
        "target_seq": 70,
        "source_node": "couchdb@node1.com",
        "source_uuid": "4ceab4f79e99ef3929a3f3e7bb9ea8f5",
        "source_seq": 68,
        "timestamp": "2018-09-27T07:34:01.554723Z"
      }
    ]
  }
},
{
  "_id": "_local/shard-sync-6Fr1fwkrRyD7NMmRmXXCmQ-E-HElyKWVluvtMH9BuGyNA",
  "seq": 73,
  "target_uuid": "2d5e533605c004d673c338e796130b9d",
  "history": {
    "couchdb@node1.com": [
      {
        "target_node": "couchdb@node2.com",
        "target_uuid": "2d5e533605c004d673c338e796130b9d",
        "target_seq": 75,
        "source_node": "couchdb@node1.com",
        "source_uuid": "7c44291538e9f88de564b13642122f12",
        "source_seq": 73,
        "timestamp": "2018-09-27T07:34:00.978796Z"
      }
    ]
  }
}
```

Is it normal that there are 32 of them? Is it normal that some look very similar?

**Comment by nickva** [comment]
32 seems normal, I would have expected maybe 48 ( 3 pairs, that is 6 * 8 shards = 48) but I didn't look too much into the internal replication algorithm. 

But overall that's much's less than the 1000000 as I think I misunderstood that it was that many shard-sync checkpoints in a single db (!) from the pervious discussion.

Don't delete _local/shard-sync-* docs, as that will mess up with the internal replicator between cluster nodes.

But if you there are a lot of _local/<id> ones, you can delete those if the replications have finished and don't expect those to be resumed (or if they resume they'd reprocess their changes feed). And use_checkpoints = false option might be something useful for your use case (it would avoid modifying that source db with _local/<id> for each replication from it).

To reduce the size other options could be to try a better compression algorithm than the default snappy one (say deflate_6).

**Comment by adrienverge** [comment]
Hi @nickva,

I apologize for the misunderstanding, I meant 1000000 docs for the whole node ("in our servers"). I'm glad to hear 32-48 `_local/shard-sync` docs are normal.

We started using `use_checkpoints = false` and deleted all other local docs.

Unfortunately CouchDB disk usage still keeps growing (by multiple dozens of GB, while the size after a fresh restoration is 5 GB) even on a cluster we don't touch (no connection at all). We are still investigating it, but it may be because:
- shard files (`db.1520354435.couch`) constantly keep growing (by ~kB), even if there are no requests done on them,
- compaction doesn't seem to happen on all shard files. This could be related to `min_file_size` or #1579 or #1383 or #1097.

So in the meantime I'll close this issue. Once again, thank you for your detailed explanations that help us understand and debug this problem further!

PS: By the way, we're stuck on 2.1.2 (because 2.2 has #1550, will be fixed in 2.3), but 2.2 has many performance improvements. It would be great to have a 2.2.1 (with the fix) while waiting for 2.3! :)

**Comment by wohali** [comment]
@adrienverge The list of issues for 2.3.0 to be released is very small. We expect release within a month or so, hopefully sooner. I don't think a 2.2.1 is coming, sorry about that. I am also sorry that you can't use the workaround in 2.2.0 to restore the prior replicator functionality - any reason why not?

**Comment by wohali** [comment]
Here's the 2.3.0 issue list. https://github.com/apache/couchdb/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.3.0

**Comment by H--o-l** [comment]
Hi !

I'm working with @adrienverge and I continue to investigate the "black matter" issue.

As @adrienverge said, shard files (`db.1520354435.couch`) constantly keep growing (by several kB per day), even though there are no requests done to them.
This is a problem because we have *many* small, untouched databases.

Compaction helps to free space on a regular basis, but it takes a bunch of cpu time.
So we would like to understand what is happening in our `.couch` files.

In a node of our cluster we monitored output of `strings /var/lib/couchd/shards/xxx/db.1520354435.couch`.
In one night, it had ~800 new rows like this one:
```
kv_nodel
?_local/shard-sync-VNaRvSQnMLpUSzV8iZvcow-IOHL5NIdglwNQCT0DL_V0Ah
seqa}	],
target_uuid
 cef8fe0a2eac1f0f7af0d5e0c56fbbd8	7
historyh
@;couchdb@node1l
142-216
-$!7
source
x2a65d174d772861e4cd085e9e347729-
$	timestamp!7|
2018-10-02T22:21:13.181557Zjjjj	~Jd
TgKo_QqiB9XPEFr08HvUC2Q
98-214
M/Uf|e0dc03c296d3847efd92e964053e5f1b	7
P15:23:01.533200Zjjjjj
kp_nodel
?_local/shard-sync-IOHL5NIdglwNQCT0DL_V0A-gKo_QqiB9XPEFr08HvUC2Qh
-IOHLFj
	db_headera
	size_infob
nilb
 cef8fe0a2eac1f0f7af0d5e0c56fbbd8l
<couchdb@node2a
```

As we have ~34k dbs, multiplied by 8 shards by node, it quickly sum up and takes a lot of space and a lot of compaction time, which sometimes ends up saturating our disks and CPU.

Can you advise us ?

**Comment by wohali** [comment]
@H--o-l that's not useful for us.

Can you look instead at: `https://your-host-name:5984/dbname/_local_docs`? You should be able to diff this, then pull the specific documents out for us to look at.

**Comment by H--o-l** [comment]
@wohali Thanks for looking at it.

For the example above, those are documents that seems to be impacted:
```json
{
  "id": "_local/shard-sync-VNaRvSQnMLpUSzV8iZvcow-IOHL5NIdglwNQCT0DL_V0A",
  "key": "_local/shard-sync-VNaRvSQnMLpUSzV8iZvcow-IOHL5NIdglwNQCT0DL_V0A",
  "value": {
    "rev": "0-1"
  },
  "doc": {
    "seq": 125,
    "target_uuid": "cef8fe0a2eac1f0f7af0d5e0c56fbbd8",
    "history": {
      "couchdb@node1": [
        {
          "target_node": "couchdb@node2",
          "target_uuid": "cef8fe0a2eac1f0f7af0d5e0c56fbbd8",
          "target_seq": 127,
          "source_node": "couchdb@node1",
          "source_uuid": "2a65d174d772861e4cd085e9e3477298",
          "source_seq": 125,
          "timestamp": "2018-10-02T22:21:13.181557Z"
        }
      ]
    }
  }
}
```
```json
{
  "id": "_local/shard-sync-IOHL5NIdglwNQCT0DL_V0A-gKo_QqiB9XPEFr08HvUC2Q",
  "key": "_local/shard-sync-IOHL5NIdglwNQCT0DL_V0A-gKo_QqiB9XPEFr08HvUC2Q",
  "value": {
    "rev": "0-1"
  },
  "doc": {
    "seq": 125,
    "target_uuid": "e0dc03c296d3847efd92e964053e5f1b",
    "history": {
      "couchdb@node2": [
        {
          "target_node": "couchdb@node3",
          "target_uuid": "e0dc03c296d3847efd92e964053e5f1b",
          "target_seq": 127,
          "source_node": "couchdb@node2",
          "source_uuid": "cef8fe0a2eac1f0f7af0d5e0c56fbbd8",
          "source_seq": 125,
          "timestamp": "2018-10-02T15:23:00.382192Z"
        }
      ]
    }
  }
}
```
Sadly I can't given you a diff before/after, thoses are the documents in there actual state.

By the way, it's seems that restarting couchdb service on our three nodes have a impact on the "black matter", as it increase it (we observe from 8Go of shards to 12Go of shards 1h after service restart, and nothing else happening on the machines).

Does that seems possible ?

Thanks again for your help !
