### ISSUE TITLE
Windows 7 - CouchDB service does not startup correctly

### ISSUE THREAD

**Issue by kipkuch** [apache/couchdb#1623]
I am installing the latest version 2.2.0 of couch db on my windows 7 laptop. After installation, I'm unable to startup Couchdb.

## Expected Behavior
CouchDB to startup correctly after installation.

## Current Behavior
After installation, service starts up, but I'm unable to hit the http://localhost:5984 URL.

When I check the log files (couch.log), I see the following error:

`[info] 2018-09-25T13:22:21.315000Z couchdb@localhost <0.7.0> -------- Application couch_log started on node couchdb@localhost
[info] 2018-09-25T13:22:21.334000Z couchdb@localhost <0.7.0> -------- Application folsom started on node couchdb@localhost
[info] 2018-09-25T13:22:21.373000Z couchdb@localhost <0.7.0> -------- Application couch_stats started on node couchdb@localhost
[info] 2018-09-25T13:22:21.373000Z couchdb@localhost <0.7.0> -------- Application khash started on node couchdb@localhost
[info] 2018-09-25T13:22:21.389000Z couchdb@localhost <0.7.0> -------- Application couch_event started on node couchdb@localhost
[info] 2018-09-25T13:22:21.405000Z couchdb@localhost <0.7.0> -------- Application ibrowse started on node couchdb@localhost
[info] 2018-09-25T13:22:21.405000Z couchdb@localhost <0.7.0> -------- Application ioq started on node couchdb@localhost
[info] 2018-09-25T13:22:21.405000Z couchdb@localhost <0.7.0> -------- Application mochiweb started on node couchdb@localhost
[info] 2018-09-25T13:22:21.420000Z couchdb@localhost <0.198.0> -------- Apache CouchDB 2.1.2 is starting.

[info] 2018-09-25T13:22:21.420000Z couchdb@localhost <0.199.0> -------- Starting couch_sup
[error] 2018-09-25T13:22:21.420000Z couchdb@localhost <0.202.0> -------- CRASH REPORT Process  (<0.202.0>) with 0 neighbors exited with reason: "The specified module could not be found." at gen_server:init_it/6(line:344) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_drv,init,['Argument__1']}, ancestors: [couch_primary_services,couch_sup,<0.198.0>], messages: [], links: [<0.201.0>], dictionary: [], trap_exit: false, status: running, heap_size: 376, stack_size: 27, reductions: 125
[error] 2018-09-25T13:22:21.420000Z couchdb@localhost <0.198.0> -------- Error starting Apache CouchDB:

    {error,{shutdown,{failed_to_start_child,couch_primary_services,{shutdown,{failed_to_start_child,collation_driver,"The specified module could not be found."}}}}}

[error] 2018-09-25T13:22:21.436000Z couchdb@localhost <0.201.0> -------- Supervisor couch_primary_services had child collation_driver started with couch_drv:start_link() at undefined exit with reason "The specified module could not be found." in context start_error
[error] 2018-09-25T13:22:21.436000Z couchdb@localhost <0.199.0> -------- Supervisor couch_sup had child couch_primary_services started with couch_primary_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,collation_driver,"The specified module could not be found."}} in context start_error
[error] 2018-09-25T13:22:21.436000Z couchdb@localhost <0.197.0> -------- CRASH REPORT Process  (<0.197.0>) with 0 neighbors exited with reason: {{shutdown,{failed_to_start_child,couch_primary_services,{shutdown,{failed_to_start_child,collation_driver,"The specified module could not be found."}}}},{couch_app,start,[normal,[]]}} at application_master:init/4(line:134) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {application_master,init,['Argument__1','Argument__2',...]}, ancestors: [<0.196.0>], messages: [{'EXIT',<0.198.0>,normal}], links: [<0.196.0>,<0.7.0>], dictionary: [], trap_exit: true, status: running, heap_size: 610, stack_size: 27, reductions: 139
[info] 2018-09-25T13:22:21.436000Z couchdb@localhost <0.7.0> -------- Application couch exited with reason: {{shutdown,{failed_to_start_child,couch_primary_services,{shutdown,{failed_to_start_child,collation_driver,"The specified module could not be found."}}}},{couch_app,start,[normal,[]]}}`

## My Environment
* Version used: CouchDB 2.2.0 x64 Windows
* Operating System and version: Windows 7 Professional SP1

**Comment by wohali** [comment]
@kipkuch Hi there, I can't reproduce this on my Win 7 Professional SP1 laptop.

Did you previously have another version of CouchDB installed first? Did you completely remove that version if so?

Did you install CouchDB to a path **without** spaces, such as `C:\CouchDB`? The installer warns that CouchDB won't work right if you install to a path with spaces such as `C:\Program Files\CouchDB`.
