### ISSUE TITLE
Couchdb build issue with SLES 15

### ISSUE THREAD

**Issue by srajmane** [apache/couchdb#1626]
## Context
Trying to build Couchdb v2.2.0 from source on SLES 15.
One of the dependency to build couchdb is libmozjs185 which is not found on SLES 15. So tried to build it from source using steps with **GCC version 7.3.1** : 

> wget http://ftp.mozilla.org/pub/mozilla.org/js/js185-1.0.0.tar.gz
> tar zxf js185-1.0.0.tar.gz 
> cd js-1.8.5/js/src
> autoconf2.13
> mkdir -p build_OPT.OBJ
> cd build_OPT.OBJ
> ../configure --prefix=/usr
>  make

However, make is failing with

> ../jsapi.cpp: In function 'JSIdArray* JS_Enumerate(JSContext*, JSObject*)':
> ../jsapi.cpp:3988:16: error: cannot convert 'bool' to 'JSIdArray*' in return
>          return false;
>                 ^~~~~
> ../config/rules.mk:1475: recipe for target 'jsapi.o' failed

Any suggestions on how to resolve the failure? 
## Your Environment

* Version used: 2.2.0
* Operating System and version (desktop or mobile): SLES 15

**Comment by wohali** [comment]
This isn't a CouchDB bug, but we can offer some support anyway.

CouchDB for RHEL/CentOS and Debian/Ubuntu builds its own couchjs package. You can try applying all of the patches we apply for that.

See: https://github.com/apache/couchdb-pkg/tree/master/js

specifically the `README` file in that directory + the patches as well.

Let us know how you get on!

**Comment by virtimus** [comment]
Managed to build couchDB on Ubuntu 18.04 (mint):

sudo apt-get --no-install-recommends -y install build-essential pkg-config erlang erlang-reltool libicu-dev  python3 python3-sphinx
sudo apt-get install devscripts debhelper dh-virtualenv  pkg-kde-tools
sudo npm i -g npm@latest
pip3 install sphinx_rtd_theme

cd /src && git clone https://github.com/apache/couchdb-pkg
cd couchdb-pkg && make couch-js-debs PLATFORM=$(lsb_release -cs)
sudo apt-get install /src/couchdb-pkg/js/couch-libmozjs185-1.0_1.8.5-1.0.0+couch-2~tara_amd64.deb /src/couchdb-pkg/js/couch-libmozjs185-dev_1.8.5-1.0.0+couch-2~tara_amd64.deb

cd /src && git clone https://github.com/apache/couchdb
cd couchdb && ./configure && make

cd /src/couchdb/src/docs && make

cd /src/couchdb && make install
