### ISSUE TITLE
Can couchdb stop responding to requests coming to local couch db while replicating to cloud couch

### ISSUE THREAD

**Issue by dinanjana** [apache/couchdb#1645]
There are recent events I have observed that couchdb looks like stalling requests if the initial replication process is failing after a restart to couch db node. Can the replication and requests to local couch db have a dependency such that ? The setup looks like where there are several nodes and all except one has push and pull links created towards to a one node in the master slave fashion. Couchdb version: 1.6
## Expected Behavior

Requests to couchdb node not getting timed out

## Current Behavior

Requests to couchdb node  getting timed out

## Your Environment

Ubuntu 12
Couchdb 1.6.1

BTW, this is the same guy posted it in here 
https://stackoverflow.com/questions/52696868/can-couchdb-stop-responding-to-requests-coming-to-local-couch-db-while-replicati

**Comment by wohali** [comment]
Sorry, the CouchDB team no longer support CouchDB 1.x. If you can reproduce the problem with CouchDB 2.2.0, we'll have a look.
