### ISSUE TITLE
Result contains "offset": null instead of "offset": 0

### ISSUE THREAD

**Issue by huxi** [apache/couchdb#1648]
A query with a `keys` argument, `_all_docs?include_docs=true&keys=["key"]`, suddenly returns `"offset": null` instead of `"offset": 0`.

Performing the same query without the `keys` argument, i.e. just `_all_docs?include_docs=true` returns a correct offset of `0`.

## Expected Behavior

```json
{
  "total_rows": 64,
  "offset": 0,
  "rows": [
    {
      // the result rows
    }
  ]
}
```

## Current Behavior

```json
{
  "total_rows": 64,
  "offset": null,
  "rows": [
    {
      // the result rows
    }
  ]
}
```

## Context

The issue started showing up after upgrading a CouchDB cluster from 2.1.0 to 2.2.0.

It causes a `JsonParseException` in [QueryResultParser](https://github.com/helun/Ektorp/blob/master/org.ektorp/src/main/java/org/ektorp/impl/QueryResultParser.java#L75) of [Ektorp](https://github.com/helun/Ektorp).

## Your Environment

* Version used: 2.2.0

**Comment by pablovp86** [comment]
Same problem here. Upgraded from 2.1.2 to 2.2.0 (Ubuntu 18.04).

**Comment by wohali** [comment]
The issue stems from : https://github.com/apache/couchdb/pull/1085
and specifically : https://github.com/apache/couchdb/pull/1085/files#diff-9d6b535641fc74e993a6c0a246313619R102

@jiangphcn added the {offset, null} there which breaks the follow up bit where it defaults to 0 if the key isn't present.

It's a meaningless value either way - but it did change. We disagree with the Ektorp author; we believe it should be possible to disable asserting JSON types in that client.

@jiangphcn are you able to look at this one? Perhaps we should remove 'offset' from view response in all cases?

**Comment by davisp** [comment]
https://github.com/apache/couchdb/blob/99825820d12d992c30caad007de3942761bf457e/src/fabric/src/fabric_view_all_docs.erl#L100

On that line we should just remove `{offset, null}` to get back to the previous behavior.

**Comment by davisp** [comment]
@wohali @jiangphcn For now i'd just revert it the 0 behavior and delay making things different until a major release.

**Comment by pablovp86** [comment]
Any prediction of when this problem will solved?

**Comment by jiangphcn** [comment]
Sorry for lateness. I am working on this. The `offset:null` part can be removed from codes. However,  I noticed that there will be NO offset with 0 returned from response.

```
curl -X GET 'localhost:15984/db01/_all_docs?include_docs=true&keys=["point2"]&update_seq=true' -u foo:bar -g|jq .
 
{
  "total_rows": 5,
  "update_seq": null,
  "rows": [
    {
      "id": "point2",
      "key": "point2",
      "value": {
        "rev": "1-d942f0ce01647aa0f46518b213b5628e"
      },
      "doc": {
        "_id": "point2",
        "_rev": "1-d942f0ce01647aa0f46518b213b5628e",
        "type": "Feature",
        "geometry": {
          "type": "Point",
          "coordinates": [
            0.2,
            0.2
          ]
        }
      }
    }
  ]
}
```

The same for POST method:
```
curl -u foo:bar -X POST -H "Content-Type: application/json" http://127.0.0.1:15984/db01/_all_docs --data "{\"include_docs\":\"true\",\"keys\":[\"point2\"]}"|jq .
{
  "total_rows": 5,
  "rows": [
    {
      "id": "point2",
      "key": "point2",
      "value": {
        "rev": "1-d942f0ce01647aa0f46518b213b5628e"
      }
    }
  ]
}
```

I will proceed to issue PR if there is objection.

**Comment by melnykstepan** [comment]
> Sorry for lateness. I am working on this. The `offset:null` part can be removed from codes. However, I noticed that there will be NO offset with 0 returned from response.
> 
> ```
> curl -X GET 'localhost:15984/db01/_all_docs?include_docs=true&keys=["point2"]&update_seq=true' -u foo:bar -g|jq .
>  
> {
>   "total_rows": 5,
>   "update_seq": null,
>   "rows": [
>     {
>       "id": "point2",
>       "key": "point2",
>       "value": {
>         "rev": "1-d942f0ce01647aa0f46518b213b5628e"
>       },
>       "doc": {
>         "_id": "point2",
>         "_rev": "1-d942f0ce01647aa0f46518b213b5628e",
>         "type": "Feature",
>         "geometry": {
>           "type": "Point",
>           "coordinates": [
>             0.2,
>             0.2
>           ]
>         }
>       }
>     }
>   ]
> }
> ```
> The same for POST method:
> 
> ```
> curl -u foo:bar -X POST -H "Content-Type: application/json" http://127.0.0.1:15984/db01/_all_docs --data "{\"include_docs\":\"true\",\"keys\":[\"point2\"]}"|jq .
> {
>   "total_rows": 5,
>   "rows": [
>     {
>       "id": "point2",
>       "key": "point2",
>       "value": {
>         "rev": "1-d942f0ce01647aa0f46518b213b5628e"
>       }
>     }
>   ]
> }
> ```
> I will proceed to issue PR if there is objection.
Do you have any estimation, when it will be ready?

**Comment by jiangphcn** [comment]
If there is no objection, the PR will be issued in coming day.

**Comment by nickva** [comment]
Offset is now `null` in 3.x and there hasn't been any discussion or incentive to change it. Closing the issue for now. Please re-open if we plan on addressing this again.
