### ISSUE TITLE
unhelpful error behaviour when when sending a wrong request body to _bulk_get

### ISSUE THREAD

**Issue by emlaver** [apache/couchdb#1651]
## Expected Behavior

When executing a POST request against the `_bulk_get` endpoint, I expect a valid JSON response.
For example, if I make a request against `_bulk_get` with invalid data in the request body I should get back a 400 response with `invalid UTF-8 JSON` reason.

## Current Behavior

When executing the request below, I get back a partial JSON response with no error message.
```
http:/localhost:5984/_users/_bulk_get' -H content-type:application/json -d '{"docs":["doc-1"]}'
```

The `docs` value in the request body is invalid.  It needs to be updated to `[{"id":"doc-1"}]`.

## Steps to Reproduce (for bugs)

1. Create a database
2. Create a document in the db
3. POST request using ` _bulk_get` against the db with invalid request data
e.g. `curl http:/localhost:5984/_users/_bulk_get'  -H content-type:application/json -d '{"docs":["doc-1"]}'`
4. Get back partial JSON response
e.g. `{"results": [%`

Verbose request details:
```
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 5984 (#0)
* Server auth using Basic with user 'admin'
> POST /db/_bulk_get HTTP/1.1
> Host: localhost:5984
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type:application/json
> Content-Length: 18
> 
* upload completely sent off: 18 out of 18 bytes
< HTTP/1.1 200 OK
< Cache-Control: must-revalidate
< Content-Type: application/json
< Date: Thu, 11 Oct 2018 16:42:07 GMT
< Server: CouchDB/2.2.0 (Erlang OTP/19)
< Transfer-Encoding: chunked
< X-Couch-Request-ID: 6afa032a5e
< X-CouchDB-Body-Time: 0
< 
* Illegal or missing hexadecimal sequence in chunked-encoding
* stopped the pause stream!
* Closing connection 0
curl: (56) Illegal or missing hexadecimal sequence in chunked-encoding
{"results": 
```

## Context

It's not clear that my request body data was invalid.  It would be ideal to get back some error message letting me know that the data is invalid.
## Your Environment

* Version used: 2.2.0
* Browser Name and version: NA
* Operating System and version (desktop or mobile): Mac OS 10.14
* Link to your project: NA
* Curl version: `curl 7.54.0 (x86_64-apple-darwin18.0)`

**Comment by emlaver** [comment]
@rnewson FYI

**Comment by ketan86** [comment]
Any update on this issue ? I am hitting the same problem. The referenced issue can't backup _users database #253 does not help.

**Comment by rnewson** [comment]
The documentation for _bulk_get is here: https://docs.couchdb.org/en/stable/api/database/bulk-api.html#db-bulk-get

The doc body is not of format {"docs":["doc-1"]}. 

Admittedly the error handling is crappy, but if you supply what the docs say you should send, it works;

{"docs":[{"id":"doc-1"}]}

**Comment by ketan86** [comment]
Thanks

**Comment by nickva** [comment]
This is now fixed:

```
% curl http://adm:pass@localhost:15984/_users/_bulk_get -H content-type:application/json -d '{"docs":["doc-1"]}'
{"results":[{"id":null,"docs":[{"error":{"rev":null,"reason":"document must be a JSON object","id":null,"error":"bad_request"}}]}]}
```
