### ISSUE TITLE
Slow reads when view indexes generating

### ISSUE THREAD

**Issue by jasons316** [apache/couchdb#1653]
I don't know if this is the right place to ask this, but we are currently getting issues when data is being inserted, or view indexes are being built. During this process, reading data from CouchDB becomes slow, often taking several seconds to return data, and sometimes even timing out.

We have an n3q8 cluster, running v2.1.1. Each node is running CentOS 7.2 and has 16 CPU cores (32 threads), 128GB RAM and 1TB of SSD storage.

We mostly run the default configuration, but have changed the following parameters:
vm.args
+A 64

local.ini
max_dbs_open = 5000
os_process_limit = 2000
os_process_soft_limit = 1000

We have also increased the OS and couchdb user ulimit to 65535.

I don't know if there is an issue with our configuration, but I would like to be able to read records from the database/views at the same time that views are being indexed with minimal delay. Is there anyway to prioritise read traffic, or reserve processing power for this purpose?

Any help would be appreciated.

Thanks.

Edit:
I should also point out that at no point during the indexing process, or at all, have the CPU, ram or disk iops been persistently maxed on the servers, which leads me to believe this is purely a soft-limit issue rather than hardware.

**Comment by janl** [comment]
How are you measuring request time? And what numbers are you getting with and without indexing/inserting?

**Comment by jasons316** [comment]
We haven't run any metrics on request time as yet. We are purely going off load times for our front end website. We run an ecommerce site, and the product pages pull the product data directly from CouchDB. When indexing or data insertion is occurring, the pages load very slowly. When there are no active tasks in CouchDB, they load near instantly.

The problem is highlighted moreso when running a search on the site. Searches return multiple products, so pulling the data for these takes a long time when CouchDB is indexing.

Happy to run some metrics if anyone can advise the best way to do this.

Thanks.

**Comment by jasons316** [comment]
We are still getting issues like the above.

Using Apache Benchmark, we can call a single document (10000 iterations, 100 concurrent), and we get over 900 requests/sec when the cluster is not indexing. This drops to around 400 /sec if indexing, and around 150 /sec if indexing and data is being written/updated simultaneously.

As mentioned previously, this prevents read requests responding in a timely manner.

Does anybody have any ideas?

Thanks,
Jason

**Comment by wohali** [comment]
@jasons316 Try limiting the number of concurrent indexing processes to be (NCPUS - 1), aka 31. Be sure to account for shards - use the output of `/_active_tasks` to ensure you're not running more than 31 indexing jobs per node.

Does it help with your benchmark?

**Comment by jasons316** [comment]
Thanks for the response.

I am unsure of how to limit the number of indexing processes. Is this in the config files?

Thanks,
Jason

**Comment by wohali** [comment]
@jasons316 remove:

```
os_process_limit = 2000
os_process_soft_limit = 1000
```

from your .ini file. This will restore the default value of 100. This is a good start.

When generating a JavaScript index, CouchDB uses one external `couchjs` process per shard. For the default configuration, that's 8 processes per design document per database. Your increased limit means that up to (2000 / 8) = 250 indexes might be building at once, using 2000 `couchjs` processes. It should be clear that a machine with 16 cores/32 threads will have a hard time juggling 2000 active processes at once, leading to lots of context switches and reduced performance.

**Comment by wohali** [comment]
@jasons316 My pleasure - it can be OK to bump this number, but only once you've set up proper cluster monitoring and know that your hardware setup can handle it. It's also intended to be set that high for ongoing maintenance of views that are already built, not for initial building of views of DBs with massive amounts of data.

Building views from scratch ties up `couchjs` processes in a way that incremental view updates don't. You could keep the number high but restrict how many views you build from scratch at once as an option, too.

As to your other question: none of this is a CouchDB bug. GitHub is for actual CouchDB bugs only.

If you are looking for general support with using CouchDB, please try one of these other options:

* The user mailing list. Signup instructions are [here](http://couchdb.apache.org/#mailing-lists)
* The Slack/IRC chat room. Joining instructions are [here](http://couchdb.apache.org/#chat)
