### ISSUE TITLE
Replication calls to _replicate are returning entire history even if replicator.max_history is set

### ISSUE THREAD

**Issue by tudordumitriu** [apache/couchdb#1659]
Hi 
We have a (potential) performance issue
We are doing custom _replicate calls on our server services in order to keep user databases in sync according to our business logic rules, which means a lot of call and responses to be parsed.
Everything works great, with one mention, the _replicate response contains ENTIRE history of all replications done upon that document.

I have tried setting up max_history in replicator group in settings, but no luck.
Since we are not interested at all replication history entries.

I don't know if replicator.max_history is the correct setting, but I found it by checking CouchDB code.

Please tell us how can we limit the ever-growing history in _replicate response

## Your Environment

* Version used: 2.2.0
* Browser Name and version:Chrome
* Operating System and version (desktop or mobile): Windows 10
* Link to your project:

**Comment by kocolosk** [comment]
Hmm, that's odd -- the history is only supposed to contain the last 20 entries by default, and yes I think you do have the right config setting there.

Can you possibly share one of these responses that contains more than 20 entries?

**Comment by tudordumitriu** [comment]
Hi @kocolosk and thanks for getting back,

I might have been wrong in saying that the entire is returned, but definitely there is something wrong, because this number is growing.
Now what is strange is that on the same documents that I used to investigate this scenario the replication is now started returning a very small number (like 9), but it steadily increased to 40 after possible 31 operations (didn't count exactly). So what I'm thinking is that was somehow cleaned by some scheduled maintenance job.

But I will attach 2 versions of the response I got for the same request (not subsequent but in time after a certain number of operations - and I am counting the start_last_seq):
{"source": "http://sa:go@localhost:5984/central","target": "http://sa:go@localhost:5984/userdb-61","doc_ids" : ["l_303381cf64f141f28a316b400b8a3cbb_org.couchdb.user:t"] }
[26_start_last_seq.txt](https://github.com/apache/couchdb/files/2504277/26_start_last_seq.txt)
[40_start_last_seq.txt](https://github.com/apache/couchdb/files/2504280/40_start_last_seq.txt)

Hope it helps.

**Comment by nickva** [comment]
Hi @tudordumitriu 

Thanks for your report.

Just like @kocolosk I thought you were looking at the replicator start / stop job history from the _scheduler/jobs. That is indeed configurable and default to 20. 

However, looking at the attached output it seems like you are noticing the `_local/<replication_id>` checkpoint document bodies. These are used to checkpoint replication progress on target and source. The bad news is that it is not configurable. The good news is it is hard-coded at 50: 

https://github.com/apache/couchdb/blob/master/src/couch_replicator/src/couch_replicator_scheduler_job.erl#L782

You could try to reduce the frequency of checkpoints. Now it defaults to 30 sec. But you could make it a bit larger: http://docs.couchdb.org/en/latest/config/replicator.html#replicator/checkpoint_interval (notice the units are in milliseconds). The default used to be 5 sec ( = 5000) so check if you have that set explicitly in your config overriding the newer default. You'd still ship all 50 history entries on each checkpoint update and read after a while but, but you'd just do it less frequently (once / minute vs once / every seconds).

**Comment by tudordumitriu** [comment]
Thank you @nickva
