### ISSUE TITLE
Access/Connect Couch Db 1.6 from a remote server 

### ISSUE THREAD

**Issue by nijilnandanam** [apache/couchdb#1663]
Hi There

I have installed couch db 1.6 in one of my amazon ec2 instance and i want to connect it from a blacknight hosted code. I had tried setting up the bind address in local.ini as 0.0.0.0 and tried connecting , but unfortunately it was not connecting.

There is no firewall blocking the port or IP  

Any help will be highly appreciated 

Thanks 
Nijil

**Comment by wohali** [comment]
Sorry, Apache CouchDB has deprecated v1.x and is no longer supporting this release via GitHub.

If you are looking for advice you can try our mailing list or Slack channel for informal assistance. See https://couchdb.apache.org/ for more information.
