### ISSUE TITLE
cannot stat 'src/docs/build/man/apachecouchdb.1': No such file or directory

### ISSUE THREAD

**Issue by lu-xiansheng** [apache/couchdb#1664]
I git clone from couchdb 2.2 and put it to unbuntu 14.0
install Dependencies
./configure

==> configuring couchdb in rel/couchdb.config
==> updating dependencies
==> config (get-deps)
==> b64url (get-deps)
==> ets_lru (get-deps)
==> khash (get-deps)
==> snappy (get-deps)
==> ioq (get-deps)
==> bear (get-deps)
==> meck (get-deps)
==> folsom (get-deps)
==> triq (get-deps)
==> hyper (get-deps)
==> ibrowse (get-deps)
==> jiffy (get-deps)
==> mochiweb (get-deps)
==> couch_epi (get-deps)
==> couch_log (get-deps)
==> chttpd (get-deps)
==> couch (get-deps)
==> couch_index (get-deps)
==> couch_mrview (get-deps)
==> couch_replicator (get-deps)
==> couch_plugins (get-deps)
==> couch_event (get-deps)
==> couch_stats (get-deps)
==> couch_peruser (get-deps)
==> couch_tests (get-deps)
==> ddoc_cache (get-deps)
==> fabric (get-deps)
==> global_changes (get-deps)
==> mango (get-deps)
==> mem3 (get-deps)
==> rexi (get-deps)
==> setup (get-deps)
==> rel (get-deps)
==> couchdb-2.2.0 (get-deps)
==> couchdb-2.2.0 (update-deps)
Updating config from {git,"https://github.com/apache/couchdb-config.git",
                          {tag,"1.0.4"}}
Updating b64url from {git,"https://github.com/apache/couchdb-b64url.git",
                          {tag,"1.0.1"}}
Updating ets_lru from {git,"https://github.com/apache/couchdb-ets-lru.git",
                           {tag,"1.0.0"}}
Updating khash from {git,"https://github.com/apache/couchdb-khash.git",
                         {tag,"1.0.1"}}
Updating snappy from {git,"https://github.com/apache/couchdb-snappy.git",
                          {tag,"CouchDB-1.0.1"}}
Updating ioq from {git,"https://github.com/apache/couchdb-ioq.git",
                       {tag,"1.0.1"}}
Updating docs from {git,"https://github.com/apache/couchdb-documentation",
                        {tag,"2.2.0"}}
Updating fauxton from {git,"https://github.com/apache/couchdb-fauxton",
                           {tag,"v1.1.18"}}
Updating folsom from {git,"https://github.com/apache/couchdb-folsom.git",
                          {tag,"CouchDB-0.8.2"}}
Updating hyper from {git,"https://github.com/apache/couchdb-hyper.git",
                         {tag,"CouchDB-2.2.0-4"}}
Updating ibrowse from {git,"https://github.com/apache/couchdb-ibrowse.git",
                           {tag,"CouchDB-4.0.1"}}
Updating jiffy from {git,"https://github.com/apache/couchdb-jiffy.git",
                         {tag,"CouchDB-0.14.11-2"}}
Updating mochiweb from {git,"https://github.com/apache/couchdb-mochiweb.git",
                            {tag,"v2.17.0"}}
Updating meck from {git,"https://github.com/apache/couchdb-meck.git",
                        {tag,"0.8.8"}}
Updating bear from {git,"https://github.com/apache/couchdb-bear.git",
                        "008f48aff819126e281d5ccae80a258bf9bf9c30"}
Updating triq from {git,"https://github.com/apache/couchdb-triq.git",
                        {tag,"v1.2.0"}}
You have configured Apache CouchDB, time to relax. Relax.

next make release
but,I get error like this
fatal: No names found, cannot describe anything.
==> config (compile)
==> b64url (compile)
==> ets_lru (compile)
==> khash (compile)
==> snappy (compile)
==> ioq (compile)
==> bear (compile)
==> meck (compile)
==> folsom (compile)
==> triq (compile)
==> hyper (compile)
==> ibrowse (compile)
==> jiffy (compile)
==> mochiweb (compile)
==> couch_epi (compile)
==> couch_log (compile)
==> chttpd (compile)
==> couch (compile)
Compiling priv/couch_js/http.c
Compiling priv/couch_js/main.c
Compiling priv/couch_js/utf8.c
Compiling priv/couch_js/util.c
==> couch_index (compile)
==> couch_mrview (compile)
==> couch_replicator (compile)
==> couch_plugins (compile)
==> couch_event (compile)
==> couch_stats (compile)
==> couch_peruser (compile)
==> couch_tests (compile)
==> ddoc_cache (compile)
==> fabric (compile)
==> global_changes (compile)
==> mango (compile)
==> mem3 (compile)
==> rexi (compile)
==> setup (compile)
==> rel (compile)
==> couchdb-2.2.0 (compile)
Installing CouchDB into rel/couchdb/ ...
==> rel (generate)
WARN:  'generate' command does not apply to directory /couchdb-test/couchdb-2.2.0
cp: cannot stat 'src/docs/build/man/apachecouchdb.1': No such file or directory
Makefile:336: recipe for target 'release' failed
make: *** [release] Error 1

BUT IF I download the apache-couchdb-2.2.0.tar.gz and  decompression it now I also run like this:
./configure
make release 
it worked noting error
why??is anyone can help me? thank!!

**Comment by wohali** [comment]
You are probably missing some required build-time dependencies.

We build CouchDB 2.2.0 on Ubuntu 14.04 via the following process:

1. Install depepndencies using the scripts in https://github.com/apache/couchdb-ci
1. `git clone`
1. `./configure && make release`
