### ISSUE TITLE
What is overriding my ~/Library/Preferences/couchdb2-local.ini 

### ISSUE THREAD

**Issue by marklindsay24** [apache/couchdb#1665]
This is related to #1020 

I have tried for two days trying to figure out how to override DB location when running the Mac App.

None of following updates work:
~/Library/Preferences/couchdb2-local.ini
/Applications/Apache\ CouchDB.app/Contents/Resources/couchdbx-core/etc/default.ini

Please HELP!
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by wohali** [comment]
Please don't open duplicate issues in our tracker.

Our Mac build is contributed and is not directly maintained by the entire Apache CouchDB team. Please be patient; someone will be along to help eventually.

If you're looking for faster support. try our user@couchdb.apache.org mailing list, or our Slack/IRC channels, both of which are described at our home page of https://couchdb.apache.org/ .

**Comment by marklindsay24** [comment]
I'm sorry, I already posted to closed defect #1020 and figured no one would look at because it was closed. I tried EVERY THING mentioned in #1020, with no luck. 

I'm sorry, but that is short answer. I would like this re-opened. OR clear instructions on updating plist. What was mentioned there was changing IP address, which I tried. but plist does not contain any database_dir.

**Comment by wohali** [comment]
@marklindsay24 Go and file an issue against https://github.com/janl/build-couchdb-mac , the bug is in that repository, not CouchDB.
