### ISSUE TITLE
Error when verifying instalation

### ISSUE THREAD

**Issue by LiamRa** [apache/couchdb#1679]
Error: {http_request_failed,"GET","http://127.0.0.1:5984/verifytestdb/", {error,{error,{conn_failed,{error,econnrefused}}}}}

That's the error I get, everything is installed properly except the replication part. Just wondering what exactly it is and how to fix it, thank you.

**Comment by wohali** [comment]
Is your CouchDB bound to 127.0.0.1?

We would need more of your couchdb.log file to diagnose this problem.

**Comment by wohali** [comment]
Closing until we get more information.
