### ISSUE TITLE
`unknown_error : shutdown` while querying a view

### ISSUE THREAD

**Issue by mariocasciaro** [apache/couchdb#1706]
A query to a view (`GET /{db}/_design/{ddoc}/_view/{view}`) randomly returned an `unknown_error : shutdown`. I found the following in the logs:

```
[error] 2018-10-30T01:55:39.748188Z couchdb@<obfuscated> <0.2708.1249> e22ce58db7 rexi_server: from: couchdb@<obfuscated>(<0.6510.1235>) mfa: fabric_rpc:map_view/5 throw:shutdown [{couch_mrview_util,get_view_index_state,5,[{file,"src/couch_mrview_util.erl"},{line,101}]},{couch_mrview_util,get_view,4,[{file,"src/couch_mrview_util.erl"},{line,45}]},{couch_mrview,query_view,6,[{file,"src/couch_mrview.erl"},{line,244}]},{rexi_server,init_p,3,[{file,"src/rexi_server.erl"},{line,139}]}]
[error] 2018-10-30T01:55:39.748746Z couchdb@<obfuscated> <0.6510.1235> e22ce58db7 req_err(4112032074) unknown_error : shutdown
    [<<"couch_mrview_util:get_view_index_state/5 L101">>,<<"couch_mrview_util:get_view/4 L45">>,<<"couch_mrview:query_view/6 L244">>,<<"rexi_server:init_p/3 L139">>]
```

Sorry if I can't give you more detailed info, that's all I've got at the moment.

## Expected Behavior

The query should return a result not an error.

## Current Behavior

The query returned - only in that one instance, for now - the following error:
```
{
  "error": "unknown_error",
  "reason": "shutdown",
  "ref": 4112032074,
  "name": "unknown_error",
  "status": 500,
  "message": "shutdown" 
}
```

## Steps to Reproduce (for bugs)

Cannot reproduce, the bug happened once.

## Your Environment

* Version used: 2.1.2
* Operating System and version (desktop or mobile): Ubuntu 16.04.4
* Running a cluster with 3 nodes and no sharding

**Comment by wohali** [comment]
Hi @mariocasciaro ,

This means that your `couchjs` process - the external process to CouchDB that runs JavaScript for handling views - crashed.

If this happens repeatedly, you can temporarily increase your logging level to `debug` which should show exactly which doc out of which database is causing the crash. It could be any number of reasons, but the most likely issue is that you've blown out the JS stack. The default size is 64MB, or 67108864.

This can be increased by adding `-S <bigger number>` to the `couchjs` line in your `local.ini` file as follows:

```
[query_servers]
javascript = ./bin/couchjs ./share/server/main.js -S 134217728
```

for a 128MB stack.

If the problem recurs and this doesn't help, please ask to reopen this ticket.

**Comment by mariocasciaro** [comment]
Hi Joan, thanks for the reply and for the workaround. What could cause the JS stack to "blow out", I mean is there anything we can do to avoid it in first instance?

**Comment by wohali** [comment]
Objects that JS allocates dynamically end up on the stack. A lot of temporary variables in your views, large list/structure manipulation, emit()ing very large objects, or tail-end recursion can all lead to this.

For complex JS views, upping the default stack size is a pretty normal thing.

For simple JS views, consider using [Mango](http://docs.couchdb.org/en/stable/api/database/find.html) instead.
