### ISSUE TITLE
cookie_authentication_handler failing to achieve successful cookie auth due to aggressive default timeout

### ISSUE THREAD

**Issue by kennsippell** [apache/couchdb#1711]
I have a fairly empty clean install of CouchDB with `httpd/authentication_handlers` set to `{couch_httpd_auth, cookie_authentication_handler}, {couch_httpd_auth, default_authentication_handler}`

## Expected Behavior

I'm attempting to authenticate using only a cookie header. Something like:

```
curl http://upstream:5984/db -H "Cookie: AuthSession=d29ya2VyOjVCREMzNkRGOoASAazydw8meb2W5VoGcXDPD_UH;" -H "Content-Type: application/json"
```

## Current Behavior
It isn't working with failure `{"error":"unauthorized","reason":"Authentication required."}`. The debug output for this lookup is:

```
[notice] 2018-11-02T13:01:56.383470Z couchdb@127.0.0.1 <0.29344.42> 41bae4dc6e upstream:5984 127.0.0.1 undefined GET /db 400 ok 0
[debug] 2018-11-02T13:02:02.431594Z couchdb@127.0.0.1 <0.29314.42> 699405e1e2 cache hit for worker
[debug] 2018-11-02T13:02:02.431645Z couchdb@127.0.0.1 <0.29314.42> 699405e1e2 timeout 600
```

## Possible Solution
Just to see if the timeout was blocking the lookup, I increased it to 3000 (didn't work) and 30000 (does work!)  Even with this massive timeout, the lookup seemed almost instantaneous (like couple ms not 300 seconds).

## Your Environment
* Version used: 2.2
* Operating System and version (desktop or mobile): Ubuntu 18.04

**Comment by wohali** [comment]
@kennsippell I think you left the `;` at the end of your cookie, try taking that off?

Can you include a full example of the commands you're using? I'm unable to reproduce - here's my worked example following along with [our documentation](http://docs.couchdb.org/en/stable/intro/security.html#cookie-authentication):

```bash
$ curl localhost:15984/
{"couchdb":"Welcome","version":"2.2.0-f350d5f5d","git_sha":"f350d5f5d","features":["pluggable-storage-engines","scheduler"],"vendor":{"name":"The Apache Software Foundation"}}
$ curl localhost:15984/_users
{"db_name":"_users","purge_seq":"0-g1AAAAFDeJzLYWBg4MhgTmHgz8tPSTV0MDQy1zMAQsMcoARTHguQZGgAUv___5-flciAU2WSApBMsgcqw6cKYt4DiHl4VSYlgMyrJ8q8AxDz7hNWuQCicj9emx1ANscTsDmRIUkeoiQLAMIZVnY","update_seq":"1-g1AAAAFDeJzLYWBg4MhgTmHgz8tPSTV0MDQy1zMAQsMcoARTIkOS_P___7MSGXAqSVIAkkn2hFQ5gFTFg1Ux4laVAFJVT8CsPBYgydAApIAK5xNWuQCicj9hlQcgKu8TVvkAohLkziwAHyFWdw","sizes":{"file":38110,"external":5361,"active":2322},"other":{"data_size":5361},"doc_del_count":0,"doc_count":1,"disk_size":38110,"disk_format_version":7,"data_size":2322,"compact_running":false,"cluster":{"q":8,"n":1,"w":1,"r":1},"instance_start_time":"0"}
$ curl -X PUT localhost:15984/_users/org.couchdb.user:wohali \
>   -H "Accept: application/json" \
>   -H "Content-Type: application/json" \
>   -d '{"name": "wohali", "password": "apple", "roles": [], "type": "user"}'
{"ok":true,"id":"org.couchdb.user:wohali","rev":"1-eeaf91cbeec553b1bb511be8e209bfda"}
$ curl -vX POST localhost:15984/_session   -H "Content-Type: application/x-www-form-urlencoded"   -d "name=wohali&password=apple"
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 15984 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 15984 (#0)
> POST /_session HTTP/1.1
> Host: localhost:15984
> User-Agent: curl/7.52.1
> Accept: */*
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 26
>
* upload completely sent off: 26 out of 26 bytes
< HTTP/1.1 200 OK
< Cache-Control: must-revalidate
< Content-Length: 39
< Content-Type: application/json
< Date: Fri, 02 Nov 2018 17:37:35 GMT
< Server: CouchDB/2.2.0-f350d5f5d (Erlang OTP/19)
< Set-Cookie: AuthSession=d29oYWxpOjVCREM4QjVGOt5WmL3C4JxHbMDbyBtF6zLDQhnJ; Version=1; Path=/; HttpOnly
<
{"ok":true,"name":"wohali","roles":[]}
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
$ curl -vX PUT localhost:15984/mydatabase \
>   --cookie AuthSession=d29oYWxpOjVCREM4QjVGOt5WmL3C4JxHbMDbyBtF6zLDQhnJ \
>   -H "X-CouchDB-WWW-Authenticate: Cookie" \
>   -H "Content-Type:application/x-www-form-urlencoded"
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 15984 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 15984 (#0)
> PUT /mydatabase HTTP/1.1
> Host: localhost:15984
> User-Agent: curl/7.52.1
> Accept: */*
> Cookie: AuthSession=d29oYWxpOjVCREM4QjVGOt5WmL3C4JxHbMDbyBtF6zLDQhnJ
> X-CouchDB-WWW-Authenticate: Cookie
> Content-Type:application/x-www-form-urlencoded
>
< HTTP/1.1 401 Unauthorized
< Cache-Control: must-revalidate
< Content-Length: 64
< Content-Type: application/json
< Date: Fri, 02 Nov 2018 17:38:55 GMT
< Server: CouchDB/2.2.0-f350d5f5d (Erlang OTP/19)
< Set-Cookie: AuthSession=d29oYWxpOjVCREM4QkIwOsxazK0odiw0o-B2dPfhC8wrdxQS; Version=1; Path=/; HttpOnly
< WWW-Authenticate: Cookie
< X-Couch-Request-ID: 2b2016a76b
< X-CouchDB-Body-Time: 0
<
{"error":"unauthorized","reason":"You are not a server admin."}
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```

OK, so I tried something for which I'm not authorized, but it did work.

**Comment by kennsippell** [comment]
So... I lied. It wasn't a clean&empty database. Definitely my mistake there. I had more in there than I was aware of.

I have a repro on a fresh install with my configuration/ddocs. I'm basically running the script you have above in a loop with 15kb payload per document. It fails after about 750 iterations. I'll continue to dig in to see if I can isolate particular aspects of the configuration which make this worse.

But I'll rephrase this issue -- how did you arrive at 600 as the default value for timeout and do you have any guidance on when to adjust this value?  Maybe you have some reference material or pointers to info about that which I haven't seen in your docs.

**Comment by wohali** [comment]
@kennsippell By default, a `_session`  token is valid for 10 minutes. CouchDB cookies are stateless, meaning we do not store the session information on the server *at all*. The 10 minute / 600 second setting is in `default.ini`, you can override it in `local.ini` with:

```ini
[couch_httpd_auth]
timeout = 3600 ; or whatever number of seconds you want
```

I presume your 750 iterations don't take the full 10 minutes?

If this is an actual bug we'll need your full configuration and test script to reproduce. Thank you for working to make that as minimal as possible! :handshake:

**Comment by kennsippell** [comment]
User Error! Thanks for helping me through it.

Feedback -- found [this](http://docs.couchdb.org/en/stable/config/auth.html#couch_httpd_auth/timeout) a bit vague.

`timeout = Number of seconds since the last request before sessions will be expired.`
