### ISSUE TITLE
Compaction daemon not working when some volumes are read-only?

### ISSUE THREAD

**Issue by sklassen** [apache/couchdb#1713]
Couchdb 2.2, when running under snap, is raising an alarm "disk is almost full" even though the film system is read-only.

## Possible Solution
i) Exclude read-only or loop devices from the disk monitoring; or, if that information isn't availble, ii) allow the dev or directory to be set via configuration; or iii) Disallow /snap directory to raise an alarm.

## Steps to Reproduce (for bugs)

couchdb.log is emitting

```
Nov 05 12:18:12 adsg-l01 couchdb.server[6448]: [info] 2018-11-05T04:18:12.556850Z couchdb@127.0.0.1 <0.53.0> -------- alarm_handler: {set,{{disk_almost_full,"/"},[]}}
Nov 05 12:18:12 adsg-l01 couchdb.server[6448]: [info] 2018-11-05T04:18:12.556883Z couchdb@127.0.0.1 <0.53.0> -------- alarm_handler: {set,{{disk_almost_full,"/snap/core/5548"},[]}}
Nov 05 12:18:12 adsg-l01 couchdb.server[6448]: [info] 2018-11-05T04:18:12.556907Z couchdb@127.0.0.1 <0.53.0> -------- alarm_handler: {set,{{disk_almost_full,"/snap/couchdb/7"},[]}}
```
While running df will reveal this
```
simon@adsg-l01:~$ df

Filesystem                                  1K-blocks       Used Available Use% Mounted on
udev                                         16382760          0  16382760   0% /dev
tmpfs                                         3282676       1544   3281132   1% /run
...
/dev/nvme0n1p2                              244567356  104018188 128056164  45% /
...
/dev/loop4                                      89984      89984         0 100% /snap/core/5548
/dev/loop1                                      42240      42240         0 100% /snap/couchdb/7
```
The data under snap is stored under /var/snap/couchdb/common (r/w) and the program binary and libraries is stored under /snap/couchdb/current (read-only). It is the second that couchdb should be monitoring.

## Context
No other side-affects. Compactor, when run manually, does run correctly. I've only seen this error under installation under snap.

## Your Environment
* Version used: Couchdb:2.2; snap 2.34.2;  snapcraft 2.43.1 
* Operating System and version (desktop or mobile): Ubunti 18.04

**Comment by wohali** [comment]
Hi @sklassen , thanks for bringing this issue over to this repository. Unfortunately this isn't all the context :) (Others, see https://github.com/apache/couchdb-pkg/pull/27 for more detail.)

The alarm warnings are innocuous - those come directly from Erlang. We can't suppress them.

What's concerning is the malfunction of the compactor daemon when it's being run from a read-only volume (like `/snap`). What you're sharing with us indicates that in this scenario, the compaction daemon never compacts any database.

**Comment by wohali** [comment]
Per @sklassen's [update](https://github.com/apache/couchdb-pkg/pull/27#issuecomment-435941673) the compaction daemon IS working, the nuisance is the alarming over the read-only volumes. I see no options in [`disksup`](http://erlang.org/doc/man/disksup.html) to change this behaviour. I'll check upstream with Erlang but we may be out of luck here.

**Comment by eiri** [comment]
If push come to shove it's possible to add `-os_mon start_disksup false` into `vm.args` to prevent `disksup` from starting at all. Why is it such a big deal? iirc we do not set alarm handlers on any of os_mon processes, so those are nothing, but harmless log warnings.
