### ISSUE TITLE
couchdb server logs continuously errors

### ISSUE THREAD

**Issue by mercoglianoisidoro** [apache/couchdb#1728]
Hello,
the couchdb server logs continuously errors like this one:

[error] 2018-11-08T09:04:36.290954Z nonode@nohost emulator -------- Error in process <0.14549.0> with exit value:
{database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,403}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,378}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,407}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,91}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,38}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,187}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,134}]}]}

What does it mean? How can I investigate?
Thank in avance, 
Isidoro.

**Comment by wohali** [comment]
This is normal - IF you didn't follow our setup documentation correctly.

Start here: http://docs.couchdb.org/en/stable/install/setup.html
