### ISSUE TITLE
Cluster Setup doesn’t consider shared http auth secret

### ISSUE THREAD

**Issue by janl** [apache/couchdb#1752]
Paraphrasing https://github.com/apache/couchdb-documentation/pull/356: Our setup wizard doesn't currently ensure consistent UUID and consistent http secret across all nodes in a cluster, so they must be done manually.

The /_cluster_setup endpoint should totally do this.

**Comment by VG-Fin** [comment]
Hi @janl,

When you said "ensure consistent UUID and consistent http secret accross all nodes in a cluster, so they must be done manually."

So you basically copied the UUID of your first node to the second one as well as the 'couch_httpd_auth' ? 
What happen if you add a new node to the cluster and you want to keep the same UUID ? also a simple copy?
