### ISSUE TITLE
can't create database in java using httpclient in cluster port

### ISSUE THREAD

**Issue by narci2010** [apache/couchdb#1758]
i can create database in commond line as below:
[root@localhost etc]# curl -X PUT "http://192.168.3.93:5984/test" --user root
Enter host password for user 'root':
{"ok":true}
 the same account and password in java httpclient,it return error message as below:
{"error":"unauthorized","reason":"You are not a server admin."}

my java code:
                String fullUrl =  "http://192.168.3.93:5984/test";
		HttpPut httpput = new HttpPut(fullUrl);
		httpput.setHeader("Content-type", "application/json;charset=UTF-8");
		httpput.setHeader("Accept", "application/json");
		httpput.setHeader("Cookie", this.login());//login use /_session api

**Comment by wohali** [comment]
Hi there,

This is not a CouchDB bug. GitHub is for actual CouchDB bugs only.

If you are looking for general support with using CouchDB, please try one of these other options:

* The user mailing list. Signup instructions are [here](http://couchdb.apache.org/#mailing-lists)
* The Slack/IRC chat room. Joining instructions are [here](http://couchdb.apache.org/#chat)
