### ISSUE TITLE
Tap forms 5 sync using Apache Couch DB on Mac OS Mojave

### ISSUE THREAD

**Issue by avinashmssr** [apache/couchdb#1763]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by avinashmssr** [comment]
Hi, I am trying to sync Apache CouchDB v2.2.0 to Tap Forms 5 using mac. I have created an admin and other non-admin users. However, only one file (The original Sample forms), that comes with tap forms manages to sync between computers (Admin login from the main mac and non-admin login through another mac). Also, the verification process fails randomly. It worked the first time but keeps failing after. Does any one have experience with this? If so, any help will be much appreciated.

**Comment by wohali** [comment]
@avinashmssr 

Hi there,

This is not a CouchDB bug. GitHub is for actual CouchDB bugs only.

If you are looking for general support with using CouchDB, please try one of these other options:

* The user mailing list. Signup instructions are [here](http://couchdb.apache.org/#mailing-lists)
* The Slack/IRC chat room. Joining instructions are [here](http://couchdb.apache.org/#chat)

You would do better to ask the Tap Forms people for help with their CouchDB plugin.
