### ISSUE TITLE
Phantom tls error/crash

### ISSUE THREAD

**Issue by slremy** [apache/couchdb#1777]
When running couch with certificates, I regularly see the following error in the logs. They do not appear to affect system functionality. 
```
[error] 2018-11-29T05:37:36.866796Z couchdb@127.0.0.1 <0.16250.98> -------- application: mochiweb, "Accept failed error", "{error,{tls_alert,\"record overflow\"}}"
[error] 2018-11-29T05:37:36.868199Z couchdb@127.0.0.1 <0.16250.98> -------- CRASH REPORT Process  (<0.16250.98>) with 0 neighbors exited with reason: {error,accept_failed} at mochiweb_acceptor:init/4(line:73) <= proc_lib:init_p_do_apply/3(line:247); initial_call: {mochiweb_acceptor,init,['Argument__1','Argument__2',...]}, ancestors: [https,couch_secondary_services,couch_sup,<0.208.0>], messages: [], links: [<0.222.0>], dictionary: [], trap_exit: false, status: running, heap_size: 2586, stack_size: 27, reductions: 881
```
This error was mentioned in passing in: https://github.com/apache/couchdb/issues/979#issuecomment-344791666
## Steps to Reproduce (for bugs)
It doesn't appear to matter whether I'm access couchdb using browser or connecting via java client.

## Your Environment

* Version used: 2.2.0 (installed via apt-get and https://apache.bintray.com/couchdb-deb)
* Browser Name and version: N/A
* Operating System and version (desktop or mobile): Xenial 
* Link to your project: N/A

**Comment by wohali** [comment]
@slremy This simply means that someone tried to connect to your SSL port and send data in plaintext without first setting up an SSL conneciton. Could be portscanning, could be a misconfigured client, etc.

http://erlang.org/pipermail/erlang-questions/2012-December/071099.html
