### ISSUE TITLE
performance problem when ab test for more than 100 concurrent connections on single node

### ISSUE THREAD

**Issue by Jing-Heng-Zhang** [apache/couchdb#1787]
I am going to use CouchDB as my shopping cart to replace the PostgreSQL as database
But I met a critical performance problem

**1 concurrent connection**
ab -c 1 -n 500 http://172.16.20.134:5984/test/000bd51215ab4d44b65001a6bda791fa
Percentage of the requests served within a certain time (ms)
  50%      1
  66%      3
  75%      3
  80%      3
  90%      3
  95%      3
  98%      3
  99%      4
 100%      4 (longest request)

**10 concurrent connection**
ab -c 10 -n 5000 http://172.16.20.134:5984/test/000bd51215ab4d44b65001a6bda791fa
Percentage of the requests served within a certain time (ms)
  50%     11
  66%     12
  75%     12
  80%     12
  90%     13
  95%     13
  98%     14
  99%     14
 100%     19 (longest request)

**100 concurrent connection**
ab -c 100 -n 5000 http://172.16.20.134:5984/test/000bd51215ab4d44b65001a6bda791fa

Percentage of the requests served within a certain time (ms)
  50%    116
  66%    117
  75%    117
  80%    118
  90%    119
  95%    123
  98%    126
  99%    126
 100%    135 (longest request)

**500 concurrent connection**
ab -c 500 -n 5000 http://172.16.20.134:5984/test/000bd51215ab4d44b65001a6bda791fa
Percentage of the requests served within a certain time (ms)
  50%    608
  66%    628
  75%    633
  80%    640
  90%    677
  95%    683
  98%    684
  99%    708
 100%    851 (longest request)

## Context
**All configuration is default**

## Expected Behavior

**I need multiple process to handle concurrent connections or similar mechanism**

## Current Behavior

**It seems there is only one process to  handler  all the concurrent connections**

## Your Environment
**Version: 2.2
Os:Centos 7.4 64bit(By VMware fusion 1 core,1GB Ram,20GB ssd disk)**
**Single Node no cluster**

Tested document content:

{"_id":"000bd51215ab4d44b65001a6bda791fa","_rev":"7-0761c0e2d5d6f02d342ff14e1f396a7d","title":"test 0e73e8f45f444bd1a4699b128b8dc31c","active":false,"clearance":false,"viewTimes":0,"createdAt":1543506141086,"type":"PRODUCT","brandId":"90df29b65d8144c090f3d77fb1ef5c15","categoryId":"f87ebb6522114a38ba0a410cbe262f34","name":"Ravi Tamada","email":"test@gmail.com","phone":{"home":"08947 000000","mobile":"9999999999"},"code":"USD","rate":1,"showLeft":true,"symbol":"$","asDefault":true,"prices":[{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100},{"moreThan":1,"price":100}]}

**Comment by wohali** [comment]
Hi there,

This is not a CouchDB bug. GitHub is for actual CouchDB bugs only. I can guaranteed you personally that people achieve > 20k requests / second with a 3-node CouchDB cluster regularly. You probably need to deploy a 3-node cluster per http://docs.couchdb.org/en/latest/setup/cluster.html

If you are looking for general support with using CouchDB, please try one of these other options:

* The user mailing list. Signup instructions are [here](http://couchdb.apache.org/#mailing-lists)
* The Slack/IRC chat room. Joining instructions are [here](http://couchdb.apache.org/#chat)
