### ISSUE TITLE
couchdb.service: Failed with result 'start-limit-hit'

### ISSUE THREAD

**Issue by axiqia** [apache/couchdb#1788]
After I installed couchdb， I could get the welcome information 

    $ curl localhost:5984       
    {"couchdb":"Welcome","version":"2.1.2","features":["scheduler"],"vendor":{"name":"The Apache Software Foundation"}}

But I can't check the status by `systemctl`

    $ systemctl status  couchdb.service
    ● couchdb.service
       Loaded: not-found (Reason: No such file or directory)
       Active: failed (Result: start-limit-hit) since 一 2018-12-03 14:52:14 CST; 6min ago
     Main PID: 30946 (code=killed, signal=USR2)
    
    12月 03 14:52:14 gpuhuawei systemd[1]: couchdb.service: Unit entered failed state.
    12月 03 14:52:14 gpuhuawei systemd[1]: couchdb.service: Failed with result 'signal'.
    12月 03 14:52:14 gpuhuawei systemd[1]: couchdb.service: Service hold-off time over, scheduling restart.
    12月 03 14:52:14 gpuhuawei systemd[1]: Stopped Apache CouchDB.
    12月 03 14:52:14 gpuhuawei systemd[1]: couchdb.service: Start request repeated too quickly.
    12月 03 14:52:14 gpuhuawei systemd[1]: Failed to start Apache CouchDB.
    12月 03 14:52:14 gpuhuawei systemd[1]: couchdb.service: Unit entered failed state.
    12月 03 14:52:14 gpuhuawei systemd[1]: couchdb.service: Failed with result 'start-limit-hit'.
    12月 03 14:53:53 gpuhuawei systemd[1]: Stopped Apache CouchDB.
    12月 03 14:53:53 gpuhuawei systemd[1]: Stopped Apache CouchDB.

When I run couchdb by command line, I got

    $ couchdb 
    {"init terminating in do_boot",{{badmatch,{error,{bad_return,{{couch_app,start,[normal,["/etc/couchdb/default.ini","/etc/couchdb/local.ini"]]},{'EXIT',{{badmatch,{error,{error,eacces}}},[{couch_server_sup,start_server,1,[{file,"couch_server_sup.erl"},{line,56}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,273}]}]}}}}}},[{couch,start,0,[{file,"couch.erl"},{line,18}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}
    [1]    2288 user-defined signal 2  couchdb

I have tried to reinstall couchdb, but it didn't help.
My work enviroment

    $ uname -a
    Linux gpuhuawei 4.15.0-34-generic #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by wohali** [comment]
Your error report says:

```
{{badmatch,{error,{error,eacces}}}
```

This indicates that at least one of the ini files is not readable by the CouchDB user.

Did you install from binary package?

For some reason you have configured CouchDB to use ini files under the `/etc` directory:

```
"/etc/couchdb/default.ini","/etc/couchdb/local.ini"
```

This is not the default configuration, as that is `/opt/couchdb/etc/*.ini`.

Either change your permissions on the files in `/etc` (and make sure they are up to date, `default.ini` changes with every release) or undo whatever customization you have put in place (for instance, editing `/opt/couchdb/etc/vm.args` or the systemd startup script) that changed the reference to where it looks for the ini files.

**Comment by wohali** [comment]
Also, this is the FIRST topic in our Troubleshooting documentation:

http://docs.couchdb.org/en/stable/install/troubleshooting.html
