### ISSUE TITLE
Setup single node using curl return unknown error

### ISSUE THREAD

**Issue by unomind** [apache/couchdb#1793]
I install couchdb 2.2.0 in virtualbox, centos 7 as guest OS. I also setup admins in local.ini. And I want to setup couchdb as single node without using fauxton wizard.

my command is:
```
curl -X POST -H "Content-Type: application/json" localhost:5984/_cluster_setup -d '{"action":"enable_single_node", "bind_address"="0.0.0.0"}'
```
## Expected Behavior
I dont know, what should the output is.

## Current Behavior
return unknown error:
{"error": "unknown_error", "reason":"badarg", "ref":"2158483052"}

Any help to setup single node (not cluster) from curl whould be nice.
Thanks

**Comment by wohali** [comment]
You have an equals sign `=` in your JSON, meaning your request is ill formed.

Try 
```bash
curl -X POST -H "Content-Type: application/json" localhost:5984/_cluster_setup -d '{"action":"enable_single_node", "bind_address":"0.0.0.0"}'
```
