### ISSUE TITLE
Can you help me create a couchdb-lucene view?

### ISSUE THREAD

**Issue by strelok1010** [apache/couchdb#1806]
A few months ago I worked with lucene + couchdb, because searches with couchdb were slow.
Here information about couchdb-lucene: 

https://github.com/rnewson/couchdb-lucene 

https://lucene.apache.org/core/2_9_4/queryparsersyntax.html

I have been doing maintenance, because the couchdb databases were extremely heavy. They were so heavy that my server was 100% full disk. I do not want to go into details, I'll go straight to the point. It seems that view functions have been accidentally deleted

My code generates the following query URLs.

> localhost:5985/local/db_urls/_design/search/url?q=filtered%3ValueHere%20AND%20filtered%3AValueHere%20AND%20competitor%3Anamecomp

> 

> localhost:5985/local/db_urls/_design/search/title?q=title%3ValueHere%20AND%20title%3AValueHere%20AND%20competitor%3Anamecomp

I have tried to recreate the views, but the result to the queries always gives empty.

> {"q":"+filtered:ValueHere+filtered:ValueHere+competitor:namecomp","fetch_duration":0,"total_rows":0,"limit":25,"search_duration":0,"etag":"8f751926c7089","skip":0,"rows":[]}

The views have remained as follows:

> {
>   "_id": "_design/search",
>   "_rev": "2-354e27564d69942d6b7b7ab03548200b",
>   "fulltext": {
>     "url": {
>       "index": "function(doc) { var ret=new Document(); ret.add(doc); return ret }"
>     },
>     "title": {
>       "index": "function(doc) { var ret=new Document(); ret.add(doc); return ret }"
>     }
>   }
> }

Although I have many doubts that "fulltext" is correct. Does anyone know what other alternatives I have? Can anybody help me?. It would be crazy to reread all the documentation, it has been very difficult the first time-

**Comment by wohali** [comment]
Hi there,

Unfortunately, we can't answer this question, and it is not a CouchDB bug itself.

If you are looking for general support with using CouchDB, please try one of these other options:

* The user mailing list. Signup instructions are [here](http://couchdb.apache.org/#mailing-lists)
* The Slack/IRC chat room. Joining instructions are [here](http://couchdb.apache.org/#chat)

**Comment by strelok1010** [comment]
Well, now I have a big mistake. Please, can you help me?.
I have removed the old lucene views and created new ones.
```
{
  "_id": "_design/foo",
  "_rev": "3-17cf9845cb8979104bef460f2eec0fbf",
  "fulltext": {
    "by_title": {
      "index": "function(doc) { var ret=new Document(); ret.add(doc.title); return ret }"
    },
    "by_filtered": {
      "index": "function(doc) { var ret=new Document(); ret.add(doc.filtered); return ret }"
    }
  }
}
```

When I clean the database, there is no problem:

```
curl -X POST http://localhost:5985/local/db_urls/_cleanup
{"ok": true}
```

But when I try to optimize the new views there are big problems:

```
curl -X POST http://localhost:5985/local/db_urls/_design/search/by_title/_optimize
{"reason":"no_such_view","code":400}
```
The worst part of all is when I try to optimize a lucene view that I have previously deleted:

```
curl -X POST http://localhost:5985/local/db_urls/_design/search/filtered/_optimize
{"ok": true}

```
Please, I beg you to help me.
