### ISSUE TITLE
CouchDB 2.3 purge_seq transition to "string" from "number" breaks Java client(s) 

### ISSUE THREAD

**Issue by sheinbergon** [apache/couchdb#1809]
According to the [docs](http://docs.couchdb.org/en/2.3.0/api/database/common.html), `purge_seq` is still reported as a "number". Reality has it - it's now ( and probably other fields as well) are now "strings". This is probably related to the "Clustered purge" feature. IBM's cloudant-java client is currently the only maintained java client for couchdb, and it cannot properly work with db-info queries (by the look of the stacktrace, it also affects the lightcouch driver, meaning both of these drivers will fail to work.

This leaves the couchdb-java ecosystem in a problematic state for 2.3 and future releases.

While I opened this [issue](https://github.com/cloudant/java-cloudant/issues/467) for the java driver, it will best to update the documentation for 2.3 and above release. and perhaps cover additional breaking changes.

**Comment by wohali** [comment]
As this will be resolved by a documentation patch, moving this to apache/couchdb-documentation.

**Comment by denyeart** [comment]
@wohali The change of purge_seq from JSON integer to JSON string also broke our CouchDB clients when we upgraded to CouchDB 2.3. Please mention the change in the v2.3 release notes.

**Comment by jiangphcn** [comment]
hey @denyeart, the change was described via commit https://github.com/apache/couchdb-documentation/commit/cc9feb13068e63332c9a1e81de95f17b31ef12c1#diff-6b4a3e899b13e42489f90830ed0a4c25R77. Is it not enough?

**Comment by denyeart** [comment]
@jiangphcn I don't think it is enough. Databases must not introduce incompatible API changes in a minor release that break existing applications.  And if they do so, it should be mentioned in release notes / upgrade notes so that people upgrading know about it.

**Comment by wohali** [comment]
We can't go back and update the 2.3 release notes now that the label has been placed on the repository, I'm sorry. It's an ASF limitation.
