### ISSUE TITLE
Is there any limit for validation design(with validate_doc_update function) document count?

### ISSUE THREAD

**Issue by Prabuganesan** [apache/couchdb#1814]
I have created a design document(with validate_doc_update function) for every object. If I have created 100 types of object then 100 design document will be created. So if I insert one document in CouchDB then 100 design document will be executed. Is it the correct way? Any limit available for the validation design document?

**Comment by wohali** [comment]
Correct - every `validate_doc_update` (VDU) will be run on *every* document `PUT/POST`. 100 different VDUs is probably a worst case scenario for your database.

Generally it is recommended to have a single VDU per database. Two or three isn't necessarily bad, if you want to do a bit of logic separation (admin/security checks in one VDU, data structure checks in another). But 100 is a terrible idea.

There's no way to limit VDUs per database other than through your own design.

**Comment by Prabuganesan** [comment]
I have designed single CouchDB for multiple objects. And create multiple apps and pointed on this single CouchDB. For this solution how can I implement DB validation for every object type? Any other solution?
