### ISSUE TITLE
Is there any limit for filter design document and index design document?

### ISSUE THREAD

**Issue by Prabuganesan** [apache/couchdb#1815]
I have designed single couchdb for multiple objects. And create multiple apps pointed on this single CouchDB. In this solution, I have two questions. 

1. I have created a filter design document for every app. If I have created 100 apps then create 100 filter design document. Is it the correct way? It's lead to any performance issue?

2. And I have created 100 objects. Every object has a primary column named as **objectname_id**. Here I need an index for the primary column. So I have created 100 index document. Is it correct?  It's lead to any performance issue?

Please answer this.

**Comment by wohali** [comment]
Hi there,

This is not a CouchDB bug. GitHub is for actual CouchDB bugs only.

If you are looking for general support with using CouchDB, please try one of these other options:

* The user mailing list. Signup instructions are [here](http://couchdb.apache.org/#mailing-lists)
* The Slack/IRC chat room. Joining instructions are [here](http://couchdb.apache.org/#chat)
