### ISSUE TITLE
Support custom _changes feeds

### ISSUE THREAD

**Issue by dodtsair** [apache/couchdb#1817]
Currently any given database has one changes feed, any replication to our from that database must consume this whole feed.  In tenanted database designs there are strong partitions around those tenants.  In the current design one tenant replicating into and out of the couchdb database must necessarily pay the performance hit of replicating the full database, where in fact the tenant is only interested in a small fraction of that data.

## Expected Behavior
Consider 6 couchdb databases named db1, dbA, dbB, dbC, dbD, dbE.
If replication is setup in the following order

1. db1 <-> dbA
1. db1 <-> dbB
1. db1 <-> dbC
1. db1 <-> dbD
1. db1 <-> dbE

Then the time it takes to replicate db1 and dbE together should be the same time it takes to replicate db1 and dbB together.  

## Current Behavior
With the current behavior 
1. db1 <-> dbA takes very little time, equal to roughly max of db1 size, dbA size
1. db1 <-> dbB takes significantly more time as all the revisions of both db1 and dbA must be iterated through
1. db1 <-> dbC must iterate through all the revisions of db1, dbA, and dbB
1. db1 <-> dbD must iterate through all the revisions of db1, dbA, dbB, and dbC
1. db1 <-> dbE must iterate through all the revisions of db1, dbA, dbB, dbC, and dbD

## Possible Solution
Allow the creation of custom feeds.  The db engineer would create a function like
```
function(doc) {
        return doc.tenantId
}

```
```
function(doc) {
        return doc.type
}

```

Upon injesting a change each of the custom feed functions would be run, the revision would be added to each feed as identified by the return from the custom feed function.

Consider an example of objects
```
{
    _id:"sdlihjalkhg",
    _rev:"1-sldkghjalkdga",
    tenantId: "adlhgalkba",
    type: "switch"
}

```
```
{
    _id:"sdlkgalkshga",
    _rev:"1-fdjkhvbwoi",
    tenantId: "adlhgalkba",
    type: "light"
}

```

```
{
    _id:"jkashdvadpj",
    _rev:"1-adicbwegad",
    tenantId: "adlhgalkba",
    type: "switch"
}

```

```
{
    _id:"asjkdbvaosadv",
    _rev:"1-ociyvaslkh",
    tenantId: "xckjbvswka",
    type: "switch"
}

```

```
{
    _id:"xcbjaovba",
    _rev:"1-cxuivghal",
    tenantId: "xckjbvswka",
    type: "light"
}

```

With the given two custom feed functions and the given documents the following feeds would exist

### adlhgalkba
```
{"seq":1, id:"sdlihjalkhg","changes":[{rev:"1-sldkghjalkdga"}]
{"seq":2, id:"sdlkgalkshga","changes":[{rev:"1-fdjkhvbwoi"}]
{"seq":3, id:"jkashdvadpj","changes":[{rev:"1-adicbwegad"}]
```

### adlhgalkba
```
{"seq":4, id:"asjkdbvaosadv","changes":[{rev:"1-ociyvaslkh"}]
{"seq":5, id:"xcbjaovba","changes":[{rev:"1-cxuivghal"}]
```

### switch
```
{"seq":1, id:"sdlihjalkhg","changes":[{rev:"1-sldkghjalkdga"}]
{"seq":3, id:"jkashdvadpj","changes":[{rev:"1-adicbwegad"}]
{"seq":4, id:"asjkdbvaosadv","changes":[{rev:"1-ociyvaslkh"}]

```
### light
```
{"seq":2, id:"sdlkgalkshga","changes":[{rev:"1-fdjkhvbwoi"}]
{"seq":5, id:"xcbjaovba","changes":[{rev:"1-cxuivghal"}]

```

This can all be done with multiple custom feed being calculated at the same time, as opposed to filtered replicate where each filtered replication must be done independently.  It is presumed that as part of injesting documents some of this work is already being done and can be leveraged to make this performance  

## Context
Consider a data model involving users invited to accounts that have files.  When setting up a browser client it would be desirable to do an offline first implementation, where there is a pouchdb database running in the browser.  That pouchdb database is replicated back to a master couchdb in the cloud.  This master database has all the accounts, users, and files in it.  With the current filtered replication, as the number of users, accounts, and files grow the replication cost for each user scales exponentially.  With a custom feed that cost can be brought down to linear.

**Comment by wohali** [comment]
This has been asked many, many times before and isn't going to happen the way you are asking for it to be implemented. Sorry to be the bearer of bad news.

For a detailed technical explanation as to why, see #592 and #831, and [this mailing list thread](https://lists.apache.org/thread.html/516793df0c1913c045441d0ff78339f307e2aff517d9223da44edd9e@%3Cdev.couchdb.apache.org%3E).

The good news is that you CAN achieve more efficient filtered replication without using JavaScript. The current recommendation for this functionality is to use a [Mango selector as a filter on the `_changes` feed](http://docs.couchdb.org/en/stable/api/database/changes.html?highlight=selector#selector), which will run significantly faster than the equivalent JavaScript `_changes` feed filter.

Also, [partitioned databases](https://github.com/apache/couchdb/pull/1789) are coming in CouchDB 2.4.0 - these may help you as well.

Finally, another thing that will help you in the future is the `_access` proposal which is slated for CouchDB 3.0. This will make multitenancy within a single database much more straightforward. See [the mailing list post on this topic](https://lists.apache.org/thread.html/6aa77dd8e5974a3a540758c6902ccb509ab5a2e4802ecf4fd724a5e4@%3Cdev.couchdb.apache.org%3E) for more information.
