### ISSUE TITLE
TLS alert / internal error on connecting to Cloudant with OTP 21.2 OpenSSL 1.1.1a CouchDB 2.3.0

### ISSUE THREAD

**Issue by jer-gentoo** [apache/couchdb#1823]
## Expected Behavior

With OTP 19.3.6.12, OpenSSL 1.0.2, and CouchDB 1.7.2, I can connect to any HTTPS replication server and have a secure connection to a verified host such as our service at Cloudant.

## Current Behavior
Setting up the same configuration with OTP 21.2, OpenSSL 1.1.1a, and CouchDB 2.3.0 works in every other respect than setting up TLS connections to Cloudant (and possibly other secure hosts, but I tried with Cloudant).

```
couchdb: [error] 2018-12-20T14:15:37.151234Z couchdb@127.0.0.1 <0.974.2> -------- couch_replicator_httpc: auth plugin initialization failed "https://*****:*****@*****.cloudant.com/*****/" {session_request_failed,"https://*****.cloudant.com/_session","*****",{conn_failed,{error,{tls_alert,"internal error"}}}}
```

Playing around with the `[ssl]` and `[replicator]` blocks in `local.ini` or even lowering security settings (e.g. to not check certificates at all) gave the same result.

Sniffing with Wireshark tells me that the local replicator returns that same error to the remote after it receives the remote certificate.

Workarounds I am thinking about are picking OpenSSL 1.1.0*, or OpenSSL 1.1.0* plus OTP 20.*, but I would rather be sure before I invest more time.

Kind regards,
     jer

**Comment by wohali** [comment]
From @rnewson (with Cloudant):

```irc
11:30 <+rnewson> cloudant supports TLS 1.0,1.1,1.2,1.3 for sure, yeah
11:31 <+rnewson> I can't say if any version of erlang works correctly with openssl 1.1.1.
11:31 <+rnewson> (99%+ of replications from couchdb to cloudant are using < TLS 1.3 btw,
                 so it certainly works)
11:32 <+rnewson> only browsers support TLS 1.3 so far, by and large. so we only see TLS
                 1.3 connections for dashboard things.
```

Erlang itself doesn't have support for TLS 1.3 or OpenSSL 1.1.1 yet:

https://groups.google.com/forum/#!topic/erlang-programming/9sRGyfkK9Io

> "no promises but planned for erlang 22"

Not sure there is anything for us to do here since this is an Erlang problem, not a CouchDB problem. 

Recommend staying with 1.1.0 or 1.0.2. We'll ensure things work for TLS 1.3 when Erlang 22 is out.

**Comment by wohali** [comment]
As a reminder, if you are working with Cloudant, and have an issue connecting to cloudant, you can file a support ticket with your account name, etc. - this isn't Cloudant tech support here ;)

**Comment by jer-gentoo** [comment]
I could reproduce this with any HTTPS connection if you like. Cloudant is the factor that did _not_ change.

**Comment by jer-gentoo** [comment]
```
lib/crypto/c_src/crypto.c:#if OPENSSL_VERSION_NUMBER >= PACKED_OPENSSL_VERSION_PLAIN(1,1,1)
lib/crypto/c_src/crypto.c:#if OPENSSL_VERSION_NUMBER >= (PACKED_OPENSSL_VERSION_PLAIN(1,1,1) -7) \
lib/crypto/c_src/crypto.c:# if OPENSSL_VERSION_NUMBER >= (PACKED_OPENSSL_VERSION_PLAIN(1,1,1))
lib/crypto/c_src/crypto.c:#if OPENSSL_VERSION_NUMBER >= (PACKED_OPENSSL_VERSION_PLAIN(1,1,1)-7)
```
Perhaps OpenSSL support in OTP 21.2 is incomplete.

**Comment by wohali** [comment]
CouchDB 2.3.0 explicitly enabled support for OTP 21 but I know of no one actually running that in production yet.

The fact is that any `{tls_alert,...}` is deep within Erlang's `ssl` application and there's nothing we can do about it. If you want, you can file an issue upstream with Erlang here: https://bugs.erlang.org/

If you're able to get SSL working with OTP 21 and OpenSSL 1.1.0 then I'd definitely consider that.

The only comment about OpenSSL 1.1.1 support in 21.1/2 is OTP-15133 and  OTP-15094 which enhance the internal Erlang ssh application to support new public key exchange methods. My guess is they didn't test if/how this broke SSL support - which sadly is very common, Erlang has had a number of serious SSL bugs in the past.

FYI TLS 1.3 support was only added to Erlang on 2 Nov as part of OTP-15310, and hasn't made it into any release yet: https://github.com/erlang/otp/commit/9c33f00f78724ce0f68fef1dfc6ab4810d8c45f18 Not sure if this is related.
