### ISSUE TITLE
Plus character in attachment name causes failure to download the attachment

### ISSUE THREAD

**Issue by ceremcem** [apache/couchdb#1830]
# Reproduction 

1. Attach `hello+there.png` (via Javascript (with [nano](https://github.com/apache/couchdb-nano), for example)) to a document 
2. Open Futon, use "View attachments" button to get `hello+there.png`
3. See that the attachment can not be found. 

More interestingly, the plus sign is replaced with whitespace when Futon is used to upload the attachment. 

(I'm not sure if I should I provide some detailed steps. Please let me know.)

# Expected behavior 

If plus sign is not allowed, a proper exception should be raised.

**Comment by ceremcem** [comment]
What is the status of this issue?

**Comment by nickva** [comment]
In a url, as a rule the `+` character has to be urlencoded.
