### ISSUE TITLE
GitHub project lists 2.2.0 as "Latest Release": should be 2.3.0

### ISSUE THREAD

**Issue by j13k** [apache/couchdb#1839]
## Expected Behavior

The Releases tab should list 2.3.0 as the latest release.

## Current Behavior

The Releases tab currently lists _2.2.0_ as the latest release, and the 2.3.0 release is hidden by default in a collapsed section.

**Comment by wohali** [comment]
Fixed, though we do not officially release through GitHub.

Official CouchDB releases are always at https://couchdb.apache.org/

**Comment by j13k** [comment]
Thanks, and understood. GitHub releases are useful however, as they can be consumed as an Atom feed, e.g.: https://github.com/apache/couchdb/releases.atom.
