### ISSUE TITLE
couchdb-2.3.0-1.el7.x86_64.rpm installation problem 

### ISSUE THREAD

**Issue by zubeydeBurcu** [apache/couchdb#1848]
Hello,
I am using rpm for the installation of the couch DB and 
[root@x:/data/couch]# rpm -ivh couchdb-2.3.0-1.el7.x86_64.rpm
error: Failed dependencies:
        couch-js = 1:1.8.5 is needed by couchdb-2.3.0-1.el7.x86_64
[root@x:/data/couch]#
[root@x:/data/couch]#
[root@x:/data/couch]#
[root@x:/data/couch]# rpm -ivh couch-js-1.8.5-21.el7.x86_64.rpm
error: Failed dependencies:
        js is obsoleted by couch-js-1:1.8.5-21.el7.x86_64
[root@x:/data/couch]#

## Expected Behavior
What is the problem reason? It does not resolved with the installation of couch-js-1.8.5-21.el7.x86_64.rpm? I

This is reproducable, can you please comment me how to resolve the issue?

I cannpt use yum for the installation, also i cannot pull from repo. These servers are not connected to internet. I need to find a solution to install with the rpm packages.

Best Regards,
Thanks
Burcu

**Comment by wohali** [comment]
You need to uninstall your `js` package first, then you can install our `couch-js` package.

**Comment by zubeydeBurcu** [comment]
Thanks Joan,

I have uninstalled js patch and  installed with the yum,  customer enabled yum with the js repulsitory and i am able to install  couch-js and couch db.
