### ISSUE TITLE
WWW-Authenticate config value is case sensitive, but gets saved or loaded in lower case, on MacOS

### ISSUE THREAD

**Issue by SCdF** [apache/couchdb#1850]
The `http/WWW-Authenticate` config property is only valid / recognised in that exact case, at least on MacOS. It is also either saved onto disk in lower case, or loaded into memory as lower case.

This means that whenever you restart CouchDB this config property ends up being in your config matrix in lower case, which in turn means it doesn't get used by the system.

Steps to reproduce: https://gist.github.com/SCdF/fb5f1dd4ebca24a986ce77b3e1a2fa59

CouchDB 2.3.0
MacOS 10.14.2 (18C54), on a case insensitive APFS volume (this is the default volume type for MacOS)
Installed CouchDB via downloading the package from the website.

**Comment by rnewson** [comment]
confirmed that case is preserved on OSX for me (using dev/run)

Can you show your local.ini file after the PUT in step 2 please?

```
curl foo:bar@localhost:15984/_node/_local/_config/httpd/WWW-Authenticate -XPUT -d '"Hello"'
""
➜  couchdb git:(feature/database-partitions) ✗ grep WWW-A ./dev/lib/node1/etc/local.ini
;WWW-Authenticate = Basic realm="administrator"
WWW-Authenticate = Hello
```

**Comment by SCdF** [comment]
@rnewson it doesn't appear to be written my `local.ini`

```
$ cat /Users/scdf/Library/Application\ Support/CouchDB2/etc/couchdb/local.ini
<snip>
[httpd]
secure_rewrites = false
enable_cors = true
max_http_request_size = 134217728
<snip>
```

Let me know if I should be looking somewhere else

**Comment by rnewson** [comment]
Ah, well that is the more likely explanation of your report, it was never persisted, so it doesn't survive restart. That is, it's not inadvertent case folding afaict.

I don't know the OSX binary bundle at all so can't speculate on why it can't write to local.ini but you could you confirm my hypothesis by setting a fully lower-case property key and confirm that it is also not persisted to local.ini?

Sidebar: double check that there's only that local.ini, perhaps you have two installs or somesuch?

@janl any thoughts on why _config can't write to local.ini?

**Comment by SCdF** [comment]
>  it was never persisted, so it doesn't survive restart.

A lower case version *is* persisted though, and that must be be being generated from my mixed case version, so that must be being stored somewhere.

I'm really confused as to where though! I'm going to search my entire hdd for `local.ini` and take a look at each one. It has to be there somewhere...

**Comment by SCdF** [comment]
Note: this machine **does** have CouchDB 1.x on it as well, which I use for supporting older versions of our software. They are in different places on disk though (CouchDB 1.x is via brew, 2.x is a MacOS app). Could they be fighting?

**Comment by SCdF** [comment]
```
$ sudo find . -name "local.ini" 2>/dev/null
./usr/local/etc/couchdb/local.ini
./Users/scdf/Code/Other/couchdb/couchdb/etc/couchdb/local.ini
./Users/scdf/Code/Other/angular-pouchdb/node_modules/semantic-release/test/registry/local.ini
./Users/scdf/Code/Medic/medic-os/platform/packages/medic-core/settings/medic-core/couchdb/private/local.ini
./Users/scdf/Library/Application Support/CouchDB2/etc/couchdb/local.ini
./Applications/Xcode.app/Contents/Developer/usr/share/xcs/CouchDB/etc/couchdb/local.ini
./Applications/Apache CouchDB.app/Contents/Resources/couchdbx-core/etc/local.ini
```

None of those files have been touched locally. Interestingly the correct one (in `~Library`) hasn't been touched for months either. 

I presume these permissions are correct: `-rw-r--r--  1 scdf  staff  1189 13 Aug 20:03`, I'm running CouchDB as `scdf` so it should have write access.

I have no idea where this parameter is being written 😨

**Comment by janl** [comment]
@SCdF can you paste the output of `ps ax | grep beam`? and `ls -la /Users/scdf/Library/Application\ Support/CouchDB2/etc/couchdb/local.ini`

**Comment by rnewson** [comment]
you could confirm which local.ini is used by stopping couchdb, manually adding a new item to it somewhere, and starting up again. then query :5984 as above to see if the item is there.

**Comment by SCdF** [comment]
@janl , Okey dokey we're getting somewhere:

```
$ ps ax | grep beam
47368   ??  S      1:10.29 /Applications/Apache CouchDB.app/Contents/Resources/couchdbx-core/bin/../erts-8.3/bin/beam.smp -K true -A 16 -Bd -- -root /Applications/Apache CouchDB.app/Contents/Resources/couchdbx-core/bin/.. -progname couchdb -- -home /Users/scdf -- -boot /Applications/Apache CouchDB.app/Contents/Resources/couchdbx-core/bin/../releases/2.3.0/couchdb -name couchdb@localhost -setcookie monster -kernel error_logger silent -sasl sasl_error_logger false -noshell -noinput -smp enable -ssl session_lifetime 300 -config /Applications/Apache CouchDB.app/Contents/Resources/couchdbx-core/bin/../releases/2.3.0/sys.config -couch_ini /Applications/Apache CouchDB.app/Contents/Resources/couchdbx-core/etc/default.ini /Users/scdf/Library/Preferences/couchdb2-local.ini
19838 s018  S+     0:00.01 grep beam

$ ls -la /Users/scdf/Library/Application\ Support/CouchDB2/etc/couchdb/local.ini
-rw-r--r--  1 scdf  staff  1189 13 Aug 20:03 /Users/scdf/Library/Application Support/CouchDB2/etc/couchdb/local.ini
```

So the config I'm using is `/Users/scdf/Library/Preferences/couchdb2-local.ini`. IDK if that's supposed to happen or not, but there it is?

So, repeating the gist, but checking that file each step, the badness happens when I *start* CouchDB with `WWW-Authenticate` in the file. When I start CouchDB it at some point in its startup re-writes it to disk as `www-authenticate`.

**Comment by rnewson** [comment]
hm, it's unusual to customise the list of ini files but perhaps that's in the binary .pkg scripting.

couchdb will write any config changes to the last file in that list, so couchdb2-local.ini should get that write. I noticed that many parts of that ps output has filenames with spaces in them. That's usually because ps is just crap at formatting things, but if the input filenames were not quoted properly, then that would be a problem.

I cannot induce case folding locally and there's no call to the function that does it anywhere in the config app itself.

**Comment by SCdF** [comment]
@rnewson so AFAICT:
 - It's writing correctly. If anything, the bug is either the [config documentation](http://docs.couchdb.org/en/stable/config/intro.html#configuration-files) is wrong for MacOS, or for some reason my particular install is pointing somewhere else
 - The spaces are OK I think, all of them are just part of the `Apache CouchDB.app` name, which is not something I can control anyway
 - It is defo somehow reading that file and then re-writing it as lower case. I unfortunately suck at Erlang so I wouldn't even know where to look here :-(

**Comment by rnewson** [comment]
@wohali aha! well that looks like it, thanks.

https://github.com/janl/couchdb-mac-app/blob/2c2e65528b8d10e001065bd3d5d3582373cc48a8/CouchDB%20Server/iniparser.c#L276 is where the bug is.

**Comment by rnewson** [comment]
oh and https://github.com/janl/couchdb-mac-app/blob/2c2e65528b8d10e001065bd3d5d3582373cc48a8/CouchDB%20Server/iniparser.c#L427

@janl just forgot that property names are case-sensitive is all.

**Comment by janl** [comment]
That’s stuff I’ve inherited from elsewhere, PRs welcome :)

**Comment by janl** [comment]
I fixed this in couchdb-mac-app master, the next version of CouchDB will include the fix.
