### ISSUE TITLE
Guide to develop plugin (looking for JWT in particular)

### ISSUE THREAD

**Issue by feg624** [apache/couchdb#1855]
Hi, I'm looking for some guide / directions to develop a plugin that supports JWT based authentication.

I've been reading different issues here, and also some alternatives, and I've found that there is an existent plugin out there https://github.com/softapalvelin/couch_jwt_auth , but I don't find the proper way to build it with Erlang.

I've also seen that CouchDB currently supports proxy auth, or I could have something in front of CouchDB to manage JWT, but in my opinion a plugin like the one mentioned above better suits the needs.

Thanks in advance,

Franco

**Comment by wohali** [comment]
Hi there @feg624 ,

This is not a CouchDB bug. GitHub is for actual CouchDB bugs only.

If you are looking for general support with using CouchDB, please try one of these other options:

* The user mailing list. Signup instructions are [here](http://couchdb.apache.org/#mailing-lists)
* The Slack/IRC chat room. Joining instructions are [here](http://couchdb.apache.org/#chat)

Thanks so much for your interest in Apache CouchDB!

P.S. That plugin was written for CouchDB 1.x and probably won't work with 2.x.
