### ISSUE TITLE
Installation path on Windows is not written to the registry

### ISSUE THREAD

**Issue by kangu** [apache/couchdb#1858]
After installing on a Windows machine, CouchDB 1.x used to write a registry key under HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Ericsson\Erlang\ErlSrv\1.1\Apache CouchDB where a WorkDir string value would be something like "C:\Program Files (x86)\Apache Software Foundation\CouchDB\bin".

For CouchDB 2.x, the registry is not updated anymore and there seems to be no standard way of determining the installation path.

## Expected Behavior
After installation on Windows machines, the installation path should be recorded somewhere in the registry, so that application can safely determine where the /log and /data folder are located.

## Current Behavior
2.x version installers do not write the installation path to the registry.

## Steps to Reproduce (for bugs)

1. Install CouchDB 2.x on a Windows machine.
2. Check that HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Ericsson\Erlang\ErlSrv\1.1\Apache CouchDB is created

## Context
I am aware that working with CouchDB on a file level is not recommended, but I have a use case where I need to move around some .couch files and integrate them into the database by doing a replication from port 5986 to 5984.

## Environment
* Version used: CouchDB 2.3
* Operating System: Windows 7, 64-bit

**Comment by wohali** [comment]
We're not going to add a key in the exact same location as 1.x, but I'll mark this as a future enhancement request.

You can write a C# program to get the path you need:

https://stackoverflow.com/questions/9787940/correct-method-to-get-installed-application-path-by-app-name-in-c-sharp#9788036

Or, you can be sure that when you install CouchDB, you specify the installation path consistently and use that path in your scripts.

**Comment by wohali** [comment]
Hey there @kangu ,

Just realized you can look at `HKLM\SYSTEM\CurrentControlSet\services\Apache CouchDB\Parameters\AppDirectory` to find this out.

As of the 3.0 installer (to be released in the next few days), you can access this at `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{4CD776E0-FADF-4831-AF56-E80E39F34CFC}\InstallLocation`. Hope that helps.
