### ISSUE TITLE
Fix chttpd etags

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#1863]
As requested by @eiri :

## Expected Behavior
etags work correctly

## Current Behavior
> A side note: I don't think chttpd family of etag functions is actually working. Make ETag generates binary make_etag, but validator etag_match/2 checks it versus tokenized header value, which gives a list of strings.

> It's an easy fix, but I'm hesitant to introduce it as part of this work, it seems that etag_respond/3 used in quite a few places in chttpd, so complete fix would make this PR rather messy.

**Comment by eiri** [comment]
@wohali So I've checked it and I was wrong, there are a proper type casting from binary to list in `etag_match`. I've added [a new elixir test](https://github.com/apache/couchdb/pull/1869) to confirm it works as expected
