### ISSUE TITLE
config system does not fail gracefully with invalid settings

### ISSUE THREAD

**Issue by fredguth** [apache/couchdb#1864]
I have tried to change the couch_httpd_auth/timeout to `24*60*60`.  It showed a error message and then nothing else would work.  Eventually every action would generate {"error":"unknown_error","reason":"badarg"}.  
## Expected Behavior

Show error message and do not change database state

## Current Behavior

Does not allow input in the form `24*60*60` and changes "something" that generates {"error":"unknown_error","reason":"badarg"} to every other action

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 2.3.0
* Browser Name and version: Chrome 71
* Operating System and version (desktop or mobile): OSX
* Link to your project:

**Comment by wohali** [comment]
@fredguth If you use curl to PUT a new value that is simply numeric, does it fix things? Or if you edit the `.ini` file?

Couch doesn't sanitize its input on the `_config` interface. This is a known issue - and I don't know if it'll be fixed any time soon.
