### ISSUE TITLE
the request Json Object with the field '"new_edits": false' use in conjonction with the "/db/_bulk_docs" seems to not work

### ISSUE THREAD

**Issue by olivenvrac** [apache/couchdb#1876]
## Description

I want to update docs massively whithout specify _rev informations in the bulk doc and generate conflicts 
to do this i use  the field '"new_edits": false' in the request Json Object use in conjonction with the "/db/_bulk_docs", but it doesnt work.

in the documentation of the handler "/db/_bulk_docs" we can read this 
Request JSON Object:
new_edits (boolean) – If false, prevents the database from assigning them new revision IDs. Default is true. Optional

## Steps to Reproduce

here is what I do :
i have 3 docs in my db : 
{ "_id": "pk5896",  "_rev": "1-946f6e944df9b086f03fb3e45935ab3b", "produit": "pomme", "type": "fruit"}
{ "_id": "ls5875",  "_rev": "1-4183ce21a4c67d05cb9a291b36710f7f", "produit": "banane", "type": "fruit"}
{ "_id": "it8765",  "_rev": "9-6058b0806c4b0e7d53058f22dd4b8c10", "produit": "salade", "type": "légume"}

I want to update this docs in bulk mode whitout _rev specified to generate conflicts.
in the documentation it is specified to position the field "new_edits": false in the json bulk doc like this :
{
 "new_edits": false,
 "docs": [
  { "_id": "pk5896", "produit": "pomme", "type": "fruit"},
  { "_id": "ls5875", "produit": "banane", "fonction": "fruit"},
  { "_id": "it8765", "produit": "salade", "fonction": "légume"},
  ]
}

but when i try to POST the document, couchdb return to me an error :
curl -sSX POST -H "Content-Type: application/json" 'http://user:mdp@serveur.domain:5984/db/_bulk_docs' -d @fic.json 
{
  "error": "unknown_error",
  "reason": "function_clause",
  "ref": 2857759975
}

if i change the value of new_edits : false by true, couchdb respond normaly :
[
  {
    "id": "pk5896"
    "error": "conflict",
    "reason": "Document update conflict."
  },
  {
    "id": "ls5875",
    "error": "conflict",
    "reason": "Document update conflict."
  },
  {
    "id": "it8765",
    "error": "conflict",
    "reason": "Document update conflict."
  }
]

## Expected Behaviour / question

is this option is always supported or i am doing a mistake  (syntax, comprehension of the focntion, other reason) ?
does it work only on _local documents ?

I have find this too in the documentation : 
http://docs.couchdb.org/en/latest/whatsnew/2.3.html?highlight=new_edits
#1683: Attempting to create a local document with an invalid revision no longer throws a badarg exception.
Also, when setting new_edits to false and performing a bulk write operation, local documents are no longer written into the wrong btree.
Finally, it is no longer possible to create a document with an empty ID during a bulk operation with new_edits set to false.

##  Environment

* CouchDB Version used: 2.3
* Operating System and version: RHEL 7

Thanks for you'r reply.

**Comment by ondra-novak** [comment]
When new_edits=false is used, you should always include _revisions key into the document. This is not correctly documented. You can see format of this field here for example:

https://docs.couchdb.org/en/stable/api/document/common.html?highlight=_revisions#getting-a-list-of-revisions

**Comment by wohali** [comment]
Kindly open a new issue at https://github.com/apache/couchdb-documentation for the docs bug? Thanks!

**Comment by olivenvrac** [comment]
thanks both for the reply.
so, i will close this issue and open a new for the documentation bug.
before closing this issue can you tell me if there is a similar method like this one described (bulk mode) for generating massive doc conflicts ?

**Comment by wohali** [comment]
No, the _bulk_docs endpoint is the only bulk endpoint useful for this in CouchDB of which I know.

**Comment by wohali** [comment]
See  https://github.com/apache/couchdb-documentation/issues/390 .
