### ISSUE TITLE
Allow access to _uuids through rewrites when secure_rewrites is enabled

### ISSUE THREAD

**Issue by nkronlage** [apache/couchdb#1882]
## Summary

I'm writing an app where I'm trying to use rewrites to provide cleaner urls.  I'd like to use the secure_rewrites setting to prevent the rewrites from accessing other databases, but I'd also like to use _uuids to generate uuids.  Since this is available at the root, it is not accessible unless I turn off secure_rewrites.

Alternatively, a way to provide an 'allow list' of destinations to rewrite to in the settings would be good too. 

## Desired Behaviour

There's a way to call _uuid through a rewrite while secure_rewrites is enabled. 

## Possible Solution

Allow accessing _uuid through any database.  Something like:

```
~$ curl 'http://127.0.0.1:5984/mydatabase/_uuids'
{"uuids":["6c59d2b3e582f05f7589fc2cef0a58c0"]}
```
Then the rewrite will not go outside the scope of the database.

## Additional context

To enable this in my app, I'd have to turn off secure_rewrites so the rewrite can access _uuids. This opens a huge security hole in the application since the rewrite could access any path then.  I'd like to keep secure_rewrites enabled for the security of the app.

See also #1881

**Comment by ondra-novak** [comment]
Don't use _uuids and create own uuids offline. 

I am using this code (javascript)

```
var genUID=function(prefix) {
	"use strict";

	var CHARSET = "0123456789aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ".split("");
	var maxrand = Math.pow(2,23);

	var encode = function(int) {
	    var res = "";
	    while (int > 0) {
	    	var z = Math.floor(int/62.0);
	    	var x = Math.floor(int-z*62.0);
	        res = CHARSET[x] + res;
	        int = z;
	    }
	    return res;
	};

	
	var s1 = prefix?prefix:"";
	var s2 = encode(Date.now());
	var a = new Uint32Array(2);
	window.crypto.getRandomValues(a);
	var s3 = encode((a[0] & 0x7FFFFFFF)| 0x40000000);
	var s4 = encode((a[1] & 0x7FFFFFFF)| 0x40000000);
	
	
	return s1+s2+s3+s4;
	
};
```

Example of result: "ICBbwoG26hEY61z1GjA"

**Comment by wohali** [comment]
A similar request was made  to allow access to `/_up` via a pinhole, but [the PR was rejected](https://github.com/apache/couchdb/pull/856). I am afraid that we'll have to mark this as WONTFIX for now, but we'll consider coming back to it when the CouchDB security system is rewritten (#1504).
