### ISSUE TITLE
Tag elixir tests into meaningful groups

### ISSUE THREAD

**Issue by iilyak** [apache/couchdb#1885]
Elixir has ability to tag test cases. Which means we can split tests into categories and run them in the sensible order. We would need to do some leg work to make it happen, but it is doable. We want to fail fast so we would run the group of tests in the following order:

- `single_node`
- `degraded_cluster`
- `cluster`
- `performance`
- `property_based`

**Comment by wohali** [comment]
poke @van-mronov @jjrodrig does this issue interest either of you?

**Comment by van-mronov** [comment]
@wohali @iilyak sure, I'd gladly deal with this task.

**Comment by van-mronov** [comment]
@wohali @iilyak so, do we already know which tests are `single_node`, etc?

**Comment by iilyak** [comment]
I don't know from the top of my head but it is easy to figure out.

1. one of the signs for tags is if we start tests differently https://github.com/apache/couchdb/blob/master/Makefile#L211
2. tests which require single node setup fail when `dev/lib` is present
  - run dev cluster for few seconds (we just need it let to join) `dev/run --admin=adm:pass`
  - stop the cluster `CTRL+C`
  - modify Makefile so `devclean` is not called for elixir tests
     - add @echo on https://github.com/apache/couchdb/blob/master/Makefile#L473 line
  - run elixir tests and check which ones fail
    - `make elixir`
    - `make elixir-cluster-without-quorum`
    - `make elixir-cluster-with-quorum`

**Comment by wohali** [comment]
I'm a little nervous about this proposal just pushing tests into a `flaky` category and then never being examined.

Who is volunteering to clean up these tests and ensure we don't ignore them forever?

**Comment by wohali** [comment]
@jjrodrig @dottorblaster Either of you still interested in taking this on?

**Comment by dottorblaster** [comment]
@wohali absolutely!

**Comment by nickva** [comment]
This was implemented in https://github.com/apache/couchdb/pull/3110

However we ended up using hard-coded suites instead it seems.
