### ISSUE TITLE
couchdb does not stop growing and occupy my entire hard drive.

### ISSUE THREAD

**Issue by carlosibex** [apache/couchdb#1892]
I'm using couchdb with lucene, I've noticed that my server has crashed many times because it takes up the entire disk space.

I have invented a "solution" and it is a programmed task that "compresses" the databases, however, it has happened to me again ... the server has been crashed. What else can I do to prevent this from happening?

My solution:

```
$alldbs = json_decode(file_get_contents("http://MyIP:5984/_all_dbs"), true);
$exceptdbs = ['_replicator', '_users'];
foreach ($alldbs as $db)
{
	if(in_array($db, $exceptdbs)) continue;
	$ch = curl_init();
	$header = array('Content-type: application/json','Accept: */*');
	curl_setopt($ch, CURLOPT_URL, 'http://MyIP:5984/'.$db.'/_compact');
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	curl_setopt($ch, CURLOPT_HTTPHEADER, $header);
	curl_setopt($ch, CURLOPT_USERPWD, 'admin'.':'.'MyPass');		  
	$response = curl_exec($ch);
	$response = json_decode($response, true);
	curl_close($ch);
}
```

UPDATE:

I updated version 2.2 to 2.3 and configured local.ini:

```
[compactions]
_default = [{db_fragmentation, "70%"}, {view_fragmentation, "60%"}, {from, "00:00"}, {to, "08:00"}, {strict_window, true}]
```

**How to can I check if this code work?**

**Comment by wohali** [comment]
Hi there,

This is not a CouchDB bug. GitHub is for actual CouchDB bugs only.

If you are looking for general support with using CouchDB, please try one of these other options:

* The user mailing list. Signup instructions are [here](http://couchdb.apache.org/#mailing-lists)
* The Slack/IRC chat room. Joining instructions are [here](http://couchdb.apache.org/#chat)

**Comment by carlosibex** [comment]
Is not a bug? https://github.com/apache/couchdb/issues/1579

**Comment by wohali** [comment]
@carlosibex You upgraded, so you are no longer running into that bug.
