### ISSUE TITLE
Local documents are not visible

### ISSUE THREAD

**Issue by nvsajeeva** [apache/couchdb#1906]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
I have two couch databases in two servers and I created a replication document.
As per (http://docs.couchdb.org/en/stable/api/local.html#api-local) local checkpoint document should be visible. But I'm unable to see it. 

Questions: 
1. I need to see the checkpoint document, Let me know the steps.
2. If I have a cascade replication setup. A(master)-> B-> C), If server B goes down, would it be possible to promote C in place of B by resuming the replication? (May be somehow backing up checkpoint information in B time to time and copy those to C during the promotion?

Create two databases in two different servers,
Create the replication,
Check local documents
```
root@es01:~# curl -X GET http://root:root@localhost:5984/_replicator/replication_sajeeva3
{"_id":"replication_sajeeva3","_rev":"2-ad59daf8d0fb5d2acdb1f1b86a4745d5","source":"http://root:root@192.168.56.101:5984/sajeeva","target":"http://root:root@192.168.56.102:5984/sajeeva","continuous":true,"create_target":true,"user_ctx":{"name":"admin","roles":["_admin"]},"owner":"root","use_checkpoints":true,"_replication_state":"triggered","_replication_state_time":"2019-02-06T11:27:29+05:30","_replication_id":"8ea02bddb63ef1e43ea4b347464e25b5"}
root@es01:~#
root@es01:~#
root@es01:~#
root@es01:~# curl -X GET http://root:root@localhost:5984/_config/replicator/use_checkpoints
"true"
root@es01:~# curl -X GET http://root:root@localhost:5984/sajeeva/_local_docs
{"error":"not_found","reason":"missing"}
root@es01:~#
root@es01:~# curl -X GET http://root:root@localhost:5984/
{"couchdb":"Welcome","uuid":"583fe429aa0737a5b562247fe8fba7be","version":"1.6.0","vendor":{"version":"15.10","name":"Ubuntu"}}
root@es01:~#
```
[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour
Local documents should be visible when _local_docs is called.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB Version used: CouchDB 1.6.0 (I checked with 1.7.2 also)
* Browser name and version:
* Operating System and version: Ubuntu 16.04

## Additional context

[TIP]:  # ( Add any other context about the prbolem here. )

**Comment by wohali** [comment]
The _local_docs endpoint wasn't added until CouchDB 2.x, sorry.

CouchDB 1.x is no longer supported.

**Comment by nvsajeeva** [comment]
Hi wohali,
If no checckpoint document is kept, how couchdb resumes the replication?
