### ISSUE TITLE
1.7.2 tag missing from repo

### ISSUE THREAD

**Issue by dgerhardt** [apache/couchdb#1909]
## Description

Older CouchDB releases < 2.3.0 can no longer be downloaded from apache.org or its mirrors. I was looking for version 1.7.2 which has never been pushed to the repository. As a side effect, older Docker images can no longer be rebuild.

## Expected Behaviour

I would expect all previously released CouchDB versions to be available at 
https://dist.apache.org/repos/dist/release/couchdb/ or https://archive.apache.org as required by http://www.apache.org/legal/release-policy.html#release-archival.

**Comment by janl** [comment]
Good find. I’ll see how we can refill the archive, but 1.x is no longer maintained and you shouldn’t rely on the Apache Archive for production deployments.

**Comment by janl** [comment]
Ah, it looks like links are weird and whatnot, but all releases are here as per policy: http://archive.apache.org/dist/couchdb/ including 1.7.2: http://archive.apache.org/dist/couchdb/source/1.7.2/

**Comment by dgerhardt** [comment]
Got it. Thanks for the quick response. We are using 2.3 for production but still need to test some data migration code against older versions of CouchDB.

Would it be possible to push the updated branch and tag to the repo? I guess it was just hold back for the binary release because of security fixes.

**Comment by janl** [comment]
another good call, I think @dch should have that locally.

**Comment by dch** [comment]
https://bsd.network/@dch/101551076239900549  maybe next week

**Comment by wohali** [comment]
@dgerhardt The problem with archive.apache.org is that it mirrors the very *first* place a file is put, and we changed our directory structure a couple of times in the past. So the top level looks like it didn't get updated since 1.2.1, when really everything is just under the source/ subdirectory instead. :)

@dch enjoy the skiing! Don't think about CouchDB until you're done! Jealous.

**Comment by big-r81** [comment]
Closing this, tag 1.7.2 isn't online, but the sources are released at the archive server.
