### ISSUE TITLE
could you please give me couchdb steps in ubuntu 

### ISSUE THREAD

**Issue by sbcsuman** [apache/couchdb#1911]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Steps to Reproduce

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB Version used:
* Browser name and version:
* Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the prbolem here. )

**Comment by wohali** [comment]
@sbcsuman http://docs.couchdb.org/en/latest/install/unix.html#installation-using-the-apache-couchdb-convenience-binary-packages

**Comment by sbcsuman** [comment]
> @sbcsuman http://docs.couchdb.org/en/latest/install/unix.html#installation-using-the-apache-couchdb-convenience-binary-packages

Hi wohali,
thanks for your update. but i am following that link but i am getting below eroor

sudo apt-get --no-install-recommends -y install \
    build-essential pkg-config erlang \
    libicu-dev libmozjs185-dev libcurl4-openssl-dev

Error:E: Unable to locate package libmozjs185-dev

**Comment by sbcsuman** [comment]
Hi Wohali,
server is running but webbrowser is working fine.

● couchdb.service - Apache CouchDB
   Loaded: loaded (/lib/systemd/system/couchdb.service; enabled; vendor preset:
   Active: active (running) since Sun 2019-02-10 14:18:07 UTC; 1s ago
 Main PID: 19634 (beam.smp)
    Tasks: 23 (limit: 1152)

**Comment by wohali** [comment]
run `curl http://localhost:5984`

point your browser at `http://localhost:5984/_utils`

**Comment by sbcsuman** [comment]
Hi,
Okay. Could you please give me for Ubuntu 18.0 version installation steps
for couchdb.

**Comment by wohali** [comment]
@sbcsuman http://docs.couchdb.org/en/latest/install/unix.html#installation-using-the-apache-couchdb-convenience-binary-packages

**Comment by sbcsuman** [comment]
Hi ,
I am following those steps. I am getting below error

root@ip-172-31-23-199:/home/ubuntu# apt-get install couchdb

                 Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 couchdb : Depends: libcurl3 (>= 7.16.2) but it is not going to be installed
           Depends: libicu55 (>= 55.1-1~) but it is not installable
           Recommends: python3-progressbar but it is not going to be
installed
E: Unable to correct problems, you have held broken packages.

**Comment by sbcsuman** [comment]
HI,

root@ip-172-31-18-78:/home/ubuntu# echo "deb
https://apache.bintray.com/couchdb-
                                                deb Ubuntu 18.04:bionic
main" \ | sudo tee -a /etc/apt/sources.list
deb https://apache.bintray.com/couchdb-deb Ubuntu 18.04:bionic main
root@ip-172-31-18-78:/home/ubuntu# sudo apt-get update

                Hit:1 http://security.ubuntu.com/ubuntu bionic-security
InRelease
Ign:2 http://ppa.launchpad.net/couchdb/stable/ubuntu bionic InRelease
Hit:3 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu bionic InRelease
Hit:4 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu bionic-updates
InRelease
Err:5 http://ppa.launchpad.net/couchdb/stable/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Hit:6 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu bionic-backports
InRelease
Ign:7 https://apache.bintray.com/couchdb-deb Ubuntu InRelease
Err:8 https://apache.bintray.com/couchdb-deb Ubuntu Release
  404  Not Found [IP: 52.34.114.104 443]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/couchdb/stable/ubuntu bionic
Release
                    ' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore
disa
                bled by default.
N: See apt-secure(8) manpage for repository creation and user configuration
deta
                ils.
E: The repository 'https://apache.bintray.com/couchdb-deb Ubuntu Release'
does n
                  ot have a Release file.
N: Updating from such a repository can't be done securely, and is therefore
disa
                bled by default.
N: See apt-secure(8) manpage for repository creation and user configuration
deta
                ils.

**Comment by wohali** [comment]
wrong command

```
$ echo "deb https://apache.bintray.com/couchdb-deb bionic main" \
    | sudo tee -a /etc/apt/sources.list
```

**Comment by sbcsuman** [comment]
As per your link i am following

*Debian/Ubuntu*: Run the command:

$ echo "deb https://apache.bintray.com/couchdb-deb {distribution} main" \
    | sudo tee -a /etc/apt/sources.list

and replace {distribution} with the appropriate choice for your OS version:

   - Debian 8: jessie
   - Debian 9: stretch
   - Ubuntu 14.04: trusty
   - Ubuntu 16.04: xenial
   - Ubuntu 18.04: bionic

**Comment by wohali** [comment]
Right, and your distribution is named `bionic`. Not `Ubuntu 18.04: bionic`.

**Comment by sbcsuman** [comment]
Hi John
I am getting below error

Failed to fetch
https://apache.bintray.com/couchdb-deb/dists/stretch/InReleas
e
