### ISSUE TITLE
Add Metric to count unindexed mango queries

### ISSUE THREAD

**Issue by janl** [apache/couchdb#1913]
Similar motivation as #1324.

https://github.com/apache/couchdb/blob/master/src/mango/src/mango_cursor.erl#L152 would be the location.

**Comment by willholley** [comment]
This has been on my wish list for a while :)

Similarly, I think it would be useful to collect metrics around the data we collect for execution stats [here](https://github.com/apache/couchdb/blob/a6bc72e76c56a1befa8675b06016ecda46ef3a2d/src/mango/src/mango_execution_stats.erl#L85). The execution stats are always collected, just not always returned to the client.

Bear in mind that unindexed Mango queries aren't a problem per se. Performance problems mostly occur when the ratio of documents examined to results returned is high, which can happen for indexed queries as well.

**Comment by janl** [comment]
> Bear in mind that unindexed Mango queries aren't a problem per se. Performance problems mostly occur when the ratio of documents examined to results returned is high, which can happen for indexed queries as well.

@willholley absolutely, my motivation here is: what metric can a DBA look at to know something uses a lot of CPU/IO without having to tap into the HTTP traffic or client code.

**Comment by willholley** [comment]
@janl if that's the requirement, I think it would be a better signal to highlight queries with a high ratio between docs examined and results returned, implying the index isn't narrowing the result set enough. We actually have a warning in (Fauxton)[https://github.com/apache/couchdb-fauxton/blob/4ae5bfb2d9ac571543da646b07e14a3e9623a510/app/addons/documents/mango/components/ExecutionStats.js#L44] when this ratio is 10:1 but it should really be a server-generated warning instead, with a corresponding metric. 

Similarly, we [already capture](https://github.com/apache/couchdb/blob/5ef18802cb82169843bd32edee838d4302d0dd97/src/mango/src/mango_execution_stats.erl#L85) the number of docs examined and number of results returned for each query so could add metrics for those. I can look at it this week if there's agreement it would be useful.

**Comment by janl** [comment]
@willholley I’m happy to +1 a PR that adds this.

**Comment by wohali** [comment]
@willholley yup, +1 from me too, if you want it in 3.0 time's a wastin'! 😉

**Comment by willholley** [comment]
thanks both - initial PR for review is https://github.com/apache/couchdb/pull/2410.
