### ISSUE TITLE
When running curl I keep getting certifcate errors

### ISSUE THREAD

**Issue by greg2git** [apache/couchdb#1923]
Here is my curl against couchDB server inside a container
curl https://127.0.0.1:6984 -k -v -E --cert-status

And here is the output:
```
* Rebuilt URL to: https://127.0.0.1:6984/
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 6984 (#0)
* found 149 certificates in /etc/ssl/certs/ca-certificates.crt
* found 594 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* error reading X.509 key or certificate file: Error while reading file.
* Closing connection 0
curl: (35) error reading X.509 key or certificate file: Error while reading file.
```

How can I get past this error or is there a patch fixing it?

**Comment by wohali** [comment]
Are you trying to use client certificates? If so, you need to include the signing CA public certificate in the file you're using. CouchDB (and Erlang) requires this "chained CA cert" file format.

Try this: https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=48203146

**Comment by greg2git** [comment]
k, let me try to play with the cert chains a little bit more. i don't see certbot in the page you have provided. is CouchDB compatible with ACME CA as explained in https://certbot.eff.org/lets-encrypt/ubuntubionic-apache?

**Comment by wohali** [comment]
If you include the signing CA public cert from LetsEncrypt, it should be fine. You have to include the full chain of certs all the way back to (and including) the CA.

**Comment by greg2git** [comment]
putting it on hold for now as there are too many CAs to really decide which will work best in the long run.
