### ISSUE TITLE
CouchDB refuses to start without a proper error

### ISSUE THREAD

**Issue by ceremcem** [apache/couchdb#1929]
## Description

I've 2 CouchDB installations in 2 LXC containers which worked fine for a long time. Then I copied and pasted the containers into another machine and run. The installation which has CouchDB@[d29011b11](https://github.com/apache/couchdb/commit/d29011b11) worked fine but the installation which has CouchDB 2.1.2~stretch refuses to start with `/etc/init.d/couchdb restart`. `/etc/init.d/couchdb status` gives the following clue (notice the "operation not permitted" line): 

```
# /etc/init.d/couchdb status
● couchdb.service - Apache CouchDB
   Loaded: loaded (/lib/systemd/system/couchdb.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-02-21 15:29:52 +03; 1s ago
 Main PID: 25593 (beam.smp)
    Tasks: 23 (limit: 4915)
   Memory: 22.4M
      CPU: 733ms
   CGroup: /system.slice/couchdb.service
           ├─25593 /opt/couchdb/bin/../erts-8.3.5/bin/beam.smp -K true -A 16 -Bd -- -root /opt/couchdb/bin/.. -progname couchdb -- -home /opt/couchdb -- -boot /opt/co…ig
           └─25623 erl_child_setup 1024

Feb 21 15:29:52 aktos-couch systemd[1]: couchdb.service: Failed to reset devices.list: Operation not permitted
Feb 21 15:29:52 aktos-couch systemd[1]: Started Apache CouchDB.
Feb 21 15:29:53 aktos-couch couchdb[25593]: [os_mon] memory supervisor port (memsup): Erlang has closed
Feb 21 15:29:53 aktos-couch couchdb[25593]: [os_mon] cpu supervisor port (cpu_sup): Erlang has closed
```

Manually starting CouchDB gives the following output:

```
# sudo -i -u couchdb /opt/couchdb/bin/couchdb
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
[os_mon] memory supervisor port (memsup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,couch_log,{{shutdown,{failed_to_start_child,couch_log_server,{{badmatch,{error,eacces}},[{couch_log_writer,init,0,[{file,\"src/couch_log_writer.erl\"},{line,42}]},{couch_log_server,init,1,[{file,\"src/couch_log_server.erl\"},{line,63}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,247}]}]}}},{couch_log_app,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,couch_log,{{shutdown,{failed_to_start_child,couch_log_server,{{badmatch,{error,eacces}},[{couch_log_writer,init,0,[{file,"src

Crash dump is being written to: erl_crash.dump...
```

...where `sudo find / -name "erl_crash.dump"` gives nothing.

**Comment by ceremcem** [comment]
The issue is caused by [the bug](https://github.com/ceremcem/smith-sync/issues/12) of the sync procedure. Creating and fixing the permissions for `/var/run/couchdb` and restarting the server fixes the problem. 

However, CouchDB should provide a proper error for this.

**Comment by raoyitao** [comment]
I ran couchdb 2.3.0 on redhat 7. 
I downloaded the RPM package and unzip it, execute the binary and also got this error. But I could not access /var/run. I found an option in default.ini there is default value (by official document)

[couchdb]
uri_file = /var/run/couchdb/couchdb.uri

I change the value, use another folder to place the file, but I still got the error while running couchdb.

**Comment by ceremcem** [comment]
@raoyitao Does this SO answer help you: https://stackoverflow.com/a/18416985/1952991

**Comment by raoyitao** [comment]
@ceremcem  this answer helps, I'm not an unprivileged user so I have to make changes to config files and change directories which CouchDB can writes to. for example, uri_file is no longer placed in /var/run, but I cannot get a full list of them,  I don't know which option specify the log path, or when /var/lib will be accessed, the official document does not include all of them. Unfortunately the page is missing: http://www.pastbedti.me/2009/04/running-couchdb-under-an-unprivileged-user-account/

BTW how to specify which config file will be used for couchDB? For example, as I decompressed the RPM package, I found ./bin/couchdb under ./opt/couchdb and I guess in this folder ./etc/default.ini and ./etc/local.ini are accessed by couchdb.

**Comment by wohali** [comment]
@raoyitao Our documentation is pretty comprehensive on this stuff:

http://docs.couchdb.org/en/latest/config/intro.html

@ceremcem THe error is indeed in what CouchDB is saying:

`{{badmatch,{error,eacces}}` is in your error output. That's a UNIX error, EACCESS, which means a permission problem.

This is also in our documentation:

https://docs.couchdb.org/en/latest/install/troubleshooting.html?highlight=eacces

**Comment by renebaudisch** [comment]
@wohali, perfect to know that there is a permission error ANYWHERE on my system. I should just take me a FEW lightyear to see where exactly...

**Comment by renebaudisch** [comment]
Just wanted to comment, that it would be nice to see a bit clearer what exactly the problem has been.
I haven't found a documentation on how to read this errors and still it is not precise and one still need to think about what to do, which permissions to check and so on. 

An additional hint like e.g "please ensure this folders/files have the needed permissions 755/644:" would be very nice in this situation...
