### ISSUE TITLE
PUT of multipart/related attachments should support Transfer-Encoding: chunked

### ISSUE THREAD

**Issue by flimzy** [apache/couchdb#1943]
My testing indicates that Transfer-Encoding: chunked causes the server to wait indefinitely, then issue a a 500 error when the client finally hangs up, when PUTing a multipart/related document + attachments.  To reproduce:

To reproduce (testing against CouchDB 2.3.0 official docker image):

```
curl -v -X PUT http://admin:abc123@localhost:6005/foo/oink \
    -H 'Content-Type: multipart/related;boundary="25d2c8595dc6d17e2c59cc97ad3db535428bf940ac8cd646d002171f2147"' \
    -H 'Transfer-Encoding: chunked' \
    --data "$(echo LS0yNWQyYzg1OTVkYzZkMTdlMmM1OWNjOTdhZDNkYjUzNTQyOGJmOTQwYWM4Y2Q2NDZkMDAyMTcxZjIxNDcNCkNvbnRlbnQtVHlwZTogYXBwbGljYXRpb24vanNvbg0KDQp7Il9hdHRhY2htZW50cyI6eyJmb28udHh0Ijp7ImNvbnRlbnRfdHlwZSI6InRleHQvcGxhaW4iLCJsZW5ndGgiOjEzLCJmb2xsb3dzIjp0cnVlfX0KLCJmZWV0Ijo0fQoNCi0tMjVkMmM4NTk1ZGM2ZDE3ZTJjNTljYzk3YWQzZGI1MzU0MjhiZjk0MGFjOGNkNjQ2ZDAwMjE3MWYyMTQ3DQoNCnRlc3QgY29udGVudAoNCi0tMjVkMmM4NTk1ZGM2ZDE3ZTJjNTljYzk3YWQzZGI1MzU0MjhiZjk0MGFjOGNkNjQ2ZDAwMjE3MWYyMTQ3LS0NCg== | base64 -d)"
```

## Desired Behaviour

The server ought to respond to the HTTP request, the same as if it were not sent using `Transfer-Encoding: chunked`

**Comment by wohali** [comment]
Confirmed on `master` (post 2.3.1) with the same command using `dev/run -n 1`. logfile shows:

```
[notice] 2019-03-12T17:51:03.030365Z node1@127.0.0.1 <0.909.0> 05a227bfb0 localhost:15984
127.0.0.1 undefined PUT /foo 202 ok 287
[error] 2019-03-12T17:51:37.839482Z node1@127.0.0.1 <0.1405.0> 16aaab9392 req_err(86628135
3) badmatch : ok
    [<<"chttpd_db:db_doc_req/3 L1029">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttp
d:process_request/1 L305">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:header
s/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[notice] 2019-03-12T17:51:37.840019Z node1@127.0.0.1 <0.1405.0> 16aaab9392 localhost:15984
 127.0.0.1 undefined PUT /foo/oink 500 ok 13094
```

**Comment by wohali** [comment]
@flimzy actually I'm not sure this is a valid test case. See:

https://curl.haxx.se/mail/archive-2004-12/0104.html

If you let curl do the chunking for you, does it do the right thing?

Your chunking process isn't including the length of the chunks which I think is invalid HTTP 1.1.

**Comment by flimzy** [comment]
I think I am letting curl do the chunking for me. Or am I misunderstanding your question?  If I omit the `Transfer-Encoding: chunked` header from the curl command, curl calculates the size of the upload, and includes the appropriate `Content-Length` header, which Couch accepts with no problem.

The curl commands are just to demonstrate a problem I discovered when working on my Go client, where wireshark confirmed that the length of chunks were most definitely being included.  I can re-produce that, and attach a packet capture if that's useful

**Comment by wohali** [comment]
@flimzy I'm not really sure what's going on here. I'm sure chunked transmission works between CouchDBs, but I don't know precisely how you're running into the issue. Did you ever get back to this, or just worked around it otherwise?

**Comment by ricellis** [comment]
I just ran into this issue as well, initially using my Java client, but reproduced in curl too.

The [mp-request.mp.gz](https://github.com/apache/couchdb/files/5666675/mp-request.mp.gz) file I'm using is the [docs example](https://docs.couchdb.org/en/stable/api/document/common.html#creating-multiple-attachments) but with only 1 of the attachments instead of both.

Curl multipart request that works (curl automatically adds the `Content-Length` header):
`curl -v -u 'admin:**' -X PUT -H 'Content-Type: multipart/related; boundary=abc123' -T mp-request.mp 'http://localhost:5984/test/testmp4'`
```
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 5984 (#0)
* Server auth using Basic with user 'admin'
> PUT /test/testmp4 HTTP/1.1
> Host: localhost:5984
> Authorization: Basic **==
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Type: multipart/related; boundary=abc123
> Content-Length: 373
> Expect: 100-continue
> 
* Done waiting for 100-continue
* We are completely uploaded and fine
< HTTP/1.1 201 Created
< Cache-Control: must-revalidate
< Content-Length: 70
< Content-Type: application/json
< Date: Wed, 09 Dec 2020 14:42:36 GMT
< ETag: "1-7ce5f48fde00bce2167f25fd04031e8e"
< Location: http://localhost:5984/test/testmp4
< Server: CouchDB/3.1.1 (Erlang OTP/20)
< X-Couch-Request-ID: 31cddc5df6
< X-CouchDB-Body-Time: 0
< 
{"ok":true,"id":"testmp4","rev":"1-7ce5f48fde00bce2167f25fd04031e8e"}
```

And curl request with added `Transfer-Encoding: chunked` header that hangs:
`curl -v --max-time 30 -u 'admin:**' -X PUT -H 'Transfer-Encoding: chunked' -H 'Content-Type: multipart/related; boundary=abc123' -T mp-request.mp 'http://localhost:5984/test/testmp3'`
```
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 5984 (#0)
* Server auth using Basic with user 'admin'
> PUT /test/testmp3 HTTP/1.1
> Host: localhost:5984
> Authorization: Basic **==
> User-Agent: curl/7.64.1
> Accept: */*
> Transfer-Encoding: chunked
> Content-Type: multipart/related; boundary=abc123
> Expect: 100-continue
> 
* Done waiting for 100-continue
* Signaling end of chunked upload via terminating chunk.
* Operation timed out after 30002 milliseconds with 0 bytes received
```

**Comment by bessbd** [comment]
Why didn't merging https://github.com/apache/couchdb/pull/3340 close this ticket?

**Comment by wohali** [comment]
Not sure...maybe cause it didn't land on `main`.
