### ISSUE TITLE
couchdb build error

### ISSUE THREAD

**Issue by shinningball** [apache/couchdb#1945]
[NOTE]: couchdb build failed

## Description

[NOTE]: # couchdb build failed

## Steps to Reproduce
1. download the source code with command:git clone -b master https://git.launchpad.net/couchdb
2. OS:ubuntu16.4
3.make failed and got the message as the following:
==> config (compile)
ERROR: OTP release 18 does not match required regex 19|20|21
ERROR: compile failed while processing /Linux/home3/cindylin/code/couchdb/couchdb/src/config: rebar_abort
Makefile:119: recipe for target 'couch' failed
make: *** [couch] Error 1

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment

* CouchDB Version used:
* Browser name and version:
* Operating System and version:

**Comment by jiangphcn** [comment]
Looks that you are using OTP 18. Please use 19 or later.

For details, please see https://github.com/apache/couchdb/pull/1833

**Comment by shinningball** [comment]
@jiangphcn After code comparison, the source code are the same with those modified files, but I still get the error described above. Thanks.

**Comment by jiangphcn** [comment]
what is your OTP version?

**Comment by wohali** [comment]
CouchDB no longer builds with Erlang 18. You need 19 or later.

This line says you are building with Erlang 18:

```
 ERROR: OTP release 18 does not match required regex 19|20|21
```

You can install newer versions of Erlang from http://packages.erlang-solutions.com/ or by compiling from source via http://erlang.org/ .

Sorry about that.
