### ISSUE TITLE
View is not updated after replication is completed.

### ISSUE THREAD

**Issue by trinhnguyense** [apache/couchdb#1946]
I installed 2 servers couchdb,
A machine as a master, a slave machine performs replication with a master machine.
I have created a view to get the latest data, on the master machine works well. But on slave machines, that view is still not updated.
View is accessed via the cradle on the project node.
When I access the view directly from the browser, the view is updated.
Now how to after the replication is complete, the view is automatically updated?

**Comment by wohali** [comment]
Views must be manually accessed once to trigger view building.

This will change with CouchDB 2.4.0 which will include an auto-view-builder called `smoosh`, but it will still take time to build a view.

If you join the nodes into a _cluster_, following the documentation, all views will update at once and all databases are internally synchronized. But this is not "master/slave" configuration.
