### ISSUE TITLE
Documentation on using ssl verify_fun

### ISSUE THREAD

**Issue by borigas** [apache/couchdb#1948]
First, sorry if this is a dumb question. I'm new to both couchdb and erlang.

I'm trying to configure SSL, but I need nodes to be accessible by IP. This makes certificate verification hard because Common Name isn't going to match an IP. Instead, I'm hoping to verify the cert by thumbprint. It looks like [verify_fun](https://docs.couchdb.org/en/latest/config/http.html#ssl/verify_fun) combined with someting like this [ssl_verify_fingerprint function](https://github.com/deadtrickster/ssl_verify_fun.erl/blob/master/src/ssl_verify_fingerprint.erl) is probably what I'm looking for, but I can't figure out how to use it. Is there documentation on how to use `verify_fun`? Thanks for your help!

**Comment by wohali** [comment]
Hi there,

This is not a CouchDB bug. GitHub is for actual CouchDB bugs only.

If you are looking for general support with using CouchDB, please try one of these other options:

* The user mailing list. Signup instructions are [here](http://couchdb.apache.org/#mailing-lists)
* The Slack/IRC chat room. Joining instructions are [here](http://couchdb.apache.org/#chat)

Sorry, and thanks for being an interested CouchDB user! :D
