### ISSUE TITLE
Couchdb replication error notification

### ISSUE THREAD

**Issue by bcyinc** [apache/couchdb#1954]
Hello Team, I am using 2 couchdb server, one as primary and the other one as secondary.
any change in primary , immediately replicates to secondary.
I want to notify my client by email if replication fails from primary to secondary (suppose any error occurs while replicating), is this possible? If yes, how to implement it?

please note that I am not bothered about whether data is replicated correctly or not. but I want to notify my client if replication encounters any error.

**Comment by kocolosk** [comment]
Hi @bcyinc there's no web hook or push notification, but there are endpoints you can poll. See http://docs.couchdb.org/en/stable/replication/intro.html#triggering-stopping-and-monitoring-replications
