### ISSUE TITLE
{os_process_error,{exit_status,139}} when push my webapp using couchapp

### ISSUE THREAD

**Issue by raoyitao** [apache/couchdb#1962]
OS: redhat 7
CouchDB: 2.3.0
Couchapp: 0.7.5

I downloaded the RPM package and unzip it, because I'm not a privileged user and is limited to some directory, so I modified local.ini to change the default derectories for uri_file, log file and database. Also I set LD_LIBRARY_PATH for monkeyspider and icu. Then I can directly start ./bin/couchdb, I can create database and documents by web UI or curl, seems it run properly.

But if I use couchapp to push my web application, it failed, on client side I got **RequestFailed: {"error":"unknown_error","reason":"undefined"}**, and on server side couchdb displayed error messages on console continuously:

_...
[info] 2019-03-04T07:34:54.100238Z couchdb@127.0.0.1 <0.226.0> -------- couch_proc_manager <0.9098.0> died normal
[error] 2019-03-04T07:34:54.100521Z couchdb@127.0.0.1 <0.7098.0> -------- OS Process Error <0.9098.0> :: {os_process_error,{exit_status,139}}
[info] 2019-03-04T07:34:54.141688Z couchdb@127.0.0.1 <0.226.0> -------- couch_proc_manager <0.9101.0> died normal
[error] 2019-03-04T07:34:54.141917Z couchdb@127.0.0.1 <0.7098.0> -------- OS Process Error <0.9101.0> :: {os_process_error,{exit_status,139}}
[info] 2019-03-04T07:34:54.189625Z couchdb@127.0.0.1 <0.226.0> -------- couch_proc_manager <0.9104.0> died normal
[error] 2019-03-04T07:34:54.189960Z couchdb@127.0.0.1 <0.7098.0> -------- OS Process Error <0.9104.0> :: {os_process_error,{exit_status,139}}
[info] 2019-03-04T07:34:54.232189Z couchdb@127.0.0.1 <0.226.0> -------- couch_proc_manager <0.9107.0> died normal
[error] 2019-03-04T07:34:54.232445Z couchdb@127.0.0.1 <0.7098.0> -------- OS Process Error <0.9107.0> :: {os_process_error,{exit_status,139}}
..._

I found trouble shooting about this in official document: http://docs.couchdb.org/en/stable/install/troubleshooting.html
However, after I **setenforce 0** and restart couchdb, it did not work. What happened to cause this error. By the way, as I use strace to view system calls I found it open /dev/tty with O_RDWR flag, but /dev/tty is not accessible.

**Comment by raoyitao** [comment]
Start couchdb with the following strace command, then I got continuous output.
----------------------------------------------------------
$ strace -f -e open ./bin/couchdb 2>&1 | grep RDWR

[pid 13110] open("/dev/tty", O_RDWR|O_NONBLOCK) = -1 ENXIO (No such device or address)
[pid 13111] open("/dev/tty", O_RDWR|O_NONBLOCK) = -1 ENXIO (No such device or address)
[pid 13110] open("/dev/tty", O_RDWR|O_NONBLOCK) = -1 ENXIO (No such device or address)
[pid 13111] open("/dev/tty", O_RDWR|O_NONBLOCK) = -1 ENXIO (No such device or address)
[pid 13114] open("/dev/tty", O_RDWR|O_NONBLOCK) = -1 ENXIO (No such device or address)
[pid 13115] open("/dev/tty", O_RDWR|O_NONBLOCK) = -1 ENXIO (No such device or address)
[pid 13114] open("/dev/tty", O_RDWR|O_NONBLOCK) = -1 ENXIO (No such device or address)
[pid 13115] open("/dev/tty", O_RDWR|O_NONBLOCK) = -1 ENXIO (No such device or address)

**Comment by janl** [comment]
this is an installation issue, your CouchDB installation can’t find or start the couchjs process, reasons for not being able to start it can be many, including bindings to libmozjs.

start by checking the path of the javascript view server and whether it points to the right place.

**Comment by raoyitao** [comment]
> this is an installation issue, your CouchDB installation can’t find or start the couchjs process, reasons for not being able to start it can be many, including bindings to libmozjs.
> 
> start by checking the path of the javascript view server and whether it points to the right place.

I'm new to couchDB, I 'm not clear what is javascript view server, do you mean that couchjs execuable? I think it's couchjs that caused the problem.

I found a similar issue: https://github.com/apache/couchdb/issues/1832
It was on archLinux due to ABI compatibility issue and has been fixed.

I tried the steps described in the post:
_$ ./bin/couchjs ./share/server/main.js
["reset"]
Segmentation fault (core dumped)_

I got a segment fault. And I traced it I got the following output:
_read(0, ["reset"]
"[\"reset\"]\n", 1024)          = 10
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x98} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault_

by "ldd -v./bin/couchjs" I saw that libmozjs and other library files can be found in my redhat. I don't know why couchjs cannot work.

**Comment by janl** [comment]
The segfault is the problem here, but I can’t help with debugging that.

**Comment by raoyitao** [comment]
> The segfault is the problem here, but I can’t help with debugging that.

I found another issue, I'm not sure if it cause that segfault.
I found something here: http://docs.couchdb.org/en/stable/install/troubleshooting.html

Use this to start up Erlang with the CouchDB libraries in its path:
**erl -env ERL_LIBS $ERL_LIBS:/path/to/couchdb/lib -couch_ini -s crypto**

In that Erlang shell, let’s check that the key libraries are running. 
_crypto:md5_init().
snappy:compress("gogogogogogogogogogogogogogo").
jiffy:decode(jiffy:encode(<<"[1,2,3,4,5]">>)).
q()._

It is OK for "crypto:md5_init()", but failed for the second command. I got:
_** exception error: undefined function snappy:compress/1_

This means I did not successfully install couchdb. Sure, I did not install it, by directly execute the binaries by adding env variables and changing couch config. I guess the CouchDB libraries was not found. But, Could you tell me what is **/path/to/couchdb/**lib ? Is it the path to "opt/couchdb/lib" or "opt/couchdb/lib/<some_directory>/priv ?

**Comment by raoyitao** [comment]
I got the solution. because the spidermonkey 1.8.5 library was built on old versioned linux, I download the latest binary for redhat 7 the set LD_LIBRARY_PATH to include it, then the couchjs could run. I think the issue is caused that libmozjs185 is built on a very old linux (redhat5). After solving this, my couchdb could work..


But I still cannot verify my couchdb as I run "**erl -env ERL_LIBS $ERL_LIBS:/path/to/erlang/lib:path/to/couchdb/lib -couch_ini -s crypto**",  **snappy:compress** and **jiffy:decode** does not work. I just tried setting ERL_LIBS to the crypto library extracted from RPM package, like this:
**erl -env ERL_LIBS $ERL_LIBS:my_home_dir/rpm/couchdb_el7/opt/couchdb/lib/crypto-3.7.4 -couch_ini -s crypto**

Then I got this:

Erlang/OTP 18 [erts-7.0] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

{"init terminating in do_boot",{undef,[{crypto,start,[],[]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump is being written to: erl_crash.dump...done
init terminating in do_boot ()

**Comment by wohali** [comment]
Likely your openssl version does not match the compiled version.

Why are you not just compiling from source? This installation method you are using is not supported.

**Comment by wohali** [comment]
Hi there,

This is not a CouchDB bug. GitHub is for actual CouchDB bugs only.

If you are looking for general support with using CouchDB, please try one of these other options:

* The user mailing list. Signup instructions are [here](http://couchdb.apache.org/#mailing-lists)
* The Slack/IRC chat room. Joining instructions are [here](http://couchdb.apache.org/#chat)
