### ISSUE TITLE
map/reduce queries fail when the GET URI is more than 1300 bytes long

### ISSUE THREAD

**Issue by dholth** [apache/couchdb#1965]
I'm having trouble with a CouchDB 2.3 GET request that fetches a bunch of keys from a view. If the URI is longer than 1300 bytes (plus 35 bytes for the schema/host/port) it fails. If it is 1300 bytes or fewer then it succeeds. I haven't set `max_uri_length` in the configs.

See also https://github.com/pouchdb/pouchdb/issues/7679

**Comment by rnewson** [comment]
please show steps to reproduce and/or some verbatim error response from couchdb. I can't reproduce this.

**Comment by dholth** [comment]
Will attempt. CouchDB appears to produce no log message for these dropped requests.

**Comment by wohali** [comment]
@dholth this is probably a duplicate of #1810, can you try the remediation listed there? 2.3.1 will fix the problem if that's what it is.

**Comment by dholth** [comment]
Thank you very much. That fixes the problem.
