### ISSUE TITLE
query servers install via env var only but docs state about [query_servers]

### ISSUE THREAD

**Issue by aogier** [apache/couchdb#1966]
Hello, I've just found out that in 2.3 the only way to configure a query server is via env vars, which is neat, but documentation and distributed local.ini are misleading in sense that they let persons think there is still an inifile way.

I'd like to suggest you to update documentation so it's more clear otherwise users can't relax :P

**Comment by rnewson** [comment]
Thou shalt read the release notes: https://docs.couchdb.org/en/stable/whatsnew/2.3.html#upgrade-notes

:)

B.

-- 
 Robert Samuel Newson
 rnewson@apache.org


On Tue, 5 Mar 2019, at 16:09, Alessandro Ogier wrote:
> Description

> Hello, I'm trying to install a query server on a local instance but so far no luck.

> I've dropped an inifile in `local.d`:

> [query_servers]
> python = /usr/bin/python3 /usr/local/bin/couchpy
> and running couchdb seems to give me a positive feedback about this:

> curl -sH 'Content-Type: application/json' \
  http://localhost:9999/_node/nonode@nohost/_config \
  | jq .query_servers

{
  "python": "/usr/bin/python3 /usr/local/bin/couchpy"
}
> but when I hit a view whose ddoc is:

> {
  "_id": "_design/dd",
  "_rev": "4-46dba025cd653009291b774ae5926444",
  "views": {
    "vv": {
      "map": "def map(doc):\n    yield(doc['_id'], 'pp')"
    }
  },
  "language": "python"
}
> server logs this:

> `[info] <0.16030.0> -------- Starting index update for db: shards/40000000-5fffffff/ciao.1551798662 idx: _design/dd
[error] emulator -------- Error in process <0.16035.0> with exit value: {{nocatch,{unknown_query_language,<<"python">>}},[{couch_query_servers,get_os_process,1,[{file,"src/couch_query_servers.erl"},{line,575}]},{couch_query_servers,start_doc_map,3,[{file,"src/couch_query_servers.erl"},{line,55}]},{couch_mrview_updater,start_query_server,1,[{file,"src/couch_mrview_updater.erl"},{line,235}]},{couch_mrview_updater,map_docs,2,[{file,"src/couch_mrview_updater.erl"},{line,188}]}]}
[error] <0.15987.0> 5cfdafc411 rexi_server: from: nonode@nohost(<0.15593.0>) mfa: fabric_rpc:map_view/5 throw:{unknown_query_language,<<"python">>}[{couch_mrview_util,get_view_index_state,5,[{file,"src/couch_mrview_util.erl"},{line,137}]},{couch_mrview_util,get_view,4,[{file,"src/couch_mrview_util.erl"},{line,81}]},{couch_mrview,query_view,6,[{file,"src/couch_mrview.erl"},{line,247}]},{rexi_server,init_p,3,[{file,"src/rexi_server.erl"},{line,140}]}]
[error] <0.15593.0> 5cfdafc411 req_err(4089041121) unknown_query_language : python
    [<<"couch_mrview_util:get_view_index_state/5 L137">>,<<"couch_mrview_util:get_view/4 L81">>,<<"couch_mrview:query_view/6 L247">>,<<"rexi_server:init_p/3 L140">>]
[notice] <0.15593.0> 5cfdafc411 localhost:9999 172.17.0.1 undefined GET /ciao/_design/dd/_view/vv?reduce=false&skip=0&limit=21 500 ok 6

`
> Can't get any clue from documentation (which is very little, in fact I've copied inifile snippet from vanilla local.ini) nor online, but that `unknown_query_language` let me think something is still wrong.

> Can you please give me a pointer I can't find by myself?

> Your Environment

> couchdb 2.3.0 dockerhub's image

> curl -sH 'Content-Type: application/json' \
  http://localhost:9999/ \
  | jq

{
  "couchdb": "Welcome",
  "version": "2.3.0",
  "git_sha": "07ea0c7",
  "uuid": "36f4f3fa844df0434a60b28a6fd3704d",
  "features": [
    "pluggable-storage-engines",
    "scheduler"
  ],
  "vendor": {
    "name": "The Apache Software Foundation"
  }
}

**Comment by aogier** [comment]
you're right, my bad, I started with this one so I just read the manual. Sorry for the noise, ciao!

**Comment by wohali** [comment]
@aogier We're very much accepting pull requests for the docs over at https://github.com/apache/couchdb-documentation if you'd like to help out! :)
