### ISSUE TITLE
CouchDB download still links to 2.3.0 rather than 2.3.1

### ISSUE THREAD

**Issue by badbod99** [apache/couchdb#1973]
## Description

Download link at http://couchdb.apache.org/ points to 2.3.0 even though 2.3.1 has been released and documentation has been updated for 2.3.1.  I can't actually find the 2.3.1 download anywhere.

## Steps to Reproduce

Go to http://couchdb.apache.org/ and click "Download".

## Expected Behaviour

2.3.1 download to be listed.

**Comment by wohali** [comment]
2.3.1 is not officially released - please wait another 24-48 hours and watch the mailing lists for the announcements.
