### ISSUE TITLE
Replication secure base with proxy.

### ISSUE THREAD

**Issue by pavellzubkov** [apache/couchdb#1975]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )
Wrong auth addres by using couchdb with nginx reverse proxy.

## Description

for example nginx conf:  
> 
(i using docker image couchdb docker local net addres "db")
```
location /couch {
	rewrite /couch/(.*) /$1 break;
    proxy_pass http://db:5984;
    proxy_redirect off;
    proxy_buffering off;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```
replicator doc:
```
...
  "source": {
    "url": "https://mysite.com/couch%2Fnew_base",
    "headers": {
      "Authorization": "Basic YWRtaW46Q291Y2hkYjA2OTA1OA=="
    }
  },
  "target": {
    "url": "http://localhost:5984/new_base",
    "headers": {
      "Authorization": "Basic YWRtaW46YWRtaW4="
    }
...
```
local (target) base send auth PUT to "/_session" after starting

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Steps to Reproduce

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour
local (target) base should send auth request to "/couch/_session" or "/couch/new_base/_session"

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB Version used: 2.3.0
* Browser name and version: any
* Operating System and version: windows, linux

## Additional context

[TIP]:  # ( Add any other context about the prbolem here. )

i solved problem by add additional redirect block to nginx conf but it wrong behaviour: 
```
...
location /_session {
	#rewrite /couch/(.*) /$1 break;
    proxy_pass http://db:5984/_session;
    proxy_redirect off;
    proxy_buffering off;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

}
...
```
Note: **replication task can work only with admin auth**

**Comment by paulbert** [comment]
We're experiencing the same issue. We are using the same version of CouchDB in addition to Docker and nginx

* Docker: https://hub.docker.com/r/apache/couchdb & https://hub.docker.com/r/treehouses/couchdb (based off official Apache container for use with ARM or x86)
* Nginx: 1.13 & 1.14

We also dug a little into the logs to see the CouchDB is failing with an auth error:
```
{"timestamp":"2019-03-07T05:18:13Z","type":"crashed","reason":"{replication_auth_error,\n {session_unexpected_result,\"405\",\n \"https://<serverurl>/_session\",\"<admin>\"}}"}
```
The <serverurl> section does not include the proxy address (in the above example `/couch`)

**Comment by wohali** [comment]
We've solved this as a documentation issue:

https://github.com/apache/couchdb-documentation/pull/399
