### ISSUE TITLE
couchddb is not working through public ip.

### ISSUE THREAD

**Issue by sbcsuman** [apache/couchdb#1976]
Hi Team,
I installed couchdb successully in ubuntu(AWS). After that i change defult.ini and local.ini files 
127.0.0.1 to 0.0.0.0 
Then couchdb is connected through public ip yesterday. now today i am checking its not connected. what is the issue. Could you please help me this issue

**Comment by wohali** [comment]
@sbcsuman 

Hi there,

This is not a CouchDB bug. GitHub is for actual CouchDB bugs only.

If you are looking for general support with using CouchDB, please try one of these other options:

* The user mailing list. Signup instructions are [here](http://couchdb.apache.org/#mailing-lists)
* The Slack/IRC chat room. Joining instructions are [here](http://couchdb.apache.org/#chat)

**Comment by tewedaj** [comment]
did you ever solve this issue ?

**Comment by big-r81** [comment]
> did you ever solve this issue ?

Hi @tewedaj, this is an old issue and I can only repeat what Joan already said.

> If you are looking for general support with using CouchDB, please try one of these other options:
>
>    The user mailing list. Signup instructions are [here](http://couchdb.apache.org/#mailing-lists)
>    The Slack chat room. Joining instructions are [here](http://couchdb.apache.org/#chat)

If you have support questions, you know now what to do next, if you found a bug, create a (more detailed) bug report please.
