### ISSUE TITLE
Auto-create system databases at startup IF configured for "single node mode"

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#1977]
## Summary

We keep getting requests for CouchDB to "just work" for single-node, standalone installations. Auto-creating all of the system databases on startup for new installs of this is a common request.

## Desired Behaviour

1. Specify somewhere in the config that this is a single-node install.
1. Upon seeing that at startup, if they don't exist, create the system databases automatically, at least `_users`, `_replicator`, if not also `_global_changes`.

## Possible Solution

Add a new config file setting such as `[couchdb] standalone=true`.

## Additional context

c/f https://github.com/apache/couchdb-docker/issues/142

**Comment by piyush0609** [comment]
@wohali Is this issue still opened? I would like to pick this up.

**Comment by wohali** [comment]
@piyush0609 If you want to dig into it, sure.

Keep in mind we're looking for a solution in Erlang with this request, and that the submitted PR must have both positive and negative test cases along with it.

**Comment by piyush0609** [comment]
@wohali Thanks. Will submit a PR soon with the points mentioned above.

> @piyush0609 If you want to dig into it, sure.
> 
> Keep in mind we're looking for a solution in Erlang with this request, and that the submitted PR must have both positive and negative test cases along with it.

**Comment by piyush0609** [comment]
@wohali I am little confused here. What I understood here is that default installation will be a single node install and if the user wants to switch it to clustered mode he can do it from the admin interface.
Can you please clarify this?

**Comment by wohali** [comment]
@piyush0609 That's not possible.

The problem is that creation of the system databases must occur **after** nodes are joined together in a cluster.

"Configuring a node for single-node mode" means basically creating the system databases right away, on initial startup. If you do this prior to joining nodes together in a cluster, you **prevent** that node from being moved into a cluster configuration without a very error-prone and intensively manual effort.

However, if a node is effectively unconfigured, it can go either way - it can become a single node, or it can be joined into a cluster. Either way, you create the system databases after all of this is done.

So your approach cannot be applied without breaking cluster installation for everyone who needs it.

This is why our Debian package asks you on install which one you want - and does the necessary steps.

To move this inside the Erlang core, the proposed approach is to look for a manually-added line in the configuration file as the trigger to create these system databases.

**Comment by iilyak** [comment]
Just an idea: Instead of introduction of a new option we could try using #1658. We might check how many nodes are configured in a seed list and create databases if it is a single node install.
```
[cluster]
seedlist = couchdb@localhost
```

**Comment by AGrzes** [comment]
Hello - I have submitted [PR](https://github.com/apache/couchdb/pull/2296) that (I hope) address the issue. It is my first contribution to CouchDB so it may be entirely wrong direction of change. Could anybody take look at the proposed change and tell me if it need anything more - or it is a miss altogether?
