### ISSUE TITLE
Error 500 when no basic auth credentials passed

### ISSUE THREAD

**Issue by danielszot** [apache/couchdb#1982]
I get 500 HTTP error response when I try to request anything without basic auth credentials passed by URL.

## Steps to Reproduce

Request without credentials: `curl localhost:5948/_up -v`
Incorrect response:
```
* TCP_NODELAY set
* Connected to localhost (::1) port 5948 (#0)
> GET /_up HTTP/1.1
> Host: localhost:5948
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Cache-Control: must-revalidate
< Content-Length: 58
< Content-Type: application/json
< Date: Mon, 18 Mar 2019 11:11:41 GMT
< Server: CouchDB/2.3.0 (Erlang OTP/19)
< X-Couch-Request-ID: 0f85ee75b9
< X-Couch-Stack-Hash: 2393520390
< X-CouchDB-Body-Time: 0
< 
{"error":"case_clause","reason":"False","ref":2393520390}
* Connection #0 to host localhost left intact
```

Log message:
```
[error] 2019-03-18T10:49:51.077220Z couchdb@dms-v1-prod-couchdb-0.dms-v1-prod-couchdb.default.svc.cluster.local <0.1357.0> 6f83030ec5 req_err(2393520390) case_clause : False
    [<<"chttpd_auth:party_mode_handler/1 L55">>,<<"chttpd:authenticate_request/2 L531">>,<<"chttpd:process_request/1 L301">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
[notice] 2019-03-18T10:49:51.077716Z couchdb@dms-v1-prod-couchdb-0.dms-v1-prod-couchdb.default.svc.cluster.local <0.1357.0> 6f83030ec5 localhost:5948 127.0.0.1 undefined GET / 500 ok 1
```

Request with bad credentials: `curl bad_user:bad_pass@localhost:5948/_up -v`
Correct response (consistent with the docs):
```
* TCP_NODELAY set
* Connected to localhost (::1) port 5948 (#0)
* Server auth using Basic with user 'a'
> GET /_up HTTP/1.1
> Host: localhost:5948
> Authorization: Basic YTph
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< Cache-Control: must-revalidate
< Content-Length: 67
< Content-Type: application/json
< Date: Mon, 18 Mar 2019 11:11:17 GMT
< Server: CouchDB/2.3.0 (Erlang OTP/19)
< X-Couch-Request-ID: 8fa0cea019
< X-CouchDB-Body-Time: 0
< 
{"error":"unauthorized","reason":"Name or password is incorrect."}
* Connection #0 to host localhost left intact
```

Request with correct credentials: `curl correct_user:correct_pass@localhost:5948/_up -v`
Correct response (consistent with the docs):
```
* TCP_NODELAY set
* Connected to localhost (::1) port 5948 (#0)
* Server auth using Basic with user 'correct_user'
> GET /_up HTTP/1.1
> Host: localhost:5948
> Authorization: Basic ***
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Cache-Control: must-revalidate
< Content-Length: 27
< Content-Type: application/json
< Date: Mon, 18 Mar 2019 11:10:28 GMT
< Server: CouchDB/2.3.0 (Erlang OTP/19)
< X-Couch-Request-ID: 6375e9098e
< X-CouchDB-Body-Time: 0
< 
{"status":"ok","seeds":{}}
* Connection #0 to host localhost left intact
```

## Expected Behaviour

Request without credentials: `curl localhost:5948/_up -v`
Expected response:
```
...
< HTTP/1.1 401
...
{"error":"unauthorized","reason":"You are not a server admin."}
```

## Your Environment

Ini file put to the /opt/couchdb/etc/default.d (ConfigMap as a source for volume of configMap type mounted to the container in given path):
```ini
[cluster]
q = 9
n = 2
[chttpd]
bind_address = any
require_valid_user = False
```

`curl correct_user:correct_pass@localhost:5948/ | jq` response:
```json
{
  "couchdb": "Welcome",
  "version": "2.3.0",
  "git_sha": "07ea0c7",
  "uuid": "9720f1c415e1674e4a6c5448dc093242",
  "features": [
    "pluggable-storage-engines",
    "scheduler"
  ],
  "vendor": {
    "name": "The Apache Software Foundation"
  }
}
```

* CouchDB Version used: 2.3.0, tested also on 2.2.0 and 2.1 (same behaviour)
* Browser name and version: curl/7.54.0
* Operating System and version: Ubuntu 18.04

## Additional context

CouchDB 2.3.0 working in 3 nodes cluster inside Kubernetes cluster. Host OS of Kubernetes nodes is Ubuntu 18.04. Data volumes are mounted to the containers as PersistentVolumes, storage behind a dedicated storage class is local disk.

**Comment by wohali** [comment]
@danielszot Can you look in your couch logfile and grep for the number `2393520390`? There should be a traceback around there that we can go on.

This could be a misconfiguration, or it could be a bug, we need the log entries to know more.

**Comment by danielszot** [comment]
@wohali I hope and assume this is misconfiguration, sorry for assigning bug label. Should be "help needed" rather.

I changed log level by adding:
```ini
[log]
level = debug
```
to configuration.

I can see messages with `[debug]` prefix in the logs. Nevertheless, after grep through log messages this is the only messages I get:

```bash
kubectl logs dms-v1-prod-couchdb-0 --container couchdb | grep -A 1 2393520390
```
```
[error] 2019-03-18T15:05:17.625875Z couchdb@dms-v1-prod-couchdb-0.dms-v1-prod-couchdb.default.svc.cluster.local <0.2949.0> 99d6944193 req_err(2393520390) case_clause : False
    [<<"chttpd_auth:party_mode_handler/1 L55">>,<<"chttpd:authenticate_request/2 L531">>,<<"chttpd:process_request/1 L301">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
--
[error] 2019-03-18T15:05:33.438952Z couchdb@dms-v1-prod-couchdb-0.dms-v1-prod-couchdb.default.svc.cluster.local <0.2949.0> dcb4734e1d req_err(2393520390) case_clause : False
    [<<"chttpd_auth:party_mode_handler/1 L55">>,<<"chttpd:authenticate_request/2 L531">>,<<"chttpd:process_request/1 L301">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
--
[error] 2019-03-18T15:05:37.033135Z couchdb@dms-v1-prod-couchdb-0.dms-v1-prod-couchdb.default.svc.cluster.local <0.2949.0> 134c36c418 req_err(2393520390) case_clause : False
    [<<"chttpd_auth:party_mode_handler/1 L55">>,<<"chttpd:authenticate_request/2 L531">>,<<"chttpd:process_request/1 L301">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L128">>,<<"proc_lib:init_p_do_apply/3 L247">>]
--
```

**Comment by wohali** [comment]
The [line that's being reported as an error here](https://github.com/apache/couchdb/blob/master/src/chttpd/src/chttpd_auth.erl#L55) is the line that fetches your

```
[chttpd]
require_valid_user = false
```

from the config file. You have a capital `False` in there. Make that `false` and the problem will go away.

For better or worse, Couch has made a project decision not to relax handling input on these types of things, so I'll close this as resolved. Hope it solves your problem!

**Comment by danielszot** [comment]
Thank you, it helped, now everything works correctly. 

This was just because I use Ansible to generate that config file based on variables and template file and by default boolean values starts from capital letter in Ansible.
