### ISSUE TITLE
Best Practices for blue-green clusters in production (with external replication clients)

### ISSUE THREAD

**Issue by irishmark** [apache/couchdb#1987]
Hi all,
We have implemented a blue-green system for our production couchDB clusters.
We need to have an offline cluster so that we can migrate data to an offline one and then switch the load balancer's DNS after the migration has completed.
Our nodes in (say) the blue cluster will be named node[0-3]-blue.domain.com and in the other one they are node[0-3]-green.domain.com. We have already observed that there is a problem with the shard maps and we have a script which; when bringing up a new blue cluster on a backup that was taken from green, then before we bring the blue cluster up we remap the shard map on each host, then we start it.

This works acceptably, the DB seems to be consistent, however our problem is that it appears to break the replication sequence with our external clients (i.e. phones). When they call using the lastSEQ obtained from the previous cluster they see a rewind (though for some reason it's not a full rewind, but is only a partial one, about 70-90% back)
With the logging in 2.3.0 we can see why, it is looking for the previous UUID and hostnames of the previous cluster (I guess these are encoded in the hash or something?)

So, it looks like the UUID might be straightforward, we can take a note of the UUID of the node as we take a backup and I guess we can set them when we bring up the new nodes.

The hostnames are more of a problem however as the only way to have matching hostnames for the nodes in two running clusters (for us in an AWS env) seems to be to have them in separate VPCs, which frankly is too far for me to ask our OPS guys to take this.

So, my questions are - is this possible at all? am I doing something crazy? how else do people prevent downtime to their clusters, yet prevent breaking the replication sequence with clients?

Will setting the UUIDs of the nodes prevent the replication sequences becoming broken?

Is there a recommended way of having an offline cluster in the same environment? Without breaking the replication sequence?

Thanks in advance for any help

**Comment by irishmark** [comment]
It looks like the answer to this might be to perform a search and replace on the _local shard-sync documents on all the nodes when starting a new cluster on new hostnames. Setting the server UUID on the servers didn't seem to help much as far as I could see

**Comment by rnewson** [comment]
All nodes in the blue cluster should have the same UUID, All nodes in the green cluster should have the same UUID, but the blue UUID should not be the same as the green UUID.

The ordering of documents in each cluster will not be the same, so you absolutely cannot make the same 'seq' value mean the same thing for both clusters.

So, yes, you are doing something crazy. 

-- 
 Robert Samuel Newson
 rnewson@apache.org
