### ISSUE TITLE
CouchDB heavy storage consumption

### ISSUE THREAD

**Issue by dilushan** [apache/couchdb#1994]
We have a project that involved with a database sync with pouchdb in mobile devices. We have faced issue when updating multiple documents (8400 docs per minute), internal storage increasing (around 20MB per minute) frequency.
We figured one main reason for that couchdb revisions. So we decided to decrease database rev_limit to around 5. But we heard it may impact replication process between couchdb and pouchdb. So how this decrease of revision limit impact to the replication process?

And figured out views taking more space than normal document storage. Is there any way to reduce couchdb view size?

I have refered to [this](https://github.com/apache/couchdb/issues/1621) problem also and found out we don't have local documents issue

**Comment by rnewson** [comment]
Reducing revs_limit causes replication issues, yes. If a common ancestor of an update cannot be found then a new branch is created (this is another way of saying a conflict is created), so we don't recommend changing revs limit at all.

You didn't mention how frequently you are compacting the databases and the views. compaction is the only operation that recovers disk space.

-- 
 Robert Samuel Newson
 rnewson@apache.org

**Comment by wohali** [comment]
@dilushan

This is not a CouchDB bug. GitHub is for actual CouchDB bugs only.

If you are looking for general support with using CouchDB, please try one of these other options:

* The user mailing list. Signup instructions are [here](http://couchdb.apache.org/#mailing-lists)
* The Slack/IRC chat room. Joining instructions are [here](http://couchdb.apache.org/#chat)
