### ISSUE TITLE
Is it possible to disable a user in a one db per-user schema?

### ISSUE THREAD

**Issue by tudordumitriu** [apache/couchdb#1995]
Hi 
Is it possible to disable / enable back an user (restricting login) if we are using Cookie authentication for a per-user db configuration.

## Summary

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

## Desired Behavior

Ideally there could be a 'disabled' field in the user document in _users db, and that to be considered in authentication handler, hence the login would be rejected, ideally with an specific error code. Of course this could be controlled via other processes or as the admin.

## Possible Solution

There are few options, but we wouldn't like to get to it unless it's strictly necessary:
1. Writing a custom httpd_auth that will take the disabled field into account and configuring it instead of cookie default handler - but is in erlang and we would have to constantly keep it up to date
2. Using Proxy Authentication - but that is not ideal as well, since we would have to manage the authentication separately, and the user base (accounts and passwords), and this also means that the ENTIRE traffic wold have to be routed through the reverse proxy, and we are afraid this would be a scalability issue, especially if we're to migrate to a cloud solution.

## Additional context
We're using CouchDB with PouchDB, continuous replication

**Comment by wohali** [comment]
@tudordumitriu The easiest is to change the password in the `_users` database. This will lock that user out until the password is changed again.

If that is unacceptable, a disabled flag is an enhancement request.

**Comment by rnewson** [comment]
Maybe a similar trick to how unix/linux accounts are disabled? Add a character to the front of password_sha (or derived_key) that cannot appear in any possible output of the hashing process. I think we convert to hex, so there are plenty of options, but `!` would do it. Re-enable by removing it.

**Comment by tabeth** [comment]
@rnewson @wohali 

By no means am I a regular maintainer of CouchDB, but it sounds like this particular issue would be resolved best by adding some documentation explaining to users how they would "disable" a user using one of the methods described above. 

The only thing then that would be needed would be the returning of a special error code, but that could be done perhaps on the client side? If done on the `derived_key` the client could manually inspect the derived key for the disable character, e.g. `!`, and manually show an error with the correct message to the user.

**Comment by BananaAcid** [comment]
How is couchdb restricting users on _users to be only to see their own doc? That seems to be specific for checking a doc.

Is that handling transferable to be doing a check on a users doc's property?

**Comment by wohali** [comment]
I'm going to close this issue as a documentation workaround issue.

@tabeth Yes, if you'd like to document this as a workaround with a PR against the couchdb-documentation repo, that'd be great. We'd welcome your contribution!

@BananaAcid Not easily, no, but if you want to dig in, the code's under the chttpd_auth_cache somewhere.
