### ISSUE TITLE
Unable to retrieve or update shard-sync _local documents

### ISSUE THREAD

**Issue by irishmark** [apache/couchdb#1996]
Using CouchDB 2.3.0:
According to the docs here - https://docs.couchdb.org/en/stable/api/local.html
It states that we can use the key/id to retrieve and update _local documents.

When I call for /{db}/_local_docs I get two sets of documents returned, one is view related (key contains "purge-mrview") the other type of document contains "shard-sync"

The first type of document containing "purge-mrview" can be retrieved via their id value, but the second type always return 404.

Is there any way to obtain and modify these local documents? (the ones with "shard-sync" in the key) 
(I am interested in modifying these documents to work around the problem documented here - https://github.com/apache/couchdb/issues/1987

**Comment by irishmark** [comment]
Closing this cos it turned out that some of the docs do exist and are editable, I just had a load of missing ones in my DB

**Comment by nickva** [comment]
shard-sync documents are used by the internal replicator to sync shard content between shard copies they are not written at the cluster level so don't follow the cluster document hashing rules where the document id is hashed and sent to a particular shard range based on that. That explains why when you make request you might see different subsets of them depending on which shard copies respond to your requests.

**Comment by wohali** [comment]
@nickva the trick is that I think if someone re-names or replaces a node during a shard split/sync, there needs to at least be some sort of doc that explains how to clean-up after the fact.
