### ISSUE TITLE
Endpoint to get name of current node

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#2005]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary & Desired Behaviour

I'd like to be able to `GET /...` some URL and get the name of the current node, as specified in vm.args.

## Possible Solution

How about just `GET /_node/_local` as the endpoint that returns the name of that node?

## Additional context

Automated monitoring and discovery of a cluster. We have the `/_membership` endpoint but this might expose IP addresses or hostnames we don't have access to from the point of inquiry.

**Comment by rnewson** [comment]
"current node" confused me. All you seem to be asking for is an endpoint that exposes the erlang node name of the node you've contacted?

**Comment by rnewson** [comment]
If so, I'm -0 on the idea but I'd at least like a config option to disable the endpoint.

**Comment by wohali** [comment]
@rnewson It's admin only, as is everything under `/_node`. Does that help?

**Comment by rnewson** [comment]
ah, yes, that helps. :)
