### ISSUE TITLE
No DB shards could be opened after backup restore 

### ISSUE THREAD

**Issue by ghobakhloum** [apache/couchdb#2010]
To backup db, files under shards folder are compressed and moved, to restore decomressing and replacing *.couch files, but after restore we get "No DB shards could be opened"

and it wont work until couchdb gets restarted

## Expected Behaviour

after restoring shards file, user must be able access the db through url

## Your Environment

linux ubunto

**Comment by wohali** [comment]
Hi there,

This is not a CouchDB bug. GitHub is for actual CouchDB bugs only.

If you are looking for general support with using CouchDB, please try one of these other options:

* The user mailing list. Signup instructions are [here](http://couchdb.apache.org/#mailing-lists)
* The Slack/IRC chat room. Joining instructions are [here](http://couchdb.apache.org/#chat)
