### ISSUE TITLE
selector filter in _changes API not using indexed search

### ISSUE THREAD

**Issue by subin1011** [apache/couchdb#2013]
Working on Database with more than 3.5 lakhs documents
## Description
When passing Selector query params to `POST /_changes?filter=_selector` API it is taking more than 600K ms to give the response where as `GET /_changes` API is taking less the 2 minutes

The same Selector query params when passed to `POST /_find`  gives result in 500 ms. The Selector query used is indexed.

After trying different approaches now I'm getting a feeling that selector query used in _changes API is not doing a indexed search.

## Steps to Reproduce

1) Run Couchdb in Docker
2) Create a database and create more that 3 Lakhs documents in it
3) curl the API
	POST {{db_name}}/_changes?filter=_selector

	Request Body
    {
        "selector": {
            {{any indexed query}}
        }   
    }
[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Current Behaviour
Taking more than 10 minutes to give response
## Expected Behaviour
Should take same time as `POST /_find` API ie., less than 1 second

* CouchDB Version used: 2.3.0

Would like to know if there is any way to speed up _changes API using selector filter.

Thanks.

**Comment by wohali** [comment]
That is correct, @subin1011 , there is no way to filter a `_changes` feed on a precalculated secondary index. This is currently technically infeasible given the design of CouchDB. Sorry about that.

What's a Lakh?

Mango selectors are faster than JavaScript functions for filtering a changes feed, but you could try one for comparison.

Remember that the way the _changes feed works is that it starts from the very first revision and runs the _selector against each version in turn. The sooner it finds a match, the sooner it returns a response. So in your case, you must have lots of revisions of documents that do not get selected by your selector. If you widen your selector to match all documents, you'll see that responses start coming much faster.

**Comment by subin1011** [comment]
Thank you @wohali.

Please correct me if I am wrong. The changes feed filters never uses indexed search but instead run the _selectors or _views against each change sequence in the database, making the response time proportional to the number of changes happening in that database ?

BTW, a Lakh equals hundred thousand.

**Comment by wohali** [comment]
Correct. There is no way to use a secondary index (JavaScript or Mango) to pre-filter a changes feed. Sorry.

For a detailed technical explanation as to why, see #592 and #831, and [this mailing list thread](https://lists.apache.org/thread.html/516793df0c1913c045441d0ff78339f307e2aff517d9223da44edd9e@%3Cdev.couchdb.apache.org%3E).
