### ISSUE TITLE
Option to enforce basic auth for all request?

### ISSUE THREAD

**Issue by viane** [apache/couchdb#2017]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

By looking this [doc](https://docs.couchdb.org/en/2.3.1/intro/security.html) looks like with admin account authentication, regular `GET` document from a custom DB will not be basic auth secured. Is there a way to configure such that apply basic auth for every request regardless the type of request? 

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

## Desired Behaviour
Either from a global switch to override which kind request should have basic auth enabled or have an option when user creating the DB to say if this DB should be protected with x type of request...
[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )
![Screen Shot 2019-04-26 at 10 52 24 AM](https://user-images.githubusercontent.com/4284629/56816575-c9bf4900-6811-11e9-91e7-67fb8b263217.png)

vs

![Screen Shot 2019-04-26 at 10 52 41 AM](https://user-images.githubusercontent.com/4284629/56816596-d5ab0b00-6811-11e9-92e8-77a78fb22912.png)
![Screen Shot 2019-04-26 at 10 53 33 AM](https://user-images.githubusercontent.com/4284629/56816597-d5ab0b00-6811-11e9-994c-2c23f237bcb6.png)
![Screen Shot 2019-04-26 at 10 53 49 AM](https://user-images.githubusercontent.com/4284629/56816598-d5ab0b00-6811-11e9-8f36-e30f48479f47.png)

**Comment by wohali** [comment]
Try `require_valid_user`.

https://docs.couchdb.org/en/2.3.1/config/auth.html?highlight=require_valid_user#chttpd/require_valid_user

If this does not meet your needs, let me know and we can reopen this ticket.
