### ISSUE TITLE
Uncaught Syntax Error

### ISSUE THREAD

**Issue by eagles051387** [apache/couchdb#2022]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

uncaught syntax error message in consol comes up when i create a new document. I am on version 2.3.1 of couchdb and fauxton this results in not being able to create the new document

## Steps to Reproduce

open the list of databases and click create new document. as soon as it brings up the json editor is when the error appears

## Expected Behaviour

It is expected that the document gets created with out any issues

## Your Environment

* CouchDB Version used: 2.3.1
* Browser name and version: chrome version 73 64bit
* Operating System and version: windows 10 64bit accessing remote server which is latest fully up to date version of centos 7

## Additional context

I tested the above on firefox and firefox doesnt have this issue at all. said issue seems to be limited to chrome.

**Comment by garrensmith** [comment]
Can you move this to the couchdb-fauxton repo


________________________________

**Comment by wohali** [comment]
No test case, please reopen at https://github.com/apache/couchdb-fauxton/
