### ISSUE TITLE
CouchDB 2.3.1: Reduce function raised exception (new TypeError("template.metaData is undefined", "undefined", 10))

### ISSUE THREAD

**Issue by nsthakur7** [apache/couchdb#2024]
[NOTE]: # Using CouchDb 2.3.1 - Getting TypeError in "Reduce function (custom)" while fetching child fields e.g. _doc.metaData.SomeDateField, however works fine in "Map" Function. Same reduce function works fine in CouchDB 1.6

## Description
We have recently upgraded to CouchDb 2.3.1 from CouchDb 1.6 and facing issue with one of the view which uses reduce function (custom), however same view works as expected in CouchDb 1.6.

In the view's reduce function, when we are fetching second level child fields, we get the following error in the couch log:
[info] 2019-05-03T06:01:46.097000Z couchdb@localhost <0.2402.0> -------- OS Process #Port<0.8540> Log :: function raised exception (new TypeError("template.metaData is undefined", "undefined", 10))

[NOTE]: # ( View doesn't return any couch documents in the result)
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Steps to Reproduce
1. Create a view 
2. Define map function as below:
`function(doc) {
    if (doc.$doctype !== 'someTemplate')
        return;
    emit([doc.metaData.fieldId1,//this line works i.e. getting fieldId1 from metaData field
            doc.metaData.fieldId2,
            doc.field3,
            doc.templateTypeX,
            doc.templateName.toLowerCase()
    ], doc);
}`
3. Define reduce function as below:
`function(keys, values, rereduce) {
    var mostRecentTemplate = null;
  

    values.forEach(function (template) {
        if (mostRecentTemplate == null 
|| Date.parse(mostRecentTemplate.templateDate) < Date.parse(template.metaData.fieldId2)) {
            mostRecentTemplate = {
                'templateType': template.templateTypeX,
                'templateName': template.templateName,
                'templateDate': template.metaData.fieldId2  //this line causing issue              
            };
        }
    });

    if (mostRecentTemplate && mostRecentTemplate.someAppState === -1) {
        mostRecentTemplate = null;
    }
    
    return mostRecentTemplate;
}`

4. Run the view query
5. No document returned received null for each key.

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour
Return the document template created in custom "reduce" function for the view.

[NOTE]: # (custom reduce function should work as it is working in CouchDB version 1.6)

## LOCAL Dev Machine

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( `{
    "rows": [
        {
            "key": [
                "XXX001",
                11222,
                "989878799",
                "AllCategoriesTemplate",
                "ak"
            ],
            "value": null
        },
        {
            "key": [
                "XXX001",
                11222,
                "989878799",
                "AllCategoriesTemplate",
                "littleton, co"
            ],
            "value": null
        },
        {
            "key": [
                "XXX001",
                11222,
                "989878799",
                "AllCategoriesTemplate",
                "nv"
            ],
            "value": null
        },
        {
            "key": [
                "XXX001",
                11222,
                "989878799",
                "AllCategoriesTemplate",
                "wa"
            ],
            "value": null
        },
        {
            "key": [
                "XXX001",
                11222,
                "989878799",
                "AllCategoriesTemplate",
                "wy"
            ],
            "value": null
        }
    ]
}`)

* CouchDB Version used: 2.3.1
* Browser name and version: Chrome
* Operating System and version: Windows 10

## Additional context
Here is how couch document looks like:
`{
  "_id": "sdfsfsfsfsfsfs",  
  "$doctype": "someDocumentTemplate",
  "templateName": "AK",
  "templateTypeX": "AllCategoriesTemplate",  
  "someKey": "989878799",
  "metaData": { 	
    "fieldId2": "2018-06-14T12:27:03.2204746Z" //Error fetching this field in the custom reduce function
  },  
  "someAppState": 0  
}`

**Comment by rnewson** [comment]
This appears to be because you don't handle the case where rereduce=true. The result from your reduce function is return in the 'values' parameter in that case, and, in the rereduce=false case, your 'mostRecentTemplate' object does not contain the metaData attribute.

**Comment by rnewson** [comment]
This custom reduce function doesn't work in 1.6.1 either, you've just had too few documents in your database for couchdb to call you with rereduce=true.
