### ISSUE TITLE
validate_doc_update not applied to design documents - potential security issue

### ISSUE THREAD

**Issue by tudordumitriu** [apache/couchdb#2026]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )
It seems that validate_doc_update is not getting applied to updates on design documents (including the document containing the validate_doc_update definition)
## Description
Following the suggestions from http://guide.couchdb.org/draft/validation.html, especially the ones on authorship, we have implemented a mechanism (that works very well for standard documents) that restricts the updates to documents according to author or certain rights.
Example from docs:
`function(newDoc, oldDoc, userCtx) {
  if (newDoc.author) {
    enforce(newDoc.author == userCtx.name,
      "You may only update documents with author " + userCtx.name);
  }
}`

## Steps to Reproduce
Now, if someone else tries to update a document, the error is thrown. But if he first updates the design document with validate_update_doc and after tries to do the update, no problem at all.

Here is a simplified example of our validate_doc_update function

`function (newDoc, oldDoc, userCtx) {
	var username = 'org.couchdb.user:' + userCtx.name;
	if (userCtx.name == 'sa')
		return;
	if (!oldDoc && newDoc.createdBy != username) throw ({forbidden: 'Cannot create documents for other users!'}); 
	if (!oldDoc && newDoc._rev.substring(0, 2) !=  \"1-\") return; 
	if (newDoc && newDoc._id.substring(0, 7) == \"_design/") throw ({forbidden: 'Cannot update design documents!'});
}`

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behavior
I would expect the exception to be thrown when updating design documents

## Your Environment
- Client PouchDB
- Server CouchDB - Per user db
- Server CouchDB - Central DB (only a subset of each PerUser db gets replicated to the CentralDB using https://github.com/redgeoff/spiegel)
- Shared Documents to multiple PerUser Databases 

* CouchDB Version used: 2.3.1
* Browser name and version: Chrome
* Operating System and version: Windows 10

**Comment by rnewson** [comment]
Only admins can modify security documents. If admin access also had to pass the VDU check we open ourselves up to a situation where a mistake can never be fixed, there'd be no way to remove a broken VDU. We deliberately do not run VDU checks when admins are modifying design documents.

**Comment by tudordumitriu** [comment]
Thanks
I think I might have missed something out, I am not doing the updates as admin (indeed it does make perfect sense NOT to run VDU as admin)
I am doing the update as a standard user, in his own database (per user db), but he does have some documents shared to him (replicated in his DB) as readonly. Readonly check is accomplished with the VDU for each PerUser db. 
But as far as I can tell the user can delete the VDU in his own DB and from this moment on he can update any documents.

P.S.
Maybe my confusion is that an user is an admin in his DB? Could this be the case?
If this is it, are there any alternatives to restrict an user to update certain documents in HIS database?

**Comment by rnewson** [comment]
There are two kinds of administrator and I was remiss to conflate the two.

when I said administrator above I specifically mean the kind that appears in the `[admins]` section. These are server admins.

A Database administrator is a regular user that's named in the 'admins' section of the security object of the database.

An administrator of either type can edit design documents without having to pass the VDU's.

**Comment by tudordumitriu** [comment]
Great
We fixed this by removing the user from admins and just keeping it as a member
So the question / bug is irrelevant but I think it would help if this would be specified in documentation

**Comment by wohali** [comment]
We'd be happy to accept a pull request on the documentation repository :) It should be a quick change, and would earn you the status of CouchDB contributor! :smile:
