### ISSUE TITLE
eunit test timedout errors during jenkins CI 

### ISSUE THREAD

**Issue by jiangphcn** [apache/couchdb#2030]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )
Encountered the following eunit test errors during jenkins CI build against CouchDB.

-  src/couch/test/couch_passwords_tests.erl
`pbkdf2_test`_

-  src/mem3/test/mem3_reshard_api_test.erl
     `create_job_with_db/1`
     `create_job_with_shard_name/1`
     `recover_in_initial_copy/1`
    `recover_in_source_delete/1`
     `check_max_jobs/1`

- src/mem3/test/mem3_reshard_test.erl
`split_one_shard/1`
`update_docs_before_topoff1/1`
`split_partitioned_db/1`
`split_twice/1`

- b64url/test/b64url_tests.erl
`decode_binary_test/0`
`decode_iolist_test/0`

The latest log can be found from https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/jenkins-fixup-eunittest/5/pipeline after disabling above test

## Steps to Reproduce

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )
Trigger build using jenkins-xxx branch or master branch

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )
These timedout errors disappear

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB Version used: 2.3.0
* Browser name and version: N/A
* Operating System and version: N/A

## Additional context

[TIP]:  # ( Add any other context about the prbolem here. )

**Comment by jiangphcn** [comment]
After ignoring the following eunit test cases, the eunit tests in all platform but one (Debian Stretch aarch64) passed[1]. 

- src/mem3/test/mem3_reshard_api_test.erl
  ` individual_job_stop_when_cluster_stopped/1`
   `recover_in_build_indices/1`

- src/mem3/test/mem3_reshard_changes_feed_test.erl
  `normal_feed_should_work_after_split/1`
  `continuous_feed_should_work_during_split/1`

[1] https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/jenkins-fixup-eunittest/8/pipeline/64

**Comment by jiangphcn** [comment]
In `Debian Stretch aarch64` platform, we got a bunch of timed-out. https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/jenkins-fixup-eunittest/8/pipeline/64. Will try to extend the duration for timed-out.

**Comment by wohali** [comment]
Hi @jiangphcn , any luck on extending the timeouts?

**Comment by iilyak** [comment]
Possible workaround is to set `trace: true` in the config [here](https://github.com/apache/couchdb/blob/master/test/elixir/test/test_helper.exs#L9). This should work because it causes ExUnit to use infinity as a timeout (see https://github.com/elixir-lang/elixir/blob/master/lib/ex_unit/lib/ex_unit/runner.ex#L410).

**Comment by wohali** [comment]
@iilyak But we're talking also about EUnit here, not ExUnit.

Thoughts?

**Comment by eiri** [comment]
Is this about individual tests or global eunit's timeout? Individual tests' timeout could be changed with `{timeout, Time::number(), Tests}` wrapper, with a caveat that this timeout also includes setup and teardown. For global timeout that's tricky. Eunit's `? DEFAULT_TEST_TIMEOUT` is 5 sec and tbh I don't think there is an option to override this.

**Comment by wohali** [comment]
@eiri Global. In the case of cross-running on another architecture, or a very low end architecture (like a Raspberry Pi) these tests simply can't run that slow. It'd be fantastic to up that globally.

Could we patch eunit?
Could we specify per-testfile or util based overrides and add a new `{timeout...}` wrapper to every file that references a global value?

Otherwise you're talking about hand-upping timeouts on hundreds and hundreds of unit tests that currently fail on `aarch64` and will soon start failing on `ppc64le`, `s390x`, etc.

**Comment by eiri** [comment]
I think there are two potential venue to approach: 1) using `parse_transform` to modify all the  tests to add that `{timeout...} or 2) modify rebar's rest runner to catch timeout and either re-run the test suite or treat it as exit 'ok'. Honestly don't know how feasible or how much work either of this could be.

I once tried to write custom eunit runner to skip rebar all together, it was doable and fwiw the tests ran faster, but it wasn't finished solution and it was getting hairy pretty quick.

@iilyak I wonder if it's possible to use that `ExUnit` to run eunit tests instead of rebar's eunit? Maybe this could be a perspective solution.

**Comment by iilyak** [comment]
We could also try patching rebar. We can try to change [this function](https://github.com/rebar/rebar/blob/master/src/rebar_eunit.erl#L468:L469) 

from 
```
eunit_primitive(Type, M, F) ->
   {Type, M, F}.
```

to 
```
eunit_primitive({timeout, _, _} = Type, M, F) ->
   {Type, M, F};
eunit_primitive(Type, M, F) ->
   {timeout, 999999999999999999, [{Type, M, F}]}.
```

**Comment by eiri** [comment]
This is actually a pretty good idea. I thought about rebar plugin, but this might be the fastest and simplest solution. Want to give it a try? I think a bump to 5 mins should be enough, we probably don't want to completely block pipeline on genuine deadlocks

**Comment by wohali** [comment]
What happens when we move to rebar3?

**Comment by jiangphcn** [comment]
hey @wohali,

It is helpful to extend timeout. The tricky thing is about eunit test on `Debian Stretch aarch64`. I have seen a lot of failures in https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/jenkins-fixup-eunittest/8/pipeline/64, so didn't add it one by one. 

```
[2019-05-14T03:34:10.023Z] module 'couch_btree'

[2019-05-14T03:34:10.023Z]   module 'couch_btree_tests'

[2019-05-14T03:34:10.023Z]     couch_btree_tests:80: btree_open_test_ (Ensure that created btree is really a btree record)...ok

[2019-05-14T03:34:10.023Z]     BTree with sorted keys

[2019-05-14T03:34:12.306Z]       couch_btree_tests:179: should_set_fd_correctly...ok

[2019-05-14T03:34:12.307Z]       couch_btree_tests:182: should_set_root_correctly...ok

[2019-05-14T03:34:12.307Z]       couch_btree_tests:185: should_create_zero_sized_btree...ok

[2019-05-14T03:34:12.307Z]       couch_btree_tests:190: should_set_reduce_option...ok

[2019-05-14T03:34:12.307Z]       couch_btree_tests:194: should_fold_over_empty_btree...ok

[2019-05-14T03:34:17.636Z]       couch_btree_tests:207: should_return_complete_btree_on_adding_all_keys...*timed out*

[2019-05-14T03:34:17.636Z]       undefined

[2019-05-14T03:34:24.062Z]     Should continuously add key-values to btree

[2019-05-14T03:34:29.286Z]       couch_btree_tests:442: should_produce_valid_btree...*timed out*

[2019-05-14T03:34:34.510Z]     Should continuously remove keys from btree

[2019-05-14T03:34:34.510Z]       couch_btree_tests:442: should_produce_valid_btree...ok

[2019-05-14T03:34:34.510Z]       couch_btree_tests:445: should_be_empty...ok

[2019-05-14T03:34:34.510Z]       [done in 0.020 s]

[2019-05-14T03:34:45.084Z]     couch_btree_tests:442: should_produce_valid_btree...*timed out*

[2019-05-14T03:34:45.084Z]     undefined

[2019-05-14T03:34:50.307Z]   couch_btree_tests:279: should_add_every_odd_key_remove_every_even...*timed out*

[2019-05-14T03:34:50.307Z]   undefined

[2019-05-14T03:34:55.531Z] couch_btree_tests:289: should_add_every_even_key_remove_every_old...*timed out*

[2019-05-14T03:34:55.531Z] undefined
```

Thanks to @iilyak and @eiri for their tips. I applied https://github.com/apache/couchdb/issues/2030#issuecomment-495347800 in https://github.com/apache/couchdb/compare/jenkins-fixup-eunittest?expand=1#diff-e2d5a00791bce9a01f99bc6fd613a39dR220.

From recent build, looks that it helps a lot. https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/jenkins-fixup-eunittest/12/pipeline/64

However, still see one failure on `Debian Stretch aarch64` for now. (maybe there are more, but stop here)
```
[2019-05-24T09:20:58.376Z] module 'chttpd_handlers'

[2019-05-24T09:20:58.376Z]   chttpd_handlers: select_override_test...ok

[2019-05-24T09:20:58.376Z]   chttpd_handlers: select_default_override_test...ok

[2019-05-24T09:20:58.376Z]   module 'chttpd_handlers_tests'

[2019-05-24T09:20:58.376Z]     _replicate

[2019-05-24T09:21:03.251Z]       chttpd_handlers_tests:48: should_escape_dbname_on_replicate...getsockopt level=41 optname=67 not yet supported

[2019-05-24T09:21:03.962Z] *timed out*

[2019-05-24T09:21:03.962Z]       undefined
```

I will comment out this test so that more eunit test can run on this platform. And see how much are left.

**Comment by iilyak** [comment]
> @wohali : What happens when we move to rebar3?

My personal opinion is we shouldn't move to rebar3. There might be better options out there. I agree with your concern though if we update rebar plugin it would make migration harder.

**Comment by iilyak** [comment]
> @eiri I once tried to write custom eunit runner to skip rebar all together, it was doable and fwiw the tests ran faster, but it wasn't finished solution and it was getting hairy pretty quick.
> @iilyak I wonder if it's possible to use that ExUnit to run eunit tests instead of rebar's eunit? Maybe this could be a perspective solution.

I am not sure if ExUnit can be used to run eunit tests (I think unlikely). However mix definitely can (with a plugin). Mix is introduced [here](https://github.com/apache/couchdb/pull/2039). We might need to modify the mix plugin though. I doubt the eunit plugin is smart enough to extend timeout.

**Comment by lag-linaro** [comment]
Any update on this guys?

Obviously this is blocking official support for AArch64 which is pretty important.

What platforms are the tests currently running on?  RPi3?

Would it also help if you were to run the tests on more capable hardware?

**Comment by wohali** [comment]
Hi @lag-linaro , we are currently setting up a brand new Jenkins instance for better testing. If packet.net is prepared to make a targeted hardware donation of at least 2 aarch64 servers for us to use long-term, please contact me off-Github at my email address, which is my GH id @ apache.org.

**Comment by lag-linaro** [comment]
Have you tried reaching out to WorksOnArm?

**Comment by wohali** [comment]
A while ago, yes, maybe 2 years now. I can contact them again.

**Comment by jiangphcn** [comment]
thanks @wohali for further information.

**Comment by lag-linaro** [comment]
> A while ago, yes, maybe 2 years now. I can contact them again.

Looks like you have a new customer @vielmetti - how exciting. :smiley:

**Comment by kocolosk** [comment]
This spiraled out into a bunch of other issues, but the end result is that we have tests passing everywhere including on aarch64 so I'm going to close this one out 😄
