### ISSUE TITLE
Debian Buster package

### ISSUE THREAD

**Issue by rgarrigue** [apache/couchdb#2031]
## Summary

Debian Buster will be out somewhen. I'ld like a CouchDB package for it.

I know most people thinks before release is too early, but me & others have to start testing things as soon as possible to be ready on release day. If the answer is "not yet", please leave this issue open & close is whenever done, so we can track the release of the package.

## Desired Behaviour

`buster/` in https://apache.bintray.com/couchdb-deb/dists/

**Comment by rnewson** [comment]
[copied from dev list response from Joan Touzet]

CouchDB does not rush to release binaries for Debian/Ubuntu/CentOS/RHEL on major x.0 releases.

It is unlikely we will publish any buster package until after its official promotion to stable. No release date has been set yet for buster, though we're aware it is in freeze status. After release, we will then add buster to our CI matrix and ensure regression tests pass properly before releasing. If history serves, you can expect the package roughly a month after the buster release.

If you need it running on buster sooner, you are always welcome to compile from scratch. Bug reports and pull requests against our CI or packaging repos from issues you find are always welcome.
