### ISSUE TITLE
How to rebuild a specific .shard file?

### ISSUE THREAD

**Issue by ceremcem** [apache/couchdb#2032]
I'm backing up my whole server (including virtual machines) periodically with rsync. Now there is something wrong with my harddisk and some files are not readable, including a file of CouchDB (message is obfuscated):

```
cp: error reading '/var/lib/lxc/my-couch2/rootfs/home/foo/couchdb/couchdb/data/.shards/40000000-5fffffff/bar2.1533443496_design/mrview/54f171fe1f24ac4eb52ac24c85f9d8fc.view': Input/output error
```

According to the [documentation](http://docs.couchdb.org/en/stable/maintenance/backups.html), it's a temporary file and will be rebuilt on demand. How can I fix it right now (trigger a rebuild) so that I could fix the file and continue my backup procedure normally?

**Comment by garrensmith** [comment]
@ceremcem making a query request to your views should rebuild the indexes

**Comment by ceremcem** [comment]
@garrensmith Thanks. Should I trigger a query request for *each view* or can I determine which view is related with that unreadable `.shard` file?

**Comment by ceremcem** [comment]
Update: It wasn't so hard to open the Fauxton interface and click every view in the database. This should trigger the desired query request. However, despite the successful query requests, the file still seems unreadable. 

Is it okay to delete this file and trigger all views again?

**Comment by ceremcem** [comment]
I backed up the erroneous file and triggered all views in the database `bar2`. That file is restored and everything seems to work correctly.
