### ISSUE TITLE
rename "bylaws" to "community guidelines"

### ISSUE THREAD

**Issue by mechanomi** [apache/couchdb#2033]
bylaws: https://couchdb.apache.org/bylaws.html

reasoning here:

https://lists.apache.org/thread.html/e5a17e8263dbc8efdd7e20978d653f3ede6c5488c4970d545d340d7f@%3Cdiversity.apache.org%3E

**Comment by wohali** [comment]
I previously talked to Bertrand about this and don't think CouchDB needs 
to change here. Other projects, especially older ones, have their own 
"bylaws" and aren't expected to change. This is mostly advice going 
forwards. I worry that if we change the name people will think it 
weakens our resolve to follow these rules we've set out for ourselves, 
which is absolutely not true.

Let me have a 1:1 with him and I'll get back to you. Next week earliest.

-Joan

**Comment by mechanomi** [comment]
understood. thx!

**Comment by wohali** [comment]
Chatted again with Bertrand and it doesn't sound like we need to do anything here. Closing it out.
