### ISSUE TITLE
Fauxton not working properly under NGINX reverse proxy

### ISSUE THREAD

**Issue by ttkdroid** [apache/couchdb#2035]
## Description

The reverse proxy instructions with NGINX works for ordinary database operations however Fauxton doesn't work properly as some of the urls doesn't follow the rewrite directives of the webserver, showing an error message `"JSON.parse: unexpected character at line 1 column 1 of the JSON data"`

## Steps to Reproduce
1. Add the reverse proxy entry to nginx.conf:
```
location /cdb {
    rewrite /cdb(.*) $1 break;
    proxy_pass http://127.0.0.1:5984;
    proxy_redirect off;
    proxy_buffering off;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```
2. Try to reach Fauxton interface:
https://www.myserver.com/cdb/_utils

## Expected Behaviour

Fauxton working properly as if it was reached directly

## Your Environment
* CouchDB Version used: 2.3.1
* Browser name and version: Firefox 60.6
* Operating System and version: Mac, Windows, Linux

## Additional context
<img width="987" alt="Screen Shot 2019-05-22 at 4 22 10 pm" src="https://user-images.githubusercontent.com/13210693/58152303-92787680-7caf-11e9-9119-aed3f97d75cd.png">
<img width="992" alt="Screen Shot 2019-05-22 at 4 22 49 pm" src="https://user-images.githubusercontent.com/13210693/58152304-92787680-7caf-11e9-9f30-d760d53a371b.png">
<img width="987" alt="Screen Shot 2019-05-22 at 4 23 26 pm" src="https://user-images.githubusercontent.com/13210693/58152305-92787680-7caf-11e9-8855-9f10bc428786.png">
<img width="988" alt="Screen Shot 2019-05-22 at 4 24 05 pm" src="https://user-images.githubusercontent.com/13210693/58152306-93110d00-7caf-11e9-810d-7524c290b9d1.png">

**Comment by ceremcem** [comment]
FYI: My use case is exactly the same (I'm reverse proxying CouchDB with Nginx in a subdirectory) with the following configuration: 

```
    location ^~ /db2/ {
        proxy_pass http://10.0.8.19:5984/;
        proxy_redirect off;
        proxy_buffering off;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
```

**Comment by wohali** [comment]
The documentation was only written to ensure CouchDB functions at the `/` (top level).

A pull request against the *documentation* for hosting CouchDB at a subdirectory is welcome.

Moving this issue to that repository now.
