### ISSUE TITLE
CouchDB replication Issue

### ISSUE THREAD

**Issue by sudhir-naico** [apache/couchdb#2042]
We have some issues with CouchDB replication. 

We have two azure VMs with OS ubuntu server 16.04.3 LTS and installed CouchDB in both VMs. CouchDB replication from one server to another server hosted in azure VM is not working. In the replication interface (fauxton), replication state is 'running', but in 'active tasks', there is no tasks corresponding to the replication. The replication was working fine before. After increasing azure disk space on the server, Public IP address of the server changed, and we edited the replication configuration with new IP. Since the replication was not working, we removed existing replication and configured a new replication. Still the replication is not working. We looked into CouchDB log file and found timeout error. Our CouchDB version is v.2.1.1. 

Here is the error from log file:-

"
2019-04-30_03:21:35.81520 [error] 2019-04-30T03:21:35.814844Z couchdb@127.0.0.1 <0.24773.645> -------- exit:{http_request_failed,"GET","http://<Destination IP Address>:5984/<database name>/",{error,{error,{conn_failed,{error,etimedout}}}}}: Replication 9335757b5ea5def3e7896351b8ef34a5 failed to start "http://<Source IP Address>5984/<database name to replicate>/" -> "http://<Destination IP Address>:5984/<database name>/" doc <<"shards/c0000000-dfffffff/_replicator.1516781452">>:<<"f48985560be6f8cbe3176255560b51d5">> stack:[{couch_replicator_api_wrap,db_open,3,[{file,"src/couch_replicator_api_wrap.erl"},{line,119}]},{couch_replicator_scheduler_job,init_state,1,[{file,"src/couch_replicator_scheduler_job.erl"},{line,590}]}]
"

Today, I created a new VM with Ubuntu Server 16.04.6. Installed CouchDB 2.3.1. Tried to configure replication from one of the existing Server to the newly created server via fauxton UI. But got the same error. I created a new test database in the new server and configure replication from the test database to a new database in the newly created server, but got same error.

Is there any issue or limitations with CouchDB replication?

CouchDB Replication Configuration 
------------------------------------
![CouchDB_Replication_Configuration](https://user-images.githubusercontent.com/33647716/58800887-b5e3df80-8626-11e9-9198-407067f0bed4.PNG)
CouchDB Replication Status
----------------------------
![CouchDB_Replication_Status](https://user-images.githubusercontent.com/33647716/58801327-d6f90000-8627-11e9-87f0-3f4b4b1cc31f.PNG)
CouchDB Replication Active Tasks
----------------------------------
![CouchDB_Replication_Active_Tasks](https://user-images.githubusercontent.com/33647716/58800888-b5e3df80-8626-11e9-88a5-233533bba140.PNG)

## Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB Version used: 2.1.1
* Browser name and version: Firefox 67 
* Operating System and version: Ubuntu Server 16.04.3 LTS (Azure VM)

**Comment by ceremcem** [comment]
@sudhir-naico Would you mind explaining how this bug is resolved?

**Comment by sudhir-naico** [comment]
@ceremcem , This is related to azure portal issue. I have already added a rule to allow the port 5984 to the required public IP address in VM Networking section. But it was somehow not working. I modified the rule to allow the port 5984 to all public IP Address by setting source and destination to 'Any'.

**Comment by ceremcem** [comment]
Thanks for the explanation. So there is nothing to worry about.
