### ISSUE TITLE
Stale couch view after purging document with conflicted revision tree

### ISSUE THREAD

**Issue by priyath** [apache/couchdb#2045]
A couple of days back, I raised a question regarding a sporadic issue we observed related to Couch views returning stale data. (Reference: https://github.com/apache/couchdb/issues/2040)

I have found out the reason for this and would like some insight from the community to understand this problem better.

## Description
We have a production setup with multiple local Couch databases (replicating amongst each other) and syncing with a master cloud Couch database. Our Couch databases also go through a scheduled daily purge where specific documents (after a grace period) gets purged from the database. 

The issue we have observed is as follows:

When a document with a conflicting revision tree is purged, it gets reverted back to the leaf revision of the conflicting revision tree. (I understand this happens because we do not specify the conflicting revision in the _purge POST request)

This reverted document is caught in the next purge window and is purged again which gets rid of the document entirely from the database as expected. However, when related views are queried for data, this is not reflected; The document Id is still visible in the queried data.

## Steps to Reproduce
Pre-requisites:
* A document with a conflicting revision tree
* A view that retrieves the above document Id

Step 1: Purge the document, specifying the latest revision. This will revert the document to the leaf of the conflicting tree

Step 2: Purge the document again, this time specifying the leaf of the conflicting tree.

Step 3: Perform a purge of another document to ensure the diff between the purge sequence of the database is greater than the purge sequence of the view by more than 1. (Based on documentation, this will trigger a complete rebuilding of the indexes)

Step 4: Access the view. The purged document Id (now completely removed from the database) will still be returned.

## Expected Behaviour
The view should not return Ids of documents that are purged completely.

## Your Environment
* CouchDB Version used: CouchDB 1.6.1
* Browser name and version: Chrome
* Operating System and version: Ubuntu

## Additional context
The fix that I plan on implementing is to specify all leaf revisions (including that of conflicting branches) when initiating the purge. 

However, I would also like to understand what exactly is happening here for the document Id to not get removed from the index when the conflicting revision tree is purged from the database.

**UPDATE**
This issue does not re-create in CouchDB 2.3.1

**Comment by sansato** [comment]
The context in this ticket is overly complicated.  As described in the mailing list, small reproducer is 1) purge more than one document and 2) query the index.

The workaround is 1) purge one document and 2) query the index immediately after the purge.  Repeat if additional documents need to be purged.  

This is a known issue in the 1.x series.  Did you try the scenario with current 2.x version?

**Comment by priyath** [comment]
Thank you for the response! What do you mean by mailing list?

I was of the impression that if the diff between the database and view purge sequences is greater than 1, a complete rebuilding of the indexes will take place which would ideally update the indexes properly.

This piece of code reflects the same: https://github.com/apache/couchdb-couch-index/blob/master/src/couch_index_updater.erl#L204

I am not sure how purging a conflicting revision tree could change this though. Haven't tested this on 2.x I will do that and update the results here.

**Comment by jiangphcn** [comment]
hey @priyath if we didn't purge all leaf revisions, the document still exists and it makes sense that it can be visible to view. 

In clustered purge, we can specify all leaf revisions in one POST requests, documents will be purged totally. Of course, we can select to purge all but one, thus the expected revision will be left.

**Comment by priyath** [comment]
> hey @priyath if we didn't purge all leaf revisions, the document still exists and it makes sense that it can be visible to view.

Agreed. But when the reverted leaf revision is purged again as in this scenario, the document is completely removed as expected but the ID still remains in the index resulting in a stale view.

**Comment by jiangphcn** [comment]
I see, and then my assumption is that the reverted leaf revision doesn't trigger update of update-seq, and thus view update doesn't happen to update index. Clustered purge should not have such behavior. You can have a try on clustered purge if feasible.

**Comment by priyath** [comment]
> I see, and then my assumption is that the reverted leaf revision doesn't trigger an update of update-seq

I see. But why wouldn't a complete rebuild of the index after the next purge fix the indexes?  

I ask this because the only way to get the views to return the correct data is by deleting all the *.view files from the system.

**Comment by jiangphcn** [comment]
could you also check the IdxPurgeSeq of shard database before running query to trigger index update so that we can see which branch of codes https://github.com/apache/couchdb-couch-index/blob/master/src/couch_index_updater.erl#L204 was executed?

**Comment by priyath** [comment]
> could you also check the IdxPurgeSeq

Is this the same value that is found in the purge_seq attribute returned from the _design/ddoc/_info endpoint? Or is there another way to obtain the IdxPurgeSeq value.

**Comment by jiangphcn** [comment]
Not sure whether you are familiar with `remsh` and we can use https://github.com/apache/couchdb-couch/blob/21c8d37ac6ee1a7fed1de1f54f95a4d3cd9f5248/src/couch_db.erl#L304

**Comment by priyath** [comment]
> Not sure whether you are familiar with `remsh` and we can use https://github.com/apache/couchdb-couch/blob/21c8d37ac6ee1a7fed1de1f54f95a4d3cd9f5248/src/couch_db.erl#L304

The purge sequence between the CouchDB and the view index shows a diff > 1 so it should go through the reset code branch.

**Comment by priyath** [comment]
> This is a known issue in the 1.x series. Did you try the scenario with current 2.x version?

Can confirm this issue **does not** recreate in CouchDB 2.3.1

**Comment by wohali** [comment]
@priyath I'm not sure there's much more we can do for you here, especially because this is 1.x and support is long done by now.

If you know you're going to be purging >1 doc at a time between view reads, then the best you can do is intentionally make a trivial change to each design document in that database. This will force the recalculation of the view on next view access.

Add a space or something to change one map function in a trivial way; this changes the checksum of the ddoc and triggers the full rebuild from scratch, without having to remove the `.view` file on disk.
