### ISSUE TITLE
CouchDB 2.3.1 refuses to build on Ubuntu 18.04

### ISSUE THREAD

**Issue by danikp** [apache/couchdb#2047]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
While building couchDB 2.3.1 from source on Ubuntu Bionic 18.04, it fails with error
$ make release
**CouchDB does not support this version of Erlang ("20.2.2").**
Check https://docs.couchdb.org/en/latest/whatsnew/index.html for the
latest information on supported releases.
Makefile:114: recipe for target 'couch' failed
make: *** [couch] Error 1

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Steps to Reproduce
# download and build
wget http://apache.spd.co.il/couchdb/source/2.3.1/apache-couchdb-2.3.1.tar.gz
tar zxf apache-couchdb-2.3.1.tar.gz
mv apache-couchdb-2.3.1 couchdb

# preparation, only on bionic
sudo apt install devscripts debhelper zip pkg-kde-tools libffi-dev libnspr4-dev
git clone https://github.com/apache/couchdb-pkg
cd couchdb-pkg
make couch-js-debs PLATFORM=bionic
sudo apt install ./js/couch-libmozjs185-*.deb
cd ..

# continue
cd couchdb/
./configure
make release
[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour
build passing
[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment
ubuntu 18.04
erlang 20.2.2 (default package for that ubuntu version)
[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB Version used: 2.3.1
* Browser name and version:
* Operating System and version: Ubuntu 18.04

## Additional context
Docs say nothing on minimal Erlang version change, obly that Erlang 21 now supported, but not it's minimal version, so build on 20.x branch expected to work

[TIP]:  # ( Add any other context about the prbolem here. )

**Comment by wohali** [comment]
The release notes

http://docs.couchdb.org/en/stable/whatsnew/2.3.html

say:

#1875: Refuse building with known bad versions of Erlang.

The number is actually wrong, it should be #1857 which was fixed after release. T

We unfortunately had to blacklist specific versions of Erlang for known issues, which includes versions of 20.x prior to 20.3.8.11 or higher.

**Comment by wohali** [comment]
The workaround is to install a newer Erlang from e.g. https://packages.erlang-solutions.com/ or from scratch or from e.g. unstable repositories/PPAs.

**Comment by danikp** [comment]
1. now docs still point to wrong issue
2. it's wrong to send us search between dozens of comments, it will be much better to list all blacklisted versions in docs directly

thanks for pointing to correct issue

**Comment by wohali** [comment]
@danikp Yeah, we can't change the 2.3.1 docs now that they've been published, it's a limitation of how our documentation system works. We did merge a fix a few days ago for this problem:

https://github.com/apache/couchdb-documentation/pull/414

If you want to improve our documentation, please submit a PR to the apache/couchdb-documentation repo. This is an all-volunteer effort, and sometimes things don't get done. Your help and understanding is especially appreciated in this matter.
