### ISSUE TITLE
Can't change node_name from couchdb@localhost

### ISSUE THREAD

**Issue by cchang62** [apache/couchdb#2048]
Env: Windows Server 2012
I run my couchdb as standalone and modified -name value in vm.args from couchdb@localhost to couchdb@my.valid.FQDN. I can browse Fauxton/_utils from web via my valid FQDN. However, I can't change node_name from couchdb@localhost and then create databases correctly or pass VerifyInstallation test.

**Comment by wohali** [comment]
For a single node install:

Stop CouchDB, then delete your entire `data/` directory contents, then update the `vm.args` file, then start CouchDB.

This should make everything fine.
