### ISSUE TITLE
Testing for Apache CouchDB Installation

### ISSUE THREAD

**Issue by sarveshtamba** [apache/couchdb#2049]
Hello,

I have installed Apache CouchDB as per the install steps in the README(https://github.com/apache/couchdb/blob/master/INSTALL.Unix.md) and some help at https://github.com/apache/couchdb/issues/2044

Going ahead I want to test my installation. A few queries:-
Q.1.) Is there any default test suite which I can invoke from the command line or any other command line tests which I can rely on for verifying the installation?

Q.2) I am able to access the UI dashboard and execute "Verify CouchDB Installation" only if I start CouchDB as Developers cluster setup using "./dev/run" to spin up three nodes(Developers cluster is set up at http://127.0.0.1:**15984**). Also able to do operations via CLI using curl.
If I start CouchDB as a single node user, using "rel/couchdb/bin/couchdb", I am able to do operations via CLI using curl, but unable to access UI dashboard at http://127.0.0.1:**5984**. Is this a known issue or am I missing anything here?

**Comment by sarveshtamba** [comment]
@wohali please provide your guidance.

**Comment by wohali** [comment]
@sarveshtamba 

Hi there,

This is not a CouchDB bug. GitHub is for actual CouchDB bugs only.

If you are looking for general support with using CouchDB, please try one of these other options:

* The user mailing list. Signup instructions are [here](http://couchdb.apache.org/#mailing-lists)
* The Slack/IRC chat room. Joining instructions are [here](http://couchdb.apache.org/#chat)
