### ISSUE TITLE
[CouchDB 2.3.1] Cluster setup timed out waiting for nodes to connect

### ISSUE THREAD

**Issue by raoyitao** [apache/couchdb#2054]
Update from 2.3.0 to 2.3.1 I met a problem when setting cluster. I have 3 hosts, on each there is a CouchDB 2.3.1 running, but I cannot join them as a cluster, I got the error "Cluster setup timed out waiting for nodes to connect", I search through Google but there's not hint why this happen.

## Description

I have configure **vm.args**, adding following content:

**-name couchdb@<[abc].mydoman.com>
-setcookie brum_brum
-kernel inet_dist_listen_min 9100
-kernel inet_dist_listen_max 9110**

The 3 hosts are **a.mydomain.com**, **b.mydomain.com**, **c.mydomain.com**, they can ping each other smoothly. In **local.ini** config files, the same **port**, **uuid** and **admin/password** were set.

Then I can run CouchDB on these hosts:
> **COUCHDB_ARGS_FILE=/path/to/my/vm.args ./bin/couchdb**

I also run this command on another host to test connections:

> **erl -name couchdb@d.mydomain.com -setcookie 'brum_brum' -kernel inet_dist_listen_min 9100 -kernel inet_dist_listen_max 9110**
(couchdb@d.mydomain.com)> **net_kernel:connect_node('couchdb@a.mydomain.com').**
**true**

It shows all these nodes can be connected.

## Steps to Reproduce

I follow the official document to setup a cluster, with the command for each node:
> **curl -X POST -H "Content-Type: application/json" http://admin:pass@IP-ADDR:PORT/_cluster_setup -d '{"action": "enable_cluster", "bind_address": "0.0.0.0", "username": "admin", "password": "pass", "node_count": "3"}'**

Then choose a coordination node and run these commands for the other two:
> **curl -X POST -H "Content-Type: application/json" http://admin:pass@COORD-IP:PORT/_cluster_setup -d '{"action": "enable_cluster", "bind_address": "0.0.0.0", "username": "admin", "password": "pass", "port": PORT, "node_count": "3", "remote_node": "REMOTE-IP", "remote_current_user": "admin", "remote_current_password": "pass"}'**
> **curl -X POST -H "Content-Type: application/json" http://admin:pass@COORD-IP:PORT/_cluster_setup -d '{"action": "add_node", "host": "REMOTE-IP", "port": PORT, "username": "admin", "password": "pass"}'**

At last finishe cluster setup:
> **curl -X POST -H "Content-Type: application/json" http://admin:pass@COORD-IP:PORT/_cluster_setup -d '{"action": "finish_cluster"}'**

But unfortunately I got the error after a few seconds:
**{"error":"setup_error","reason":"Cluster setup timed out waiting for nodes to connect"}**

The status of CouchDB cluster:
> **curl http://admin:pass@COORD-IP:PORT/_cluster_setup**
**{"state":"cluster_enabled"}**

## My Environment

* CouchDB Version used: **2.3.1 extracted from el7 RPM package**
* Operating System and version: **Red Hat Enterprise Linux Server release 7.6**

## Additional context

I have ever set 3 CouchDB servers as a cluster, but the version I used is 2.3.0. And now I switch to 2.3.1 seems I cannot setup cluster. I don't know why there is a timeout message.

The only information I could found is https://fossies.org/diffs/apache-couchdb/2.3.0_vs_2.3.1/src/setup/src/setup.erl-diff.html
Seems this error message is added in version 2.3.1

**Comment by raoyitao** [comment]
And I also tried http://COORD-IP:PORT/_utils/#/setup to setup a cluster, after adding nodes, I clicked "Configure Cluster" button and received the same error message.

**Comment by 0chris** [comment]
I'm also having this issue. @raoyitao did you find workaround/fix? :)

**Comment by raoyitao** [comment]
> I'm also having this issue. @raoyitao did you find workaround/fix? :)

No, I didn't. So I setup CouchDB cluster with 2.3.0 binary, the cluster information is saved in database, then I switch to 2.3.1 to start CouchDB, seems it could work. But it i still a troublesome thing that I cannot use CouchDB 2.3.1 to setup a cluster directly.

**Comment by vectorselector** [comment]
same problem. 
cannot obtain couchdb 2.3.0 binaries now either.
"relax" seems ironic after 3 days pulling my hair out trying to get 5 brand new 2.3.1 nodes to talk
`nc -vz someone 9100`   does get refused, firewall is specifically opened for this port for those nodes.
5984 and 4369 succeed in nc

**Comment by vectorselector** [comment]
So, I was able to get it working by adding the following lines to my vm.args

   -kernel inet_dist_listen_min 9100
   -kernel inet_dist_listen_max 9110

it's in one of the docs somewhere (old docs?)

**Comment by wohali** [comment]
Hi @vectorselector , so sorry you had all this trouble. Next time, reach out for help via our user@couchdb.apache.org mailing list, or our Slack channel, both of which are linked on our https://couchdb.apache.org/ home page.

Documentation on the setting you needed is right in our cluster setup guide. You might want to read the rest of this section to ensure you have taken all necessary steps to get your cluster working:

https://docs.couchdb.org/en/stable/setup/cluster.html#configure-and-test-the-communication-with-erlang

Best,
@wohali

**Comment by Rjayavasge** [comment]
H Wohali,
Still getting the error,
{"error":"setup_error","reason":"Cluster setup timed out waiting for nodes to connect"}

Configured the ad guideline.
Please support

Regards
Ruwan

**Comment by karelfridrich** [comment]
I got stuck on this too. Debian 11, Couch 3.2.2. Worked like a charm on 2.2.*. Ports were set up correctly, but there was another option I needed to change in vm.args:

-kernel inet_dist_use_interface {127,0,0,1}
to
-kernel inet_dist_use_interface {0,0,0,0}

Otherwise the port 9100 was opened only on localhost. I missed this option probably because of the odd IP format.
