### ISSUE TITLE
Changes feed with selector filter doesnt show deleted docs

### ISSUE THREAD

**Issue by modul** [apache/couchdb#2061]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Deleted documents are not included in the changes feed when filtering with `_selector`. It does work while filtering by doc_ids, which is not applicable in my scenario.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Steps to Reproduce

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

```
# Create document
curl -H 'Content-Type: application/json' -X PUT "localhost:5984/storage/123456" -d '{"name": "Document Name"}'

# Start changes feed
curl -H 'Content-Type: application/json' -X POST "localhost:5984/storage/_changes?feed=longpoll&filter=_selector&since=now" -d '{"selector": {"name": "Document Name"}}'

# Remove document (in another shell, of course)
curl -H 'Content-Type: application/json' -X DELETE "localhost:5984/storage/123456?rev=<LAST-REV>" 
```

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

The request to `_changes` should terminate with a results object for that particular document, including `deleted=true`.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

CouchDB running from (official) docker image:
```
{
    "couchdb": "Welcome", 
    "features": [
        "pluggable-storage-engines", 
        "scheduler"
    ], 
    "git_sha": "c298091a4", 
    "uuid": "54b4e44520a6fc9996a7eb635783fa96", 
    "vendor": {
        "name": "The Apache Software Foundation"
    }, 
    "version": "2.3.1"
}
```

**Comment by rnewson** [comment]
In your third step you remove the 'name' property of the document, and thus it no longer matches your selector. 

The DELETE method performs a PUT preserving only _id, _rev and _deleted (set to true).

Instead do a PUT, keeping the "name" field and adding "_deleted":true

**Comment by wohali** [comment]
Hi there,

This is not a CouchDB bug. GitHub is for actual CouchDB bugs only.

If you are looking for general support with using CouchDB, please try one of these other options:

* The user mailing list. Signup instructions are [here](http://couchdb.apache.org/#mailing-lists)
* The Slack/IRC chat room. Joining instructions are [here](http://couchdb.apache.org/#chat)

**Comment by modul** [comment]
Well, that does make sense. I would suggest to mention this in the docs even though it is self-explanatory.

Thanks for the quick response and sorry for opening this as a bug.
