### ISSUE TITLE
CouchDB app fails to autostart at login with macOS Mojave 10.14.5

### ISSUE THREAD

**Issue by MrBokeh** [apache/couchdb#2065]
# CouchDB app fails to autostart at login with macOS Mojave 10.14.5

## Description

CouchDB app fails to autostart at login with macOS Mojave 10.14.5

The https://github.com/janl/couchdb-mac-app repo is not fixing this issue for a long time

## Steps to Reproduce

Double click to start the mac app

## Expected Behaviour

Able to change autostart 

## Your Environment

* CouchDB Version used: 2.3.1
* Browser name and version: Google Chrome 75.0.3770.80
* Operating System and version: macOS Mojave 10.14.5 

## Additional context

There's a typo on the TIP with the word "problem" here

**Comment by janl** [comment]
PRs welcome :)

**Comment by nickva** [comment]
Apache CouchDb doesn't provide MacOS binaries.  They are provided by https://neighbourhood.ie/ at https://neighbourhood.ie/download-apache-couchdb-mac/. 

It's been about 4 years. @MrBokeh, perhaps try a newer version?  If you still see the issue, please contact Neighbourhood.ie
