### ISSUE TITLE
Erlang/OTP 22 Support

### ISSUE THREAD

**Issue by maciozo** [apache/couchdb#2069]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

Erlang/OTP 22 was released in May https://www.erlang.org/news/132. Would it be possible to add support for this?

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

## Desired Behaviour

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

Support for building/running CouchDB with OTP 22

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

Simply adding 22 to the version regex doesn't seem to have been enough, at least. Fails at `==> couchdb (compile)`.

EDIT: Upon further investigation, it may be a Fauxton compilation issue that's my fault. Checking now.

The compilation is successful without Fauxton - I think I just have some missing dependacies for that.

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )
Currently, Void Linux cannot run/build CouchDB, because it provides OTP 22.

**Comment by nickva** [comment]
Thanks for reporting the issue, @maciozo 

I tried installing erlang 22 and elixir build on erlang 22 locally with asdf

```
$ asdf current
elixir         v1.8.2-otp-22 (set by ASDF_ELIXIR_VERSION environment variable)
erlang         22.0.5   (set by ASDF_ERLANG_VERSION environment variable)
```

Then did `git clean -xffd` to clean all current build artifacts, added 22 to rebar.conf.script in main repo and for snappy dependency and got `make eunit` and `make elixir` tests to pass.

Created a PR to update snappy:
 https://github.com/apache/couchdb-snappy/commit/0f73f2b1b3508c31dd1129e2d7233ff9a469c775

And then one update the main repo with that new snappy version and bumped rebar.config.script values:
 https://github.com/apache/couchdb/pull/2070

Though that also required bumping elixir from 1.6.6. to 1.7.4

**Comment by maciozo** [comment]
Just built from erlang-22-support. Fauxton reports a good installation!

**Comment by wohali** [comment]
@nickva could you be sure to update apache/couchdb-ci to bump the minimum version of Elixir required to 1.7.4? Thanks.

One line fix: https://github.com/apache/couchdb-ci/blob/master/bin/install-elixir.sh#L31

**Comment by nickva** [comment]
@wohali thanks for the reminder!

https://github.com/apache/couchdb-ci/pull/22

**Comment by nickva** [comment]
Documentation PR as well:

https://github.com/apache/couchdb-documentation/pull/425
