### ISSUE TITLE
CouchDB Memory Leak - Beam.smp

### ISSUE THREAD

**Issue by XuHugo** [apache/couchdb#2079]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )
couchdb version 2.1.1,
## Description
I am using couchdb in fabric and deploy to k8s; when I send a lot of transactions quickly ;I found that memory of node（k8s） consumption is Maxed out and Pod（k8s）become Evicted；The CouchDb process that has the issue is the "beam.smp" of Erlang.
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Steps to Reproduce

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment
couchdb ： 2.1.1,
fabric ：1.4
k8s ：1.11.1
[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB Version used:
* Browser name and version:
* Operating System and version:

## Additional context
k8s'log:
opt0712       peer0-ke-7b546b4f6c-wf8pb              0/2       Evicted   0          15h       <none>          
opt0712       peer0-zong-5c85894f7f-4p9rh           2/2       Running   13       9h        172.17.94.9    
opt0712       peer0-zong-5c85894f7f-fbwcd           0/2       Evicted   0          23h       <none>          
opt0712       peer0-zong-5c85894f7f-fl55f           0/2       Evicted   0          19h       <none>          
opt0712       peer0-zong-5c85894f7f-ksbn6           0/2       Evicted   0          14h       <none>          
opt0712       peer1-er-9bc5487dc-gzkbf              2/2       Running   0          10d       172.17.55.5     

node'log: beam.smp cpu 109%
blockch+ 28539  109  1.6 2001772 131864 ?      Sl   13:21  37:06 /opt/couchdb/bin/../erts-6.2/bin/beam.smp -K true -A 16 -Bd -- -root /opt/couchdb/bin/.. -progname co-- -boot /opt/couchdb/bin/../releases/2.1.1/couchdb -kernel inet_dist_listen_min 9100 -kernel inet_dist_listen_max 9100 -kernel error_logger silent -sasl sasl_error_lt -config /opt/couchdb/bin/../releases/2.1.1/sys.config

[TIP]:  # ( Add any other context about the prbolem here. )

**Comment by wohali** [comment]
There were a lot of memory leaks cleaned up in 2.3.1 and 3.0.0. Please try reproducing this with the very latest Docker image. If you can, please reopen the issue.
