### ISSUE TITLE
Using CouchDB2.0 replication of one of our dbases never completes. Thousands of pending documents, and only a few get written. 

### ISSUE THREAD

**Issue by rvaldepenas** [apache/couchdb#2095]
We use continuous replication from a source server to multiple target servers. We have a 40GB dbase that has some updates and new items added daily, and we expect the continuous replication to update or add those items, but it doesn't update or add items. At least it is very very slow, where some of these updates or added items are months old.
I don't know if the issue is with attachments or not.

I have started a new source server, where it will only do continuous replication to a single server, and only replicate the dbase that we are having issues. The same issue is still there, where very few documents are written and there are thousands of pending changes.

Here is what I see in the log file for the source server.
[notice] 2019-07-30T20:49:26.057000Z couchdb@localhost <0.20065.103> f9c8bdfc6e ENCefleet01.ENCdomain.hal.com:5984 IPSourceServer undefined PUT /lists/sites%2Fhotel%2Fentertain.media.94.json?new_edits=false 500 ok 120051

[error] 2019-07-30T20:51:03.678000Z couchdb@localhost <0.28447.103> -------- fabric_worker_timeout update_docs,couchdb@localhost,<<"shards/e0000000-ffffffff/lists.1478891781">>

[<<"chttpd_db:db_doc_req/3 L765">>,<<"chttpd:process_request/1 L293">>,<<"chttpd:handle_request_int/1 L229">>,<<"mochiweb_http:headers/6 L122">>,<<"proc_lib:init_p_do_apply/3 L237">>]
[notice] 2019-07-30T21:42:28.580000Z couchdb@localhost <0.693.0> a6890b01c8 ENCefleet01.ENCdomain.hal.com:5984 IPSourceServer undefined PUT /lists/sites%2Fhotel%2Ffoodandbeverage.southern-europe.249.json?new_edits=false 500 ok 94
[error] 2019-07-30T21:42:28.580000Z couchdb@localhost <0.667.0> d02f177a5b req_err(3685245358) badmatch : ok
    [<<"chttpd_db:db_doc_req/3 L765">>,<<"chttpd:process_request/1 L293">>,<<"chttpd:handle_request_int/1 L229">>,<<"mochiweb_http:headers/6 L122">>,<<"proc_lib:init_p_do_apply/3 L237">>]

Please let me know what suggestions you have for me to try, or what additional information you need from me.

thanks,
rolando

**Comment by rvaldepenas** [comment]
This is one of the replication document we have for the second source server. There are only 2 replication documents. One is for replicating the "lists" dbase we are having issues with to the same dbase name on the target server. And this replication document which replicates the same "lists" dbase to a new "lists2" dbase on the target server.

{
  "_id": "ENClists2",
  "_rev": "14-70f4af541719bc00f23efbee74db4bbd",
  "source": "http://localhost:5984/lists",
  "target": "http://ENCefleet_svc_couch:TargetServerPassword@TargetServerNameAndDomain:5984/lists2",
  "create_target": true,
  "continuous": true,
  "owner": "ENCefleet_svc_couch",
  "_replication_state": "triggered",
  "_replication_state_time": "2019-08-03T02:29:33-07:00",
  "_replication_id": "94f17120dc281987c9770c9827715036"
}

**Comment by nickva** [comment]
Thank you for your report, @rvaldepenas 

What version of CouchDB are you using?

Here are some parameters to try to adjust:

If you suspect your documents, or attachments are rather large, try increasing
```
[httpd] max_httpd_request_size = <bytes>
```
In a few previous CouchDB version that was set at 64Mb so if you have anything large (doc + attachment size) it might fail. In 2.3.x it is set to 4Gb so if your version is 2.3.x the default is hopefully ok.

The other limits are

```
[couchdb]
max_document_size = <bytes>
max_attachment_size = <bytes>
```

Though the defaults for those should be infinity by default. But you can try to increase them if you've already configured them.

For the fabric timeout error. Can try increasing
```
[fabric]
request_timeout = <msec>
```
The default is 60000 so can try to make it 120000 perhaps.

There are some replication parameters such as `worker_processes` and `connection_timeout` that might help as well.

**Comment by rvaldepenas** [comment]
Hi Nick,
We are using version 2.0
I assume you want me to try these changes on both the source and target, correct?
We have max_document_size set to 250,000,000
I don't see [CouchDB]max_attachment_size in Configuration. There is however an "attachment_stream_buffer_size" which we have set to 999600.
Our CouchDB installation does not have a [fabric] section in Configuration.
for [replicator] connection_timeout we have it set to 480000 and
for [replicator] worker processes we have it set to 20.

from the source CouchDB log, I see many of these errors. Can you tell me what they mean?
[error] 2019-08-05T16:05:27.801000Z couchdb@localhost <0.13727.227> -------- Replicator, request PUT to "http://ENCefleet_svc_couch:*****@TargetServerName:5984/lists/sites%2Fhotel%2Ffoodandbeverage.southern-europe.307.json?new_edits=false" failed due to error {error,
    {'EXIT',
        {{{nocatch,{mp_parser_died,noproc}},
          [{couch_att,'-foldl/4-fun-0-',3,
               [{file,"src/couch_att.erl"},{line,591}]},
           {couch_att,fold_streamed_data,4,
               [{file,"src/couch_att.erl"},{line,642}]},
           {couch_att,foldl,4,[{file,"src/couch_att.erl"},{line,595}]},
           {couch_httpd_multipart,atts_to_mp,4,
               [{file,"src/couch_httpd_multipart.erl"},{line,208}]}]},
         {gen_server,call,
             [<0.16126.227>,
              {send_req,
                  {{url,

**Comment by nickva** [comment]
I'd recommend trying the latest CouchDB version. We have fixed some of the `nocatch,{mp_parser_died,noproc` errors in point releases since 2.0. 

The fabric settings could go on the target and source. If the section is not there, you can add it without any issues.

Try decreasing the worker processes a bit. If you have any large docs or attachments those workers will concurrently try to write those to the target and it might overwhelm it.

For an up-to-date list of config option try looking at the default.ini config that comes with the installation.

https://github.com/apache/couchdb/blob/master/rel/overlay/etc/default.ini#L43-L53

> There is however an "attachment_stream_buffer_size" which we have set to 999600.

I think that is too large. I would keep it at a default of 4K to start with.

**Comment by rvaldepenas** [comment]
Ok, I have just started a continuous replication from the second source server that I have setup which has CouchDB2.0 to another target server which has CouchDB2.3.1. This appears to be working as documents are being written. At the same time the "continuous replication" to the other target server, has not shown more than 6 documents written today. I did not make any of the changes from your last recommendation. Only because I wanted to see what happens when replicating between lower to higher version.
The goal being that we will upgrade both source and target servers to CouchDB2.2, and NOT 2.3.1. Even though the above target test server has CouchDB2.3.1.
I would like to get your recommendation for the upgrade path. I was thinking that I would upgrade only 1 target server to CouchDB2.2. So then we would be replicating from CouchDB2.0 to CouchDB2.2, for only one server. If the replication works, then we would start upgrading the remaining target servers to CouchDB2.2, then finally we would upgrade our source server to CouchDB2.2. What do you think?

**Comment by nickva** [comment]
> I was thinking that I would upgrade only 1 target server to CouchDB2.2. So then we would be replicating from CouchDB2.0 to CouchDB2.2, for only one server. If the replication works, then we would start upgrading the remaining target servers to CouchDB2.2, then finally we would upgrade our source server to CouchDB2.2. What do you think?

That sounds reasonable. I think 2.2 has most of the major fixes to replication since 2.0, especially related to large docs and attachments.

Another thing to think about when replicating docs or attachments that may exceed max {http request size | doc size |  attachment size} limits is that documents that are too large won't be written to the target but the replication will nevertheless continue. You'l have an indication of this in the `"doc_write_failures": ...` counter in the `_active_tasks` output or the completion stats in the document, for a non-continuous replication.

**Comment by rvaldepenas** [comment]
Nick,
I wanted to let you that we successfully upgraded all servers, and that replication appears to be working much better! I wanted to thank you for all of your tips and suggestions. And confirming my solution for the upgrade. We have a few issues with a few servers that I might ping you on this thread. Thanks again!

**Comment by nickva** [comment]
@rvaldepenas glad everything working out. Thanks for the update!

**Comment by rvaldepenas** [comment]
hi Nick,
I'm wondering if within CouchDB2.2, there is some sort of notification to a group mailbox, when replication streams are stuck in "retrying" or other notifications that would be helpful to warn of CouchDB replication issues?

**Comment by nickva** [comment]
@rvaldepenas sorry just now noticed the question after 4 years when looking to close some inactive tickets. For Apache CouchDB you can use `_scheduler/jobs` and inspect the `history` list. That would indicate if the jobs is continuously retrying  or not. The history will how the last 20 or so event for that particular jobs.

Otherwise, closing the issue as resolved.
