### ISSUE TITLE
error: read_beyond_eof when query couchdb

### ISSUE THREAD

**Issue by biwugang** [apache/couchdb#2097]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
when query couchdb, the error occur:
{"error":"error","reason":"{badmatch,\n    {'EXIT',\n        {bad_return_value,\n            {read_beyond_eof,\n                \"./data/shards/a0000000-bfffffff/local_whisks.1562291929.couch\"}}}}"}

if the item which is not saved in such shard, the query is success.
it looks like the shard file is bad or corrupted

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Steps to Reproduce
couchdb is used for our service, 
couchdb will save some binary (the biggest size is about 50 MB)
current couchDB data size is 15GB,
it is hard to reproduce

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB Version used: 2.1.2
* Browser name and version: I use curl command to do query
* Operating System and version: centos

## Additional context
it looks like the shard file is bad,
how to fix such issue?

[TIP]:  # ( Add any other context about the prbolem here. )

**Comment by shahkishak** [comment]
I'm facing this issue as well.
Couch log's size is growing wild over this one...

**Comment by wohali** [comment]
This is indeed a corrupt shard file. You need to restore from backup.

Please be aware that CouchDB does not support storing the .couch shard files on a NAS/SAN, especially over NFS. This can result in exactly the sort of corruption you're seeing.
