### ISSUE TITLE
Build fails without any error code (related to Couchjs)

### ISSUE THREAD

**Issue by sm-tradeboox** [apache/couchdb#2103]
## Description
I'm building CouchDB 2.3.1 from source and the build process keeps dying near the end without any real reason provided, except for the following error message at the end - 

```
...
==> apache-couchdb-2.3.1 (compile)
cp: cannot access src/couch/priv/couchjs
make: *** [Makefile:115: couch] Error 2
```

I'm attaching the complete build log.
[apache-couchdb-2.3.1.build.log](https://github.com/apache/couchdb/files/3479861/apache-couchdb-2.3.1.build.log)

## Environment
```
[couchmgr@test-c ~]$ uname -a
SunOS test-c.tradeboox.id 5.11 joyent_20181011T004530Z i86pc i386 i86pc

[couchmgr@test-c ~]$ rebar --version
rebar 2.6.4 21 20190705_115734 No VCS info available.

[couchmgr@test-c ~]$ iex -v
Erlang/OTP 21 [erts-10.3.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [dtrace]
IEx 1.7.4 (compiled with Erlang/OTP 21)

[couchmgr@test-c ~]$ erl --version
Erlang/OTP 21 [erts-10.3.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [dtrace]
```
I'll see if the same issue is replicated in Ubuntu 16.04. I don't believe so, because we have a CouchDB instance running there, and I believe it was built from source.

Thank you for your help in this matter.

**Comment by wohali** [comment]
See if anything here helps: https://issues.apache.org/jira/browse/COUCHDB-2995?jql=project%20%3D%20COUCHDB%20AND%20text%20~%20smartos

We don't support SmartOS / Joyent, but if you are able to make it work and a patch is required, we'll merge it (if it doesn't break building on other platforms).

**Comment by sm-tradeboox** [comment]
Hello. Yes, thanks! Seems to work.

The diff file rebar.config.script.diff applied to file src/couch/rebar.config.script fixes the complie error. I can't say yet if compile is correct. Is there a test suite for CouchDB?

**Comment by wohali** [comment]
Run `make check`.
