### ISSUE TITLE
Documentation: Proxy authentication is incorrect

### ISSUE THREAD

**Issue by paulbert** [apache/couchdb#2108]
## Summary

Setting up Proxy Authentication based on the 1.2.8 section of the documentation results in CouchDB crashing.

https://docs.couchdb.org/en/stable/api/server/authn.html#proxy-authentication

I noticed that the option for Proxy Authentication in the configuration documentation, 3.5, is `{couch_httpd_auth, proxy_authentication_handler}` not `{chttpd_auth, proxy_authentication_handler}`

https://docs.couchdb.org/en/stable/config/http.html#chttpd/authentication_handlers

Setting with `couch_httpd_auth` works, so I think this is a documentation issue.

## Desired Behaviour

Section 1.2.8 of documentation should have `{couch_httpd_auth, proxy_authentication_handler}` in the setting, so people using that section to set up Proxy Authentication will avoid crashing CouchDB.

**Comment by wohali** [comment]
Are you sure? What version of CouchDB are you running?

We specifically address changing this in a previous documentation PR...

https://github.com/apache/couchdb-documentation/pull/328/files

And here's the related code fix:

https://github.com/apache/couchdb/pull/1436

**Comment by paulbert** [comment]
We're running version 2.3.0.

I guess I'm not sure what should be correct, but the two sections of the documentation are contradictory with `chttpd_auth` in 1.2.8 and `couch_httpd_auth` in 3.5. 
 `couch_httpd_auth` is working, so I assumed that was correct.

**Comment by wohali** [comment]
`couch_httpd_auth` is wrong and deprecated. Are you using port 5984?

Can you try again with 2.3.1? Lots changed between 2.3.0 and 2.3.1 in this specific part of the code, which is why the documentation reflects what it does.

**Comment by paulbert** [comment]
Yes port 5984.  It's working with 2.3.1, thanks!

So it looks like the change above should be the opposite.  Section 3.5 of the docs uses the deprecated `couch_httpd_auth` for the proxy and null handlers.

https://docs.couchdb.org/en/stable/config/http.html#chttpd/authentication_handlers

**Comment by wohali** [comment]
Thanks, I'll take care of it.
