### ISSUE TITLE
Publish package on ARM

### ISSUE THREAD

**Issue by kocolosk** [apache/couchdb#2113]
# Summary

We're building packages for ARM now but we're not publishing them to `repo-nightly.apache.org` like the others. See

https://github.com/apache/couchdb/blob/master/Jenkinsfile#L525-L538

and 

https://github.com/apache/couchdb/blob/master/Jenkinsfile#L454

I don't know much about building Debian repos so not sure where to drop the `aarch64-debian-stretch` .debs so the `reprepro` commands pick them up appropriately. /cc @wohali

**Comment by wohali** [comment]
I can take this, but won't get to it until next week.

Really glad to see there's progress here! @lag-linaro will be very pleased. :)

**Comment by lag-linaro** [comment]
> @lag-linaro will be very pleased. :)

Amazing!  Thank you so much. :+1:

**Comment by wohali** [comment]
This is done, arm packages are up as of a while back surreptitiously and will be official with 3.0.0. Closing this issue.
