### ISSUE TITLE
_explain missed index in Elixir.PartitionMangoTest

### ISSUE THREAD

**Issue by kocolosk** [apache/couchdb#2116]
## Summary

Jenkins randomly failed on this test, where `_explain` should have responded that the query used an index on the "some" field, but instead responded that the "_id" index was used.

As far as I know the Elixir suite runs a single node so we shouldn't be dealing with any quorum consistency issues or anything like that. Don't think this is urgent but it'd be good to understand how that's possible and under what circumstances

## Steps to Reproduce

Unclear - this is the first time I've ever seen that test fail.

## Your Environment

https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/jenkins-cpse-debugging/25/tests

**Error**
```
Assertion with == failed
```

**Stacktrace**
```
4) test explain works with partitions (PartitionMangoTest)
test/elixir/test/partition_mango_test.exs:394
Assertion with == failed
code: assert body["index"]["def"] == %{"fields" => [%{"some" => "asc"}]}
left: %{"fields" => [%{"_id" => "asc"}]}
right: %{"fields" => [%{"some" => "asc"}]}
stacktrace:
test/elixir/test/partition_mango_test.exs:433: (test)
```

**Comment by kocolosk** [comment]
Happened again: https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/jenkins-elixir-retry-until-flakes/2/tests

**Comment by wohali** [comment]
Haven't seen this one in a few months, but let's keep it open for now.

**Comment by wohali** [comment]
Please reopen if this recurs.
