### ISSUE TITLE
Missing metrics to monitor internal replication status

### ISSUE THREAD

**Issue by natarajaya** [apache/couchdb#2120]
This is more a general design question than a bug report.

## Description

We are running our CouchDB clusters on GKE.
Entire setup is very simple: each cluster has 3 nodes, default sharding settings (`q=8,n=3`).

To make sure that our clusters are healthy, we monitor:
* `/_membership` data on every node, to verify that every node has connectivity to other nodes.
* `couchdb_httpd_request_time` [metric](https://github.com/gesellix/couchdb-prometheus-exporter/blob/master/README_metrics.md), which contains "length of a request inside CouchDB without MochiWeb", to verify that every node responds in a reasonable time.

We are looking to improve our monitoring solution to cover more failure modes, and have couple of questions:
* Is there a way to determine that node is lagging to process writes?
* After split brain situations (node lost connectivity to other nodes, but now connectivity is restored and node is syncing data) – is there a way to determine  "replication lag" or, in other words, amount of documents that are left to update?
* Does it make sense to monitor if databases contain documents with conflicts after split brain situations?

Thanks!

## Your Environment

GKE, CouchDB is installed with Helm using semi-official chart:
https://github.com/gpii-ops/gpii-infra/tree/master/shared/charts/couchdb

* CouchDB Version used: 2.3.1
* Browser name and version: None
* Operating System and version: None, GKE

**Comment by wohali** [comment]
Hi @natarajaya,

As you said, this is not a CouchDB bug. GitHub is for actual CouchDB bugs only. Unfortunately this means your question got ignored.

If you are looking for general support with using CouchDB, please try one of these other options:

* The user mailing list. Signup instructions are [here](http://couchdb.apache.org/#mailing-lists)
* The Slack/IRC chat room. Joining instructions are [here](http://couchdb.apache.org/#chat)
