### ISSUE TITLE
_find performance poor for _count reduce operation

### ISSUE THREAD

**Issue by ngspinu** [apache/couchdb#2129]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Although the docs advise to start using **__find_** rather the regular db views, it looks like _**_find**_ is at least 5x time slower than a regular view. Is that something expected?
![image](https://user-images.githubusercontent.com/35466661/63499019-afe7f700-c4cf-11e9-86cf-8580f101d45d.png)

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Steps to Reproduce
**USING NODEJS**
1. Create a new index through .createIndex 
2. Query the db through _find using fields to match the newly created index.
3. We queried for about 10k rows. It took about 3.8 seconds, while a regular view, for the same amout of data took 800ms.

**USING CURL**
The same as above. The execution took the same amount of time(3.8)s.

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour
The find execution should take at least the same amount of time as a normal view, or less?

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment
Nodejs under linux/mac-os.

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB Version used:
2.3.1
* Browser name and version:
* Operating System and version:
Mac-os / Centos 7

## Additional context

[TIP]:  # ( Add any other context about the prbolem here. )

**Comment by garrensmith** [comment]
A _find shouldn’t be slower. It’s using map/reduce underneath. So it’s the same query engine. What does your _explain say? Is the index being used. You can also enable execution_stats to tell you how the find query went to get more insight.


________________________________

**Comment by ngspinu** [comment]
This is what _explain says:
![image](https://user-images.githubusercontent.com/35466661/63509337-98ffcf80-c4e4-11e9-9d8c-6dd46d1f3b2f.png)

And this is how the index _design doc look like.
![image](https://user-images.githubusercontent.com/35466661/63509298-7a99d400-c4e4-11e9-994b-7dcb75c53b4c.png)

And this is what the execution_stats look like
![image](https://user-images.githubusercontent.com/35466661/63509482-f136d180-c4e4-11e9-90fb-991510e7707a.png)

**Comment by garrensmith** [comment]
Is you query it multiple times is it always 3700ms or is it faster? From the JavaScript, it looks like you creating the mango view then querying it versus the map index which has already been created and possibly already built.


________________________________

**Comment by ngspinu** [comment]
Even if I create the index on runtime, or if using one that was created before - the result will always take over 3.5seconds.

The above piece of code is just to get some runtime outputs(they both run ONE time):
1. The _find - using an index - takes 3700ms.
2. Executing a view(that was created before) - 800ms 

They both examine the same amount of data(i.e 15846) - however - the _find is way slower.

**Comment by willholley** [comment]
One difference between Query and MapReduce is that Query will always load
the entire document for each result row (effectively include_docs=true in
MapReduce terms) and then construct a result returning only the specified
fields. This means there's a potentially expensive additional fetch for
each row, particularly so if your documents are large.

In general, indexing with Query is significantly faster than JavaScript
MapReduce but querying is not (though is more flexible).

**Comment by wohali** [comment]
Query also doesn't have the Reduce part of MapReduce yet. If you're really trying to get just a `_count` then you will be faster for JS right now.

**Comment by ngspinu** [comment]
So that means _find will never be as fast as a regular db view.
I guess the docs should be warning about this performance trade you are doing when using _find.

Perhaps this issue be moved on the couchdb docs repo?

**Comment by wohali** [comment]
@ngspinu No, it is still accurate in the large majority of cases.

Reduce support for Mango is being added in #1254.

**Comment by wohali** [comment]
@ngspinu if you want to open a Documentation issue on the specific sentence you found misleading, we can add a qualifier there saying that reduce support for _count, _sum, and _stats is still forthcoming, and that in that specific situation, we still recommend JS views.

**Comment by ngspinu** [comment]
@wohali - this issue was closed, but there is no real response on why `_find` is way slower than running a regular `view`. Is there any way we could get some?
Thank you.
