### ISSUE TITLE
Using `+` in a document `_id`

### ISSUE THREAD

**Issue by harish1992** [apache/couchdb#2144]
While creating document, should `+` sign be percent encoded in `id`?

consider this:

Document creation:

` curl -H 'Content-Type: application/json' -X POST http://127.0.0.1:5984/kitura_test_db -d '{"id": "123+456","key": "123+456"}' `

Response: 

   `{ "ok":true,"id":"fd848ff548334259626e95c9f7010b7c","rev":"1-13e6d186ed0ff9a304acf9e00c6778da"}`

The document get created successfully.

Document retrieval:

`  curl http://127.0.0.1:5984/kitura_test_db/123+456  `

Response:

`{"error":"not_found","reason":"missing"}`

Whereas the request:

`curl http://127.0.0.1:5984/kitura_test_db/123%2B456`

Response:

`{"_id":"123+456","_rev":"1-34d19d1d466727d25183f2553b6c4a80","favorited":false,"value":"value1","truncated":false,"created_at":"Tue Aug 28 21:16:23 +0000 2012"}`

Does retrieval require the `id` to be percent encoded? if so, is this documented somewhere? since `+` allowed character in `url`

**Comment by ceremcem** [comment]
See also #1830

**Comment by jaydoane** [comment]
In your example:
```
curl -H 'Content-Type: application/json' -X POST http://127.0.0.1:5984/kitura_test_db -d '{"id": "123+456","key": "123+456"}'
```
you are using a field named `id` in the document body, which does _not_ actually specify the document id. When creating a new document via POST, use `_id`; see [the docs](https://docs.couchdb.org/en/latest/api/database/common.html#post--db) for details. I think this is confusing, but I assume there's a historical reason for this apparent inconsistency.

**Comment by harish1992** [comment]
So I tried the document creation again by replacing `id` with `_id`:

`curl -H 'Content-Type: application/json' -X POST http://127.0.0.1:5984/kitura_test_db -d '{"_id": "123+456","key": "123+456"}'`

Response:

`{"ok":true,"id":"123+456","rev":"3-70ff850521574a05877483e9828dc65c"}`

So the document gets successfully created. But the catch here is , I am unable to retrieve the document using `_id`.
 
The request `curl http://127.0.0.1:5984/kitura_test_db/123+456`  yields the response

`{"error":"not_found","reason":"missing"}` 

But the request:
`curl http://127.0.0.1:5984/kitura_test_db/_all_docs`  results in

`{"total_rows":2,"offset":0,"rows":[
{"id":"123+456","key":"123+456","value":{"rev":"3-70ff850521574a05877483e9828dc65c"}},
{"id":"123456","key":"123456","value":{"rev":"3-aceebea5ce5cc3aaa33ff520e1ee40dc"}}
]}`

As you can see the document with `_id` `123+456` is still present, but I am unable to retrieve it like other docs  with no `+` in their ids  unless I percent encode `+` like this:

`curl http://127.0.0.1:5984/kitura_test_db/123%2B456` 

Response:

`{"_id":"123+456","_rev":"3-70ff850521574a05877483e9828dc65c","key":"123+456"}`

Why does the CouchDB agent allow the document creation with `+` sign but require percent encoding of  `+` sign for retrieval? 

### Steps to reproduce the issue

Step 1: create a doc with `_id` `123+456` 

  `curl -H 'Content-Type: application/json' -X POST http://127.0.0.1:5984/kitura_test_db -d '{"_id": "123+456","key": "123+456"}'`

Step 2: Retrieve the doc

`curl http://127.0.0.1:5984/kitura_test_db/123+456`

### Expected behaviour

if `_id` with `+` sign is valid then all the DB operations must be possible on document not just creation

**Comment by jaydoane** [comment]
I think the distinction is that in the document body the `+` character does not need to be URL encoded, but it does when it's used in the URL.

**Comment by rnewson** [comment]
Correct, Jay. Url encoding is needed in urls, but not elsewhere. I'm not seeing a problem here.
