### ISSUE TITLE
Request to make the database explorer side panel re-sizable to show the long view names

### ISSUE THREAD

**Issue by nsthakur7** [apache/couchdb#2150]
## Summary
Request to make the database explorer side panel re-sizable to show the long view names.

## Desired Behaviour
To display full long view names on the database explorer side panel.

## Possible Solution
Make the database explorer side panel re-sizable so that user can see the entire view names, especially for the scenario when view names are very long.

Refer the screenshot:
![image](https://user-images.githubusercontent.com/25045937/63822748-761e6100-c9a5-11e9-9edf-3d7640d28fa2.png)

**Comment by wohali** [comment]
This is a Fauxton issue - I'll move the issue for you.

**Comment by iamgollum** [comment]
@nsthakur7 which browser and version are you using? Microsoft Edge?
