### ISSUE TITLE
Compaction hanging on busy sharded system

### ISSUE THREAD

**Issue by user36362992** [apache/couchdb#2158]
## Description

On a busy 3-host sharded CouchDB installation, manually triggered compactions (triggered hourly using a cron) are hanging for hours at a time, and errors are appearing in the logs:

`Aug 30 14:57:17 component-datastore-coll-2.os.anony.com anony-datastore[<0.9806.3>] gen_server couch_compaction_daemon terminated with reason: {compaction_loop_died,{timeout,{gen_server,call,[<0.1227.0>,start_compact]}}}#012  last msg: {'EXIT',<0.9808.3>,{timeout,{gen_server,call,[<0.1227.0>,start_compact]}}}#012     state: {state,<0.9808.3>,[<<"shards/eaaaaa9c-f5555545/anony-collector.1567163470">>]}

Aug 30 14:57:17 component-datastore-coll-2.os.anony.com anony-datastore[<0.9806.3>] CRASH REPORT Process couch_compaction_daemon (<0.9806.3>) with 0 neighbors exited with reason: {compaction_loop_died,{timeout,{gen_server,call,[<0.1227.0>,start_compact]}}} at gen_server:handle_common_reply/8(line:726) <= proc_lib:init_p_do_apply/3(line:247); initial_call: {couch_compaction_daemon,init,['Argument__1']}, ancestors: [couch_secondary_services,couch_sup,<0.213.0>], message_queue_len: 0, messages: [], links: [<0.222.0>], dictionary: [], trap_exit: true, status: running, heap_size: 610, stack_size: 27, reductions: 875`

## Steps to Reproduce

On a busy 3-host sharded CouchDB installation, with auto-compaction disabled, manually trigger compaction using:

`
l(mem3).
l(couch_db).
lists:foreach(fun(Dbname) -> couch_util:with_db(Dbname, fun(Db) -> couch_db:start_compact(Db) end) end, element(2, couch_server:all_databases())).
`

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment

{"couchdb":"Welcome","version":"2.2.0","git_sha":"2a16ec4","features":["pluggable-storage-engines","scheduler"],"vendor":{"name":"The Apache Software Foundation"}}

* CouchDB Version used: 2.2
* Browser name and version: n/a
* Operating System and version: Debian 8.11

ini file:

`
[compactions]
;_default = [{db_fragmentation, "70%"}, {view_fragmentation, "60%"}]
_default = []

[query_server_config]
reduce_limit = false
os_process_limit = 600

[mango]
; Set to true to disable the "index all fields" text index, which can lead
; to out of memory issues when users have documents with nested array fields.
index_all_disabled = true

[attachments]
compression_level = 6

[log]
writer = syslog
level = debug
syslog_host = localhost
syslog_appid = anony-datastore
syslog_facility = local6

; NOTE: a uuid will be added automatically by couchdb on startup into custom.ini
; couchdb writes to the last ini file processed
[couchdb]
; Timeout of 10m for external processes
os_process_timeout = 600000
; Allow doc sizes up to 1GiB
single_max_doc_size = 1073741824

[query_servers]
; 128MiB stack size for JS query servers
javascript = /opt/anony/datastore/bin/couchjs -S 134217728 /opt/anony/datastore/share/server/main.js
coffeescript = /opt/anony/datastore/bin/couchjs -S 134217728 /opt/anony/datastore/share/server/main-coffee.js

[fabric]
; 5m timeout for view requests
; Set to 'infinity' to emulate the behaviour from CouchDB 1.x
request_timeout = 300000

[compaction_daemon]
_default=
~                     
`

## Additional context

Additional log output:

`
Aug 30 14:57:03 component-datastore-coll-2.os.anony.com anony-datastore[<0.10910.3>] Starting compaction for db "shards/eaaaaa9c-f5555545/anony-collector.1567158916" at 0

Aug 30 14:57:03 component-datastore-coll-2.os.anony.com anony-datastore[<0.10916.3>] Compaction process spawned for db "shards/eaaaaa9c-f5555545/anony-collector.1567158916"

Aug 30 14:57:04 component-datastore-coll-2.os.anony.com anony-datastore[<0.218.0>] New task status for <0.10916.3>: [{changes_done,0},{database,<<"shards/eaaaaa9c-f5555545/anony-collector.1567158916">>},{progress,0},{started_on,1567177024},{total_changes,0},{type,database_compaction},{updated_on,1567177024}]

Aug 30 14:57:11 component-datastore-coll-2.os.anony.com anony-datastore[<0.1669.0>] Starting compaction for db "shards/caaaaa9e-d5555547/anony-collector.1567163470" at 38131

Aug 30 14:57:11 component-datastore-coll-2.os.anony.com anony-datastore[<0.11190.3>] Compaction process spawned for db "shards/caaaaa9e-d5555547/anony-collector.1567163470"

Aug 30 14:57:11 component-datastore-coll-2.os.anony.com anony-datastore[<0.9808.3>] Fragmentation for database 'shards/eaaaaa9c-f5555545/anony-collector.1567163470' is 35%, estimated space for compaction is 3043462 bytes.

Aug 30 14:57:17 component-datastore-coll-2.os.anony.com anony-datastore[<0.9806.3>] gen_server couch_compaction_daemon terminated with reason: {compaction_loop_died,{timeout,{gen_server,call,[<0.1227.0>,start_compact]}}}#012  last msg: {'EXIT',<0.9808.3>,{timeout,{gen_server,call,[<0.1227.0>,start_compact]}}}#012     state: {state,<0.9808.3>,[<<"shards/eaaaaa9c-f5555545/anony-collector.1567163470">>]}

Aug 30 14:57:17 component-datastore-coll-2.os.anony.com anony-datastore[<0.9806.3>] CRASH REPORT Process couch_compaction_daemon (<0.9806.3>) with 0 neighbors exited with reason: {compaction_loop_died,{timeout,{gen_server,call,[<0.1227.0>,start_compact]}}} at gen_server:handle_common_reply/8(line:726) <= proc_lib:init_p_do_apply/3(line:247); initial_call: {couch_compaction_daemon,init,['Argument__1']}, ancestors: [couch_secondary_services,couch_sup,<0.213.0>], message_queue_len: 0, messages: [], links: [<0.222.0>], dictionary: [], trap_exit: true, status: running, heap_size: 610, stack_size: 27, reductions: 875

Aug 30 14:57:17 component-datastore-coll-2.os.anony.com anony-datastore[<0.222.0>] Supervisor couch_secondary_services had child compaction_daemon started with couch_compaction_daemon:start_link() at <0.9806.3> exit with reason {compaction_loop_died,{timeout,{gen_server,call,[<0.1227.0>,start_compact]}}} in context child_terminated
Aug 30 14:57:17 component-datastore-coll-2.os.anony.com anony-datastore[<0.222.0>] Supervisor couch_secondary_services started couch_compaction_daemon:start_link() at pid <0.11344.3>

Aug 30 14:57:17 component-datastore-coll-2.os.anony.com anony-datastore[<0.11346.3>] Fragmentation for database 'shards/eaaaaa9c-f5555545/anony-collector.1566987762' is 0%, estimated space for compaction is 12464 bytes.
`

Output of `curl -s 127.0.0.1:5984/_active_tasks`:

`
[{"node":"couchdb@component-datastore-coll-2.os.anony.com","pid":"<0.4650.5>","changes_done":0,"database":"shards/caaaaa9e-d5555547/anony-anony.1567163470","progress":0,"started_on":1567178532,"total_changes":1229,"type":"database_compaction","updated_on":1567178532},{"node":"couchdb@component-datastore-coll-3.os.anony.com","pid":"<0.14623.35>","changes_done":0,"database":"shards/0aaaaaaa-15555553/anony-anony.1567163470","progress":0,"started_on":1567179490,"total_changes":1256,"type":"database_compaction","updated_on":1567179490},{"node":"couchdb@component-datastore-coll-3.os.anony.com","pid":"<0.30161.46>","changes_done":0,"database":"shards/3ffffffc-4aaaaaa5/anony-anony.1567163470","progress":0,"started_on":1567179511,"total_changes":1241,"type":"database_compaction","updated_on":1567179511},{"node":"couchdb@component-datastore-coll-3.os.anony.com","pid":"<0.3713.47>","changes_done":0,"database":"shards/aaaaaaa0-b5555549/anony-anony.1567163470","progress":0,"started_on":1567179555,"total_changes":1225,"type":"database_compaction","updated_on":1567179555},{"node":"couchdb@component-datastore-coll-3.os.anony.com","pid":"<0.4069.47>","changes_done":0,"database":"shards/35555552-3ffffffb/anony-anony.1567163470","progress":0,"started_on":1567179509,"total_changes":1249,"type":"database_compaction","updated_on":1567179509},{"node":"couchdb@component-datastore-coll-3.os.anony.com","pid":"<0.419.47>","changes_done":0,"database":"shards/00000000-0aaaaaa9/anony-anony.1567163470","progress":0,"started_on":1567179487,"total_changes":1238,"type":"database_compaction","updated_on":1567179487},{"node":"couchdb@component-datastore-coll-3.os.anony.com","pid":"<0.4381.47>","changes_done":1254,"database":"shards/4aaaaaa6-5555554f/anony-anony.1567163470","progress":100,"started_on":1567179516,"total_changes":1254,"type":"database_compaction","updated_on":1567179608},{"node":"couchdb@component-datastore-coll-3.os.anony.com","pid":"<0.4424.47>","changes_done":0,"database":"shards/5ffffffa-6aaaaaa3/anony-anony.1567163470","progress":0,"started_on":1567179525,"total_changes":1250,"type":"database_compaction","updated_on":1567179525},{"node":"couchdb@component-datastore-coll-3.os.anony.com","pid":"<0.4455.47>","changes_done":0,"database":"shards/55555550-5ffffff9/anony-anony.1567163470","progress":0,"started_on":1567179518,"total_changes":1248,"type":"database_compaction","updated_on":1567179518},{"node":"couchdb@component-datastore-coll-3.os.anony.com","pid":"<0.5063.47>","changes_done":1230,"database":"shards/7ffffff8-8aaaaaa1/anony-anony.1567163470","progress":100,"started_on":1567179548,"total_changes":1230,"type":"database_compaction","updated_on":1567179607},{"node":"couchdb@component-datastore-coll-3.os.anony.com","pid":"<0.5065.47>","changes_done":0,"database":"shards/8aaaaaa2-9555554b/anony-anony.1567163470","progress":0,"started_on":1567179551,"total_changes":1222,"type":"database_compaction","updated_on":1567179551},{"node":"couchdb@component-datastore-coll-3.os.anony.com","pid":"<0.6359.47>","changes_done":0,"database":"shards/b555554a-bffffff3/anony-anony.1567163470","progress":0,"started_on":1567179568,"total_changes":1231,"type":"database_compaction","updated_on":1567179568},{"node":"couchdb@component-datastore-coll-3.os.anony.com","pid":"<0.8310.47>","changes_done":0,"database":"shards/6aaaaaa4-7555554d/anony-anony.1567163470","progress":0,"started_on":1567179605,"total_changes":119,"type":"database_compaction","updated_on":1567179605},{"node":"couchdb@component-datastore-coll-3.os.anony.com","pid":"<0.8465.47>","changes_done":0,"database":"shards/9ffffff6-aaaaaa9f/anony-anony.1567163470","progress":0,"started_on":1567179610,"total_changes":142,"type":"database_compaction","updated_on":1567179610},{"node":"couchdb@component-datastore-coll-3.os.anony.com","pid":"<0.8473.47>","changes_done":0,"database":"shards/7555554e-7ffffff7/anony-anony.1567163470","progress":0,"started_on":1567179605,"total_changes":120,"type":"database_compaction","updated_on":1567179605},{"node":"couchdb@component-datastore-coll-3.os.anony.com","pid":"<0.8643.47>","changes_done":5,"database":"shards/9555554c-9ffffff5/anony-anony.1567163470","progress":100,"started_on":1567179608,"total_changes":5,"type":"database_compaction","updated_on":1567179608}]
`

**Comment by rnewson** [comment]
the couch_compaction_daemon crashes because of this line;

```
{ok, _} = couch_db:start_compact(Db),
```

couch_db:start_compact(Db) waits for 5000 ms for a reply, and in a busy system this might not be sufficient.

Smoosh, the replacement compaction daemon in CouchDB 3.0, does this instead;

```
DbPid ! {'$gen_call', {self(), Ref}, start_compact},
```

That is, we do not block for a reply.
