### ISSUE TITLE
Remove `delayed_commits` setting

### ISSUE THREAD

**Issue by kocolosk** [apache/couchdb#2165]
Documentation of deprecation:

https://github.com/apache/couchdb/blob/103a0624f309ea0d796176a55eb5faea68f26047/test/javascript/tests/delayed_commits.js#L16

**Comment by davisp** [comment]
@kocolosk In #2208 @nickva did the initial work to remove delayed_settings and I mentioned on that review that we may want to remove `fsync_options` lest we have people trying to move to disabling those once `delayed_commits` is gone.

Should we include removing that as part of this you reckon?

**Comment by kocolosk** [comment]
Good point. I'm OK to remove those options as well.

**Comment by davisp** [comment]
Cool beans.

**Comment by kocolosk** [comment]
All done here.
