### ISSUE TITLE
Remove support for ?stale query parameter in favor of `stable` and `update_after` combo

### ISSUE THREAD

**Issue by kocolosk** [apache/couchdb#2169]
Personally I'd probably close this one as a WONTFIX but copying from our earlier release notes:

* The ``stale`` parameter for views and ``_find`` has been deprecated in favour of two new parameters: ``stable`` and ``update``. The old ``stale=ok`` behaviour is equivalent to ``stable=true&update=false``, and the old ``stale=update_after`` behaviour is equivalent to ``stable=true&update=lazy``. The deprecated ``stale`` parameter will be removed in CouchDB 3.0.

**Comment by rnewson** [comment]
Given that the behaviours themselves continues to be supported (albeit independently), I don't think we should remove these options; they are both reasonable combinations of the new `stable` and `update` options.

+1 for a WONTFIX from me also.

**Comment by wohali** [comment]
I don't really care either way, but this was something that whomever put in the new behaviour (@banjiewen perhaps?) wanted to deprecate.

**Comment by kocolosk** [comment]
Anyone is welcome to reopen this and advocate for it but for now I'm closing this out.
