### ISSUE TITLE
Document new management subsystems (smoosh, ioq, ken)

### ISSUE THREAD

**Issue by kocolosk** [apache/couchdb#2171]
- [x] smoosh
- [x] ioq
- [x] ken

**Comment by kocolosk** [comment]
Smoosh and IOQ both have extensive operator guides in the actual code repos; these could probably be edited and ported over to docs.couchdb.org. Ken does not.

**Comment by kocolosk** [comment]
https://github.com/apache/couchdb-documentation/pull/438

**Comment by kocolosk** [comment]
https://github.com/apache/couchdb-documentation/pull/439

**Comment by denib** [comment]
IOQ docs not merged. There's a ML thread to figure out what needs to be documented.

**Comment by janl** [comment]
ioq merged, closing
