### ISSUE TITLE
Port parallelization code from _all_docs to _bulk_get

### ISSUE THREAD

**Issue by kocolosk** [apache/couchdb#2172]
## Summary

We currently have two endpoints for retrieving multiple documents by ID in a single request: `_all_docs` and `_bulk_get`. The former endpoint has some code to parallelize the requests for documents while the latter pulls them from disk serially. This performance delta isn't documented anywhere and so our users are often leaving latency on the table.

## Desired Behaviour

There should be no perf difference between these two endpoints.

**Comment by nickva** [comment]
_bulk_get is optimized and now now quite a bit faster: https://github.com/apache/couchdb/pull/4238

Closing as complete.
