### ISSUE TITLE
call to Function() blocked by CSP

### ISSUE THREAD

**Issue by allemanfredi** [apache/couchdb#2185]
I'm trying to use couchdb but i receive the following error: 

`function raised error: (new Error(\"call to Function() blocked by CSP\"`

I read that other people have had a similar issue but for the `eval` function, are they similar by chance?

**Comment by popojargo** [comment]
Is this a Fauxton error or an error resulting from a map/reduce?

**Comment by wohali** [comment]
Looks like a MapReduce error.

Please use the same functionality to re-enable Function(), with the same warnings provided to other users why that's not a good thing to enable.

See #916 and https://docs.couchdb.org/en/stable/whatsnew/2.3.html for the new way to define a replacement.

**Comment by allemanfredi** [comment]
@wohali thank you!! I solved by refactoring code which causes CSP problems.
