### ISSUE TITLE
[Sporadic] 201 response but document not created

### ISSUE THREAD

**Issue by priyath** [apache/couchdb#2187]
I understand CouchDB 1.6.1 is not supported but would appreciate some help from the community for a very a weird problem our production CouchDB has been facing. I am quite lost on this one. Hoping someone might have some clues on how I could debug this further. 

## Description
We have a production setup (think Point of Sales) where 3 registers (A, B, C) have its own local Couch database. One of the 3 acts as a master ( so all devices write to the same CouchDB) and all 3 devices sync with a Cloud CouchDB to keep data in sync.

One of our workflows in the system requires a document to be created and then the same document to be accessed via a view. We have faced a very strange sporadic issue where the document creation seemingly succeeds but when queried via the view, the document does not exist.

One example was when Register A created document `df3176c7df394ffe94bccd7337a908dd` in register B (master). Master CouchDB logs indicated the following for this event:

`01 Sep 2019 22:32:20 GMT] [info] [<0.8663.3>] 10.10.10.120 - - PUT /databasename/df3176c7df394ffe94bccd7337a908dd 201`

As you can see, the logs indicate a 201 but upon investigation, this document was not found in the database! Further, no entry corresponding to this document was found in the _changes feed of the database as well.

The only workaround as of now is to either switch the master device or completely delete all the view indexes for the devices and rebuild them from scratch. 

My main question is can there be a case where a document creation completes with a 201 but the document may not actually get created in the database?

## Steps to Reproduce
Unable to reproduce since this issue is sporadic.

## Expected Behaviour
The document should be created as expected and be available via the view.

## Your Environment

* CouchDB Version used: 1.6.1
* Browser name and version: Chrome 
* Operating System and version: Ubuntu 14.04

## Additional context
In the past, we have faced problems with our CouchDB views growing in size (a few GBs sometimes!) and we have also noticed a substantial number of conflicting revision trees in some of our documents. I wonder if this could be somehow related to this issue.

**Comment by kocolosk** [comment]
Hi, the only way the database intentionally allows for this to happen is if you have `delayed_commits` enabled and the system crashes in the one second window between when the document was written and the commit occurs.

I'm having a little trouble following this workaround:

> The only workaround as of now is to either switch the master device or completely delete all the view indexes for the devices and rebuild them from scratch.

Are you saying that the `df3176c7df394ffe94bccd7337a908dd` did show up on the other database instances at some point? That would be truly strange.

**Comment by wohali** [comment]
No response for ~6 months; closing.
