### ISSUE TITLE
Support Geospatial Queries

### ISSUE THREAD

**Issue by sain801028** [apache/couchdb#2194]
My team is about to move from mongodb to couchdb, because mongodb is not easy to configure and operate...etc.

I hope to support geospatial queries, the team has used mongodb geospatial queries, hope that couchdb will also support in the future.

**Comment by jiangphcn** [comment]
I wrote one wiki page to help bind hastings/easton into couchdb to support geospatial queries in 2017. It might not be up-to-date but I believe that this can help you in some extent. 

https://github.com/cloudant-labs/hastings/wiki/Introduce-GeoSpatial-Index-To-CouchDB

**Comment by wohali** [comment]
The 3rd party solution with hastings and easton is the best way to do geospatial in CouchDB.

Because of licensing restrictions we are unable to ship Geospatial in CouchDB downloads, sorry about that.
