### ISSUE TITLE
Add WeatherReport and its dependencies

### ISSUE THREAD

**Issue by jaydoane** [apache/couchdb#2212]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

The CouchDB community [has expressed interest](http://mail-archives.apache.org/mod_mbox/couchdb-dev/201908.mbox/%3CCAL5mLEsD5KsE0tq8hF3%2B9zkCD8c11Jg7UKnuEvQE79i1agS6-A%40mail.gmail.com%3E) in accepting a donation by IBM Cloudant of the WeatherReport diagnostic tool and its dependencies. WeatherReport is a port of [riaknostic](https://github.com/basho/riaknostic), with modifications to make it relevant for CouchDB/Cloudant.

## Desired Behaviour

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

It should be possible to run an escript against a currently running CouchDB cluster in the following manner, and get similar output:
```
$ ./weatherreport --etc ~/proj/couchdb/dev/lib/node1/etc/ -a
['node1@127.0.0.1'] [error] Local search node at 'clouseau@127.0.0.1' not
responding: pang
['node2@127.0.0.1'] [error] Local search node at 'clouseau@127.0.0.1' not
responding: pang
['node3@127.0.0.1'] [error] Local search node at 'clouseau@127.0.0.1' not
responding: pang
['node1@127.0.0.1'] [notice] Data directory
/Users/jay/proj/couchdb/dev/lib/node1/data is not mounted with 'noatime'.
Please remount its disk with the 'noatime' flag to improve performance.
['node2@127.0.0.1'] [notice] Data directory
/Users/jay/proj/couchdb/dev/lib/node2/data is not mounted with 'noatime'.
Please remount its disk with the 'noatime' flag to improve performance.
['node3@127.0.0.1'] [notice] Data directory
/Users/jay/proj/couchdb/dev/lib/node3/data is not mounted with 'noatime'.
Please remount its disk with the 'noatime' flag to improve performance.
returned 1
```

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

The WeatherReport OTP application also depends on another Cloudant repository called Custodian (which will also be donated) and [recon](http://ferd.github.io/recon).

Some work needs to be done on those repos before they can be donated. Extant branches need to be merged to master, and Custodian files all need to have license headers added, etc. Once the existing repos have been cleaned up, presumably they should be forked into ASF repos (although I'm unfamiliar with this part of the process, and will need assistance).

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

While WeatherReport has been deployed to production at Cloudant for years, it hasn't gotten much use since operators tend to reach for more familiar tools. However, it's been a lot more useful in the on-prem Cloudant Local offering, where customers are typically much less experienced at operating the product. In those deployments, WeatherReport's output has often been useful to Cloudant's support staff in helping customers debug (remote) cluster issues.

**Comment by nickva** [comment]
WeatherReport and recon are now in 3.x
