### ISSUE TITLE
Release 2.3.2

### ISSUE THREAD

**Issue by adrienverge** [apache/couchdb#2213]
While waiting for 3.0.0 to be out, is it possible to release a new intermediate version, so we can benefit from https://github.com/apache/couchdb-documentation/pull/425? (amongst others)

It is needed to package CouchDB for CentOS 8 and Fedora 32, where Erlang < 22 is not available anymore.

**Comment by adrienverge** [comment]
Sorry for pushing this question, but since last week, Erlang 21 was dropped from Fedora 31, and is not available anymore. Which means we cannot compile the last CouchDB stable release (2.3.1), because it requires Erlang < 22 (cf. https://github.com/apache/couchdb/issues/2069 and https://github.com/apache/couchdb/commit/9d143ba).

Is it possible to have an intermediate CouchDB release (2.3.2?) so we can compile with Erlang 22?

**Comment by wohali** [comment]
@adrienverge If you want to help see this happen. propose a backport PR against the 2.3.x branch that includes all the patches cherry-picked from `master` to make this happen.

**Comment by wohali** [comment]
@adrienverge the other option is to use something like kerl when preparing your packages instead.

**Comment by wohali** [comment]
CentOS 8 packages are now published at the usual place. Installation instructions:

http://docs.couchdb.org/en/stable/install/unix.html#installation-using-the-apache-couchdb-convenience-binary-packages

and use `8` instead of `7` or `6`.

**Comment by adrienverge** [comment]
> propose a backport PR against the 2.3.x branch that includes all the patches cherry-picked from master to make this happen.

Doing this creates many conflicts, more than I would expect. I tried to resolve a few, but I'm not familiar with Erlang nor CouchDB internals, so I stopped rather than creating a bugged release.

To be honest, I'd be more confident to see a release created by someone who maintains CouchDB.
I understand that you don't have much time for that. But is there a date planned for the next minor release?


> the other option is to use something like kerl

We're creating "pseudo-official" (COPR) RPM packages for Fedora and CentOS, so using the standard RPM way (`rpmbuild`) is required.

**Comment by wohali** [comment]
The PMC team doesn't plan to do another CouchDB release before 3.0.0, sorry. The tasks left before that occurs are listed here: https://github.com/apache/couchdb/projects/1

**Comment by wohali** [comment]
Now that 3.x is out, the chances of us doing a 2.3.2 are slim-to-none. The only foreseeable reasons we might do this are:

* CVE against CouchDB 2.x
* Marking features as deprecated that are removed in a 3.x version

We don't anticipate any of the latter, but we'll keep our eyes on the former and give it consideration.
