### ISSUE TITLE
Only check DbVersion if metadataVersion has changed

### ISSUE THREAD

**Issue by kocolosk** [apache/couchdb#2224]
## Summary

We use a single key for each database to track the versioning of important database-specific content like validation functions, security properties, and revision stemming limits. Currently we retrieve this key on every request to ensure those properties are all still current, which adds latency and creates a hot spot in a cluster for any database with a high request load.

The proposal here is to increment both the database-specific `DbVersion` *and* the global `metadataVersion` whenever any of these properties changes on any database, and to skip reading the `DbVersion` key on each request unless the `metadataVersion` has changed.

The tradeoff is that any existing use of `metadataVersion` will experience more frequent cache invalidations. Not super-frequent, mind you; even in multi-tenant environments with thousands of databases we don't see this metadata change all that often.

## Desired Behaviour

Lower request latency and elimination of a potential read hotspot in FoundationDB.

## Additional context

Some relevant discussion of this exact topic in the FoundationDB Forums:

https://forums.foundationdb.org/t/sharing-the-metadataversionkey-for-multiple-tenants/

**Comment by nickva** [comment]
Worked on this @davisp https://github.com/apache/couchdb/pull/2261

That sets up the cache to take advantage of the metadata version key. Will switch to using the new feature in a separate commit.

**Comment by nickva** [comment]
This is fixed. 

https://github.com/apache/couchdb/blob/prototype/fdb-layer/src/fabric/src/fabric2_fdb.erl#L1867-L1884
