### ISSUE TITLE
Reuse the open transaction for include_docs=true responses

### ISSUE THREAD

**Issue by kocolosk** [apache/couchdb#2225]
## Summary

CouchDB should reuse the open transaction when embedding document bodies into a response where the user has requested `include_docs=true`. Currently each document is loaded using a separate transaction. For example, here's a trace of a request to `/foo/_all_docs?limit=3&include_docs=true`:

![all_docs](https://user-images.githubusercontent.com/16679/66127674-41ac4f00-e5ba-11e9-8fbf-5d4e1dce0066.png)

The purple elements are new transactions, so you can see that we're using a separate transaction for each of the three included documents. We can significantly reduce latency and load on FoundationDB by not doing that.

Performance aside, reusing the transaction is the **correct** behavior. If we start a new transaction we run the risk that the document revision has been overwritten since the beginning of the top-level response and so we won't see it.

## Desired Behaviour

Responses with `include_docs=true` should be delivered in a single transaction.

## Possible Solution

As an example, we can pass the transaction object into the initial accumulator for the `view_cb/2` function and use it when retrieving the document here:

https://github.com/apache/couchdb/blob/ff2cdb84f639ea26ac7b1ad85abb0a49c5141c74/src/chttpd/src/chttpd_db.erl#L988

**Comment by nickva** [comment]
A simple thing to try would be to wrap the whole db request function in a transaction:

https://github.com/apache/couchdb/blob/ff2cdb84f639ea26ac7b1ad85abb0a49c5141c74/src/chttpd/src/chttpd_db.erl#L385-L386

So it would look something like:

```
   fabric2_fdb:transactional(Db, fun(TxDb) -> Fun(Req, TxDb) end)
```

We might hit issues with transaction size limits or timeouts sooner.  For reads, values are not included in the size limit, but keys and conflicts ranges are. Perhaps we could track transaction size estimates and/or age and do something clever like start a new transaction if we reach the limits. Perhaps snapshot reads might also be useful here, as the long transaction could now easier conflict with other updates and retry too often.

**Comment by kocolosk** [comment]
As a general rule I think we should not stitch together multiple FDB transactions underneath a single CouchDB operation. A good exception would be a continuous `_changes` feed, where there's already no expectation that the response is generated from a single version of the underlying database. I realize this could shorten response sizes, but I think that's generally a good direction for us to be taking the project.

Snapshot reads are only useful to relax the isolation around a read performed as part of a RW transaction in FDB. A read-only transaction that never commits doesn't increase the likelihood of conflicts.

**Comment by nickva** [comment]
Yeah `_changes` feeds might seem like a place to do multiple transactions like that. I suppose  `_all_docs` results would return a timeout or transaction size error and clients would have to interpret that and paginate through the data. 

> Snapshot reads are only useful to relax the isolation around a read performed as part of a RW transaction in FDB

Ah you're right. It won't be much help here, these are all read transactions. (Maybe a tiny performance boost since a snapshot won't need to start gathering conflict ranges).

**Comment by rnewson** [comment]
https://github.com/apache/couchdb/pull/3243 should cover this?

**Comment by rnewson** [comment]
Confirmed that the `cache_grv` work achieves this. I print the GRV within the fold_docs transaction and the get_body_wait transactions and they are all the same.

```diff
diff --git a/src/fabric/src/fabric2_db.erl b/src/fabric/src/fabric2_db.erl
index a310470ea..352b30946 100644
--- a/src/fabric/src/fabric2_db.erl
+++ b/src/fabric/src/fabric2_db.erl
@@ -946,9 +946,12 @@ fold_docs(Db, UserFun, UserAcc0, Options) ->
     fabric2_fdb:transactional(Db, fun(TxDb) ->
         try
             #{
+              tx := Tx,
                 db_prefix := DbPrefix
             } = TxDb,

+couch_log:error("fold_docs ~p", [erlfdb:wait(erlfdb:get_read_version(Tx))]),

             Prefix = erlfdb_tuple:pack({?DB_ALL_DOCS}, DbPrefix),
             Meta = get_all_docs_meta(TxDb, Options),

diff --git a/src/fabric/src/fabric2_fdb.erl b/src/fabric/src/fabric2_fdb.erl
index 5394f27bb..8b2a19535 100644
--- a/src/fabric/src/fabric2_fdb.erl
+++ b/src/fabric/src/fabric2_fdb.erl
@@ -772,7 +772,7 @@ get_doc_body_wait(#{} = Db0, DocId, RevInfo, Future) ->
     #{
         tx := Tx
     } = Db = ensure_current(Db0),
-
+    couch_log:error("get_doc_body ~p", [erlfdb:wait(erlfdb:get_read_version(Tx))]),
     #{
         rev_id := {RevPos, Rev},
         rev_path := RevPath
```

**Comment by nickva** [comment]
#3243 would cover it, but I thought we already fixed this for most general cases like _all_docs variants and view rows emits. I see for _all_docs, _design_docs and _local_docs we use `TxDb` https://github.com/apache/couchdb/blob/main/src/fabric/src/fabric2_db.erl#L971, and for views https://github.com/apache/couchdb/blob/main/src/couch_views/src/couch_views_reader.erl#L199

The code in chttpd might still catch some edge cases though from other requests which use the `view_cb` callback
