### ISSUE TITLE
Replication target with only DB name replicates to node-local port

### ISSUE THREAD

**Issue by segevfiner** [apache/couchdb#2239]
## Description

When you create a replication that specifies a `target` using only a database name, CouchDB will replicate to the node local port which is unexpected and not really useful. Since AFAIK `user_ctx` only works when you specify the `source`/`target` as only a DB name that also neuters that feature and basically local DB references in replications in general.

## Steps to Reproduce

Create a replication like this:
```json
{
  "_id": "foo",
  "source": "http://some-other-db:5984/foo",
  "target": "foo",
  "continuous": true,
  "user_ctx": {"name": "admin","roles": ["_admin"]}, "owner": "admin"}
}
```

## Expected Behaviour

The target database is replicated on the standard clustered port (5984). But it is replicated to the node local (5986) port instead.

## Your Environment

* CouchDB Version used: 2.3.1
* Browser name and version: Firefox 69.0.2
* Operating System and version: macOS 10.14.6

**Comment by wohali** [comment]
This has been resolved in CouchDB 3.0.0. We do not expect another 2.x release at this point. Thanks for this report!
