### ISSUE TITLE
Validator of replicator should respond with 400 instead 407

### ISSUE THREAD

**Issue by vmatyusGitHub** [apache/couchdb#2241]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

The validation document of `_replicator` database should answer with `400 Bad Reqest` instead of `403 Forbidden`

## Steps to Reproduce

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )
```
curl -v -X PUT http://localhost:5984/_replicator/test -d '{"source":"http://admin:pass@localhost:5984/animaldb","target":"http://admin:pass@localhost:5984/newanimal","query_params": "dog"}'
```
```
...
< HTTP/1.1 403 Forbidden
< Cache-Control: must-revalidate
< Content-Length: 77
< Content-Type: application/json
< Date: Mon, 03 Jun 2019 15:13:13 GMT
< Server: CouchDB/2.3.0 (Erlang OTP/19)
< X-Couch-Request-ID: 09b71f560a
< X-CouchDB-Body-Time: 0
< 
{"error":"forbidden","reason":"The `query_params' field must be an object."}
```
## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )
This is a bad request from the user and should be status code 400

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB Version used: 2.3.1
* Browser name and version: curl
* Operating System and version: MacOS 14.0

## Additional context

[TIP]:  # ( Add any other context about the prbolem here. )

**Comment by nickva** [comment]
400 is more correct, however 403 has been traditionally used by CouchDB as a response from validate doc update (VDU) functions. At some point `_replicator` docs were also validated by an auto-injected design doc. Now they are re-written as an Erlang function, however the validation response was preserved for backwards compatibility.

Another aspect here is that a 403 is also a signal to a replicator to skip over a reject document on the target. That might be in the odd case or replicating `_replicator` dbs themselves. At some point we used to skip over any 4xx error, but that's not the case [any longer](https://github.com/apache/couchdb/commit/d4d49077d3ecca7d5122f4ba0961fa38f6fa597a). That sort of argues that we should just preserve the 403 response.

**Comment by nickva** [comment]
@rnewson Thanks for explaining. That makes sense. I erroneously thought 403 was used mostly in the context of authentication/authorization and we just repurposed it for VDU validation, but that's not the case.

In light of that I think we can close it as "works as expected".
