### ISSUE TITLE
Single element `keys` is not treated the same as `key`

### ISSUE THREAD

**Issue by vmatyusGitHub** [apache/couchdb#2243]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )
During an execution of a view with reduce function, if there is `key` query parameter
specified, it will return with correct values. However, if there is `keys` query parameter
with only one key specified, then the CouchDB requires to use `group=true` additionally. 

## Steps to Reproduce

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )
Execute a view with reduce function with `keys` query param, that contains only one element.
```
curl $URL/db/_design/ddoc/_view/view?keys=["key1"]
```
```
400 Bad Request
{
    "error": "query_parse_error",
    "reason": "Multi-key fetchs for reduce views must use `group=true`"
}
```
## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )
Should display the result as the single `key` query parameter does.
```
curl $URL/db/_design/ddoc/_view/view?key="key1"
```
```
200 OK
{
    "rows": [
        {
            "key": null,
            "value": 1
        }
    ]
}
```
The implementation should check the length of keys not just whether key has been used in preference to keys.
## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB Version used: 2.3.1
* Browser name and version: Postman
* Operating System and version: MacOS 14.0

## Additional context

[TIP]:  # ( Add any other context about the prbolem here. )
It is also possible to deprecate the single form of key from the API anyway as it reduces this type of complexity.

**Comment by pavellzubkov** [comment]
same problem... very nasty bug...(
