### ISSUE TITLE
Partitioning not working on Debian Buster x64

### ISSUE THREAD

**Issue by vintzl** [apache/couchdb#2245]
I am using couchdb 2.3.1-1~buster (in Debian Buster)

following this https://docs.couchdb.org/en/master/partitioned-dbs/index.html

    curl -X PUT http://admin:password@127.0.0.1:5984/testing?partitioned=true

        {"ok":true}

    curl http://127.0.0.1:5984/testing|jq 

        {
          "db_name": "testing",
          "purge_seq": "x-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "update_seq": "x-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "sizes": {
            "file": 33992,
            "external": 0,
            "active": 0
          },
          "other": {
            "data_size": 0
          },
          "doc_del_count": 0,
          "doc_count": 0,
          "disk_size": 33992,
          "disk_format_version": 7,
          "data_size": 0,
          "compact_running": false,
          "cluster": {
            "q": 8,
            "n": 1,
            "w": 1,
            "r": 1
          },
          "instance_start_time": "0"
        }

The following property is missing

    "props": {
        "partitioned": true
    },

after putting some data:

    {
        "_id": "person:0001",
        …
    }

and quering  `http://127.0.0.1:5984/testing/_partition/person`

I get

    `{"error":"not_found","reason":"missing"}`

**Comment by wohali** [comment]
Partitioning will be in CouchDB 3.0.

You are looking at the `master` branch of the documentation, try here:

https://docs.couchdb.org/en/stable/
