### ISSUE TITLE
POST on /db with invalid db name returns 404 instead of 400

### ISSUE THREAD

**Issue by b0wter** [apache/couchdb#2246]
## Description
Trying to add a document to a database using an invalid database name returns NOT FOUND instead of BAD REQUEST. See the [documentation](https://docs.couchdb.org/en/stable/api/database/common.html#post--db)

## Steps to Reproduce
```bash
$ curl http://localhost:5984/00-this-[is]-{an}-inv@lid-name/ -X POST -H "Content-Type: application/json" -d '{"servings":4,"subtitle":"Delicious with fresh bread","title":"Fish Stew"}'

{"error":"not_found","reason":"Database does not exist."}
```

## Expected Behaviour
Should return:
```
{"error":"bad_request","reason":"Invalid database name."}
```

## Your Environment
I've tried this with CouchDb version v.2.3.1. inside docker (using the official image from dockerhub).

**Comment by noahshaw11** [comment]
After further testing, I am unsure how the author @b0wter was able to create a database with the invalid name `00-this-[is]-{an}-inv@lid-name`. Using bash, I receive
```
$ curl -X PUT http://localhost:15984/00-this-[is]-{an}-inv@lid-name/ -H"Authorization: Basic YWRtOnBhc3M="
{"error":"illegal_database_name","reason":"Name: '00-this-[is]-an-inv@lid-name'. Only lowercase characters (a-z), digits (0-9), and any of the characters _, $, (, ), +, -, and / are allowed. Must begin with a letter."}
```
which is expected.
However, running
```
$ curl http://localhost:15984/00-this-[is]-{an}-inv@lid-name/ -X POST -H'Authorization: Basic YWRtOnBhc3M=' -H "Content-Type: application/json" -d '{"servings":4,"subtitle":"Delicious with fresh bread","title":"Fish Stew"}'
```
before trying to create the database does return `{"error":"not_found","reason":"Database does not exist."}`. This is correct since the database has not been created. Perhaps this has been fixed since the opening of this ticket.

**Comment by b0wter** [comment]
After reading the documentation it seemed logical to me that the api should return "400 - database name invalid" because otherwise it would not have been specified in the documentation since it will never be returned. 

After checking more parts of the `/{db}` documentation it seems to me that the return codes/reasons are the same for all http methods and make perfect sense for delete/put/get and post is just the odd one. 
Usually I would not have noticed but I am writing a CouchDB client and use the documentation to define my integration tests.

I'll close this issue and will put up a pr for an update of the documentation and see where that goes.
