### ISSUE TITLE
Cluster setup does not create IOQ stats database

### ISSUE THREAD

**Issue by kocolosk** [apache/couchdb#2249]

**Comment by wohali** [comment]
In light of your proposal to keep IOQ1 mainline, should this have an "if IOQ2 enabled, create IOQ stats database" thing? And if so, how do we check which one has been enabled?

**Comment by jaydoane** [comment]
> how do we check which one has been enabled

According to [the docs](https://github.com/apache/couchdb-ioq/blob/master/IOQ2.md#enable-ioq2), we can tell if IOQ2 is enabled using:
```erlang
ioq:ioq2_enabled().
```

**Comment by kocolosk** [comment]
I think we should actually not create the IOQ database, as the statistics collection every minute will end up surprising people who aren't expecting such a large internal database. I'm instead going to submit a request to reduce the logging level for the error message and close this ticket once that's merged.

**Comment by janl** [comment]
+1

**Comment by janl** [comment]
This is done: https://github.com/apache/couchdb-ioq/commit/4843f3709b4be997cf8424c44f856523fd31b7d1

**Comment by kocolosk** [comment]
So, that patch does address this issue, but I'd like to make a more substantive switch to the IOQ system that simplifies the configuration (and removes the stats database as well). The PR for that is now up at apache/couchdb#2408
