### ISSUE TITLE
Couchdb view become unusable 

### ISSUE THREAD

**Issue by technipfmc-houston** [apache/couchdb#2252]
View becomes unavailable.    

**Please look at the couchdb logs error in attached file**.  I have the full log if you would like for me to send this was just pieces.

Application goes down as the view is used throughout the application 

(https://github.com/apache/couchdb/files/3720237/couchdb.txt)
when hitting the view in _design/Fieldling/_view all views have the below error
with futon ie
http://localhost:5984/_utils/database.html?enbasemobilefmc/_design/fieldlink/_view/authorization

error accessing view no response.

We restore the server once already and it work for a little while.

see different type of Errors in the couchdb logs attached as couchdb.txt:  I tried to copy the file I assume it did attach
[couchdb.txt](https://github.com/apache/couchdb/files/3720240/couchdb.txt)

[NOTE]: # view becomes inaccessible 
[TIP]:  # Couchdb view become unusable 

## Steps to Reproduce

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

View to work

[TIP]:  # ( Include as many relevant details about your environment as possible. )

CouchDB Version used:1.6.2
Windows 2012 R2.

{"name":"fieldlink","view_index":{"signature":"033c9f5097179704f1dcdaf924186342","language":"javascript","disk_size":294340804608,"data_size":62833502424,"update_seq
":67360272,"purge_seq":0,"updater_running":false,"compact_running":false,"waiting_commit":false,"waiting_clients":0}}

[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )
* CouchDB Version used:1.6.2
* Browser name and version:
* Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the prbolem here. )

**Comment by technipfmc-houston** [comment]
Okay I kicked off a compaction on the fieldlink view and the compaction was successful. 
I am able to access view again.
I am monitoring the couchdb log to make sure there are no errors.

I will let you know if that fixed the issue.

Thanks
Mike Walker

**Comment by technipfmc-houston** [comment]
still got and error in dblog but view is still available as of now:

Here is the part of the log that sent the error.


[Sat, 12 Oct 2019 13:09:25 GMT] [info] [<0.13522.0>] 127.0.0.1 - - GET /enbasemobilefmc/_design/fieldlink/_view/docType?key=%22DeliveryNote%22&startkey_docid=DeliveryNote-0082529631&limit=501 200
[Sat, 12 Oct 2019 13:09:25 GMT] [error] [<0.13521.0>] {error_report,<0.34.0>,
                       {<0.13521.0>,crash_report,
                        [[{initial_call,
                           {mochiweb_acceptor,init,
                            ['Argument__1','Argument__2','Argument__3']}},
                          {pid,<0.13521.0>},
                          {registered_name,[]},
                          {error_info,
                           {error,
                            {badmatch,{error,einval}},
                            [{mochiweb_http,new_request,3,
                              [{file,
                                "c:/cygwin/relax/APACHE~2.1/src/mochiweb/mochiweb_http.erl"},
                               {line,133}]},
                             {mochiweb_http,handle_invalid_request,3,
                              [{file,
                                "c:/cygwin/relax/APACHE~2.1/src/mochiweb/mochiweb_http.erl"},
                               {line,127}]},
                             {mochiweb_http,handle_invalid_request,1,
                              [{file,
                                "c:/cygwin/relax/APACHE~2.1/src/mochiweb/mochiweb_http.erl"},
                               {line,122}]},
                             {proc_lib,init_p_do_apply,3,
                              [{file,"proc_lib.erl"},{line,239}]}]}},
                          {ancestors,
                           [couch_httpd,couch_secondary_services,
                            couch_server_sup,<0.35.0>]},
                          {messages,[{tcp_closed,#Port<0.17464>}]},
                          {links,[<0.111.0>]},
                          {dictionary,[{couch_rewrite_count,0}]},
                          {trap_exit,false},
                          {status,running},
                          {heap_size,1598},
                          {stack_size,27},
                          {reductions,775922}],
                         []]}}
[Sat, 12 Oct 2019 13:09:25 GMT] [info] [<0.13523.0>] 127.0.0.1 - - GET /enbasemobilefmc/_design/fieldlink/_view/authorization?startkey=%22wud%22&endkey=%22WUD%22 200

**Comment by technipfmc-houston** [comment]
It might be a bug I see this post and the developer down graded the version and it fixed the issue:

https://stackoverflow.com/questions/21763784/couchdb-crashes-with-no-reason-in-the-crash-report

However I would not want to downgrade.   The Couchdb does not stop working with this error however I am assuming the process might be.   LET ME KNOW.

Thanks 

Mike

**Comment by wohali** [comment]
@technipfmc-houston We don't officially support 1.x CouchDB anymore, sorry.
