### ISSUE TITLE
2.3 Release Notes - HTTP Global Handlers

### ISSUE THREAD

**Issue by rhucle** [apache/couchdb#2253]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
> These are no longer defined in the default.ini file, but have been moved to the couch.app context. If you need to customize your handlers, you can modify the app context using a **couchdb.config** file as usual.

I need to customize a handler and can't find any reference to `couchdb.config` in the documentation. 

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

**Comment by wohali** [comment]
This requires a compile from modified source, the `couchdb.config` file is autogenerated from the source. See the file `src/couch/src/couch.app.src` for more info.
