### ISSUE TITLE
couch 2.1.0 CRASH REPORT Process couch_compaction_daemon

### ISSUE THREAD

**Issue by anfuenmayor** [apache/couchdb#2256]
It was evidenced that couchdb was out of service for several minutes, and a log appears every second: Failure Report Process
couchdb: [error] 2019-10-14T08:41:36.650616Z couchdb@localhost <0.254.0> -------- **CRASH REPORT Process couch_compaction_daemon** (<0.254.0>) with 0 neighbors exited with reason: {compaction_loop_died,{{badmatch,{error,enoent}},[{couch_compaction_daemon,abs_path,1,[{file,"src/couch_compaction_daemon.erl"},{line,526}]},{couch_compaction_daemon,free_space_rec,2,[{file,"src/couch_compaction_daemon.erl"},{line,517}]},{couch_compaction_daemon,can_view_compact,4,[{file,"src/couch_compaction_daemon.erl"},{line,358}]},{couch_compaction_daemon,maybe_compact_view,3,[{file,"src/couch_compaction_daemon.erl"},{line,255}]},{couch_compaction_daemon,maybe_compact_views,3,[{file,"sr..."},...]},...]}} at gen_server:terminate/6(line:744) <= proc_lib:init_p_do_apply/3(line:239); initial_call: {couch_compaction_daemon,init,['Argument__1']}, ancestors: [couch_secondary_services,couch_sup,<0.204.0>], messages: [], links: [<0.213.0>], dictionary: [], trap_exit: true, status: running, heap_size: 987, stack_size: 27, reductions: 2812
couchdb: [error] 2019-10-14T08:41:36.651033Z couchdb@localhost <0.213.0> -------- Supervisor couch_secondary_services had child compaction_daemon started with couch_compaction_daemon:start_link() at <0.254.0> exit with reason {compaction_loop_died,{{badmatch,{error,enoent}},[{couch_compaction_daemon,abs_path,1,[{file,"src/couch_compaction_daemon.erl"},{line,526}]},{couch_compaction_daemon,free_space_rec,2,[{file,"src/couch_compaction_daemon.erl"},{line,517}]},{couch_compaction_daemon,can_view_compact,4,[{file,"src/couch_compaction_daemon.erl"},{line,358}]},{couch_compaction_daemon,maybe_compact_view,3,[{file,"src/couch_compaction_daemon.erl"},{line,255}]},{couch_compaction_daemon,maybe_compact_views,3,[{file,"sr..."},...]},...]}} in context child_terminated
Oct 14 03:41:36 couchdb: [error] 2019-10-14T08:41:36.861680Z couchdb@localhost emulator -------- Error in process <0.18407.1999> on node 'couchdb@localhost' with exit value: {{badmatch,{error,enoent}},[{couch_compaction_daemon,abs_path,1,[{file,"src/couch_compaction_daemon.erl"},{line,526}]},{couch_compaction_daemon,free_space_rec,2,[{file,"src/couch_compaction_daemon.erl"},{line,517}]},{couch_compaction_daemon...
Oct 14 03:41:36 couchdb: [error] 2019-10-14T08:41:36.862123Z couchdb@localhost <0.20505.1999> -------- gen_server couch_compaction_daemon terminated with reason: {compaction_loop_died,{{badmatch,{error,enoent}},[{couch_compaction_daemon,abs_path,1,[{file,"src/couch_compaction_daemon.erl"},{line,526}]},{couch_compaction_daemon,free_space_rec,2,[{file,"src/couch_compaction_daemon.erl"},{line,517}]},{couch_compaction_daemon,can_view_compact,4,[{file,"src/couch_compaction_daemon.erl"},{line,358}]},{couch_compaction_daemon,maybe_compact_view,3,[{file,"src/couch_compaction_daemon.erl"},{line,255}]},{couch_compaction_daemon,maybe_compact_views,3,[{file,"sr..."},...]},...]}}
Oct 14 03:41:36 couchdb: last msg: {'EXIT',<0.18407.1999>,{{badmatch,{error,enoent}},[{couch_compaction_daemon,abs_path,1,[{file,"src/couch_compaction_daemon.erl"},{line,526}]},{couch_compaction_daemon,free_space_rec,2,[{file,"src/couch_compaction_daemon.erl"},{line,517}]},{couch_compaction_daemon,can_view_compact,4,[{file,"src/couch_compaction_daemon.erl"},{line,358}]},{couch_compaction_daemon,maybe_compact_view,3,[{file,"src/couch_compaction_daemon.erl"},{line,255}]},{couch_compaction_daemon,maybe_compact_views,3,[{file,"src/couch_compaction_daemon.erl"},{line,227}]},{couch_compaction_daemon,'-compact_loop/1-fun-0-',3,[{file,"src/couch_compaction_daemon.erl"},{line,141}]},{couch_server,'-all_databases/2-fun-0-',4,[{file,"src/couch_server.erl"},{line,273}]},{filelib,do_fold_files2,8,[{file,"filelib.erl"},{line,184}]}]}}
Oct 14 03:41:36 couchdb: state: {state,<0.18407.1999>,[]}
Oct 14 03:41:36 couchdb: [error] 2019-10-14T08:41:36.862436Z couchdb@localhost <0.20505.1999> -------- CRASH REPORT Process couch_compaction_daemon (<0.20505.1999>) with 0 neighbors exited with reason: {compaction_loop_died,{{badmatch,{error,enoent}},[{couch_compaction_daemon,abs_path,1,[{file,"src/couch_compaction_daemon.erl"},{line,526}]},{couch_compaction_daemon,free_space_rec,2,[{file,"src/couch_compaction_daemon.erl"},{line,517}]},{couch_compaction_daemon,can_view_compact,4,[{file,"src/couch_compaction_daemon.erl"},{line,358}]},{couch_compaction_daemon,maybe_compact_view,3,[{file,"src/couch_compaction_daemon.erl"},{line,255}]},{couch_compaction_daemon,maybe_compact_views,3,[{file,"sr..."},...]},...]}} at gen_server:terminate/6(line:744) <= proc_lib:init_p_do_apply/3(line:239); initial_call: {couch_compaction_daemon,init,['Argument__1']}, ancestors: [couch_secondary_services,couch_sup,<0.204.0>], messages: [], links: [<0.213.0>], dictionary: [], trap_exit: true, status: running, heap_size: 987, stack_size: 27, reductions: 2816

**local.ini**
[database_compaction]
; larger buffer sizes can originate smaller files
doc_buffer_size = 524288 ; value in bytes
checkpoint_after = 5242880 ; checkpoint after every N bytes were written

[view_compaction]
; larger buffer sizes can originate smaller files
keyvalue_buffer_size = 2097152 ; value in bytes

[daemons]
index_server={couch_index_server, start_link, []}
external_manager={couch_external_manager, start_link, []}
query_servers={couch_proc_manager, start_link, []}
vhosts={couch_httpd_vhost, start_link, []}
httpd={couch_httpd, start_link, []}
uuids={couch_uuids, start, []}
auth_cache={couch_auth_cache, start_link, []}
os_daemons={couch_os_daemons, start_link, []}
compaction_daemon={couch_compaction_daemon, start_link, []}

[compaction_daemon]
; The delay, in seconds, between each check for which database and view indexes
; need to be compacted.
check_interval = 300
; If a database or view index file is smaller then this value (in bytes),
; compaction will not happen. Very small files always have a very high
; fragmentation therefore it's not worth to compact them.
min_file_size = 131072

_default = [{db_fragmentation, "70%"}, {view_fragmentation, "60%"}]

## Environment
Filesystem Size Used Avail Use% Mounted on
/dev/sda               30G    9.2G   21G  32% /
devtmpfs              7,9G      0      7,9G   0% /dev
tmpfs                    7,9G      0      7,9G   0% /dev/shm
tmpfs                    7,9G    798M  7,1G   10% /run
tmpfs                    7,9G      0       7,9G   0% /sys/fs/cgroup
/dev/sda5            497M   105M  392M  22% /boot
/dev/mapper/data_pool-XFS_Volume 100G    26G   75G  26% /mnt/datavolume
tmpfs                 1.6G    0  1.6G   0% /run/user/1000

* CouchDB Version used:  Couchdb 2.1.0 
* Operating System and version: vm centos 7 of ms azure

**Comment by wohali** [comment]
We believe your problem has been fixed, as the compaction daemon was completely replaced in CouchDB 3.0.0. Please test with 3.0.0, and if this problem recurs, please re-tag this issue.
