### ISSUE TITLE
After upgrade from 1.6.1 to 2.3.1 no view in design documents work.

### ISSUE THREAD

**Issue by technipfmc-houston** [apache/couchdb#2269]
Database is upgraded and can retrieve data.

After database is upgrade I let view/index be created by hitting a view in design document.  Takes a bit but completes with no errors.

But then I hit any view in the design document and get the same error below.  This exact database and views used to work in v1.6.1.   Is there new limits in Memory for design document/views with the new version?    Is there anyway I can up the limit.  I monitor the servers memory and it never climbs above 3G with 8G in total.  I also get add memory to servers as well.

Even if I decide to break up the views into multiple design document what is limit.  I would hate for this to happen in a PROD database all of a sudden  and the only answer is to break the design document down even further. 

This is the error from the couchdb log.

[error] 2019-10-21T15:41:33.641000Z couchdb@localhost <0.2163.0> -------- OS Process Error <0.416.0> :: {<<"InternalError">>,{[{<<"message">>,**<<"allocation size overflow">>**},{<<"fileName">>,<<"./share/server/main.js">>},{<<"lineNumber">>,1435},{<<"stack">>,<<"([object Object])@./share/server/main.js:1435\n()@./share/server/main.js:1582\n()@./share/server/main.js:1603\n@./share/server/main.js:1\n">>}]}}
[error] 2019-10-21T15:41:33.641000Z couchdb@localhost emulator -------- Error in process <0.2163.0> on node couchdb@localhost with exit value:
{{nocatch,{<<"InternalError">>,{[{<<"message">>,<<"allocation size overflow">>},{<<"fileName">>,<<"./share/server/main.js">>},{<<"lineNumber">>,1435},{<<"stack">>,<<"([object Object])@./share/server/main.js:1435\n()@./share/server/main.js:1582\n()@./share/server/main.js:1603\n@./share/server/main.js:1\n">>}]}}},[{couch_os_process,prompt,2,[{file,"src/couch_os_process.erl"},{line,59}]},{couch_query_servers,map_doc_raw,2,[{file,"src/couch_query_servers.erl"},{line,68}]},{couch_mrview_updater,'-map_docs/2-fun-0-',3,[{file,"src/couch_mrview_updater.erl"},{line,199}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{couch_mrview_updater,map_docs,2,[{file,"src/couch_mrview_updater.erl"},{line,206}]}]}

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Steps to Reproduce

Hit any view in design document.     

If you clone a view into a new design documents the views work.

views should return data just like v1.6.1

## Your Environment

Window Server 2012 R2
8G memory 2G used.
4 CPUs

* CouchDB Version used: 1.6.1 upgrade to 2.3.1
* Browser name and version: Chrome.
* Operating System and version:

Thanks for any help

Mike Walker

**Comment by wohali** [comment]
Hi @technipfmc-houston ,

You need to increase your stack size setting; this was a change between 1.x and 2.x for security reasons. Please see https://docs.couchdb.org/en/stable/whatsnew/2.3.html#upgrade-notes for details.
