### ISSUE TITLE
Surface purge_info history via HTTP

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#2281]
## Summary

Back about 15 months ago, @kocolosk said:

  https://github.com/apache/couchdb/pull/1370#issuecomment-397138672

> Historically one could think about external consumers of _changes and internal consumers of the sequence index as being on equal footing, and there's something appealing about that. The latter group has some efficiency advantages but fundamentally an external process could go and do everything that the internal consumers do using the node-local HTTP interface. The lack of HTTP access to the purge index breaks that. An external indexer, for example, has no way of knowing revisions have been purged from the main database short of checking the individual shard's purge sequence and rebuilding the entire index if it changes, whereas the internal consumers can be smarter.

## Desired Behaviour and Additional Context

As an external consumer (PouchDB or other system implementing a CouchDB compatible replicator), I would like to be able to access the `purge_info` data so that I can avoid reintroducing documents that have been previously purged.

I am aware that the upper bound on those numbers of revisions (by default, 1000 I think?) means I need to access this endpoint often.

## For reference:

https://cloud.ibm.com/docs/services/Cloudant/api?topic=cloudant-documents#purge

**Comment by nickva** [comment]
`_purged_infos` API is now implemented by @jiahuili430!

Closing as completed.
