### ISSUE TITLE
fabric doc_update_errors

### ISSUE THREAD

**Issue by olivenvrac** [apache/couchdb#2303]
## Description
Hi.
I have a problem on my single node couchDB server but i dont know what it is about.
I'm using elasticsearch to monitor the instance using the "_stats" handler wich return to me some hundred of errors  per day on the  "doc_update_errors" of the fabric metrics.
-> i 
![fabric-doc_update errors](https://user-images.githubusercontent.com/31409996/68392988-4c36a700-016b-11ea-9eeb-a0cfaefce7d8.png)
give you the metrics in copy on this issue
I don't know how to properly interpret and resolve this.

There is no relative messages to this errors in the logs on the serveur. Only on the thats handler
I am not sure what it is about and the consequences.
can you help me to interprete this and tell me if i can loose documents when this errors happens.

## Steps to Reproduce
 i don't know how to reproduce these errors

## Expected Behaviour
Understand what's happen and what to do for resolve this.

## Your Environment
Linux version 3.10.0-327.el7.x86_64 (RHEL 7.2)
CouchDB 2.3

Thank you in advance for your explanations

**Comment by davisp** [comment]
Hiya,

As long as you're paying attention to the HTTP status codes that CouchDB is sending you, you'll not lose any document updates. All that this metric is counting is when you've not gotten a quorum write for some identical reason across all replica responses.

For instance, you would see these errors if you attempted to update a document and it returned a `409 Conflict` response. You might also get them if a couple of your nodes are under load and not managing to keep internal replication up to date faster than your write load. In this case you would be seeing `202 Accepted` HTTP status codes indicating that a document was accepted by at least one node but not with an entire quorum. This means the document has been fsync'ed to disk and internal replication will eventually ensure that all `N` copies exist in the cluster.
