### ISSUE TITLE
following up on known issue 3390

### ISSUE THREAD

**Issue by dhuang612** [apache/couchdb#2304]
## Description
I wanted to check up on this issue that was marked as resolved:
https://issues.apache.org/jira/browse/COUCHDB-3390
I checked under the release information for the versions
 2.3.0
2.2.0
2.1.0
2.0.0
and I don't see it listed under any of these as being fixed?
http://docs.couchdb.org/en/2.3.0/
## Steps to Reproduce
https://github.com/pouchdb/pouchdb/issues/6436

Thank you!

**Comment by kocolosk** [comment]
The fix version in JIRA is listed as 2.1.0. I guess we forgot to put it into the release notes at the time.
