### ISSUE TITLE
Cant start CouchDB on Windows Server 2019

### ISSUE THREAD

**Issue by DennisSchuenemann** [apache/couchdb#2308]
Hello,

I try to install CouchDB 2.3.1 on Windows Server 2019. I pay attention that the installation path is without spaces. after the installation is finished, the Service is crashing every few seconds.
In the windows eventviewer I got `Failed to open process handle for process with PID 2344 when terminating service Apache CouchDB: The parameter is incorrect.`

On Server 2016 i have no issuse, using the same approach. Are there any known Issuses with Windows Server 2019?

best regards

**Comment by wohali** [comment]
Hi @DennisSchuenemann ,

Open an Administrator prompt, `cd` into the `CouchDB\bin` directory, and run the `couchdb.cmd` file. What do you see?

**Comment by DennisSchuenemann** [comment]
Hello @wohali,

I get the following output:

`kernel-poll not supported; "K" parameter ignored
{"Kernel pid terminated",application_controller,"{application_start_failure,couch,{{shutdown,{failed_to_start_child,couch_secondary_services,{shutdown,{failed_to_start_child,httpd,eacces}}}},{couch_app,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,couch,{{shutdown,{failed_to_start_child,couch_secondary_services,{shutdown,{failed_to_start_child,httpd,eacces}}}},{couch_app`

I attached you the erl_crash.dump file, that was created. (as zip, .dump is not supported by github)

We use Windows Server 2019 (1809)

[erl_crash.zip](https://github.com/apache/couchdb/files/4169422/erl_crash.zip)

**Comment by wohali** [comment]
`eacces` in that error message means that the folder structure is not owned by the right user. Kindly check the permissions on the folder structure and ensure that CouchDB can both read and write all of the files in the `etc` and `data` subdirectories. Most likely, some aggressive administrator policy set on your machine kicked in and denied access to the files.

That should resolve this issue.
