### ISSUE TITLE
Document autoupdate:false design document option

### ISSUE THREAD

**Issue by kocolosk** [apache/couchdb#2312]
## Summary

We have undocumented behavior that allows users to opt-out of automatic indexing for specific design documents or types of indexes in a design document.

The simplest configuration is

```
{
  "_id": "_design/foo",
  "autoupdate": false,
  ...
}
```

It's also possible to specify certain types of indexes separately:

```
{
  "_id": "_design/foo",
  "autoupdate": {
    "views": false, # Views and Mango JSON indexes
    "indexes": false, # Lucene and Mango Text indexes
    "st_indexes": false, % Geospatial
  },
  ...
}
```

I think we might be better off leaving that extra behavior undocumented as I'm not sure I'd want to commit to those names long-term.

## Desired Behaviour

Setting "autoupdate": false in a design document causes it to be skipped by ken. This should be documented.

**Comment by willholley** [comment]
I added a PR to cover the basic boolean case recently -
https://github.com/apache/couchdb-documentation/pull/453.

**Comment by kocolosk** [comment]
Closing in favor of apache/couchdb-documentation#453
