### ISSUE TITLE
conflicting revisions getting created instead of getting "conflict" error response within a node

### ISSUE THREAD

**Issue by subin1011** [apache/couchdb#2320]
## Description

while trying to update a document in parallel within a node, conflicting revisions are created. 

Running an application with a two node couchdb cluster (Node A and Node B). However, All the API traffic from the application has been directed only to the node A.
The application receives a multiple parallel requests which reads and updates a value from a single document. Have handled the race condition based on the conflict error response,
**{"error"=>"conflict", "reason"=>"Document update conflict."}**. In most cases this works fine but at some point instead of getting conflict error response, have created conflicting revisions 2-a and 2-b within node A.
Thereby race condition handling failed.

While trying to reproduce the same with a couchdb in stand alone mode conflicting revisions are not created.

Want to understand if conflicting revisions will be created within the same node. Thought it happens only when syncing with a different node.

## Environment

* CouchDB Version used: 2.3.0
* Operating System and version: Ubuntu 16.04

**Comment by davisp** [comment]
This is an effect of quorum writes in a cluster. What happens during a clustered write is that the updates are sent to all nodes in the cluster and the responses are then collected and returned.

In your case what is happening is that you have two concurrent writes that are then distributed to all shard copies. Say you want to write both Rev1 and Rev2 concurrently. Depending on timing, those may arrive at nodes in different orders. I.e., node1 might see Rev1 first, while node2 might see `Rev2` first. In that case both updates will be accepted and the result would then be a conflict written on both nodes.
