### ISSUE TITLE
I need help with CouchDB offline feature.

### ISSUE THREAD

**Issue by aaamitsingh** [apache/couchdb#2334]
Hi All,
I am new to CouchDB just watched a few tutorials and want to use this DB with python on my next project.

In my app, I want to use an offline-first feature where I'm going to store the temperature of a multiple truck engine(suppose 100 trucks). For recording the temperature I'm going to use Raspberry pi. 

**a.** Here I want to use the offline-first feature because the truck will be travelling to a remote area where the network will not be available sometimes and that time I want to store the data into to local database and once it will get the network the data will be sync to main CouchDB server.

**b.** and on the raspberry pi due to low memory availability, I only want to store the temperature data of a day or week but on the server, I want to store the temperature for a 1-2 year. 

In some tutorial, I have read that this can be done with the PouchDB but as I'm not using browser-side application so I cant use this.

Any help would be greatly appreciated.

**Comment by pavellzubkov** [comment]
may be couchdb server on rpi + nodejs on rpi + nano library? nodejs app store data to couchdb then couchdb replicate to main server when network is available.

**Comment by natcohen** [comment]
@aaamitsingh Post your questions on stackoverflow, this is used to track bugs!

To answer your question, PouchDB can be used on the server using Node.js
