### ISSUE TITLE
JS Full text search

### ISSUE THREAD

**Issue by pavellzubkov** [apache/couchdb#2341]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary
It is possible to add to couchdb java script full text search [FlexSearch](https://github.com/nextapps-de/flexsearch) because it is realy fast?

## Desired Behaviour

Fast full text search.
I try this library and it fantastic fast. 

## Possible Solution

add this library to couchdb for executing by spidermonkey

## Additional context

Benchmark:
data - 50 000 docs with string field "title" (field length 15 -20 words)
couchdb creating view on this data approx. 30 sec on my machine
flexsearch creating index on this data  approx. 4 sec on my machine
full text search request to flexsearch executing in **30-50 msec!**

**Comment by garrensmith** [comment]
FlexSearch looks pretty cool. It wouldn't be possible to use that with CouchDB for a few reasons but the main issue is because FlexSearch is designed for nodejs and browser environments.

A good use-case might be to combine it with PouchDB. That could probably fit your use case.
