### ISSUE TITLE
CouchDb 2.3 rebuilding indexes for unchanged design documents

### ISSUE THREAD

**Issue by kierondye-fraedom** [apache/couchdb#2348]
We have a problem in our production environment where every time we deploy an unchanged design document it is causing a reindex on the next view access. We deploy using a PUT request to update the existing document. The database size is 4.4GB and reindexing takes several hours. Can you explain what scenarios might cause the reindexing? 

My understanding is that 2 scenarios might cause the reindex: 

1. The design document changes.
2. The purge sequence in the view is inconsistent with the database.

But I am not sure about what might trigger a purge event.

On my local environment with a database size of 250MB I have been unable to reproduce the problem.

CouchDB version: 2.3
Browser: Not Applicable
Operating System: Windows Server 2016

**Comment by davisp** [comment]
Can you verify that the design document signature has not changed before and after the PUT request? You could show this with something like:

* `GET /dbname/_design/docid/_info`
* `PUT /dbname/_design/docid`
* `GET /dbnae/_design/docid/_info`

The `view_index.signature` should remain the same before and after. If it does, then also check to see if there are any errors in the logs around that time. Perhaps something crashes in an odd way that triggers the rebuild.

**Comment by janl** [comment]
please re open if this problem persists

**Comment by kierondye-fraedom** [comment]
I know this is 9 months down the line but I thought it would be fair to give an update on this. As a workaround we put code into our deployment pipeline to prevent views being deployed if they had not been changed. Given that PUTting a view document causes the revision to change regardless of whether the rest of the document has we guessed that this changes the hash and causes the re-indexing. We are still having trouble working out what causes major re-indexing to occur but our problems are probably by design. Thanks for your response @davisp and apologies for the slow update.
