### ISSUE TITLE
CouchDB 2.3.1 Save view failed On Red Hat6.5

### ISSUE THREAD

**Issue by jyxiaoka** [apache/couchdb#2364]
The latest COuchDB 2.3.1 for Linux(RedHat6.5) can not save a simple view.

## Description

When I create a design document and view, and then save the view, it's failed with the message:
"save failed,Reason:Undefined". 
The HTTP request return:
http://localhost:4784/exiaresource/_design/testDoc
response:{"error":"unknown_error","reson":"undefined"}

I was installed the CouchDB 2.3.1 from source, and  installed the dependency package one by one.when I start the CouchDB , the log message is :
"./bin/couchjs: error while loading shared libraries: libmozjs185.so.1.0: cannot open shared object file: No such file or directory"

But the libmozjs185.so.1.0 file already exists in the '/usr/lib' or '/usr/local/lib',I try some ways such as edit the `rebar.config.script` file ,but it is failed to save the view always.

## Steps to Reproduce

1.Install CouchDB 2.3.1 from source.
2.Create a new view,and then save the new view.
3.It is failed with the undefined message.

## Your Environment

* CouchDB Version used:CouchDB 2.3.1
* Browser name and version: Chrome
* Operating System and version:Red Hat Enterprise 6.5

**Comment by davisp** [comment]
Can you run `ldd bin/couchjs` to see what it thinks its linked to? If `libmozjs185.so.1.0` is in `/usr/local/lib` you may have to update `/etc/ld.so.conf` and run `ldconfig` to get those shared libraries updated.

**Comment by maojianyu** [comment]
> Can you run `ldd bin/couchjs` to see what it thinks its linked to? If `libmozjs185.so.1.0` is in `/usr/local/lib` you may have to update `/etc/ld.so.conf` and run `ldconfig` to get those shared libraries updated.

Thanks.
I run the command 'ldd bin/couchjs',It's show as :
```
couchdb  couchdb.cmd  couchjs  couchup  nohup.out  remsh
[root@redhat-server bin]# ldd couchjs
	linux-vdso.so.1 =>  (0x00007ffcec381000)
	libmozjs185.so.1.0 => not found
	libm.so.6 => /lib64/libm.so.6 (0x0000003be8c00000)
	libc.so.6 => /lib64/libc.so.6 (0x0000003be8000000)
	/lib64/ld-linux-x86-64.so.2 (0x00005610277ff000)
[root@redhat-server bin]#
```

and then I run the ‘ldconfig’ command，and copy the libmozjs185.so.1.0 to the /usr/lib/，the ldd command show as:
```
[root@redhat-server bin]# ldd couchjs
./couchjs: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/libmozjs185.so.1.0)
./couchjs: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/lib/libmozjs185.so.1.0)
	linux-vdso.so.1 =>  (0x00007fff3e720000)
```
but it still get this error 'Save failed. Reason: undefined' when I create a new view.

So I run ' strings /usr/lib64/libstdc++.so.6 | grep CXXABI' ,an not found the 1.3.9 version.
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3

and I see the ` libstdc++.so.6 -> libstdc++.so.6.0.13`, It's old version.

Now I try to update the gcc and try again.

**Comment by janl** [comment]
please reopen if this is still an issue

**Comment by jyxiaoka** [comment]
I have solved the problem:
```
[root@redhat-server bin]# ldd couchjs
./couchjs: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/libmozjs185.so.1.0)
./couchjs: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/lib/libmozjs185.so.1.0)
	linux-vdso.so.1 =>  (0x00007fff3e720000)
```
Like below:
```
[root@redhat-server bin]# ldd couchjs
[root@redhat-server ~]# cd /usr/couchdb/bin/
[root@redhat-server bin]# ldd couchjs
	linux-vdso.so.1 =>  (0x00007ffc237b6000)
	libmozjs185.so.1.0 => /usr/lib/libmozjs185.so.1.0 (0x00007f69bcf71000)
	libm.so.6 => /lib64/libm.so.6 (0x0000003be8c00000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f69bcbe4000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x0000003be8400000)
	libffi.so.6 => not found
	libnspr4.so => /lib64/libnspr4.so (0x0000003beb800000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f69bc8a9000)
	/lib64/ld-linux-x86-64.so.2 (0x0000555b8a5a5000)
	libdl.so.2 => /lib64/libdl.so.2 (0x0000003be7c00000)
	librt.so.1 => /lib64/librt.so.1 (0x0000003be8800000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x0000003be9c00000)
[root@redhat-server bin]#
```
but still can not create a new view.the error is still： 
{"error":"unknown_error","reson":"undefined"}

Emphasize that couchdb is installed offline.Can anyone help solve this？

**Comment by jiangphcn** [comment]
Would you please first verify whether `couchjs` can work correctly?
1. run ` ./src/couch/priv/couchjs`, you should see below
```
Usage: couchjs [FILE]

The couchjs command runs the Apache CouchDB JavaScript interpreter.

The exit status is 0 for success or 1 for failure.

Options:

  -h          display a short help message and exit
  -V          display version information and exit
  -H          enable couchjs cURL bindings (only avaiable
              if package was built with cURL available)
  -T          enable test suite specific functions (these
              should not be enabled for production systems)
  -S SIZE     specify that the runtime should allow at
              most SIZE bytes of memory to be allocated
              default is 64 MiB
  -u FILE     path to a .uri file containing the address
              (or addresses) of one or more servers
  --eval      Enable runtime code evaluation (dangerous!)

Report bugs at <https://issues.apache.org/jira/browse/COUCHDB>.
```

2. create test.js with
```
["reset"]
["add_fun", "function(doc) {return;}"]
```
and then run `cat test.js | ./src/couch/priv/couchjs share/server/main.js`, you need to see below result.
```
true
true
```

**Comment by jyxiaoka** [comment]
@jiangphcn when I run `./couchjs` in the dictionary `/usr/couchdb/bin`, The result is shown below:
```
[root@redhat-server bin]# ./couchjs
./couchjs: error while loading shared libraries: libffi.so.6: cannot open shared object file: No such file or directory
```

Offline installation requires too many dependencies, I have given up, thank you.
