### ISSUE TITLE
CouchDB Process Dies Without Any Error Log

### ISSUE THREAD

**Issue by arifcse019** [apache/couchdb#2365]
## Description

We have a three-node Cluster of CouchDB 2.3.1. The CouchDB process dies without any error logged (we have debug level logging). This has happened two times for each of our nodes in the span of three months.

## Steps to Reproduce

Not known.

## Expected Behaviour

The process should log error messages/ problems before terminating

## Your Environment

{"couchdb":"Welcome","version":"2.3.1","git_sha":"c298091a4","uuid":"4ebb08d132299ae512bd001e673fc7fa","features":["pluggable-storage-engines","scheduler"],"vendor":{"name":"The Apache Software Foundation"}

* CouchDB Version used: 2.3.1
* Browser name and version: N/A
* Operating System and version: Ubuntu 14.04

## Additional context

Logfile attached. Please notice sometime after 13:59:36, the process died and at 13:59:38, the process got started by upstart. 

[secondary-2019-12-15T13_59_05.000Z-2019-12-15T13_59_38.000Z.csv.log](https://github.com/apache/couchdb/files/3969027/secondary-2019-12-15T13_59_05.000Z-2019-12-15T13_59_38.000Z.csv.log)

**Comment by davisp** [comment]
Would it be possible to enable core dumps for the beam.smp process? Erlang in general is designed to bail pretty hard if it encounters any error conditions and relies on being run under a service supervisor like upstart or runit.

**Comment by arifcse019** [comment]
@davisp thanks for your response. any pointer on how to enable core dump for beam.smp?

meanwhile, we found this in the upstart log

> `eheap_alloc: Cannot allocate 3936326656 bytes of memory (of type “heap”).
Crash dump is being written to: erl_crash.dump...[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed`

but cant find the crash dump file in /opt where couchdb is running from

**Comment by arifcse019** [comment]
There seems to be a memory leak issue going on. In the attached image, the orange line is showing memory usage percentage of a 2.3.1 node and the blue line is of a 1.7.1 node. They are running independently, not connected to each other. Where the orange line dips down after consistently rising is when the crash happened

<img width="1175" alt="Screen Shot 2019-12-18 at 1 58 43 AM" src="https://user-images.githubusercontent.com/10591704/71071697-4d7bcc00-213a-11ea-9761-70245fa95747.png">

I will close this ticket and open a new one
