### ISSUE TITLE
Does smoosh take DB param revs_limit into account ?

### ISSUE THREAD

**Issue by creativityjuice** [apache/couchdb#2368]
First of all, thanks for your work on CouchDB, we love it !
Secondly, I know I'm not suppose to rely on revisions, but I do.
## Description
The automatic compaction deamon is removing all revisions(except the last one obviously) on some of our documents. Unfortunately we need it to perform a merge on our app side.
We are happy with smoosh but we would like to have control on the number of revisions that smmosh can remove on a DB. Smoosh doesn't seem to take into account DB param revs_limit. Is there another way ?
## Expected Behaviour
Smoosh should take revs_limit param into account when compacting databases
## Your Environment
- CouchDB version : 2.3.1
- git_sha : c298091a4
- OS : Ubuntu 18.04

Thanks for all,

**Comment by kocolosk** [comment]
Hi @creativityjuice, thanks! A couple of comments from my end on this topic:

* The `revs_limit` setting doesn't control how many document bodies are kept, only how many revision *identifiers*. This is important when you have a frequently updated document and a replication peer that only checks in periodically. If the document is updated more than `revs_limit` times in between replications it will look like a new conflict from the perspective of the replication peer (as the peer won't be able to join up edit histories).
* There is no setting to control how many document bodies are preserved; compaction (whether automatic or manually triggered) always removes the body of any revision for which a descendant exists in the edit history.

If I understand your situation correctly what you're really asking for is the ability for compaction to preserve some number of older edits, and then for a flag to have smoosh use that configuration. Unfortunately, that'd be a relatively sophisticated patch; a lot of the codebase is organized around the notion that "leafs" of the revision tree are special. I should also point out that in the 4.0 release there won't be a compaction process at all -- old document revisions will be removed immediately when the new update is committed.

As an aside, if I take the question "Does smoosh take `_revs_limit` into account?" literally the answer is **yes** -- smoosh will honor a database's configured revision stemming limit. It's just that this setting doesn't do what you're looking for it to do.

I'm going to close this issue but happy to hear your thoughts on the above.
