### ISSUE TITLE
Error adding node to cluster

### ISSUE THREAD

**Issue by intckarl** [apache/couchdb#2378]
I can't add new node to existing cluster and the log says this:

[error] 2019-12-11T11:12:48.045000Z couchdb@ENT1088.ARCGISONLINE.COM emulator -------- Error in process <0.1033.0> on node 'couchdb@ENT1088.ARCGISONLINE.COM' with exit value:
{database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,395}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,370}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,399}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,86}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,38}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,187}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,134}]}]}

Any idea?

**Comment by intckarl** [comment]
Also
 HTTP POST request '/_cluster_setup' failed. Code 500. Error:{"error":"error","reason":"{invalid_ejson,{conn_failed,{error,nxdomain}}}

**Comment by nickva** [comment]
@intckarl 

Make sure to follow https://docs.couchdb.org/en/stable/setup/cluster.html and verify cluster connectivity after setting up node names.

`{mem3_shards,load_shards_from_db,"_users",` should stop appearing as soon as you create the `_users` database.
