### ISSUE TITLE
Verify CouchDB Installation failed

### ISSUE THREAD

**Issue by mentax007** [apache/couchdb#2380]
## Description
I install new 6 node cluster. Enable authentication and add 5 nodes through Fauxton.
When I run  Verify CouchDB Installation from Fauxton I see an error in Replication check

Error: unauthorized to access or create database http://0.0.0.0:5984/verifytestdb_replicate/
And on one of the node I see an error:
[error] 2019-12-22T16:05:37.312700Z couchdb@s2dfw.domain.net <0.26254.18> -------- throw:{unauthorized,<<"unauthorized to access or create database http://0.0.0.0:5984/verifytestdb_replicate/">>}: Replication 1c12e0a7574f8c90d3301e1442736899+create_target failed to start "http://0.0.0.0:5984/verifytestdb/" -> "http://0.0.0.0:5984/verifytestdb_replicate/" doc null:null stack:[{couch_replicator_api_wrap,db_open,4,[{file,"src/couch_replicator_api_wrap.erl"},{line,114}]},{couch_replicator_scheduler_job,init_state,1,[{file,"src/couch_replicator_scheduler_job.erl"},{line,584}]}]
[error] 2019-12-22T16:05:37.313062Z couchdb@s2dfw.domain.net <0.376.0> -------- couch_replicator_scheduler : Transient job {"1c12e0a7574f8c90d3301e1442736899","+create_target"} failed, removing. Error: <<"unauthorized: unauthorized to access or create database http://0.0.0.0:5984/verifytestdb_replicate/">>

Every time when I run Verify CouchDB Installation I can see this error on different node. 5 nodes are fine, but one of them alway show error.

If I disable password authentication, Verify CouchDB Installation finished without any errors.

{"couchdb":"Welcome","version":"2.3.1","git_sha":"c298091a4","uuid":"cfceef0b14b96c459ff3c374122c4876","features":["pluggable-storage-engines","scheduler"],"vendor":{"name":"The Apache Software Foundation"}}

* CouchDB Version used: 2.3.1
* Browser name and version: Google chrome Version 79.0.3945.88 (Official Build) (64-bit)
* Operating System and version: MacOS X Catalina

**Comment by janl** [comment]
the verify installation code is very old, it might need updating to account for password auth’d clusters, which are the default now.

https://github.com/apache/couchdb-fauxton/blob/master/app/addons/verifyinstall/resources.js#L124-L125 suggests that the code is using “local” database URLs (no http://server… in front of the database name), which no longer works.

The patch to make the fully qualified URLs should be simple enough :)

**Comment by geeksilva97** [comment]
Hey, @janl. Does the `beginner-friendly` label mean this issue is good for new contributors?

**Comment by big-r81** [comment]
Closing this (CouchDB v2.3.1).
