### ISSUE TITLE
update rebar.config with latest module tags

### ISSUE THREAD

**Issue by janl** [apache/couchdb#2391]
ioq e.g. is missing at least one commit

**Comment by davisp** [comment]
PR: https://github.com/apache/couchdb/pull/2400

So far I've only done ioq. We'll want to audit the other dependencies as well. I just wanted to get the ball rolling.

**Comment by kocolosk** [comment]
The ioq one was intentional on my part because I decided I didn't want to ship a simpler IOQ. #2408 has my preferred direction.

**Comment by wohali** [comment]
relaese notes WIP PR will be: https://github.com/apache/couchdb-documentation/pull/471
