### ISSUE TITLE
3.0 build is broken on Microsoft Windows

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#2404]
Should be something simple.

```
==> config (compile)
==> b64url (compile)
==> ets_lru (compile)
==> khash (compile)
==> snappy (compile)
==> ioq (compile)
==> hqueue (compile)
Compiling c:/relax/couchdb/src/hqueue/c_src/hqueue.c
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.40629 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line error D8021 : invalid numeric argument '/Werror'
ERROR: compile failed while processing c:/relax/couchdb/src/hqueue: rebar_abort
make: *** [couch] Error 1
```

**Comment by wohali** [comment]
Resolved via #2405 .

Now, docs won't build: `Fatal error in launcher: Unable to create process using '"'`.

**Comment by wohali** [comment]
Resolved the docs build with a python 3.7/pip/sphinx update. Will make separate commits to apache/couchdb-glazier with the new steps required.

**Comment by wohali** [comment]
Re-opening. Fauxton can't be found on Windows right now. It's in `rel/overlay/share/www` but `GET /_utils/index.html` returns Not found.

**Comment by janl** [comment]
This sounds like it? https://github.com/apache/couchdb/commit/ff0da20de60b3a70af8727e8fad9a3ff00430fad#diff-bab26d0becaf24757b2024c70e3cd676

**Comment by wohali** [comment]
Yeah, it's an optional variable, Erlang is supposed to set the default value here:

https://github.com/apache/couchdb/blob/08a9a5ffe6b2dcfeb480c4cdb15d60ececea8442/src/chttpd/src/chttpd_misc.erl#L294-L297

but that's the wrong guess. I'll dig in a bit more...the variable SHOULD be optional.

**Comment by janl** [comment]
That’s where the erlang side should pick up the env var that is set in `couchdb.cmd` :)

**Comment by wohali** [comment]
But the old behaviour should work too, it shouldn't *have* to be set.

**Comment by janl** [comment]
IIRC, I built it so that it HAS to be set in `couchdb.cmd`/`couchdb`

**Comment by wohali** [comment]
🤷‍♀ ok, i'll update it.

**Comment by wohali** [comment]
That PR didn't fix Fauxton on Windows @janl . Going to have to dig into the change more deeply, and see exactly how this functioned under 2.3.1.

For completeness, after `make release` on Windows, `rel\couchdb\bin\couchdb` contains:

```
set COUCHDB_FAUXTON_DOCROOT="./share/www"
```

and hitting `http://localhost:5984/_utils` after startup produces the raw text string `Not found.`

**Comment by wohali** [comment]
Got it.

In .cmd/.bat files, you don't quote the value of a string with spaces. In other words,

```batch
C:\relax\couchdb\rel\couchdb>SET A=b c d

C:\relax\couchdb\rel\couchdb>echo %A%
b c d
```

PR coming up to fix this.
