### ISSUE TITLE
Discussion: CouchDB & linux memory overcommitting

### ISSUE THREAD

**Issue by tomasged** [apache/couchdb#2425]
Hi, we're experimenting an OOM issue with an old CouchDB installation (1.6.1), but still since we're considering upgrading to the latest CouchDB version, this still applies.

From time to time, CouchDB commits quite a lot of memory, triggering the Linux oom-killer; since the CouchDB process already had the most amount of memory reserved to it, it's always the first candidate to be terminated and it's killed by it.

I think this prevents the regular Erlang mechanism from creating crash dumps that can be analyzed later, so we're a bit puzzled here about which operation is triggering such big amount of memory committing given there's no extra info we can use. Our code base which connects to CouchDB is quite legacy, so maybe it's hiding the operation triggering the issue. We're working on it, but at the same time we would like to gather info from CouchDB's side.

It takes a bit of time for us to do experiments, so we're wondering if CouchDB is prepared to work in an environment without memory over-committing... maybe in this way once the Erlang VM sees that its memory allocation gets rejected by the operating system, it will crash and the crash dump file will be generated, ensuring a posterior analysis from our side.

If my thinking is not correct or if there's a better approach to debug the issue, let me know. Thanks.

**Comment by janl** [comment]
They @tomasged the Apache CouchDB team does not provide support for version 1 anymore.

Commercial options are available, e.g. at https://neighbourhood.ie/couchdb-support/production-support/ (that’s my company).

The first thing I’d check is if you have heavily conflicted documents.

**Comment by tomasged** [comment]
Thanks for the hint for the conflicted documents.

Sorry, the question still applies for CouchDB 2.x. With over committing disabled in Linux, will CouchDB 2.x try to manage the situation and/or the Erlang VM will crash gracefully?

For example, I know that Redis requires over committing but there's nothing in the CouchDB 2.x documentation mentioning this and possible cases.

**Comment by janl** [comment]
There are a number of `erl` tweaks that can keep CouchDB ram usage at a ceiling. `man erl` gives all the options.
