### ISSUE TITLE
CouchDB fails to replicate locally if not accessed from local machine

### ISSUE THREAD

**Issue by natcohen** [apache/couchdb#2440]
I have CouchDB installed behind nginx and I can access it through my personal address: https://couchdb.myaddress.com/_utils

The problem is when I try to replicate local to local, it fails because CouchDB uses the address https://couchdb.myaddress.com instead of http://localhost:5984 to replicate locally. Am I missing a configuration or is it a bug?

If I connect to fauxton from localhost instead of my https address, the replication succeeds and use localhost to replicate.

**Comment by wohali** [comment]
This is a known and documented CouchDB 2.x issue. The workaround is to always specify the full URL to a DB for replication.

The ability to do "local" replication has already been removed for CouchDB 3.0, see https://github.com/apache/couchdb/pull/2089

**Comment by natcohen** [comment]
@wohali Thanks for the info!

By the way, would it be possible to have an estimate time for the 3.0 release? Is it days, weeks, months, quarters? That would be extremely helpful!

**Comment by wohali** [comment]
@natcohen You can watch the progress on the 3.0 release here: https://github.com/apache/couchdb/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.0.0

If I had to guess, late January or early February, but there's no guarantee. It's ready when it's ready. 😉

**Comment by natcohen** [comment]
@wohali That's exactly what I needed! Thanks
