### ISSUE TITLE
Add missing parameters to default.ini

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#2457]
* shard restriction parameters - Work was left out of #2012. 
* rexi kill all message - work was left out ot #2021 

@nickva can you please take this so the description is accurately written? Thanks!

**Comment by wohali** [comment]
Adding more for you, Nick, with the rexi kill all

**Comment by nickva** [comment]
@wohali will do, thank you for pointing those out!

**Comment by nickva** [comment]
PR issued https://github.com/apache/couchdb/pull/2459

Also had noticed there were a few more reshard params missing so added those too
