### ISSUE TITLE
the GitHub short description should be set properly

### ISSUE THREAD

**Issue by mechanomi** [apache/couchdb#2471]
at the moment, it just says "Apache CouchDB", which is not a description of the project ;)

**Comment by wohali** [comment]
@mechanomi sadly we can't fix it ourselves, only ASF Infrastructure has the ability to edit that (and the tags). they're auto-populated by the setup script, and rather dumbly at that.

Bikeshed something here? Then we can open the Infra ticket to fix it.

**Comment by wohali** [comment]
I've filed https://issues.apache.org/jira/browse/INFRA-20564 for this, with the description "Seamless multi-master syncing database with an intuitive HTTP/JSON API, designed for reliability".
