### ISSUE TITLE
compile failed while processing /tmp/apache-couchdb-2.3.1/src/couch: rebar_abort

### ISSUE THREAD

**Issue by Sharvin26** [apache/couchdb#2481]
[NOTE]:  CouchDB build failed

## Description

I am facing an issue when building the CouchDB on Ubuntu machine. I have configured `Erlang/OTP 19 [erts-8.3.5.4]` on the ubuntu machine.
 
## Steps to Reproduce

Downloaded the package and then built it using the following steps.
1. `cd temp`
2. `wget http://apache.cs.utah.edu/couchdb/source/2.3.1/apache-couchdb-2.3.1.tar.gz`

3. `tar zxvf apache-couchdb-2.3.1.tar.gz`
4. `cd apache-couchdb-2.3.1/`
5. `./configure`
6. `make release`

### Error =>
```
Compiled src/couch_bt_engine_compactor.erl
Compiled src/couch_auth_cache.erl
Compiling /tmp/apache-couchdb-2.3.1/src/couch/priv/couch_js/http.c
/tmp/apache-couchdb-2.3.1/src/couch/priv/couch_js/http.c:18:10: fatal error: jsapi.h: No such file or directory
 #include <jsapi.h>
          ^~~~~~~~~
compilation terminated.
ERROR: compile failed while processing /tmp/apache-couchdb-2.3.1/src/couch: rebar_abort
Makefile:114: recipe for target 'couch' failed
make: *** [couch] Error 1
sed: can't read /tmp/apache-couchdb-2.3.1/rel/couchdb/etc/local.ini: No such file or directory
```

## Expected Behaviour

Downloading and building CouchDB successfully.

## Your Environment

* CouchDB version used: 2.3.1
* Browser name and version: -
* Operating system and version: Ubuntu 18.04.3 LTS

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by Sharvin26** [comment]
I was missing download of this package => 
```
sudo apt-get --no-install-recommends -y install \
    build-essential pkg-config erlang \
    libicu-dev libmozjs185-dev libcurl4-openssl-dev
```

**Comment by jiangphcn** [comment]
cool, `jsapi.h` is supposed to be found at https://github.com/apache/couchdb/blob/2.3.1-draft/src/couch/rebar.config.script#L119-L122
