### ISSUE TITLE
Unexpected cluster state for single node config

### ISSUE THREAD

**Issue by gesellix** [apache/couchdb#2557]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

With CouchDB 3.x (#2296) we have the option to setup a node as "single node" via config setting. I expected this to have the same effect like using the Fauxton cluster setup UI from CouchDB 2.x.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

Using the new config setting we get the following cluster state at `/_cluster_setup`:

```{"state":"cluster_finished"}```

When using the Fauxton based single node setup, the `/_cluster_setup` endpoint returns:

```{"state":"single_node_enabled"}```

## Steps to Reproduce

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

```
git clone https://github.com/apache/couchdb-docker
cd couchdb-docker/
echo -e "\n[couchdb]\nsingle_node = true\n" >> dev/local.ini 
docker build -t couchdb:3 dev
docker run --rm -it --env COUCHDB_USER=admin --env COUCHDB_PASSWORD=password -p 5984:5984 couchdb:3
curl --user admin:password -X GET "http://localhost:5984/_cluster_setup" 
```

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

`GET /_cluster_setup` should return `single_node_enabled` when the new `couchdb.single_node=true` setting has been used.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: `CouchDB/3.0.0-8748310 (Erlang OTP/21)`
* Operating system and version: Docker image based on [docker-couchdb](https://github.com/apache/couchdb-docker) (`docker build -t couchdb:3 dev`)

**Comment by janl** [comment]
Good find! Agreed that this is a little confusing. CouchDB internals don’t really care about cluster vs. single node. A single node just happens to be a cluster of one, hence the confusion. The introduction of the new setting requires one more clause in this function:

https://github.com/apache/couchdb/blob/3f64ef2b98796ba8e0391fb80483502fdafc6a8c/src/setup/src/setup_httpd.erl#L30-L54

It should be easy enough to add, using `config:get_boolean()` like here https://github.com/apache/couchdb/blob/3f64ef2b98796ba8e0391fb80483502fdafc6a8c/src/setup/src/setup_sup.erl#L38

@gesellix wanna try a PR?

**Comment by gesellix** [comment]
> wanna try a PR?

Oh yes, the code pointers help a lot. I'll try!

**Comment by gesellix** [comment]
Fixed with #2574 - thx @janl!

**Comment by gesellix** [comment]
Not sure if #2574 fixes this issue.

@janl can you confirm that `is_single_node_enabled` will be called in case of a single_node-configured instance?

I think that it won't be called, because `GET /_node/_local/_config` yields `cluster.n = 3` for me. `is_single_node_enabled` will only be called in case of `cluster.n = 1`.

**Comment by janl** [comment]
Ah shoot, you're right! Cc @wohali

**Comment by janl** [comment]
Thanks @gesellix

**Comment by gesellix** [comment]
🙏 you're welcome
