### ISSUE TITLE
CouchDB 3 RC1: seeding cluster fails because local _users db doesn't exist

### ISSUE THREAD

**Issue by willholley** [apache/couchdb#2559]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

When attempting to join a CouchDB cluster using the seedlist function, `_up` always returns a 404.

## Steps to Reproduce

I used the Helm chart to deploy a 3 node cluster (building a Docker container from RC1). 

After Helm completed, running `_up` on one of the db nodes returns a 404:

```
$ curl localhost:5984/_up -v
...
< HTTP/1.1 404 Object Not Found
...
<
{"status":"seeding","seeds":{"couchdb@couchdb-h7nus9h3pt-couchdb-1.couchdb-h7nus9h3pt-couchdb.couchdb-h7nus9h3pt.svc.cluster.local":{"timestamp":"2020-02-17T11:52:58.127186Z","last_replication_status":"ok","pending_updates":{"_nodes":0,"_dbs":0,"_users":"missing_source"}},"couchdb@couchdb-h7nus9h3pt-couchdb-2.couchdb-h7nus9h3pt-couchdb.couchdb-h7nus9h3pt.svc.cluster.local":{"timestamp":"2020-02-17T11:50:40.175625Z","last_replication_status":"error"},"couchdb@couchdb-h7nus9h3pt-couchdb-1.couchdb-h7nus9h3pt-couchdb.couchdb-h7nus9h3pt.svc.cluster.local":{}}}
* Connection #0 to host localhost left intact
```

The cluster appears to have been joined correctly, but is missing system databases:

```
$ curl -s http://127.0.0.1:5984/_membership -u admin:***
{"all_nodes":["couchdb@couchdb-h7nus9h3pt-couchdb-0.couchdb-h7nus9h3pt-couchdb.couchdb-h7nus9h3pt.svc.cluster.local","couchdb@couchdb-h7nus9h3pt-couchdb-1.couchdb-h7nus9h3pt-couchdb.couchdb-h7nus9h3pt.svc.cluster.local","couchdb@couchdb-h7nus9h3pt-couchdb-2.couchdb-h7nus9h3pt-couchdb.couchdb-h7nus9h3pt.svc.cluster.local"],"cluster_nodes":["couchdb@couchdb-h7nus9h3pt-couchdb-0.couchdb-h7nus9h3pt-couchdb.couchdb-h7nus9h3pt.svc.cluster.local","couchdb@couchdb-h7nus9h3pt-couchdb-1.couchdb-h7nus9h3pt-couchdb.couchdb-h7nus9h3pt.svc.cluster.local","couchdb@couchdb-h7nus9h3pt-couchdb-2.couchdb-h7nus9h3pt-couchdb.couchdb-h7nus9h3pt.svc.cluster.local"]}
```

I then created the `_users` database using the `_cluster_setup` endpoint:

```
$ curl -s http://127.0.0.1:5984/_cluster_setup -XPOST -H "Content-Type: application/json"  -d '{"action": "finish_cluster"}' -u admin:***
{"ok":true}

$ curl -s http://127.0.0.1:5984/_all_dbs
["_replicator","_users"]
```

`_up` still returns a 404:
```
$ curl localhost:5984/_up -v
...
< HTTP/1.1 404 Object Not Found
...
<
{"status":"seeding","seeds":{"couchdb@couchdb-h7nus9h3pt-couchdb-1.couchdb-h7nus9h3pt-couchdb.couchdb-h7nus9h3pt.svc.cluster.local":{"timestamp":"2020-02-17T11:57:16.714300Z","last_replication_status":"ok","pending_updates":{"_nodes":0,"_dbs":0,"_users":"missing_source"}},"couchdb@couchdb-h7nus9h3pt-couchdb-2.couchdb-h7nus9h3pt-couchdb.couchdb-h7nus9h3pt.svc.cluster.local":{"timestamp":"2020-02-17T11:50:40.175625Z","last_replication_status":"error"},"couchdb@couchdb-h7nus9h3pt-couchdb-1.couchdb-h7nus9h3pt-couchdb.couchdb-h7nus9h3pt.svc.cluster.local":{}}}
```

## Expected Behaviour

seedlist should correctly sync `_users` when it is created and `_up` should return a 200 status code.

## Your Environment

Helm chart on Kind.

* CouchDB version used: 3.0 RC1
* Browser name and version: 
* Operating system and version:

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by willholley** [comment]
cc @kocolosk

**Comment by willholley** [comment]
it seems like this was okay as of [83bdcf6](https://github.com/apache/couchdb/compare/83bdcf6...3.0.0-RC1)

**Comment by willholley** [comment]
my suspicion is that the auth cache changes in https://github.com/apache/couchdb/commit/27bb45043435828915bdcbdc130b685e5533bbd8  mean we no longer call `couch_auth_cache:ensure_users_db_exists/0` at startup, so the local db sync that is part of the seeding process fails. Is there another point at which this should be created?

**Comment by nickva** [comment]
@willholley You're probably right. 

With the https://github.com/apache/couchdb/commit/27bb45043435828915bdcbdc130b685e5533bbd8 commit the db will be auto-created when it is used the first time.

It seems we could either auto-create it again on startup or check if db exists before attempting to sync it:

https://github.com/apache/couchdb/blob/bb30e984c653640b5ef9b80d3e5a2801bad14efe/src/mem3/src/mem3_rpc.erl#L192

**Comment by nickva** [comment]
Created a PR to not include users db in local_dbs output if it doesn't exist:

https://github.com/apache/couchdb/pull/2560
