### ISSUE TITLE
500 instead of 412 response in DB creation race

### ISSUE THREAD

**Issue by ricellis** [apache/couchdb#2613]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

In my scenario multiple clients are trying to create the same database (actually `_replicator`, but it is true for any DB), the code gracefully handles the expected `412` if the database exists, but sometimes a `500 {"error":"error", "reason":"conflict"}` is received instead.

## Steps to Reproduce

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

Run two threads in parallel creating the same database name. It can take quite a few attempts to provoke it - I see this problem on around ~6% of attempts.

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

Expected to receive a `412` on the losing thread.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

`apache/couchdb:3` docker, but I have also reproduced on `2.3.1`

* CouchDB version used: 3.0.0 & 2.3.1
* Browser name and version:
* Operating system and version: docker (on macOS)

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by nickva** [comment]
@ricellis 

Thank you for your bug report.

This is a valid bug. It happens in this function:

https://github.com/apache/couchdb/blob/master/src/fabric/src/fabric_db_create.erl#L37


Two concurrent requests can both check that the db exists, that can return`false` for both so they then proceed to create the shard doc. One can succeed and the other will get a conflict.
