### ISSUE TITLE
missing find selector regex syntax docs. couchdb regex uses unique syntax and no documentation appears to exist online referencing it.

### ISSUE THREAD

**Issue by vectorselector** [apache/couchdb#2620]
https://docs.couchdb.org/en/2.2.0/api/database/find.html
or any newer versions...

missing find selector regex syntax docs. 
couchdb regex uses unique syntax and no documentation appears to exist online referencing it.

how does one set a word boundary? I found case-insensitive on stackoverflow (?i) but this is the only example I can find in the wild...

is there a canonical couchdb regex syntax?

**Comment by wohali** [comment]
CouchDB is written in Erlang. Mango relies on the Erlang regular expression library, which itself is based on PCRE - but with some modifications.

http://erlang.org/doc/man/re.html should give you a full reference.

http://erlang.org/doc/man/re.html#internal-option-setting is the specific setting you were asking about.

**Comment by vectorselector** [comment]
thank you
