### ISSUE TITLE
CouchDB 3.0 fails to start on CentOS 8 after following installation instructions

### ISSUE THREAD

**Issue by natcohen** [apache/couchdb#2623]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

After a fresh install in a freshly installed CentOS 8, CouchDB fails to start.

Instead, CouchDB returns the following error:

```
[info] 2020-03-02T15:44:38.397655Z couchdb@127.0.0.1 <0.11.0> -------- Application couch_log started on node 'couchdb@127.0.0.1'
[info] 2020-03-02T15:44:38.409035Z couchdb@127.0.0.1 <0.11.0> -------- Application folsom started on node 'couchdb@127.0.0.1'
[info] 2020-03-02T15:44:38.459996Z couchdb@127.0.0.1 <0.11.0> -------- Application couch_stats started on node 'couchdb@127.0.0.1'
[info] 2020-03-02T15:44:38.460161Z couchdb@127.0.0.1 <0.11.0> -------- Application khash started on node 'couchdb@127.0.0.1'
[info] 2020-03-02T15:44:38.469610Z couchdb@127.0.0.1 <0.11.0> -------- Application couch_event started on node 'couchdb@127.0.0.1'
[info] 2020-03-02T15:44:38.469779Z couchdb@127.0.0.1 <0.11.0> -------- Application hyper started on node 'couchdb@127.0.0.1'
[info] 2020-03-02T15:44:38.477903Z couchdb@127.0.0.1 <0.11.0> -------- Application ibrowse started on node 'couchdb@127.0.0.1'
[info] 2020-03-02T15:44:38.485659Z couchdb@127.0.0.1 <0.11.0> -------- Application ioq started on node 'couchdb@127.0.0.1'
[info] 2020-03-02T15:44:38.485799Z couchdb@127.0.0.1 <0.11.0> -------- Application mochiweb started on node 'couchdb@127.0.0.1'
[info] 2020-03-02T15:44:38.491456Z couchdb@127.0.0.1 <0.232.0> -------- Preflight check: Asserting Admin Account

[info] 2020-03-02T15:44:38.491566Z couchdb@127.0.0.1 <0.232.0> -------- 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  No Admin Account Found, aborting startup.                  
  Please configure an admin account in your local.ini file.  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Steps to Reproduce

Follow the steps for CentOS here: https://docs.couchdb.org/en/stable/install/unix.html

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour

The admin account should be configured at first Fauxton startup. In this case, CouchDB refuses to even start...

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used:
* Operating system and version: CentOS 8

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by wohali** [comment]
@natcohen This is a breaking change in CouchDB 3.0 and expected:

* http://docs.couchdb.org/en/stable/whatsnew/3.0.html
* https://github.com/apache/couchdb/pull/2389

In the Debian installer, the `debconf` framework allows us to prompt the user at install time for the user, and place it in an `ini` file. Unfortunately, CentOS/RedHat have no such mechanism.

To work around this, add a section like the following to your `/opt/couchdb/etc/local.ini` file:

```ini
[admins]
admin = password
```

You can then run `service start couchdb` and CouchDB will startup with your admin user.

**Comment by natcohen** [comment]
Ok but then the doc should reflect that... Following this: https://docs.couchdb.org/en/stable/install/unix.html doesn't give a clue to what needs to be done.

**Comment by wohali** [comment]
@natcohen Thanks - would you be willing to help us? We're always looking for support. 

Fork https://github.com/apache/couchdb-documentation and make a pull request with the recommended change. We'll definitely take it!
