### ISSUE TITLE
Replication remote -> local doesn't work in 3.0

### ISSUE THREAD

**Issue by natcohen** [apache/couchdb#2626]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Version used: Remote CouchDB 2.3.1 and Local CouchDB 3.0

Simple remote->local replication using authentication on both ends doesn't work

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Steps to Reproduce

Go on Fauxton and create a replication using the UI for a remote to local DB (existing or new fail). Once created, the list of replication shows that the source is not correct and display the address of the destination. The replication fails with the retry message.

My CouchDB instances run behind nginx and https addresses are used for both sides.

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour

Replicates without errors...

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: 3.0
* Browser name and version: Chrome 80
* Operating system and version: CentOS 8

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by natcohen** [comment]
Not sure what the problem is but no replications work... maybe the nginx proxy?

Even local to local replication fails. It's using the https address in source and target but should maybe use localhost?

**Comment by pavellzubkov** [comment]
Replications with same proxy config works correctly with couch 2.3.1 on both side?

**Comment by natcohen** [comment]
CouchDB 2.3.1 already had issues with reverse proxies but I thought 3.0 had fixed them. What is the best practice for replicating through a reverse proxy? The UI doesn't work at all...

**Comment by nickva** [comment]
There was a similar issue reported and I think it's related:

https://github.com/apache/couchdb/issues/2594

We had figured out there that Fauxton grabs the URL from the browser's location and uses parts of for the "local" replications. I can see how proxies or container environments would interfere with that. As the URL the browser connect to the server might not be accessible for the server to connect to itself especially with `localhost` being used.

Try to reproduce the issue outside Fauxton and just using the API directly.

Somethings to keep in mind with a proxy:

  * Make sure that it doesn't buffer requests, as say _changes feeds APIs need to stream data

  * They may alter the `Set-Cookie` headers and prevent servers behind the reverse proxies to authenticate requests properly. To avoid the issue can switch to basic auth only by setting
   ```
  [replicator]
  auth_plugins = couch_replicator_auth_noop
   ```

**Comment by natcohen** [comment]
@nickva How can I do a basic auth? With https://admin:password@mycouch.com/mydb ?

That exposes the password...

Also, do you know if nginx alter the setcookie header by default? that would surprise me.

**Comment by nickva** [comment]
> Also, do you know if nginx alter the setcookie header by default? that would surprise me.

I don't know much about nginx. Don't think it does it by default? But can certainly do it with various directives or settings.

 > How can I do a basic auth? With https://admin:password@mycouch.com/mydb ? That exposes the password...

The password would have to be sent to the `_session/` endpoint so it will be exposed just as well? Otherwise the connection to `mycouch.com` seems to be using TLS (https) and so the credentials would go over the encrypted TLS stream.

Would you be able to share some logs (take care to remove credentials) and or more detailed proxy config files to reproduce the issue.

Also have you tried to reproduce it without Fauxton in the loop?

**Comment by natcohen** [comment]
So I have tried with basic auth for the remote server which is behind the reverse proxy and it works...

When I say it exposes the password, I meant it exposes the clear password in the CouchDB replication document, not in the request!

I have tried multiple configuration (source and/or target being behind nginx) but here is a simple example to reproduce the issue. Use your own computer with CouchDB installed (not behind a reverse proxy) as the source. On a remote server, install CouchDB and nginx. I use the following config to redirect the requests to the right port (I didn't test without ssl but I don't think it's different):

```conf
server {
    listen 443 ssl http2;
    server_name db.address.com;

    ssl_certificate /etc/letsencrypt/live/db.address.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/db.address.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/db.address.com/chain.pem;
    ssl_dhparam /etc/ssl/certs/dhparam.pem;

    location / {
        proxy_pass  http://127.0.0.1:5984;
    }

    error_page 404 /404.html;
        location = /40x.html {
    }

    error_page 500 502 503 504 /50x.html;
        location = /50x.html {
    }
}
```

Try to replicate from you local computer to the remote server with session

**Comment by wohali** [comment]
@natcohen Your proxy config is incomplete.

See our documentation here: https://docs.couchdb.org/en/stable/best-practices/reverse-proxies.html#reverse-proxying-with-nginx

**Comment by natcohen** [comment]
@wohali Shame on me, I completely missed this part of the doc! Everything works except for the Fauxton issue mentioned by @nickva that grabs the url from the browser for localhost but it's already tracked in another thread!
