### ISSUE TITLE
Compaction file swap issue on CouchDB 3.x + Windows

### ISSUE THREAD

**Issue by pavellzubkov** [apache/couchdb#2632]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
Today I can't get view result with next error
log:
```
{{badmatch,{error,ebusy}},
 [{couch_mrview_compactor,swap_compacted,2,
                          [{file,"src/couch_mrview_compactor.erl"},
                           {line,232}]},
  {couch_index,commit_compacted,2,[{file,"src/couch_index.erl"},{line,406}]},
  {couch_index,handle_call,3,[{file,"src/couch_index.erl"},{line,199}]},
  {gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},
  {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},
  {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
```

server resp with status 500. err same as above . message -
`{gen_server,call,[<0.13136.57>,{get_state,16303},infinity]}`

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Steps to Reproduce
unknown

## Expected Behaviour
normal resp

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: 3.0
* Browser name and version: Chrome
* Operating system and version: image: couchdb:3.0.0 on Docker

## Additional Context
after manual restart docker container problem gone

**Comment by wohali** [comment]
@pavellzubkov How long did the problem persist?

`ebusy` means the file was busy and in use. The error message suggests the compactor was finishing up compacting your view by swapping files around. It should have been a transient error.

/cc @nickva

**Comment by wohali** [comment]
Also, was this Docker container being hosted on Windows?

**Comment by pavellzubkov** [comment]
@wohali  i've observe this problem about half hour. in active tasks tab in fauxton i've seen freezing compacton task on one of shards. 
records from log file
[lodjunk.txt](https://github.com/apache/couchdb/files/4284997/lodjunk.txt)

**Comment by wohali** [comment]
The error is coming from https://github.com/apache/couchdb/blob/master/src/couch_mrview/src/couch_mrview_compactor.erl#L232 which is where the compactor attempts to delete the index file after swapping.

One possible explanation is that you're running Docker on Windows, are mapping your data directory to a Windows file system, and something is still holding the file open. (File locking mechanisms on Windows differ from those on Unix.)

If this is Docker running on a Linux host, I'm not sure.

**Comment by pavellzubkov** [comment]
Yes. Docker on windows host. thanks for answer.

**Comment by wohali** [comment]
Reopening because this may be a problem for Windows CouchDB servers. Thanks for the report.

**Comment by wohali** [comment]
Sorry, my mistake. Looking at this code, it's not changed in years - we probably have never been able to support Windows-hosted Docker containers where the data directory is mapped to a local file system under Windows.

This probably should be added to the Docker documentation.
