### ISSUE TITLE
Deb packages for ARM64 for Ubuntu

### ISSUE THREAD

**Issue by razum2um** [apache/couchdb#2639]
Currently https://apache.bintray.com/couchdb-deb repository has only 
```
binary-amd64/
binary-i386/
```
I wonder, since aarch64 is officially supported and built, will you provide *deb packages?

**Comment by razum2um** [comment]
@wohali yep, sorry I meant ubuntu tree, namely bionic

**Comment by nickva** [comment]
We provide Debian deb packages for arm64. Using an older or similar version (based off the Debian version ubuntu was based on) should work.
