### ISSUE TITLE
Seeing error after moving shards to new hosts.

### ISSUE THREAD

**Issue by YadavRatnesh** [apache/couchdb#2640]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
We wanted to move our 3 node cluster to a 8 node cluster. I followed the steps mentioned in https://docs.couchdb.org/en/2.3.1/cluster/sharding.html#moving-a-shard.
After I removed old nodes from the cluster and database configs, I am seeing following error from all of new nodes,
_**[error] 2020-03-06T08:32:54.902589Z couchdb@NewNode1 emulator -------- Error in process <0.8567.3867> on node 'couchdb@cNewNode1' with exit value:
{{rexi_DOWN,{'couchdb@Old’Node1,noconnect}},[{mem3_rpc,rexi_call,2,[{file,"src/mem3_rpc.erl"},{line,349}]},{mem3_rep,calculate_start_seq,1,[{file,"src/mem3_rep.erl"},{line,349}]},{mem3_rep,repl,1,[{file,"src/mem3_rep.erl"},{line,218}]},{mem3_rep,go,1,[{file,"src/mem3_rep.erl"},{line,83}]},{mem3_sync,'-start_push_replication/1-fun-0-',2,[{file,"src/mem3_sync.erl"},{line,211}]}]}**_

- These error messages are logged in thousands per minute per node
- All the error are coming only for one of old node. 
- None of old machines shows up '@localhost:5984/_membership' request.

## Steps to Reproduce

Move the shards to new hosts - https://docs.couchdb.org/en/2.3.1/cluster/sharding.html#cluster-sharding-remove-shard-files

## Expected Behaviour

There should not be any errors 

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: 2.3.1
* Browser name and version:
* Operating system and version: Docker container 

## Additional Context
I am also seeing following warning in the logs
[warning] $DATE couchdb@core-*****- <0.323.0> -------- mem3_sync shards/*****/MYDBName.1524506188 couchdb@OLDNode1 {{rexi_DOWN,{'couchdb@OLDNode1,noconnect}},[{mem3_rpc,rexi_call,2,[{file,[115,114,99,47,109,101,109,51,95,114,112,99,46,101,114,108]},{line,349}]},{mem3_rep,calculate_start_seq,1,[{file,[115,114,99,47,109,101,109,51,95,114,101,112,46,101,114,108]},{line,349}]},{mem3_rep,repl,1,[{file,[115,114,99,47,109,101,109,51,95,114,101,112,46,101,114,108]},{line,218}]},{mem3_rep,go,1,[{file,[115,114,99,47,109,101,109,51,95,114,101,112,46,101,114,108]},{line,83}]},{mem3_sync,'-start_push_replication/1-fun-0-',2,[{file,[115,114,99,47,109,101,109,51,95,115,121,110,99,46,101,114,108]},{line,211}]}]}

[TIP]:  # ( Add any other context about the problem here. )

**Comment by wohali** [comment]
@YadavRatnesh 
Hi there,

This is not a CouchDB bug. GitHub is for actual CouchDB bugs only.

If you are looking for general support with using CouchDB, please try one of these other options:

* The user mailing list. Signup instructions are [here](http://couchdb.apache.org/#mailing-lists)
* The Slack/IRC chat room. Joining instructions are [here](http://couchdb.apache.org/#chat)

If, after discussing with people on-list, you are able to pinpoint an issue in our code or documentation, feel free to return to this issue.
