### ISSUE TITLE
v3.0 Possible security issue  - no login required via http://127.0.0.1:5984

### ISSUE THREAD

**Issue by nkev** [apache/couchdb#2642]
##  Description
If I login as admin via http://localhost:5984 then logout, I can no longer access any CouchDB page via localhost.

However, I can now still access the DB as admin without logging in if I change the browser URL to http://127.0.0.1:5984

## Your Environment
* CouchDB version used: v3.0
* Browser name and version: Chrome 80.0.3987.132
* Operating system and version: MacOS, Catalina 10.15.3

**Comment by wohali** [comment]
Hi there,

I can't reproduce this. Exact steps:

1. Start CouchDB (I'm using the `dev/run -n 1` script.)
2. Login to Fauxton using `https://localhost:port/_utils`
3. Log out using Fauxton.
4. Enter the URL `https://127.0.0.1:port`. At this point I see the top level `GET /` output.
5. Enter the URL `https://127.0.0.1:port/_all_dbs`, At this point I receive `{"error":"unauthorized","reason":"You are not a server admin."}`.

**Comment by nkev** [comment]
I just tried logging out and it said I was logged out (see 1 below) but the `Logout` link at the bottom left did not change to `Login` and I could still access everything (see 2 below) without even changing to 127.0.0.1:

![image](https://user-images.githubusercontent.com/5410916/76180661-ab3c2380-6212-11ea-8e7c-0b47c2c8e1fc.png)

The only thing I have different from a vanilla install is I have an additional admin user called `nuri` that has the same password as the `admin` user.

I uninstalled CouchDB (deleted `app` file in applications) and reinstalled with no luck. Please let me know if you need me to send you any kind of log file (tell me where it is too please).

**Comment by nkev** [comment]
I think that second user with same password as admin was the issue. I deleted that user and it works as expected now.
