### ISSUE TITLE
Unable to log out from Fauxton when setting cookie_domain 

### ISSUE THREAD

**Issue by natcohen** [apache/couchdb#2647]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
When the cookie_domain is set to `mydomain.com` the logout button in Fauxton shows a message that the logout was successful but it actually doesn't logout.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Steps to Reproduce

1. Add the cookie domain setting to CouchDB (explained [here](https://docs.couchdb.org/en/stable/config/auth.html#couch_httpd_auth/cookie_domain)) to your domain
2. Login as admin through Fauxton and try to logout

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour

Should logout and display the login page

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: 3.0
* Browser name and version: Chrome 80
* Operating system and version: CentOS 8

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by ericlowry** [comment]
This may be related to my issue  https://github.com/apache/couchdb/issues/2655

**Comment by rnewson** [comment]
same cause as https://github.com/apache/couchdb/issues/2655, yup. A PR is up for it.

**Comment by ericlowry** [comment]
Thanks!  BTW - I love this feature, solves a bunch of challenges I had with couch db's "native" auth services
