### ISSUE TITLE
Is there a way to make couchdb 3.0 works like couchdb 2.0 without admin ?

### ISSUE THREAD

**Issue by dummys** [apache/couchdb#2701]
Hi,

We were using couchdb 2.0 without any installation because the server is accessed only locally by only one server. We are deploying automatically couchdb on the ubuntu server. Now with 3.0 we had to first create an admin user in order to start the server, but we still can't access the server with anonymous access.
We setup like the documentation said inside `local.d/ip.ini`:
```
[chttpd]
bind_address = 0.0.0.0
require_valid_user = false

[couch_httpd_auth]
require_valid_user = false
```
and we also setup `local.d/couchdb.ini`:

```
[couchdb]
default_security = everyone
```
But we still get error like:

`undefined PUT /couchdb/1blank.pdf0_2020-_03-_22_07_39_31 404 ok`

Is there a way to make couchdb 3.0 behave like 2.0 ? What is you advice ?
Or as  it will  have only one server using this, I use the admin account ?
Or can I automate the creation of a user when installing it with debconf ? I'm already creating the admin user like this.
Thanks

**Comment by wohali** [comment]
@dummys Try changing the following in your ini file:

```
[couchdb]
default_security = everyone
```

You'll still need the admin user to start CouchDB.

**Comment by dummys** [comment]
@wohali I didn't understand, I showed you that I already have `everyone` what do you  want I put in place ?

**Comment by wohali** [comment]
@dummys Sorry, let me review this in more detail today and get back to you.

**Comment by dummys** [comment]
ok thanks

**Comment by wohali** [comment]
Sorry for rushing through this yesterday.

With CouchDB 3.0, only admin users can create databases, delete databases, or anything else mentioned here: https://docs.couchdb.org/en/stable/intro/security.html#authentication

So no, there is no way in 3.0 to allow regular users the ability to create databases without them also being admin users. Sorry about that.

Once you've created a db as an admin, a regular user can then edit that database if you give them a role and adjust the `_security` object for that database.

Or, as you say:
>  Or as it will have only one server using this, I use the admin account ?

Yes, if you're the only one using the database server, and only one thing needs to access it, and you're not worried about accidental DB creation/deletions, then just use the admin user you're creating with debconf.

> can I automate the creation of a user when installing it with debconf

No, only the admin user can be created using debconf.

**Comment by dummys** [comment]
ok now you answer correctly, appreciate. Have a nice day thanks

**Comment by vsoloviov** [comment]
If anyone else is looking here why a new database requires auth after upgrade to 3.x: you need to remove *_admin* role from http://localhost:5984/_utils/#/database/your_database_name/permissions from **Members** to make the database anonymously accessible.

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/15050416/102202480-069cef80-3ed0-11eb-9ff0-be9cfb2a3189.png">

**Comment by vectorselector** [comment]
Assuming we don't want to manually turn this off all the time:
1) is there a setting to not have this default admin role added to each database?
2) what is the correct way to form a connection string per user and password? (what are we actually SUPPOSED to be doing, even on localhost?)
