### ISSUE TITLE
CouchDB v. 2.3.1 installation verification fails on macOS Catalina 10.15.3

### ISSUE THREAD

**Issue by CharaLagou** [apache/couchdb#2702]
CouchDB v. 2.3.1 installation verification fails on macOS Catalina 10.15.3

## Description

CouchDB 2.3.1 installed with homebrew. 
Verification on Fauxton fails with message: "Error: undefined"

![image](https://user-images.githubusercontent.com/11322049/77255808-74322d00-6c6a-11ea-904d-c5580809057c.png)

There are several crash reports in Library/Logs/DiagnosticReports related to couchjs. Indicatively, I attach the most recent of them.
[couchjs_2020-03-22-192007-3_User.crash.txt](https://github.com/apache/couchdb/files/4365866/couchjs_2020-03-22-192007-3_User.crash.txt)

## Steps to Reproduce
1. Install couchdb with: $ brew install couchdb
2. Create admin on: http://127.0.0.1:5984/_utils/#createAdmin/couchdb@127.0.0.1
3. Login with admin credentials on: http://127.0.0.1:5984/_utils/#login
4. Single node setup on address 0.0.0.0 and port 5984 with admin credentials
5. Verify installation on: http://127.0.0.1:5984/_utils/#/verifyinstall

## Expected Behaviour

Successful installation verification

## Your Environment

* CouchDB version: 2.3.1
* Browser name: same result on Chrome, Safari
* Operating system and version: macOS Catalina 10.15.3

**Comment by wohali** [comment]
@CharaLagou Only the 3.0.0 installer is signed for Catalina. We're not likely to release a signed 2.3.1 installer at this time.

**Comment by CharaLagou** [comment]
@wohali I used the v. 3.0.0 installer and I cannot create an admin. Shall I open another issue for that?

**Comment by wohali** [comment]
Yes, that's fine - since you're on macOS I'll pass you off to the dev of that installer, @janl on the other ticket #2705 .
