### ISSUE TITLE
Nightly/weekly build for small fixes

### ISSUE THREAD

**Issue by natcohen** [apache/couchdb#2713]
I have a bug that blocks me from using CouchDB 3.0.0. This bug was fixed but I can't have the fixed version... is there a way to get a nightly/weekly build?

**Comment by dottorblaster** [comment]
Hi! I don't know the actual schedule but we're backporting our fixes to a `3.0.x` branch that we will use for CouchDB 3.0.1 too. So, I don't know when a new release is coming, but I think that you'll be able to use CouchDB 3 very soon :)

**Comment by natcohen** [comment]
Sounds good!
