### ISSUE TITLE
proxy authenticated user can't fetch own org.couchdb.users: object

### ISSUE THREAD

**Issue by dholth** [apache/couchdb#2734]
## Description

I'm using an nginx config to send the username to CouchDB in a header. This works in CouchDB 2.0, and gets you a proper _session in CouchDB 3.0, but users are denied access to their own user objects.

I noticed the test that contains the X-Auth-CouchDB-UserName header name is commented out.

I noticed the documentation says the password hash is mandatory, but proxy authenticated users don't have passwords in CouchDB.

Another odd thing is that the @ symbol is escaped to user%40example.org in the CouchDB logs (but not in the header data that is passed to CouchDB) CouchDB 2 and 3 do this escaping. So the CouchDB log file knows we are logged in.

A difference between CouchDB 2 and 3 is that in CouchDB 2 all _users access fails, stealthily, with a 404 instead of a 403 or some other error code.

## Steps to Reproduce

- Enable proxy authentication.
- Create user object.
- Fetch _session, sending X-Auth-CouchDB-UserName user@example.com header. Expect to be logged in.
- Fetch _users/org.couchdb.user:user@example.com, sending username in header. Expect user object in CouchDB 2, but error in CouchDB 3.

## Your Environment

nginx headers:
```
proxy_set_header X-Auth-CouchDB-UserName user@example.com;
proxy_set_header X-Auth-CouchDB-Token (hmac);
```

relevant local.ini sections:
```

[chttpd]
bind_address = 0.0.0.0
authentication_handlers = {chttpd_auth, proxy_authentication_handler}, {chttpd_auth, cookie_authentication_handler}, {chttpd_auth, default_authentication_handler}

[couch_httpd_auth]
proxy_use_secret = true
; place same secret in /usr/local/openresty/nginx/conf/dgf.conf
; secret = (python -c "import os; print os.urandom(16).encode('hex')")
timeout = 6000
```

user object:
```
{
    "_id": "org.couchdb.user:user@example.com",
    "name": "user@example.com",
    "type": "user",
    "roles": [
        "application_role"
    ],
    "full_name": "Test"
}
```

**Comment by rnewson** [comment]
Same reason as https://github.com/apache/couchdb/issues/2730, the default _security setting changed in 3.0 to a more secure setting (admin only). You can relax this yourself by modifying the _security object of the _users database. 

Mentioned in the upgrade notes for the 3.0 major release here: https://docs.couchdb.org/en/stable/whatsnew/3.0.html
