### ISSUE TITLE
when I try to make a cluster, couchdb drains my life force and tries to make me commit suicide

### ISSUE THREAD

**Issue by vectorselector** [apache/couchdb#2755]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

I have spent 1 year trying to make clusters reliably. I follow every step of https://docs.couchdb.org/en/stable/setup/cluster.html
I have tried with versions 2.3.0, 2.3.1, 3.0.0

After a few weeks of manual suffering (literally, full time weeks.) destroying and recreating servers,
I've switched to Ansible and now get my errors much quicker. I have an error factory, it seems:
The "enable cluster" post attempt returns either {"error":"unknown_error","reason":"badarg","ref":2080903964}
or "cluster is already enabled" error, 
or (my favorite one)
{"ok":true}
 followed by the add-node post attempt getting a 
{"error":"bad_request","reason":"Cluster is not enabled."}

The end result is always all nodes in "cluster_nodes" and only the setup-node in "all_nodes".
yet I can "nc -vz private-ip 5984" with success for all 3 ports 5984 4369 9100 for all hosts
attempting to finish the cluster times out.

Using Ansible has allowed me to try hundreds of combinations of the order of things, templating my vm.args and local.ini... I've literally attempted to build thousands of clusters. 
I have now spent over 3 months of my life, full time, trying to consistently make couchdb clusters.
I know your documents by heart at this point. I have a working cluster from about a year ago that I am afraid to touch, that I managed to make with Fauxton. I know it's possible. 

I must be extremely stupid (possibly a total idiot!) , but I've also literally spent months of my life trying to make couchdb clusters, so I'm fairly confident that this process can and should be improved.
At this point,  I'm miserable. This is causing health issues. CouchDB is a malicious entity laughing at me while it tries to murder me.  Am I crazy? Maybe. This is what CouchDB made me. I am its problem child. If CouchDB were not the only FOSS multi-master document DB in the world I would have run away ages ago.

## Description

"all_nodes":[only-setup-node], "cluster_nodes":[everyone]

I ensure that the vm.args has a shared cookie
I ensure that local.ini has same admin & password, same uuid, same secret.

If I manage to enable_cluster and add_node for all nodes, then when attempting to finish_cluster I usually get a {"error":"setup_error","reason":"Cluster setup timed out waiting for nodes to connect"}

## Steps to Reproduce
build servers. set firewall rules. install couchdb. mess with vm.args and local.ini. 
try to make a cluster. fail. wish that cluster configuration was in a file, not erlang memory or unicorn land. curl a few dozen more times anyway. destroy servers. repeat x10000000000000000000

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )
a cluster

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: 2.3.0, 2.3.1, 3.0.0
* Browser name and version: chromium 80
* Operating system and version: ubuntu 16.04 & 18.04

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )
clustering is stressful, difficult, apparently-magical, and contradicts this "just relax" concept.

**Comment by vectorselector** [comment]
very sorry for the strong language. i have literally suffered a lot, however, and this must be recorded for posterity, either as a testament to my stupidity, or the difficulty I outlined above.

**Comment by vectorselector** [comment]
vm.args file
```
-name couchdb@1.2.3.4

-setcookie mycookie

# Tell kernel and SASL not to log anything
-kernel error_logger silent
-sasl sasl_error_logger false

# Use kernel poll functionality if supported by emulator
+K true

# Start a pool of asynchronous IO threads
+A 16

# Comment this line out to enable the interactive Erlang shell on startup
+Bd -noinput

# Force use of the smp scheduler, fixes #1296
-smp enable

# Set maximum SSL session lifetime to reap terminated replication readers
-ssl session_lifetime 300

-kernel inet_dist_listen_min 9100
-kernel inet_dist_listen_max 9100
```

local.ini
```

; CouchDB Configuration Settings

; Custom settings should be made in this file. They will override settings
; in default.ini, but unlike changes made to default.ini, this file won't be
; overwritten on server upgrade.

[couchdb]
;max_document_size = 4294967296 ; bytes
;os_process_timeout = 5000
uuid = sameuuidonallnodesetc

[couch_peruser]
; If enabled, couch_peruser ensures that a private per-user database
; exists for each document in _users. These databases are writable only
; by the corresponding user. Databases are in the following form:
; userdb-{hex encoded username}
;enable = true
; If set to true and a user is deleted, the respective database gets
; deleted as well.
;delete_dbs = true
; Set a default q value for peruser-created databases that is different from
; cluster / q
;q = 1

[chttpd]
;port = 5984
;bind_address = 127.0.0.1
; Options for the MochiWeb HTTP server.
;server_options = [{backlog, 128}, {acceptor_pool_size, 16}]
; For more socket options, consult Erlang's module 'inet' man page.
;socket_options = [{sndbuf, 262144}, {nodelay, true}]
bind_address = 0.0.0.0

[httpd]
; NOTE that this only configures the "backend" node-local port, not the
; "frontend" clustered port. You probably don't want to change anything in
; this section.
; Uncomment next line to trigger basic-auth popup on unauthorized requests.
;WWW-Authenticate = Basic realm="administrator"

; Uncomment next line to set the configuration modification whitelist. Only
; whitelisted values may be changed via the /_config URLs. To allow the admin
; to change this value over HTTP, remember to include {httpd,config_whitelist}
; itself. Excluding it from the list would require editing this file to update
; the whitelist.
;config_whitelist = [{httpd,config_whitelist}, {log,level}, {etc,etc}]

[query_servers]
;nodejs = /usr/local/bin/couchjs-node /path/to/couchdb/share/server/main.js

[couch_httpd_auth]
; If you set this to true, you should also uncomment the WWW-Authenticate line
; above. If you don't configure a WWW-Authenticate header, CouchDB will send
; Basic realm="server" in order to prevent you getting logged out.
; require_valid_user = false
secret = 123456etc

[ssl]
;enable = true
;cert_file = /full/path/to/server_cert.pem
;key_file = /full/path/to/server_key.pem
;password = somepassword
; set to true to validate peer certificates
;verify_ssl_certificates = false
; Set to true to fail if the client does not send a certificate. Only used if verify_ssl_certificates is true.
;fail_if_no_peer_cert = false
; Path to file containing PEM encoded CA certificates (trusted
; certificates used for verifying a peer certificate). May be omitted if
; you do not want to verify the peer.
;cacert_file = /full/path/to/cacertf
; The verification fun (optional) if not specified, the default
; verification fun will be used.
;verify_fun = {Module, VerifyFun}
; maximum peer certificate depth
;ssl_certificate_max_depth = 1
;
; Reject renegotiations that do not live up to RFC 5746.
;secure_renegotiate = true
; The cipher suites that should be supported.
; Can be specified in erlang format "{ecdhe_ecdsa,aes_128_cbc,sha256}"
; or in OpenSSL format "ECDHE-ECDSA-AES128-SHA256".
;ciphers = ["ECDHE-ECDSA-AES128-SHA256", "ECDHE-ECDSA-AES128-SHA"]
; The SSL/TLS versions to support
;tls_versions = [tlsv1, 'tlsv1.1', 'tlsv1.2']

; To enable Virtual Hosts in CouchDB, add a vhost = path directive. All requests to
; the Virual Host will be redirected to the path. In the example below all requests
; to http://example.com/ are redirected to /database.
; If you run CouchDB on a specific port, include the port number in the vhost:
; example.com:5984 = /database
[vhosts]
;example.com = /database/

; To create an admin account uncomment the '[admins]' section below and add a
; line in the format 'username = password'. When you next start CouchDB, it
; will change the password to a hash (so that your passwords don't linger
; around in plain-text files). You can add more admin accounts with more
; 'username = password' lines. Don't forget to restart CouchDB after
; changing this.
[admins]
myuser = -pbkdf2-encodedpasswordfromrunningcouchdbalready

[cluster]
n = 3


```

**Comment by vectorselector** [comment]
firewall is ufw, each host allows from each other host on private ip for ports 5984, 4369, 9100
netcat to each from each works until trying to cluster, after which 5984 refuses, but port is open and works before cluster attemps

**Comment by vectorselector** [comment]
ok, it just worked suddenly, first pass adding nodes gave document-update-conflict, finished single-node cluster, then enabled other nodes all over again, worked, then added other nodes again, then finish cluster again, then it worked. suddenly.

**Comment by vectorselector** [comment]
but no joke, i still have no idea how it works, can't repeat it in ansible, can only suggest "jiggling the handle randomly" over and over again, then complaining like I did, at which point the contrarian tricky monster decides to work suddenly.

**Comment by wohali** [comment]
@vectorselector As you realised yourself, language like this is **not** welcome here and explicitly against our Code of Conduct.

If you are looking for general support with using CouchDB, and want a faster response, please try one of these other options:

* The user mailing list. Signup instructions are [here](http://couchdb.apache.org/#mailing-lists)
* The Slack/IRC chat room. Joining instructions are [here](http://couchdb.apache.org/#chat)

Next time try asking for help _before_ you get frustrated ;)
