### ISSUE TITLE
Support SpiderMonkey 68

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#2770]
## Summary

Ubuntu focal (20.04) comes out in 2 weeks. That distribution no longer carries libmozjs-60, substituting libmozjs-68 instead. This will also be the case for Debian bullseye (11.0).

Unless we want to go back to shipping our own SM packages, our best option is to carry forward support to SM68.

## Possible Solution

I've started work on this locally and will push a PR once it's ready. There's significant enough changes that it's not just a `rebar.config.script` tweak, unfortunately.

**Comment by florianb** [comment]
@wohali i missed the version of the actual js-engine when invoking `couchjs -V`, it might be a quick enhancement adding `(JS_GetImplementationVersion)[https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/JSAPI_reference/JS_GetImplementationVersion]` to the version output.

**Comment by wohali** [comment]
@florianb If you would like to add this (preferably, after the UTF8 and SM68 PRs land) it'd be a welcome addition.

Remember that SM 1.8.5 may not have this, so it'll need manual testing. Our usual CI builds won't pick this up. If you pull our `couchdbdev/debian-stretch-erlang-20.3.8.25-1` image, that still contains  1.8.5.

**Comment by florianb** [comment]
Aye - :heavy_check_mark: SM 1.8.5 supports it: https://github.com/florianb/mozjs185/blob/f07f5186515453bcf8a161e021f091d95f262665/js/src/jsapi.cpp#L1141

I'll subscribe the PR - hopefully i'll recognize its landing. otherwise bump me.
