### ISSUE TITLE
Unable to create local replication job without authentication

### ISSUE THREAD

**Issue by snilaxan** [apache/couchdb#2814]
We want to create a local replication job from "databases1" to "databases2" using an Admin Party user without authentication and fully qualified URL in both source & target database.

## Description
We tried to create a local replication job via Fauxton UI as follows.
![image](https://user-images.githubusercontent.com/3293837/80075292-1a25cf80-8568-11ea-98bd-e517ab983c69.png)

Please note that the Replication "Job Configuration" menu in Fauxton UI allows us to create a replication job with Authentication as "None".

But. we're unable to create the replication job and getting an error message like "**Missing credentials for local source database.**"

![image](https://user-images.githubusercontent.com/3293837/80076372-bef4dc80-8569-11ea-89d3-53fa2d12577e.png)

Note: **In the CouchDB 1.x, We could specify replications with just the local names of the source/target database names without authentication for replicating from local-->local.**

Also, try to create a local replication job using the following JSON via cURL request.
```
{
  "_id": "MySync-database",
  "_rev": "1-338d41144e90f6ef8d5d2d028c9f8865",
  "owner": "database1",
  "user_ctx": {
    "roles": [
      "_admin"
    ],
    "name": "root"
  },
  "continuous": true,
  "create_target": true,
  "source": "database1",
  "target": "database2"
}
```
Replication doc is successfully created but replication job failed & getting an error.
![image](https://user-images.githubusercontent.com/3293837/80078214-3461ac80-856c-11ea-89aa-28c16cfd29fa.png)

As per the CouchDB replication setting documentation, source or target database is either "Source/Target database name or URL."

![image](https://user-images.githubusercontent.com/3293837/80076919-72f66780-856a-11ea-9901-d80947ee47ea.png)

Reference: http://docs.couchdb.org/en/latest/json-structure.html#replication-settings

## Questions:

1. How to create a local replication job without authentication?
2. How to create a local replication job without fully qualified URL in both the source & target database?

Please share if there any configuration needs to change in the couchdb side to enabled the above options works.

## Steps to Reproduce
Screenshot attached above for steps to reproduce.

## Expected Behaviour
Should be able to create couch local replication job without authentication & fully qualified URL for both source & target databases.

## Your Environment
* CouchDB version used: 2.3.1
* Browser name and version: Google Chrome & Version 81.0.4044.113 (64-bit)
* Operating system and version: Ubuntu 16.04

## Additional Context
This couchdb cluster is configured with 3 nodes.

**Comment by wohali** [comment]
> 1. How to create a local replication job without authentication?

In 2.x, you need to specify the source and target both at `http://localhost/<database-name>`. This assumes Admin Party.

In 3.x, you must specify authentication.

> 2. How to create a local replication job without fully qualified URL in both the source & target database?

I'm afraid this never worked the way you might expect in 2.x and was fully removed in 3.0 to stop people from thinking it works the same as 1.x. You **must** use the `http://localhost/<database-name>` syntax for both the source and the target. Sorry about that.

For details, see https://lists.apache.org/thread.html/ddcd9db93cee363db7da571f5cbc7f2bd24b881a34e1ef734d6a0a1c@%3Cdev.couchdb.apache.org%3E and https://github.com/apache/couchdb/pull/2089 and the 3.0 release notes.

**Comment by snilaxan** [comment]
Thanks @wohali
