### ISSUE TITLE
Can't create user. Server responds with 500 Internal Server Error.

### ISSUE THREAD

**Issue by DeylEnergy** [apache/couchdb#2867]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
Hello, was following [security introduction](https://docs.couchdb.org/en/2.3.1/intro/security.html) and got into the error when trying to add a new user to $HOST/_users. The response from curl request and through Fauxton is identical. 

## Steps to Reproduce

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

**Through curl:**
```
curl -X PUT http://localhost:5984/_users/org.couchdb.user:jan \
     -H "Accept: application/json" \
     -H "Content-Type: application/json" \
     -d '{"name": "jan", "password": "apple", "roles": [], "type": "user"}'
```

**Response:**
```
*   Trying ::1:5984...
* TCP_NODELAY set
* connect to ::1 port 5984 failed: Connection refused
*   Trying 127.0.0.1:5984...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 5984 (#0)
> PUT /_users/org.couchdb.user:jan HTTP/1.1
> Host: localhost:5984
> User-Agent: curl/7.68.0
> Accept: application/json
> Content-Type: application/json
> Content-Length: 69
> 
* upload completely sent off: 69 out of 69 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Cache-Control: must-revalidate
< Content-Length: 47
< Content-Type: application/json
< Date: Tue, 05 May 2020 03:17:23 GMT
< Server: CouchDB/2.3.1 (Erlang OTP/22)
< X-Couch-Request-ID: 913ae46a1b
< X-CouchDB-Body-Time: 0
< 
{"error":"unknown_error","reason":"undefined"}
* Connection #0 to host localhost left intact
```

**And how it looks in Fauxton:**
![](https://i.imgur.com/GyCFuq9.png)

## Expected Behaviour

Server shoud respond with something like this:
```
PUT /_users/org.couchdb.user:jan HTTP/1.1
Accept: application/json
Content-Length: 62
Content-Type: application/json
Host: localhost:5984
User-Agent: curl/7.31.0
```
## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: 2.3.1-3 (from Arch community repository)
* Browser name and version: Chromium Version 80.0.3987.87 (Official Build) Arch Linux (64-bit)
* Operating system and version: Arch Linux (64-bit) / Kernel: Linux 5.5.2-arch1-1

**Comment by wohali** [comment]
Can you share your logfile output from when the error occurred? I'm not sure where Arch places it, but in our packages it's usually in `/var/log/couchdb` or similar.

**Comment by wohali** [comment]
I also note that CouchDB 2.3.1 doesn't officially support Erlang 22, but perhaps the Arch community has provided their own downstream patches for compatibility...

**Comment by DeylEnergy** [comment]
Here's the output, I start couchdb.service manually
```
May 05 10:21:23 dellpc couchdb[2716]: [notice] 2020-05-05T04:21:23.960819Z couchdb@127.0.0.1 <0.295.0> -------- rexi_buffer : cluster stable
May 05 10:21:23 dellpc couchdb[2716]: [notice] 2020-05-05T04:21:23.959978Z couchdb@127.0.0.1 <0.291.0> -------- rexi_server : cluster stable
May 05 10:21:23 dellpc couchdb[2716]: [notice] 2020-05-05T04:21:23.576165Z couchdb@127.0.0.1 <0.683.0> 5b095c6b37 localhost:5984 127.0.0.1 undefined PUT /_users/org.couchdb.user:jan 500 ok 5091
May 05 10:21:23 dellpc couchdb[2716]: [error] 2020-05-05T04:21:23.561202Z couchdb@127.0.0.1 <0.741.0> -------- rexi_server: from: couchdb@127.0.0.1(<0.738.0>) mfa: fabric_rpc:update_docs/3 exit:{timeout,{gen_server,call,[couch_proc_manager,{get_proc,{doc,<<"_design/_auth">>,{1,[<<>
May 05 10:21:18 dellpc couchdb[2716]: [error] 2020-05-05T04:21:18.579995Z couchdb@127.0.0.1 <0.755.0> -------- OS Process Error <0.756.0> :: {os_process_error,{exit_status,127}}
May 05 10:21:18 dellpc couchdb[2773]: ./bin/couchjs: error while loading shared libraries: libffi.so.7: cannot open shared object file: No such file or directory
May 05 10:21:14 dellpc couchdb[2716]: [notice] 2020-05-05T04:21:14.069774Z couchdb@127.0.0.1 <0.421.0> -------- Started replicator db changes listener <0.556.0>
May 05 10:21:14 dellpc couchdb[2716]: [notice] 2020-05-05T04:21:14.061034Z couchdb@127.0.0.1 <0.376.0> -------- couch_replicator_clustering : cluster stable
May 05 10:21:09 dellpc couchdb[2716]: [notice] 2020-05-05T04:21:09.099178Z couchdb@127.0.0.1 <0.110.0> -------- config: [features] scheduler set to true for reason nil
May 05 10:21:08 dellpc couchdb[2716]: [error] 2020-05-05T04:21:08.972105Z couchdb@127.0.0.1 <0.275.0> -------- Could not get design docs for <<"shards/e0000000-ffffffff/_users.1588035186">> error:{badarg,[{ets,member,[mem3_openers,<<"_users">>],[]},{mem3_shards,maybe_spawn_shard_w>
May 05 10:21:08 dellpc couchdb[2716]: [notice] 2020-05-05T04:21:08.966628Z couchdb@127.0.0.1 <0.295.0> -------- rexi_buffer : started servers
May 05 10:21:08 dellpc couchdb[2716]: [notice] 2020-05-05T04:21:08.959394Z couchdb@127.0.0.1 <0.291.0> -------- rexi_server : started servers
May 05 10:21:08 dellpc couchdb[2716]: [info] 2020-05-05T04:21:08.937344Z couchdb@127.0.0.1 <0.227.0> -------- Apache CouchDB has started on http://127.0.0.1:5986/
May 05 10:21:08 dellpc couchdb[2716]: [info] 2020-05-05T04:21:08.937070Z couchdb@127.0.0.1 <0.227.0> -------- Apache CouchDB has started. Time to relax.
May 05 10:21:08 dellpc couchdb[2716]: [notice] 2020-05-05T04:21:08.815137Z couchdb@127.0.0.1 <0.110.0> -------- config: [features] pluggable-storage-engines set to true for reason nil
May 05 10:21:08 dellpc couchdb[2716]: [info] 2020-05-05T04:21:08.802713Z couchdb@127.0.0.1 <0.228.0> -------- Starting couch_sup
May 05 10:21:08 dellpc couchdb[2716]: [info] 2020-05-05T04:21:08.800442Z couchdb@127.0.0.1 <0.227.0> -------- Apache CouchDB 2.3.1 is starting.
```

**Comment by wohali** [comment]
The error is:

```
May 05 10:21:18 dellpc couchdb[2773]: ./bin/couchjs: error while loading shared libraries: libffi.so.7: cannot open shared object file: No such file or directory
```

Your `libffi` is missing, or incompatible. Please speak to your distribution about fixing the CouchDB binary there.

This is not a CouchDB bug.

**Comment by DeylEnergy** [comment]
Thank you @wohali Just installed ```libffi''' dependency and it's working now.

**Comment by mikeymckay** [comment]
I'm seeing this same result, but a different output in the logfile. I have libffi7, and there is no libffi error. 

This is from the bitnami couchdb aws package which seems to be:
 Debian
 Couchdb 3.2.2.
Erlang: System version: Erlang/OTP 24 [erts-12.3.2] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [jit]


The error in the logfile is:

`[error] 2022-10-04T10:38:22.681658Z couchdb@127.0.0.1 <0.22734.281> -------- OS Process Error <0.22722.281> :: {os_process_error,{exit_status,139}}
[error] 2022-10-04T10:38:27.648770Z couchdb@127.0.0.1 <0.22774.281> -------- rexi_server: from: couchdb@127.0.0.1(<0.22951.281>) mfa: fabric_rpc:update_docs/3 exit:{timeout,{gen_server,call,[couch_proc_manager,{get_proc,{doc,<<"_design/_auth">>,{1,[<<117,58,224,21,122,139,26,34,51,159,60,14,244,241,191,25>>]},{[{<<"language">>,<<"javascript">>},{<<"validate_doc_update">>,<<"\n    function(newDoc, oldDoc, userCtx, secObj) {\n        if (newDoc._deleted === true) {\n            // allow deletes by admins and matching users\n            // without checking the other fields\n            if ((userCtx.roles.indexOf('_admin') !== -1) ||\n                (userCtx.name == oldDoc.name)) {\n                return;\n            } else {\n                throw({forbidden: 'Only admins may delete other user docs.'});\n            }\n        }\n\n        if (newDoc.type !== 'user') {\n            throw({forbidden : 'doc.type must be user'});\n        } // we only allow user docs for now\n\n        if (!newDoc.name) {\n            throw({forbidden: 'doc.name is required'});\n        }\n\n        if (!newDoc.roles) {\n            throw({forbidden: 'doc.roles must exist'});\n        }\n\n        if (!isArray(newDoc.roles)) {\n            throw({forbidden: 'doc.roles must be an array'});\n        }\n\n        for (var idx = 0; idx < newDoc.roles.length; idx++) {\n            if (typeof newDoc.roles[idx] !== 'string') {\n                throw({forbidden: 'doc.roles can only contain strings'});\n            }\n        }\n\n        if (newDoc._id !== ('org.couchdb.user:' + newDoc.name)) {\n            throw({\n                forbidden: 'Doc ID must be of the form org.couchdb.user:name'\n            });\n        }\n\n        if (oldDoc) { // validate all updates\n            if (oldDoc.name !== newDoc.name) {\n                throw({forbidden: 'Usernames can not be changed.'});\n            }\n        }\n\n        if (newDoc.password_sha && !newDoc.salt) {\n            throw({\n                forbidden: 'Users with password_sha must have a salt.' +\n                    'See /_utils/script/couch.js for example code.'\n            });\n        }\n\n        var available_schemes = [\"simple\", \"pbkdf2\", \"bcrypt\"];\n        if (newDoc.password_scheme\n                && available_schemes.indexOf(newDoc.password_scheme) == -1) {\n            throw({\n                forbidden: 'Password scheme `' + newDoc.password_scheme\n                    + '` not supported.'\n            });\n        }\n\n        if (newDoc.password_scheme === \"pbkdf2\") {\n            if (typeof(newDoc.iterations) !== \"number\") {\n               throw({forbidden: \"iterations must be a number.\"});\n            }\n            if (typeof(newDoc.derived_key) !== \"string\") {\n               throw({forbidden: \"derived_key must be a string.\"});\n            }\n        }\n\n        var is_server_or_database_admin = function(userCtx, secObj) {\n            // see if the user is a server admin\n            if(userCtx.roles.indexOf('_admin') !== -1) {\n                return true; // a server admin\n            }\n\n            // see if the user a database admin specified by name\n            if(secObj && secObj.admins && secObj.admins.names) {\n                if(secObj.admins.names.indexOf(userCtx.name) !== -1) {\n                    return true; // database admin\n                }\n            }\n\n            // see if the user a database admin specified by role\n            if(secObj && secObj.admins && secObj.admins.roles) {\n                var db_roles = secObj.admins.roles;\n                for(var idx = 0; idx < userCtx.roles.length; idx++) {\n                    var user_role = userCtx.roles[idx];\n                    if(db_roles.indexOf(user_role) !== -1) {\n                        return true; // role matches!\n                    }\n                }\n            }\n\n            return false; // default to no admin\n        }\n\n        if (!is_server_or_database_admin(userCtx, secObj)) {\n            if (oldDoc) { // validate non-admin updates\n                if (userCtx.name !== newDoc.name) {\n                    throw({\n                        forbidden: 'You may only update your own user document.'\n                    });\n                }\n                // validate role updates\n                var oldRoles = (oldDoc.roles || []).sort();\n                var newRoles = newDoc.roles.sort();\n\n                if (oldRoles.length !== newRoles.length) {\n                    throw({forbidden: 'Only _admin may edit roles'});\n                }\n\n                for (var i = 0; i < oldRoles.length; i++) {\n                    if (oldRoles[i] !== newRoles[i]) {\n                        throw({forbidden: 'Only _admin may edit roles'});\n                    }\n                }\n            } else if (newDoc.roles.length > 0) {\n                throw({forbidden: 'Only _admin may set roles'});\n            }\n        }\n\n        // no system roles in users db\n        for (var i = 0; i < newDoc.roles.length; i++) {\n            if (newDoc.roles[i] !== '_metrics') {\n              if (newDoc.roles[i][0] === '_') {\n                  throw({\n                      forbidden:\n                      'No system roles (starting with underscore) in users db.'\n                  });\n              }\n            }\n        }\n\n        // no system names as names\n        if (newDoc.name[0] === '_') {\n            throw({forbidden: 'Username may not start with underscore.'});\n        }\n\n        var badUserNameChars = [':'];\n\n        for (var i = 0; i < badUserNameChars.length; i++) {\n            if (newDoc.name.indexOf(badUserNameChars[i]) >= 0) {\n                throw({forbidden: 'Character `' + badUserNameChars[i] +\n                        '` is not allowed in usernames.'});\n            }\n        }\n    }\n">>}]},[],false,[]},{<<"_design/_auth">>,<<"1-753ae0157a8b1a22339f3c0ef4f1bf19">>}},5000]}} [{gen_server,call,3,[{file,"gen_server.erl"},{line,247}]},{couch_query_servers,get_ddoc_process,2,[{file,"src/couch_query_servers.erl"},{line,630}]},{couch_query_servers,with_ddoc_proc,2,[{file,"src/couch_query_servers.erl"},{line,525}]},{couch_query_servers,validate_doc_update,5,[{file,"src/couch_query_servers.erl"},{line,368}]},{couch_db,'-validate_doc_update_int/3-lc$^0/1-0-',5,[{file,"src/couch_db.erl"},{line,914}]},{couch_db,'-validate_doc_update_int/3-fun-1-',3,[{file,"src/couch_db.erl"},{line,917}]},{couch_stats,update_histogram,2,[{file,"src/couch_stats.erl"},{line,102}]},{couch_db,'-prep_and_validate_updates/6-fun-1-',3,[{file,"src/couch_db.erl"},{line,1014}]}]
196.207.167.189 admin PUT /_users/org.couchdb.user%3Ammckay`

**Comment by PLJNS** [comment]
I am also experiencing what @mikeymckay is reporting. I can create admins, but when I attempt to use them to create a user:

```
curl -X PUT http://localhost:5984/_users/org.couchdb.user:jan \ ;; subsititing my values
     -H "Accept: application/json" \
     -H "Content-Type: application/json" \
     -d '{"name": "jan", "password": "apple", "roles": [], "type": "user"}'
```

I receive: `{"error":"unknown_error","reason":"undefined"}`, running an add user from Fauxton also fails, as does verifying the installation on step `Create View`.

I have a suspicion that this is a problem with the "Bitnami" side of things, though that's only a guess.

```
[error] 2022-11-03T05:03:05.683431Z couchdb@127.0.0.1 <0.521.0> -------- OS Process Error <0.522.0> :: {os_process_error,{exit_status,139}}
[notice] 2022-11-03T05:03:08.330962Z couchdb@127.0.0.1 <0.374.0> -------- couch_replicator_clustering : cluster stable
[notice] 2022-11-03T05:03:08.335963Z couchdb@127.0.0.1 <0.401.0> -------- Started replicator db changes listener <0.540.0>
[info] 2022-11-03T05:03:08.336856Z couchdb@127.0.0.1 <0.542.0> -------- open_result error {not_found,no_db_file} for _replicator
[error] 2022-11-03T05:03:10.648455Z couchdb@127.0.0.1 <0.513.0> -------- rexi_server: from: couchdb@127.0.0.1(<0.509.0>) mfa: fabric_rpc:update_docs/3 exit:{timeout,{gen_server,call,[couch_proc_manager,{get_proc,{doc,<<"_design/_auth">>,{1,[<<117,58,224,21,122,139,26,34,51,159,60,14,244,241,191,25>>]},{[{<<"language">>,<<"javascript">>},{<<"validate_doc_update">>,<<"\n    function(newDoc, oldDoc, userCtx, secObj) {\n        if (newDoc._deleted === true) {\n            // allow deletes by admins and matching users\n            // without checking the other fields\n            if ((userCtx.roles.indexOf('_admin') !== -1) ||\n                (userCtx.name == oldDoc.name)) {\n                return;\n            } else {\n                throw({forbidden: 'Only admins may delete other user docs.'});\n            }\n        }\n\n        if (newDoc.type !== 'user') {\n            throw({forbidden : 'doc.type must be user'});\n        } // we only allow user docs for now\n\n        if (!newDoc.name) {\n            throw({forbidden: 'doc.name is required'});\n        }\n\n        if (!newDoc.roles) {\n            throw({forbidden: 'doc.roles must exist'});\n        }\n\n        if (!isArray(newDoc.roles)) {\n            throw({forbidden: 'doc.roles must be an array'});\n        }\n\n        for (var idx = 0; idx < newDoc.roles.length; idx++) {\n            if (typeof newDoc.roles[idx] !== 'string') {\n                throw({forbidden: 'doc.roles can only contain strings'});\n            }\n        }\n\n        if (newDoc._id !== ('org.couchdb.user:' + newDoc.name)) {\n            throw({\n                forbidden: 'Doc ID must be of the form org.couchdb.user:name'\n            });\n        }\n\n        if (oldDoc) { // validate all updates\n            if (oldDoc.name !== newDoc.name) {\n                throw({forbidden: 'Usernames can not be changed.'});\n            }\n        }\n\n        if (newDoc.password_sha && !newDoc.salt) {\n            throw({\n                forbidden: 'Users with password_sha must have a salt.' +\n                    'See /_utils/script/couch.js for example code.'\n            });\n        }\n\n        var available_schemes = [\"simple\", \"pbkdf2\", \"bcrypt\"];\n        if (newDoc.password_scheme\n                && available_schemes.indexOf(newDoc.password_scheme) == -1) {\n            throw({\n                forbidden: 'Password scheme `' + newDoc.password_scheme\n                    + '` not supported.'\n            });\n        }\n\n        if (newDoc.password_scheme === \"pbkdf2\") {\n            if (typeof(newDoc.iterations) !== \"number\") {\n               throw({forbidden: \"iterations must be a number.\"});\n            }\n            if (typeof(newDoc.derived_key) !== \"string\") {\n               throw({forbidden: \"derived_key must be a string.\"});\n            }\n        }\n\n        var is_server_or_database_admin = function(userCtx, secObj) {\n            // see if the user is a server admin\n            if(userCtx.roles.indexOf('_admin') !== -1) {\n                return true; // a server admin\n            }\n\n            // see if the user a database admin specified by name\n            if(secObj && secObj.admins && secObj.admins.names) {\n                if(secObj.admins.names.indexOf(userCtx.name) !== -1) {\n                    return true; // database admin\n                }\n            }\n\n            // see if the user a database admin specified by role\n            if(secObj && secObj.admins && secObj.admins.roles) {\n                var db_roles = secObj.admins.roles;\n                for(var idx = 0; idx < userCtx.roles.length; idx++) {\n                    var user_role = userCtx.roles[idx];\n                    if(db_roles.indexOf(user_role) !== -1) {\n                        return true; // role matches!\n                    }\n                }\n            }\n\n            return false; // default to no admin\n        }\n\n        if (!is_server_or_database_admin(userCtx, secObj)) {\n            if (oldDoc) { // validate non-admin updates\n                if (userCtx.name !== newDoc.name) {\n                    throw({\n                        forbidden: 'You may only update your own user document.'\n                    });\n                }\n                // validate role updates\n                var oldRoles = (oldDoc.roles || []).sort();\n                var newRoles = newDoc.roles.sort();\n\n                if (oldRoles.length !== newRoles.length) {\n                    throw({forbidden: 'Only _admin may edit roles'});\n                }\n\n                for (var i = 0; i < oldRoles.length; i++) {\n                    if (oldRoles[i] !== newRoles[i]) {\n                        throw({forbidden: 'Only _admin may edit roles'});\n                    }\n                }\n            } else if (newDoc.roles.length > 0) {\n                throw({forbidden: 'Only _admin may set roles'});\n            }\n        }\n\n        // no system roles in users db\n        for (var i = 0; i < newDoc.roles.length; i++) {\n            if (newDoc.roles[i] !== '_metrics') {\n              if (newDoc.roles[i][0] === '_') {\n                  throw({\n                      forbidden:\n                      'No system roles (starting with underscore) in users db.'\n                  });\n              }\n            }\n        }\n\n        // no system names as names\n        if (newDoc.name[0] === '_') {\n            throw({forbidden: 'Username may not start with underscore.'});\n        }\n\n        var badUserNameChars = [':'];\n\n        for (var i = 0; i < badUserNameChars.length; i++) {\n            if (newDoc.name.indexOf(badUserNameChars[i]) >= 0) {\n                throw({forbidden: 'Character `' + badUserNameChars[i] +\n                        '` is not allowed in usernames.'});\n            }\n        }\n    }\n">>}]},[],false,[]},{<<"_design/_auth">>,<<"1-753ae0157a8b1a22339f3c0ef4f1bf19">>}},5000]}} [{gen_server,call,3,[{file,"gen_server.erl"},{line,247}]},{couch_query_servers,get_ddoc_process,2,[{file,"src/couch_query_servers.erl"},{line,630}]},{couch_query_servers,with_ddoc_proc,2,[{file,"src/couch_query_servers.erl"},{line,525}]},{couch_query_servers,validate_doc_update,5,[{file,"src/couch_query_servers.erl"},{line,368}]},{couch_db,'-validate_doc_update_int/3-lc$^0/1-0-',5,[{file,"src/couch_db.erl"},{line,914}]},{couch_db,'-validate_doc_update_int/3-fun-1-',3,[{file,"src/couch_db.erl"},{line,917}]},{couch_stats,update_histogram,2,[{file,"src/couch_stats.erl"},{line,102}]},{couch_db,'-prep_and_validate_updates/6-fun-1-',3,[{file,"src/couch_db.erl"},{line,1014}]}]
[notice] 2022-11-03T05:03:10.659312Z couchdb@127.0.0.1 <0.487.0> 95d609dc5c 34.97.188.226:5984 24.185.35.19 admin PUT /_users/org.couchdb.user:jan 500 ok 5096
```

**Comment by pauljonescodes** [comment]
I have confirmed this is something to do with Bitnami's distribution, when I follow these instructions:

https://www.linode.com/docs/guides/install-couchdb-20-on-ubuntu/

I receive no such errors.
