### ISSUE TITLE
Unable to install CouchDB from apt in Ubuntu 20.04 "Focal"

### ISSUE THREAD

**Issue by hamiltonsalazar** [apache/couchdb#2868]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
I followed the instructions at http://docs.couchdb.org/en/stable/install/unix.html#installation-using-the-apache-couchdb-convenience-binary-packages like "Ubuntu 18.04 (bionic)" but it didn't work. Currently, there are no instructions for 20.04.

When I run sudo apt install couchdb, I expect it to install properly

## Current Behavior
Here is what I'm currently 

<pre>:<font color="#3465A4"><b>~</b></font>$ sudo apt install -y couchdb
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
No se pudieron instalar algunos paquetes. Esto puede significar que
usted pidió una situación imposible o, si está usando la distribución
inestable, que algunos paquetes necesarios aún no se han creado o se
han sacado de «Incoming».
La siguiente información puede ayudar a resolver la situación:

Los siguientes paquetes tienen dependencias incumplidas:
 couchdb : Depende: couch-libmozjs185-1.0 pero no va a instalarse
           Depende: libcurl3 (&gt;= 7.16.2) pero no es instalable
           Depende: libicu55 (&gt;= 55.1-1~) pero no es instalable
           Depende: libssl1.0.0 (&gt;= 1.0.1) pero no es instalable
<font color="#CC0000"><b>E: </b></font>No se pudieron corregir los problemas, usted ha retenido paquetes rotos.
</pre>

Sorry for the Spanish, my language is that.

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour

When I run `sudo apt install couchdb`, I expect it to install properly

## Your Environment

I'm running Ubuntu 20.04. I did not have couchdb installed previously.

**Comment by wohali** [comment]
CouchDB 3.1.0 releases today, with support for Focal.

**Comment by hamiltonsalazar** [comment]
@wohali I followed all instructions for install CouchDB 3.1.0 with support for Focal but it didn't worked. 

Current Behavior:

<pre><font color="#3465A4"><b>~</b></font>$ sudo apt install -y couchdb
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
No se pudieron instalar algunos paquetes. Esto puede significar que
usted pidió una situación imposible o, si está usando la distribución
inestable, que algunos paquetes necesarios aún no se han creado o se
han sacado de «Incoming».
La siguiente información puede ayudar a resolver la situación:

Los siguientes paquetes tienen dependencias incumplidas:
 couchdb : Depende: couch-libmozjs185-1.0 pero no va a instalarse
           Depende: libcurl3 (&gt;= 7.16.2) pero no es instalable
           Depende: libicu55 (&gt;= 55.1-1~) pero no es instalable
           Depende: libssl1.0.0 (&gt;= 1.0.1) pero no es instalable
<font color="#CC0000"><b>E: </b></font>No se pudieron corregir los problemas, usted ha retenido paquetes rotos.</pre>

**Comment by wohali** [comment]
@hamiltonsalazar I tested it just now, focal packages are working.

I see your install is trying to pull in `libcurl3`, `libicu55`, etc. Those are definitely the wrong dependencies. You probably have the `bionic` line in your `apt.conf` file.

Be sure you are trying to install our `focal` packages, not our `bionic` packages.

Run this command:

```bash
$ echo "deb https://apache.bintray.com/couchdb-deb focal main" \
    | sudo tee /etc/apt/sources.list.d/couchdb.list
```

and try again. I removed the `-a` argument to `tee` above, so that this overwrites any wrong entry you may have in `/etc/apt/sources.list.d/couchdb.list`.

**Comment by hamiltonsalazar** [comment]
@wohali 
I really appreciate your help. I have installed correctly.

Finally, i'd like to ask you about CouchDB and Java: currently, is there an official CouchDB Java driver? or could you recommend me one. 

I'm starting to work on my thesis and it's a investigation about performance comparison between CouchDB and other non-realational database engine, to support a system.

**Comment by hamiltonsalazar** [comment]
@wohali 
I really appreciate your help. I have installed correctly.

Finally, i'd like to ask you about CouchDB and Java: currently, is there an official CouchDB Java driver? or could you recommend me one.

I'm starting to work on my thesis and it's about performance comparison between CouchDB and other non-realational database engine, to support a system.

**Comment by wohali** [comment]
Good luck with your thesis work, @hamiltonsalazar !

If you are looking for general support with using CouchDB, please try one of these other options:

* The user mailing list. Signup instructions are [here](http://couchdb.apache.org/#mailing-lists)
* The Slack/IRC chat room. Joining instructions are [here](http://couchdb.apache.org/#chat)

**Comment by ErandaPeiris** [comment]
Hi, 
I did the same steps but still, the issue remains. 

root@cposTest:/etc/apache2/sites-available# sudo apt install -y couchdb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 couchdb : Depends: libmozjs-68-0 (>= 68.6.0) but it is not installable
           Depends: libc6 (>= 2.29) but 2.27-3ubuntu1.2 is to be installed
           Depends: libgcc-s1 (>= 3.3.1) but it is not installable
           Depends: libicu66 (>= 66.1-1~) but it is not installable
           Depends: libstdc++6 (>= 9) but 8.4.0-1ubuntu1~18.04 is to be installed
           Depends: libtinfo6 (>= 6) but it is not installable
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/couchdb.list:1
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/couchdb.list:1
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/couchdb.list:1
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/couchdb.list:1
W: Target CNF (main/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/couchdb.list:1
W: Target CNF (main/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/couchdb.list:1
E: Unable to correct problems, you have held broken packages.

**Comment by wohali** [comment]
Looks like you are targeting `bionic` instead of `focal`. Check your `/etc/apt/sources.list.d/couchdb.list` file.

If you need more help please try our Slack or IRC channels; you can access these via https://couchdb.apache.org/ and click on Chat.
