### ISSUE TITLE
Docker Image for new releases

### ISSUE THREAD

**Issue by grapevineai** [apache/couchdb#2871]
Could we take advantage of Github Actions/Workflow to build and automatically push and image to docker hub?

When the new 3.1.0 release will be pushed to Docker Hub?

**Comment by wohali** [comment]
We cannot, per policy at the moment.

The downstream change must be manually PR'ed, which has been done.

The images are already live.

Can you be patient for, like, 8 hours? We actually made the images live before the release announcement, you know.

**Comment by grapevineai** [comment]
🙈 sorry for my impatience...I was wondering if it was possible to do it automatically, but I got my answer.

Thank you so much!

**Comment by wohali** [comment]
Thanks for the apology and kind words, @grapevineai .

FYI we still haven't officially released 3.1.0, that'll be tomorrow lunchtime, so you're using it ahead of the announcement.
