### ISSUE TITLE
Couchdb sort param fails to retrieve the indexes and instead returns Unrecognized sort parameter: ipv4-addr.value<string>"

### ISSUE THREAD

**Issue by hamedminaee** [apache/couchdb#2882]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

Hi couch team,
I have an issue with sorting params sent to couch to return the indexed docs in a sorted order:
when I use
q:sort=ipv4-addr.value<string>
and send it to couch I get
Unrecognized sort parameter: ipv4-addr.value<string>"
however the following params sent to couch returns the indexed docs
query=ipv4-addr.value:"127.0.0.1"
which means that lucerne filtering works but sorting fails on specific fields. I am wondering is it because of the - in the field value? is there any fix for it?

[NOTE]: # ( Describe the problem you're encountering. )

when I use
q:sort=ipv4-addr.value<string>
and send it to couch I get
Unrecognized sort parameter: ipv4-addr.value<string>"

## Expected Behaviour

I should be able to get the indexed docs for the index field  ipv4-addr.value 

## Your Environment

![image](https://user-images.githubusercontent.com/52859974/81719231-2a3c1b00-9453-11ea-83e7-2d0f2271956d.png)

{"couchdb":"Welcome","version":"3.0.0","git_sha":"03a77db6c","uuid":"435c977694aa149f9a3f1e8d56e8f0ba","features":["search","access-ready","partitioned","pluggable-storage-engines","reshard","scheduler"],"vendor":{"name":"The Apache Software Foundation"}}

**Comment by rnewson** [comment]
hi,

correct, the sort field is not valid, the regex is;

https://github.com/cloudant-labs/clouseau/blob/master/src/main/scala/com/cloudant/clouseau/IndexService.scala#L879

but basically you can only use a to z, A to Z, 0 to 9, underscore and period.

**Comment by hamedminaee** [comment]
Thanks you 🙏

**Comment by raininfotech22-dharmesh** [comment]
f
