### ISSUE TITLE
500:Internal Server Error "internal_server_error",  reason: "No DB shards could be opened."

### ISSUE THREAD

**Issue by hamiltonsalazar** [apache/couchdb#2883]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Hello, i'm connecting to CouchDB from Java with Ektorp. I'm inserting with threads, it works fine until reach to around 100 threads. 

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Current Behavior

When reach to around 100 threads i get the next error:

> 500:Internal Server Error
> Response Body:
> {
>   "error" : "internal_server_error",
>   "reason" : "No DB shards could be opened.",
>   "ref" : 3763885668
> }

That one is repeating on some documents, randomly. 

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour
I want to know what is reason for that, if i can change the settings in COUCHDB to fix it. 

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment

I'm using java version "1.8.0_251" in a project with Ektorp 1.5 for connection with CouchDB. 
- CouchDB 3.1

That is my configuration of the connection with CouchDB:

```
            int milSeg = 100000;
            this.httpClient = new StdHttpClient.Builder()
                    .url("http://localhost:5984")
                    .maxConnections(100)
                    .connectionTimeout(milSeg)
                    .socketTimeout(milSeg)
                    .build();
            dbInstance = new StdCouchDbInstance(this.httpClient);
```

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

Thanks for read.

**Comment by wohali** [comment]
This isn't enough information for us to go on, I'm afraid.

If you look in your `couch.log` file we can see what errors are there.

Most likely you've run out of system resources to handle 100 requests at once. Does your system show it's out of RAM or CPU via standard monitoring utilities?

**Comment by hamiltonsalazar** [comment]
I think that is the reason, limited CPU. I appreciate that you have read. Sorry for your time, i'll close it and try a better machine.
