### ISSUE TITLE
Password requirement validation when creating users in CouchDB

### ISSUE THREAD

**Issue by sto3psl** [apache/couchdb#2951]
## Summary

When creating users in CouchDB with `PUT /_users/org.couchdb.user:<name>` I would like to have the ability to enforce password rules. For example, a password should have a minimum length of 10 characters, special characters or whatever the developer of the app wants.

I tried to accomplish this with the `validate_doc_update` function but realised that the passed document already contains `derived_key` and `salt` but no password.

My current solution involves a serverless function that acts as proxy and checks the password requirements before passing the request to CouchDB.

## Desired Behaviour

When a request is made to `PUT /_users/org.couchdb.user:<name>`, CouchDB should validate the password and return an HTTP `400` error if the validation fails. Ideally the response contains a message like: `Password does not conform to requirements.`

## Possible Solution

I had a quick chat with @janl about this problem and his idea was to add a `passwordRegex` config option to CouchDB.

Example:

```ini
# Check that a password has 10 or more characters
passwordReqex = /.{10,}/ 
```

**Comment by Terreii** [comment]
I would like to take this issue. 🙋‍♂️

But there is one change I would like to make to this feature request (or look into how easy it would be):
Change the option to a list of RegEx. All of them would have to be matched to pass.

This would make it easier to meet usual business requirements and make changes.

**Comment by janl** [comment]
@Terreii sgtm, looking forward to your PR :)

**Comment by Terreii** [comment]
I'm happy to report, that I have solved my route block (while mine wasn't as big as in the Suez Canal 🙃).
Turns out that you can't run tests if they are deactivated.

So my pull request will be to branch `3.x`.
