### ISSUE TITLE
["error","list_error","not a row 'reset'"]

### ISSUE THREAD

**Issue by teebu** [apache/couchdb#2962]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Calling a list function, throws errors. I initially started noticing these error logs. The unusual thing is after refreshing the endpoints the results come back. I talked to rnewson from couchdb and he thinks the issue sounds like a list function runs but leaves the view server (a couchjs process) in "list" mode, then the next reset (for a map/reduce or something) blows up, as we don't expect it them.

```
[debug] 2020-06-23T03:12:00.194889Z couchdb@127.0.0.1 <0.23278.930> -------- OS Process #Port<0.1239277> Input  :: ["reset",{"reduce_limit":true,"timeout":5000}]
[debug] 2020-06-23T03:12:00.196258Z couchdb@127.0.0.1 <0.23278.930> -------- OS Process #Port<0.1239277> Output :: ["error","list_error","not a row 'reset'"]
[error] 2020-06-23T03:12:00.196567Z couchdb@127.0.0.1 <0.10822.931> 6baa7e28d2 OS Process Error <0.23278.930> :: {<<"list_error">>,<<"not a row 'reset'">>}
[info] 2020-06-23T03:12:00.196771Z couchdb@127.0.0.1 <0.27104.924> -------- couch_proc_manager <0.23278.930> died normal

[debug] 2020-06-23T03:56:01.381814Z couchdb@127.0.0.1 <0.10570.941> -------- OS Process #Port<0.1263125> Output :: ["error","list_error","not a row 'ddoc'"]
[error] 2020-06-23T03:56:01.382309Z couchdb@127.0.0.1 <0.20004.938> -------- OS Process Error <0.10570.941> :: {<<"list_error">>,<<"not a row 'ddoc'">>}
[error] 2020-06-23T03:56:01.385312Z couchdb@127.0.0.1 <0.20004.938> -------- gen_server couch_proc_manager terminated with reason: bad return value {<<"list_error">>,<<"not a row 'ddoc'">>}
--
[debug] 2020-06-23T03:56:16.519341Z couchdb@127.0.0.1 <0.1703.942> -------- OS Process #Port<0.1255745> Input  :: ["reset",{"reduce_limit":true,"timeout":25000}]
[debug] 2020-06-23T03:56:16.519741Z couchdb@127.0.0.1 <0.1703.942> -------- OS Process #Port<0.1255745> Output :: ["error","list_error","not a row 'reset'"]
[error] 2020-06-23T03:56:16.519924Z couchdb@127.0.0.1 <0.11889.942> 598892c5fa OS Process Error <0.1703.942> :: {<<"list_error">>,<<"not a row 'reset'">>}
```

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Steps to Reproduce

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: 
2.3.0
* Operating system and version:
Debian GNU/Linux 9 (stretch) running on Google GCE.

## Additional Context

Erlang: 
20

[TIP]:  # ( Add any other context about the problem here. )

**Comment by teebu** [comment]
What does `waiting on user` mean? Is there something more I can provide?

**Comment by janl** [comment]
hm, I swear I had asked for more info here, but now I’m completely blanking. Sorry for the confusing tag.

**Comment by janl** [comment]
Ah yes, we’d need all your design docs in the affected db.

**Comment by teebu** [comment]
I am unable to provide that.

**Comment by wohali** [comment]
Can you try a newer version of CouchDB, specifically CouchDB 3.1.0 running on either Ubuntu 20.04 or Debian 10 (or our Docker container)? These have a newer version of CouchJS in them that may affect the results.

**Comment by janl** [comment]
please reopen with sample ddocs if this happens on the systems @wohali mentioned.

**Comment by sinm** [comment]
@wohali, @janl I may confirm it happens in v. 1.6 too. For me somehow view server stays in list-state waiting for `list_end` or `list_row`, but client asking for `ddoc, new`. I suppose this may be in case of http client that is requesting list suddenly disconnects. Nginx in front of CouchDB logged http code 499 a minute earlier.

Actually a workaround in a view server would be to drop list processing and "redirect" `ddoc, new` command to main loop but this behaviour is against test case "should exit if it gets a non-row in the middle".

**Comment by sinm** [comment]
... confirmed in v. 3.1.0, `bad_return_value` in `[<<"gen_server:call/3 L223">>,<<"couch_query_servers:ret_os_process/1 L645">>,<<"couch_query_servers:with_ddoc_proc/2 L514">>,<<"chttpd_show:send_doc_update_response/6 L127">>,<<"chttpd:handle_req_after_auth/2 L322">>,<<"chttpd:process_request/1 L305">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L150">>]`

**Comment by wohali** [comment]
We need a full test case before we can consider re-opening this, especially because a] this seems to be a bug back to 1.6.0, which means changing longstanding functionality (even if wrong) and b] list functions are deprecated and slated to be removed in 4.0.

**Comment by sinm** [comment]
@wohali I see, sounds reasonable.
Anyway my test case scenario:
1. make list that responds in chunks relatively slow
2. query list and cancel request silently just after first chunk received
3. request a lot of updates in parallel so all view servers will be busy
4. sometimes single update fails with code 500 returned

**Comment by wohali** [comment]
Can you give us actual data and a list that reproduces this? Sorry to be a stickler, but we don't have time to create these kinds of synthetic test cases.

**Comment by nickva** [comment]
I was able to reproduce this issue artificially by raising an error the list_cb (list processing callback, called for each row from the view). The the couch_js process stuck in the `getRow` was returned to the process pool.  That would be enough to trigger this bug.

The fix is rather simple and it's to only return the process to the pool there were no errors thrown here: 
https://github.com/apache/couchdb/blob/main/src/couch/src/couch_query_servers.erl#L532-L534

**Comment by nickva** [comment]
This was fixed. Closed
