### ISSUE TITLE
Remove obsolete purge_seq properties

### ISSUE THREAD

**Issue by ricellis** [apache/couchdb#3026]
## Summary

Remove the obsolete purge_seq properties from various places

## Desired Behaviour

Present meta-information without obsolete properties present.

## Possible Solution

Remove `purge_seq` properties from:
Database meta information `GET /{db}`, `POST _dbs_info`
Design document view index meta information `GET /{db}/_design/{id}`

## Additional context

Currently this information is returned with hard-coded values that mean nothing. It makes accessing/identifying the "current" information less obvious and can lead to confusion.

**Comment by nickva** [comment]
The information in the purge_seq seem to return an aggregated purge_seq from shards and doesn't seem to be hard-coded

```
http post $DB/db1/_purge doc1:='["1-4b8a35d3f70a5962f86c6dd06ceb599c"]'
```

```
    "purge_seq": "1-g1AAAABTeJzLYWBgYMpgTmHgz8tPSTV0MDQy1zMAQsMckEQeC5BkaABS_4EgK5ERp8pEhqR6sBKGLAAtGRY_",
    "sizes": {
        "active": 594,
        "external": 9,
        "file": 29026
    },
    "update_seq": "3-g1AAAACTeJzLYWBgYMpgTmHgz8tPSTV0MDQy1zMAQsMckEQeC5BkaABS_4EgK4M5kTkXKMCelJRsYpKSgqkLp0mJDEn1UCMYwEYYmBskG1skYSrPAgBISySb"
}
```

```
> fabric_view_changes:decode_seq("1-g1AAAABTeJzLYWBgYMpgTmHgz8tPSTV0MDQy1zMAQsMckEQeC5BkaABS_4EgK5ERp8pEhqR6sBKGLAAtGRY_").
[{'node1@127.0.0.1',[2147483648,4294967295],1},
 {'node1@127.0.0.1',[0,2147483647],0}]
```

Closing the issue for now as a ML discussion is a better starting point for this
