### ISSUE TITLE
Cannot Install v-3.1.0 msi in windows 10

### ISSUE THREAD

**Issue by samahudin** [apache/couchdb#3066]
Windows 10 shows errors while installing the latest package downloaded from https://couchdb.neighbourhood.ie/downloads/3.1.0/win/apache-couchdb-3.1.0.msi. 

## Description
When the package is Run using UI it shows below error:

![image](https://user-images.githubusercontent.com/49563144/89698677-131ca480-d940-11ea-914b-6e92dc48c3bd.png)

To create the log, I have tried command line : msiexec /l* log.txt /i apache-couchdb-3.0.0.msi. Now the error is like below 

![image](https://user-images.githubusercontent.com/49563144/89698725-58d96d00-d940-11ea-9cdc-bf09fe80cb5b.png)
## Steps to Reproduce
 
1. Download msi from https://couchdb.neighbourhood.ie/downloads/3.1.0/win/apache-couchdb-3.1.0.msi. 
2. method A : Double click to install
3. method B : Execute in CMD/PS : msiexec /l* log.txt /i apache-couchdb-3.0.0.msi

## Environment
![image](https://user-images.githubusercontent.com/49563144/89698843-03519000-d941-11ea-9330-8c744a0bfd31.png)

* CouchDB version used: 3.1.0
* Operating system and version: Win 10

## Additional Context
I have downloaded the package multiple times to make sure it is not corrupt on download.
I have installed and uninstalled older version of couchDB and couchbase before, not sure it has anything to do with this.
I have installed dotnetfx35.exe beforehand.

**Comment by wohali** [comment]
Can you please double-check the checksum of the file after you download it? Use the following:

```
C:\>fciv -both apache-couchdb-3.1.0.msi
//
// File Checksum Integrity Verifier version 2.05.
//
                MD5                             SHA-1
-------------------------------------------------------------------------
35a1d3e6b4df28e60abb0eef49180769 fbd609aa7d4e7fc796212d3a0c1fe71705ca425a apache-couchdb-3.1.0.msi
```

The numbers should match mine above.

**Comment by samahudin** [comment]
> Can you please double-check the checksum of the file after you download it? Use the following:
> 
> ```
> C:\>fciv -both apache-couchdb-3.1.0.msi
> //
> // File Checksum Integrity Verifier version 2.05.
> //
>                 MD5                             SHA-1
> -------------------------------------------------------------------------
> 35a1d3e6b4df28e60abb0eef49180769 fbd609aa7d4e7fc796212d3a0c1fe71705ca425a apache-couchdb-3.1.0.msi
> ```
> 
> The numbers should match mine above.

It is different for me : 
3ea46579a22d9386585b1155113d23d5 5a8479bacb8442473ea36a5dff728935ff809208 apache-couchdb-3.1.0.msi

What will be wrong ?

**Comment by wohali** [comment]
Your download is corrupted.

Try saving the file to a different drive.

Your browser may have a corrupted download. Try downloading with a different browser, or a command line utility like `wget.exe`:

`wget https://couchdb.neighbourhood.ie/downloads/3.1.0/win/apache-couchdb-3.1.0.msi`

**Comment by samahudin** [comment]
I have used Edge browser now to download the file again, still no luck! 
Also tried to get it by installing wget, but it is complaining "Unable to establish SSL connection".

Below are my observations, if it anything leads to a conclusion : 
*I have tried with packages downloaded using chrome, FF, edge without success (6 times, I think).
*Chrome and Edge showed a safety warning on the file.
*Checksum of all these files are different than that you provided.
*I have successfully installed v.2.3.1 without any glitch, so I cannot suspect browsers.

Thanks @wohali for you time on this!

**Comment by wohali** [comment]
I don't have a good answer for you here. This is the first time we've seen this reported, and no one is able to reproduce this.

**Comment by wohali** [comment]
From a host in Japan:

```bash
$ wget https://couchdb.neighbourhood.ie/downloads/3.1.0/win/apache-couchdb-3.1.0.msi
--2020-08-08 03:24:05--  https://couchdb.neighbourhood.ie/downloads/3.1.0/win/apache-couchdb-3.1.0.msi
Resolving couchdb.neighbourhood.ie (couchdb.neighbourhood.ie)... 185.26.156.32
Connecting to couchdb.neighbourhood.ie (couchdb.neighbourhood.ie)|185.26.156.32|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://couchdbneighbourhoodie.fra1.digitaloceanspaces.com/downloads/3.1.0/win/apache-couchdb-3.1.0.msi [following]
--2020-08-08 03:24:07--  https://couchdbneighbourhoodie.fra1.digitaloceanspaces.com/downloads/3.1.0/win/apache-couchdb-3.1.0.msi
Resolving couchdbneighbourhoodie.fra1.digitaloceanspaces.com (couchdbneighbourhoodie.fra1.digitaloceanspaces.com)... 5.101.109.41
Connecting to couchdbneighbourhoodie.fra1.digitaloceanspaces.com (couchdbneighbourhoodie.fra1.digitaloceanspaces.com)|5.101.109.41|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 60686336 (58M) []
Saving to: ‘apache-couchdb-3.1.0.msi’

apache-couchdb-3.1.0.m 100%[==========================>]  57.88M  6.73MB/s    in 11s     

2020-08-08 03:24:20 (5.33 MB/s) - ‘apache-couchdb-3.1.0.msi’ saved [60686336/60686336]

$ sha1sum apache-couchdb-3.1.0.msi 
fbd609aa7d4e7fc796212d3a0c1fe71705ca425a  apache-couchdb-3.1.0.msi
$ md5sum apache-couchdb-3.1.0.msi 
35a1d3e6b4df28e60abb0eef49180769  apache-couchdb-3.1.0.msi
$ ls -la apache-couchdb-3.1.0.msi 
-rw-r--r-- 1 joant joant 60686336 May  4 20:03 apache-couchdb-3.1.0.msi

```

I have the same results from my laptop here in Canada.

If your downloaded file does not match this file's size or checksum, the problem isn't on our end - it's something related to your Internet provider or your connection to the Internet.

The only possibility is that whatever ISP you are behind, in whichever country you are in, is giving you a corrupted, truncated download.

**Comment by samahudin** [comment]
Thanks @wohali for your time on this! I am still struggling on this. Let me try on other options. If anything find success, I'll post here.

**Comment by samahudin** [comment]
Finally I got 3.1.0 installed! 
The package from 'digitaloceanspaces' worked - https://couchdbneighbourhoodie.fra1.digitaloceanspaces.com/downloads/3.1.0/win/apache-couchdb-3.1.0.msi
The checksum also matches.

**The file from https://couchdb.neighbourhood.ie still seems corrupted.**

**Comment by wohali** [comment]
They are the _exact same file_. There is no corruption.

Your ISP must have a transparent proxy that cached the first URL truncated.

I bet, if you try the download again in 48 or 72 hours, it will be fine.

In any case I am glad you have a successful download now.

**Comment by samahudin** [comment]
> They are the _exact same file_. There is no corruption.
> 
> Your ISP must have a transparent proxy that cached the first URL truncated.
> 
> I bet, if you try the download again in 48 or 72 hours, it will be fine.
Sure I'll check on later.
Since this cannot be controlled from user-end, is it good to list all available mirrors in the download page?

**Comment by wohali** [comment]
There are no mirrors. The URL always redirects to a page under that domain.
