### ISSUE TITLE
I have used Edge browser now to download the file again, still no luck!

### ISSUE THREAD

**Issue by samahudin** [apache/couchdb#3067]
I have used Edge browser now to download the file again, still no luck! 
Also tried to get it by installing wget, but it is complaining "Unable to establish SSL connection".

Below are my observations, if anything leads to a conclusion : 
*I have tried with packages downloaded using chrome, FF, edge without success (6 times, I think).
*Chrome and Edge showed a safety warning on the file.
*Checksum of all these files are different than that you provided.
*I have successfully installed v.2.3.1 without any glitch, so I cannot suspect browsers.

Thanks @wohali for you time on this!

_Originally posted by @samahudin in https://github.com/apache/couchdb/issues/3066#issuecomment-670832929_

**Comment by wohali** [comment]
Please do not make duplicate issues.
