### ISSUE TITLE
upload of file bigger than 13MO is not working, despite max_document_size increased

### ISSUE THREAD

**Issue by dummys** [apache/couchdb#3085]
Hi, 
Couchdb version: `{"couchdb":"Welcome","version":"3.1.0","git_sha":"ff0feea20","uuid":"75cd56376f4cc829406aacaeec491e36","features":["access-ready","partitioned","pluggable-storage-engines","reshard","scheduler"],"vendor":{"name":"The Apache Software Foundation"}}`
We are using openemr with couchdb to store the file as document. We have a weird behavior on server running couchdb 3.x. It was working without any change on coucchdb 2.x.
Our web server are configured with `upload_max_filesize` and `post_max_size` and we tried to setup in couchdb in a ini file under local.d the following:

```
[couchdb]
max_document_size = 20000000 ; bytes

[httpd]
max_http_request_size = 4294967296 ; 4 GB
```
But when looking in the couchdb.log file we seen this:

`[notice] 2020-08-18T15:01:36.998852Z couchdb@127.0.0.1 <0.774.0> 18ff2b5c26 couchdb.openemr.local 10.10.10.10 undefined PUT /couchdb/1imgpsh_fullsize_anim.png10_2020-_08-_18_11_01_35 413 ok 1336`

So if I understand correctly, couchdb is returning a 413, ` Request Entity Too Large`, but we still don't understand how to debug further and what to adjust to make it works.

**Comment by wohali** [comment]
How big of an attachment are you trying to add?

**Comment by wohali** [comment]
Remember that your binary file is being transcoded into the json document. This results in an increase in storage size required for binary attachments.

Try bumping `max_document_size` to `40000000` for instance, and see if that works for you.
