### ISSUE TITLE
Make req.body available to custom javascript filters in _changes

### ISSUE THREAD

**Issue by stheobald** [apache/couchdb#3086]
## Summary
The docs acknowledge that a list of doc_ids involved in a filtered replication can exceed the length available in req.query, and endorse using a POST method instead of GET in this case. doc_ids can be included in the req.body in this situation.

req.body is currently ONLY read for the builtin filters (doc_id for example) and is not made available to custom javascript filters defined in _design docs. This means that any custom filter is subject to the length limitations of req.query, and cannot use req.body to work around this.

## Desired Behaviour
req.body should be available for use in custom filters where a body is provided in the request to _changes.

## Additional context
I have a situation where the number of doc_ids involved in my filtered replication can reach the limits imposed by req.query. I also need to use a custom filter to satisfy the business requirements in an efficient manner.

**Comment by stheobald** [comment]
I have discussed this with @rnewson.

**Comment by ricellis** [comment]
This works for me in CouchDB 3.3.2 e.g. with a design doc:
```json
{"filters":
  {
    "myfilter": "function(doc, req){ if (req.body.foo && doc._id.startsWith(req.body.foo)) { return true;} else { return false;}}"
  }
}
```

and

```sh
curl -H 'content-type: application/json' -d '{"foo": "someprefix"}' "${COUCH_DB}_changes?filter=filterdoc/myfilter"
```

**Comment by nickva** [comment]
This is fixed by @eiri in https://github.com/apache/couchdb/pull/3373

Close as completed.
