### ISSUE TITLE
Allow for creating databases starting with a special character

### ISSUE THREAD

**Issue by mqtik** [apache/couchdb#3136]
CouchDB has an amazing funcionality regarding _users; it's proof that special databases it's allowing developers to work faster, safer.

I'm building a couchdb panel for two of our projects (for open sourcing when ready), and I'd like to create databases that starts with _ (underscore), to be "special" databases.

That way, when listing databases, I can separate special databases from system and regular ones. 

By being this "special" databases (I'd not dare to call it system databases"), these databases can be like an inbetween system of _users and other databases, and we can create a database such as _emails, and that database can have special privileges such as send emails to _users. Another can be _assets, to store URL's of the media that the user uploads.

I'm studying the code of CouchDB and compiling, thinking to try and do this myself (the part of allow creating databases with custom characters on start), but it seems quite a bit hacky (specially for upgrading couchDB later), and I'm sure you have better ideas on how to handle this.

I was about to post on StackOverflow, but I feel this might be more of a feature request than a bug or how-to-use issue.

Thanks and I'll stay tuned for replies.

**Comment by wohali** [comment]
You will need to fork CouchDB and maintain your own version with this modification. CouchDB is not going to allow end users to create databases beginning with `_`, sorry.

**Comment by mqtik** [comment]
Oh, well. I'll have to see another way.

I'm curious @wohali, why not? I know _* databases are special, but why users can't create such databases? 

Thanks for your reply.

**Comment by wohali** [comment]
They are system reserved databases by convention. The product needs a place for expansion for ecosystem projects where specific functionality is assigned to databases starting with `_`. This includes `_users`, `_replicator`, and `_global_changes` but may expand in the future. It's a convention that dates back to the first versions of CouchDB, so it's unlikely to change. Sorry about that.
