### ISSUE TITLE
spidermonkey_68 identified as spidermonkey_60 and erroneously(?) blocked by configure on aarch64

### ISSUE THREAD

**Issue by lostnet** [apache/couchdb#3149]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

I created a couchdb3/spidermonkey_68 package on nixos, on x86_64 it works fine, but on aarch64 it errors out with the warning:
ERROR: SpiderMonkey 60 is known broken on ARM 64 (aarch64). Use 1.8.5 instead.
which comes from [couchdb/configure](https://github.com/apache/couchdb/blob/master/configure#L181)

## Steps to Reproduce

run configure --spidermonkey-version=68 on aarch64.

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour
If there is a problem with _68 this should be given in the configure and referenced in an issue, but it seems to block all versions except 1.8.5 and refer to them as _60 so it is impossible to tell if problems exist or the check is out of date.

I was under the impression that 68 was deemed fine on linux/aarch64 and I can only find references to problems building spidermonkey itself on windows/aarch64 in mozilla documentation, which is not relevant. Couchdb bugs seem to indicate that a  SEGV problem with _60 was resolved or no longer reproducable, so possibly the check should be removed entirely.

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment

* CouchDB version used: 3.1.0
* Browser name and version: N/A
* Operating system and version: nixos-unstable

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by wohali** [comment]
We've never formally tested libmozjs-68 on aarch64, and have a conservative stance on whitelisting dependencies like this under the "principle of least surprise."

To get this changed it would be best to run our test suite multiple times in a loop (`make check`) looking for any segmentation violation crashes of couchjs. If you want you can try overriding that line and running the test a few times, and let us know how it goes.

**Comment by lostnet** [comment]
Thanks @wohali, so far I've pulled in libcurl and run the make javascript part of the tests a few times. The tests still running there instead of in elixir didn't have any problems, so I'll look at bringing in any other dependencies and getting a full make check running in the next few days.

**Comment by lostnet** [comment]
I've created a repo of results from aarch64 and an x86_64 celeron for comparison [here](https://github.com/lostnet/couchdb-nix-debug) A vast majority of the noise in aarch64 tests seem to relate to a timeouts joining the cluster, etc. One involves a view test, but I don't see any SEGVs .or any coredumps occuring.

I tried unblocking and testing 1.8.5 on nixos/aarch64 but I encounter a SIGSEGV during spidermonkey's own tests due to this [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1250400) which was fixed in spidermonkey_49 and don't see which 1.8.5 [debian patch](https://sources.debian.org/patches/mozjs/1.8.5-1.0.0+dfsg-6/) would be specific to this. (Perhaps the default debian kernel is not configured with CONFIG_ARM64_VA_BITS=48 as it is on the nixos kernel I am using.)

There might be a reason to prefer debian+aarch64+1.8.5 over other spidermonkey versions on debian, but I'm not seeing 
much reason to think 1.8.5 wont segfault more often than newer versions on anything that didn't incorporate all of debian's patches, kernel settings compiler choices(?) etc.

**Comment by wohali** [comment]
OK. This is coming in too late to adjust what we do for the 3.1.1 release (that's today) but I'll look at blacklisting just SM60 for aarch64 when I'm back from holiday, week of October 5.

**Comment by lostnet** [comment]
Sounds good, have a nice holiday!

**Comment by big-r81** [comment]
Closing this, fixed in 016385f408e83e4058fbc8116c257fd579cc5688.
