### ISSUE TITLE
Can couchdb be installed on Debian bullseye?

### ISSUE THREAD

**Issue by santicalvo** [apache/couchdb#3154]
I can't install CouchDB on Debian testing (aka Bullseye).

I followed installation instructions on [the docs](https://docs.couchdb.org/en/stable/install/unix.html) and tried the installs procedures to _Debian Buster_, _Ubuntu 18.04_ and _Ubuntu 20.04_.

None of the attempts worked. They all have conflicts with the library _libicu.x.x_

```
$ sudo apt-get install -y couchdb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 couchdb : Depends: libicu66 (>= 66.1-1~) but it is not installable
```

I tried to install it from source and got the following error at the end of the process:

```
.......

You have configured Apache CouchDB, time to relax. Relax.
==> config (compile)
ERROR: OTP release 23 does not match required regex 19|20|21|22
ERROR: compile failed while processing /home/santi/Aplicaciones/couchdb/src/config: rebar_abort
make: *** [Makefile:125: couch] Error 1
```

I don't know if this is a bug, or CouchDB is not supported on my operative system. Is it so? Can CouchDB be installed on Debian testing?

Thanks

**Comment by wohali** [comment]
You will have to install from source. We only officially release packages once Debian/Ubuntu/RedHat/CentOS officially release, not for releases in testing.

**Comment by gerrycocco** [comment]
Hi.  Since Debian Bullseye's release date was 2021-08-14, can you comment on the availability of an official release package?  Thank you.
