### ISSUE TITLE
boolean parameters incorrectly handled when POSTed to view-like requests

### ISSUE THREAD

**Issue by ricellis** [apache/couchdb#3200]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

When using a `POST` with request body to pass parameters to a view-like request the boolean parameters are accepting only JSON strings, but not booleans. For example the `stable` parameter works with `"true"` and `"false"` but not `true` and `false`.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Steps to Reproduce

`POST` to a view:

`curl -H 'Content-Type: application/json' -d '{"stable": true}' 'https://examples.cloudant.com/animaldb/_design/views101/_view/latin_name'`
```{"error":"query_parse_error","reason":"Invalid value for `stable`."}```

`curl -H 'Content-Type: application/json' -d '{"stable": "true"}' 'https://examples.cloudant.com/animaldb/_design/views101/_view/latin_name'`
`{"total_rows":5,"offset":0,"rows":[...`

Equivalent `GET` behaviour:
`curl 'https://examples.cloudant.com/animaldb/_design/views101/_view/latin_name?stable=true'`
`{"total_rows":5,"offset":0,"rows":[...`

`curl 'https://examples.cloudant.com/animaldb/_design/views101/_view/latin_name?stable="true"'`
```{"error":"query_parse_error","reason":"Invalid value for `stable`."}```

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

Expected a `boolean` to be accepted.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used:
3.1.0
* Browser name and version:
N/A
* Operating system and version:
N/A

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

I think it would be beneficial to _both_ accept the `boolean` type _and_ continue to accept strings for two reasons:
1. to avoid breaking anyone who is using the already released string form
1. `update` has to accept a string for `"lazy"` in a JSON body - so it would be useful to accept `"true"` and `"false"` there as well to avoid interaction problems with strongly typed langauges where this property would need to be a string and not a boolean (to be able to support `lazy`).

Thanks to @rnewson for pointing out to me that they are being treated as strings because the support for post is currently converting the query params directly and suggesting:
>normally you have to write a separate function with clauses for all the params

and for proposing a test addition:
```erlang
body: %{
        :keys => ["_design/foo", "_design/foo2"],
        :update => false
      }
```

**Comment by rnewson** [comment]
This was introduced in https://github.com/apache/couchdb/pull/2343. As @ricellis has already noted, we normally have a different function for passing request parameters in JSON bodies (because they can be string/boolean/list/object/number) to the one that parses request params, which are always strings.

**Comment by rnewson** [comment]
If `"true"` and `"false"` have been accepted in a public couchdb release then we need to maintain that when we add support for `true` and `false`, otherwise we could consider removing it.

**Comment by bessbd** [comment]
I'm interested in fixing this.
