### ISSUE TITLE
CI infra needs fixing for fdb

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#3205]
Current platforms that fail:

* macOS (needs FDB)
* FreeBSD (has FDB installed, but `rebar` does not look in `/usr/local` for libs and include files)

https://ci-couchdb.apache.org/blue/organizations/jenkins/jenkins-cm1%2FFullPlatformMatrix/activity?branch=main for latest status.

**Comment by kocolosk** [comment]
I think this is resolved now judging by the Jenkins link above -- macOS and FreeBSD are both green.
