### ISSUE TITLE
Deprecating Javascript Update functions 

### ISSUE THREAD

**Issue by cefn** [apache/couchdb#3235]
The 3.0 documentation [doesn't warn of javascript update functions being removed](https://docs.couchdb.org/en/latest/ddocs/ddocs.html?highlight=update%20handler#update-functions) in 4.0 (unlike many other document design functions which have the warning ).

Nevertheless, I'm picking up on project work which suggests javascript update functions [will be removed](https://github.com/apache/couchdb/issues/1554).

I was hoping to rely on update functions in pouchdb (through plugin), couchdb and cloudant. Having them removed from the parent project means would not have the flexibility to move between DB providers without rearchitecting when they are eventually removed from maintained couchdb and cloudant versions. The couchdb and cloudant projects are where I'd be wanting to run to for hosting my data if pouchdb isn't stable or maintained.

This issue records my requirement for update functions to inform debate if it's not already settled. I don't think I'd be able to express these in the proposed mango forms I've seen discussed.

## Summary

I have found that the ability to transform field values into other fields on insert is fairly fundamental to my app and works around the limited expressivity of Mango and potential efficiency concerns within map/reduce. There are other places the transformation could be done, but none which is as elegant and well-managed as it is within a designdoc-managed update function. I would rather not rely on the client to maintain this consistent field-duplication and mapping before insert as it's an indexing issue.

## Desired Behaviour

I would like the future Query server implementation and API to retain the ability to intercept document insertion and run arbitrary javascript to transform it, as per existing support in 3.0.

## Additional context

In a design I'm working on, I have been depending on the ability to run updates on incoming data in order to derive fields from source field values provided. 

In this way the fields `priority` and `actionable` can be assigned and used for simple filtering and ordering later. Both fields are a mapping of existing fields, although the mapping is complex. 

Both fields are intended to assist with the ordering of task data items. Priority is an integer . Actionable is a Unix epoch time in milliseconds.

From these priority and actionable fields, several indexes can be composed via map/reduce without recalculating these values from the source fields.

As an aside, consumers will need id (for the client-side data model) and _id (for couchdb) to align, and this can be enforced here too.

This gives you a flavour...

```js
function save(storedDoc, req){
  if (!req.body) {
    return [null, "No document"]
  }

  var sentDoc = JSON.parse(req.body)
  
  //align '_id' field with 'id'
  sentDoc._id = sentDoc.id

  //project priority field
  sentDoc["*priority"] = getPriorityOrder(sentDoc)

  //project actionable field
  sentDoc["*actionable"] = whenTaskActionable(sentDoc)

  return [sentDoc, "ok"]
}
```

You can see the full implementation at https://gist.github.com/cefn/749e28f88dd5c7511dc2dd935d0381ef

**Comment by wohali** [comment]
Update functions are not being removed in 4.0.

**Comment by wohali** [comment]
For reference: https://github.com/apache/couchdb/issues/1534#issuecomment-537656882
