### ISSUE TITLE
Replication of attachments fails when the attachment name contains a +

### ISSUE THREAD

**Issue by Dev-Owl** [apache/couchdb#3239]
## Description
We noticed today that when we replicate an attachment from one CouchDB to another that you are not able to download the attachment on the other side, the side that created the document however is able to download the attachment.
We noticed that this is related to files that contain a + in the filename, like: example+broken.pdf. 

## Steps to Reproduce

1. Create a document
2. Upload a file with a + in the name
3. Replicate document 
4. Open document on the other side

## Expected Behaviour

The document can be opened on both sides once replicated

## Your Environment

* CouchDB version used: 3.1.1 / 3.1.0
* Browser name and version: Chrome  86.0.4240.111
* Operating system and version: Windows Server 2016 Data center and Ubuntu 20.04.1 

## Additional Context

We noticed that in version 3.1.1 an uploaded document containing a + in the file name gets changed by CouchDb, the + character is replaced with a space. This works around the issue but actually seems to be more a hack as a fix, changing the filename/attachment name might break some applications (like ours).

**Comment by ricellis** [comment]
This is probably related to https://github.com/apache/couchdb/issues/2235 and friends.

**Comment by iilyak** [comment]
The PR has been merged in 3.x and main. Since it is a behaviour change the fix is protected by configuration toggle.

```
[chttpd]
; Set to true to decode + to space in db and doc_id parts.
; decode_plus_to_space = true
```
