### ISSUE TITLE
Cluster replication stops working

### ISSUE THREAD

**Issue by kripper** [apache/couchdb#3241]
## Description

Replication on a 2-node CouchDB stops working.

## Steps to Reproduce

1. Setup a 2-node cluster
2. Disconnect node-2
3. Write docs to node-1
4. Reconnect node-2
5. Compare the number of docs on node-1 and node-2. Docs written to node-1 will be missing on node-2 and this problem doesn't autorecover.
6. Workarrund to fix this problem: restart CouchDB on node-1. This will force replication of missing docs.

If you cannot reproduce, disconnect and reconnect node-2 while writing docs to node-1. Repeat 3 o 4 times until replication stops working.

## Expected Behaviour

CouchDB should sync all docs when node-2 comes online again.

## Your Environment

Same setup on both nodes:

* CouchDB version used: couchdb-3.1.1-1.el7.x86_64
* Operating system and version: CentOS 7 - 3.10.0-327.el7.x86_64

## Questions

Is this normal behaviour? Is there any setting to fix this?
How can I debug this issue? Log contains passwords and too much irrelevant information.
What should I look for?

**Comment by nickva** [comment]
It was possible that nodes were not automatically reconnected when network connectivity was restored. We have fixed this by implementing explicit re-connections in https://github.com/apache/couchdb/pull/4182
