### ISSUE TITLE
CouchDB should trim all whitespace when removing comments from config entries

### ISSUE THREAD

**Issue by kocolosk** [apache/couchdb#3259]
## Description

As discovered in #3257, CouchDB will fail to parse a config entry if it contains multiple trailing whitespace characters followed by a comment.

## Steps to Reproduce

Create a config file with

```
[couchdb]
single_node=true  ; Note the two spaces instead of one
```

and CouchDB will not start up in `single_node` mode.

## Expected Behaviour

All trailing whitespace should be removed from a configuration line.

## Your Environment

CouchDB 3.1.1

**Comment by Ljzn** [comment]
https://github.com/apache/couchdb-config/pull/31 Hi, I did a fix but the travisCI is broken due to fdb.

**Comment by nickva** [comment]
This is now fixed in https://github.com/apache/couchdb/pull/4287. We simplified the parsing logic and one of the transformation steps there is to use `string:trim/1` on the value after removing the comments.
