### ISSUE TITLE
Standard headers not returned in response

### ISSUE THREAD

**Issue by vmatyusGitHub** [apache/couchdb#3261]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
There are no `X-Couch-Request-ID` and `X-CouchDB-Body-Time` header returned at the following endpoints:
* GET/HEAD /_scheduler/jobs
* GET/HEAD /_scheduler/jobs/{jobid}
* GET/HEAD {db}/{docid}?open_revs=all

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Steps to Reproduce

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

Send a request to the following endpoints:
```bash
curl --head {db}/{docid}?open_revs=all
curl --request GET {db}/_scheduler/jobs
```

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

These two headers (`X-Couch-Request-ID` and `X-CouchDB-Body-Time` ) are standard headers that should be returned for each request.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: 3.1.0, git_sha:ff0feea20
* Browser name and version: -
* Operating system and version: MAC Catalina 10.15.7

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by janl** [comment]
those look like honest oversights. A PR would get merged quickly :)

**Comment by rnewson** [comment]
The fix is simple enough. We should use the `send_json` functions from `chttpd` module, not `couch_httpd`;

couch_replicator_httpd.erl

```
-import(couch_httpd, [
    send_json/2,
    send_json/3,
    send_method_not_allowed/2
]).```

**Comment by bessbd** [comment]
I'm interested in opening a PR (or two, I guess) for this.

**Comment by bessbd** [comment]
Nit: I believe it's `_scheduler/jobs/{jobid}` instead of `{db}/_scheduler/jobs/{jobid}` in the ticket description.

**Comment by vmatyusGitHub** [comment]
> Nit: I believe it's _scheduler/jobs/{jobid} instead of {db}/_scheduler/jobs/{jobid} in the ticket description.

Yes, corrected the description.

**Comment by bessbd** [comment]
I believe this is done now. Can somebody please close the ticket?
