### ISSUE TITLE
Views can't be queried if database is being updated (regression)

### ISSUE THREAD

**Issue by rnewson** [apache/couchdb#3262]
## Description

A view cannot be queried if the database is being updated.

## Steps to Reproduce

1. run a tight loop inserting documents in one terminal
2. query a view in the other
3. Observe that the view response does not come.
4. stop the loop
5. Observe the view response.

## Expected Behaviour

The view response should return as soon as the view is at least at the update sequence of the database as of the _start_ of the view request. It should not require view seq to equal the db's current update seq.

## Your Environment

N/A

* CouchDB version used: main

## Additional Context

N/A

**Comment by davisp** [comment]
Closed via https://github.com/apache/couchdb/pull/3266
