### ISSUE TITLE
DB not found issue

### ISSUE THREAD

**Issue by anushreemjoshi** [apache/couchdb#3293]
[NOTE]: # 
DB created on Openshift clsuter is not working 

## Description

The DB was created on Openshift cluster  - by creating Couch DB cluster and then creating a route for the same.
The DB was accessible through the route. Few days , it stopped working.

## Steps to Reproduce

NA

## Expected Behaviour

DB should be working properly.

## Your Environment

Openshift cluster 4.3 
Following error is seen in couch DB operator Pod:

 formation_controller.go:186] Error syncing formation pipeline/example-couchdbcluster: database not found

* CouchDB version used:
couchdb-operator.v1.4.2 on Openshift.

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by nickva** [comment]
Perhaps if it's still an issue contact the developers couchdb-operator.v1.4.2 on Openshift. We do not support Openshift and/or couchdb-operator.
