### ISSUE TITLE
Timing error in erlfdb `flush_future_message`

### ISSUE THREAD

**Issue by leonardb** [apache/couchdb#3294]
## Description

`erlfdb:flush_future_message/1` bypasses the receive if the message is not already in the process mailbox.

This leads to errant 'ready' messages being received by the process within which the erlfdb command is being executed.

## Steps to Reproduce

I cannot produce a small test case as it requires load to allow it to expose the behavior.

We ran across this in a dev system which wraps erlfdb (couchdb-erlfdb does not allow issue submission directly)

Introducing a non-zero value for the `after` clause allows for the message to be received.

I believe this may be a case of `is_ready(Future)` returning true and the message not yet existing in the mailbox.

## Expected Behaviour

I do not expect future 'ready' messages which have already been received, via erlfdb:wait/1/2 to end up being received by other processes.

## Your Environment

* CouchDB version used: NA
* Browser name and version: NA
* Operating system and version: NA

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

if `flush_future_message` is meant to actually flush the message maybe it should actually receive and handle the expected message.

**Comment by davisp** [comment]
That seems plausible looking at it. I think the right solution would be to have a new internal API that will silence a future (as opposed to cancelling) by setting the `cancelled` flag to true so that we don't send the message.

**Comment by leonardb** [comment]
@davisp 
I'm not well versed enough in the design of the nif, but it seems that even then there may be a race condition where the message is dispatched before being silenced

**Comment by davisp** [comment]
@leonardb I've pushed a branch to `couchdb-erlfdb` that should theoretically fix the issue. Do you think you could give it a try to see if it fixes the issue for you?

**Comment by leonardb** [comment]
Thanks @davisp 

I can confirm I'm no longer receiving spurious messages with the patch applied when running the same ops/data I was using for the initial report.
