### ISSUE TITLE
No 3.1.1 binaries available for Windows

### ISSUE THREAD

**Issue by pferdone** [apache/couchdb#3295]
## Description

I tried to download the Windows x64 binaries from this website https://couchdb.apache.org/#download

Upon following the link https://couchdb.neighbourhood.ie/downloads/3.1.1/win/apache-couchdb-3.1.1.msi I am presented with:

```
Forbidden

You don't have permission to access /downloads/3.1.1/win/apache-couchdb-3.1.1.msi on this server.
```

I also tried to find an installer at https://apache.bintray.com/couchdb/win/ but only versions up to 2.3.1 can be found.

&nbsp;

EDIT:

Going to https://docs.couchdb.org/en/stable/install/windows.html#installation-from-binaries doesnt help either, cause following the link to http://couchdb.org/#download also gives me

```
Forbidden

You don't have permission to access / on this server.
Apache/2.2.15 (CentOS) Server at couchdb.org Port 80
```

**Comment by janl** [comment]
server move snafu, I’m on it

**Comment by janl** [comment]
fixed, it’ll be 3600 seconds for DNS to propagate. If you want to get ahead of the curve, `185.26.156.247` is the new IP for couchdb.neighbourhood.ie
