### ISSUE TITLE
Error loading config key from local.ini with scaped (equal) = char

### ISSUE THREAD

**Issue by mtenrero** [apache/couchdb#3319]
## Description

Configuring values in local.ini file with a key which has the = (equal) character are not read appropriately, as the first occurrence gets read as the key / value delimiter. 

I've no found a way to escape that character inside the key. It's required for some JWT tokens with kids including that character.

## Steps to Reproduce

Configure it in the local.ini file directly, or using the API (if so, it will work until the instance gets restarted) with a key containing equal character:

```ini
[jwt_keys]
rsa:h213h2h1jg3hj2= = <somevalue>
```

## Expected Behaviour

It should be parsed as `rsa:h213h2h1jg3hj2=` -> `<somevalue>` instead of `rsa:h213h2h1jg3hj2` -> `= <somevalue>`

## Your Environment

Debian and MacOS latest 3.x:  `couchdb-3.1.1.87a6b1a`

**Comment by wohali** [comment]
This is related to https://github.com/apache/couchdb/issues/2188 - both of them have issues with equals signs in keys or values in  the ini file. Fix one and you should fix the other.

**Comment by mtenrero** [comment]
I'm not sure if you realized this issue is already fixed in this PR: [https://github.com/apache/couchdb-config/pull/32](https://github.com/apache/couchdb-config/pull/32 )

**Comment by WillBDaniels** [comment]
Big +1 to this feature. Specifically, this bug blocks integration with AWS Cognito, who's `kid` is always suffixed with a `=`. Since that's the case, there's no way for jwt's generated from logging into cognito to them be used for auth in CouchDB :( 
@mtenrero did you get any traction re-opening/moving that PR over to the main repo from the (now archived) config?

**Comment by mtenrero** [comment]
> Big +1 to this feature. Specifically, this bug blocks integration with AWS Cognito, who's `kid` is always suffixed with a `=`. Since that's the case, there's no way for jwt's generated from logging into cognito to them be used for auth in CouchDB :( @mtenrero did you get any traction re-opening/moving that PR over to the main repo from the (now archived) config?

sure, I'll work on this during this week.

I did this change specifically for cognito as well :D

**Comment by nickva** [comment]
I tried a different approach here where we allow `=` in the key with the constraint that we have to use ` = ` (have a space before and after `=`) form.

https://github.com/apache/couchdb/pull/4287
