### ISSUE TITLE
HTTP GET request to http://127.0.0.1:15984/_utils/ returns 404

### ISSUE THREAD

**Issue by sklassen** [apache/couchdb#3333]
CouchDB request to http://127.0.0.1:15984/_utils/ will return 404 "Not found".

This particularly affect couchdb running under snapd. If the data and index directory are absolute (as is standard under snapd) then the rest of couchdb works correctly. 

## Description

remsh into the server shows the problem. current directory has been lost. 

```
simon@sigyn:~$ couchdb.remsh 
Erlang/OTP 19 [erts-8.3.5.4] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]
Eshell V8.3.5.4  (abort with ^G)
(couchdb@127.0.0.1)1> file:get_cwd().
{error,enoent}
```
Likely in the snapd refresh the directory is becoming unreadable. 

## Steps to Reproduce

The problem is easily reproduce. Any change to the current working directory will render the _utils directory unattainable.  

`./dev/run -n 1`

```
simon@sigyn:couchdb$ ./dev/remsh
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Eshell V10.6.4  (abort with ^G)
(node1@127.0.0.1)1> pwd().
/home/simon/src/github.com/apache/couchdb
ok
```
```
simon@sigyn:couchdb$ curl -I http://127.0.0.1:15984/_utils/
HTTP/1.1 200 OK
```
```
(node1@127.0.0.1)1> cd("/tmp").
/tmp
ok
```
```
simon@sigyn:couchdb$ curl -I http://127.0.0.1:15984/_utils/
HTTP/1.1 404 Object Not Found
```
```
(node1@127.0.0.1)2> cd("/home/simon/src/github.com/apache/couchdb").
/home/simon/src/github.com/apache/couchdb
ok
```
```
simon@sigyn:couchdb$ curl -I http://127.0.0.1:15984/_utils/
HTTP/1.1 200 OK
```

## Expected Behaviour

CouchDB should not return 404. 

## Your Environment

This problem is specific to running under snapd version 3.1.1 2020-11-25 (9)

**Comment by big-r81** [comment]
Hey @sklassen I would close this for now.
