### ISSUE TITLE
New databases created on compact, db-name.xxXXxx.couch.compact.data

### ISSUE THREAD

**Issue by Delink-D** [apache/couchdb#3348]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

I have been trying to clean my databases in couch for few days now, I noticed every time I run compact on a db manually the size of disk (shards folder) increased in size which is the opposite of what I wanted. Today I have looked trough the folder and noticed **db-name.xxXxx.couch.compact.data** this kind of dbs in the shards folders.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Steps to Reproduce

- Have a 40GB database (_db-A_)
- Move some records into another database (_bd-B_) through replication
- Using a script get all the copied records and Delete them from db-A
-  Run compact on the view `curl -q -s -H "Content-Type: application/json" -X POST localhost:5984/bigdb/_compact/xyz-view`
- Run compact on the database `curl -q -s -H "Content-Type: application/json" -X POST localhost:5984/bigdb/_compact`
- Nothing seemed to be working after running the above commands
- I looked around and found this [script](https://github.com/Napsty/scripts/blob/master/couchdb/compact_couchdb.sh) tried it to see if it will come to my rescue. The script is meant to go through all dbs compacting them
- Nothing worked

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour

When compacting a database, it should free up disk space

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: 2.3.1
* Operating system and version: Ubuntu 18.04.2

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

Is it safe to delete this extra created databases manually?
How do I clean my dbs?

**Comment by janl** [comment]
This is how compaction works. It copies all index and document data into two separate files and joins them into the new database/shard file at the end. So for the time of compaction, your disk usage is increasing. CouchDB has worked this way since before 1.0. This is not a bug.
