### ISSUE TITLE
No CouchDB Admin password found pop up should allow pasting

### ISSUE THREAD

**Issue by personalnadir** [apache/couchdb#3349]
I use a password manager to keep track of passwords. When opening CouchDB for the first time after installation a pop up appeared with the title "No CouchDB Admin password found." When I tried to paste a new password generated by my password manager, I discovered that the pop up box does will not accept the text. 

## Summary
Password dialogue boxes in CouchDB should allow text to be pasted to allow users to make use of passwords generated by password managers. 

## Desired Behaviour
Allow the pop up box to accept passwords to be pasted into into it.

## Additional context
Allow passwords to be pasted into the pop up box means the initial setup works with password managers, and allow for more complex passwords to be entered. I am using MacOS 10.15.7

**Comment by personalnadir** [comment]
The pop up box for setting the password also does not submit when pressing return, instead it adds a newline to the password, making the cursor drop out of view.

**Comment by janl** [comment]
Haha, this is on the native Mac builds I assume, I’ll take this one.

**Comment by big-r81** [comment]
Closing this, belonging to [janl/couchdb-mac-app](https://github.com/janl/couchdb-mac-app).
