### ISSUE TITLE
The authorization scheme for HTTP Basic Authentication should not be case sensitive

### ISSUE THREAD

**Issue by eiri** [apache/couchdb#3367]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Basic authentication in CouchDB expects `auth-scheme` in `Authorization` to be case sensitive and equal to "Basic".

According to [HTTP Authentication RFC2617](https://tools.ietf.org/html/rfc2617) it should be case-insensitive.

From section 1.2, emphasis is mine:

> HTTP provides a simple challenge-response authentication mechanism
   that MAY be used by a server to challenge a client request and by a
   client to provide authentication information. It uses an extensible,
   **case-insensitive token to identify the authentication scheme**...

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Steps to Reproduce

This is from dev instance with temp creds:

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

```
$ curl http://localhost:15984/test1 -X PUT -H'Authorization: basic YWRtaW46YWRtaW4='
{"error":"unauthorized","reason":"You are not a server admin."}

$ curl http://localhost:15984/test1 -X PUT -H'Authorization: Basic YWRtaW46YWRtaW4='
{"ok":true}

 $ curl http://localhost:15984/test1 -X GET -H'Authorization: BASIC YWRtaW46YWRtaW4='
{"error":"unauthorized","reason":"You are not authorized to access this db."}

 # curl http://localhost:15984/test1 -X GET -H'Authorization: Basic YWRtaW46YWRtaW4='
{"db_name":"test1", ...
```

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

Header `Authorization` for basic authentication should accept all  "Basic", "basic" and "BASIC" `auth-scheme` as valid.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: HEAD of 3.x branch
* Browser name and version: curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
* Operating system and version: Darwin 19.6.0 Darwin Kernel Version 19.6.0

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by iilyak** [comment]
The PR with a fix has been merged.
