### ISSUE TITLE
Return map reduce response in /{db}/_changes

### ISSUE THREAD

**Issue by android-programmer** [apache/couchdb#3379]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary
It would be nice to return map reduce response along with `_id`  when calling `GET /{db}/_changes`. Currently we need to get the `id` first and query the view  `/{db}/_design/{ddoc}/_view/{view}` so there are 2 round trips API call. By setting query parameters `/{db}/_changes?map=true` or `/{db}/_changes?reduce=true`, there is only 1 API call.

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

#### For map response only:
`GET  /{db}/_changes?map=true` 
#### For reduce response only:
`GET /{db}/_changes?reduce=true`

`map` and `reduce` default value is `false` 

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

**Comment by wohali** [comment]
This isn't likely to happen, the _changes feed has nothing to do with map-reduce.

Attempts to filter _changes feeds via views failed for a number of reasons, and the work was abandonned prior to 1.x.
