### ISSUE TITLE
Delayed view consistency issue in `main`

### ISSUE THREAD

**Issue by nickva** [apache/couchdb#3381]
Querying a view while the database is being concurrently updated may result in the view values returning from an older version, as seen the view indexer, but the revision of the included document may be from a newer version as seen by the API node.

To reproduce (thanks to @rnewson):

 1. Create an empty `db1` db
 2. Insert ddoc `_design/foo` doc:
```
{
 "views": {
      "bar": {
            "map": "function (doc) {emit(doc.country, doc.country,doc._rev,doc.customer,doc.accountNumber]);}"
       }
    }
}
```
3.  Run concurrent updaters with `rnd2.py` script (see below)
4. Query the view while the updater is running: 
```
curl 'foo:bar@localhost:15984/db1/_design/foo/_view/bar?include_docs=true&limit=10'
```

The revisions of the included doc might be different. The issue happens even with a single updater (1 thread):

```
{"id":"doc151","key":1,"value":[1,"12-80ee207707c0ef11bec3580e6088521a",5050477,683620],"doc":{"_id":"doc151","_rev":"28-8bf50ab6d0e9ce2235496be7c5ec771f","country":8,"customer":8542530,"accountNumber":657275}},
```

The reason this behavior happens is if view is stale, the rebuild happens once only https://github.com/apache/couchdb/blob/main/src/couch_views/src/couch_views.erl#L58 then we read view. However, with continuous updates, the view results read after the rebuild may be again stale but we read the view rows anyway and return. If the view has `include_docs=true`, the included docs may be from now a more recent db version.

The rough outline of the current algorithm looks like:
```
query() ->
 Is view fresh?
  Yes:
    Return the view, if include_docs=true, also load docs in the same Tx
  No:
    Throw `build_view` (exit transaction implicitly)
    Wait for view to reach `WaitSeq` (not in a transaction)
    When view is >= WaitSeq a watch fires the API node is notified:
      Start Tx, read the rows from the view, the view values are built up to WaitSeq only
      If the view has include_docs=true, read doc, the latest doc revision might be at WaitSeq + 5 by now
```

A few ideas on how to fix this were suggested by @kocolosk @rnewson and @davisp. The idea is to try to set the GRV of the tx which reads the view rows to the version at which the view was built, assuming we can be reasonably sure it wasn't too long (< 5 sec) in the past. That way document revisions, their bodies and all associated data will be as it was when the build had finished.

rnd2.py:
```python
#!/usr/bin/env python
​
import random
import requests
import threading
​
url='http://127.0.0.1:15984/db1/'
​
def thread_fun():
    s = requests.Session()
    s.auth = ('foo', 'bar')
    while True:
        doc_id = random.randrange(1, 1000)
        doc =  {"country": random.randrange(1,10), "customer": random.randrange(1,10000000), "accountNumber": random.randrange(1,1000000)}
        r = s.get('{}/doc{}'.format(url, doc_id))
        if r.status_code == 200:
            doc['_rev'] = r.json()['_rev']
        r = s.put('{}/doc{}'.format(url, doc_id), json = doc)
​
​
if __name__ == "__main__":
    for x in range(10):
        t = threading.Thread(target=thread_fun)
        t.start()
```

**Comment by android-programmer** [comment]
what is the environment ?

**Comment by nickva** [comment]
The environment is a recent version of the main branch (running on FDB).

**Comment by nickva** [comment]
I updated the description to not necessarily reference include_docs=true since it doesn't depend on that

**Comment by nickva** [comment]
The results of some experiments.

So playing around by saving the indexer GRV then attempting to read the view at that version we get write conflicts  in ebtree with continuous retries. The reason for that is indexer GRV does not have any of the written indexed data yet. (This is the version it read the docs and the change feed from, but it won't have any of the indexing data associated with those changes). So ebtrees are empty, and it turns out, if they are empty when we read them ebtrees end up [writing](https://github.com/apache/couchdb/blob/main/src/ebtree/src/ebtree.erl#L107-L109) (!) resulting in conflicts. Our transaction closure retries, and since it sets the same stale GRV again, it conflicts and then the cycle repeats. (Should we have a version of `ebtree:open` that is `read_only`? It might be nice to be able to assert that reading a view would only perform reads and not any unexpected writes...)

Another idea is to use the committed version of the indexer. After a transaction has committed we can retrieve the [committed version](https://apple.github.io/foundationdb/api-c.html#c.fdb_transaction_get_committed_version), then update the job progress in a separate transaction when we [finalize everything](https://github.com/apache/couchdb/blob/main/src/couch_views/src/couch_views_indexer.erl#L248). That wouldn't always work either, since a doc could have been updated while the indexing transaction was running. Since we are using snapshots to limit the number of conflicts in the indexer, do_update function will commit, but any reads of that document after the committed version might have a different doc revision.

Ideally we should read the indexed data at the committed version, but the doc bodies at the indexer GRV version. It is currently not trivial to run multiple transactions from the same process since we use the pdict to keep some state. We still could spawn a separate process running at the indexer GRV just to fetch doc bodies while the view data is read at  the current GRV. That should work, I think...

However, another issue might be that in case the indexer has batched up the indexing in more than one transaction we may not be able to the exact doc bodies from a few transactions previous to the last one. So it seems it would be at most a best effort to see updates from the last transaction which reported its progress in the couch_jobs data.

**Comment by kocolosk** [comment]
Reprising our Slack conversation:

> Ideally we should read the indexed data at the committed version, but the doc bodies at the indexer GRV version.

Yes, this is exactly the right thing to do to achieve consistency between the view and the reads of the underlying DB.

> However, another issue might be that in case the indexer has batched up the indexing in more than one transaction we may not be able to the exact doc bodies from a few transactions previous to the last one.

This is the big reason why it's important to advance the target `DbSeq` during each additional transactional batch of an indexing job. Advancing the sequence will ensure that once the indexer finally catches up, it will have observed all the latest versions of all documents associated with the last read version it acquired.

**Comment by nickva** [comment]
I updated the PR https://github.com/apache/couchdb/pull/3391 to:

 - Save both the GRV and the committed version of the indexer
 - When the view is emitted to make sure to set the view data to be read from the committed version
 - For emitting the included docs a separate process is started which will emit docs from indexer's GRV snapshot

Still WIP. The thing compiles but the one commented test still times out. Also we may need to adjust the view indexer to commit more often to avoid the indexer GRV timing out (it was kept alive since the indexer had started emitted data so it could be almost expiring by the time the view reader gets to it).

**Comment by nickva** [comment]
Cleaned up https://github.com/apache/couchdb/pull/3391 a bit and it now passes all the couch_views tests, including a new test which checks that the indexer GRV and the committed version work.

**Comment by nickva** [comment]
https://github.com/apache/couchdb/pull/3447 to go along with #3391 to lower the view indexer TX times

**Comment by nickva** [comment]
This issue is partially fixed. If the db has finished updating we'll return include_docs consistent what the view indexer has seen.

To always return a consistent view result we'd also need this [commit]( https://github.com/apache/couchdb/commit/2e40063aae17658138bfaffa2304b5e461e43e30) from @kocolosk's branch.

However, with that commit the view results may never return if the db is continuously updated at a high enough rate, and that's also something we recently changed in https://github.com/apache/couchdb/pull/3266. So, with the first commit we'd be undoing this behavior.

This may hinge on the outcome of the ML discussion about API compatibility and consistency guarantees: https://lists.apache.org/thread.html/r7d1419f04d6b59a9740b4941fde4d91d712c9aa114bc47982c6e6fc7%40%3Cdev.couchdb.apache.org%3E.
