### ISSUE TITLE
While using main branch /_reshard/jobs split always returns with 400 or 500 error

### ISSUE THREAD

**Issue by mojito317** [apache/couchdb#3387]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

The POST `/_reshard/jobs` endpoint is not working with any existing db name while I was using the main branch.

```curl
curl --location --request POST 'http://127.0.0.1:15984/_reshard/jobs' \
--header 'Content-Type: application/json' \
--data-raw '{
    "db": "_users",
    "type": "split"
}'
```

Results with a 400 error however the `_users` db is existing:

```json
{
    "error": "bad_request",
    "reason": "Invalid `db`"
}
```

I tried this out with other existing db names as well, but those are not working as well.

An odd thing is when I try out the endpoint with the `_dbs` value:

```curl
curl --location --request POST 'http://127.0.0.1:15984/_reshard/jobs' \
--header 'Content-Type: application/json' \
--data-raw '{
    "db": "_dbs",
    "type": "split"
}'
```

It results an 500 error:

```json
[
    {
        "error": "{'EXIT',\n    {function_clause,\n        [{mem3_reshard,shard_from_name,\n             [<<\"_dbs\">>],\n             [{file,\"src/mem3_reshard.erl\"},{line,199}]},\n         {mem3_reshard,start_split_job,1,\n             [{file,\"src/mem3_reshard.erl\"},{line,93}]},\n         {rpc,local_call,3,[{file,\"rpc.erl\"},{line,321}]},\n         {mem3_reshard_api,'-create_jobs/5-fun-0-',1,\n             [{file,\"src/mem3_reshard_api.erl\"},{line,32}]},\n         {lists,map,2,[{file,\"lists.erl\"},{line,1239}]},\n         {mem3_reshard_httpd,handle_reshard_req,1,\n             [{file,\"src/mem3_reshard_httpd.erl\"},{line,108}]},\n         {chttpd,handle_req_after_auth,2,[{file,\"src/chttpd.erl\"},{line,330}]},\n         {chttpd,process_request,1,[{file,\"src/chttpd.erl\"},{line,311}]}]}}",
        "node": "node1@127.0.0.1",
        "shard": "_dbs"
    }
]
```

## Steps to Reproduce

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )
1. A 201 or a 202 response, like this:

```json
[
    {
        "ok": true,
        "id": "001-46df42bb53df24c7d32212982479c85e7f4b5bdfe04526b47a0e3000899af438",
        "node": "nonode@nohost",
        "shard": "shards/00000000-7fffffff/_global_changes.1614539418"
    },
    {
        "ok": true,
        "id": "001-8964009e85822a354ac67412d003f5aa05d5c5adf9f37b70f5453e859250b6fa",
        "node": "nonode@nohost",
        "shard": "shards/80000000-ffffffff/_global_changes.1614539418"
    }
]
```

2. Or an error response with a reason that explains the cause of the problem more.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: a9e0ebe2434e4bcdc7fe156e888767e7e57c26e
* Browser name and version: cURL
* Operating system and version: BigSur 11.2.1

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by wohali** [comment]
You probably want the `3.x` branch, not `main`, which doesn't have the 2.x/3.x concept of shards anymore.

**Comment by mojito317** [comment]
Thanks for the information, @wohali!

If `main` does not have the concept of shards anymore, could the response code be a `403` or a `410` then? I think the `400` error message (```Invalid `db` ```) is misleading here. 

It also came to my notice that some of the GET reshard endpoints are working wile I was running the `main` branch, so I would like to ask for similar response codes there if you reach the point where you turn off the `reshard` endpoints properly. Thanks in front!

**Comment by wohali** [comment]
`main` is under heavy development towards `4.0` and is not feature complete, as far as I understand.

I would not be using it at the moment and would stick with `3.x` for any production use.

I'm sure a pass will be done to clean up the removed endpoints for 4.0.
