### ISSUE TITLE
Authentication chttpd_auth cookie and jwt not working side by side

### ISSUE THREAD

**Issue by tudordumitriu** [apache/couchdb#3388]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )
The 2 authentication methods should work side by side according to documentation, but (according to specific configuration described below) only one will work
## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )
If we are trying to configure in chttpd or httpd sections
authentication_handlers ={couch_httpd_auth, jwt_authentication_handler}, {chttpd_auth, cookie_authentication_handler}, {chttpd_auth, default_authentication_handler} only one handler will work (jwt of cookie)
More than that the jwt handler will only work if configured in chttpd section and cookie handler only in httpd. 
If we try activating cookie handler in chttpd or if we try jwt handler in httpd they won't work at all.
So, jwt and cookie not working together neither in chttpd nor httpd, jwt not working in httpd and cookie not working in chttpd

## Steps to Reproduce

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour
According to docs http://docs.couchdb.com/en/latest/api/server/authn.html?highlight=authentication_handlers#jwt-authentication the jwt and cookie auth handlers should be working side by side and both configurable in chttpd section
[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment
Docker Image running in K8s cluster, configured via HELM chart.
[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: 3.1.1 Docker Image
* Browser name and version: Chrome 88
* Operating system and version: Windows 10 Pro

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by wohali** [comment]
`couch_httpd_auth` is deprecated, everything should be in `chttpd_auth`. Does it work if you put everything inside there? If not, it's a bug. If yes, it's a documentation bug.

**Comment by tudordumitriu** [comment]
Once I moved the settings in chttpd_auth and updated the handlers accordingly all went fine, both auth methods working side by side.
Thanks and indeed the docs should be updated because is very confusing because they do work separately.
