### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by MatthijsBurgh** [apache/couchdb#3420]
## Description

```bash
  E: Failed to fetch https://apache.bintray.com/couchdb-deb/dists/focal/main/binary-amd64/Packages.gz  File has unexpected size (1136 != 1011). Mirror sync in progress? [IP: 34.215.63.224 443]
     Hashes of expected file:
      - Filesize:1011 [weak]
      - SHA256:54c02f85956b97b0948461d1f3b6d736163c5048ffa13d5198776b13f34ab637
      - SHA1:c0c9b49fb5898bc596790dad1ed56963644ae37e [weak]
      - MD5Sum:2d9a544a74959858c5c141c57bfeef55 [weak]
     Release file created at: Thu, 17 Sep 2020 22:04:09 +0000
  E: Some index files failed to download. They have been ignored, or old ones used instead.
```

This only seems to happen on GitHub Actions on Focal, it does work on my local machine on Focal. Also Bionic seems to work on both GitHub Actions and my local machine. So I think it is an issue related to this specific server(34.215.63.224 443).

## Steps to Reproduce

```bash
sudo sh -c 'echo "deb https://apache.bintray.com/couchdb-deb `lsb_release -cs` main" > /etc/apt/sources.list.d/couchdb.list'
wget https://couchdb.apache.org/repo/bintray-pubkey.asc -O - | sudo apt-key add -

sudo apt-get update
```

## Expected Behaviour

Just updating apt-get without any issues.

## Your Environment

* Operating system and version: Ubuntu 20.04

## Additional Context

None

**Comment by wohali** [comment]
If you repeat the action does it still occur? As you say, I can't reproduce this problem here.

We are planning to move to a new repository hosting service in the next couple of weeks, which will probably resolve this issue.

**Comment by MatthijsBurgh** [comment]
Yes, it keeps occurring when rerunning the action.

**Comment by MatthijsBurgh** [comment]
I don't experience this issue anymore on GitHub Actions.
