### ISSUE TITLE
Normalise all config options so default.ini is 100% commented out

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#3473]
The goal for `default.ini` and `local.ini` was always to have all values commented out.

It shouldn't be a hard effort to go through and make all of these values the correct defaults in the code.

Then, `default.ini` should just be **documentation** as to what the defaults are, so someone doesn't have to grep through a potentially unfriendly code base.

**Comment by chewbranca** [comment]
If the aim is to get `default.ini` to be fully commented, then I think it would be prudent to delete `config:get/2` [1] which injects a default value in. If we're expecting to have the config options fully defined in code, then i don't think there is a scenario where having a config value lookup but not having a default valued defined in the code is appropriate.

[1] https://github.com/apache/couchdb-config/blob/main/src/config.erl#L156-L157

**Comment by wohali** [comment]
Nice work @jiahuili430 @iilyak and others!

@chewbranca given this got closed, can you open a new issue for your comment?
