### ISSUE TITLE
Add packages for Debian bullseye

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#3477]
When #3476 is done, it should be trivial to publish Debian bullseye packages.

**Comment by wohali** [comment]
This is ready to go once `bullseye` is live.

**Comment by TechInterMezzo** [comment]
Any news about the bullseye package?

**Comment by wohali** [comment]
The release is being prepared, expect within 1-2 weeks. Sorry for the delay.

**Comment by AJ1989x** [comment]
Any new Informations?

**Comment by wohali** [comment]
3.2.0 has been released on bullseye. Because of dependencies, we are unable to release any older versions on bullseye at this time.
