### ISSUE TITLE
Change repo references everywhere to new Artifactory repo

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#3478]
See https://lists.apache.org/thread.html/r9200fed3fa812f8c7de07a2500425f258db3231baa8e05f288175e4a%40%3Cbuilds.apache.org%3E

Once this is live, we'll need to change:
* Documentation (installation instructions)
  * We should go back and do this at least for `2.3.1` & `3.1.1` too
* `couchdb-docker` Dockerfiles must pull from the new repo
  * This then needs to make its way into `official-images` downstream for Docker
* `couchdb-pkg` `build.sh` script to push via the new API / credentials

...all before end of April 2021. Did I miss anything?

**Comment by ajoy39** [comment]
Hi sorry for the silly and possible off topic question, but could this be why my builds on Codeship are failing at the apt update step? Getting a 403 Forbidden trying to update the repo for CouchDB

```
E: Failed to fetch https://apache.bintray.com/couchdb-deb/dists/bionic/InRelease  403  Forbidden [IP: 34.213.218.48 443]
00:13
E: The repository 'https://apache.bintray.com/couchdb-deb bionic InRelease' is not signed.
00:13
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
00:13
N: See apt-secure(8) manpage for repository creation and user configuration details.
00:13
E: Failed to fetch http://www.apache.org/dist/cassandra/debian/dists/21x/InRelease  403  Forbidden [IP: 34.213.218.48 443]
00:13
E: The repository 'http://www.apache.org/dist/cassandra/debian 21x InRelease' is not signed.
00:13
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
00:13
N: See pt-secure(8) manpage for repository creation and user configuration details.
```

If not related than I apologize, just trying to figure out why our builds are suddenly failing for a Dep we don't use (assuming it's included in the default Codeship image for Laravel)

**Comment by wohali** [comment]
@ajoy39 Thanks for the notification, we're looking into it.

**Comment by iilyak** [comment]
I am not sure whether my below note is out of scope of this ticket or not. It seems that deprecation of bintray.com had a wider impact.

> Did I miss anything?

We need to fix boost download https://github.com/cloudant-labs/ateles/blame/19a8f64d5ae965d84cff03bdf88b7c00670bef6b/CMakeLists.txt#L31. Currently the builds of ateles component are failing. The relevant ticket on boost side is https://github.com/boostorg/boost/issues/499.

**Comment by ajoy39** [comment]
I think this is out of CouchDB's hands, according to bin trays site they;re doing  scheduled brown outs today to remind customers  to move. This appears to be what was breaking our builds but they're working now https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by wohali** [comment]
Apparently, today is a "brown-out" day for bintray, encouraging their users to migrate to another platform. There is nothing we can do about it but wait, the downloads will be restored tomorrow (or later today, the note is unclear):

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

I am in discussion with ASF Infra about accelerating our efforts to move elsewhere.

**Comment by wohali** [comment]
https://status.bintray.com/ has the specifics:

> Schedule brown-out session on April 12th 6AM to 2PM Pacific Daylight Time

So we should expect the same on the 26th, if we haven't relocated by then.

**Comment by Soph** [comment]
I did run into this yesterday and found a tweet that suggested to replace `apache.bintray.com/` with ` http://apache.jfrog.io/artifactory/`. This kind of worked but `apt` still refused to use the sources because it complained the repository is not signed. 

Reading the linked thread in the first item in this issue the url sounds roughly right, so maybe there is only a tiny thing missing to get signing working? (Or just provide the new/right key for this new url)

**Comment by wohali** [comment]
@Soph That repo is indeed the eventual relocation, but isn't live yet and should not be trusted until we give the all clear.  (Amongst other things, the signing is different and hasn't been worked out yet.)
