### ISSUE TITLE
TLS v1.3 support Bitnami CouchDB

### ISSUE THREAD

**Issue by ayyappansubbiah** [apache/couchdb#3534]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

We have an application that uses Bitnami CouchDB as the data store. The couchDB is configured for SSL on port #6984. The application is using TLS v1.3 and unable to connect the couchDB as it supports only up to TLS v1.2. I am able to validate that from the browser by setting the maximum TLS version to be 1.2. Can you please how to update the CouchDB to support TLS v1.3.

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

## Desired Behaviour

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )
 Allow to support TLS v1.3 
## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by wohali** [comment]
This isn't a CouchDB issue, it's your Bitnami image.

CouchDB using a modern Erlang will support TLS v1.3.

You'll need to take this up with them, not us.
