### ISSUE TITLE
Unable To Build CouchDB 3.1.1 from source on RHEL 7.6

### ISSUE THREAD

**Issue by QualityControll** [apache/couchdb#3543]
## Description

I'm trying to follow the instructions for building CouchDB from source on RHEL 7.6:
https://docs.couchdb.org/en/stable/install/unix.html

But I am running into the following 'make' error.

ERROR: Failed to load /home/dev/couchdb-3.1.1/rebar.config: {error,
                                                                {20,file,
                                                                 {error,
                                                                  {badmatch,
                                                                   {error,
                                                                    enoent}},
                                                                  [{erl_eval,
                                                                    expr,3,
                                                                    []}]}}}
make: *** [couch] Error 1

## Steps to Reproduce

1. Downloaded CouchDB 3.1.1: https://github.com/apache/couchdb/archive/refs/tags/3.1.1.zip

2. unzip couchdb-3.1.1.zip

3. cd couchdb-3.1.1

4. sudo yum install autoconf autoconf-archive automake \
    curl-devel erlang-asn1 erlang-erts erlang-eunit gcc-c++ \
    erlang-os_mon erlang-xmerl erlang-erl_interface help2man \
    js-devel-1.8.5 libicu-devel libtool perl-Test-Harness

5.  Note that the above failed since js-devel seems to be obsoleted by couch-js-devel, installed the above, but replaced js-devel-1.8.5 with couch-js-devel-1.8.5

6.  rpm -qa | grep erlang returns this version of erlang: erlang-R16B-03.18.el7.x86_64

7.  Downloaded couchdb-rebar: https://github.com/apache/couchdb-rebar/archive/refs/heads/main.zip

8.  unzip couchdb-rebar-main.zip

9. mv couchdb-rebar-main couchdb-3.1.1/src/rebar

10. ./configure

Output of configure:

==> configuring couchdb in rel/couchdb.config
make: Entering directory `/home/dev/couchdb-3.1.1/src/rebar'
./bootstrap
No beam files found.
Recompile: src/rebar
Recompile: src/rebar_abnfc_compiler
Recompile: src/rebar_app_utils
Recompile: src/rebar_appups
Recompile: src/rebar_asn1_compiler
Recompile: src/rebar_base_compiler
Recompile: src/rebar_cleaner
Recompile: src/rebar_config
Recompile: src/rebar_core
Recompile: src/rebar_cover_utils
Recompile: src/rebar_ct
Recompile: src/rebar_deps
Recompile: src/rebar_dia_compiler
Recompile: src/rebar_dialyzer
Recompile: src/rebar_edoc
Recompile: src/rebar_erlc_compiler
Recompile: src/rebar_erlydtl_compiler
Recompile: src/rebar_escripter
Recompile: src/rebar_eunit
Recompile: src/rebar_file_utils
Recompile: src/rebar_getopt
Recompile: src/rebar_lfe_compiler
Recompile: src/rebar_log
Recompile: src/rebar_metacmds
Recompile: src/rebar_mustache
Recompile: src/rebar_neotoma_compiler
Recompile: src/rebar_otp_app
Recompile: src/rebar_otp_appup
Recompile: src/rebar_port_compiler
Recompile: src/rebar_proto_compiler
Recompile: src/rebar_proto_gpb_compiler
Recompile: src/rebar_protobuffs_compiler
Recompile: src/rebar_qc
Recompile: src/rebar_rand_compat
Recompile: src/rebar_rel_utils
Recompile: src/rebar_reltool
Recompile: src/rebar_require_vsn
Recompile: src/rebar_shell
Recompile: src/rebar_subdirs
Recompile: src/rebar_templater
Recompile: src/rebar_upgrade
Recompile: src/rebar_utils
Recompile: src/rebar_xref
Recompile: src/rmemo
==> rebar (compile)
==> rebar (escriptize)
Congratulations! You now have a self-contained script called "rebar" in
your current working directory. Place this script anywhere in your path
and you can use rebar to build OTP-compliant apps.
make: Leaving directory `/home/dev/couchdb-3.1.1/src/rebar'
make: Entering directory `/home/dev/couchdb-3.1.1/src/rebar'
make: Leaving directory `/home/dev/couchdb-3.1.1/src/rebar'
You have configured Apache CouchDB, time to relax. Relax.

12.  make release

ERROR: Failed to load /home/dev/couchdb-3.1.1/rebar.config: {error,
                                                                {20,file,
                                                                 {error,
                                                                  {badmatch,
                                                                   {error,
                                                                    enoent}},
                                                                  [{erl_eval,
                                                                    expr,3,
                                                                    []}]}}}
make: *** [couch] Error 1

I have no file in the couchdb-3.1.1 directory called 'rebar.config', although I do see a 'rebar.config.script' file.

## Expected Behaviour

CouchDB-3.1.1 compiles on RHEL 7.6 and succeeds.

## Your Environment

CouchDB 3.1.1
RedHat Enterprise Linux 7.6
Kernel: 3.10.0-957.el7.x86_64
Erlang R16B03-1 (erts-5.10.4) [source] [64-bit] [smp:12:12] [async-threads:10] [hipe] [kernel-poll:false]

**Comment by nickva** [comment]
@QualityControll Erlang R16B is not supported. Try to pick one of the 20.3.8.x+, 21.3+, 22.3+ 23.3+ versions instead.

**Comment by QualityControll** [comment]
@nickva Thanks - installing erlang 22.3 fixed my problem.

**Comment by nickva** [comment]
@QualityControll np! Thanks for reaching out!
