### ISSUE TITLE
New document inserts may sometimes conflict with themselves

### ISSUE THREAD

**Issue by nickva** [apache/couchdb#3560]
In the presence of retryable errors emitted by FDB it's possible for new document inserts to return a conflict (409) instead of a 201 response. This happens when `1021` error code is emitted along with other retryable codes.

`1021` is `commit_unknown_result` and essentially means we don't know if the transaction committed or not. In general, we have a way to [mitigate this](https://github.com/apache/couchdb/blob/main/src/fabric/src/fabric2_fdb.erl#L186-L191) by writing a unique transaction ID to subspace and then, before each transaction starts, we check the previous error code. If the transaction ID is present we know the previous transaction has committed and we return the saved result from the previous transaction (so for doc updates we'd return a 201 for example).

However, that doesn't work if another retryable error code is emitted in the same request. 

A few examples by logging on the `on_error` error code:

```
[error] 2021-05-11T05:01:39.433449Z node1@127.0.0.1 <0.517.0> b6a156aa76  ++++++++++++++ ERROR CODE 1042 +++++++++++
[error] 2021-05-11T05:01:39.435380Z node1@127.0.0.1 <0.517.0> b6a156aa76  ++++++++++++++ ERROR CODE 1009 +++++++++++
[error] 2021-05-11T05:01:39.455958Z node1@127.0.0.1 <0.517.0> b6a156aa76  ++++++++++++++ ERROR CODE 1021 +++++++++++
[error] 2021-05-11T05:01:39.472909Z node1@127.0.0.1 <0.517.0> b6a156aa76  ++++++++++++++ ERROR CODE 1009 +++++++++++
[notice] 2021-05-11T05:01:39.489403Z node1@127.0.0.1 <0.517.0> b6a156aa76 127.0.0.1:15984 127.0.0.1 adm POST /random-test-db--576460743007172517--576460752303423487 409 ok 63
```

Another example

```
[error] 2021-05-11T05:11:50.210820Z node1@127.0.0.1 <0.498.0> 77d4be8e88  ++++++++++++++ ERROR CODE 1021 +++++++++++
[error] 2021-05-11T05:11:50.218575Z node1@127.0.0.1 <0.498.0> 77d4be8e88  ++++++++++++++ ERROR CODE 1009 +++++++++++
[error] 2021-05-11T05:11:50.244467Z node1@127.0.0.1 <0.498.0> 77d4be8e88  ++++++++++++++ ERROR CODE 1021 +++++++++++
[notice] 2021-05-11T05:11:50.266724Z node1@127.0.0.1 <0.498.0> 77d4be8e88 127.0.0.1:15984 127.0.0.1 adm POST /random-test-db--576460743366880824--576460752303423488 409 ok 7
```

The glossary of error codes involved:

```
commit_unknown_result 1021
future_version 1009
proxy_memory_limit_exceeded 1042
```

I think we probably want to have a longer "memory" of the previous commit unknown result state for the request, and then keep re-using the success result on subsequent retries. 

This was discovered while running the test suite with the client buggify options turned on:

```
make buggify-elixir-suite
```

That may have to be done multiple times until it picks 1021 as the activated error it will periodically throw.

**Comment by nickva** [comment]
@jaydoane ooh a 4100 - an internal FoundationDB crash. Never seen that before!

https://apple.github.io/foundationdb/api-error-codes.html

I wonder what happened. That's not an expected result of this PR I think. Try running on master a few times perhaps you found a legitimate bug in FDB. Maybe it's an access or file limit error or somesuch.

I run most of the test with a recent-ish 6.3 branch built from scratch using. Did you use a downloaded package from Apple?

**Comment by jaydoane** [comment]
That run above was from main, so not due to your PR. I did find this, however, which looks a lot like the same issue: https://forums.foundationdb.org/t/client-side-buggify-internal-error/1824

I'm running 6.2.10 from FoundationDB-6.2.10.pkg so maybe time to upgrade. Or maybe not, since I'm hitting this issue: https://github.com/apple/foundationdb/issues/4629

**Comment by nickva** [comment]
@jaydoane nice find! that does look similar.

Try upgrading to 6.3. Or if you'd want to take the plunge and compile it from scratch :-) https://gist.github.com/nickva/3ccba519c2307a584dfbda07381d215a

**Comment by nickva** [comment]
@jaydoane and note that it is expected for buggify-elixir-suite to fail sometimes with req_timedout and a few 500s here and there. Just keep an eye out for for the 409 conflict errors when 201s are expected. The fix should eliminate those.

**Comment by jaydoane** [comment]
Compiling FDB from source sounds like a super fun time, but it seems there will be a [patch in less than a couple weeks](https://github.com/apple/foundationdb/issues/4789#issuecomment-841854553), so I'll just wait for that.

**Comment by nickva** [comment]
This is fixed
