### ISSUE TITLE
Run couchdb2.3.1 on Raspberry Pi 3B？

### ISSUE THREAD

**Issue by teafff** [apache/couchdb#3598]
## Description
I want to compile the source code of couchdb2.3.1 on Raspberry Pi 3B.

The dependency has been installed:
pi@raspberrypi:~/CouchDB/apache-couchdb-2.3.1 $ sudo ./configure 
==> configuring couchdb in rel/couchdb.config
You have configured Apache CouchDB, time to relax. Relax.

Then, I run make release:
pi@raspberrypi:~/CouchDB/apache-couchdb-2.3.1 $ sudo make release
==> config (compile)
==> b64url (compile)
==> ets_lru (compile)
==> khash (compile)
==> snappy (compile)
==> ioq (compile)
==> bear (compile)
==> meck (compile)
==> folsom (compile)
==> triq (compile)
==> hyper (compile)
==> ibrowse (compile)
==> jiffy (compile)
==> mochiweb (compile)
==> couch_epi (compile)
==> couch_log (compile)
==> chttpd (compile)
==> couch (compile)
==> couch_index (compile)
==> couch_mrview (compile)
==> couch_replicator (compile)
==> couch_plugins (compile)
==> couch_pse_tests (compile)
==> couch_event (compile)
==> couch_stats (compile)
==> couch_peruser (compile)
==> couch_tests (compile)
==> ddoc_cache (compile)
==> fabric (compile)
==> global_changes (compile)
==> mango (compile)
==> mem3 (compile)
==> rexi (compile)
==> setup (compile)
==> rel (compile)
==> apache-couchdb-2.3.1 (compile)
Installing CouchDB into rel/couchdb/ ...
ERROR: Failed to load /home/pi/CouchDB/apache-couchdb-2.3.1/src/couch/rebar.config: {error,
                                                                                     {164,
                                                                                      file,
                                                                                      {error,
                                                                                       badarg,
                                                                                       [{erlang,
                                                                                         iolist_to_binary,
                                                                                         [[["#define ",
                                                                                            "SM185",
                                                                                            " ",
                                                                                            [],
                                                                                            10],
                                                                                           ["#define ",
                                                                                            "HAVE_JS_GET_STRING_CHARS_AND_LENGTH",
                                                                                            " ",
                                                                                            "1",
                                                                                            10],
                                                                                           ["#define ",
                                                                                            "JSSCRIPT_TYPE",
                                                                                            " ",
                                                                                            "JSObject*",
                                                                                            10],
                                                                                           ["#define ",
                                                                                            "COUCHJS_NAME",
                                                                                            " ",
                                                                                            "\"couchjs\"",
                                                                                            10],
                                                                                           ["#define ",
                                                                                            "PACKAGE",
                                                                                            " ",
                                                                                            "\"apache-couchdb\"",
                                                                                            10],
                                                                                           ["#define ",
                                                                                            "PACKAGE_BUGREPORT",
                                                                                            " ",
                                                                                            "\"https://issues.apache.org/jira/browse/COUCHDB\"",
                                                                                            10],
                                                                                           ["#define ",
                                                                                            "PACKAGE_NAME",
                                                                                            " ",
                                                                                            "\"Apache CouchDB\"",
                                                                                            10],
                                                                                           ["#define ",
                                                                                            "PACKAGE_STRING",
                                                                                            " ",
                                                                                            [34,
                                                                                             65,
                                                                                             112,
                                                                                             97,
                                                                                             99,
                                                                                             104,
                                                                                             101,
                                                                                             32,
                                                                                             67,
                                                                                             111,
                                                                                             117,
                                                                                             99,
                                                                                             104,
                                                                                             68,
                                                                                             66,
                                                                                             32,
                                                                                             102,
                                                                                             97,
                                                                                             116,
                                                                                             97,
                                                                                             108,
                                                                                             58,
                                                                                             32,
                                                                                             19981,
                                                                                             26159,
                                                                                             19968,
                                                                                             20010,
                                                                                             32,
                                                                                             103,
                                                                                             105,
                                                                                             116,
                                                                                             32,
                                                                                             20179,
                                                                                             24211,
                                                                                             65288,
                                                                                             25110,
                                                                                             32773,
                                                                                             20219,
                                                                                             20309,
                                                                                             29238,
                                                                                             30446,
                                                                                             24405,
                                                                                             65289,
                                                                                             65306,
                                                                                             46,
                                                                                             103,
                                                                                             105,
                                                                                             116,
                                                                                             34],
                                                                                            10],
                                                                                           ["#define ",
                                                                                            "PACKAGE_VERSION",
                                                                                            " ",
                                                                                            [34,
                                                                                             102,
                                                                                             97,
                                                                                             116,
                                                                                             97,
                                                                                             108,
                                                                                             58,
                                                                                             32,
                                                                                             19981,
                                                                                             26159,
                                                                                             19968,
                                                                                             20010,
                                                                                             32,
                                                                                             103,
                                                                                             105,
                                                                                             116,
                                                                                             32,
                                                                                             20179,
                                                                                             24211,
                                                                                             65288,
                                                                                             25110,
                                                                                             32773,
                                                                                             20219,
                                                                                             20309,
                                                                                             29238,
                                                                                             30446,
                                                                                             24405,
                                                                                             65289,
                                                                                             65306,
                                                                                             46,
                                                                                             103,
                                                                                             105,
                                                                                             116,
                                                                                             34],
                                                                                            10]]],
                                                                                         []},
                                                                                        {erl_eval,
                                                                                         do_apply,
                                                                                         6,
                                                                                         [{file,
                                                                                           "erl_eval.erl"},
                                                                                          {line,
                                                                                           680}]},
                                                                                        {erl_eval,
                                                                                         expr,
                                                                                         5,
                                                                                         [{file,
                                                                                           "erl_eval.erl"},
                                                                                          {line,
                                                                                           449}]},
                                                                                        {erl_eval,
                                                                                         exprs,
                                                                                         5,
                                                                                         [{file,
                                                                                           "erl_eval.erl"},
                                                                                          {line,
                                                                                           126}]},
                                                                                        {file,
                                                                                         eval_stream2,
                                                                                         6,
                                                                                         [{file,
                                                                                           "file.erl"},
                                                                                          {line,
                                                                                           1393}]},
                                                                                        {file,
                                                                                         script,
                                                                                         2,
                                                                                         [{file,
                                                                                           "file.erl"},
                                                                                          {line,
                                                                                           1090}]},
                                                                                        {rebar_config,
                                                                                         new,
                                                                                         2,
                                                                                         [{file,
                                                                                           "src/rebar_config.erl"},
                                                                                          {line,
                                                                                           238}]},
                                                                                        {rebar_core,
                                                                                         process_dir,
                                                                                         4,
                                                                                         [{file,
                                                                                           "src/rebar_core.erl"},
                                                                                          {line,
                                                                                           131}]}]}}}
make: *** [Makefile:370：release] error 1

Is this caused by arm system conflict？

Can you give me some help for this problem?

## Your Environment
* CouchDB version used:2.3.1
* Browser name and version:Chrom
* Operating system and version:Raspberry Pi OS（Raspbian）

**Comment by wohali** [comment]
@teafff We don't support CouchDB 2.x anymore.

We have support for the RPi 4 already - you can install the package directly from our repositories.

For older RPis, we are blocked on our build process, and aren't likely to add support any time soon. See #892 or #1428 for detail.
