### ISSUE TITLE
CouchDB instance without search node crashes when calling a search request

### ISSUE THREAD

**Issue by mojito317** [apache/couchdb#3603]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )
CouchDB crashes if I bombard it with search requests when search node does not exist.
See [this gist file](https://gist.githubusercontent.com/mojito317/324ed8ca3770be1562ed90346b2f8fa6/raw/6b160ffdf9068309a9e38db604447e8f5da69943/gistfile1.txt) to check the logs.

## Steps to Reproduce

I could only reproduce the issue when I ran unit tests.

1. Start a plain CouchDB instance that does not contain the `_search` functionality. I used [the latest docker image](https://hub.docker.com/_/couchdb).
2. Start the `CloudantDatabaseTests` in `tests/unit/database.tests.py` file from the `cloudant/python-cloudant` repo.
I tried to skip as many tests as possible, so if you only keep these tests, you probably can reproduce the crash:
*  https://github.com/cloudant/python-cloudant/blob/master/tests/unit/database_tests.py#L1081-L1121
* https://github.com/cloudant/python-cloudant/blob/master/tests/unit/database_tests.py#L1618-L1643
* https://github.com/cloudant/python-cloudant/blob/master/tests/unit/database_tests.py#L1645-L1677

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )
CouchDB should not crash.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: 3.1.1
* Browser name and version: not a browser, I tried it via `python-cloudant` (master)
* Operating system and version: macOS Big Sur, 11.3.1

## Additional Context

You have to set the following env vars when starting the `nosetest`:
```sh
DB_USER={uname};DB_PASSWORD={pwd};DB_URL=http://127.0.0.1:5984;RUN_CLOUDANT_TESTS=false
```

[TIP]:  # ( Add any other context about the problem here. )

**Comment by rnewson** [comment]
fixed by https://github.com/apache/couchdb/pull/4404
