### ISSUE TITLE
Incorrect response from `/db/_bulk_get` when requesting deleted document ID

### ISSUE THREAD

**Issue by phedny** [apache/couchdb#3608]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

When sending a POST request to `/db/_bulk_get` endpoint that requests a document that has been deleted, this is not returned as an error, but as an ok.

## Steps to Reproduce

Assuming a local database `demo`:

1. Create a document: `curl -X PUT http://localhost:5984/demo/id --header $AUTH_HEADER --header $JSON_HEADER -d '{"key":"value"}'`
2. Delete the document: `curl -X DELETE http://localhost:5984/demo/id\?rev=1-59414e77c768bc202142ac82c2f129de --header $AUTH_HEADER`
3. Bulk get the document by `_id`: `curl -X POST http://localhost:5984//demo/_bulk_get $AUTH_HEADER --header $JSON_HEADER -d '{"docs": [{"id": "id"}]}'`

## Expected Behaviour

I expected a result that is similar to the situation when the document had never existed (with `reason` set to `deleted` instead of `missing`), e.g.
```json
{"results": [{"id": "id", "docs": [{"error":{"id":"id","rev":"undefined","error":"not_found","reason":"deleted"}}]}]}
```

The actual result is:
```json
{"results": [{"id": "id", "docs": [{"ok":{"_id":"id","_rev":"2-9b2e3bcc3752a3a952a3570b2ed4d27e","_deleted":true}}]}]}
```

## Your Environment

```json
{"couchdb":"Welcome","version":"3.1.1","git_sha":"ce596c65d","uuid":"f232e7548ad3f073ffa6c1126f918b79","features":["access-ready","partitioned","pluggable-storage-engines","reshard","scheduler"],"vendor":{"name":"The Apache Software Foundation"}}
```

* CouchDB version used: 3.1.1
* Browser name and version: N/A
* Operating system and version: Linux, OS X and Windows

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by noahshaw11** [comment]
After some investigating, I believe the response currently returned by `_bulk_get` for a deleted document is correct and standard. Currently, PouchDB returns a similar response as CouchDB does. Also, specifying and not specifying the `_rev` does not change the response returned.
```
% curl -X POST http://localhost:15984/demo/_bulk_get -H"Authorization: Basic YWRtOnBhc3M=" -H"Content-Type: application/json" -d '{"docs":[{"id":"id"}]}'
{"results": [{"id": "id", "docs": [{"ok":{"_id":"id","_rev":"2-9b2e3bcc3752a3a952a3570b2ed4d27e","_deleted":true}}]}]}
% curl -X POST http://localhost:15984/demo/_bulk_get -H"Authorization: Basic YWRtOnBhc3M=" -H"Content-Type: application/json" -d '{"docs":[{"id":"id","_rev":"1-59414e77c768bc202142ac82c2f129de"}]}'
{"results": [{"id": "id", "docs": [{"ok":{"_id":"id","_rev":"2-9b2e3bcc3752a3a952a3570b2ed4d27e","_deleted":true}}]}]}
```
The current response is also related to the POST request to `_bulk_docs` to delete a doc:
```
POST /db/_bulk_docs HTTP/1.1
Accept: application/json
Content-Length: 109
Content-Type:application/json
Host: localhost:5984
{
    "docs": [
        {
            "_id": "FishStew"
        },
        {
            "_id": "LambStew",
            "_rev": "2-0786321986194c92dd3b57dfbfc741ce",
            "_deleted": true
        }
    ]
}
```
