### ISSUE TITLE
Ensure all code paths for creating databases respect db creation options

### ISSUE THREAD

**Issue by chewbranca** [apache/couchdb#3631]
When partitioned queries were introduced, new database creation options were added for the `?partitioned=true` boolean along with the hash function used, and these options are stored in the dbs db doc for the relevant database. The underlying bug here is that there are a number of different code paths that result in creation of database shards, and not all of them create the shards with the appropriate database options. We fixed a few of these issues in [1], but I've stumbled upon some more scenarios where we encounter these failures. These currently manifest on partitioned databases having shards created after initial database creation and are incorrectly created without the partitioned flag.

If individual shards of a partitioned database are incorrectly created as non-partitioned, for the most part things just "work", making this an issue that hides in plain site. One of the things that does _not_ work, is that design documents with partitioned query views have a partitioned boolean metadata value, and there's additional validation logic to prevent partitioned ddocs from being written to unpartitioned database shards. So in the event you get a shard replica incorrectly created as unpartitioned, _and_ you have a ddoc that maps to that shard, the ddoc will be unable to write to that shard replica.

In the event two of the three replicas are created correctly as partitioned, and only one of the shards is incorrectly created as unpartitioned, _and_ there's a partitioned=true ddoc on that shard range, then the ddoc will fail to write to the unpartitioned shard, which will then trigger read_repair anytime the ddoc is accessed through the quorum system, however, the read_repair logic doesn't not enforce `W=N` write semantics, so having two out of three shard replicas properly created as partitioned will result in false positive read_repair success, never triggering the failure case where we log the issue. As a result, there will be a false positive successful read_repair operation every time the ddoc is accessed.

<hr />

I've tried to be a bit more meticulous in terms of auditing this issue and trying to fix it once and for all. I _think_ there are only two ways of creating database shards: 1) Calling `couch_server:open` with the option `create_if_missing=true`, and 2) by directly calling `couch_server:create`. If anyone can think of any code paths I'm skipping, let me know.

Here's the scenarios where we set `create_if_missing`:

```
(! 22221)-> grep -r create_if_missing src/
src//mem3/src/mem3_shards.erl:                [create_if_missing(mem3:name(S), mem3:engine(S)) || S
src//mem3/src/mem3_shards.erl:create_if_missing(Name, Options) ->
src//mem3/src/mem3_util.erl:    Options = [nologifmissing, sys_db, {create_if_missing, true}, ?ADMIN_CTX],
src//mem3/src/mem3_util.erl:                Options1 = [{create_if_missing, true} | Options],
src//couch/test/eunit/couch_db_tests.erl:        {ok, Db} = couch_db:open(DbName, [{create_if_missing, true}]),
src//couch/test/eunit/couch_db_tests.erl:        {ok, Db} = couch_db:open(DbName, [{create_if_missing, true}]),
src//couch/test/eunit/couch_db_tests.erl:        {ok, Db1} = couch_db:open(DbName, [{create_if_missing, true}]),
src//couch/src/couch_server.erl:        Create = couch_util:get_value(create_if_missing, Options, false),
src//fabric/src/fabric_util.erl:    get_shard(Live, [{create_if_missing, true} | Options], 100, Factor).
```

And here's the scenarios where we call `couch_server:create` directly:

```
(! 22220)-> grep -r couch_server:create src/
src//mem3/test/eunit/mem3_seeds_test.erl:    {ok, _} = couch_server:create(<<"_users">>, []),
src//mem3/src/mem3_shards.erl:            case couch_server:create(Name, [?ADMIN_CTX] ++ Options) of
src//couch/test/eunit/couch_server_tests.erl:    Resp = couch_server:create(?tempdb(), [{engine, <<"cowabunga!">>}]),
src//couch/src/couch_httpd_db.erl:    case couch_server:create(DbName, [{user_ctx, UserCtx}] ++ Engine) of
src//couch/src/couch_server.erl:            couch_server:create(DbName, Options);
src//couch/src/couch_db.erl:    couch_server:create(DbName, Options).
src//dreyfus/src/dreyfus_rpc.erl:        couch_server:create(DbName, Options);
src//fabric/src/fabric_rpc.erl:    rexi:reply(case couch_server:create(DbName, Options) of
```

<hr />

Let's audit these to see which are problematic and need to be fixed, starting with the `create_if_missing` invocations:

> src//mem3/src/mem3_shards.erl:                [create_if_missing(mem3:name(S), mem3:engine(S)) || S
> src//mem3/src/mem3_shards.erl:create_if_missing(Name, Options) ->

These two calls [2][3] are a function in `mem3_shards` with the same name as the option we're interested in, which is why they showed up with grep, but basically the call in [2] to the function defined in [3] ends up calling `couch_server:create` so we've got an overlap between the two greps here, and we'll cover the case of [4]:

> src//mem3/src/mem3_shards.erl:            case couch_server:create(Name, [?ADMIN_CTX] ++ Options) of

here too. You'll notice that when the function in [4] calls `couch_server:create` it passes in the `Options` passed in from [2] which is just `mem:engine(S)` supplying the engine options. You'll notice nothing here checks to see if the database should be created, and therefore this is one of the problematic shard creation code paths that'll we need to fix.

<hr />

Next up is:

> src//mem3/src/mem3_util.erl:    Options = [nologifmissing, sys_db, {create_if_missing, true}, ?ADMIN_CTX]

from [5]. This line of code is from `mem3_util:ensure_exists` [6] which is only used to the creation of sys_dbs, so I _think_ we're ok to leave this as is, as we don't make partitioned system dbs.

<hr />

> src//mem3/src/mem3_util.erl:                Options1 = [{create_if_missing, true} | Options],

This is from `mem3_util:get_or_create_db` from [7], and this is the improved db creation function we updated in [1], and this properly sets the db properties by way of [8], so we're good to go here.

<hr />

The following three cases are for isolated tests:

> src//couch/test/eunit/couch_db_tests.erl:        {ok, Db} = couch_db:open(DbName, [{create_if_missing, true}]),
> src//couch/test/eunit/couch_db_tests.erl:        {ok, Db} = couch_db:open(DbName, [{create_if_missing, true}]),
> src//couch/test/eunit/couch_db_tests.erl:        {ok, Db1} = couch_db:open(DbName, [{create_if_missing, true}]),

<hr />

> src//couch/src/couch_server.erl:        Create = couch_util:get_value(create_if_missing, Options, false),

This is the core mechanism couch_server uses to determine if it should create the database when it's missing [9].

<hr />

> src//fabric/src/fabric_util.erl:    get_shard(Live, [{create_if_missing, true} | Options], 100, Factor).

This is another problematic invocation in [10], which is called as part of `fabric_util:get_db` [11]. You can clearly see in the `fabric_util:get_db/1` (arity one case) that we're supplying an empty list of options which will never have the partition options [12]. We never actually use the one arity function head, as you can see from the following grep:

```
(! 22224)-> grep -r fabric_util:get_db src/
src//fabric/src/fabric.erl:    {ok, Db} = fabric_util:get_db(dbname(DbName), [?ADMIN_CTX]),
src//fabric/src/fabric.erl:    {ok, Db} = fabric_util:get_db(dbname(DbName), [?ADMIN_CTX]),
src//fabric/src/fabric.erl:    {ok, Db} = fabric_util:get_db(dbname(DbName), opts(Options)),
```

Those three invocations come from `fabric:get_revs_limit/1` [13], `fabric:get_purge_infos_limit/1` [14], and the two arity version of `fabric:get_security/2` [15], although do note that the one arity `fabric:get_security/1` just calls the two arity with an empty options list. You can see in the following grep that we never actually supply database creation options to `fabric:get_security` and only use the options for setting a user_ctx, if at all:

```
(! 22227)-> grep -r fabric:get_security src/
src//mem3/test/eunit/mem3_reshard_test.erl:    with_proc(fun() -> fabric:get_security(DbName, [?ADMIN_CTX]) end).
src//chttpd/src/chttpd_auth_request.erl:    {_} = fabric:get_security(DbName, [{user_ctx, Ctx}]),
src//chttpd/src/chttpd_auth_request.erl:    Sec = fabric:get_security(DbName, [{user_ctx, Ctx}]),
src//chttpd/src/chttpd_external.erl:            fabric:get_security(Db);
src//chttpd/src/chttpd_db.erl:    fabric:get_security(DbName, [{user_ctx, Ctx}]),
src//chttpd/src/chttpd_db.erl:    send_json(Req, fabric:get_security(Db));
src//fabric/src/fabric_util.erl:    {SecProps} = fabric:get_security(DbName), % as admin
```

As such all three of these cases are broken, but they all use the same db creation invocation in [10], so we can fix the problem there.

<hr />

Next up are the direct invocations of `couch_server:create`:

> src//mem3/test/eunit/mem3_seeds_test.erl:    {ok, _} = couch_server:create(<<"_users">>, []),

This is an isolated test.

> src//mem3/src/mem3_shards.erl:            case couch_server:create(Name, [?ADMIN_CTX] ++ Options) of

This was covered above.

> src//couch/test/eunit/couch_server_tests.erl:    Resp = couch_server:create(?tempdb(), [{engine, <<"cowabunga!">>}]),

This is for an isolated test.

<hr />

> src//couch/src/couch_httpd_db.erl:    case couch_server:create(DbName, [{user_ctx, UserCtx}] ++ Engine) of

This interesting case comes from [16], and because it doesn't include db creation options, it means that you can't actually create partitioned dbs against the 5986 endpoint.

<hr />

> src//couch/src/couch_server.erl:            couch_server:create(DbName, Options);

This is the core couch_server logic for creating databases that have had `create_if_missing` passed through [17].

<hr />

> src//couch/src/couch_db.erl:    couch_server:create(DbName, Options).

This is an alias function `couch_db:create/2` --> `couch_server:create/2` . This opens up more code paths for invoking create without the appropriate options. For the most part, it seems this function is only used in test modules, so the following grep shows cases that don't involve the word "test":

```
(! 22233)-> grep -r couch_db:create src/ | grep -v test
src//couch/src/couch_auth_cache.erl:        {ok, Db} = couch_db:create(users_db(), Options),
src//couch_replicator/src/couch_replicator_docs.erl:    {ok, Db} = couch_db:create(DbName, [?ADMIN_CTX]),
```

The first case is for creating an internal users database, and the second case is part of the inline eunit tests of that module, so I don't think either of these scenarios or this code path are problematic at the moment.

<hr />

> src//dreyfus/src/dreyfus_rpc.erl:        couch_server:create(DbName, Options);

This is from `dreyfus_rpc:get_or_create_database` [19], which is only invoked by `{ok, Db} = get_or_create_db(DbName, []),` in [20], and you can clearly see that it's supplying an empty list for the db creation options, which is not appropriate.

On a related note, it's not in ASF CouchDB, but the Hastings [21] library uses a similar structure to Dreyfus and is susceptible to the same `get_or_create_database` code [22]. I've included it here as a reminder it needs to be fixed too.

<hr />

And for our final code path we have:

> src//fabric/src/fabric_rpc.erl:    rexi:reply(case couch_server:create(DbName, Options) of

which is in the `fabric_rpc:create_db/2` function that is only used by way of `fabric:create_db` and `fabric_db_create:go`, and this is the main code path for creating databases (partitioned or not), and I believe this is working as expected.

<hr />

## How to find problematic shards

I've created a little remsh snippet that can be invoked on any node in the cluster and it will audit all dbs and shard replicas for issues, returning the problematic shards. I think it would be worthwhile to add this to `mem3_util` or some such.

```erlang
rr(mem3_shards), f(FoldPartitionedShards), FoldPartitionedShards = fun() ->                                                                                                              Dbnames = lists:filter(fun fabric_util:is_partitioned/1, element(2, fabric:all_dbs())),                                                                                          
    Shards = lists:flatten([mem3:shards(Dbname) || Dbname <- Dbnames]),                                                                                                              
    lists:foldl(fun(Shard, Acc) ->                                                                                                                                                   
        case rpc:call(Shard#shard.node, erlang, apply, [fun() ->                                                                                                                     
                    {ok, Db} = couch_db:open_int(Shard#shard.name, []),                                                                                                              
                    couch_db:is_partitioned(Db)                                                                                                                                      
                end, []]) of                                                                                                                                                         
            true ->                                                                                                                                                                  
                Acc;                                                                                                                                                                 
            false ->                                                                                                                                                                 
                [{Shard#shard.node, Shard#shard.name} | Acc]                                                                                                                         
        end                                                                                                                                                                          
    end, [], Shards)                                                                                                                                                                 
end.                                                                                                                                                                                 
```

## Problematic shard creation code paths to fix

This leaves us with the following bugs to fix:

  * [ ] https://github.com/apache/couchdb/blob/8ac1978d78af2fc288bed1a99c092c44632ac35a/src/mem3/src/mem3_shards.erl#L361
  * [ ] https://github.com/apache/couchdb/blob/8ac1978d78af2fc288bed1a99c092c44632ac35a/src/fabric/src/fabric_util.erl#L108
  * [ ] https://github.com/apache/couchdb/blob/8ac1978d78af2fc288bed1a99c092c44632ac35a/src/couch/src/couch_httpd_db.erl#L235
  * [ ] https://github.com/apache/couchdb/blob/8ac1978d78af2fc288bed1a99c092c44632ac35a/src/dreyfus/src/dreyfus_rpc.erl#L108
  * [ ] https://github.com/cloudant-labs/hastings/blob/master/src/hastings_rpc.erl#L103-L111

[1] https://github.com/apache/couchdb/pull/2690
[2] https://github.com/apache/couchdb/blob/8ac1978d78af2fc288bed1a99c092c44632ac35a/src/mem3/src/mem3_shards.erl#L361
[3] https://github.com/apache/couchdb/blob/8ac1978d78af2fc288bed1a99c092c44632ac35a/src/mem3/src/mem3_shards.erl#L411-L423
[4] https://github.com/apache/couchdb/blob/8ac1978d78af2fc288bed1a99c092c44632ac35a/src/mem3/src/mem3_shards.erl#L416
[5] https://github.com/apache/couchdb/blob/8ac1978d78af2fc288bed1a99c092c44632ac35a/src/mem3/src/mem3_util.erl#L268
[6] https://github.com/apache/couchdb/blob/8ac1978d78af2fc288bed1a99c092c44632ac35a/src/mem3/src/mem3_util.erl#L265-L274
[7] https://github.com/apache/couchdb/blob/8ac1978d78af2fc288bed1a99c092c44632ac35a/src/mem3/src/mem3_util.erl#L511-L529
[8] https://github.com/apache/couchdb/blob/8ac1978d78af2fc288bed1a99c092c44632ac35a/src/mem3/src/mem3_util.erl#L519
[9] https://github.com/apache/couchdb/blob/8ac1978d78af2fc288bed1a99c092c44632ac35a/src/couch/src/couch_server.erl#L108
[10] https://github.com/apache/couchdb/blob/8ac1978d78af2fc288bed1a99c092c44632ac35a/src/fabric/src/fabric_util.erl#L108
[11] https://github.com/apache/couchdb/blob/8ac1978d78af2fc288bed1a99c092c44632ac35a/src/fabric/src/fabric_util.erl#L96-L132
[12] https://github.com/apache/couchdb/blob/8ac1978d78af2fc288bed1a99c092c44632ac35a/src/fabric/src/fabric_util.erl#L96-L97
[13] https://github.com/apache/couchdb/blob/8ac1978d78af2fc288bed1a99c092c44632ac35a/src/fabric/src/fabric.erl#L152
[14] https://github.com/apache/couchdb/blob/8ac1978d78af2fc288bed1a99c092c44632ac35a/src/fabric/src/fabric.erl#L173-L175
[15] https://github.com/apache/couchdb/blob/8ac1978d78af2fc288bed1a99c092c44632ac35a/src/fabric/src/fabric.erl#L177-L184
[16] https://github.com/apache/couchdb/blob/8ac1978d78af2fc288bed1a99c092c44632ac35a/src/couch/src/couch_httpd_db.erl#L235
[17] https://github.com/apache/couchdb/blob/8ac1978d78af2fc288bed1a99c092c44632ac35a/src/couch/src/couch_server.erl#L115
[18] https://github.com/apache/couchdb/blob/8ac1978d78af2fc288bed1a99c092c44632ac35a/src/couch/src/couch_db.erl#L150-L151
[19] https://github.com/apache/couchdb/blob/8ac1978d78af2fc288bed1a99c092c44632ac35a/src/dreyfus/src/dreyfus_rpc.erl#L104-L111
[20] https://github.com/apache/couchdb/blob/8ac1978d78af2fc288bed1a99c092c44632ac35a/src/dreyfus/src/dreyfus_rpc.erl#L43
[21] https://github.com/cloudant-labs/hastings
[22] https://github.com/cloudant-labs/hastings/blob/master/src/hastings_rpc.erl#L103-L111
[23] https://github.com/apache/couchdb/blob/8ac1978d78af2fc288bed1a99c092c44632ac35a/src/fabric/src/fabric_rpc.erl#L164-L173

**Comment by chewbranca** [comment]
Alright, I've opened up a CouchDB PR that fixes the `mem3_shards`, `fabric_util`, and `dreyfus_rpc` issues in https://github.com/apache/couchdb/pull/3633.

I've got a related PR for the Hastings issue in: https://github.com/cloudant-labs/hastings/pull/31.

I've left the 5986 creation of PQ shards issue as is, feedback welcome on what we should do there (if anything).

**Comment by chewbranca** [comment]
PR is out to fix the shard recreation issues in CouchDB, aside from the creation of PQ databases on 5986, here: https://github.com/apache/couchdb/pull/3633.

PR is out to fix the shard creation issues in Hastings here: https://github.com/cloudant-labs/hastings/pull/31.

**Comment by janl** [comment]
@chewbranca exceptional sleuthing, thanks for putting all this together.

**Comment by chewbranca** [comment]
I managed to come up with a sneaky test case to induce one of these failures and confirmed it fails in CI: https://github.com/apache/couchdb/pull/3633#issuecomment-867929586

**Comment by chewbranca** [comment]
Alright, I've merged https://github.com/apache/couchdb/pull/3633, closing this out.
