### ISSUE TITLE
404 at deletion of an existing attachment when using wrong rev

### ISSUE THREAD

**Issue by mojito317** [apache/couchdb#3684]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )
https://github.com/apache/couchdb/pull/3673 _created_ a bug. When we try to DELETE an existing attachment with an invalid rev we get a `404` instead `409`.

## Steps to Reproduce

* Create a document with an attachment
* Try to DELETE it with an invalid rev like `4-somegarbage`

## Expected Behaviour

The response code should be `409`, not `404` similarly to PUT.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: 3.x, after the f31e92 commit
* Browser name and version: cURL
* Operating system and version: MacOS Big Sur 11.3.1 (20E241)

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by nickva** [comment]
Thanks for the bug report @mojito317

**Comment by nickva** [comment]
These PRs should fix it https://github.com/apache/couchdb/pull/3687 https://github.com/apache/couchdb/pull/3686
