### ISSUE TITLE
Installation via apt issue: public key not available

### ISSUE THREAD

**Issue by teknari** [apache/couchdb#3709]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

I am trying to install CouchDB via APT on a new hosted Debian 10 installation.

When I run sudo apt update, I get the following error:

$ sudo apt update
Hit:1 http://mirrors.linode.com/debian buster InRelease
Hit:2 http://mirrors.linode.com/debian-security buster/updates InRelease
Hit:3 http://mirrors.linode.com/debian buster-updates InRelease
Get:4 https://apache.jfrog.io/artifactory/couchdb-deb buster InRelease [5,151 B]
Err:4 https://apache.jfrog.io/artifactory/couchdb-deb buster InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0EE62FB37A00258D
Reading package lists... Done
W: GPG error: https://apache.jfrog.io/artifactory/couchdb-deb buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0EE62FB37A00258D
E: The repository 'https://apache.jfrog.io/artifactory/couchdb-deb buster InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

## Steps to Reproduce

I run the following commands as shown on the CouchDB [Installation page](https://docs.couchdb.org/en/stable/install/unix.html) .

`sudo apt update && sudo apt install -y curl apt-transport-https gnupg`

`curl https://couchdb.apache.org/repo/keys.asc | gpg --dearmor | sudo tee /usr/share/keyrings/couchdb-archive-keyring.gpg >/dev/null 2>&1`

`source /etc/os-release`

`echo "deb [signed-by=/usr/share/keyrings/couchdb-archive-keyring.gpg] https://apache.jfrog.io/artifactory/couchdb-deb/ ${VERSION_CODENAME} main" \
    | sudo tee /etc/apt/sources.list.d/couchdb.list >/dev/null
`

## Expected Behaviour

I expect `sudo apt update` to work.

## Your Environment
I am running Debian 10 on a fresh install

**Comment by wohali** [comment]
Please try re-running `curl https://couchdb.apache.org/repo/keys.asc | gpg --dearmor | sudo tee /usr/share/keyrings/couchdb-archive-keyring.gpg` (without the `>/dev/null 2>&1`) and look for any error.

After that, try again a `apt update`.

**Comment by wohali** [comment]
I just took a brand new Debian Buster install and can confirm the instructions work, from scratch. There must be something wrong with your install.

Converting to a peer-support topic as the installation system does seem to work correctly.
