### ISSUE TITLE
Unexpected rewind of sequence id in `_changes`

### ISSUE THREAD

**Issue by j3k0** [apache/couchdb#3788]
## Description

CouchDB should rewrite the sequence id to prevent a rewind when:

- the node referenced by the sequence id isn't up;
- other nodes are known to contain the same shards.

In our CouchDB 3.1 cluster, this doesn't happen. Sequence id is rewound to 0 when the referenced node isn't up. As our system relies on the `_changes` stream to perform time critical operations, this prevents us from doing maintenance operations on the nodes.

## Steps to Reproduce

* The cluster contains 3 nodes (`couchdb3-3`, `couchdb3-4`, `couchdb3-5`).
* The database has `q=3, n=3`.

Here's a sequence id, which references the `couchdb3-3` node, decoded:
```erl
Decode("g1AAAADSeJzLYWBgYM5gTmHQTM4vTc5ISXKA0sa6xnoFRZlliSWpeimpFalVemn5ZamJesnJOUAtTHksDKuAAEj9B4KsJOYJ60vIMCYpFAiAhqwEmgUypC6SDEMSGUDGhID01_ZlAQCmtEgi").
[{'couchdb@couchdb3-3.private.dexez.fovea.cc',[2863311530, 4294967295], 59813748},
 {'couchdb@couchdb3-3.private.dexez.fovea.cc',[1431655765, 2863311529], 59801177},
 {'couchdb@couchdb3-3.private.dexez.fovea.cc',[0,1431655764], 59800974}]
```

When I ask for the next change since this sequence number:
```
curl 'http://couchdb3-5:5984/XXX/_changes?limit=1&since=g1AAAADSeJzLYWBgYM5gTmHQTM4vTc5ISXKA0sa6xnoFRZlliSWpeimpFalVemn5ZamJesnJOUAtTHksDKuAAEj9B4KsJOYJ60vIMCYpFAiAhqwEmgUypC6SDEMSGUDGhID01_ZlAQCmtEgi'
```

I get a response with sequence number `"179415900-..."`, decoded below:
```erl
[{'couchdb@couchdb3-3.private.dexez.fovea.cc',[0,1431655764], {59800975,<<"700a83e">>, 'couchdb@couchdb3-3.private.dexez.fovea.cc'}},
 {'couchdb@couchdb3-3.private.dexez.fovea.cc',[1431655765, 2863311529], 59801177},
 {'couchdb@couchdb3-3.private.dexez.fovea.cc',[2863311530, 4294967295], 59813748}]
```
As expected: a subsequent change.

However, if I stop the `couchdb3-3` node and perform the same request to `_changes` , I now get a different sequence number, fully rewound. After the same curl request to `_changes`, here's the decoded sequence id from the reply.
```erl
[{'couchdb@couchdb3-5.private.dexez.fovea.cc',[0,1431655764], 0},
 {'couchdb@couchdb3-5.private.dexez.fovea.cc',[1431655765, 2863311529], {2,<<"5d30401">>, 'couchdb@couchdb3-2.private.dexez.fovea.cc'}},
 {'couchdb@couchdb3-5.private.dexez.fovea.cc',[2863311530, 4294967295], 0}]
```
It references the first change in the DB (number 2, somehow).

* There's are internal replication jobs running.
* Cluster looks fine, as we ensured here: https://couchdb.slack.com/archives/C49LEE7NW/p1633934452482700

## Expected Behaviour

The sequence id should not get rewound but rewritten to another cluster node.

## Your Environment

```json
{
  "couchdb": "Welcome",
  "version": "3.1.1",
  "git_sha": "ce596c65d",
  "uuid": "206f795daa7e4c1695ab2504669c587e",
  "features": [
    "access-ready",
    "partitioned",
    "pluggable-storage-engines",
    "reshard",
    "scheduler"
  ],
  "vendor": {
    "name": "The Apache Software Foundation"
  }
}
```

---

**_local_docs** 

https://gist.github.com/j3k0/aee25e538c644272b1fe24cd8b119e09

---

**/_node/couchdb@couchdb3-3.private.dexez.fovea.cc/shards%2F55555555-aaaaaaa9%2Freeceipt-prod-events.1586635709**
```json
{
  "db_name": "shards/55555555-aaaaaaa9/reeceipt-prod-events.1586635709",
  "engine": "couch_bt_engine",
  "doc_count": 60554140,
  "doc_del_count": 13,
  "update_seq": 60554155,
  "purge_seq": 0,
  "compact_running": false,
  "sizes": {
    "active": 413785880486,
    "external": 710195001063,
    "file": 481634439442
  },
  "instance_start_time": "1634141284695562",
  "disk_format_version": 8,
  "committed_update_seq": 60554155,
  "compacted_seq": 54228925,
  "props": {},
  "uuid": "1273b6e4e311cfa447781c1c3bf754d1"
}
```

**/_node/couchdb@couchdb3-4.private.dexez.fovea.cc/shards%2F55555555-aaaaaaa9%2Freeceipt-prod-events.1586635709**
```json
{
  "db_name": "shards/55555555-aaaaaaa9/reeceipt-prod-events.1586635709",
  "engine": "couch_bt_engine",
  "doc_count": 60554140,
  "doc_del_count": 13,
  "update_seq": 60554155,
  "purge_seq": 0,
  "compact_running": false,
  "sizes": {
    "active": 413565673438,
    "external": 710195001063,
    "file": 429487776068
  },
  "instance_start_time": "1633872286555424",
  "disk_format_version": 8,
  "committed_update_seq": 60554155,
  "compacted_seq": 59018957,
  "props": {},
  "uuid": "9ebc87480a381e1a9e11411aee20a129"
}
```

**/_node/couchdb@couchdb3-4.private.dexez.fovea.cc/shards%2F55555555-aaaaaaa9%2Freeceipt-prod-events.1586635709**
```json
{
  "db_name": "shards/55555555-aaaaaaa9/reeceipt-prod-events.1586635709",
  "engine": "couch_bt_engine",
  "doc_count": 60554140,
  "doc_del_count": 13,
  "update_seq": 60554155,
  "purge_seq": 0,
  "compact_running": false,
  "sizes": {
    "active": 413579466049,
    "external": 710195001063,
    "file": 431963197764
  },
  "instance_start_time": "1633935343033088",
  "disk_format_version": 8,
  "committed_update_seq": 60554155,
  "compacted_seq": 58873782,
  "props": {},
  "uuid": "5d30401008b13d8622f804cdf2fe36c6"
}
```

---

**update_seq** for all shards in all nodes:

```
for shard in 00000000-55555554 55555555-aaaaaaa9 aaaaaaaa-ffffffff; do echo "===== $shard ====="; for i in 3 4 5; do /usr/bin/curl -s "$COUCH_URL/_node/couchdb@couchdb3-$i.private.dexez.fovea.cc/shards%2F$shard%2Freeceipt-prod-events.1586635709" | jq .update_seq; done; done
===== 00000000-55555554 =====
60551929
60551929
60551929
===== 55555555-aaaaaaa9 =====
60554673
60554673
60554673
===== aaaaaaaa-ffffffff =====
60565039
60565039
60565039
```

---

**_membership**

<img width="477" alt="Screen Shot 2021-10-11 at 11 22 23" src="https://user-images.githubusercontent.com/191881/137443221-c0983fa0-a9d1-46f3-939b-27fa2ded2ab8.png">

We verified that those domain names are resolving to the right IP addresses on all 3 nodes.

---

CouchDB 3.1.1 running on Ubuntu bionic using the provided `.deb`

```
deb https://apache.bintray.com/couchdb-deb bionic main
```

## Additional Context

Initial discussion on Slack:

 * https://couchdb.slack.com/archives/C49LEE7NW/p1633934452482700
 * https://couchdb.slack.com/archives/C49LEE7NW/p1634122431095600

**Comment by nickva** [comment]
This may be related to another issue created today https://github.com/apache/couchdb/issues/3787

Noticed that the some of the decoded changes sequence shards lack the node uuids. That's the `700a83e` bit from the `{59800975,<<"700a83e">>, 'couchdb@...}` tuple. That uuid is used for checking internal replication checkpoints [1] or avoid rewinds when shards are moved between nodes. Yours is the first case where a node is replaced with another node, and the 3787 was generated from the rewinds observed after moving shards to new nodes.

[1] https://github.com/apache/couchdb/blob/3.x/src/fabric/src/fabric_rpc.erl#L631-L638

**Comment by j3k0** [comment]
Would it be possible to generate a sequence id manually that includes the node's `uuid`? I can confirm if this would solve the issue.

**Comment by kocolosk** [comment]
I have a hypothesis on this one. @j3k0 your observation that the rewind does not happen with a node in maintenance mode is key.

When a node is in maintenance mode we still submit a request to that node, and then we catch the `maintenance_mode` error message and replace the worker with another one that is responsible for the same shard range. When that replacement happens we minimize rewinds correctly through analyzing internal replication checkpoints. In contrast, if the node has disconnected from the cluster entirely, we don't initiate a worker at all, but instead proactively replace it. That replacement looks like it is [starting from zero](https://github.com/apache/couchdb/blob/3.1.1/src/fabric/src/fabric_view_changes.erl#L146-L150). The probable fix there is to invoke `make_replacement_arg` to inject a `{replace, EpochNode, Uuid, Seq}` tuple for the typical case when we have that information.

**Comment by nickva** [comment]
Agree with @kocolosk's finding! That explains the rewind in this case. We'd have to couple that with the fix to always include the uuids in the generated sequences as outline in https://github.com/apache/couchdb/issues/3787
