### ISSUE TITLE
Jenkins PR and full CI check doesn't run erlfmt format check properly

### ISSUE THREAD

**Issue by nickva** [apache/couchdb#3871]
Noticed that after some recent changes erlfmt-check was failing but the PRs were merged successfully.

This is because we run erlfmt-check during the dist tarball [build](https://github.com/apache/couchdb/blob/728f3b936b2eb7f9572ebf90d6887a3c2849f571/build-aux/Jenkinsfile.pr#L53) stage and that runs on Erlang 20 (the [lowest version](https://github.com/apache/couchdb/blob/728f3b936b2eb7f9572ebf90d6887a3c2849f571/build-aux/Jenkinsfile.pr#L53)). Since erlfmt is  not compatible with Erlang 20 we skip it that check. 🤦

**Comment by lostnet** [comment]
I'd also noticed that configure.ps1 has an equivalent of install_local_rebar but not install_local_erlfmt but this might not have been noticed when following glazier instructions since they use Erlang 20.

**Comment by nickva** [comment]
@lostnet thanks for noticing.

I debated just copy pasting from `rebar` and modifying it to install `rebar3` and `erlfmt`, but since I don't have a working windows dev setup to verify it, and don't know ps1, I opted to create a separate enhancement issue for it: https://github.com/apache/couchdb/issues/3873 for the time being. https://github.com/apache/couchdb/issues/3873

**Comment by nickva** [comment]
The fix to make sure we run erlfmt https://github.com/apache/couchdb/pull/3872

**Comment by nickva** [comment]
The fix for the 3.x CI erlfmt was merged. Closing the issue. Made a separate issue about erlfmt in windows
