### ISSUE TITLE
Couchdb does not save configuration

### ISSUE THREAD

**Issue by rreyesg28** [apache/couchdb#3904]
I have couchdb installed on an eks cluster, I have a problem every time the POD is restarted or deleted, the configuration is lost.
So far I haven't found any solution that saves the configuration even when the cluster is restarted.
The only thing that comes close to a solution is to add referenced fields to the configuration, however this option does not allow adding all the fields of the configuration.
[https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-configure-couchdb-cluster](url)

**Comment by kocolosk** [comment]
Are you referring to server config settings, the kind that you see in the `_config` interface? The key to making those persistent is to map `/opt/couchdb/etc/local.d` in each pod to a persistent volume. We noted this as an enhancement in apache/couchdb-helm#7 quite a while back but never introduced the config setting to make it possible. If that's in fact what you're looking for, can you chime in over there with some detail? If not, feel free to reopen this one to clarify.
