### ISSUE TITLE
badarg error in couch_util:reorder_results from fabric doc_update

### ISSUE THREAD

**Issue by nickva** [apache/couchdb#3948]
Noticed this error pop up when inserting large _bulk_docs batches

```
req_err(2308979097) unknown_error : badarg#012 [
 <<"dict:fetch/2 L131">>,
 <<"couch_util:-reorder_results/2-lc$^1/1-1-/2 L507">>,
 <<"couch_util:-reorder_results/2-lc$^1/1-1-/2 L507">>,
 <<"fabric_doc_update:go/3 L42">>, 
 <<"fabric:update_docs/3 L299">>,
 <<"chttpd_db:db_req/2 L553">>, 
 <<"chttpd:handle_req_after_auth/2 L327">>,
 <<"chttpd:process_request/1 L310">>
]
```

This error happened when the number of replies doesn't match the number of responses when we call `couch_util:reorder_results/2`.

https://github.com/apache/couchdb/blob/e4b8a4624fc7ae09b4649aac9a8d68226208cd8b/src/fabric/src/fabric_doc_update.erl#L45

In my test I was inserting 100+ design documents in a rapid succession. They had VDUs and map views. Eventually it got to a point where there were timeouts allocating and calling `couchjs` processes. Those manifested as above `badarg` exception and `500`.

Adding log statements, noticed two separate cases
   1) None of the responses returned and `Health = ok` and `Results = []`
   2) Some returned with `Health = accepted`, `length(AllDocs) = 101` and `length(Results) = 50`
Both cases result in a `badarg`.

https://github.com/apache/couchdb/blob/e4b8a4624fc7ae09b4649aac9a8d68226208cd8b/src/couch/src/couch_util.erl#L529-L531

Here we look at the size of input docs, and if that's `>100`, we use a dictionary. If the dict key is missing it blows up with a `badarg`. That behavior is different than when there are `< 100` docs since `couch_util:get_value/2` returns `undefined`. I suspect then end up with a `201` HTTP response and each of the missing doc would have "error" : "undefined"? But I haven't checked that far.

**Comment by tonysun83** [comment]
@nickva A trivial approach which you probably considered is to mask the `dict:fetch` by catching the badargs and storing `undefined` for the > 100 case. Assuming that the < 100 case simply has "error" : "undefined" as part of it's 201 response, then this trivial change would align with it. 

We know generally why `Results` is not fully populated (as you mentioned). More importantly, I don't think it's possible to write the code in such a way where we can guarantee len(AllDocs) == len(Results). Any solution would probably entail populating the missing result with place holder such as `undefined`. What do you think?

**Comment by tonysun83** [comment]
@nickva I will investigate further. It's another one of those "it's been like this for a while, but how should it really behave" situations. And also, "if we change it drastically, will it break existing behavior."

**Comment by nickva** [comment]
I used this script to insert a bunch of ddocs with VDUs at the same time: https://gist.github.com/nickva/bde7d3cfa8c9df0dd18700c661fec4ab

The VDU isn't as critical and it looks like I didn't even trigger the `throw{forbidden:..})` as things were failing before then.

**Comment by nickva** [comment]
This was fixed. Thanks @tonysun83 !
