### ISSUE TITLE
Zombie continuous replication jobs 

### ISSUE THREAD

**Issue by tan-tony** [apache/couchdb#3988]
## Description
I have found a problem in our Couch cluster that some of the continuous replication jobs are still running (showing under _active_tasks); however, the corresponding replication doc is no longer in _replicator. 
These continuous replications were setup between 2 clusters, cluster xxx with 4 nodes and yyy with 2 nodes. 
Currently I could not find a way to stop these tasks, and they are still around after Couch service restarts. 

See example below. 
  ```
{
    "node": "couchdb@db02.xxx",
    "pid": "<0.9876.2>",
    "changes_pending": null,
    "checkpoint_interval": 30000,
    "checkpointed_source_seq": "152-g1AAAABleJzLYWBgYMxgTmGQSc4vTc5ISXJISTIw1EvOyDTUK8uvKEkt0stLLckBqmJKZMhjYfgPBFkZzIkzcoFC7JYGyYmGlmkEdGcBAAObH_k",
    "continuous": true,
    "database": "_replicator",
    "doc_id": "72ad82ac143cbef8896eef52bc08e5f0",
    "doc_write_failures": 0,
    "docs_read": 0,
    "docs_written": 0,
    "missing_revisions_found": 0,
    "replication_id": "daeb17fcc93c7a3839a541a495739667+continuous+create_target",
    "revisions_checked": 0,
    "source": "http://db01.yyy/abc/",
    "source_seq": 0,
    "started_on": 1649145165,
    "target": "http://db01.xxx:5984/abc/",
    "through_seq": "152-g1AAAABleJzLYWBgYMxgTmGQSc4vTc5ISXJISTIw1EvOyDTUK8uvKEkt0stLLckBqmJKZMhjYfgPBFkZzIkzcoFC7JYGyYmGlmkEdGcBAAObH_k",
    "type": "replication",
    "updated_on": 1649284218,
    "user": null
  }
```
```
$ curl 'http://db02.xxx:5984/_replicator/72ad82ac143cbef8896eef52bc08e5f0' | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    41  100    41    0     0    200      0 --:--:-- --:--:-- --:--:--   200
{
  "error": "not_found",
  "reason": "missing"
}

```

## Steps to Reproduce
Unknown.

## Expected Behaviour
_active_tasks should match what's in _replicator. 

## Your Environment
Couch 2.3.1 running in Centos7 VM.
{
  "couchdb": "Welcome",
  "version": "2.3.1",
  "git_sha": "c298091a4",
  "uuid": "79089b52d0bdf39de414eae795f3e646",
  "features": [
    "pluggable-storage-engines",
    "scheduler"
  ],
  "vendor": {
    "name": "The Apache Software Foundation"
  }
}

**Comment by nickva** [comment]
@tan-tony I remember 2.3.1 having a few bugs like that. Unfortunately we don't support 2.x any longer. See if you can reproduce the issue with a recent 3.x release perhaps

**Comment by tan-tony** [comment]
Hi @nickva we are not ready to move on to 3.x yet, due to API changes. 
Do you recall any methods that could stop these replications in the meantime?

**Comment by nickva** [comment]
@tan-tony a quick server restart would clear them out. 

I don't recall if we had a remsh (erlang shell) set up in 2.3.1 but if there is one you could also connect to  "couchdb@db02.xxx" then use the `exit(<0.9876.2>, kill)` to kill that process directly.

Another thing to try is to delete it via the POST to _replicate https://docs.couchdb.org/en/stable/api/server/common.html#replicate using the replication_id `cancel: true`. That might not work though but it's worth trying.

**Comment by tan-tony** [comment]
@nickva  We have tried roling restart nodes before and didnt seem to help, does every node have to be stopped first and then start back up?
Yeah, also tried `cancel: true` before and didn't work.

**Comment by nickva** [comment]
The `{"node": "couchdb@db02.xxx", "pid": "<0.9876.2>"}` part indicates it is running on `db02.xxx` and has a process ID `<0.9876.2>` after restart if you still see that job means the restart didn't happen properly, or the document may still be in the `_replicator` database. Perhaps the document was deleted but there is a conflict and the replication manager sees the deleted document.  Try fetching the document with `?deleted=true`. 

There could be DNS mixup and you might be reaching a different node than the indented one...?

**Comment by tan-tony** [comment]
DNS should be ok, our cluster is functioning everyday for production. 
I tried deleted flag just now and still the same case.
Killing the process probably will work, but I'm afraid it might come back again after a restart.
```
$ curl 'http://db02.xxx:5984/_replicator/72ad82ac143cbef8896eef52bc08e5f0?deleted=true' | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    41  100    41    0     0    211      0 --:--:-- --:--:-- --:--:--   211
{
  "error": "not_found",
  "reason": "missing"
}

```

**Comment by tan-tony** [comment]
@nickva Decided to clean up all these and deleted the whole _replicator database today then restarted couch. These tasks are still running somehow.

**Comment by nickva** [comment]
@tan-tony are there any other _replicator databases?. Perhaps the cluster is partitioned? The replication job has to be started somewhere if you restart all the nodes and it's still running, something is still creating it.

**Comment by tan-tony** [comment]
@nickva  I couldn't find any other _replicator db, searched through _all_dbs. The cluster is running with q=1.

**Comment by nickva** [comment]
@tan-tony another option could be that the `_replicator` was created as a node-local (non-clustered) db.

See if you look in `curl .../_node/_local/_all_dbs` or, if 2.3.1 doesn't have the `_node/_local` API, check the local port 5986 (by default) `curl http://localhost:5986` and see if `_replicator` shows up there.
