### ISSUE TITLE
3.2.2 tag is unavailable

### ISSUE THREAD

**Issue by ArchangeGabriel** [apache/couchdb#4002]
3.2.2 was released on April 19th, but… https://github.com/apache/couchdb/releases/tag/3.2.2 is 404.

**Comment by big-r81** [comment]
It is provided when we release infos about the fixed CVE. It should be available next week.

**Comment by ArchangeGabriel** [comment]
OK, I see, thanks. I was looking for the commit that made https://github.com/apache/couchdb/issues/999#issuecomment-382410495= the default, but could not use the diff between tags feature to find it.
