### ISSUE TITLE
Prevent "403 Forbidden" with JWT auth

### ISSUE THREAD

**Issue by gbshhennsi** [apache/couchdb#4010]
### Discussed in https://github.com/apache/couchdb/discussions/4009

<div type='discussions-op-text'>

<sup>Originally posted by **gbshhennsi** April 29, 2022</sup>
Hello !

I am trying to secure my couchdb with a JWT Token. I succefully accessed the Database with the Token and it responds with:

`{
    "couchdb": "Welcome",
    "version": "3.2.1",
    "git_sha": "244d428af",
    "uuid": "7ce2e0a56139046ee7405702e5c7eb42",
    "features": [
        "access-ready",
        "partitioned",
        "pluggable-storage-engines",
        "reshard",
        "scheduler"
    ],
    "vendor": {
        "name": "The Apache Software Foundation"
    }
}`

The Problem is when I want to access a specific Database I am recieving 

`{
    "error": "forbidden",
    "reason": "You are not allowed to access this db."
}`.

The problem is I want to get docs from my Database without user-password authentication.
My docker.ini files auth section looks like this

![image](https://user-images.githubusercontent.com/53291773/165939466-89fe6800-25b5-461c-9fc9-a69a09878f9b.png)

Is the JWT authentication missing the feature of accessing databases without basic auth or am I doing something wrong?
Thanks in advance!

</div>

**Comment by big-r81** [comment]
Please dont open topics as issue and discussion. Closing this for now. Continue in #4009
