### ISSUE TITLE
Cluster setup unable to sync admin passwords

### ISSUE THREAD

**Issue by camo-f** [apache/couchdb#4022]
Hi,

## Description
I'm starting three identical CouchDB databases as Docker containers, without data. Same username/admin, same Erlang cookie, same secret. Only the hostname changes.
I followed cluster setup instructions. Membership seems fine :
```
{
  "all_nodes": [
    "couchdb@staging_couchdb-1.lan",
    "couchdb@staging_couchdb-2.lan",
    "couchdb@staging_couchdb-3.lan"
  ],
  "cluster_nodes": [
    "couchdb@staging_couchdb-1.lan",
    "couchdb@staging_couchdb-2.lan",
    "couchdb@staging_couchdb-3.lan"
  ]
}
```
I can't finish the setup tough :
```bash
curl -X POST -H "Content-Type: application/json" "http://couchdb:password@127.0.0.1:5984/_cluster_setup" -d '{"action": "finish_cluster"}'
```
Returns
```
{"error":"setup_error","reason":"Cluster setup unable to sync admin passwords"}
```

In the coordinator node logs :
```
[notice] da15887192 Setup: [{<<"action">>,<<"finish_cluster">>}]
[notice] da15887192 finish_cluster: [{<<"action">>,<<"finish_cluster">>}]
[error] da15887192 setup sync_admin results [{error,erofs},{error,erofs}] errors []
[notice] da15887192 127.0.0.1:5984 127.0.0.1 couchdb POST /_cluster_setup 500 ok 6
```
In the joining nodes logs :
```
[notice] -------- config: [admins] couchdb set to '****' for reason nil
```
I also removed joining nodes and re-added them, but I got the same result.

## Steps to Reproduce
See above

## Expected Behaviour

Expecting the cluster setup to finish

## Your Environment

* CouchDB version used: 3.2.2 Docker image

```
{
  "couchdb": "Welcome",
  "version": "3.2.2",
  "git_sha": "d5b746b7c",
  "uuid": "f46682509877e4e6e44e7d5ab04ae518",
  "features": [
    "access-ready",
    "partitioned",
    "pluggable-storage-engines",
    "reshard",
    "scheduler"
  ],
  "vendor": {
    "name": "The Apache Software Foundation"
  }
}
```

## Additional Context

Looks similar to issue #3805, though I'm using CouchDB 3.2.2

Also, I have a working cluster with the same environment, but started in 3.1.1 and upgraded to 3.2.2.

**Comment by big-r81** [comment]
Hi,

`{error,erofs}` means a read-only filesystem. Do you have write access?

**Comment by big-r81** [comment]
Getting no response, closing now.
