### ISSUE TITLE
SpiderMonkey Detection on Fedora 36

### ISSUE THREAD

**Issue by jo** [apache/couchdb#4057]
## Description
When building CouchDB on Fedora 36, SpiderMonkey is wrongly identiefied as `1.8.5` (presumably the default?), although SpiderMonkey is installed in version `91`.

## Steps to Reproduce
Spin up a Fedora 36 docker:

```sh
docker run -it fedora:36 /bin/bash
```
You'll be thrown inside the docker container. Run
```sh
dnf install git autoconf autoconf-archive automake curl-devel erlang-asn1 erlang-erts erlang-eunit gcc-c++ erlang-os_mon erlang-xmerl erlang-erl_interface help2man libicu-devel libtool perl-Test-Harness mozjs91-devel erlang-reltool erlang-rebar
cd
git clone https://github.com/apache/couchdb.git
cd couchdb
git checkout 3.2.2
./configure
```

Now inspect the contents of `config.erl`, which looks like this:
```erl
{with_proper, true}.
{erlang_md5, false}.
{spidermonkey_version, "1.8.5"}.
```

After manually fixing the version (`sed -i -e 's/1.8.5/91/' config.erl`), compilation works.

## Expected Behaviour
Present SpiderMonkey version should be detected, and written to `config.erl` like this:

```erl
{with_proper, true}.
{erlang_md5, false}.
{spidermonkey_version, "91"}.
```

## Your Environment

* CouchDB version used: git tag 3.2.2
* Operating system and version: Fedora 36

**Comment by big-r81** [comment]
Hi,

does this happen with the "main" branch too?

**Comment by big-r81** [comment]
Sorry, no iirc it's the default, there is no auto detection of sm.
But I think I saw a PR/Issue for that, need to search...

**Comment by big-r81** [comment]
```
./configure --help
...
--spidermonkey-version VSN  specify the version of SpiderMonkey to use (defaults to 1.8.5)
...
```

You need to do something like that:


```./configure --spidermonkey-version 91```

**Comment by jo** [comment]
even better :) thanks!
