### ISSUE TITLE
Please add 32 bit version of conch dB

### ISSUE THREAD

**Issue by ZS-cop** [apache/couchdb#4058]
NOTE: I can't able to use conch dB because I am having 32bit system(windows 10)

I am Devyansh Narayan from GitHub and please solve this problem

Please Ans in English

The key words "MUST"

**Comment by big-r81** [comment]
Hi,

we will not provide an 32 bit executable for windows. As of CouchDB 2.0 we only support a 64-bit build of CouchDB.
