### ISSUE TITLE
Support for OpenSSL3 to allow installation in Ubuntu 22.04

### ISSUE THREAD

**Issue by Kaspanoombro** [apache/couchdb#4067]
## Summary

Cannot install the couchdb in Ubuntu 22.04. I suspect that is because of openssl 3 being the default now,

## Desired Behaviour

Install and run immediately in http://127.0.0.1:5984

**Comment by Kaspanoombro** [comment]
Jun 17 13:21:58 XXXX snapd[820]: api_snaps.go:317: Installing snap "couchdb" revision unset
Jun 17 13:23:31 XXXX systemd[1]: Mounting Mount unit for couchdb, revision 9...
Jun 17 13:23:31 XXXX systemd[1]: Mounted Mount unit for couchdb, revision 9.
Jun 17 13:23:32 XXXX systemd[1]: Started snap.couchdb.hook.install.921cbf6c-db43-4841-beee-7d54e34b4e6b.scope.
Jun 17 13:23:32 XXXX systemd[1]: snap.couchdb.hook.install.921cbf6c-db43-4841-beee-7d54e34b4e6b.scope: Deactivated successfully.
Jun 17 13:23:32 XXXX systemd[1]: Started Service for snap application couchdb.server.
Jun 17 13:23:32 XXXX systemd[1]: Started snap.couchdb.hook.configure.9e56ae93-8911-4cd6-83ca-22d1bc258822.scope.
Jun 17 13:23:32 XXXX systemd[1]: snap.couchdb.hook.configure.9e56ae93-8911-4cd6-83ca-22d1bc258822.scope: Deactivated successfully.
Jun 17 13:23:33 XXXX couchdb.server[123411]: [info] 2022-06-17T12:23:33.791536Z couchdb@127.0.0.1 <0.11.0> -------- Application couch_log started on node 'couchdb@127.0.0.1'
Jun 17 13:23:33 XXXX couchdb.server[123411]: [info] 2022-06-17T12:23:33.797620Z couchdb@127.0.0.1 <0.11.0> -------- Application folsom started on node 'couchdb@127.0.0.1'
Jun 17 13:23:33 XXXX couchdb.server[123411]: [info] 2022-06-17T12:23:33.833291Z couchdb@127.0.0.1 <0.11.0> -------- Application couch_stats started on node 'couchdb@127.0.0.1'
Jun 17 13:23:33 XXXX couchdb.server[123411]: [info] 2022-06-17T12:23:33.833389Z couchdb@127.0.0.1 <0.11.0> -------- Application khash started on node 'couchdb@127.0.0.1'
Jun 17 13:23:33 XXXX couchdb.server[123411]: [info] 2022-06-17T12:23:33.839117Z couchdb@127.0.0.1 <0.11.0> -------- Application couch_event started on node 'couchdb@127.0.0.1'
Jun 17 13:23:33 XXXX couchdb.server[123411]: [info] 2022-06-17T12:23:33.839231Z couchdb@127.0.0.1 <0.11.0> -------- Application hyper started on node 'couchdb@127.0.0.1'
Jun 17 13:23:33 XXXX couchdb.server[123411]: [info] 2022-06-17T12:23:33.846108Z couchdb@127.0.0.1 <0.11.0> -------- Application ibrowse started on node 'couchdb@127.0.0.1'
Jun 17 13:23:33 XXXX couchdb.server[123411]: [info] 2022-06-17T12:23:33.849388Z couchdb@127.0.0.1 <0.11.0> -------- Application ioq started on node 'couchdb@127.0.0.1'
Jun 17 13:23:33 XXXX couchdb.server[123411]: [info] 2022-06-17T12:23:33.849508Z couchdb@127.0.0.1 <0.11.0> -------- Application mochiweb started on node 'couchdb@127.0.0.1'
Jun 17 13:23:33 XXXX couchdb.server[123411]: [info] 2022-06-17T12:23:33.852945Z couchdb@127.0.0.1 <0.222.0> -------- Preflight check: Asserting Admin Account
Jun 17 13:23:33 XXXX couchdb.server[123411]: [info] 2022-06-17T12:23:33.853010Z couchdb@127.0.0.1 <0.222.0> --------
Jun 17 13:23:33 XXXX couchdb.server[123411]: %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Jun 17 13:23:33 XXXX couchdb.server[123411]:   No Admin Account Found, aborting startup.
Jun 17 13:23:33 XXXX couchdb.server[123411]:   Please configure an admin account in your local.ini file.
Jun 17 13:23:33 XXXX couchdb.server[123411]: %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Jun 17 13:23:34 XXXX systemd[1]: snap.couchdb.server.service: Main process exited, code=exited, status=1/FAILURE
Jun 17 13:23:34 XXXX systemd[1]: snap.couchdb.server.service: Failed with result 'exit-code'.
Jun 17 13:23:34 XXXX systemd[1]: snap.couchdb.server.service: Consumed 1.327s CPU time.
Jun 17 13:23:34 XXXX systemd[1]: snap.couchdb.server.service: Scheduled restart job, restart counter is at 1.
Jun 17 13:23:34 XXXX systemd[1]: Stopped Service for snap application couchdb.server.
Jun 17 13:23:34 XXXX systemd[1]: snap.couchdb.server.service: Consumed 1.327s CPU time.
Jun 17 13:23:34 XXXX systemd[1]: Started Service for snap application couchdb.server.

**Comment by big-r81** [comment]
You need to configure an [admin account](https://docs.couchdb.org/en/stable/config/auth.html#config-admins), which is clearly described in the in the logs:
```
Jun 17 13:23:33 XXXX couchdb.server[123411]: %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Jun 17 13:23:33 XXXX couchdb.server[123411]: No Admin Account Found, aborting startup.
Jun 17 13:23:33 XXXX couchdb.server[123411]: Please configure an admin account in your local.ini file.
Jun 17 13:23:33 XXXX couchdb.server[123411]: %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by Kaspanoombro** [comment]
These are my steps: go to Software app of Ubuntu and choose to install Couchdb. It installs successfully but nothing happens. I check the logs and that appears. I try to had a admin account in local.ini but i am unable (even with sudo). The files are protected (maybe because it is a snap install). So, how to proceed? Thank you.

**Comment by Kaspanoombro** [comment]
I just removed and try it using the terminal: sudo snap install couchdb. Again no problems, but it never asks for a admin password.

**Comment by big-r81** [comment]
Ok, maybe it's "used" from your previous install...

**Comment by Kaspanoombro** [comment]
I purged previous installations and this a fresh install of Ubuntu. I did try to add a password in sudo nano /var/snap/couchdb/current/etc/local.ini but again i cannot write in this file.

**Comment by big-r81** [comment]
This is an old version, and it seems the package isn't updated. I don't know about the snap release process, maybe @nickva can help?

**Comment by Kaspanoombro** [comment]
I sort it out. Just in case needs this information:
1) Follow the instructions to install the CouchDB repository:
https://docs.couchdb.org/en/stable/install/unix.html#enabling-the-apache-couchdb-package-repository

2) Edit the /etc/apt/sources.list.d/couchdb.list and change the disti from jammy to focal
deb [signed-by=/usr/share/keyrings/couchdb-archive-keyring.gpg] https://apache.jfrog.io/artifactory/couchdb-deb/ focal main

3) Install the required old packages:
wget http://archive.ubuntu.com/ubuntu/pool/main/i/icu/libicu66_66.1-2ubuntu2_amd64.deb
sudo dpkg -i libicu66_66.1-2ubuntu2_amd64.deb
wget http://cz.archive.ubuntu.com/ubuntu/pool/main/m/mozjs68/libmozjs-68-0_68.6.0-1ubuntu1_amd64.deb
sudo dpkg -i libmozjs-68-0_68.6.0-1ubuntu1_amd64.deb

4) Install couchdb using sudo apt install couchdb
