### ISSUE TITLE
Provide release for Ubuntu 22.04 "Jammy Jellyfish"

### ISSUE THREAD

**Issue by camtauxe** [apache/couchdb#4081]
The CouchDB apt repository at https://apache.jfrog.io/artifactory/couchdb-deb/ does not include a release for the latest Ubuntu LTS, 22.04 "Jammy Jellyfish"

## Description

Following the installation instructions provided in the [official docs](https://docs.couchdb.org/en/stable/install/unix.html#enabling-the-apache-couchdb-package-repository) eventually fails with the message:

```
Failed to update apt cache: E:The repository 'https://apache.jfrog.io/artifactory/couchdb-deb jammy Release' does not have a Release file.
```

## Steps to Reproduce

(Commands copy-pasted from installation instructions)

```
sudo apt update && sudo apt install -y curl apt-transport-https gnupg
curl https://couchdb.apache.org/repo/keys.asc | gpg --dearmor | sudo tee /usr/share/keyrings/couchdb-archive-keyring.gpg >/dev/null 2>&1
source /etc/os-release
echo "deb [signed-by=/usr/share/keyrings/couchdb-archive-keyring.gpg] https://apache.jfrog.io/artifactory/couchdb-deb/ ${VERSION_CODENAME} main" \
    | sudo tee /etc/apt/sources.list.d/couchdb.list >/dev/null
```

## Expected Behaviour

Adding the apt repository succeeds because there is a release for this version of Ubuntu

## Your Environment

* Operating system and version: Ubuntu 22.04

**Comment by nickva** [comment]
Good idea @camtauxe.

For now I believe it might be possible to use the focal version

**Comment by nickva** [comment]
Good idea @big-r81

**Comment by nickva** [comment]
@camtauxe @big-r81 I uploaded a jammy CI / build image then built and uploaded packages for jammy in https://github.com/apache/couchdb-pkg/pull/100

I had noticed that either libicu or mozjs78 brings a tzdata package and then it ask for an interactive timezone choice during install.

**Comment by nickva** [comment]
Closing issue. Please reopen if there are any problems with the new jammy packages
