### ISSUE TITLE
CouchDB v3.2.2 - couchjs error on creation of view (Mac osx 10.15.7 Catalina)

### ISSUE THREAD

**Issue by dcappo** [apache/couchdb#4147]
[CouchDB_fails_to_create_view.docx](https://github.com/apache/couchdb/files/9339463/CouchDB_fails_to_create_view.docx)

Same error occurs on programmatic access.

**Comment by big-r81** [comment]
Thank you for the report. Closing this because of a similiar report. See #4047.
