### ISSUE TITLE
Couchdb-photon is not working

### ISSUE THREAD

**Issue by TechRemoteSloutions** [apache/couchdb#4192]
Couchdb-photon  is not working i  am following error.

uname=zzzz; upwd=xxxxx; \
> couch="-H Content-Type:application/json -X PUT http://$uname:$upwd@127.0.0.1:5984"; \
> curl $couch/photon; curl https://raw.githubusercontent.com/ermouth/couch-photon/master/photon.json | \
> curl $couch/photon/_design/photon -d @- ; curl $couch/photon/_security -d '{}' ; \
> curl $couch/_node/_local/_config/csp/attachments_enable -d '"false"' ; \
> curl $couch/_node/_local/_config/chttpd_auth/same_site -d '"lax"' ; \
> couch=''; uname='zzzz'; upwd='xxxxx'
curl: (3) Port number ended with 'd'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2191k  100 2191k    0     0  31.4M      0 --:--:-- --:--:-- --:--:-- 31.4M
curl: (3) Port number ended with 'd'
curl: (3) Port number ended with 'd'
curl: (3) Port number ended with 'd'
curl: (3) Port number ended with 'd'

**Comment by big-r81** [comment]
Hi,

`photon` is a third-party project. Please ask [here](https://github.com/ermouth/couch-photon) for help.
