### ISSUE TITLE
The database with q = 1024

### ISSUE THREAD

**Issue by ornotnull** [apache/couchdb#4196]
Trying to create a database with q = 1024 and n = 1.
Is this supported? Any limitation for q?

<0.7629.0> cd536cbb12 req_err(1645417114) unknown_error : badarith
    [<<"math:pow/2">>,<<"fabric_util:get_db_timeout/4 L160">>,<<"fabric_util:get_db/2 L114">>,<<"fabric:get_security/2 L183">>,<<"chttpd_auth_request:db_authorization_check/1 L112">>,<<"chttpd_auth_request:authorize_request/1 L19">>,<<"chttpd:handle_req_after_auth/2 L325">>,<<"chttpd:process_request/1 L310">>]

the error is produced by line 160 of src/fabric/src/fabric_util.erl

math:pow(Factor, N + 1)

and do not see a way to avoid this

Factor is not less then 2 by 111 line
Factor = max(2, config:get_integer("fabric", "shard_timeout_factor", 2))

**Comment by nickva** [comment]
A q factor is 1024 is probably not practical. The default is 2 and I even it the larger clusters I don't recall seeing anything larger than 256.

What are you trying to do?

**Comment by ornotnull** [comment]
OK. Now just testing the database of size about 10Tb
and follow the recommendation to keep a shard within 10Gb
https://neighbourhood.ie/blog/2020/09/22/sharding-choosing-the-right-q-value/

So the test database is q = 1024 and n = 2 but now only able to go with q = 256, n = 2

**Comment by big-r81** [comment]
Hi,

what @nickva says, but I can reproduce this, See for more error messages: https://gist.github.com/big-r81/d244a22c36820c165ed63a105d6a092b

**Comment by nickva** [comment]
@ornotnull you can still go as high as 1022 or so (the highest limit is 1023 and there is a +1 so max q would be about 1022). But even with a 10TB I would stick with a smaller sharding factor.

**Comment by nickva** [comment]
@ornotnull thanks for reaching out and reporting the bug. Here is a PR that should fix it https://github.com/apache/couchdb/issues/4196

**Comment by ornotnull** [comment]
@nickva, thank you a lot 
able to compile the new 3.2.2-228b07e version and no issue any more
