### ISSUE TITLE
Proxy & JWT Authentication Guides missing

### ISSUE THREAD

**Issue by hadrysmateusz** [apache/couchdb#4228]
The [authentication section](https://docs.couchdb.org/en/latest/intro/security.html#authentication) of the security user guides only have information on basic and cookie authentication but there is nothing on proxy and jwt authentication. The only information on these authentication types can be found in the [API reference](https://docs.couchdb.org/en/latest/api/server/authn.html#authentication). And the information there (especially about jwt authentication) is (at least in my opinion) not very clear.

**Comment by big-r81** [comment]
@hadrysmateusz, @Syedpash Is this still an issue?

**Comment by nickva** [comment]
This is documented now https://docs.couchdb.org/en/stable/api/server/authn.html#jwt-authentication

Closing as completed.
