### ISSUE TITLE
_revs_limit & _purged_infos_limit are not saved

### ISSUE THREAD

**Issue by ornotnull** [apache/couchdb#4244]
how to reproduce:

1. single node
2. create the database
3. set some non-default values for _revs_limit or _purged_infos_limit
4. do _compact 
5. restart couchdb
6. check _revs_limit & _purged_infos_limit, now the default values

clustered might affected too

**Comment by nickva** [comment]
Thanks for your bug report. Is restarting, is always necessary, simply letting the compaction finish does result in the new values taking a effect?

**Comment by ornotnull** [comment]
restart performed after compaction is finished
