### ISSUE TITLE
How to hide the version of CouchDB and Erland in the response header

### ISSUE THREAD

**Issue by yzgang76** [apache/couchdb#4258]
[NOTE]: #How to hide the version of CouchDB and Erland in the response header

## Description
In the Rest API response headers, the 'Server' expose the verison of CouchDB and Erland

Server | CouchDB/3.2.2 (Erlang OTP/23)

for security reseason, is it possible to hide the Server information? 

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Steps to Reproduce
Send a Rest Request 

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour

Hide 'Server' in the response headers

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used:
* Browser name and version:
* Operating system and version:

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by big-r81** [comment]
Hi,

there is no config option to disable the server version header. If you really need to hide this, you need to comment out [these](https://github.com/apache/couchdb/blob/7f1d2b2ed63be13a7297e0d229b78e620a4204b8/src/couch/src/couch_httpd.erl#L1206-L1208) lines and compile CouchDB by yourself. The server header will then be replaced by a default one from MochiWeb.

Please keep in mind that security by obscurity alone does not create a higher level of security.
