### ISSUE TITLE
Cannot get to the COUCHDB repo on RHEL 7-8 or Rocky 8 

### ISSUE THREAD

**Issue by hostingwiz** [apache/couchdb#4282]
Hello,

I cannot update COUCHDB as I cannot get to the repo and I have tried the url from many different networks.

http://apache.bintray.com/couchdb-rpm/el7/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 502 - Bad Gateway

Any information would be greatly appreciated. 

Thanks

**Comment by nickva** [comment]
apache.bintray.com is decommissioned (all of bintray is I think).

see https://docs.couchdb.org/en/3.2.2-docs/install/unix.html#enabling-the-apache-couchdb-package-repository
