### ISSUE TITLE
unable to create new user

### ISSUE THREAD

**Issue by faisalabdulkadir** [apache/couchdb#4296]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description: Each time I try to create a new user using the fauxton UI I keep getting the error undefined. As it is now I can only use my admin login credentials which I specified during the initial setup of the app

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Steps to Reproduce
I ran the command curl -X PUT http://admin:xxxxx@localhost:5984/_users/org.couchdb.user:jan \
     -H "Accept: application/json" \
     -H "Content-Type: application/json" \
     -d '{"name": "jan", "password": "apple", "roles": [], "type": "user"}'

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour
I expect the user to be created 

[NOTE]: # ( Tell us what you expected to happen. )

I get the error {"error":"unknown_error","reason":"undefined"}

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: v. 3.2.2
* Browser name and version: chrome
* Operating system and version: macOS Catalina version 10.15.7

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by benel** [comment]
Just to help you describe the problem:

- Is this with the UI or with `curl`? or both?
- Did you create the `_users` database first?

**Comment by faisalabdulkadir** [comment]
- I can't create a user with both UI and curl
   - Yes. I created the _users database first

**Comment by benel** [comment]
And did you verify your installation with <http://localhost:5984/_utils/#/verifyinstall>?

**Comment by benel** [comment]
> everything seems checked except two

Then your installation is broken.
It's out of my skills but I'm sure you will find people here to help you with that.

**Comment by faisalabdulkadir** [comment]
Okay.. Thank you so much for the help

**Comment by big-r81** [comment]
On which OS is CouchDB running?

**Comment by faisalabdulkadir** [comment]
It's running on macOS

**Comment by big-r81** [comment]
What version of macOS and is there anything in your logs?

**Comment by faisalabdulkadir** [comment]
I am using macOS Catalina version 10.15.7. I've even tried installing "brew
install nspr" as seen in the docs which was referring to something like a
missing dependency with mac but that still didn't solve the issue. below is
my last few logs


[info] 2022-12-08T15:53:05.419616Z ***@***.*** <0.277.0> --------
couch_proc_manager <0.3206.1> died epipe
[error] 2022-12-08T15:53:05.473739Z ***@***.*** <0.3209.1> --------
OS Process died with status: 134
[error] 2022-12-08T15:53:05.479716Z ***@***.*** <0.3209.1> --------
gen_server <0.3209.1> terminated with reason: {exit_status,134}
  last msg: redacted
     state: {os_proc,"./bin/couchjs
./share/server/main.js",#Port<0.21333>,fun couch_os_process:writejson/2,fun
couch_os_process:readjson/1,5000,300000}
    extra: []
[error] 2022-12-08T15:53:05.479934Z ***@***.*** <0.3209.1> --------
gen_server <0.3209.1> terminated with reason: {exit_status,134}
  last msg: redacted
     state: {os_proc,"./bin/couchjs
./share/server/main.js",#Port<0.21333>,fun couch_os_process:writejson/2,fun
couch_os_process:readjson/1,5000,300000}
    extra: []
[error] 2022-12-08T15:53:05.480553Z ***@***.*** <0.3209.1> --------
CRASH REPORT Process  (<0.3209.1>) with 0 neighbors exited with reason:
{exit_status,134} at gen_server:handle_common_reply/8(line:805) <=
proc_lib:init_p_do_apply/3(line:226); initial_call:
{couch_os_process,init,['Argument__1']}, ancestors: [<0.3208.1>],
message_queue_len: 0, links: [], dictionary: [], trap_exit: false, status:
running, heap_size: 2586, stack_size: 28, reductions: 1564
[error] 2022-12-08T15:53:05.480865Z ***@***.*** <0.3209.1> --------
CRASH REPORT Process  (<0.3209.1>) with 0 neighbors exited with reason:
{exit_status,134} at gen_server:handle_common_reply/8(line:805) <=
proc_lib:init_p_do_apply/3(line:226); initial_call:
{couch_os_process,init,['Argument__1']}, ancestors: [<0.3208.1>],

**Comment by big-r81** [comment]
Can you do the following steps?

1. Stop CouchDB
2. Clear/truncate log file
3. Start CouchDB
4. Run your user creation command from above
6. Stop CouchDB
7. Upload your log file

Afterwards, open a terminal and cd into your CouchDB directory and run the following command:

`./bin/couchjs -V`

and paste the output.

**Comment by faisalabdulkadir** [comment]
after following the steps above and running the command again.... I get
the following log messages:

[info] 2022-12-08T18:13:08.432370Z ***@***.*** <0.254.0> --------
Preflight check: Checking For Monsters

[info] 2022-12-08T18:13:08.432449Z ***@***.*** <0.254.0> --------
Preflight check: Asserting Admin Account

[info] 2022-12-08T18:13:08.436471Z ***@***.*** <0.254.0> --------
Apache CouchDB 3.2.2 is starting.

[info] 2022-12-08T18:13:08.436569Z ***@***.*** <0.255.0> --------
Starting couch_sup
[info] 2022-12-08T18:13:08.592748Z ***@***.*** <0.254.0> --------
Apache CouchDB has started. Time to relax.

[notice] 2022-12-08T18:13:08.606814Z ***@***.*** <0.296.0> --------
rexi_server : started servers
[notice] 2022-12-08T18:13:08.608976Z ***@***.*** <0.300.0> --------
rexi_buffer : started servers
[notice] 2022-12-08T18:13:08.698008Z ***@***.*** <0.330.0> --------
mem3_reshard_dbdoc start init()
[notice] 2022-12-08T18:13:08.702758Z ***@***.*** <0.332.0> --------
mem3_reshard start init()
[notice] 2022-12-08T18:13:08.702946Z ***@***.*** <0.333.0> --------
mem3_reshard db monitor <0.333.0> starting
[notice] 2022-12-08T18:13:08.705514Z ***@***.*** <0.332.0> --------
mem3_reshard starting reloading jobs
[notice] 2022-12-08T18:13:08.705756Z ***@***.*** <0.332.0> --------
mem3_reshard finished reloading jobs
[info] 2022-12-08T18:13:08.734696Z ***@***.*** <0.339.0> --------
Apache CouchDB has started. Time to relax.

[info] 2022-12-08T18:13:08.734794Z ***@***.*** <0.339.0> --------
Apache CouchDB has started on http://127.0.0.1:5984/
[notice] 2022-12-08T18:13:08.832255Z ***@***.*** <0.427.0> --------
All system databases exist.
[notice] 2022-12-08T18:13:09.633770Z ***@***.*** <0.344.0> 23215c095a
127.0.0.1:5984 127.0.0.1 undefined GET /_up 200 ok 37
[notice] 2022-12-08T18:13:09.777170Z ***@***.*** <0.345.0> 1314f323bb
127.0.0.1:5984 127.0.0.1 undefined GET /_utils/ 304 ok 1
[notice] 2022-12-08T18:13:09.865079Z ***@***.*** <0.345.0> cdd9c33d67
127.0.0.1:5984 127.0.0.1 undefined GET
/_utils/dashboard.assets/css/styles.1dd5f02ec0ce91979b00.css 304 ok 12
[notice] 2022-12-08T18:13:09.867120Z ***@***.*** <0.348.0> af28fddefe
127.0.0.1:5984 127.0.0.1 undefined GET
/_utils/dashboard.assets/js/vendor.1dd5f02ec0ce91979b00.js 304 ok 12
[notice] 2022-12-08T18:13:09.871999Z ***@***.*** <0.347.0> 58a064500d
127.0.0.1:5984 127.0.0.1 undefined GET
/_utils/dashboard.assets/js/manifest.9d15b7c24fc8359d2668.js 304 ok 15
[notice] 2022-12-08T18:13:09.876089Z ***@***.*** <0.346.0> 4351f8d1fc
127.0.0.1:5984 127.0.0.1 undefined GET
/_utils/dashboard.assets/css/styles.01f570698487acedea0d.css 304 ok 20
[notice] 2022-12-08T18:13:09.876663Z ***@***.*** <0.349.0> 8ba0783b91
127.0.0.1:5984 127.0.0.1 undefined GET
/_utils/dashboard.assets/js/bundle.01f570698487acedea0d.js 304 ok 20
[notice] 2022-12-08T18:13:10.342487Z ***@***.*** <0.348.0> 25bebaa70d
127.0.0.1:5984 127.0.0.1 undefined GET /_session 200 ok 0
[notice] 2022-12-08T18:13:10.376621Z ***@***.*** <0.346.0> a9cbcec87e
127.0.0.1:5984 127.0.0.1 undefined GET / 200 ok 40
[notice] 2022-12-08T18:13:10.376621Z ***@***.*** <0.349.0> 4f16dae6bc
127.0.0.1:5984 127.0.0.1 undefined GET / 200 ok 42
[notice] 2022-12-08T18:13:10.377153Z ***@***.*** <0.347.0> 315385f120
127.0.0.1:5984 127.0.0.1 undefined GET / 200 ok 41
[notice] 2022-12-08T18:13:10.382688Z ***@***.*** <0.347.0> 317e0c51bc
127.0.0.1:5984 127.0.0.1 undefined GET
/_utils/dashboard.assets/img/couchdb-logo.png 304 ok 1
[notice] 2022-12-08T18:13:10.471906Z ***@***.*** <0.349.0> 646041ccaa
127.0.0.1:5984 127.0.0.1 undefined GET
/_utils/dashboard.assets/fonts/fauxtonicon5.woff 304 ok 1
[notice] 2022-12-08T18:13:10.472435Z ***@***.*** <0.347.0> 9280daf507
127.0.0.1:5984 127.0.0.1 undefined GET
/_utils/dashboard.assets/fonts/fontawesome-webfont.woff 304 ok 2
[notice] 2022-12-08T18:13:10.560756Z ***@***.*** <0.347.0> 5d71283cd6
127.0.0.1:5984 127.0.0.1 undefined GET /_session 200 ok 2
[notice] 2022-12-08T18:13:13.759756Z ***@***.*** <0.384.0> --------
couch_replicator_clustering : cluster stable
[notice] 2022-12-08T18:13:13.769599Z ***@***.*** <0.411.0> --------
Started replicator db changes listener <0.535.0>
[info] 2022-12-08T18:13:13.770299Z ***@***.*** <0.537.0> --------
open_result error {not_found,no_db_file} for _replicator
[notice] 2022-12-08T18:13:23.607390Z ***@***.*** <0.296.0> --------
rexi_server : cluster stable
[notice] 2022-12-08T18:13:23.607520Z ***@***.*** <0.300.0> --------
rexi_buffer : cluster stable
[error] 2022-12-08T18:13:37.389915Z ***@***.*** <0.760.0> -------- OS
Process Error <0.761.0> :: {os_process_error,{exit_status,134}}
[error] 2022-12-08T18:13:42.112163Z ***@***.*** <0.752.0> --------
rexi_server: from: ***@***.***(<0.748.0>) mfa:
fabric_rpc:update_docs/3
exit:{timeout,{gen_server,call,[couch_proc_manager,{get_proc,{doc,<<"_design/_auth">>,{1,[<<117,58,224,21,122,139,26,34,51,159,60,14,244,241,191,25>>]},{[{<<"language">>,<<"javascript">>},{<<"validate_doc_update">>,<<"\n
   function(newDoc, oldDoc, userCtx, secObj) {\n        if (newDoc._deleted
=== true) {\n            // allow deletes by admins and matching users\n
         // without checking the other fields\n            if
((userCtx.roles.indexOf('_admin') !== -1) ||\n                (userCtx.name
== oldDoc.name)) {\n                return;\n            } else {\n
       throw({forbidden: 'Only admins may delete other user docs.'});\n
       }\n        }\n\n        if (newDoc.type !== 'user') {\n
 throw({forbidden : 'doc.type must be user'});\n        } // we only allow
user docs for now\n\n        if (!newDoc.name) {\n
 throw({forbidden: 'doc.name is required'});\n        }\n\n        if
(!newDoc.roles) {\n            throw({forbidden: 'doc.roles must
exist'});\n        }\n\n        if (!isArray(newDoc.roles)) {\n
 throw({forbidden: 'doc.roles must be an array'});\n        }\n\n
 for (var idx = 0; idx < newDoc.roles.length; idx++) {\n            if
(typeof newDoc.roles[idx] !== 'string') {\n
 throw({forbidden: 'doc.roles can only contain strings'});\n            }\n
       }\n\n        if (newDoc._id !== ('org.couchdb.user:' + newDoc.name))
{\n            throw({\n                forbidden: 'Doc ID must be of the
form org.couchdb.user:name'\n            });\n        }\n\n        if
(oldDoc) { // validate all updates\n            if (oldDoc.name !==
newDoc.name) {\n                throw({forbidden: 'Usernames can not be
changed.'});\n            }\n        }\n\n        if (newDoc.password_sha
&& !newDoc.salt) {\n            throw({\n                forbidden: 'Users
with password_sha must have a salt.' +\n                    'See
/_utils/script/couch.js for example code.'\n            });\n        }\n\n
       var available_schemes = [\"simple\", \"pbkdf2\", \"bcrypt\"];\n
   if (newDoc.password_scheme\n                &&
available_schemes.indexOf(newDoc.password_scheme) == -1) {\n
 throw({\n                forbidden: 'Password scheme `' +
newDoc.password_scheme\n                    + '` not supported.'\n
   });\n        }\n\n        if (newDoc.password_scheme === \"pbkdf2\") {\n
           if (typeof(newDoc.iterations) !== \"number\") {\n
throw({forbidden: \"iterations must be a number.\"});\n            }\n
       if (typeof(newDoc.derived_key) !== \"string\") {\n
throw({forbidden: \"derived_key must be a string.\"});\n            }\n
   }\n\n        var is_server_or_database_admin = function(userCtx, secObj)
{\n            // see if the user is a server admin\n
 if(userCtx.roles.indexOf('_admin') !== -1) {\n                return true;
// a server admin\n            }\n\n            // see if the user a
database admin specified by name\n            if(secObj && secObj.admins &&
secObj.admins.names) {\n
 if(secObj.admins.names.indexOf(userCtx.name) !== -1) {\n
 return true; // database admin\n                }\n            }\n\n
     // see if the user a database admin specified by role\n
 if(secObj && secObj.admins && secObj.admins.roles) {\n                var
db_roles = secObj.admins.roles;\n                for(var idx = 0; idx <
userCtx.roles.length; idx++) {\n                    var user_role =
userCtx.roles[idx];\n                    if(db_roles.indexOf(user_role) !==
-1) {\n                        return true; // role matches!\n
       }\n                }\n            }\n\n            return false; //
default to no admin\n        }\n\n        if
(!is_server_or_database_admin(userCtx, secObj)) {\n            if (oldDoc)
{ // validate non-admin updates\n                if (userCtx.name !==
newDoc.name) {\n                    throw({\n
 forbidden: 'You may only update your own user document.'\n
   });\n                }\n                // validate role updates\n
         var oldRoles = (oldDoc.roles || []).sort();\n                var
newRoles = newDoc.roles.sort();\n\n                if (oldRoles.length !==
newRoles.length) {\n                    throw({forbidden: 'Only _admin may
edit roles'});\n                }\n\n                for (var i = 0; i <
oldRoles.length; i++) {\n                    if (oldRoles[i] !==
newRoles[i]) {\n                        throw({forbidden: 'Only _admin may
edit roles'});\n                    }\n                }\n            }
else if (newDoc.roles.length > 0) {\n                throw({forbidden:
'Only _admin may set roles'});\n            }\n        }\n\n        // no
system roles in users db\n        for (var i = 0; i < newDoc.roles.length;
i++) {\n            if (newDoc.roles[i] !== '_metrics') {\n              if
(newDoc.roles[i][0] === '_') {\n                  throw({\n
     forbidden:\n                      'No system roles (starting with
underscore) in users db.'\n                  });\n              }\n
   }\n        }\n\n        // no system names as names\n        if
(newDoc.name[0] === '_') {\n            throw({forbidden: 'Username may not
start with underscore.'});\n        }\n\n        var badUserNameChars =
[':'];\n\n        for (var i = 0; i < badUserNameChars.length; i++) {\n
       if (newDoc.name.indexOf(badUserNameChars[i]) >= 0) {\n
 throw({forbidden: 'Character `' + badUserNameChars[i] +\n
       '` is not allowed in usernames.'});\n            }\n        }\n
 }\n">>}]},[],false,[]},{<<"_design/_auth">>,<<"1-753ae0157a8b1a22339f3c0ef4f1bf19">>}},5000]}}
[{gen_server,call,3,[{file,"gen_server.erl"},{line,246}]},{couch_query_servers,get_ddoc_process,2,[{file,"src/couch_query_servers.erl"},{line,630}]},{couch_query_servers,with_ddoc_proc,2,[{file,"src/couch_query_servers.erl"},{line,525}]},{couch_query_servers,validate_doc_update,5,[{file,"src/couch_query_servers.erl"},{line,368}]},{couch_db,'-validate_doc_update_int/3-lc$^0/1-0-',5,[{file,"src/couch_db.erl"},{line,914}]},{couch_db,'-validate_doc_update_int/3-fun-1-',3,[{file,"src/couch_db.erl"},{line,917}]},{couch_stats,update_histogram,2,[{file,"src/couch_stats.erl"},{line,102}]},{couch_db,'-prep_and_validate_updates/6-fun-1-',3,[{file,"src/couch_db.erl"},{line,1014}]}]
[notice] 2022-12-08T18:13:42.112753Z ***@***.*** <0.727.0> f8b3ec1d15
localhost:5984 127.0.0.1 admin PUT /_users/org.couchdb.user:jan 500 ok 5054
[info] 2022-12-08T18:13:49.025870Z ***@***.*** <0.39.0> --------
SIGTERM received - shutting down

[info] 2022-12-08T18:13:49.026009Z ***@***.*** <0.39.0> --------
SIGTERM received - shutting down

**Comment by faisalabdulkadir** [comment]
When I try to run the command ./bin/couchjs -V  in my couch directory... I
get the error:

zsh: no such file or directory: ./bin/couchjs

**Comment by big-r81** [comment]
search for couchjs in your couchdb install directory, cd into that directory and try again with `./couchjs -V`, or can you join our slack community, then we can have a litte live session https://join.slack.com/t/couchdb/shared_invite/zt-fa9zim0j-H04m4o_KcLdWeOxEAcwM8g

**Comment by big-r81** [comment]
I am closing this topic as there has been no response.
