### ISSUE TITLE
Documentation should clearly mention how to configure backoff for replication

### ISSUE THREAD

**Issue by mikhailantoshkin** [apache/couchdb#4299]
## Summary
Documentation on replication states mentions that, quoting, `Repeated consecutive crashes result in an exponential backoff` and that `Maximum backoff interval is around a day or so`, but do not mention how to configure maximum backoff interval. Instead, this is mentioned in description of `max_history` configuration parameter for `replicator` section.

## Desired Behaviour
It would be much easier for the first time reader if connection of `max_history` to backoff interval will be mentioned somewhere in `Replicaton` section of documentation

**Comment by big-r81** [comment]
Hi @mikhailantoshkin, would you like to submit a PR for this, because you know best what needs to be done now ;-)?

**Comment by mikhailantoshkin** [comment]
Sure, I'll give it a shot)
