### ISSUE TITLE
Couch 3.1  restarts on all nodes but only 2 come back online sportically

### ISSUE THREAD

**Issue by zdravko123** [apache/couchdb#4300]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

We are having issues with all our Production CloudDB clusters running Ubuntu 18.04
we have about 14 clusters of 3 nodes each so a total of 52 hosted in Azure.
Since last Friday we saw that the nodes were falling in traffic & CPU (suspect losing connections or something was restarting) then they would ramp up but only 2 out of the 3 nodes would rejoin the cluster.
Although we saw sporadic issues in the days leading up to it but also a few months prior but they were recovering faster without outages.
We suspect something has changed recently but are unsure what exactly, we did note a new kernel was installed a few weeks prior.

Needless to say this is causing great hardship to the team with a person monitoring the servers 24/7 and manually restarting them.

Problem start time id say 7:30Pm on last Friday the 2nd as no one was around to restart them, it lasted a good hour.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Steps to Reproduce

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used:
* Browser name and version:
* Operating system and version:

## Additional Context
![2022-12-08 13_23_45-View panel - All Clusters - CPU Usage - Dashboards - Grafana](https://user-images.githubusercontent.com/47307329/206838232-7b39d071-0fa0-48a9-9961-0549152f7123.png)
![2022-12-10 18_30_28-2022-12-08 13_09_57-View panel - All Clusters - CPU Usage - Dashboards - Grafana](https://user-images.githubusercontent.com/47307329/206838279-f351692d-0041-446f-9451-9e37874bd204.png)
![2022-12-10 18_32_46-Untitled - Paint](https://user-images.githubusercontent.com/47307329/206838358-d6dbc9f6-a0e3-467f-bee8-2308b1c9728d.png)

[TIP]:  # ( Add any other context about the problem here. )

Any help would be much appreciated, some of the clusters are 1-4 months old, the others a few years, but it seems to be effecting all of them... its really quite perplexing,.. we havnt had too much change interims of load, and we also doubled the CPUS to 8 cores over the last few weeks to cope with XMas, which is even stranger.

**Comment by zdravko123** [comment]
![2022-12-10 19_29_34-Node Exporter (AU-WEST-02) - Dashboards - Grafana](https://user-images.githubusercontent.com/47307329/206841254-37fb7267-860c-4f5d-b5df-6c7f30b1983f.png)
image

**Comment by big-r81** [comment]
Any interesting in your log files, when the issues are rising?

**Comment by zdravko123** [comment]
we suspect that the new kernel was buggy, we doubled the size of the machines a few days prior or when it started happening, we believe this kicked in the new kernal install and then we had issues.  There was a new one that fixed some socket/tcp race conditions Friday we installed this on all the clusters and it looks like the issue has gone away.. luckily....  So i put it down to OS Kernal update for now, or Santa.

**Comment by zdravko123** [comment]
Question 1: What was the cause of instability?
Answer: Bad Ubuntu kernel (Version: 5.4.0-1095.101~18.04.1)

Question 2: Why it all started Friday, 2nd Dec?
Answer: This is when we started upsizing VMs in anticipation of holidays load

Question 3: How did the instability crawl in?
Answer: The bad kernel was downloaded around 18th of Nov. However Ubuntu requires VM to reboot for the new kernel to kick in. That reboot happened on 2nd, 3rd and 4th of Dec (Fri, Sat, Sun)

Question 3: What was the fix?
Answer: Ubuntu issued a fixed kernel 9th Dec (Friday). VMs were patched manually (with exception of NZ and MISC clusters ) between 3 am and 4:30 am today

**Comment by zdravko123** [comment]
https://www.ubuntuupdates.org/package/core/bionic/main/updates/linux-azure-5.4
