### ISSUE TITLE
Process couchspawnkillable.exe is moved in quarantine by virus scanner

### ISSUE THREAD

**Issue by damienlibouton** [apache/couchdb#4304]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
With some virus scanner like Avira Prime on Windows 11, the process couchspawnkillable.exe is moved in quarantine. 
The consequence is we can't request on views after that. 
When I restore the file and ask to the virus scanner to skip the analysis of the couchdb folder then everything is fine again. 

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Steps to Reproduce
Use CouchDB 3.2.2 on Windows 11, then proceed a virus scan.
The process couchspawnkillable.exe should be moved in quarantine.

## Expected Behaviour
The process couchspawnkillable.exe shouldn't be moved in quarantine.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: CouchDB 3.2.2
* Operating system and version: Windows 11

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by rnewson** [comment]
This sounds like a problem for Avira Prime, not CouchDB. Can you explain why you think we would need to do anything?

**Comment by nickva** [comment]
Try contacting Avira to report a false positive. The source for the file in question is https://github.com/apache/couchdb/blob/main/src/couch/priv/spawnkillable/couchspawnkillable_win.c and it hasn't changed significantly in 13 years.

Another idea is perhaps your machine was infected by something which modified or patched that file, can try comparing the contents (sha256 or md5) of `couchspawnkillable.exe` from a freshly downloaded and installed CouchDB install.

**Comment by damienlibouton** [comment]
> Try contacting Avira to report a false positive. The source for the file in question is https://github.com/apache/couchdb/blob/main/src/couch/priv/spawnkillable/couchspawnkillable_win.c and it hasn't changed significantly in 13 years.
> 
> Another idea is perhaps your machine was infected by something which modified or patched that file, can try comparing the contents (sha256 or md5) of `couchspawnkillable.exe` from a freshly downloaded and installed CouchDB install.

Thanks for the answer but before reporting this to Avira I did some check following your second idea.

### New machine CouchDB 3.2.2
```
PS C:\Program Files\Apache CouchDB\lib\couch-3.2.2\priv> Get-FileHash .\couchspawnkillable.exe

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          94A44AF0A43A3648E3B9388B6E0C8A90868D1F7C6329A86D0B6488580A30E0DF       C:\Program Files\Apache CouchDB\lib\couch-3.2.2\priv\couchspawnkillable.exe
```
### New machine CouchDB 3.2.0
```
PS C:\Program Files\Apache CouchDB\lib\couch-3.2.0\priv> Get-FileHash .\couchspawnkillable.exe

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          F9E14C76B8271C8F044343DF31F009AFB5BB750292B4E7534EC447639AD138E5       C:\Program Files\Apache CouchDB\lib\couch-3.2.0\priv\couchspawnkillable.exe
```
### Problematic machine CouchDB 3.2.2
```
PS C:\Program Files\Apache CouchDB\lib\couch-3.2.2\priv> Get-FileHash .\couchspawnkillable.exe

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          94A44AF0A43A3648E3B9388B6E0C8A90868D1F7C6329A86D0B6488580A30E0DF       C:\Program Files\Apache CouchDB\lib\couch-3.2.2\priv\couchspawnkillable.exe
```
Do you think it's normal to see a different hash value between CouchDB 3.2.0 and 3.2.2 taking into account that the last commit of this file was on April 1, 2017 ?

If yes I will just try to report this to Avira.

Once again thanks for your answer !

**Comment by damienlibouton** [comment]
> > Do you think it's normal to see a different hash value between CouchDB 3.2.0 and 3.2.2 taking into account that the last commit of this file was on April 1, 2017 ?
> 
> I would say yes, because we upgraded our build-chain to Visual Studio 2022 for the 3.2.2 release of CouchDB.
> 
> I would suspect for the next release a sha-diff again...

Yes I agree with you

I did another quick check installing CouchDB 3.1.1 on a fresh machine and the hash is also different.
```
PS C:\Program Files\Apache CouchDB\lib\couch-3.1.1\priv> Get-FileHash .\couchspawnkillable.exe

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          C3C879C3FF89CCEA84910D182DAE0F118C3B3EBCC89A67EBD2C278BC947A22B7       C:\Program Files\Apache CouchDB\lib\couch-3.1.1\priv\couchspawnkillable.exe
```

As usual, thank you for your reactivity !

I close this issue and I will try to contact Avira about this false positive even if I have no hope of success ! 
This is why I wanted to talk about this with you !

Have a good day
