### ISSUE TITLE
Network Less 3.3.0 Install

### ISSUE THREAD

**Issue by jo** [apache/couchdb#4312]
Previously, it was possible to build CouchDB without network access. Since 3.3.0 RC1 network access is required to

```
./configure
==> configuring couchdb in rel/couchdb.config
...
===> Verifying dependencies...
===> Fetching getopt v1.0.2
...
```

Without network access, configure fails with

```
./configure
==> configuring couchdb in rel/couchdb.config
...
===> Verifying dependencies...
===> Failed to update package getopt from repo hexpm
===> Package not found in any repo: getopt
```

Tested with

- icu 4c-71_1
- Erlang OTP-24.3.4.6 and OTP-25.2
- spidermonkey 91.0esr

**Comment by nickva** [comment]
Thanks for trying it out and the` report @jo. Yeah it would be nice to see why this is a regression. 

Something with a rebar3 changed I imagined and the dependencies are not checked cached the same way as before?

**Comment by nickva** [comment]
This commit should enable ./configure and make release to work without a network https://github.com/apache/couchdb/pull/4319

**Comment by nickva** [comment]
@jo thanks taking the time and care to try out the new release and help debug it! It's much appreciated!
