### ISSUE TITLE
Verify Install Replication Test Failure in 3.3.0

### ISSUE THREAD

**Issue by jo** [apache/couchdb#4313]
Replication test fails with response:
```json
{"error":"unknown_error","reason":"badarg","ref":2888279473}
```

![Screenshot from 2022-12-17 18-36-58](https://user-images.githubusercontent.com/17586/208255024-86d1e592-0f4e-4752-8119-d597f7072bad.png)

The logs show
```
[error] 2022-12-17T18:04:15.637384Z e97200c05c0aab273717da799b19488e@127.0.0.1 <0.24053.0> 5b216d97d5 req_err(2888279473) unknown_error : badarg
    [<<"erlang:list_to_binary/1">>,<<"chttpd:make_uri/2 L575">>,<<"chttpd:fix_uri/3 L553">>,<<"chttpd:possibly_hack/1 L513">>,<<"chttpd:handle_req_after_auth/2 L407">>,<<"chttpd:process_request/1 L388">>,<<"chttpd:handle_request_int/1 L325">>,<<"mochiweb_http:headers/6 L140">>]
[notice] 2022-12-17T18:04:15.637532Z e97200c05c0aab273717da799b19488e@127.0.0.1 <0.24053.0> 5b216d97d5 127.0.0.1:37621 127.0.0.1 admin POST /_replicate 500 ok 1
```

I was able to reproduce the Fauxton verify install test failure with curl:

```
curl -XPUT http://user:password@127.0.0.1:37621/verifytestdb
curl -XPOST http://user:password@127.0.0.1:37621/_replicate -d '{"create_target":true,"source":"verifytestdb","target":"verifytestdb_replicate"}' -H'Content-Type:application/json'
{"error":"unknown_error","reason":"badarg","ref":2888279473}
```

IMO replication must include the full urls for source and target. It was still supported for the /_replicate endpoint in 3.2.2, which I just confirmed.

Issuing a replication with full urls like this works as expected, so maybe just the test is outdated?
```json
{
  "create_target": true,
  "source": "http://user:password@127.0.0.1:37621/verifytestdb",
  "target": "http://user:password@127.0.0.1:37621/verifytestdb_replicate"
}
```

**Comment by nickva** [comment]
@jo thanks for trying it out and for your report.

It worked on MacOS for me. I wonder if it's related to a difference in networking how localhost is resolved or set up. What OS or network settings are you using?

**Comment by jo** [comment]
I am running this on Fedora from inside a Flatpak container, like defined here: https://github.com/jo/couchdb-flatpak-example/blob/couchdb-3.3.0/com.example.HelloCouchDB.yml

**Comment by jo** [comment]
Ah, I just read https://docs.couchdb.org/en/3.2.2-docs/api/server/common.html#post--_replicate

> For backwards compatibility, CouchDB 3.x will auto-convert bare database names by prepending the address and port CouchDB is listening on, to form a complete URL. This behaviour is deprecated in 3.x and will be removed in CouchDB 4.0.

**Comment by nickva** [comment]
This PR https://github.com/apache/couchdb/pull/4314 fix this issue
