### ISSUE TITLE
Auto Shard Management 

### ISSUE THREAD

**Issue by TheRook** [apache/couchdb#4315]
Dynamically manage sharing and other database tuning at runtime.

## Summary

A new revolution in database management is automating as much as possible so that the database can react to application demands more quickly and avoid outages or performance bottlenecks.  Automated shard management and database tuning is an emerging technology that can greatly benefit the growing CouchDB ecosystem. 

## Desired Behaviour

Making it effortless to reshape and tune a CouchDB cluster.

## Possible Solution
 The Apache Foundation has two promising projects that can tune and reshape a database cluster at runtime. 

Apache ShardingSphere:
https://github.com/apache/shardingsphere
ShardingSphere uses JDBC which is supported by CouchDB, but this combination is missing something.

Apache OtterTune:
https://ottertune.com/

## Additional context

It would be nice to be able to manage a large number of smaller CouchDB instances running CouchDB that syncs over OrbitDB, a DHT and CRDT-based p2p protocol.

**Comment by rnewson** [comment]
Are you planning to work on this?

**Comment by rnewson** [comment]
Thank you for the ticket. We're aware that couchdb could improve its sharding system, and particularly we see value in higher level tools to allow resharding in place, and so on. 

This is a huge topic and not one that this issue will advance at all, unless you are willing to do this work in substantial part.

I note that neither project you mention would be appropriate for CouchDB.
