### ISSUE TITLE
CouchDB 3.3.1 for MacOS is missing Spidermonkey

### ISSUE THREAD

**Issue by StephanU** [apache/couchdb#4381]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )
It seems like the "bundled" Apache CouchDB for MacOS does not contain Spidermonkey (anymore). 
The result is, that views cannot be created ("Verify Installation" fails in the "Create View" step). Manually creating views results in an error "500 internal server error".
The couchdb log is flooded with the following message:
```
[info] 2023-01-17T13:48:05.756841Z couchdb@localhost <0.298.0> -------- couch_proc_manager <0.12658.0> died normal
[error] 2023-01-17T13:48:05.756890Z couchdb@localhost <0.1176.0> -------- OS Process Error <0.12658.0> :: {os_process_error,{exit_status,134}}
```
Installing Spidermonkey manually (`brew install spidermonkey`) solves the problem.
Using CouchDB 3.1.1 this works out of the box (without installing spidermonkey manually). 

```
 % ./couchjs -V
dyld[69565]: Library not loaded: /usr/local/opt/spidermonkey/lib/libmozjs-91.dylib
  Referenced from: <2EEBCDB5-670B-39A8-8361-18D50EA6898C> /Users/stephan/Downloads/Apache CouchDB.app/Contents/Resources/couchdbx-core/bin/couchjs
  Reason: tried: '/usr/local/opt/spidermonkey/lib/libmozjs-91.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/spidermonkey/lib/libmozjs-91.dylib' (no such file), '/usr/local/opt/spidermonkey/lib/libmozjs-91.dylib' (no such file), '/usr/lib/libmozjs-91.dylib' (no such file, not in dyld cache)
zsh: abort      ./couchjs -V
```

I think this issue #4296 has the same problem, but with version 3.2.2.

## Steps to Reproduce

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )
- Download Apache CouchDb 3.3.1 for MacOs.
- Make sure you **don't** have spidermonkey installed.
- Start the CouchDB and execute "Verifiy Installation", it will fail when creating the view.

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )
- Installing the "Apache CouchDB native application" for MacOS should work out of the box.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: 3.3.1
* Browser name and version: Firefox 108.0.2
* Operating system and version: macOS Ventura 13.1

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by big-r81** [comment]
Closing this, duplicate, see #4372.
