### ISSUE TITLE
remsh doesn't works when vm.args cookie is quoted

### ISSUE THREAD

**Issue by nickva** [apache/couchdb#4405]
In https://github.com/apache/couchdb-pkg/pull/106 we fixed a bug where the Erlang cookie couldn't accept some characters. With that fix the cookie value in vm.args might be quoted and our remsh script doesn't know how to parse that yet. That will break remsh access on next release.

We'll likely need updates here  https://github.com/apache/couchdb/blob/88ebc65c0d0c464bf45b10ad6a3234dd07361975/rel/overlay/bin/remsh#L50-L57

And here https://github.com/apache/couchdb/blob/88ebc65c0d0c464bf45b10ad6a3234dd07361975/rel/overlay/bin/remsh#L121-L130

**Comment by imskr** [comment]
Can I work on this? I'm new to this project

**Comment by big-r81** [comment]
> Can I work on this? I'm new to this project

@imskr 
Sure! 👍

**Comment by big-r81** [comment]
@imskr 
Do you have any news / work on this feature?

**Comment by imskr** [comment]
Hi @big-r81 I need some help here. Can you guide me?

**Comment by big-r81** [comment]
Hi, what questions do you have? Are you able to compile CouchDB already? If not, read our [README for Devs](https://github.com/apache/couchdb/blob/main/README-DEV.rst). If you have any other questions, please just ask.

**Comment by imskr** [comment]
Yes I'm able to compile. I was wondering how we can parse the quoted cookie value

**Comment by big-r81** [comment]
The cookie can come from an env var (`ERL_FLAGS`), from an args file (`vm.args`) or from the command line as argument from the `remsh` script. In https://github.com/apache/couchdb-pkg/pull/106 there should be some inspirations of the changed regex for cookie extractions.
