### ISSUE TITLE
beam.smp not able to start when ipv6 is disabled

### ISSUE THREAD

**Issue by ctsatheesh** [apache/couchdb#4421]
[NOTE]: # ( ^^ When ipv6 is disabled, couchdb is not able to start service. ^^ )

## Description
When starting couchdb with IPV6 disabled, it fails with error: 
.....
 CGroup: /system.slice/couchdb.service
             ├─932103 /opt/couchdb/bin/../erts-12.3.2.7/bin/beam.smp -K true -A>
             ├─932114 /opt/couchdb/bin/../erts-12.3.2.7/bin/epmd -daemon
             └─932133 erl_child_setup 65536

Feb 12 08:57:28 <ip> systemd[1]: Started Apache CouchDB.
Feb 12 08:57:28 <ip> epmd[932114]: epmd: failed to bind on ipaddr ::1

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Steps to Reproduce
Disable ipv6 in linux/ubuntu system.
Start couchdb
[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour
Couchdb especially beam.smp should be able to bind only ipv4 if ipv6 is disabled on the system.
[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment
Ubuntu 20.04
[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: 3.2.2
* Browser name and version: NA
* Operating system and version: Ubuntu 20.04

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by big-r81** [comment]
Is there any oher erlang (epmd) process running in the background (if CouchDB is shutdown)?

**Comment by satheeshp2e** [comment]
No other epmd process running.

**Comment by big-r81** [comment]
What is the output of (run in shell):

`erl -eval '{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"])), io:fwrite(Version), halt().' -noshell`

**Comment by satheeshp2e** [comment]
24.2.1

**Comment by big-r81** [comment]
okay and how did you instal CouchDB?

**Comment by satheeshp2e** [comment]
Followed these steps:

sudo apt update && sudo apt install -y curl apt-transport-https gnupg
curl https://couchdb.apache.org/repo/keys.asc | gpg --dearmor | sudo tee /usr/share/keyrings/couchdb-archive-keyring.gpg  >/dev/null 2>&1
source /etc/os-release
echo "deb [signed-by=/usr/share/keyrings/couchdb-archive-keyring.gpg] https://apache.jfrog.io/artifactory/couchdb-deb/ ${VERSION_CODENAME} main"  | sudo tee /etc/apt/sources.list.d/couchdb.list >/dev/null
sudo apt update
sudo apt install -y couchdb

**Comment by big-r81** [comment]
ok, what shows:

```
ls -al /opt/couchdb
```

**Comment by big-r81** [comment]
If you have Ubuntu 20.04 and you have installed CouchDB v3.2.2, you should have an `erts-11.2.2.13` dir inside... 

Can you remove CouchDB and your system erlang version completely and reinstall CouchDB? 
Do a backup of your CouchDB data, if any.

**Comment by satheeshp2e** [comment]
My bad.
Actually installed version of couchdb is: 
couchdb/jammy,now 3.3.1~jammy amd64 [installed]

**Comment by big-r81** [comment]
Then you have the fixes for the erlang, if ipv6 is disabled. Can you remove your system erlang and try again?

**Comment by satheeshp2e** [comment]
After disabling ipv6, here is the output of ip command.
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP group default qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet xx.x.xx.x/20 metric 100 brd 10.0.15.255 scope global dynamic ens5
       valid_lft 2869sec preferred_lft 2869sec
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet xxx.xx.x.x/16 brd xxx.xx.xxx.xxx scope global docker0
       valid_lft forever preferred_lft forever

With this, when starting couchdb service, bind error is not seen, but couchdb is not listening on 5984 and it keeps changing the process id.

$ ps -aef | grep couchdb
couchdb   661190       1  0 14:56 ?        00:00:00 /opt/couchdb/bin/../erts-12.3.2.7/bin/beam.smp -K true -A 16 -Bd -- -root /opt/couchdb/bin/.. -progname couchdb -- -home /opt/couchdb -- -boot /opt/couchdb/bin/../releases/3.3.1/couchdb -name couchdb@127.0.0.1 -setcookie 5 -kernel inet_dist_use_interface {127,0,0,1} -kernel error_logger silent -sasl sasl_error_logger false -noshell -noinput -smp enable -ssl session_lifetime 300 -- -config /opt/couchdb/bin/../releases/3.3.1/sys.config --
couchdb   661201       1  0 14:56 ?        00:00:00 /opt/couchdb/bin/../erts-12.3.2.7/bin/epmd -daemon
couchdb   661220  661190  0 14:56 ?        00:00:00 erl_child_setup 65536

$ ps -aef | grep couchdb
couchdb   661241       1  0 14:56 ?        00:00:00 /opt/couchdb/bin/../erts-12.3.2.7/bin/beam.smp -K true -A 16 -Bd -- -root /opt/couchdb/bin/.. -progname couchdb -- -home /opt/couchdb -- -boot /opt/couchdb/bin/../releases/3.3.1/couchdb -name couchdb@127.0.0.1 -setcookie 5 -kernel inet_dist_use_interface {127,0,0,1} -kernel error_logger silent -sasl sasl_error_logger false -noshell -noinput -smp enable -ssl session_lifetime 300 -- -config /opt/couchdb/bin/../releases/3.3.1/sys.config --
couchdb   661252       1  0 14:56 ?        00:00:00 /opt/couchdb/bin/../erts-12.3.2.7/bin/epmd -daemon
couchdb   661271  661241  0 14:56 ?        00:00:00 erl_child_setup 65536

**sudo systemctl status couchdb**
couchdb.service - Apache CouchDB
     Loaded: loaded (/lib/systemd/system/couchdb.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-02-15 15:31:12 UTC; 215ms ago
   Main PID: 703243 (beam.smp)
      Tasks: 37 (limit: 9401)
     Memory: 19.6M
        CPU: 236ms
     CGroup: /system.slice/couchdb.service
             ├─703243 /opt/couchdb/bin/../erts-12.3.2.7/bin/beam.smp -K true -A 16 -Bd -- -root /opt/couchdb/bin/.. -progname couchdb -- -home /opt/couchdb -- -boot /o>
             ├─703254 /opt/couchdb/bin/../erts-12.3.2.7/bin/epmd -daemon
             └─703273 erl_child_setup 65536

Feb 15 15:31:12 ip-10-0-14-8 systemd[1]: Started Apache CouchDB.

But beam.smp is not listening on 5984 port.

**Comment by satheeshp2e** [comment]
> Then you have the fixes for erlang, if ipv6 is disabled. Can you remove your system erlang and try again?

How do I remove system erlang ?

**Comment by big-r81** [comment]
> > Then you have the fixes for erlang, if ipv6 is disabled. Can you remove your system erlang and try again?
> 
> How do I remove system erlang ?

https://www.how2shout.com/linux/how-to-install-erlang-on-ubuntu-20-04-lts-linux/#7_Uninstall_or_Remove_Erlang_from_Ubuntu_2004

**Comment by ctsatheesh** [comment]
Looks like, ipv6 is not completely disabled in the system. After disabling ipv6(with a reboot of the system), we are able to bring up couchdb and process is listening on 5984 port.
