### ISSUE TITLE
Minor. A setting for HAProxy is wrong

### ISSUE THREAD

**Issue by 8thblock** [apache/couchdb#4456]
A setting for HAProxy is wrong.

Look at the first example here
https://docs.couchdb.org/en/stable/best-practices/reverse-proxies.html

You have repeated couchdb2 as a server name twice. Just correct the last line to couchdb3.

Cheers,
DM

**Comment by big-r81** [comment]
@8thblock 
Hi, do you need any support (setting up dev environment, etc..) while working on this or do you have any other questions?
