### ISSUE TITLE
"apache.jfrog.io" no more available.  Where are the .deb packages now?

### ISSUE THREAD

**Issue by hilbix** [apache/couchdb#4489]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

I tried to follow the instructions to install CouchDB on Ubuntu 22.04:

<https://docs.couchdb.org/en/latest/install/unix.html#enabling-the-apache-couchdb-package-repository>

But URL <https://apache.jfrog.io/artifactory/couchdb-deb/dists/jammy/InRelease> fails to download with

```
# curl -D- https://apache.jfrog.io/artifactory/couchdb-deb/dists/jammy/InRelease
HTTP/1.1 302 Moved Temporarily
Date: Wed, 22 Mar 2023 04:48:34 GMT
Content-Type: text/html
Content-Length: 138
Connection: keep-alive
Location: https://landing.jfrog.com/reactivate-server/apache

<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

## Steps to Reproduce

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

Open <https://apache.jfrog.io/artifactory/couchdb-deb/> in a browser, this gives:

```
Time flies when you’re having fun.
Your 14-day trial may be over, but you have options!
Need help choosing the right subscription or additional time on your trial? Just let us know and a DevOps expert will reach out to assist you.
```

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

Artifactory is available at the documented URL.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

```
# cat /etc/apt/sources.list.d/couchdb.list 
  deb [signed-by=/etc/opt/keys/apache.gpg] https://apache.jfrog.io/artifactory/couchdb-deb/              jammy   main
# md5sum /etc/opt/keys/apache.gpg 
35f3e52afb5b8cb33ab0751e39b9886b  /etc/opt/keys/apache.gpg
```

* CouchDB version used: N/A (cannot install)
* Browser name and version: apt
* Operating system and version: Ubuntu 22.04.2 LTS

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

If this problem is transient, then please consider moving somewhere with some more stable service.
Debian Repositories are so plain dead simple, that there is absolutely no need to host them at some unreliable ISP.
If you need Jfrog to create the deb packages etc., then please consider some official mirror.

Thanks.
PS: Please note that such type of error also creates massive warnings in the monitoring infrastructure, because `apt` fails to update properly.

**Comment by nickva** [comment]
Thank you for your report. Apologies for the error. I made an ASF infra ticket hopefully it's just a temporary blip. 
https://issues.apache.org/jira/browse/INFRA-24371

> Debian Repositories are so plain dead simple, that there is absolutely no need to host them at some unreliable ISP.
If you need Jfrog to create the deb packages etc., then please consider some official mirror.

They maybe be simple but somebody has to host them. JFrog is not an ISP. There are also features we use like package signing, RPM support, automatic repo management etc.

**Comment by nickva** [comment]
@hilbix access should be restored, closing

**Comment by jmta** [comment]
Hi,
This issue appears to have returned, can I expect this JFrog instance to be back up soon?

**Comment by big-r81** [comment]
I would say, it's only temporary. I add a comment to the existing INFRA ticket.

**Comment by Nithe14** [comment]
Now it redirects to landing.jfrog.com and consistently returns an HTTP 409 error. At least for the RPM repo.

**Comment by vectorselector** [comment]
this issue should not be closed while the infrastructural single-point-of-failure exists, which was never addressed.
this breaks apt for production systems

**Comment by rnewson** [comment]
if jfrog's uptime is insufficient for you (I think this incident is unlikely to occur again, fwiw) you can make your own mirror of our debian repository easily enough and pull through that instead. In some environments having an in-house mirror is a requirement.

**Comment by big-r81** [comment]
fyi: all should be functional again!
