### ISSUE TITLE
I get an error from time to time "No DB shards could be opened".

### ISSUE THREAD

**Issue by man4j** [apache/couchdb#4497]
## Description

I get an error from time to time **{"error":"internal_server_error","reason":"No DB shards could be opened.","ref":3085039011}**. My couchdb server is running under very low load, a certain number of requests per day. But every few months in the logs I see this error. There are no anomalies on the physical host at this time.

## Steps to Reproduce

Can not reproduce.

## Your Environment

* CouchDB version used: 3.3.1
* Browser name and version:
* Operating system and version: official docker image

[couchdb]
single_node = true
max_document_size = 104857600
os_process_timeout = 60000
uuid = 5df939f744387ae4fa952e508ffe9c9d

[chttpd_auth]
timeout = 60000
secret = f0393df78f36900c7eabc290375b4d6c

[httpd]
server_options = [{backlog, 60000}, {acceptor_pool_size, 32}, {max, 60000}]
socket_options = [{recvbuf, 1048576}, {nodelay, true}]

[fabric]
shard_timeout_factor = 600000

[cluster]
n = 1
q = 1

[native_query_servers]
enable_erlang_query_server = true

**Logs from couchdb for the period then the error occured:**

[info] 2023-03-22T12:17:56.927601Z nonode@nohost <0.24024.92> -------- Starting index update for db: shards/00000000-ffffffff/customer_db.1675884148 idx: _design/by_trainer_view

[info] 2023-03-22T12:17:56.947198Z nonode@nohost <0.24024.92> -------- Index update finished for db: shards/00000000-ffffffff/customer_db.1675884148 idx: _design/by_trainer_view

[error] 2023-03-22T12:17:57.214453Z nonode@nohost <0.25092.92> 92761c941b req_err(3085039011) internal_server_error : No DB shards could be opened.

2023-03-22T12:17:57.215433283Z     [<<"fabric_util:get_shard/4 L134">>,<<"fabric_util:get_shard/4 L152">>,<<"fabric:get_security/2 L220">>,<<"chttpd_auth_request:db_authorization_check/1 L109">>,<<"chttpd_auth_request:authorize_request/1 L19">>,<<"chttpd:handle_req_after_auth/2 L406">>,<<"chttpd:process_request/1 L388">>,<<"chttpd:handle_request_int/1 L325">>]

**Comment by big-r81** [comment]
Could you please show us the complete log file (as  a gist or from a paste-bin service)?

**Comment by man4j** [comment]
Log file: [https://pastebin.com/HFLHsBAH](https://pastebin.com/HFLHsBAH)

**Comment by nickva** [comment]
That's generated from a timeout when trying to query security properties from any available shards. Normally if q=2,n=3 there are quite a few of those shards for your case with n=1, q=1 there is only shard copy and if that times-out then the security properties fetch times and it results in a crash.

If you're on 3.3.1 try increasing the `[fabric] shard_timeout_min_msec` to say 5000 from the default of 100.

**Comment by man4j** [comment]
thanks, I will try!
