### ISSUE TITLE
Error: Exceeded maximum number of revisions

### ISSUE THREAD

**Issue by manurajsingh** [apache/couchdb#4523]
Hello All

I am on CouchDB 3.3.1.

I am invoking a purge request to remove 50,000 documents, where my CouchDB contains about 150,000 documents.

I have updated local.ini with following
`[purge]
max_document_id_number = 100000`

as well as changed the _purged_infos_limit for that couch database to 100,000 (upped from 1000 default)

In either of the cases, I am getting back error informing me 

"{"error":"bad_request","reason":"Exceeded maximum number of revisions."}<EOL>"

Please could you indicate what is wrong with my configuration.

Thanks.

**Comment by nickva** [comment]
@manurajsingh did the above suggestion help?

**Comment by manurajsingh** [comment]
That helped thank you.
