### ISSUE TITLE
 jsapi.h: No such file or directory

### ISSUE THREAD

**Issue by tuaris** [apache/couchdb#455]
The needed include files are under `/home/user/include/js`.  How do I ensure that path is being used during build for version 2.0.0?

```
compiling /home/user/work/apache-couchdb-2.0.0/src/couch/priv/couch_js/http.c
/home/user/work/apache-couchdb-2.0.0/src/couch/priv/couch_js/http.c:18:19: fatal error: jsapi.h: No such file or directory
 #include <jsapi.h>
                   ^
compilation terminated.
ERROR: compile failed while processing /home/user/work/apache-couchdb-2.0.0/src/couch: rebar_abort
```

**Comment by wohali** [comment]
1. Start with a clean checkout.
2. Run `./configure -c` to ensure you are enabling the curl interface for couchjs. This is used primarily for testing, but will make the process easier. You will need to ensure libcurl is installed along with its developer package (i.e., include headers)
3. Edit the file `src/couch/rebar.config.script` and on line 74 change `-I/usr/local/include` to `-I/usr/local/include -I/home/user/include/js`. On the same line you'll have to change `-lmozjs185` to `-L/home/user/lib -lmozjs185` if the `libmozsj185.so` library isn't installed under `/usr` as well.
4. `make rel` should succeed.

In production it is common for CouchDB to not have to share a machine with other processes that would conflict on the JS version, so it's most typical that Spidermonkey 1.8.5 will be installed under /usr.

If you're feeling enterprising, a pull request to enhance our `rebar.config.script` to support adding include/library paths from environment variables would be most welcome. You can see we reference environment variables down on lines 91 and 92; a similar trick for JS_CFLAGS/JS_LDFLAGS should work.

**Comment by antonyRoberts** [comment]
@tuaris, I don't know if the above worked for you, but I was also having an issue installing couchDB 2.0.0 because of the missing ```jsapi.h``` file. My problem was related to the installation of SpiderMonkey.  @wohali was kind enough to help me through the problem and point me to their [make file](https://github.com/apache/couchdb-ci/blob/master/ansible/roles/dependencies-centos/tasks/spidermonkey.yml) which provides a link to the dependencies to get SpiderMonkey to run on RedHat or CentOs, and https://github.com/apache/couchdb-ci looks to be helpful for a couple of other build issues I've had to stumble upon fixes for.

**Comment by MarcoDima** [comment]
I'm having a similar problem while trying to change the paths of the folders where couchdb finds spidermonkey and icu.
I edited the rebar.config.script to modify spidermonkey path and it seems to work.
So is there a way to make the same with icu? I can't find where this path is set and so i'm not able to change it.

I'm using Ubuntu 14.04, Spidermonkey 1.8.5 and icu4c-52_1 and couchdb-2.1

**Comment by m4ver1k** [comment]
In `Arch Linux` and installing `js185` solves the issue.

**Comment by abarbosa-godaddy** [comment]
> In `Arch Linux` installing `js185` solves the issue.

Like `sudo pacman -S js185`? It didn't work for me.

I am using Manjaro.

**Comment by big-r81** [comment]
> > In `Arch Linux` installing `js185` solves the issue.
> 
> Like `sudo pacman -S js185`? It didn't work for me.
> 
> I am using Manjaro.

Hi, try to install the latest spidermonkey version with
```
pamac install js91
```
and configure your CouchDB install with:
```
./configure --spidermonkey-version 91
make
```

**Comment by abarbosa-godaddy** [comment]
Nice, @big-r81 . It worked. Thank you,
