### ISSUE TITLE
CouchDB data folder is getting bigger and bigger

### ISSUE THREAD

**Issue by larryaubstore** [apache/couchdb#464]
Hi, I just noticed that CouchDB data folder is getting big very quickly.  I use this docker image: https://github.com/klaemo/docker-couchdb (Tag 2.0.0)

The fix I found for the moment is to call manually  'http://couchdbserver/{dbname}/_view_cleanup' on each database. 

Before cleanup, the database took 5GB and after cleanup the database take 86M.

It there a way to configure automatically the 'clean_up' task ?

**Comment by janl** [comment]
See http://docs.couchdb.org/en/2.0.0/maintenance/compaction.html for details

**Comment by larryaubstore** [comment]
Thank you for the quick response. Do you have an example somewhere ? 

I added this config in local.ini but it does not seem to work:

`_default = [{db_fragmentation, "70%"}, {view_fragmentation, "60%"}, {from, "07:00"}, {to, "11:00"}]`

Do I have to specify the databases somewhere ?

**Comment by larryaubstore** [comment]
The automatic compaction does not seem to work. I tried with 5%, it is never triggered:

`__default = [{db_fragmentation, "5%"}, {view_fragmentation, "5%"}, {from, "07:00"}, {to, "11:00"}]_`

There is an other thing that it is not clear to me. Does '_clean_up' operation included in compaction ?
