### ISSUE TITLE
DOCUMENTATION - Creating a new user method HTTP method is wrong

### ISSUE THREAD

**Issue by dbeniteza** [apache/couchdb#4642]
Hello,

I've found an error on the documentation section [1.5.2.2. Creating a New User](https://docs.couchdb.org/en/stable/intro/security.html#creating-a-new-user).

It is said "_Creating a new user is a very trivial operation. You just need to do a [PUT](https://tools.ietf.org/html/rfc7231#section-4.3.4) request with the user’s data to CouchDB_"

This is wrong, since the PUT method will try to create the _users database. The correct HTTP method is POST.

Please correct this typo in the documentation.

As a suggestion, it would help to explicitly include in this documentation section that this call must be done with an admin user. Consider including in the curl example something like this:
```
curl -X **POST** <admin_user>:<admin_password>@localhost:5984/_users/org.couchdb.user:jan \
     -H "Accept: application/json" \
     -H "Content-Type: application/json" \
     -d '{"name": "jan", "password": "apple", "roles": [], "type": "user"}'
```

**Comment by nickva** [comment]
> since the PUT method will try to create the _users database. The correct HTTP method is POST.

PUT should not create a new database but a new user document

The URL is `http://localhost:5984/_users/org.couchdb.user:jan` `_users` is the database and `org.couchdb.user:jan` is the document ID. PUT is also the correct method in this case as we're creating or replacing a resource and we're identifying by its resource (the URL path).

Maybe we should assert or include that we are assuming in the documentation that `_users` db has already been created  and the `jan` user has not been added to it yet.

Good point however that this needs an admin user and admin password. That is mentioned above in [Authentication Database](https://docs.couchdb.org/en/stable/intro/security.html#authentication-database) but that may be easy to miss so showing it in the example would make it easier to see.
