### ISSUE TITLE
Configuring [jwt_keys] via HTTP PUT Fails

### ISSUE THREAD

**Issue by ronnieroyston** [apache/couchdb#4655]
[Documentation says](https://docs.couchdb.org/en/stable/api/server/configuration.html#put--_node-node-name-_config-section-key):

> `PUT /_node/{node-name}/_config/{section}/{key}`
> Updates a configuration value. The new value should be supplied in the request body in the corresponding JSON format. If you are setting a string value, you must supply a valid JSON string. In response CouchDB sends old value for target section key.

## Description

It don't work. CouchDB replies:
```
  "error": "bad_request",
  "reason": "invalid UTF-8 JSON"
```
or
```
{
  "error": "unknown_error",
  "reason": "function_clause",
  "ref": 1050348183
}
```

## Steps to Reproduce

http://localhost:5984/_node/_local/_config/jwt_keys/rsa%3Apublic

with body (it's all one single line):
```
"rsa:public = -----BEGIN PUBLIC KEY-----\nMIIBIjANBg......xAB\n-----END PUBLIC KEY-----"
```
also tried:
```
{
	"rsa": {
		"public": "-----BEGIN PUBLIC KEY-----\nMIIBIjA.....IDAQAB\n-----END PUBLIC KEY-----\n"
	}
}
```
and
```
{"rsa":"public = -----BEGIN PUBLIC KEY-----\nMIIBIjAN....DAQAB\n-----END PUBLIC KEY-----\n"}
```
also tried several other variations.

## Expected Behaviour

It is supposed to configure this key.

## Your Environment

Containerized Couch :latest w Chrome

**Comment by big-r81** [comment]
Hi,

you send only the value in the body as JSON string. You will need to double-escape the `\n`.

Example:
```
curl -X PUT "http://a:a@127.0.0.1:15984/_node/_local/_config/jwt_keys/hmac:testkey" -d '"-----BEGIN PUBLIC KEY-----\\nMIIBIjAN....DAQAB\\n-----END PUBLIC KEY-----\\n"
```
