### ISSUE TITLE
Expose A Function For All Database Requests w/ doc, req arguments?

### ISSUE THREAD

**Issue by ronnieroyston** [apache/couchdb#4667]
Documentation indicates that one can [log()](https://docs.couchdb.org/en/stable/query-server/javascript.html#log) [toJSON](https://docs.couchdb.org/en/stable/query-server/javascript.html#toJSON)(or otherwise handle) a [request object](https://docs.couchdb.org/en/stable/json-structure.html#request-object)  but it don't work for design validation functions.

I am pondering the best way to extend authorization on CouchDB. If a function could fire on HTTP request we could build out custom authorization possibly per field or per document. As is, the authorization for the entire database is either on or off in terms of read access.

**Comment by janl** [comment]
since this is in the direct doc write path, shelling out to an external service will make this impossibly slow in practice. In addition, couchjs has no access to a HTTP client library (on purpose). This type of work is best done in a proxy in front of CouchDB.
