### ISSUE TITLE
couch_peruser not working

### ISSUE THREAD

**Issue by bshikhar13** [apache/couchdb#468]
I am using CouchDB 2.0 on my Windows machine. I created `_users` database. Setted the `couch_peruser` flag in the configuration window to be true. After restarting the CouchDB when I added a user in the _users database, no new database was created. What can be the problem?

**Comment by wohali** [comment]
couch_peruser is indeed broken in 2.0.0; there are no plans to fix it at this time. The current plan is to replace the feature entirely with new functionality.

If you need couch_peruser functionality please use couchdb 1.6.x.
