### ISSUE TITLE
Update docs to describe how to install on CIS hardened ubuntu 

### ISSUE THREAD

**Issue by nickva** [apache/couchdb#4723]
From Slack thread:

EC2 instance with CIS Hardened (AMI ami-09bc4918bb796a43a)
```
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

These were steps shared by a user on how to install:

1. Add `[trusted=yes]` to couchdb repo
2. Manually import GPG key with command:
   `apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0EE62FB37A00258D`
3.  `apt install couchdb --allow_unauthenticated`

**Comment by rnewson** [comment]
a suggestion to do `--allow_unauthenticated` is not something that should land in our official docs.

**Comment by nickva** [comment]
Agree, those were just the steps that user took, I copy pasted them verbatim.

I never heard of “hardened” Ubuntu either. Wonder if it has fewer root certificates, or silently ignored our public key…

**Comment by rnewson** [comment]
🤷 it makes no sense to choose a hardened OS image and then install unauthenticated software on top.

**Comment by nickva** [comment]
I think it's still interesting for us to figure out if is there a way to do it properly. They are probably not the first user to encounter these "hardened" images. I do not have access to AWS but perhaps someone else does and can try it out.

**Comment by rnewson** [comment]
oh, for sure. we should update our advice on how to do it securely, if it's possible within the CIS strictures.

**Comment by nickva** [comment]
Having found that CIS hardened images don't seem to be [available](https://www.cisecurity.org/cis-hardened-image-list) for a general download only on cloud providers, I am closing the issue. Without an image at hand it will just end up being guess work.
