### ISSUE TITLE
CouchDB crashing under macOS Sonoma

### ISSUE THREAD

**Issue by mrappard** [apache/couchdb#4730]
CouchDB crashing under macOS Sonoma

## Description

CouchDB crashing under macOS Sonoma Beta

## Steps to Reproduce

Did a Fresh install of CouchDB 3.3.2 and the program will just crash and reload over and over again

## Expected Behaviour

Not doing that

## Your Environment

* CouchDB 3.3.2
* Apple M1 Pro
* MAC OS 14.0 Beta (23A5312d)

## Additional Context

The Log is Logging 

[error] 2023-07-18T23:04:20.046391Z couchdb@localhost emulator -------- Error in process <0.20531.63> on node couchdb@localhost with exit value:
{database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,430}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,405}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,434}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,100}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,214}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,160}]}]}

Over and over again

Would be happy to provide any additional info.

**Comment by rnewson** [comment]
That's not a crash (though it does look alarming if you're new to couchdb). Just create the `_users` database and it'll stop. It's harmless, but noisy.

Are you also reporting a crash or was this it?

**Comment by mrappard** [comment]
Again... it's one of those things that becomes clear when your seeing it, but the Application (Apache CouchDB) from the Application folder, repeatedly crashes (The computer hangs for a moment then it works then it hangs for a moment over and over again)

And this is with a Fresh Install.

I.E. Yes I needs access to the _users directory, but I think there is a _users directory it's unable to access it.

**Comment by mrappard** [comment]
Here is the Crash Report 

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               beam.smp [1091]
Path:                  /Applications/Apache CouchDB.app/Contents/Resources/couchdbx-core/erts-13.2/bin/beam.smp
Identifier:            beam.smp
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        Apache CouchDB [917]
Responsible:           Apache CouchDB [917]
User ID:               501

Date/Time:             2023-08-14 13:59:35.3941 -0400
OS Version:            macOS 14.0 (23A5312d)
Report Version:        12
Anonymous UUID:        079DC458-6D9E-B11E-FABD-8462B65BC4D2


Time Awake Since Boot: 88 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x0000000101660000
Exception Codes:       0x0000000000000002, 0x0000000101660000

Termination Reason:    Namespace SIGNAL, Code 10 Bus error: 10
Terminating Process:   exc handler [1091]

VM Region Info: 0x101660000 is in 0x101660000-0x101680000;  bytes after start: 0  bytes before end: 131071
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      VM_ALLOCATE                 101560000-101660000    [ 1024K] rw-/rwx SM=PRV  
--->  VM_ALLOCATE                 101660000-101680000    [  128K] rwx/rwx SM=PRV  
      GAP OF 0x24000 BYTES
      dyld private memory         1016a4000-1016e4000    [  256K] rw-/rwx SM=PRV  

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_platform.dylib      	       0x1806a16f8 _platform_memmove + 168
1   beam.smp                      	       0x100f09b08 asmjit::_abi_1_9::CodeHolder::copyFlattenedData(void*, unsigned long, asmjit::_abi_1_9::CopySectionFlags) + 120
2   beam.smp                      	       0x100ed24c4 BeamGlobalAssembler::BeamGlobalAssembler(asmjit::_abi_1_9::JitAllocator*) + 640
3   beam.smp                      	       0x100ee1878 beamasm_init + 288
4   beam.smp                      	       0x100f41f8c erl_start + 9656
5   beam.smp                      	       0x100eb591c main + 12
6   dyld                          	       0x1802f9058 start + 2224

Thread 1:: sys_sig_dispatc
0   libsystem_kernel.dylib        	       0x180633474 read + 8
1   beam.smp                      	       0x1010851a8 signal_dispatcher_thread_func + 104
2   beam.smp                      	       0x1010e7804 thr_wrapper + 168
3   libsystem_pthread.dylib       	       0x180673034 _pthread_start + 136
4   libsystem_pthread.dylib       	       0x18066de3c thread_start + 8

Thread 2:: sys_msg_dispatc
0   libsystem_kernel.dylib        	       0x1806360ac __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1806735fc _pthread_cond_wait + 1228
2   beam.smp                      	       0x1010e5444 ethr_cond_wait + 12
3   beam.smp                      	       0x100f66d0c erts_cnd_wait + 180
4   beam.smp                      	       0x100f66b88 sys_msg_dispatcher_wait + 44
5   beam.smp                      	       0x100fe9838 erts_thr_progress_register_managed_thread + 584
6   beam.smp                      	       0x100f66330 sys_msg_dispatcher_func + 112
7   beam.smp                      	       0x1010e7804 thr_wrapper + 168
8   libsystem_pthread.dylib       	       0x180673034 _pthread_start + 136
9   libsystem_pthread.dylib       	       0x18066de3c thread_start + 8


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000101660000   x1: 0x000000013480d240   x2: 0x0000000000001ef0   x3: 0x0000000101660020
    x4: 0x00000000331ad200   x5: 0x0000000000000020   x6: 0x00000001011221e0   x7: 0x00000001011221c0
    x8: 0x0000000101660000   x9: 0x0000000000000000  x10: 0x0000000000000000  x11: 0x0000000000000000
   x12: 0x00000001348082e0  x13: 0x0000000000000000  x14: 0x0000600003de8000  x15: 0x0000000000000001
   x16: 0x00000001806a1650  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000001f10
   x20: 0x0000000000001f10  x21: 0x0000000000000001  x22: 0x0000000000001f10  x23: 0x0000000101660000
   x24: 0x0000000134808260  x25: 0x0000000000000000  x26: 0x0000000134808240  x27: 0x0000000000000010
   x28: 0x0000000000000000   fp: 0x000000016ef4e980   lr: 0x0000000100f09b08
    sp: 0x000000016ef4e920   pc: 0x00000001806a16f8 cpsr: 0x80001000
   far: 0x0000000101660000  esr: 0x9200004f (Data Abort) byte write Permission fault

Binary Images:
       0x100eb0000 -        0x1011b7fff beam.smp (*) <e55f1ae8-343b-3b47-a8c6-ac00e054abaa> /Applications/Apache CouchDB.app/Contents/Resources/couchdbx-core/erts-13.2/bin/beam.smp
       0x18069e000 -        0x1806a4ffb libsystem_platform.dylib (*) <e0882bf0-1ddf-32f7-b839-df904b1bc220> /usr/lib/system/libsystem_platform.dylib
       0x1802f3000 -        0x18038686f dyld (*) <197a2824-ba58-3ff4-8c52-399ae7ba8457> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x180631000 -        0x18066bfef libsystem_kernel.dylib (*) <34754346-13eb-3436-9244-5d697f1b3ab6> /usr/lib/system/libsystem_kernel.dylib
       0x18066c000 -        0x180678ff3 libsystem_pthread.dylib (*) <c7c679c8-ed5a-351e-bade-bbca3631b70e> /usr/lib/system/libsystem_pthread.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)
Writable regions: Total=702.9M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=702.9M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           684.2M       19 
MALLOC guard page                   96K        6 
STACK GUARD                       56.0M        3 
Stack                             9264K        3 
VM_ALLOCATE                        1.0G        9 
__AUTH                             714K      162 
__AUTH_CONST                      12.6M      311 
__DATA                            3454K      298 
__DATA_CONST                      15.3M      314 
__DATA_DIRTY                       695K      104 
__FONT_DATA                          4K        1 
__LINKEDIT                       884.0M        2 
__OBJC_RO                         70.5M        1 
__OBJC_RW                         2149K        1 
__TEXT                           240.0M      328 
dyld private memory                272K        2 
mapped file                         64K        1 
shared memory                       80K        4 
===========                     =======  ======= 
TOTAL                              2.9G     1571 



-----------
Full Report
-----------

{"app_name":"beam.smp","timestamp":"2023-08-14 13:59:35.00 -0400","app_version":"","slice_uuid":"e55f1ae8-343b-3b47-a8c6-ac00e054abaa","build_version":"","platform":1,"share_with_app_devs":0,"is_first_party":1,"bug_type":"309","os_version":"macOS 14.0 (23A5312d)","roots_installed":0,"incident_id":"9B6E2D7D-5630-4261-8666-383BDBD9EF20","name":"beam.smp"}
{
  "uptime" : 88,
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,3",
  "coalitionID" : 1012,
  "osVersion" : {
    "train" : "macOS 14.0",
    "build" : "23A5312d",
    "releaseType" : "User"
  },
  "captureTime" : "2023-08-14 13:59:35.3941 -0400",
  "codeSigningMonitor" : 1,
  "incident" : "9B6E2D7D-5630-4261-8666-383BDBD9EF20",
  "pid" : 1091,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-08-14 13:59:35.2584 -0400",
  "procStartAbsTime" : 2111223778,
  "procExitAbsTime" : 2114438309,
  "procName" : "beam.smp",
  "procPath" : "\/Applications\/Apache CouchDB.app\/Contents\/Resources\/couchdbx-core\/erts-13.2\/bin\/beam.smp",
  "parentProc" : "Apache CouchDB",
  "parentPid" : 917,
  "coalitionName" : "org.apache.couchdb",
  "crashReporterKey" : "079DC458-6D9E-B11E-FABD-8462B65BC4D2",
  "responsiblePid" : 917,
  "responsibleProc" : "Apache CouchDB",
  "codeSigningID" : "beam",
  "codeSigningTeamID" : "5FZCA65884",
  "codeSigningFlags" : 570491649,
  "codeSigningValidationCategory" : 6,
  "codeSigningTrustLevel" : 4294967295,
  "instructionByteStream" : {"beforePC":"YgwBrMADX9ZjgACRY+h7kiIMQKxlAADLIQAFiyAEQKwhgACRQgAFyw==","atPC":"AgwArUIAAfHpAABUYAQArWOAAJEgBECsIYAAkUKAAPFo\/\/9UIQACiw=="},
  "sip" : "enabled",
  "vmRegionInfo" : "0x101660000 is in 0x101660000-0x101680000;  bytes after start: 0  bytes before end: 131071\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      VM_ALLOCATE                 101560000-101660000    [ 1024K] rw-\/rwx SM=PRV  \n--->  VM_ALLOCATE                 101660000-101680000    [  128K] rwx\/rwx SM=PRV  \n      GAP OF 0x24000 BYTES\n      dyld private memory         1016a4000-1016e4000    [  256K] rw-\/rwx SM=PRV  ",
  "exception" : {"codes":"0x0000000000000002, 0x0000000101660000","rawCodes":[2,4318429184],"type":"EXC_BAD_ACCESS","signal":"SIGBUS","subtype":"KERN_PROTECTION_FAILURE at 0x0000000101660000"},
  "termination" : {"flags":0,"code":10,"namespace":"SIGNAL","indicator":"Bus error: 10","byProc":"exc handler","byPid":1091},
  "vmregioninfo" : "0x101660000 is in 0x101660000-0x101680000;  bytes after start: 0  bytes before end: 131071\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      VM_ALLOCATE                 101560000-101660000    [ 1024K] rw-\/rwx SM=PRV  \n--->  VM_ALLOCATE                 101660000-101680000    [  128K] rwx\/rwx SM=PRV  \n      GAP OF 0x24000 BYTES\n      dyld private memory         1016a4000-1016e4000    [  256K] rw-\/rwx SM=PRV  ",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":10764,"threadState":{"x":[{"value":4318429184},{"value":5175824960},{"value":7920},{"value":4318429216},{"value":857395712},{"value":32},{"value":4312932832,"symbolLocation":32,"symbol":"asmjit::_abi_1_9::EmitterUtils::noExt"},{"value":4312932800,"symbolLocation":0,"symbol":"asmjit::_abi_1_9::EmitterUtils::noExt"},{"value":4318429184},{"value":0},{"value":0},{"value":0},{"value":5175804640},{"value":0},{"value":105553181179904},{"value":1},{"value":6449403472,"symbolLocation":0,"symbol":"_platform_memmove"},{"value":0},{"value":0},{"value":7952},{"value":7952},{"value":1},{"value":7952},{"value":4318429184},{"value":5175804512},{"value":0},{"value":5175804480},{"value":16},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4310735624},"cpsr":{"value":2147487744},"fp":{"value":6156511616},"sp":{"value":6156511520},"esr":{"value":2449473615,"description":"(Data Abort) byte write Permission fault"},"pc":{"value":6449403640,"matchesCrashFrame":1},"far":{"value":4318429184}},"queue":"com.apple.main-thread","frames":[{"imageOffset":14072,"symbol":"_platform_memmove","symbolLocation":168,"imageIndex":1},{"imageOffset":367368,"symbol":"asmjit::_abi_1_9::CodeHolder::copyFlattenedData(void*, unsigned long, asmjit::_abi_1_9::CopySectionFlags)","symbolLocation":120,"imageIndex":0},{"imageOffset":140484,"symbol":"BeamGlobalAssembler::BeamGlobalAssembler(asmjit::_abi_1_9::JitAllocator*)","symbolLocation":640,"imageIndex":0},{"imageOffset":202872,"symbol":"beamasm_init","symbolLocation":288,"imageIndex":0},{"imageOffset":597900,"symbol":"erl_start","symbolLocation":9656,"imageIndex":0},{"imageOffset":22812,"symbol":"main","symbolLocation":12,"imageIndex":0},{"imageOffset":24664,"symbol":"start","symbolLocation":2224,"imageIndex":2}]},{"id":10767,"name":"sys_sig_dispatc","threadState":{"x":[{"value":4},{"value":0},{"value":4},{"value":6157070432},{"value":6156512136},{"value":15},{"value":27993984541616484},{"value":0},{"value":59},{"value":1},{"value":1},{"value":4314497712},{"value":4314497712},{"value":0},{"value":0},{"value":0},{"value":3},{"value":8066811672},{"value":0},{"value":0},{"value":4313649152,"symbolLocation":96,"symbol":"compose_tab_27_3"},{"value":6157070088},{"value":4},{"value":4312290328},{"value":128},{"value":30347},{"value":18446744073709551615},{"value":4313579680,"symbolLocation":0,"symbol":"erts_allctrs"},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4312289704},"cpsr":{"value":1610616832},"fp":{"value":6157070208},"sp":{"value":6157070048},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6448952436},"far":{"value":6157070336}},"frames":[{"imageOffset":9332,"symbol":"read","symbolLocation":8,"imageIndex":4},{"imageOffset":1921448,"symbol":"signal_dispatcher_thread_func","symbolLocation":104,"imageIndex":0},{"imageOffset":2324484,"symbol":"thr_wrapper","symbolLocation":168,"imageIndex":0},{"imageOffset":28724,"symbol":"_pthread_start","symbolLocation":136,"imageIndex":5},{"imageOffset":7740,"symbol":"thread_start","symbolLocation":8,"imageIndex":5}]},{"id":10769,"name":"sys_msg_dispatc","threadState":{"x":[{"value":260},{"value":0},{"value":0},{"value":0},{"value":0},{"value":160},{"value":0},{"value":0},{"value":6157643128},{"value":0},{"value":4313892168,"symbolLocation":24,"symbol":"smq_mtx"},{"value":2},{"value":0},{"value":0},{"value":0},{"value":0},{"value":305},{"value":8066808960},{"value":0},{"value":4313892144,"symbolLocation":0,"symbol":"smq_mtx"},{"value":4313892344,"symbolLocation":0,"symbol":"smq_cnd"},{"value":6157644000},{"value":0},{"value":0},{"value":0},{"value":1},{"value":256},{"value":0},{"value":4313890816,"symbolLocation":104,"symbol":"pi_1_keys_list_heap"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6449214972},"cpsr":{"value":1610616832},"fp":{"value":6157643248},"sp":{"value":6157643104},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6448963756},"far":{"value":4311114432}},"frames":[{"imageOffset":20652,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":4},{"imageOffset":30204,"symbol":"_pthread_cond_wait","symbolLocation":1228,"imageIndex":5},{"imageOffset":2315332,"symbol":"ethr_cond_wait","symbolLocation":12,"imageIndex":0},{"imageOffset":748812,"symbol":"erts_cnd_wait","symbolLocation":180,"imageIndex":0},{"imageOffset":748424,"symbol":"sys_msg_dispatcher_wait","symbolLocation":44,"imageIndex":0},{"imageOffset":1284152,"symbol":"erts_thr_progress_register_managed_thread","symbolLocation":584,"imageIndex":0},{"imageOffset":746288,"symbol":"sys_msg_dispatcher_func","symbolLocation":112,"imageIndex":0},{"imageOffset":2324484,"symbol":"thr_wrapper","symbolLocation":168,"imageIndex":0},{"imageOffset":28724,"symbol":"_pthread_start","symbolLocation":136,"imageIndex":5},{"imageOffset":7740,"symbol":"thread_start","symbolLocation":8,"imageIndex":5}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4310368256,
    "size" : 3178496,
    "uuid" : "e55f1ae8-343b-3b47-a8c6-ac00e054abaa",
    "path" : "\/Applications\/Apache CouchDB.app\/Contents\/Resources\/couchdbx-core\/erts-13.2\/bin\/beam.smp",
    "name" : "beam.smp"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6449389568,
    "size" : 28668,
    "uuid" : "e0882bf0-1ddf-32f7-b839-df904b1bc220",
    "path" : "\/usr\/lib\/system\/libsystem_platform.dylib",
    "name" : "libsystem_platform.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6445543424,
    "size" : 604272,
    "uuid" : "197a2824-ba58-3ff4-8c52-399ae7ba8457",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6448943104,
    "size" : 241648,
    "uuid" : "34754346-13eb-3436-9244-5d697f1b3ab6",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6449184768,
    "size" : 53236,
    "uuid" : "c7c679c8-ed5a-351e-bade-bbca3631b70e",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  }
],
  "sharedCache" : {
  "base" : 6444793856,
  "size" : 3971661824,
  "uuid" : "411c6161-39d1-33b8-830d-c90b3e51ed0a"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)\nWritable regions: Total=702.9M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=702.9M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           684.2M       19 \nMALLOC guard page                   96K        6 \nSTACK GUARD                       56.0M        3 \nStack                             9264K        3 \nVM_ALLOCATE                        1.0G        9 \n__AUTH                             714K      162 \n__AUTH_CONST                      12.6M      311 \n__DATA                            3454K      298 \n__DATA_CONST                      15.3M      314 \n__DATA_DIRTY                       695K      104 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       884.0M        2 \n__OBJC_RO                         70.5M        1 \n__OBJC_RW                         2149K        1 \n__TEXT                           240.0M      328 \ndyld private memory                272K        2 \nmapped file                         64K        1 \nshared memory                       80K        4 \n===========                     =======  ======= \nTOTAL                              2.9G     1571 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "d22ef97400c14a870090f3e7d7cc3dd57659f3fe",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6410af69ed1e1e7ab93ed169",
      "factorPackIds" : {
        "SIRI_VALUE_INFERENCE_PHONECALL_SMART_APP_SELECTION" : "6467af26e1a7a067be468054"
      },
      "deploymentId" : 250000007
    },
    {
      "rolloutId" : "64c025b28b7f0e739e4fbe58",
      "factorPackIds" : {

      },
      "deploymentId" : 250000005
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "8ca8349c-e2bc-482c-9ca7-3907b48a5341",
      "experimentId" : "648b5a581b04c12d4127bbb6",
      "deploymentId" : 400000002
    },
    {
      "treatmentId" : "6dd670af-0633-45e4-ae5f-122ae4df02be",
      "experimentId" : "64406ba83deb637ac8a04419",
      "deploymentId" : 900000017
    }
  ]
}
}

**Comment by rnewson** [comment]
that's more like it, thanks for the report.

**Comment by mrappard** [comment]
Feels like it might be an Elixir problem

https://elixirforum.com/t/bus-error-after-upgrading-to-sonoma-beta/56354

**Comment by big-r81** [comment]
Hi,

macOS Sonoma isn't released yet and the latest provided macOS binary doesn't support it. You can try to compile CouchDB on your own and see if it works then.

**Comment by rnewson** [comment]
CouchDB is not written in Elixir but I think it's likely that erlang/OTP doesn't work right on the pre-release macOS as yet. Until it's an official release I'm not sure we'll be able to help. It might entirely be fixed by a newer release of erlang/OTP, I'm sure that team will be keen to support Sonoma as quickly as possible.

**Comment by big-r81** [comment]
Closing for now. You can reopen the issue when we released a supported version for macOS Sonoma.
