### ISSUE TITLE
 file copy of .couch from 2.x isn't picked up by couchdb 3.3.2

### ISSUE THREAD

**Issue by fr2lancer** [apache/couchdb#4733]
[NOTE]: # file copy of .couch from 2.x isn't picked up by couchdb 3.3.2

## Description
Simply when I copied one of <db_name>.couch file to couchdb 3.3.2
 GET '127.0.0.1:5984/<db_name> -> no database error
when I copied _dbs file to couchdb 3, 
GET '127.0.0.1:5984/<db_name> -> I can see the detail of <db_name> but number of docs is 0

Admin is set and it works well from scratch.
but when I got to start to data migration with file copying, it didn't seem to work .

## Steps to Reproduce

[NOTE]: # please see above

## Expected Behaviour

Couch db 2 file needs to be loaded in couchdb 3 when file copy.

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used:
* Browser name and version:
* Operating system and version:

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by nickva** [comment]
Are there any errors showing in the logs when the db is opened?

It's mostly likely that the node names in the _dbs are different on the new cluster. Make sure to update those node names to match.

Refer to https://docs.couchdb.org/en/stable/cluster/sharding.html#moving-a-shard and copying a shard section to see how the `_dbs` metadata is structured and how nodes should be updated.

**Comment by fr2lancer** [comment]
Thank you so much. I ended up copy whole files.
