### ISSUE TITLE
CouchDB does not sync when connected to  DSL line 

### ISSUE THREAD

**Issue by seifbm** [apache/couchdb#4734]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

On a Normal DSL couch DB does not sync data unless i restart apach couch db service or restart the workstation.
Connection speed is 20Mb Down and 1Mb upload

When i switch to Mobile tethering the sync start with no issues 

## Steps to Reproduce

connect to a standard DSL with 1Mb upload max

## Expected Behaviour

Sync data with a delay as upload is slow

## Your Environment

On Workstation
curl http://localhost:5984/
{"couchdb":"Welcome","version":"3.2.2","git_sha":"d5b746b7c","uuid":"f7a67b47b840333c1dd4f529c57b43fa","features":["access-ready","partitioned","pluggable-storage-engines","reshard","scheduler"],"vendor":{"name":"The Apache Software Foundation"}}

On Server
curl https://direct-couchdb-****.com/
{"couchdb":"Welcome","version":"3.1.1","git_sha":"ce596c65d","uuid":"af5ea6680a634041ae534246bcaf7ad7","features":["access-ready","partitioned","pluggable-storage-engines","reshard","scheduler"],"vendor":{"name":"The Apache Software Foundation"}}

OS: | Windows 10 Enterprise  (64 bit)
Build: | 10.0.19045.2965
Apache CouchDB    3.2.2
Google Chrome    114.0.5735.110

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by dangotti** [comment]
@seifbm, I opened the ticket https://neighbourhoodie.freshdesk.com/support/tickets/889 on Neighbourhoodie to help us.

**Comment by janl** [comment]
Heya @dangotti no need to open a ticket here if you also submitted to our _private_ support issue tracker. We’ll respond there. I’lll close and lock this issue.
