### ISSUE TITLE
Run CouchDB in port other than 5984

### ISSUE THREAD

**Issue by aruns05** [apache/couchdb#4741]
Description

Below is a docker file to run couchDB in port 5988. Is it possible to run Couchdb in port other than 5984

* CouchDB version used: v3.3.2
* Browser name and version: Chrome/ Firefox
* Operating system and version: MacOS Ventura 13.4

version: '3'
services:
  couchserver:
    image: couchdb
    restart: always
    ports:
      - '5988:5988'
    environment:
      - COUCHDB_USER=<>
      - COUCHDB_PASSWORD=<>
      - DB_NAME=<>
    volumes:
      - ./dbdata:/opt/couchdb/data

**Comment by rnewson** [comment]
https://docs.couchdb.org/en/stable/config/http.html#chttpd/port
