### ISSUE TITLE
Couch db hung and system unstable after periods of times

### ISSUE THREAD

**Issue by fr2lancer** [apache/couchdb#4747]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

After couchdb 3 was installed successfully, -> no modified in vm.cfg and minimal config in local.ini

for certain period(2-3 days), it worked fine(I was able to communicated to other services) but load average gets high and /proc/<proc_id>/mem_files were stuck so systemctl related commands are unstable such as reboot, ps -ef, systemctl.

It is repeated after rebooting the server.

And not much obvious log were found in couchdb.log

And resource usage wise, still have space in memory, swap

So I am doubting if some of implementation couchdb and erlang could course this issue.

## Expected Behaviour

1) expecting couchdb or erlang would send proper verbose message when in abnormal condition
2) process exit safely when it required
3) Or provide more troubleshooting details in the doc

## Your Environment

* CouchDB version used:
couchdb-3.3.2-1.el8 in RHEL8 packages
* Operating system and version:
2 * Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz
Mem 4G
Red Hat Enterprise Linux release 8.8 (Ootpa)(4.18.0-477.10.1.el8_8.x86_64)

**Comment by big-r81** [comment]
Hi,

you can increase the log level to see whether the behavior is triggered through CouchDB. We have a great documentation at https://docs.couchdb.org. You can search for "logging" (as a small hint).

Restart CouchDB after changing the ini file and observe your log files if there are any new infos.

At the moment, we can't give any advice to you, because you didn't proven that CouchDB is the problem.

**Comment by fr2lancer** [comment]
Hi. is there a way to debug it from Erlang level? 

It actually nothing show in the debug logs. It just silently died.

**Comment by nickva** [comment]
Are there any logs at all at debug or info level being emitted? When things slow down too much there are usually timeout errors being logged.

I see you have 4GB of ram. That may be a bit low, does it behave differently if you increase the amount of memory?

Could try querying a `/_node/_local/_stats` and `/_node/_local/_system` and share to see if there are any message queues backing up perhaps.

**Comment by fr2lancer** [comment]
Hi it has been upgrade to use 8GB ram on last Thurs. today I checked it -> still same issue - seems like died on Sat
I can't query it as it not responding me any more

I found this in dmesg -> so it became  'D' status and consuming resources

 INFO: task 1_scheduler:1658 blocked for more than 120 seconds.
[169939.922146]       Not tainted 4.18.0-477.10.1.el8_8.x86_64 #1
[169939.922162] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.


[169694.167806]       Not tainted 4.18.0-477.10.1.el8_8.x86_64 #1
[169694.167823] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[169694.167848] task:1_scheduler     state:D stack:    0 pid: 1658 ppid:     1 flags:0x00000080
[169694.167853] Call Trace:
[169694.167857]  __schedule+0x2d1/0x870
[169694.167866]  schedule+0x55/0xf0
[169694.167868]  io_schedule+0x12/0x40
[169694.167871]  migration_entry_wait_on_locked+0x1ea/0x290
[169694.167876]  ? filemap_fdatawait_keep_errors+0x50/0x50
[169694.167879]  do_swap_page+0x5b0/0x710
[169694.167881]  ? pmd_devmap_trans_unstable+0x2e/0x40
[169694.167886]  ? handle_pte_fault+0x5d/0x880
[169694.167888]  __handle_mm_fault+0x453/0x6c0
[169694.167890]  handle_mm_fault+0xca/0x2a0
[169694.167892]  __do_page_fault+0x1f0/0x450
[169694.167897]  do_page_fault+0x37/0x130
[169694.167900]  ? page_fault+0x8/0x30
[169694.167904]  page_fault+0x1e/0x30

**Comment by nickva** [comment]
`D` state from what I remember is un-interruptable sleep waiting on a disk operation. If it's true that it was in that state for 120 seconds, that indicates a problem with disk IO.  Check perhaps that you have enough disk bandwidth? Is this running in a cloud provider's host or directly on a hardware?

**Comment by fr2lancer** [comment]
Hi.

It seems like kernel issue https://access.redhat.com/solutions/7014646
once it has been patched, I didn't see such log in dmesg.

I just wonder why it happens only in couchdb ?

btw, you can close this ticket. I will reopen this if I found similar symptoms

**Comment by nickva** [comment]
@fr2lancer that's great news that they fixed it.

> I just wonder why it happens only in couchdb ?

It's hard to say. Unlike other software, but not unlike other databases, CouchDB performs a lot of concurrent writes mixed with fsyncs. If the kernel is also trying to read/write swap pages it could trigger some specific corner case?
