### ISSUE TITLE
Encrypt the [ssl] password for the private key file.

### ISSUE THREAD

**Issue by estoT1** [apache/couchdb#4768]
Encrypt the [ssl] password for the private key file.

## Summary
Currently the [ssl] private key file password is not getting encrypted.

## Desired Behaviour
Encrypt the [ssl] password for the private key file.
https://docs.couchdb.org/en/stable/config/http.html#ssl/password

**Comment by rnewson** [comment]
And how do you see the password being decrypted when the couchdb service starts?

**Comment by estoT1** [comment]
For example store with salt or pepper.

**Comment by rnewson** [comment]
Salt and pepper are only used when hashing a value through a one-way digest algorithm like SHA-2. CouchDB needs the actual password in order to decrypt the encrypted private key in your proposal.

I don't understand what you are proposing, can you please describe in more detail how you would like CouchDB to encrypt the ssl password and how CouchDB would be able to decrypt it when it needs the actual password to decrypt the private key?

Thanks.

**Comment by estoT1** [comment]
Thank you for your feedback and time,
The actual implementation is in the scope of a programmer. The requested result is that the ini file does not have the password in clear text. 
Password masking is solved by other projects also. Example ActiveMQ Artemis password masking: https://activemq.apache.org/components/artemis/documentation/latest/masking-passwords.html
Thank you in advance!

**Comment by rnewson** [comment]
Obfuscation or masking provides no real protection (I note that the link you mentioned says the masking feature is "deprecated and exists only to maintain backward-compatibility"), we would rather not pretend it has any value.

The file containing the ssl password should be restricted by normal OS-level access controls and the hosting server should be similarly protected against intrusion.

We're open to a proposal but the onus on designing something that represents a genuine security improvement is on you. It is not sufficient to say "encrypt this" without details. To guide you, CouchDB typically runs as a supervised service and thus will need access to the plaintext password to the private key every time it starts.

You can of course move your TLS layer elsewhere, to HAProxy or Nginx or similar. This is almost mandatory once you have a multi-node CouchDB cluster anyway.

**Comment by pavlov2000uk** [comment]
Here is another example -> https://docs.confluent.io/platform/current/security/secrets-tutorial.html

**Comment by big-r81** [comment]
> Here is another example -> https://docs.confluent.io/platform/current/security/secrets-tutorial.html

But in this example, what is the benefit? You would need to store the master key somewhere on the computer who want to access the properties file...

**Comment by big-r81** [comment]
I am closing this topic as there has been no response.
