### ISSUE TITLE
remsh extract wrong NODE name from ERL_FLAGS.

### ISSUE THREAD

**Issue by telesoho** [apache/couchdb#4783]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

remsh cannot node name from env ERL_FLAGS.

## Steps to Reproduce

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

1. export ERL_FLAGS="-setcookie balabala"
2. set `-name couchdb@172.1.0.111` in `etc/vm.args`
3. run remsh

## Expected Behaviour

remsh should show `(couchdb@172.1.0.111)1>` as shell prompt. 
But it show default prompt `(remsh1087@127.0.0.1)1>`.

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: 3
* Browser name and version: Chrome
* Operating system and version: Ubuntu 22.04

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by nickva** [comment]
Thanks for reporting the issue and for the fix @telesoho! It's much appreciated.
