### ISSUE TITLE
compaction_log_level  not working on Couchdb version 3.3.2 

### ISSUE THREAD

**Issue by Sdas0000** [apache/couchdb#4815]
## Description

compaction_log_level  to capture compaction information not working on Couchdb version 3.3.2.

## Steps to Reproduce

[log]
writer = journald
level = error
compaction_log_level = debug

also tried 

[log]
writer = journald
level = error
compaction_log_level = warning

## Expected Behaviour

The compaction information should be published to logs 

Proper documentation Not available 

## Your Environment

Non-Production 

* CouchDB version used: 3.3.2 
* Browser name and version:
* Operating system and version: Linux

**Comment by big-r81** [comment]
Hi,

looking at https://docs.couchdb.org/en/stable/config-ref.html#cap-log there is no `compaction_log_level` key. Try to set `level` properly.

**Comment by Sdas0000** [comment]
It is in default.ini 

https://github.com/apache/couchdb/blob/main/rel/overlay/etc/default.ini

Line number 96 
 
; Sets the log level for informational compaction related entries.
;compaction_log_level = info




I think it is coded : 

167 | {Key, Starting1} ->
-- | --
168 | Level = smoosh_utils:log_level("compaction_log_level", "notice"),
169 | LogMsg = "~s: Started compaction for ~s",
 
252 | Capacity = smoosh_utils:capacity(State#state.name),
253 | Level = smoosh_utils:log_level("compaction_log_level", "notice"),
254 | LogMsg = "~s: enqueueing ~p to compact with priority ~p",

**Comment by nickva** [comment]
The `default.ini` has two(!) places where we configure the compaction log level. One is in the `[couchdb]` section, and the other is in the `[smoosh]` section. The one in `[couchdb]` indicates when compaction actually happens, even if triggered manually via `/_compact` endpoint; and the one in `[smoosh]`, is for entries emitted by the smoosh auto-compactor service.

Try setting both to `warning` (or both to`error`) and see if you see any emitted logs. Depending how you set the values, if it's at runtime you may want to call `_reload` or simply restart your nodes: https://docs.couchdb.org/en/stable/api/server/configuration.html#node-node-name-config-reload

Good find @big-r81 that we never documented that config value. They are kind of low level that's probably why bit might be nice to document them nevertheless.

**Comment by big-r81** [comment]
@nickva 
Would it make sense to consolidate this into one section (e.g. [smoosh]) only?

**Comment by Sdas0000** [comment]
After setting compaction logging information , we are still not getting anything in our log for compaction , 
"log": {
    "level": "error",
    "writer": "journald"
  },
.....
"smoosh": {
    "compaction_log_level": "notice",
    "db_channels": "ratio_dbs, slack_dbs",
    "view_channels": "ratio_views,slack_views"
},
.....
 "couchdb": {
    "attachment_stream_buffer_size": "4096",
    "changes_doc_ids_optimization_threshold": "100",
    "compaction_log_level": "notice",
    "database_dir": "./data",
    "default_engine": "couch",
    "default_security": "admin_only",
    "file_compression": "snappy",
    "max_dbs_open": "100000",
    "max_document_size": "4194304",
    "os_process_timeout": "5000",
    "users_db_security_editable": "false",
    "uuid": "5b48005e5b5ff19ec5b18e04068ffa40",
    "view_index_dir": "./data"
  }

If we set log.level = info , we are getting compaction information : 

"log": {
    "level": "info",
    "writer": "journald"
  },

Nov 02 19:14:41 xxxxxxx couchdb[2333]: couchdb@demo-ab-1-ro-us-east1-1-1.c.np-store-monarch.internal <0.2104.10> -------- Starting compaction for db "shards/c0000000-dfffffff/item_store-0.1698775231" at 141132
Nov 02 19:14:41 xxxxxxx couchdb[2333]: couchdb@demo-ab-1-ro-us-east1-1-1.c.np-store-monarch.internal <0.2079.10> -------- Starting compaction for db "shards/e0000000-ffffffff/item_store-0.1698775231" at 141325
Nov 02 19:14:41 xxxxxxx couchdb[2333]: couchdb@demo-ab-1-ro-us-east1-1-1.c.np-store-monarch.internal <0.1331.9> -------- Starting compaction for db "shards/80000000-9fffffff/item_store-0.1698775231" at 141371
Nov 02 19:14:41 xxxxxxx couchdb[2333]: couchdb@demo-ab-1-ro-us-east1-1-1.c.np-store-monarch.internal <0.2107.10> -------- Starting compaction for db "shards/60000000-7fffffff/item_store-0.1698775231" at 141524
Nov 02 19:14:41 xxxxxxx couchdb[2333]: couchdb@demo-ab-1-ro-us-east1-1-1.c.np-store-monarch.internal <0.2108.10> -------- Starting compaction for db "shards/20000000-3fffffff/item_store-0.1698775231" at 141585
Nov 02 19:14:41 xxxxxxxx couchdb[2333]: couchdb@demo-ab-1-ro-us-east1-1-1.c.np-store-monarch.internal <0.2084.10> -------- Starting compaction for db "shards/a0000000-bfffffff/item_store-0.1698775231" at 141778
Nov 02 19:14:41 xxxxxxxx couchdb[2333]: couchdb@demo-ab-1-ro-us-east1-1-1.c.np-store-monarch.internal <0.2112.10> -------- Starting compaction for db "shards/00000000-1fffffff/item_store-0.1698775231" at 140895
Nov 02 19:14:41 xxxxxxxx couchdb[2333]: couchdb@demo-ab-1-ro-us-east1-1-1.c.np-store-monarch.internal <0.1310.9> -------- Starting compaction for db "shards/40000000-5fffffff/item_store-0.1698775231" at 141210

Couchdb version : 

{
  "couchdb": "Welcome",
  "version": "3.3.2",

**Comment by nickva** [comment]
That's great @Sdas0000. Yeah, compaction level has to higher or equal than your log level, otherwise you won't see those messages. So for instance if you set your log level to `warning`, then your smoosh and couchdb `compaction_log_level` should be `warning`, `error`, etc to be logged.

Initially your log level was set to `error` but your `compaction_log_level` was at `notice` so you didn't see them. Then, when log level is `info`, you started seeing `notice` messages. `notice` is a big higher than `info` as per:

```erlang
level_to_integer(debug) -> 1;
level_to_integer(info) -> 2;
level_to_integer(notice) -> 3;
level_to_integer(warning) -> 4;
level_to_integer(warn) -> 4;
level_to_integer(error) -> 5;
level_to_integer(err) -> 5;
level_to_integer(critical) -> 6;
level_to_integer(crit) -> 6;
level_to_integer(alert) -> 7;
level_to_integer(emergency) -> 8;
level_to_integer(emerg) -> 8;
```

**Comment by Sdas0000** [comment]
if log level is info or warning , we are already getting compaction info without setting compaction_log_level. There no need to set compaction_log_level. Our issue is we want to keep log as "error" and need compaction information by setting compaction_log_level to info or notice. Basically we are looking what time compaction starts and what time compaction ends .

**Comment by nickva** [comment]
>  Our issue is we want to keep log as "error" and need compaction information by setting compaction_log_level to info or notice

See my comment above: https://github.com/apache/couchdb/issues/4815#issuecomment-1773335087
Try setting both to `error` and see if you see any emitted logs if your log level is `error`

When you set `[log] level = error` you're saying "I don't want to log anything with a level lower than `error`". Then setting `compaction_log_level` to `info` or `warning`, unsurprisingly, won't show up in your logs.

Notice how logging work here: 

https://github.com/apache/couchdb/blob/e9d703c2139cdb695259c814c79f041e6864b81e/src/smoosh/src/smoosh_channel.erl#L168-L172

`compaction_log_level = info` there would effectively call `couch_log:info("....")`, so that won't show up in your log unless you turned you log level all the way down to info.

**Comment by nickva** [comment]
Wonder if that resolved it and if we should close the issue?

**Comment by big-r81** [comment]
I am closing this topic as there has been no response.
