### ISSUE TITLE
Need to limit access to Fauxton UI to localhost, but maintain remote API access.

### ISSUE THREAD

**Issue by estoT1** [apache/couchdb#4827]
Need to limit access to Fauxton UI to localhost, but maintain remote API access.

Do I understand correctly that the Fauxton UI cannot be disabled or limited to localhost separately from the other APIs?
Other than messing with the share/www directory or using a front end proxy to route remote API requests to localhost bind address?

Thank you in advance.

**Comment by rnewson** [comment]
To what end? Fauxton is just calling the API, it has no special privileges.

**Comment by estoT1** [comment]
Thank you for your prompt reply, all feedback is appreciated.
From your reply I infer the Fauxton UI cannot be limited to local host bind address from the APIs?

Short answer: Reducing the attack surface. Everything has its issue and must be patched.
Long answer: To minimize the impact of UI vulnerabilities and assign appropriate maintenance plan/risk response plan for the CouchDB asset group.

Thanking you in advance!
🙇

**Comment by rnewson** [comment]
Got it.

What you can do is remove all the files under the `share/www` directory, and then `/_utils` won't serve up those files. You can then place those files elsewhere and use haproxy/nginx/anything to serve them, putting whatever additional access restrictions you'd like over them.

If you're building from source you can use the `--disable-fauxton` configure option which skips all the build steps for fauxton and skips the crucial final step of copying the output into the `share` directory in the artifact.

**Comment by estoT1** [comment]
Thank you, this fully answers my question! 
Have a great day!
