### ISSUE TITLE
"fabric_rpc:open_revs/3 error:undef" print stack

### ISSUE THREAD

**Issue by sergey-safarov** [apache/couchdb#4891]
## Description

We catch issue when on one node we can see error messages
> [error] 2023-12-02T03:02:01.186324Z couchdb@db0b.example.com <0.10897.1475> -------- rexi_server: from: couchdb@db0a.example.com(<17902.8977.1460>) mfa: fabric_rpc:all_docs/3 exit:timeout [{rexi,init_stream,1,[{file,"src/rexi.erl"},{line,300}]},{rexi,stream2,3,[{file,"src/rexi.erl"},{line,241}]},{fabric_rpc,view_cb,2,[{file,"src/fabric_rpc.erl"},{line,494}]},{couch_mrview,finish_fold,2,[{file,"src/couch_mrview.erl"},{line,672}]},{rexi_server,init_p,3,[{file,"src/rexi_server.erl"},{line,146}]}]

And on other node
> [error] 2023-12-02T04:47:42.328226Z couchdb@db1a.example.com <0.5507.1008> 2cabd72b84 rexi_server: from: couchdb@db0b.example.com(<17533.119.1516>) mfa: fabric_rpc:open_revs/3 error:undef [{fabric_rpc,open_revs,[<<"shards/80000000-ffffffff/account/dd/0f/7499dd7f62950b58fa2c375aef7a-202311.1698796829">>,[{{<<"202311-1261be79-d7ee-44d6-a3fe-671f733bc7c3">>,all},[]},{{<<"202311-117b562b-7257-4656-a414-57f646484eee">>,all},[]},{{<<"202311-117fb1dc-f20f-4469-a363-a8de609579da">>,all},[]} ....

Full error message in the attached file
[couchdb-open_revs_3.log](https://github.com/apache/couchdb/files/13533406/couchdb-open_revs_3.log)

Here call `fabric_rpc:open_revs/3` contains big array of docs_id and do not allow print full stack.
Looks like error hapens after calling 
```sh
curl -s -X POST \
        -H "Content-Type: application/json" \
        -d @/tmp/request_body.json \
        --output - \
        "${COUCHDB_URL}/${db}/_bulk_get?include_docs=true&attachments=true" 
```
Where "request_body.json" contains about 1000 of docs_id.

## Steps to Reproduce

Do not know

## Expected Behaviour

Looks like something goes wrong in the `couch_db:open_doc_revs/3` and function return not expected result.
https://github.com/apache/couchdb/blob/2af3cd811f5c714dc9f23320b797be54f6ed0f14/src/couch/src/couch_db.erl#L353-L363
I think required additional wraper function to catch errors and print stack without docs_id list.

## Your Environment

Used  3 nodes cluster with `apache/couchdb:3.3.2` docker image.
```
[root@ippbx-0b ~]# curl -s http://127.0.0.1:5984| jq
{
  "couchdb": "Welcome",
  "version": "3.3.2",
  "git_sha": "11a234070",
  "uuid": "3d809247857132201f34cd9ead11668f",
  "features": [
    "access-ready",
    "partitioned",
    "pluggable-storage-engines",
    "reshard",
    "scheduler"
  ],
  "vendor": {
    "name": "The Apache Software Foundation"
  }
}
```

* CouchDB version used: 3.3.2
* Browser name and version: do not used
* Operating system and version: Linux CentOS 8 aarch64

## Additional Context

NA

**Comment by sergey-safarov** [comment]
I have set docs_id array to one element in the my curl command and have rerproduced error.
Here is stack error
> [error] 2023-12-02T05:57:21.583678Z couchdb@db1a.example.com <0.19605.1025> 5ddaa614bb rexi_server: from: couchdb@db0b.example.com(<17533.26366.1526>) mfa: fabric_rpc:open_revs/3 error:undef [{fabric_rpc,open_revs,[<<"shards/00000000-7fffffff/account/33/0d/7bfd3f38d7b0e0f2bd6ec392f975-202311.1698796803">>,[{{<<"_design/resources">>,all},[]}],[{user_ctx,{user_ctx,<<"admin">>,[<<"_admin">>],<<"default">>}},attachments]],[]},{rexi_server,init_p,3,[{file,"src/rexi_server.erl"},{line,141}]}]

**Comment by nickva** [comment]
The `fabric_rpc:all_docs/3 exit:timeout` looks a fabric request timeout. Wonder if it would help to increase fabric request_timeout value a bit:

```ini
[fabric]
request_timeout = 60000
```

Maybe make that 90000 (90 sec).

This one `mfa: fabric_rpc:open_revs/3 error:undef` indicates one of the functions in the call is not defined at all. In this case the first candidate might be the the `fabric_rpc:open_revs/3` function itself. That function is new in 3.3.2 so wonder if there is a possibility some of your nodes were upgraded and some were not , and some new nodes were dispatching requests to un-upgraded yet (old) <3.3.2 nodes.

**Comment by sergey-safarov** [comment]
yes, you are correct.
I found used wrong verions on the one node. Here on the two nodes used 3.3.2 and on the one node 3.2.1
Thank you for hint.
Closing.
