### ISSUE TITLE
no match of right hand value

### ISSUE THREAD

**Issue by sergey-safarov** [apache/couchdb#4901]
## Description

In the CouchDB logs I can see messages
> [error] 2023-12-06T17:36:36 [couchdb@db1a.example.com](mailto:couchdb@db1a.example.com) <> -------- CRASH REPORT Process  (<0.26820.435>) with 2 neighbors crashed with reason: no match of right hand value {'EXIT',noproc} at couch_file:pread_binary/2(line:166) <= couch_file:pread_term/2(line:155) <= couch_btree:get_node/2(line:474) <= couch_btree:lookup/3(line:314) <= couch_btree:lookup/2(line:304) <= couch_bt_engine:open_local_docs/2(line:388) <= couch_db:open_doc_int/3(line:1875) <= couch_db:open_doc/3(line:301); initial_call: {couch_index,init,['Argument__1']}, ancestors: [<0.20772.431>], message_queue_len: 0, links: [<0.20772.431>,<0.24852.435>], dictionary: [{io_priority,{view_update,<<"shards/80000000-9fffffff/xxxxxxxxxxxx...">>}}], trap_exit: false, status: running, heap_size: 2586, stack_size: 28, reductions: 6532

Looks like here `no match of right hand value ` need to be hanled.

## Steps to Reproduce

Do not know

## Expected Behaviour

Expected to print human readable error message.

## Your Environment

* CouchDB version used: `apache/couchdb:3.3.2` docker image 
* Browser name and version: do not used
* Operating system and version: CentOS 8 stream

## Additional Context

N/A

**Comment by nickva** [comment]
Thanks @sergey-safarov. That looks like couch_file closed while a view_update write was pending.

**Comment by rnewson** [comment]
noting that we would not 'handle' that unexpected value in the way you might imagine. it is the erlang way to assert the positive case, safe in the knowledge that anything _unexpected_ will cause the erlang process to crash. so, while quite noisy as a long line, that looks like the right error handling.

the real question is why that erlang process crashed while it was in use. there might be other lines in the log file that tell us more.

**Comment by sergey-safarov** [comment]
Here installed 3 node cluster.
For two nodes log for this time range is clean.
Full error log for one node with issue follow.

>[error] 2023-12-06T17:36:36.080062Z couchdb@db1a.example.com <0.26820.435> -------- CRASH REPORT Process  (<0.26820.435>) with 2 neighbors crashed with reason: no match of right hand value {'EXIT',noproc} at couch_file:pread_binary/2(line:166) <= couch_file:pread_term/2(line:155) <= couch_btree:get_node/2(line:474) <= couch_btree:lookup/3(line:314) <= couch_btree:lookup/2(line:304) <= couch_bt_engine:open_local_docs/2(line:388) <= couch_db:open_doc_int/3(line:1875) <= couch_db:open_doc/3(line:301); initial_call: {couch_index,init,['Argument__1']}, ancestors: [<0.20772.431>], message_queue_len: 0, links: [<0.20772.431>,<0.24852.435>], dictionary: [{io_priority,{view_update,<<"shards/80000000-9fffffff/account/8d/b1/c4...">>}}], trap_exit: false, status: running, heap_size: 2586, stack_size: 28, reductions: 6532
[error] 2023-12-06T17:36:36.079813Z couchdb@db1a.example.com <0.26820.435> -------- CRASH REPORT Process  (<0.26820.435>) with 2 neighbors crashed with reason: no match of right hand value {'EXIT',noproc} at couch_file:pread_binary/2(line:166) <= couch_file:pread_term/2(line:155) <= couch_btree:get_node/2(line:474) <= couch_btree:lookup/3(line:314) <= couch_btree:lookup/2(line:304) <= couch_bt_engine:open_local_docs/2(line:388) <= couch_db:open_doc_int/3(line:1875) <= couch_db:open_doc/3(line:301); initial_call: {couch_index,init,['Argument__1']}, ancestors: [<0.20772.431>], message_queue_len: 0, links: [<0.20772.431>,<0.24852.435>], dictionary: [{io_priority,{view_update,<<"shards/80000000-9fffffff/account/8d/b1/c4...">>}}], trap_exit: false, status: running, heap_size: 2586, stack_size: 28, reductions: 6532
    extra: []
     state: {st,"./data",index_server_2,couchdb_indexes_by_sig_2,couchdb_indexes_by_pid_2,couchdb_indexes_by_db_2}
  last msg: redacted
[error] 2023-12-06T17:36:36.082938Z couchdb@db1a.example.com <0.283.0> -------- gen_server index_server_2 terminated with reason: no match of right hand value {'EXIT',noproc} at couch_file:pread_binary/2(line:166) <= couch_file:pread_term/2(line:155) <= couch_btree:get_node/2(line:474) <= couch_btree:lookup/3(line:314) <= couch_btree:lookup/2(line:304) <= couch_bt_engine:open_local_docs/2(line:388) <= couch_db:open_doc_int/3(line:1875) <= couch_db:open_doc/3(line:301) at couch_index_server:handle_info/2(line:207) <= gen_server:try_dispatch/4(line:695) <= gen_server:handle_msg/6(line:771) <= proc_lib:init_p_do_apply/3(line:226)
    extra: []
     state: {st,"./data",index_server_2,couchdb_indexes_by_sig_2,couchdb_indexes_by_pid_2,couchdb_indexes_by_db_2}
  last msg: redacted
[error] 2023-12-06T17:36:36.083228Z couchdb@db1a.example.com <0.283.0> -------- gen_server index_server_2 terminated with reason: no match of right hand value {'EXIT',noproc} at couch_file:pread_binary/2(line:166) <= couch_file:pread_term/2(line:155) <= couch_btree:get_node/2(line:474) <= couch_btree:lookup/3(line:314) <= couch_btree:lookup/2(line:304) <= couch_bt_engine:open_local_docs/2(line:388) <= couch_db:open_doc_int/3(line:1875) <= couch_db:open_doc/3(line:301) at couch_index_server:handle_info/2(line:207) <= gen_server:try_dispatch/4(line:695) <= gen_server:handle_msg/6(line:771) <= proc_lib:init_p_do_apply/3(line:226)
[error] 2023-12-06T17:36:36.083514Z couchdb@db1a.example.com <0.283.0> -------- CRASH REPORT Process index_server_2 (<0.283.0>) with 1 neighbors exited with reason: no match of right hand value {'EXIT',noproc} at couch_file:pread_binary/2(line:166) <= couch_file:pread_term/2(line:155) <= couch_btree:get_node/2(line:474) <= couch_btree:lookup/3(line:314) <= couch_btree:lookup/2(line:304) <= couch_bt_engine:open_local_docs/2(line:388) <= couch_db:open_doc_int/3(line:1875) <= couch_db:open_doc/3(line:301) at couch_index_server:handle_info/2(line:207) <= gen_server:try_dispatch/4(line:695) <= gen_server:handle_msg/6(line:771) <= proc_lib:init_p_do_apply/3(line:226); initial_call: {couch_index_server,init,['Argument__1']}, ancestors: [couch_secondary_services,couch_sup,<0.253.0>], message_queue_len: 0, links: [<0.285.0>,<0.271.0>], dictionary: [], trap_exit: true, status: running, heap_size: 1598, stack_size: 28, reductions: 3560362
[error] 2023-12-06T17:36:36.083784Z couchdb@db1a.example.com <0.283.0> -------- CRASH REPORT Process index_server_2 (<0.283.0>) with 1 neighbors exited with reason: no match of right hand value {'EXIT',noproc} at couch_file:pread_binary/2(line:166) <= couch_file:pread_term/2(line:155) <= couch_btree:get_node/2(line:474) <= couch_btree:lookup/3(line:314) <= couch_btree:lookup/2(line:304) <= couch_bt_engine:open_local_docs/2(line:388) <= couch_db:open_doc_int/3(line:1875) <= couch_db:open_doc/3(line:301) at couch_index_server:handle_info/2(line:207) <= gen_server:try_dispatch/4(line:695) <= gen_server:handle_msg/6(line:771) <= proc_lib:init_p_do_apply/3(line:226); initial_call: {couch_index_server,init,['Argument__1']}, ancestors: [couch_secondary_services,couch_sup,<0.253.0>], message_queue_len: 0, links: [<0.285.0>,<0.271.0>], dictionary: [], trap_exit: true, status: running, heap_size: 1598, stack_size: 28, reductions: 3560362
[error] 2023-12-06T17:36:36.084049Z couchdb@db1a.example.com <0.271.0> -------- Supervisor couch_secondary_services had child index_server_2 started with couch_index_server:start_link(2) at <0.283.0> exit with reason no match of right hand value {'EXIT',noproc} at couch_file:pread_binary/2(line:166) <= couch_file:pread_term/2(line:155) <= couch_btree:get_node/2(line:474) <= couch_btree:lookup/3(line:314) <= couch_btree:lookup/2(line:304) <= couch_bt_engine:open_local_docs/2(line:388) <= couch_db:open_doc_int/3(line:1875) <= couch_db:open_doc/3(line:301) in context child_terminated
[error] 2023-12-06T17:36:36.084248Z couchdb@db1a.example.com <0.271.0> -------- Supervisor couch_secondary_services had child index_server_2 started with couch_index_server:start_link(2) at <0.283.0> exit with reason no match of right hand value {'EXIT',noproc} at couch_file:pread_binary/2(line:166) <= couch_file:pread_term/2(line:155) <= couch_btree:get_node/2(line:474) <= couch_btree:lookup/3(line:314) <= couch_btree:lookup/2(line:304) <= couch_bt_engine:open_local_docs/2(line:388) <= couch_db:open_doc_int/3(line:1875) <= couch_db:open_doc/3(line:301) in context child_terminated

After this timestamp and before CouchDB log is clean.
I also check CouchDB process uptime and found no CouchDB process restart at this time range.

**Comment by sergey-safarov** [comment]
Hello @nickva 
Dev started database refactoring. Now we shrinking CouchDB size and I think now we cannot reproduce this error.
I will close ticket now. If some time we can stable reproduce issue, then will reopen.
