### ISSUE TITLE
Configurable "Special  Character" to allow JSON fieldnames beginning with underscore "_" 

### ISSUE THREAD

**Issue by larrachecoeur** [apache/couchdb#4907]
## Summary
The usage of the underscore character as a prefix for system fields to makes it impossible to store native JSON-Fhir Documents in CouchDb.   
In [FHIR ](https://hl7.org/fhir/) someone decided to use the "_" as a prefix for field-extensions.  

```json
 "birthDate" : "1974-12-25",
  "_birthDate" : {
    "extension" : [{
      "url" : "http://hl7.org/fhir/StructureDefinition/patient-birthTime",
      "valueDateTime" : "1974-12-25T14:35:45-05:00"
    }]
  },
```
## Desired Behaviour
It should be possible to store any valid JSON Object in CouchDb

## Possible Solution
Configurable "Special  Character(s)" to allow JSON fieldnames beginning with underscore "_" .  
So each user can decide what chars to avoid in it's datadefinitions.
Or perhaps a kind of internal masking for such keys

## Additional context

It would be great to store JSON-Fhir objects natively in CouchDb because I think it could be the coolest thinkable storage engine  for it

**Comment by rnewson** [comment]
The restriction only applies at the top-level, so if it's possible to put your FHIR object in a subobject you'll be fine.

Unfortunately it will not be possible to make this configurable for a bunch of reason, not least replication compatibility but also security aspects. The underscore prefix in couchdb is well-established and used for a variety of features.

**Comment by larrachecoeur** [comment]
hello robertwow ! thank you for answering immediately. in between i was out for run and ordered my thaughtsi have no control overat what level the field is set. but i see at least two nice solutions1. wrap it in a persistance-metastructure and send those candidates one level down.2. write an adapter to replace the underscore against something else for persistence and vice versa as the problem only can hapen in im / export usecaseskindly regardsmarcoAm 09.12.2023 19:24 schrieb Robert Newson ***@***.***>:
The restriction only applies at the top-level, so if it's possible to put your FHIR object in a subobject you'll be fine.
Unfortunately it will not be possible to make this configurable for a bunch of reason, not least replication compatibility but also security aspects. The underscore prefix in couchdb is well-established and used for a variety of features.

**Comment by big-r81** [comment]
Closing this, because a workaround was given.
