### ISSUE TITLE
Huge ram usage

### ISSUE THREAD

**Issue by BhasherBEL** [apache/couchdb#4926]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

Running an empty CouchDB on my laptop usage a lot of RAM (around 1.5GB), even without any specific configuration. On any other support I was able to test, it was way more small.

## Steps to Reproduce

Dockerfile:
```Dockerfile
FROM couchdb:latest

ADD local.ini /opt/couchdb/etc
```
docker-compose:
```yaml
services:
  db:
    build:
      context: .
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
```
`docker stats`:
```sh
7ecf938cb065   src-scapp-history-db-1           0.06%     1.552GiB / 23.15GiB   6.70%     8.87kB / 715B     69.6kB / 8.19kB   42
73fd375e5930   src-scapp-cart-db-1              0.12%     1.559GiB / 23.15GiB   6.73%     9.08kB / 715B     81.9kB / 8.19kB   42
9742f9db97f6   src-scapp-recommendations-db-1   0.06%     1.55GiB / 23.15GiB    6.69%     4.8kB / 769B      69.6kB / 8.19kB   42
c08de0592197   src-scapp-products-db-1          0.08%     1.557GiB / 23.15GiB   6.73%     8.83kB / 715B     69.6kB / 8.19kB   42
45db3f937f1c   src-scapp-logging-db-1           0.10%     1.559GiB / 23.15GiB   6.73%     11.5kB / 5.84kB   164kB / 8.19kB    51
```
(in fact, I'm using 5 instances of couchDB, all with exactly the same Dockerfile and docker-compose. The only difference is the db name in docker-compose)

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

I was expecting way smaller ram usage from each CouchDB instance.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

```json
{"couchdb":"Welcome","version":"3.3.3","git_sha":"40afbcfc7","uuid":"ef5f3f8a5617f9722e26959adb163522","features":["access-ready","partitioned","pluggable-storage-engines","reshard","scheduler"],"vendor":{"name":"The Apache Software Foundation"}}
```

* CouchDB version used: 3.3.3
* Browser name and version: Firefox 118.0.2 (64-bit)
* Operating system and version: Linux 6.5.7-arch1-1 # 1 SMP PREEMPT_DYNAMIC Tue, 10 Oct 2023 21:10:21 +0000 x86_64 GNU/Linux

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by big-r81** [comment]
Hey,

according to [this](https://docs.docker.com/engine/reference/commandline/stats/), I would say that the output of this command is the memory usage of the container, not from couchdb.

**Comment by BhasherBEL** [comment]
Indeed, but it's the official CouchDB image, that only run CouchDB.

**Comment by big-r81** [comment]
> Indeed, but it's the official CouchDB image, that only run CouchDB.
It is provided for convience for the user.
> In such cases, is there a way to extract the usage of CouchDB specifically, inside the CouchDB container ?
I don't know what you mean. What are you trying to achive?

**Comment by big-r81** [comment]
I am closing this topic as there has been no response.

**Comment by joan-morera** [comment]
A bit late, but just in case anyone is still trying to debug this issue.

This has been happening to me since I updated to *Debian Trixie*. Noticing the inflating process was *beam.smp*, I did a quick look and came upon [this issue](https://github.com/teslamate-org/teslamate/discussions/3045) and it's[ solution ](https://github.com/teslamate-org/teslamate/discussions/3045#discussioncomment-8757861) on the teslamate repo, with the core problem being on a change done on the docker side related to the max limit of open files being unlimited.

Adding their proposed solution to the docker compose file or run string brings back the memory use to normal levels, tested with `couchdb:3.5.0`.

```    
    ulimits:
      nofile: 65536
```

**Comment by nickva** [comment]
Thank you @joan-morera for reaching out with a solution. That's an interesting corner case.

I made sure to at least add a note to the docs https://github.com/apache/couchdb/pull/5575.

We already had mention of how to mitigate that but a specific reference to docker was missing.
