### ISSUE TITLE
Better way to follow progress on 3.0

### ISSUE THREAD

**Issue by natew** [apache/couchdb#493]
Hey, new to Couch and building an app with it for the first time. Putting together a fancy stack that glues a lot of cool new technology, with Couch/Pouch as the db.

I've been diving into Couch for the last few weeks pretty intensely and am glad to see despite relative lack of hype in the communities I follow, it seems to be making steady progress.

I've just finished reading [this thread](https://lists.apache.org/thread.html/09a5686bca8049010b82796cc0fe99ef27aed4983a3f02fd6956259f@%3Cdev.couchdb.apache.org%3E) for the second time after spending a few weeks working on a test app, and understand a hell of a lot more of whats being talked about now.

I would love to be able to follow development here a bit better. My interests are in a few things coming up but primarily the improved document permissions system for which without I wouldn't be able to build most apps I think would be valuable.

After browsing JIRA/Github I don't see any places to follow most of these points brought up. Would be really nice to be able to subscribe to a Github issue for each of the main bullet points.

Also, JIRA seems to have some information on 3.0, 4.0, etc, but then there are active comments here on PR's. Any chance of moving roadmap stuff into github?

Keep up the great work!

**Comment by wohali** [comment]
Hi @natew, you caught us in the switchover between JIRA and GitHub Issues. If you follow our dev@couchdb.apache.org mailing list you'll see more news on this in the coming weeks.

I'm going to close this out for now - but please don't hesitate to ask questions if you have any on the mailing lists!
