### ISSUE TITLE
Connection refused in Macbook M1

### ISSUE THREAD

**Issue by ckarapapas** [apache/couchdb#4930]
Hi, 
after installing the latest version on my M1 macbook i get repetedly a "connection refused" on my browser and i cannot connect to the admin page.
Here are some logs,

[error] 2023-12-26T10:21:12.309696Z couchdb@localhost <0.258.0> -------- CRASH REPORT Process  (<0.258.0>) with 0 neighbors exited with reason: {{shutdown,{failed_to_start_child,couch_primary_services,{shutdown,{failed_to_start_child,couch_password_hasher,{undef,[{crypto,strong_rand_bytes,[16],[]},{couch_uuids,random,0,[{file,"src/couch_uuids.erl"},{line,40}]},{couch_passwords,hash_admin_password,2,[{file,"src/couch_passwords.erl"},{line,50}]},{couch_password_hasher,'-hash_admin_passwords/1-fun-0-',2,[{file,"src/couch_password_hasher.erl"},{line,69}]},{lists,foreach_1,2,[{file,"lists.erl"},{line,1686}]},{couch_password_hasher,init,...},...]}}}}},...} at application_master:init/4(line:142) <= proc_lib:init_p_do_apply/3(line:241); initial_call: {application_master,init,['Argument__1','Argument__2',...]}, ancestors: [<0.257.0>], message_queue_len: 1, links: [<0.257.0>,<0.16.0>], dictionary: [], trap_exit: true, status: running, heap_size: 987, stack_size: 28, reductions: 159
[error] 2023-12-26T10:21:12.309744Z couchdb@localhost <0.258.0> -------- CRASH REPORT Process  (<0.258.0>) with 0 neighbors exited with reason: {{shutdown,{failed_to_start_child,couch_primary_services,{shutdown,{failed_to_start_child,couch_password_hasher,{undef,[{crypto,strong_rand_bytes,[16],[]},{couch_uuids,random,0,[{file,"src/couch_uuids.erl"},{line,40}]},{couch_passwords,hash_admin_password,2,[{file,"src/couch_passwords.erl"},{line,50}]},{couch_password_hasher,'-hash_admin_passwords/1-fun-0-',2,[{file,"src/couch_password_hasher.erl"},{line,69}]},{lists,foreach_1,2,[{file,"lists.erl"},{line,1686}]},{couch_password_hasher,init,...},...]}}}}},...} at application_master:init/4(line:142) <= proc_lib:init_p_do_apply/3(line:241); initial_call: {application_master,init,['Argument__1','Argument__2',...]}, ancestors: [<0.257.0>], message_queue_len: 1, links: [<0.257.0>,<0.16.0>], dictionary: [], trap_exit: true, status: running, heap_size: 987, stack_size: 28, reductions: 159
[info] 2023-12-26T10:21:12.309779Z couchdb@localhost <0.16.0> -------- Application couch exited with reason: {{shutdown,{failed_to_start_child,couch_primary_services,{shutdown,{failed_to_start_child,couch_password_hasher,{undef,[{crypto,strong_rand_bytes,[16],[]},{couch_uuids,random,0,[{file,"src/couch_uuids.erl"},{line,40}]},{couch_passwords,hash_admin_password,2,[{file,"src/couch_passwords.erl"},{line,50}]},{couch_password_hasher,'-hash_admin_passwords/1-fun-0-',2,[{file,"src/couch_password_hasher.erl"},{line,69}]},{lists,foreach_1,2,[{file,"lists.erl"},{line,1686}]},{couch_password_hasher,init,...},...]}}}}},...}
[info] 2023-12-26T10:21:12.309814Z couchdb@localhost <0.16.0> -------- Application couch exited with reason: {{shutdown,{failed_to_start_child,couch_primary_services,{shutdown,{failed_to_start_child,couch_password_hasher,{undef,[{crypto,strong_rand_bytes,[16],[]},{couch_uuids,random,0,[{file,"src/couch_uuids.erl"},{line,40}]},{couch_passwords,hash_admin_password,2,[{file,"src/couch_passwords.erl"},{line,50}]},{couch_password_hasher,'-hash_admin_passwords/1-fun-0-',2,[{file,"src/couch_password_hasher.erl"},{line,69}]},{lists,foreach_1,2,[{file,"lists.erl"},{line,1686}]},{couch_password_hasher,init,...},...]}}}}},...}
[info] 2023-12-26T10:21:25.060975Z couchdb@localhost <0.259.0> -------- Preflight check: Checking For Monsters

[info] 2023-12-26T10:21:25.060999Z couchdb@localhost <0.259.0> -------- Preflight check: Asserting Admin Account

[info] 2023-12-26T10:21:25.062153Z couchdb@localhost <0.259.0> -------- Apache CouchDB 3.3.3 is starting.

[info] 2023-12-26T10:21:25.062173Z couchdb@localhost <0.260.0> -------- Starting couch_sup
[error] 2023-12-26T10:21:25.066936Z couchdb@localhost <0.265.0> -------- Unable to load crypto library. Failed with error:
"load_failed, Failed to load NIF library: 'dlopen(/private/var/folders/_k/6qw01kfj6t1b89ctrc4rp_h80000gn/T/AppTranslocation/2DBC0BAB-AB87-44B2-B975-3FFDA52F8F23/d/Apache CouchDB.app/Contents/Resources/couchdbx-core/bin/../lib/crypto-5.2/priv/lib/crypto.so, 0x0002): Library not loaded: /opt/homebrew/opt/openssl@3/lib/libcrypto.3.dylib
  Referenced from: <D82F0F67-2F3C-3172-80A8-F308947F9009> /private/var/folders/_k/6qw01kfj6t1b89ctrc4rp_h80000gn/T/AppTranslocation/2DBC0BAB-AB87-44B2-B975-3FFDA52F8F23/d/Apache CouchDB.app/Contents/Resources/couchdbx-core/lib/crypto-5.2/priv/lib/crypto.so
  Reason: tried: '/opt/homebrew/opt/openssl@3/lib/libcrypto.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/openssl@3/lib/libcrypto.3.dylib' (no such file), '/opt/homebrew/opt/openssl@3/lib/libcrypto.3.dylib' (no such file), '/usr/lib/libcrypto.3.dylib' (no such file, not in dyld cache)'"
OpenSSL might not be installed on this system.

[error] 2023-12-26T10:21:25.067209Z couchdb@localhost <0.265.0> -------- Unable to load crypto library. Failed with error:
"load_failed, Failed to load NIF library: 'dlopen(/private/var/folders/_k/6qw01kfj6t1b89ctrc4rp_h80000gn/T/AppTranslocation/2DBC0BAB-AB87-44B2-B975-3FFDA52F8F23/d/Apache CouchDB.app/Contents/Resources/couchdbx-core/bin/../lib/crypto-5.2/priv/lib/crypto.so, 0x0002): Library not loaded: /opt/homebrew/opt/openssl@3/lib/libcrypto.3.dylib
  Referenced from: <D82F0F67-2F3C-3172-80A8-F308947F9009> /private/var/folders/_k/6qw01kfj6t1b89ctrc4rp_h80000gn/T/AppTranslocation/2DBC0BAB-AB87-44B2-B975-3FFDA52F8F23/d/Apache CouchDB.app/Contents/Resources/couchdbx-core/lib/crypto-5.2/priv/lib/crypto.so
  Reason: tried: '/opt/homebrew/opt/openssl@3/lib/libcrypto.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/openssl@3/lib/libcrypto.3.dylib' (no such file), '/opt/homebrew/opt/openssl@3/lib/libcrypto.3.dylib' (no such file), '/usr/lib/libcrypto.3.dylib' (no such file, not in dyld cache)'"
OpenSSL might not be installed on this system.

[warning] 2023-12-26T10:21:25.067400Z couchdb@localhost <0.266.0> -------- The on_load function for module crypto returned:
{error,{load_failed,"Failed to load NIF library: 'dlopen(/private/var/folders/_k/6qw01kfj6t1b89ctrc4rp_h80000gn/T/AppTranslocation/2DBC0BAB-AB87-44B2-B975-3FFDA52F8F23/d/Apache CouchDB.app/Contents/Resources/couchdbx-core/bin/../lib/crypto-5.2/priv/lib/crypto.so, 0x0002): Library not loaded: /opt/homebrew/opt/openssl@3/lib/libcrypto.3.dylib\n  Referenced from: <D82F0F67-2F3C-3172-80A8-F308947F9009> /private/var/folders/_k/6qw01kfj6t1b89ctrc4rp_h80000gn/T/AppTranslocation/2DBC0BAB-AB87-44B2-B975-3FFDA52F8F23/d/Apache CouchDB.app/Contents/Resources/couchdbx-core/lib/crypto-5.2/priv/lib/crypto.so\n  Reason: tried: '/opt/homebrew/opt/openssl@3/lib/libcrypto.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/openssl@3/lib/libcrypto.3.dylib' (no such file), '/opt/homebrew/opt/openssl@3/lib/libcrypto.3.dylib' (no such file), '/usr/lib/libcrypto.3.dylib' (no such file, not in dyld cache)'"}}

[warning] 2023-12-26T10:21:25.067438Z couchdb@localhost <0.266.0> -------- The on_load function for module crypto returned:
{error,{load_failed,"Failed to load NIF library: 'dlopen(/private/var/folders/_k/6qw01kfj6t1b89ctrc4rp_h80000gn/T/AppTranslocation/2DBC0BAB-AB87-44B2-B975-3FFDA52F8F23/d/Apache CouchDB.app/Contents/Resources/couchdbx-core/bin/../lib/crypto-5.2/priv/lib/crypto.so, 0x0002): Library not loaded: /opt/homebrew/opt/openssl@3/lib/libcrypto.3.dylib\n  Referenced from: <D82F0F67-2F3C-3172-80A8-F308947F9009> /private/var/folders/_k/6qw01kfj6t1b89ctrc4rp_h80000gn/T/AppTranslocation/2DBC0BAB-AB87-44B2-B975-3FFDA52F8F23/d/Apache CouchDB.app/Contents/Resources/couchdbx-core/lib/crypto-5.2/priv/lib/crypto.so\n  Reason: tried: '/opt/homebrew/opt/openssl@3/lib/libcrypto.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/openssl@3/lib/libcrypto.3.dylib' (no such file), '/opt/homebrew/opt/openssl@3/lib/libcrypto.3.dylib' (no such file), '/usr/lib/libcrypto.3.dylib' (no such file, not in dyld cache)'"}}

[error] 2023-12-26T10:21:25.067497Z couchdb@localhost <0.264.0> -------- CRASH REPORT Process  (<0.264.0>) with 0 neighbors crashed with reason: call to undefined function crypto:strong_rand_bytes(16) at couch_uuids:random/0(line:40) <= couch_passwords:hash_admin_password/2(line:50) <= couch_password_hasher:'-hash_admin_passwords/1-fun-0-'/2(line:69) <= lists:foreach_1/2(line:1686) <= couch_password_hasher:init/1(line:47) <= gen_server:init_it/2(line:962) <= gen_server:init_it/6(line:917); initial_call: {couch_password_hasher,init,['Argument__1']}, ancestors: [couch_primary_services,couch_sup,<0.259.0>], message_queue_len: 0, links: [<0.262.0>], dictionary: [], trap_exit: false, status: running, heap_size: 1598, stack_size: 28, reductions: 421
[error] 2023-12-26T10:21:25.067544Z couchdb@localhost <0.259.0> -------- Error starting Apache CouchDB:

    {error,{shutdown,{failed_to_start_child,couch_primary_services,{shutdown,{failed_to_start_child,couch_password_hasher,{undef,[{crypto,strong_rand_bytes,[16],[]},{couch_uuids,random,0,[{file,"src/couch_uuids.erl"},{line,40}]},{couch_passwords,hash_admin_password,2,[{file,"src/couch_passwords.erl"},{line,50}]},{couch_password_hasher,'-hash_admin_passwords/1-fun-0-',2,[{file,"src/couch_password_hasher.erl"},{line,69}]},{lists,foreach_1,2,[{file,"lists.erl"},{line,1686}]},{couch_password_hasher,init,1,[{file,"src/couch_password_hasher.erl"},{line,47}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,962}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,917}]}]}}}}}}

[error] 2023-12-26T10:21:25.067590Z couchdb@localhost <0.264.0> -------- CRASH REPORT Process  (<0.264.0>) with 0 neighbors crashed with reason: call to undefined function crypto:strong_rand_bytes(16) at couch_uuids:random/0(line:40) <= couch_passwords:hash_admin_password/2(line:50) <= couch_password_hasher:'-hash_admin_passwords/1-fun-0-'/2(line:69) <= lists:foreach_1/2(line:1686) <= couch_password_hasher:init/1(line:47) <= gen_server:init_it/2(line:962) <= gen_server:init_it/6(line:917); initial_call: {couch_password_hasher,init,['Argument__1']}, ancestors: [couch_primary_services,couch_sup,<0.259.0>], message_queue_len: 0, links: [<0.262.0>], dictionary: [], trap_exit: false, status: running, heap_size: 1598, stack_size: 28, reductions: 421
[error] 2023-12-26T10:21:25.067710Z couchdb@localhost <0.262.0> -------- Supervisor couch_primary_services had child couch_password_hasher started with couch_password_hasher:start_link() at undefined exit with reason call to undefined function crypto:strong_rand_bytes(16) at couch_uuids:random/0(line:40) <= couch_passwords:hash_admin_password/2(line:50) <= couch_password_hasher:'-hash_admin_passwords/1-fun-0-'/2(line:69) <= lists:foreach_1/2(line:1686) <= couch_password_hasher:init/1(line:47) <= gen_server:init_it/2(line:962) <= gen_server:init_it/6(line:917) in context start_error
[error] 2023-12-26T10:21:25.067753Z couchdb@localhost <0.262.0> -------- Supervisor couch_primary_services had child couch_password_hasher started with couch_password_hasher:start_link() at undefined exit with reason call to undefined function crypto:strong_rand_bytes(16) at couch_uuids:random/0(line:40) <= couch_passwords:hash_admin_password/2(line:50) <= couch_password_hasher:'-hash_admin_passwords/1-fun-0-'/2(line:69) <= lists:foreach_1/2(line:1686) <= couch_password_hasher:init/1(line:47) <= gen_server:init_it/2(line:962) <= gen_server:init_it/6(line:917) in context start_error
[error] 2023-12-26T10:21:25.067814Z couchdb@localhost <0.260.0> -------- Supervisor couch_sup had child couch_primary_services started with couch_primary_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,couch_password_hasher,{undef,[{crypto,strong_rand_bytes,[16],[]},{couch_uuids,random,0,[{file,"src/couch_uuids.erl"},{line,40}]},{couch_passwords,hash_admin_password,2,[{file,"src/couch_passwords.erl"},{line,50}]},{couch_password_hasher,'-hash_admin_passwords/1-fun-0-',2,[{file,"src/couch_password_hasher.erl"},{line,69}]},{lists,foreach_1,2,[{file,"lists.erl"},{line,1686}]},{couch_password_hasher,init,1,[{file,"src/couch_password_hasher.erl"},{line,47}]},{gen_server,...},...]}}} in context start_error
[error] 2023-12-26T10:21:25.067872Z couchdb@localhost <0.260.0> -------- Supervisor couch_sup had child couch_primary_services started with couch_primary_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,couch_password_hasher,{undef,[{crypto,strong_rand_bytes,[16],[]},{couch_uuids,random,0,[{file,"src/couch_uuids.erl"},{line,40}]},{couch_passwords,hash_admin_password,2,[{file,"src/couch_passwords.erl"},{line,50}]},{couch_password_hasher,'-hash_admin_passwords/1-fun-0-',2,[{file,"src/couch_password_hasher.erl"},{line,69}]},{lists,foreach_1,2,[{file,"lists.erl"},{line,1686}]},{couch_password_hasher,init,1,[{file,"src/couch_password_hasher.erl"},{line,47}]},{gen_server,...},...]}}} in context start_error
[error] 2023-12-26T10:21:25.067918Z couchdb@localhost <0.258.0> -------- CRASH REPORT Process  (<0.258.0>) with 0 neighbors exited with reason: {{shutdown,{failed_to_start_child,couch_primary_services,{shutdown,{failed_to_start_child,couch_password_hasher,{undef,[{crypto,strong_rand_bytes,[16],[]},{couch_uuids,random,0,[{file,"src/couch_uuids.erl"},{line,40}]},{couch_passwords,hash_admin_password,2,[{file,"src/couch_passwords.erl"},{line,50}]},{couch_password_hasher,'-hash_admin_passwords/1-fun-0-',2,[{file,"src/couch_password_hasher.erl"},{line,69}]},{lists,foreach_1,2,[{file,"lists.erl"},{line,1686}]},{couch_password_hasher,init,...},...]}}}}},...} at application_master:init/4(line:142) <= proc_lib:init_p_do_apply/3(line:241); initial_call: {application_master,init,['Argument__1','Argument__2',...]}, ancestors: [<0.257.0>], message_queue_len: 1, links: [<0.257.0>,<0.16.0>], dictionary: [], trap_exit: true, status: running, heap_size: 987, stack_size: 28, reductions: 159
[error] 2023-12-26T10:21:25.067979Z couchdb@localhost <0.258.0> -------- CRASH REPORT Process  (<0.258.0>) with 0 neighbors exited with reason: {{shutdown,{failed_to_start_child,couch_primary_services,{shutdown,{failed_to_start_child,couch_password_hasher,{undef,[{crypto,strong_rand_bytes,[16],[]},{couch_uuids,random,0,[{file,"src/couch_uuids.erl"},{line,40}]},{couch_passwords,hash_admin_password,2,[{file,"src/couch_passwords.erl"},{line,50}]},{couch_password_hasher,'-hash_admin_passwords/1-fun-0-',2,[{file,"src/couch_password_hasher.erl"},{line,69}]},{lists,foreach_1,2,[{file,"lists.erl"},{line,1686}]},{couch_password_hasher,init,...},...]}}}}},...} at application_master:init/4(line:142) <= proc_lib:init_p_do_apply/3(line:241); initial_call: {application_master,init,['Argument__1','Argument__2',...]}, ancestors: [<0.257.0>], message_queue_len: 1, links: [<0.257.0>,<0.16.0>], dictionary: [], trap_exit: true, status: running, heap_size: 987, stack_size: 28, reductions: 159
[info] 2023-12-26T10:21:25.068033Z couchdb@localhost <0.16.0> -------- Application couch exited with reason: {{shutdown,{failed_to_start_child,couch_primary_services,{shutdown,{failed_to_start_child,couch_password_hasher,{undef,[{crypto,strong_rand_bytes,[16],[]},{couch_uuids,random,0,[{file,"src/couch_uuids.erl"},{line,40}]},{couch_passwords,hash_admin_password,2,[{file,"src/couch_passwords.erl"},{line,50}]},{couch_password_hasher,'-hash_admin_passwords/1-fun-0-',2,[{file,"src/couch_password_hasher.erl"},{line,69}]},{lists,foreach_1,2,[{file,"lists.erl"},{line,1686}]},{couch_password_hasher,init,...},...]}}}}},...}
[info] 2023-12-26T10:21:25.068066Z couchdb@localhost <0.16.0> -------- Application couch exited with reason: {{shutdown,{failed_to_start_child,couch_primary_services,{shutdown,{failed_to_start_child,couch_password_hasher,{undef,[{crypto,strong_rand_bytes,[16],[]},{couch_uuids,random,0,[{file,"src/couch_uuids.erl"},{line,40}]},{couch_passwords,hash_admin_password,2,[{file,"src/couch_passwords.erl"},{line,50}]},{couch_password_hasher,'-hash_admin_passwords/1-fun-0-',2,[{file,"src/couch_password_hasher.erl"},{line,69}]},{lists,foreach_1,2,[{file,"lists.erl"},{line,1686}]},{couch_password_hasher,init,...},...]}}}}},...}
 
Thanks in advance

**Comment by jaydoane** [comment]
I think the relevant part of your error logs is:

> Reason: tried: '/opt/homebrew/opt/openssl@3/lib/libcrypto.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/openssl@3/lib/libcrypto.3.dylib' (no such file), '/opt/homebrew/opt/openssl@3/lib/libcrypto.3.dylib' (no such file), '/usr/lib/libcrypto.3.dylib' (no such file, not in dyld cache)'"
OpenSSL might not be installed on this system.

Please make sure you have OpenSSL installed. You can read more about that dependency [here](https://www.erlang.org/doc/man/crypto_app#dependencies).

**Comment by big-r81** [comment]
Close this topic, a solution was given.
