### ISSUE TITLE
Database not reachable after snap auto refresh to 3.3.3

### ISSUE THREAD

**Issue by ParkSeungwon** [apache/couchdb#4939]
latest/stable:    3.3.3 2024-01-02 (15) 47MB -
  latest/candidate: 3.3.3 2024-01-02 (15) 47MB -
  latest/beta:      ↑
  latest/edge:      ↑
  3.x/stable:       3.3.3 2024-01-02 (15) 47MB -
  3.x/candidate:    ↑
  3.x/beta:         ↑
  3.x/edge:         ↑
  2.x/stable:       2.3.1 2020-03-18  (5) 46MB -
  2.x/candidate:    ↑
  2.x/beta:         ↑
  2.x/edge:         ↑
installed:          3.3.3            (15) 47MB -

My system suddenly didn't work..(ubuntu server snap. couchdb was not responding)
 I found that couchdb version was refreshed today.. (How can I stop snap auto refresh? )
I even couldn't access fauxton at :5984/_utils.
After I revert back to 3.1.1. I can access databases with :5984/_utils now.
but, still server is not responding to my app.
python-couchdb cannot access database.. I think my former version was couchdb 2.
but snap only provide 3.1.1 and 3.3.3.
How can I go back to 2.3.1?
Or what package should I use to access the DB? Should I rewrite them?

**Comment by sklassen** [comment]
execute `sudo snap revert` that should restore your previous snap.

**Comment by ParkSeungwon** [comment]
after rebooting, it works fine with 3.1.1. thanks...

**Comment by big-r81** [comment]
I’m updating the tracks at snapcraft to only allow minor updates automatically.

**Comment by ErikVerheul** [comment]
I experienced the same problem. To solve it check the -setcookie parameter in /opt/couchdb/etc/vm.args. Generate a long string with openssl rand -hex 32 or so and add it to your config.
