### ISSUE TITLE
Document revision value requirement when updating

### ISSUE THREAD

**Issue by Aaron-Zhao** [apache/couchdb#498]
It seems like CouchDB 2 no longer requires revision value for updating an existing document (PUT /{db}/{docid}). It always updates the newest version of the document.

But attaching a file to a document (PUT /{db}/{docid}/{attname}) still requires a revision value.

Can we in the future just default rev to the newest version for attachments?

**Comment by wohali** [comment]
I think you are mistaken in your belief that CouchDB no longer requires the revision value for updating a document.

```
$ curl -X PUT localhost:5984/foo
{"ok":true}
$ curl -X PUT localhost:5984/foo/bar -d '{"joan": "is great"}'
{"ok":true,"id":"bar","rev":"1-9b0890fa11b66dc9f0cc4917e11553d1"}
$ curl localhost:5984/foo/bar
{"_id":"bar","_rev":"1-9b0890fa11b66dc9f0cc4917e11553d1","joan":"is great"}
$ curl -X PUT localhost:5984/foo/bar -d '{"joan": "is still great"}'
{"error":"conflict","reason":"Document update conflict."}
```

**Comment by wohali** [comment]
Because CouchDB is eventually consistent by design - our entire replication structure (*the* key feature of CouchDB) requires revisions to be part of the API to ensure consistency. You can learn more about this at http://guide.couchdb.org/draft/consistency.html

**Comment by Aaron-Zhao** [comment]
Thanks for the info! That's helpful.
