### ISSUE TITLE
until parameter for change request

### ISSUE THREAD

**Issue by ronag** [apache/couchdb#4995]
Would be nice to have an `until` parameter for change feeds that work similar to `since` but instead of start, it specifies the end of the feed, e.g.:

`/{db}/_changes?since=0&until=now`

**Comment by rnewson** [comment]
until=now is the default  behaviour (that is, if you don't ask for feed=continuous)

For any other value of `until` there is no solution, as you cannot construct a future update sequence string externally.

**Comment by ronag** [comment]
> until=now is the default behaviour (that is, if you don't ask for feed=continuous)

Exactly, would like to have it for `feed=continuous` which is much more efficient than normal.

**Comment by rnewson** [comment]
feed=continuous is as "efficient" as normal mode, it's the same code except it keeps reopening the database as it changes and sends the new updates. there is still no way for you to construct a future update sequence, and thus there's nothing you could pass as the `until` parameter. 

I do not understand your need.

**Comment by ronag** [comment]
normal feeds require several thousand http requests while continuous is a single streaming request. There is a significant difference in both overhead and latency. Even with tricks like keep alive and pipelining (I'm unsure how well those are actually supported).

**Comment by rnewson** [comment]
keepalive (multiple sequential send req, read resps on the same tcp connection) is supported (and encouraged!). pipelining (sending multiple requests before reading the first response) is also supported.

I still don't see how you could know what value to pass to `until`. Have you seen that the changes endpoint supports a `limit` parameter? perhaps that is what you mean (`from here, return the next 10,000 updates and wait until they happen)

**Comment by ronag** [comment]
> keepalive (multiple sequential send req, read resps on the same tcp connection) is supported (and encouraged!). pipelining (sending multiple requests before reading the first response) is also supported.

That's great! However, from our tests it's still a lot slower than a continuous feed in addition to that it takes more memory (at least on client side). Especially when running in clustered mode.

Feel free to close if you still don't think it makes sense.

**Comment by rnewson** [comment]
(obviously you'd also need to strip the comma to process "normal" format as a stream but this is simple.)

**Comment by ronag** [comment]
That's a good point!
