### ISSUE TITLE
Nouveau Availability

### ISSUE THREAD

**Issue by Sliosh** [apache/couchdb#5002]
Hello.

We are planing to deploy CouchDB to all our customers sites. Because of that we are evaluating how we will rollout couchdb. It would be good to know when we can expect version 3.4.0. Is there any possible timeframe known a this point in time? And will nouveau be included (as stable) in 3.4.0?

Thanks for your help.

**Comment by nickva** [comment]
Nouveau will be included in 3.4.0 release.

There is not  set timeframe, but currently the main thing we're waiting on is review of the nouveau deb packaging PR in https://github.com/apache/couchdb-pkg/pull/125. I am planning on reviewing this week or weekend.

**Comment by Sliosh** [comment]
Thanks. This sounds good to me. I have a second question about Nouveau. We want to have one or more couchdb nodes for our customer in different offices from our customer. We need to sync the data between the nodes, and everything should still work for every node, even if the Network between the nodes is lost. The should get synced after network restoration. We use clustering with n = NODE_COUNT and q = 1, so that we get all data on every node. This seems to work as expected, but Nouveau doesen't work if any node is down. We get the following message if a node (In this example `couchdb@deacsrewdbbt1.customer.de`) is down: 
``` "error": "badrecord",
  "reason": "[{{shard,<<\"shards/00000000-ffffffff/foo.1710344337\">>,\n         '[couchdb@deacsrewdbbt21.elara-gmbh.de](mailto:couchdb@deacsrewdbbt2.elara-gmbh.de)',<<\"foo\">>,\n         [0,4294967295],\n         #Ref<0.2580037850.2056257537.222954>,\n         [{props,[]}]},\n  nil},\n {{shard,<<\"shards/00000000-ffffffff/foo.1710344337\">>,\n         '[couchdb@deacsrewdbbt3.customer.de](mailto:couchdb@deacsrewdbbt31.customer.de)',<<\"foo\">>,\n         [0,4294967295],\n         #Ref<0.2580037850.2056257537.222953>,\n         [{props,[]}]},\n  nil}]",

 "ref": 3715306381 
``` 

Is it not supported by Nouveau to work only with the local node in this case, or do i need to change something for this to work?

Thanks.

**Comment by rnewson** [comment]
Nouveau will be marked EXPERIMENTAL in couchdb 3.4.0 as we gather feedback from the community. 

I certainly expect fault-tolerance from Nouveau so will look into your finding this week.

**Comment by rnewson** [comment]
as an aside, we strongly recommend that couchdb clusters do not span locations (offices in your case). the nodes of any given cluster should be very close together (<1ms ping time). For your use case we'd recommend a cluster per office and use of the http replication facility to sync data between offices.

**Comment by rnewson** [comment]
further aside, you don't have to have a nouveau node for each couchdb node, you can safely point multiple couchdb nodes at the same nouveau node. whether this is better or worse for you will depend on what you're doing and the performance specs of the server(s) nouveau is running on. one-to-one is a sensible place to start, though.

**Comment by rnewson** [comment]
I figured it out and have posted a PR to fix the fault tolerance.

**Comment by rnewson** [comment]
our slack is the best place for this kind of chat (couchdb.slack.com).

a couple of notes;

1) the 'r' and 'w' fields under cluster do nothing, they are no longer used by the code (for several years now)
2) erlang clusters (and therefore also couchdb clusters) need low latency between them, and reliable networking too. if these conditions aren't met we recommend separate clusters that use replication to push data around, as our replication system is tolerant of high latency and unreliable networking.

**Comment by rnewson** [comment]
oh, and 3) yes, you would need to delete databases within each cluster separately, as db deletion is not propagated by replication.

**Comment by rnewson** [comment]
3.4.1 is out now with nouveau (marked `EXPERIMENTAL`).
