### ISSUE TITLE
"apache.jfrog.io" trial expired

### ISSUE THREAD

**Issue by jmta** [apache/couchdb#5010]
The apache jfrog instance is down meaning it is not possible to download artifacts from the server

## Description
As above

## Steps to Reproduce

Open https://apache.jfrog.io/artifactory/couchdb-deb/ in a browser, this gives:

Time flies when you’re having fun.
Your 14-day trial may be over, but you have options!
Need help choosing the right subscription or additional time on your trial? Just let us know and a DevOps expert will reach out to assist you.

## Expected Behaviour

Artifactory is available at the documented URL.

## Your Environment

Irrelevant

## Additional Context
Exactly the same issue as #4489 and exactly the same day in the year...

**Comment by nickva** [comment]
Thanks for your report. ASF infra is aware and are trying to restore the service.

**Comment by Lorenzo10122002** [comment]
Hello, are there other ways to install couchDB while the issue gets fixed? I'm trying to set up a server but i get an error because of this. Thank you

**Comment by lore-10** [comment]
Hello, are there other ways to install couchDB while the issue gets fixed? I'm trying to set up a server but i get an error because of this. Thank you

**Comment by big-r81** [comment]
All should work again!
