### ISSUE TITLE
Requiring support for leading wildcard search for nouveau

### ISSUE THREAD

**Issue by GMishx** [apache/couchdb#5027]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

Requiring support for leading wildcard search for Nouveau indexes. Currently, the leading wildcard searches are not supported by Nouveau and throws a 400.

## Desired Behaviour

Ability to configure leading wildcard search for Nouveau.

## Possible Solution

In the previous integration with `couchdb-lucene`, there was a [configurable setting in `couchdb-lucene.ini` which can enable leading wildcard search](https://github.com/rnewson/couchdb-lucene?tab=readme-ov-file#other-tricks). Need a similar setting for Nouveau to support searches like `?q=name:*roe*`

**Comment by rnewson** [comment]
This will not be supported for the same reason that Lucene itself recommends against it, it is very inefficient (all documents with the field must be read, you get no benefit from an index).

If you truly need this a common trick is to reverse your index input and reverse your query, converting a suffix query into a more efficient prefix query.

**Comment by rnewson** [comment]
https://lucene.apache.org/core/9_10_0/queryparser/org/apache/lucene/queryparser/flexible/standard/CommonQueryParserConfiguration.html#setAllowLeadingWildcard(boolean)

**Comment by GMishx** [comment]
Thanks for the explanation and inputs.
