### ISSUE TITLE
Inherited Permissions Not Applied in CouchDB's Windows Installer

### ISSUE THREAD

**Issue by sht2017** [apache/couchdb#5028]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
The CouchDB Windows installation program will not inherit the default permission setting of the parent path to the installation path. That could lead to the problem described in original description.
<details>
<summary>Original Steps to Reproduce [Solved]</summary>

<br>

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )
Cannot start couchdb server on Windows with a fresh install.

According to the error message, seems it may caused by improper permission configuration or missing files ({badmatch,{error,eacces}). Tried to install it on another path and repair it, still stayed the same.
**I doubt that might be a bug because it won't make the installation path auto-inherit the parent-path's permission.**

</details>

## Steps to Reproduce

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )
![recordx](https://github.com/apache/couchdb/assets/29155206/b9b7e91f-c4a0-4222-b98a-8c3441df005c)
<details>
<summary>Original Steps to Reproduce [Solved]</summary>

<br>

Start the InstallationFile.msi, install without checking the checkbox registered as Windows Service. Keeps the rest of settings default.
```cmd
${InstallationPath}\bin>couchdb.cmd
{"Kernel pid terminated",application_controller,"{application_start_failure,couch_log,{{shutdown,{failed_to_start_child,couch_log_server,{{badmatch,{error,eacces}},[{couch_log_writer,init,0,[{file,\"src/couch_log_writer.erl\"},{line,36}]},{couch_log_server,init,1,[{file,\"src/couch_log_server.erl\"},{line,56}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,423}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,226}]}]}}},{couch_log_app,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,couch_log,{{shutdown,{failed_to_start_child,couch_log_server,{{badmatch,{error,eacces}},[{couch_log_writer,init,0,[{file,"src/couch_log_writer.erl"},{line,36}]},{couch_log_server,init,1,[{file,"src/couch_log_server.erl"},{line,56}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}},{couch_log_app,start,[normal,[]]}}})
```

</details>

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )
The installation path of the program should have the same permission as its parent.
<details>
<summary>Original Steps to Reproduce [Solved]</summary>

<br>

Start the couchdb server.

</details>

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: 3.3.3-2 (Latest release on (https://neighbourhood.ie/download-apache-couchdb-win/)[https://neighbourhood.ie/download-apache-couchdb-win/])
* Browser name and version: Google Chrome 123.0.6312.86 (Stable) (x64)
* Operating system and version: Windows 11 23H2 (22631.3296)

## Additional Context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by rnewson** [comment]
`{error,eacces}` is the important bit. couchdb is not permitted to write to the log file location you've configured.

**Comment by sht2017** [comment]
Solved, somehow the setup program for Windows would alternate the installation path permission. That might be a bug?

**Comment by sht2017** [comment]
> `{error,eacces}` is the important bit. couchdb is not permitted to write to the log file location you've configured.



> Hey,
> 
> your user account has no write permissions on your installation directory. Check your users security settings.

Thanks, for solving it by resetting the installation path permission. However, somehow the setup program for Windows would alternate the installation path permission. I doubt that might be a bug because it won't make the installation path auto-inherit the parent-path's permission.

**Comment by sht2017** [comment]
> Hi,
> 
> commenting on your video from above: The msi is doing an administrative installation of CouchDB (UAC window is opening during setup), so the install directory has system rights. Looking at the wix installer we have this:
> 
> ```
> <CreateFolder>
>   <Permission User="[WIX_ACCOUNT_LOCALSYSTEM]" GenericAll="yes" />
>   <Permission User="[WIX_ACCOUNT_ADMINISTRATORS]" GenericAll="yes" />
>   <Permission User="[WIX_ACCOUNT_USERS]" GenericRead="yes" GenericExecute="yes" />
> </CreateFolder>
> ```
> 
> So users in the USERS group will get read/execute access by default ...

I still believe so. 
Since the part you provide,
`<Permission User="[WIX_ACCOUNT_USERS]" GenericRead="yes" GenericExecute="yes" />`
Obviously, the USERS group will not get write access by default. If anyone tries to start CouchDB server without the administrator's permission it will fail anyway due to the lack of write access to the default log path as I occoured.
```
{"Kernel pid terminated",application_controller,"{application_start_failure,couch_log,{{shutdown,{failed_to_start_child,couch_log_server,{{badmatch,{error,eacces}},[{couch_log_writer,init,0,[{file,\"src/couch_log_writer.erl\"},{line,36}]},{couch_log_server,init,1,[{file,\"src/couch_log_server.erl\"},{line,56}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,423}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,226}]}]}}},{couch_log_app,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,couch_log,{{shutdown,{failed_to_start_child,couch_log_server,{{badmatch,{error,eacces}},[{couch_log_writer,init,0,[{file,"src/couch_log_writer.erl"},{line,36}]},{couch_log_server,init,1,[{file,"src/couch_log_server.erl"},{line,56}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}},{couch_log_app,start,[normal,[]]}}})

Crash dump is being written to: erl_crash.dump...
```
So I guess we may need to consider that to let the USERs group obtain write access to the path, or change the default path for log file...

**Comment by sht2017** [comment]
@big-r81

**Comment by big-r81** [comment]
Hi,

I think we should not mix things here. The current setup is an administrative installation (exactly a system-wide install) with the possibility to install and run CouchDB as a Windows service (with administrator privileges). So far, all is working as expected. Currently, CouchDB is not intended to run under a "normal" user after installation.
At the moment you have the possibility (workaround) change the installation folder permissions to have write access for the current user after the installation.

To fix this as a whole, there need to be more changes to the process of distributing it for Windows:

1. Create an installer, which allows a system-wide or user-wide installation of CouchDB and / or
2. Distribute CouchDB as a zipped package without installation at all

I would welcome any PRs which provide more flexible and user-friendly installation methods in the [CouchDB Glazier](https://github.com/apache/couchdb-glazier) repository. 😉

**Comment by sht2017** [comment]
> Hi,
> 
> I think we should not mix things here. The current setup is an administrative installation (exactly a system-wide install) with the possibility to install and run CouchDB as a Windows service (with administrator privileges). So far, all is working as expected. Currently, CouchDB is not intended to run under a "normal" user after installation. At the moment you have the possibility (workaround) change the installation folder permissions to have write access for the current user after the installation.
> 
> To fix this as a whole, there need to be more changes to the process of distributing it for Windows:
> 
> 1. Create an installer, which allows a system-wide or user-wide installation of CouchDB and / or
> 2. Distribute CouchDB as a zipped package without installation at all
> 
> I would welcome any PRs which provide more flexible and user-friendly installation methods in the [CouchDB Glazier](https://github.com/apache/couchdb-glazier) repository. 😉

Sure, I'll look into the [CouchDB Glazier](https://github.com/apache/couchdb-glazier) repository =)
