### ISSUE TITLE
HTTP call inside validation function in design document?

### ISSUE THREAD

**Issue by hubodz** [apache/couchdb#5042]
Hello,
I try to invoke a HTTP call while validating the document (perfectly, I would like to be able to perform the validation in an external endpoint), but when trying to use `fetch` or create `XMLHttpRequest` object, I get a `ReferenceError`.

Is it expected, or there is some kind of bug?

Thanks!

**Comment by rnewson** [comment]
This is deliberately prohibited. a validate_doc_update function can only depend on the input parameters and is sandboxed to prevent any network or file access. This is to ensure the result is deterministic.

**Comment by hubodz** [comment]
Thank you!
