### ISSUE TITLE
Verify CouchDB Installation fails with create view

### ISSUE THREAD

**Issue by NETEROabdelrahman** [apache/couchdb#5062]
## Description

I'm trying to verify the installation but I get a server error
![Screenshot (116)](https://github.com/apache/couchdb/assets/114447180/54c21af4-e6e8-4611-9b35-8a639d911f98)

## Expected Behaviour

the verification process is expected to run successfully

* CouchDB version used: v. 3.3.3
* Browser name and version: [Chrome 125 on Windows 11]
* Operating system and version: windows 11

**Comment by big-r81** [comment]
Hi,

on Windows you need to bind the chttp interface to 127.0.0.1 or to your real ip.

```
[chttpd]
bind_address = 127.0.0.1
```

**Comment by NETEROabdelrahman** [comment]
i still get the same issue, 
![Screenshot (117)](https://github.com/apache/couchdb/assets/114447180/041f53b5-c47d-42a7-af2c-a5e0f11c43d4)
![Screenshot (118)](https://github.com/apache/couchdb/assets/114447180/9245af60-d602-468e-94d1-2a404feb8fe3)

**Comment by big-r81** [comment]
Can you show your config from Fauxton or via command line like (maybe you need to install curl for Windows):

```
curl.exe -s --user user:password http://127.0.0.1:5984/_node/_local/_config
```
Could you append your log file too?

**Comment by NETEROabdelrahman** [comment]
I figured out that Avira is blocking couchspawnkillable.exe, i restored the file and now create view is working just fine
