### ISSUE TITLE
Allow specifying password files instead of cleartext

### ISSUE THREAD

**Issue by nerodono** [apache/couchdb#5155]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

Some systems allow specifying file paths for sensitive fields instead of using cleartext, this allows using secret managements systems such as `agenix` or `sops-nix`.

## Summary

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )
It would be handy if couchdb had option like `-file-/secrets/password`. I know that couchdb also accepts hashed passwords in a config instead of cleartext ones, however, please see "additional context" why this option is also desirable.

## Desired Behaviour

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

```
[admins]
admin = -file-/secrets/password
```

Couchdb looks into `/secrets/password`, sets password for `admin` from that file (either hashed or cleartext).

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )
I use `sops-nix` as my secrets management solution, providing such option would make the workflow more consistent. I can implement this feature myself if you could guide me into the right place of code.

**Comment by rnewson** [comment]
Perhaps a different existing authentication handler would suit you better? (https://docs.couchdb.org/en/stable/api/server/authn.html) the Proxy and JWT handlers in particular would let you externalise authentication in a way that might better integration with your secrets management solution.

Am I inferring correctly that `sops-nix` would arrange for those files to contain the appropriate passwords? If so, is it not capable of writing them in INI format?

You've mentioned 'cleartext' a few times, so I must add that couchdb will always hash any cleartext credentials it finds in the `.ini` files and write the hash back down to disk, to protect the secret value. You should always write a hashed value instead (ideally with PBKDF2 and a high iteration count).

The enhancement in question is probably not too difficult to do but there are caching concerns. For performance reasons we would need to cache the contents of those files in memory, and it would be unprecedented to monitor those files for  changes (we don't do that for our `.ini` files).

My take, so far, is that we would not want the additional complexity and failure modes that this would bring, without bringing a feature that would benefit many users. 

I think there is likely to be a much better way to achieve your goal than the proposal submitted, but please add any further details or comments and we can continue the discussion.

**Comment by nickva** [comment]
I think @rnewson indicated a good solution: using an `.ini` file which sops-nix seems to [support](https://github.com/Mic92/sops-nix/blob/eb34eb588132d653e4c4925d862f1e5a227cc2ab/README.md?plain=1#L580).

CouchDB config system, besides `default.ini` and `local.ini`, will also look in the directories `default.d` and `local.d`, which can contain any number of `*.ini` files. So, wonder if deploying something `.../couchdb/etc/local.d/50-sopx-admins.ini` would work with contents being something simple like this:

```
[admins]
adm = pass
```

Or better if it's pre-hashed already:

```
[admins]
adm = -pbkdf2:sha256-ae88e5f190f4...,50000
```

**Comment by rnewson** [comment]
right, just manage a `.ini` file of your own (one per cred, or all in one) and call config reload whenever it updates.

**Comment by nerodono** [comment]
Sure, it is a solution to add entire `.ini` config as a secret. (A little off-topic) `sops-nix` works a bit different, here's yml configuration of sops, as an example:
```yaml
users:
  user:
    password: qwerty
```
It will create file `/run/secrets/users/user/password` and place `qwerty` as contents. It's a bit too __secret__ to store entire config in the secrets. JWT authentication works for that purpose though.

@nickva proposed good solution, thanks! This will definitely work for me.
