### ISSUE TITLE
Nouveau search query fails

### ISSUE THREAD

**Issue by Dev-Owl** [apache/couchdb#5262]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )
## Description
We are currently testing out Nouveau and are running into a blocker that I can't find a solution for.  After creating an index without any (visible) errors. All requests to it end with the following response from CouchDB:

```
{
  "error": "bad_request",
  "reason": "This TopFieldCollectorManager was created without concurrency (supportsConcurrency=false), but multiple collectors are being created"
}
```
This seems to be related to the data in the index, other indexes are running fine.  First I thought that its related to the store flag (4th parameter of the index function) because one index that was failing with store:true worked well with store:false. 

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )
## Steps to Reproduce

Create an index in a design document like:
```
function(doc){
    var searchValue = "";
    if(doc.Name){
        searchValue += doc.Name;
    }
    if(doc.Description){
        searchValue += doc.Description;
    }
    if(doc.PerformedBy){
        searchValue += doc.PerformedBy;
    }
    if(doc.Component.Name){
        searchValue += doc.Component.Name;
    }
    if(doc.LastEditedBy){
        searchValue += doc.LastEditedBy;
    }
    
    index("text", "search", searchValue, {"store": false});
}
```
Run a query like:
`http://localhost:5984/vesse1220/_partition/1220-taskhistory/_design/history_search/_nouveau/default?q=search:clean*`

Please note the database is using partitions.

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )
## Expected Behaviour
Getting the search results back.

## Your Environment
* CouchDB version used: 3.4.1
* Browser name and version: Chrome 129.0.6668.60 
* Operating system and version: Windows 11 22621.4169

## Additional Context
Using openjdk jdk-17.0.8.101 to run the Nouveau

**Comment by rnewson** [comment]
Thanks, looking into it. Thought that had been found and squashed a while back, should be easy.

**Comment by rnewson** [comment]
sidenote, as you're not putting spaces between those values when you add them, I'm not sure you'll get the search results you're hoping for.

**Comment by Dev-Owl** [comment]
Thanks for the swift response, i switched the search back to the "search plugin" but as this is a new product we are working on i thought i could directly start with the new feature.

Also thanks for the remarks, you are absolutely correct regarding the spaces in the terms.

Out of curiosity why does this error happen? I checked the source and honestly dont understand how this relates to the data?

**Comment by rnewson** [comment]
because of this commit: https://github.com/apache/couchdb/commit/ab594435e5f9dac9b8438394dbbc9ec10bd6cf7b

I can't induce this locally (and obviously the CI test suite doesn't tickle it).

However, I think reverting the above is the answer. I will try a bit longer to repro locally first though

and thank you for trying nouveau :)

**Comment by Dev-Owl** [comment]
I was able to replicate it with a few documents and a very simple index. I'm currently traveling back home from a trade show, tomorrow i could include the test data that triggered it for me if this helps.

**Comment by rnewson** [comment]
thanks, I'd appreciate that. it would be good to know the dbs `q` value also.

**Comment by rnewson** [comment]
repro'ed locally. dug into the Lucene code to figure out the trigger. Fix incoming.

**Comment by rnewson** [comment]
that should do it. 😳

**Comment by Dev-Owl** [comment]
Very nice, from your point of view is building a new application with the current search application still a "good" idea given Nouveau?

**Comment by rnewson** [comment]
We've marked nouveau as experimental in 3.4.1 (though to flush out more obscure bugs than the embarrassing one we found here), so while I very much appreciate the feedback and any usage of nouveau I think you should be cautious.

 I will say that I feel nouveau is going to be a better foundation that the current system (dreyfus/clouseau) as that is build on a, in hindsight, unnecessary and shaky proposition, attempting to emulate Erlang semantics inside the JVM. Nouveau takes a simpler tack, http+json.

 If you are willing to keep going with nouveau we will certainly be prompt in investigating and fixing any issues you find. 

I'll try to get a point release out with this fix as soon as possible.

**Comment by janl** [comment]
[nouveau-1.0-SNAPSHOT-4299acf4.jar.zip](https://github.com/user-attachments/files/17186496/nouveau-1.0-SNAPSHOT-4299acf4.jar.zip)

In anticipation of a proper release, @Dev-Owl, here’s a Nouveau .jar that you can replace the one in your 3.4.1 installation with to try out the fix (and keep experimenting).

**Comment by muhdaizwan** [comment]
> [NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )
> ## Description
> We are currently testing out Nouveau and are running into a blocker that I can't find a solution for.  After creating an index without any (visible) errors. All requests to it end with the following response from CouchDB:
> 
> ```
> {
>   "error": "bad_request",
>   "reason": "This TopFieldCollectorManager was created without concurrency (supportsConcurrency=false), but multiple collectors are being created"
> }
> ```
> This seems to be related to the data in the index, other indexes are running fine.  First I thought that its related to the store flag (4th parameter of the index function) because one index that was failing with store:true worked well with store:false. 
> 
> [NOTE]: # ( Describe the problem you're encountering. )
> [TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )
> ## Steps to Reproduce
> 
> Create an index in a design document like:
> ```
> function(doc){
>     var searchValue = "";
>     if(doc.Name){
>         searchValue += doc.Name;
>     }
>     if(doc.Description){
>         searchValue += doc.Description;
>     }
>     if(doc.PerformedBy){
>         searchValue += doc.PerformedBy;
>     }
>     if(doc.Component.Name){
>         searchValue += doc.Component.Name;
>     }
>     if(doc.LastEditedBy){
>         searchValue += doc.LastEditedBy;
>     }
>     
>     index("text", "search", searchValue, {"store": false});
> }
> ```
> Run a query like:
> `http://localhost:5984/vesse1220/_partition/1220-taskhistory/_design/history_search/_nouveau/default?q=search:clean*`
> 
> Please note the database is using partitions.
> 
> [NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )
> ## Expected Behaviour
> Getting the search results back.
> 
> 
> ## Your Environment
> * CouchDB version used: 3.4.1
> * Browser name and version: Chrome 129.0.6668.60 
> * Operating system and version: Windows 11 22621.4169
> 
> ## Additional Context
> Using openjdk jdk-17.0.8.101 to run the Nouveau  
>

**Comment by muhdaizwan** [comment]
> sidenote, as you're not putting spaces between those values when you add them, I'm not sure you'll get the search results you're hoping for.
