### ISSUE TITLE
Nouveau range faceting doesn’t work as documented

### ISSUE THREAD

**Issue by espy** [apache/couchdb#5273]
## Description

The range faceting syntax in the [Nouveau docs](https://docs.couchdb.org/en/latest/ddocs/nouveau.html#ranges) doesn’t work. It describes the same ranges syntax as the [ddocs search page](https://docs.couchdb.org/en/latest/api/ddoc/search.html#get--db-_design-ddoc-_search-index), but this doesn’t actually work with Nouveau.

I’m not sure whether the Nouveau docs are wrong, or Nouveau is missing the intended implementation. There is a working syntax described elsewhere.

In addition, this other working syntax has confusing defaults for inclusive/exclusive range facets (described further below).

## Steps to Reproduce

In a CouchDB with activated Nouveau, with a running Nouveau server:

1. Have some docs with a number value, eg. `rating: 8.1`
2. Add a Nouveau `double` index for that key:
    ```json
    {
      "_id": "_design/nouveau_example",
      "nouveau": {
        "range": {
          "index": "if (doc.rating) { index('double', 'rating', doc.rating) } }"
        }
      }
    }
    ```
3. Send a ranges query as described in the [Nouveau Docs](https://docs.couchdb.org/en/latest/ddocs/nouveau.html#ranges), but without using `Infinity`, because that also doesn’t work as documented, see [this issue](https://github.com/apache/couchdb/issues/5271):

    Taken from the docs:
    ```
    ?q=*:*&ranges={"price":{"cheap":"[0 TO 100]","expensive":"{100 TO Infinity}"}}
    ```
    …adapted to use our data and `10` instead of `Infinity`:
    ```
    ?q=*:*&ranges={"rating":{"boring":"[0 TO 8]","amazing":"{8 TO 10}"}}
    ```
    As JSON, for readability:
    ```JSON
    {
      "rating": {
        "boring": "[0 TO 8]",
        "amazing": "{8 TO 10}"
      }
    }
    ```
4. This returns:
    ```json
    {
      "error": "query_parse_error",
      "reason": "range values must be lists of objects"
    }
    ```

Turning the query into a list of objects doesn’t work though. What _does_ work is the syntax found in this [Nouveau README.md](https://github.com/apache/couchdb/blob/8d5669173841923a8653acddc2200f6fff8547b8/nouveau/README.md?plain=1#L95):

```
?q=*:*&ranges={ "rating": [ { "label": "boring", "min": 0, "max": 8 }, { "label": "amazing", "min": 8, "max": 10 } ] }
```
as JSON, for readability:
```json
{
  "rating": [
    {
      "label": "boring",
      "min": 0,
      "max": 8
    },
    {
      "label": "amazing",
      "min": 8,
      "max": 10
    }
  ]
}
```

This returns a result:
```json
 "total_hits": 23,
  "ranges": {
    "rating": {
      "boring": 16,
      "amazing": 9
    }
  },
```

Now, you’ll notice that the total count in the facets is more than the `total_hits` (25 vs 23), this is because the rating `8` falls into both facets, so all hits with a rating of `8` are counted twice. The [Nouveau implementation of ranges](https://github.com/apache/couchdb/blob/main/nouveau/src/main/java/org/apache/couchdb/nouveau/api/Range.java#L40) can also use `min_inclusive` and `max_inclusive` boolean keys, which (to me) implies that `min` and `max` are by default _exclusive_, however we just saw they aren’t: `8` is included in both `min` and `max`, and the default for both booleans is actually `true`. 

Using `min_inclusive` and `max_inclusive` does then work. Assigning the `8` to the `amazing` facet like so:

```
?q=*:*&ranges={ "rating": [ { "label": "boring", "min": 0, "max": 8, "max_inclusive": false }, { "label": "amazing", "min": 8, "max": 10 } ] }
```
returns:
```json
  "total_hits": 23,
  "ranges": {
    "rating": {
      "boring": 14,
      "amazing": 9
    }
  },
```

## Expected Behaviour

I expected the example in the docs to work.

## Your Environment

```json
{
  "couchdb":"Welcome",
  "version":"3.4.1",
  "git_sha":"f504e38a5",
  "uuid":"4e36c505782b7068ead9895902c5f07d",
  "features":[
    "nouveau",
    "access-ready",
    "partitioned",
    "pluggable-storage-engines",
    "reshard",
    "scheduler"
  ],
  "vendor":{"name":"The Apache Software Foundation"}
}
```

* CouchDB version used: 3.4.1 Mac binary
* Browser name and version: Requests made using Thunder Client for VS Code
* Operating system and version: Mac OS Sonoma 14.6.1

**Comment by espy** [comment]
Just found this [Nouveau API docs page](https://docs.couchdb.org/en/latest/api/ddoc/nouveau.html#api-ddoc-nouveau) which has the correct syntax, so I suppose the docs on the [main Nouveau page](https://docs.couchdb.org/en/latest/ddocs/nouveau.html#ranges) are simply out of date.

**Comment by rnewson** [comment]
I was just getting to this ticket. Yes, the nouveau syntax here is different. I will confirm it all works as documented now.

**Comment by rnewson** [comment]
Thank you for the feedback btw, this is exactly the sort of thing I was hoping for in the first release. Hopefully it's all just little documentation oopsies...
