### ISSUE TITLE
Revert couch_lru to using gb_trees

### ISSUE THREAD

**Issue by nickva** [apache/couchdb#528]
Recently couch_lru was changed to use ets tables.

During eprof  profiling it showed improved performance however recently in a larger test with more concurrent updates and 5000 max dbs open it showed a significant degradation compared to the previous (gb_tree-based) version

![lru_cache](https://cloud.githubusercontent.com/assets/211822/26177091/5eaa875c-3b26-11e7-923c-e6edd6ca5f8e.png)

**Comment by wohali** [comment]
PR #529 closed this.
