### ISSUE TITLE
Overrideable max results for `counts` with Nouveau

### ISSUE THREAD

**Issue by espy** [apache/couchdb#5284]
Currently, a `counts` request to a Nouveau view will only return the top 16-20 (ish? Haven’t been able to nail this down) highest results for any given counted field. It would be useful if this could be overridden somehow to include a specific number results per field. I suppose returning all fields by default is a recipe for potential disaster though, so we shouldn’t do that 😅.

I’m also not sure whether it would be useful to be able to reverse the counts (return the lowest counts).

## Summary

Assume we have a DB with thousands of products in hundreds of colours (not the best example in the world, admittedly). Emitting a string index for the colours will let us count the individual colours, however we only get back the most frequently occurring ones, even though there are far more. In this case, none of the colours that occur less than 39 times appear in the results.

```json
{
  "counts": {
    "color": {
      "turquoise": 40,
      "tan": 39,
      "salmon": 52,
      "red": 41,
      "purple": 42,
      "orchid": 83,
      "orange": 40,
      "mint green": 39,
      "maroon": 41,
      "magenta": 85,
      "lavender": 45,
      "indigo": 40,
      "green": 43,
      "cyan": 82,
      "blue": 78,
      "azure": 39
    }
  }
}
```

## Desired Behaviour

Have some ability to override the default number of results per counted field.

## Possible Solution

The most future-proof variant would probably be overloading the `counts` array to be able to take strings or objects:

```json
["color", "department"]
```

becomes

```json
[{"name": "color", "maxResults": "100"}, "department"]
```

Would be extensible in the future:

```json
[{"name": "color", "maxResults": "100", "sort": "asc"}, "department"]
```

Note sure how feasible this is.

## Additional context

The current implementation probably covers a lot of real-world use-cases already (thinking about faceting UIs for shops for example), but in data analytics, having more control over the count results could be really useful.

**Comment by rnewson** [comment]
At the shard level we collect the top 10 results for a counts facet, this can be overridden in the http request body to nouveau. Unfortunately there is no way to ask couchdb to do so as yet, we need to add a query parameter to the `_nouveau` endpoint and ensure it gets passed to nouveau on the java side. Happily the hard bit is done, this is just plumbing (and some docs...)

https://github.com/apache/couchdb/blob/main/nouveau/src/main/java/org/apache/couchdb/nouveau/api/SearchRequest.java#L59

https://github.com/apache/couchdb/blob/main/nouveau/src/main/java/org/apache/couchdb/nouveau/api/SearchRequest.java#L162

https://github.com/apache/couchdb/blob/main/nouveau/src/main/java/org/apache/couchdb/nouveau/lucene9/Lucene9Index.java#L306
