### ISSUE TITLE
Nouveau ddoc signature returned by `_info` is wrong

### ISSUE THREAD

**Issue by espy** [apache/couchdb#5291]
If you `GET` the `_info` of a ddoc that contains just a `nouveau` section and one or more indexes, `signature` is always `3e823c2a4383ac0c18d4e574135a5b08`. 

## Description

Any ddoc with just a `nouveau` key always has `3e823c2a4383ac0c18d4e574135a5b08` as a `signature`, which is also the same as the `signature` for any "empty" ddoc without any indexes, eg.

```json
{
  "_id": "_design/test",
  "_rev": "9-1607aa524e868b26cb775a5252a6ced3",
  "language": "javascript"
}
```

So it seems the `nouveau` object in ddocs is invisible to the hashing function used for `signature`. 
Note that proper 64bit hashes _are_ generated per ddoc for the _directories on disk_, so the hashing does work somewhere:

```
data/nouveau/{nodeName}/shards/{shardName}/{databaseName}.{someInteger}/{ddocHash}
```
The `{ddocHash}` here looks as expected (for a Nouveau ddoc, which should have a 64 bit hash).

## Steps to Reproduce

1. Look at the `/_info` output of any ddoc that has a `nouveau` section

## Expected Behaviour

I would expect these to be different from ddoc to ddoc and between changes to the same ddoc, like it is for ddocs with a `views` section.

## Your Environment

```json
{
  "couchdb":"Welcome",
  "version":"3.4.1",
  "git_sha":"f504e38a5",
  "uuid":"4e36c505782b7068ead9895902c5f07d",
  "features":[
    "nouveau",
    "access-ready",
    "partitioned",
    "pluggable-storage-engines",
    "reshard",
    "scheduler"
  ],
  "vendor":{"name":"The Apache Software Foundation"}
}
```

* CouchDB version used: 3.4.1 Mac binary
* Browser name and version: Requests made using Thunder Client for VS Code
* Operating system and version: Mac OS Sonoma 14.6.1

**Comment by janl** [comment]
we had a brief look at [the index calculation](https://github.com/apache/couchdb/blob/main/src/nouveau/src/nouveau_util.erl#L63), but couldn’t spot anything obviously wrong.

**Comment by rnewson** [comment]
thanks, will find and fix.

**Comment by rnewson** [comment]
I don't follow? How are you seeing a signature at all? ```curl 'http://foo:bar@localhost:15984/db1/_design/baz/_nouveau_info/foo?q=*:*' -s | jq
{
  "name": "_design/baz/foo",
  "search_index": {
    "update_seq": 23,
    "purge_seq": 0,
    "num_docs": 0,
    "disk_size": 228
  }
}```

**Comment by rnewson** [comment]
the one from _info is under `view_indexer` and relates only to the view group. it is correct that a nouveau blob doesn't change it.

Will add 'signature' to _nouveau_info output in response to this issue though
