### ISSUE TITLE
401 Unauthorized after apt upgrade

### ISSUE THREAD

**Issue by sensiblearts** [apache/couchdb#5343]
I just (Nov 25) upgraded to CouchDb 3.4.2 on Ubuntu.

It was working fine but the most recent upgrade broke it.

I'm using CORS and sending headers, `Accept, Content-Type, Access-Control-Allow-Origin, X-Auth-CouchDB-Token, X-Auth-CouchDB-UserName, X-Auth-CouchDB-Roles`, where the username and token allow the user to access his own database. (I'm not using couch_per_user -- I'm doing that myself in the application layer.)

Any ideas where to start looking? My original local.ini file is intact, unchanged by the upgrade.

**Comment by big-r81** [comment]
Hey,

always a good start is to look at your CouchDB log file and maybe the log file of your proxy server.

**Comment by big-r81** [comment]
From which version did you upgrade to 3.4.2?

**Comment by sensiblearts** [comment]
I'm embarrassed to say I'm not sure, but I'm pretty sure it was 3.3.?.  I probably updated it to the latest version in July 2024. It was at least 3.2, I'm sure.

I don't see anything in the log files that could be useful, other than possibly an `undefined`:
```
[notice] 2024-11-25T21:23:44.133642Z couchdb@127.0.0.1 <0.5938.0> 7a195f7abb localhost:5984 127.0.0.1 undefined OPTIONS /userdb-6e6a612d34613136386430372d323037352d343235342d613262642d396465666130366230656530/_all_docs?startkey=%22djrn:%22&endkey=%22djrn:%EF%BF%B0%22&include_docs=true 204 ok 1
[error] 2024-11-25T21:23:44.136634Z couchdb@127.0.0.1 <0.10389.0> 4e967067dd rexi_server: from: couchdb@127.0.0.1(<0.5938.0>) mfa: fabric_rpc:open_shard/2 throw:{unauthorized,<<"You are not authorized to access this db.">>} [{couch_db,open,2,[{file,"src/couch_db.erl"},{line,177}]},{mem3_util,get_or_create_db,2,[{file,"src/mem3_util.erl"},{line,602}]},{fabric_rpc,open_shard,2,[{file,"src/fabric_rpc.erl"},{line,331}]},{rexi_server,init_p,3,[{file,"src/rexi_server.erl"},{line,141}]}]
[notice] 2024-11-25T21:23:44.137230Z couchdb@127.0.0.1 <0.5938.0> 4e967067dd localhost:5984 127.0.0.1 undefined GET /userdb-6e6a612d34613136386430372d323037352d343235342d613262642d396465666130366230656530/_all_docs?startkey=%22djrn:%22&endkey=%22djrn:%EF%BF%B0%22&include_docs=true 401 ok 2
```
Some relevant request headers for the above:
```
access-control-allow-origin:
*
origin:
http://localhost:4000
referer:
http://localhost:4000/
sec-fetch-mode:
cors
sec-fetch-site:
cross-site
x-auth-couchdb-roles:
x-auth-couchdb-token:
817f08ab61ec96b...blah..blah..
x-auth-couchdb-username:
nja-4a168d07-2075-4254-a2bd-9defa06b0ee0

```

The `secret` in Fauxton is the same. (I use the `secret` to generate the per-user token for the `x-auth` header, above.) The token and the username are the same, and the database has not changed, nor has the local.ini file. The only thing I know that changed is whatever the apt upgrade did, and now I get 401. 

(I can still log in to Fauxton as admin and view all dbs.)

Thanks for any advice. 

I'm still in dev mode, so I think I'll just start from scratch with a fresh database and see what I can figure out.

**Comment by sensiblearts** [comment]
@big-r81 , I started with a fresh data folder and initialized the single node db with `http://127.0.0.1:5984/_utils/#setup`. Note that it is using the same local.ini file (with `chttpd_auth` settings (`secret`, `hash_algorithms` == `sha256, sha`).

Next, I ran my (elixir) code that was working before, to 1) create a user, 2) create the user's db, and 3) set security settings on the db. Again, I get `Unauthorized`.

The only think that I can think of is that the couch **secret**, even though it is the same as it was, in the Fauxton settings, is not valid.

Can you point me to link(s) to explain **how to reset the secret** and generate proper tokens for a per-user database? Below shows how I'm currently doing the token. (I changed the secret by adding it to [chttpd_auth] in local.ini, but I get the same result. Also, I thought couch was supposed to hash it and write it back to the ini file, but I see only what I originally typed in, no hash.)

How I'm using the token, in the code for the request headers:

```elixir
defp cb_token do
    couch_secret = Application.get_env(:njeco, :couch_secret)
    couch_admin = Application.get_env(:njeco, :couch_admin)
    :crypto.mac(:hmac, :sha256, couch_secret, couch_admin) |> Base.encode16 |> String.downcase
  end

  defp headers do
    [
      {"Access-Control-Allow-Origin", "*"},
      {"Content-Type", "application/json"},
      {"X-Auth-CouchDB-UserName", Application.get_env(:njeco, :couch_admin)},
      {"X-Auth-CouchDB-Roles", "_admin"},
      {"X-Auth-CouchDB-Token", cb_token()},
      {"Accept", "Application/json; Charset=utf-8"}
    ]
  end
```

And a snippet of the responses:
```
user create:
  status: 401,
  body: "{\"error\":\"unauthorized\",\"reason\":\"You are not authorized to access this db.\"}\n",
 
sec create:
  status: 401,
  body: "{\"error\":\"unauthorized\",\"reason\":\"You are not a server admin.\"}\n",
 db create:
  status: 404,
  body: "{\"error\":\"not_found\",\"reason\":\"Database does not exist.\"}\n",
```

**Comment by big-r81** [comment]
Are there maybe any other config files in `local.d/` or `default.d/` directory?

**Comment by sensiblearts** [comment]
Yes. I think you may have found it.

There are 3 files in `default.d` that seem not relevant and one in `local.d` that seems to be the problem.  The `10-admins.ini` file seems to be overriding `local.ini`.

In `10-admins.ini`, the `[chttpd_auth]` section is **blank**, and there is a `secret` in the `[admins]` section -- which looks nothing like the secret as visible in Fauxton:

```

# Package-introduced administrative user
[admins]
admin = -pbkdf2:sha256-a38a96de..blah..blah..,600000
nja_admin = -pbkdf2-1ee14f32adb86..blah...blah...,10
secret = -pbkdf2:sha256-69537672cb...blah...blah...,600000

[couchdb]
uuid = 70385bcb4e0b8502e14e1577dc037af4

[chttpd_auth]


[couch_httpd_auth]
timeout = 6000

[chttpd]
enable_cors = true
bind_address = 0.0.0.0
port = 5984

[cors]
origins = *
credentials = true
headers = Accept, Content-Type, Access-Control-Allow-Origin, X-Auth-CouchDB-Token, X-Auth-CouchDB-UserName, X-Auth-CouchDB-Roles
methods = GET, PUT, POST, HEAD, DELETE

[couch_peruser]
enable = false

[cluster]
n = 1

```

I can probably get this fixed, and I see discussion of the `10-admins.ini` at [https://docs.couchdb.org/en/stable/config/auth.html](https://docs.couchdb.org/en/stable/config/auth.html), but I **need to understand how/why apt upgrade overwrote my previous settings** -- should I make all my settings in local.ini and delete the 10-admins.ini, or backup 10-admins.ini and restore it after apt-upgrade, or...?

Thanks for any advice.

**Comment by sensiblearts** [comment]
For anyone interested, this is a good explanation of 10-admins.ini, [https://lindevs.com/reset-couchdb-admin-password-in-linux/](https://lindevs.com/reset-couchdb-admin-password-in-linux/).

**Comment by big-r81** [comment]
Yeah, there is an order, how config files are used. It's written [here](https://docs.couchdb.org/en/stable/config/intro.html) in the documentation. As you already figured out, th `10-admins.ini` file is the last one in the config file chain, so all new and edited values are written to it.

**Comment by sensiblearts** [comment]
@big-r81 Thank you again for your help.

It took a lot of attempts, moving and changing config settings. It seems the thing that finally worked was:
- moving all the `chttpd` and `chttpd_auth` stuff out of local.ini and into 10-admins.ini
- deleting the `secret` from the `ini` file and letting couch regenerate its own secret, then using that one in my application to generate the token.

I tried a number of times changing the secret, but I was doing it by editing the ini file. I think the key is: **when you want to change the secret, delete it in the ini file and let couch create it.**

(Also, I could be wrong because I'm basing this on my memory, but I think that just after the apt upgrade, the 10-admins.ini file -- modified by  the upgrade -- had the secret under the [admins] block, whereas it should be under the [chttpd_auth] block.)

**Comment by big-r81** [comment]
> (Also, I could be wrong because I'm basing this on my memory, but I think that just after the apt upgrade, the 10-admins.ini file -- modified by the upgrade -- had the secret under the [admins] block, whereas it should be under the [chttpd_auth] block.)

Okay, if you have a reproducer, please open a new ticket. The `secret` needs to be under `[chttpd_auth]`. If you have a line under `[admins]`, then you have a database admin user called `secret`.
