### ISSUE TITLE
[Jenkins] 500 error on getting view output

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#548]
## Expected Behavior
In `reduce_builtin.js` we call a view that has a built in reduce. It should return fine, and usually does.

## Current Behavior
Once we saw a failure where a 500 comes back instead. The `couch.log` shows a gen_server exit: https://paste.apache.org/QfOz

## Possible Solution
```irc
 <+davisp> Its doing "exit(ExitReasonOfProcess) where ExitReasonOfProcess was {normal, stuff...}
 <+davisp> Looks like something isn't properly monitoring the index and it closes as a race condition
 <+davisp> I *think* this line should go after line 49 instead:
           https://github.com/apache/couchdb/blob/master/src/couch_mrview/src/couch_mrview_util.erl#L54
```

## Your Environment
[Jenkins automated run](https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/jenkins-pipeline/5/pipeline/44), `jenkins-pipeline` build 5, CentOS 7, Erlang 18.3. Logfiles uploaded to central logger as `jenkins-couchdb-5-2017-05-29T01:55:35.826219`.

**Comment by wohali** [comment]
Seen again in the same automated run, Ubuntu 16.04, Erlang 18.3. Log excerpt here: https://paste.apache.org/8cF9

**Comment by janl** [comment]
Let’s see if https://github.com/apache/couchdb/pull/562 fixes this.

@wohali IIRC this has to be merged to master before we see it in Jenkins, right?

**Comment by janl** [comment]
Hah, ok, looking closer now, this can’t work.

@davisp line 54 relies on `State` which is only bound in line 50.

I’m not too deep in the code, is what you meant adding the `erlang:monitor` on the `Pid` that’s returned by `get_index_pid()`?

**Comment by davisp** [comment]
Oh derp. Yeah, thats not right. This is a race condition when deleting the database out from under the view.

**Comment by davisp** [comment]
Random idea. I wonder if curl is using keep-alive on the connection and we're getting a mesage back from an old rpc worker which looks like an error and closes the connection.

**Comment by davisp** [comment]
Maybe try adding connection: close hereish?

https://github.com/apache/couchdb/blob/master/test/javascript/couch.js#L438

**Comment by janl** [comment]
testing: https://github.com/apache/couchdb/pull/562

**Comment by janl** [comment]
@davisp running this locally in a while loop `make javascript suites=builtin_reduce.js` still gives me occasional errors like:

```
    Error: {gen_server,call,[<0.5915.0>,{get_state,19},infinity]}
```

**Comment by janl** [comment]
Point of note: This happens more if my test machine is idle otherwise. If there is other CPU load, this tends not to happen.

**Comment by davisp** [comment]
Yeah, I htink this is not right. I'd abandon this approach and try the Connection: close I wrote down somewhere else while staring at my phone with one eye after I woke up.

**Comment by janl** [comment]
@davisp sorry for the confusion, this is with the initial suggestion reverted and now using `Connection: close`. Still fails occasionally

**Comment by wohali** [comment]
@janl Correct, Jenkins only runs on the master, 2.1.x and jenkins-pipeline (for debugging) branches at present. Running the test in a loop is the easiest way to repro these test cases.

**Comment by wohali** [comment]
We have more instances of this today: 

https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/master/8/pipeline/48 (Ubuntu 16.04, Erlang 18.3)
https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/master/8/pipeline/47 (Ubuntu 16.04, default Erlang)
https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/master/9/pipeline/47 (Ubuntu 16.04, default Erlang)
https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/master/10/pipeline/41 (CentOS 6, Erlang 18.3)
https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/master/10/pipeline/43 (CentOS 7, Erlang 18.3)
https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/master/10/pipeline/48 (Ubuntu 16.04, Erlang 18.3)
https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/master/10/pipeline/47 (Ubuntu 16.04, default Erlang)

This is now by far our most common failure scenario in Jenkins.

**Comment by janl** [comment]
And another one on Travis:

```
test/javascript/tests/view_collation.js                        
    Error: {gen_server,call,[<0.7764.0>,{get_state,8},infinity]}
Trace back (most recent call first):
    
 548: test/javascript/couch.js
      CouchError([object Object])
 511: test/javascript/couch.js
      ([object CouchHTTP])
 177: test/javascript/couch.js
      ("(function (doc) {emit(doc.foo, null);})",null,[object Object])
  85: test/javascript/tests/view_collation.js
      ()
  37: test/javascript/cli_runner.js
      runTest()
  48: test/javascript/cli_runner.js
```

**Comment by wohali** [comment]
Another 6 or so occurrences for this in Jenkins. I'm not going to keep updating this ticket with the links, we have enough evidence to go on at this point.

**Comment by kocolosk** [comment]
I thought that perhaps with the work in #576 and #577 this might be resolved, but now I think we may have just morphed to an `{'EXIT',normal}` error. I've seen this twice in 10 runs locally.

**Comment by kocolosk** [comment]
I think I know what's happening here. Every `db.query()` invocation in this test creates a ddoc with a random name, queries the view, and then deletes the ddoc. In many cases we have consecutive invocations where the ddocs have the same computed signature. It looks like we're hitting a race condition where we request to delete a ddoc, the server starts closing all the associated indexes, we create a new one with the same sig, the coordinator grabs an Fd from the cache with that sig, and the Fd is closed underneath it during the response.

I tested this theory by adding a random string to each view, and so far I've looped through 40 consecutive runs without a failure. That's of course not fixing the real race condition, but if we can't track down the race condition in short order it might be a useful hack to stop the flakiness. It wouldn't be the first time, and this is not really a bug you'd expect to encounter in production ...

**Comment by kocolosk** [comment]
@eiri I'm curious about your thoughts on this. You were poking at some of the same issues in #576 but I think that didn't totally address the race condition. There's a gap in between retrieving the index Pid from the `?BY_SIG` ets table and then monitoring the underlying `#mrst.fd`. You've introduced the retry logic to get the index state, but all the while I think the underlying Fd could be unmonitored.

**Comment by eiri** [comment]
@kocolosk yes, we've discussed this on IRC before I did the patches and came to the same conclusion - this is a race happening because of rapid create\delete cycle on views with same signature. The delay logic I did not solving the race, naturally, but we've decided that we don't really want to encourage this anti-pattern and this fix should be enough for javascript test suite because of its single-thread nature.

I'm kind of curious how you running the tests to get the errors you are seeing, because to be honest I have hard time to fail javascript test suite locally even on VM with restricted resources.

**Comment by kocolosk** [comment]
Hmm, I didn't need to do anything special -- just ran it in a bash loop and it would fail within the first 10 runs.

**Comment by kocolosk** [comment]
The more I dig the more I think this is a non-trivial race condition. I'd recommend that we file a separate ticket explicitly focused on addressing the race condition, including an easily-reproducible test case (should be straightforward in a multi-threaded environment), and then tweak the JS one to avoid the view signature optimization so it can focus on what it was originally designed to test.

**Comment by wohali** [comment]
@kocolosk If we're going to fix test cases, we're going to have to fix quite a few of them, and it's seems it's not just JS tests that are affected. Here are additional instances of this issue in the last ~10 Travis failures on master:

https://travis-ci.org/apache/couchdb/jobs/248891365 (view_collation.js)
https://travis-ci.org/apache/couchdb/jobs/248840745 (**EUnit** test in couch_mrview_changes_since_tests - where we got the `{gen_server,call,[...,infinity]}` error again!)
https://travis-ci.org/apache/couchdb/jobs/245780773 (reduce_builtin.js - but it's an `{'EXIT',noproc}` this time. different? not much useful in the couch.log...)
https://travis-ci.org/apache/couchdb/jobs/245780769 (reduce_builtin.js)
https://travis-ci.org/apache/couchdb/jobs/245428546 (reduce_builtin.js)
https://travis-ci.org/apache/couchdb/jobs/243780114 (view_pagination.js)

I'm marking this as a 2.1 blocker for now. If we want to split the issue up, fine, but the eunit test tells me we may still have 2 distinct failure modes. My priority is a repeatable, clean-running test suite for the 2.1 release.

**Comment by janl** [comment]
@sebastianrothbucher do you maybe have some time to tackle the JS tests? I know you’ve done tons of this kind of work :)

One idea would be to leave the tests as-is as good as possible, and inject the random element in couch.js, but that’s probably only really doable for ad-hoc queries that  don’t reference the doc by name later. But we do have a bunch of those.

**Comment by sebastianrothbucher** [comment]
Let me check if I can some time later this week. Just from the top of my head: Would inserting a nonsensical if('randomString1'=='randomString2') {/*do nothing*/} at the end of each map function (i.e. one change in couch.js) do the trick?

**Comment by wohali** [comment]
Even a *whitespace* change would be sufficient.

**Comment by sebastianrothbucher** [comment]
or append a randomized comment when uploading the map fkt

**Comment by sebastianrothbucher** [comment]
I did a PR for just that. Sadly I can't reproduce (on a CentOS VM), but tests still work - maybe Travis gives us more stable test runs now

**Comment by wohali** [comment]
@kocolosk @eiri What do you want to do about the actual race condition? Do you think the race itself should be a 2.1 release blocker?

Feel free to keep this issue for it, or open a new one.

**Comment by eiri** [comment]
It's rather hard to fix it for real with a solid chance of accidentally adding deadlock or bottleneck and at the same time it is induced by usage anti-pattern, so I don't see it as a blocker.

**Comment by kocolosk** [comment]
Not a blocker. We should write a solid reproducible test case for it (should be easy enough in EUnit right?) and address it, but agree it's difficult.

I think it is possible to observe this bug in normal operations, especially if a user is following the best practice around ddoc upgrades. Deleting the temporary ddoc after migrating the main one could easily kill any in-progress view responses.

**Comment by wohali** [comment]
OK, see #647 for the continuation to this bug. I am closing this one out for now, unless we see repeats of this pop up in test runs.

Thanks everyone! 💃 🐄 🎆
