### ISSUE TITLE
js restartServer() sometimes fails

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#553]
## Current & Expected Behaviour
Failure is on master.

The JS test `test/javascript/tests/delayed_commits.js` has a bunch of calls to `restartServer()` in it. So do some other JS tests. Sometimes, the restart fails:

```
test/javascript/tests/delayed_commits.js                       

FAIL restart
```

The uploaded couch.log file after restart looks normal - no problems in startup that I can see (_id jenkins-couchdb-3-2017-05-30T21:27:03.085057). Perhaps it just took too long to restart.

## Possible Solution
Increase timeout?

**Comment by wohali** [comment]
FYI restartServer() seems to be implemented twice, once with a 1s timeout and once with a 5s timeout. Would be good to remove the redundancy and to set an appropriate timeout.

**Comment by janl** [comment]
For completeness sake: https://github.com/apache/couchdb/pull/556#issuecomment-305751373
