### ISSUE TITLE
JS stats test has inconsistent results

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#554]
## Current & Expected Behaviour
Sometimes, the JS `test/javascript/tests/stats.js` test errors with off-by-one errors such as the following:

```
test/javascript/tests/stats.js                                 
    Error: expected '8', got '9'
Trace back (most recent call first):
    
  52: test/javascript/test_setup.js
      T(false,"expected '8', got '9'","Request counts are incremented proper
 321: test/javascript/couch_test_runner.js
      TEquals(8,9,"Request counts are incremented properly.")
 132: test/javascript/tests/stats.js
      (6,9)
  46: test/javascript/tests/stats.js
      runTest([object Array],[object Object])
 131: test/javascript/tests/stats.js
      ()
  37: test/javascript/cli_runner.js
      runTest()
  48: test/javascript/cli_runner.js
      
[31mfail
```

## Possible Solution
This test was recently re-enabled under the assumption that it was good to have something covering this area of our API, but significant sections had to be commented out because results didn't match up with requests being made. 

It would be good to determine whether these tests are deterministic enough - or whether we actually have a bug in our stats handling - since numbers seem off in quite a few places.

## Your Environment
Most recent failure is Jenkins, master branch, logs _id jenkins-couchdb-1-2017-05-29T01:59:56.803570, Ubuntu 12.04, Erlang 18.3.

**Comment by janl** [comment]
`stats.js` relies heavily on `restartServer` which [I believe](https://github.com/apache/couchdb/pull/556#issuecomment-305751373) we nixed for 2.0 {

**Comment by wohali** [comment]
restartServer() works with 2.0 via a call out to `dev/run`, see my comments here: https://github.com/apache/couchdb/pull/556#issuecomment-305900649

**Comment by janl** [comment]
yup, sorry,*retract retract*

**Comment by wohali** [comment]
We're still seeing a bunch of these:

https://travis-ci.org/apache/couchdb/jobs/243780115 - stats.js mismatch line 58
https://travis-ci.org/apache/couchdb/jobs/243303510 - stats.js mismatch line 58

I think we have a real set of bugs here, but it may be time to re-disable the entire stats.js test for now. The fact that the test run is failing is a blocker; the fact that our stats are sometimes inconsistent, to me, isn't - though it may be indicative of race conditions as of yet uncovered.

Thoughts?

**Comment by wohali** [comment]
I have fully disabled this test for now. I'm starting to think that the dynamic behaviour of the clustered setup means these stats don't make as much sense anymore -- and that the test needs a complete rework.

We can revisit after 2.1.0.
