### ISSUE TITLE
eunit context cleanup times out while cleaning up os daemons

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#571]
## Expected and Current Behaviour
Sometimes, the eunit test harness fails to complete context cleanup. In this case, it fails finishing off the `couchdb_os_daemons_tests` test `should_spawn_multiple_daemons`.

https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/master/15/pipeline/49

Makefile output:
```
module 'couchdb_os_daemons_tests'
  OS Daemons tests
    couchdb_os_daemons_tests:107: should_check_daemon...ok
    couchdb_os_daemons_tests:113: should_check_daemon_table_form...ok
    couchdb_os_daemons_tests:120: should_clean_tables_on_daemon_remove...[0.548 s] ok
    couchdb_os_daemons_tests:127: should_spawn_multiple_daemons...[0.607 s] ok
    undefined
    *** context cleanup failed ***
**in function test_util:stop_sync_throw/4 (src/test_util.erl, line 161)
in call from couchdb_os_daemons_tests:teardown/2 (test/couchdb_os_daemons_tests.erl, line 58)
**throw:{timeout,os_daemon_stop}

Application config was left running!
Application couch_epi was left running!
Application ioq was left running!
  undefined
  Application config was left running!
*** context setup failed ***
**in function meck_proc:start/2 (src/meck_proc.erl, line 96)
  called as start(couch_stats,[passthrough])
in call from test_util:mock/1 (src/test_util.erl, line 245)
in call from test_util:'-mock/1-lc$^0/1-0-'/1 (src/test_util.erl, line 238)
in call from test_util:start/3 (src/test_util.erl, line 226)
in call from couchdb_os_daemons_tests:setup/1 (test/couchdb_os_daemons_tests.erl, line 47)
**error:{already_started,<0.10686.1>}

[done in 7.158 s]
```

## Possible Solution
Increase the timeout for `couchdb_os_daemons_tests:teardown/2`.

**Comment by janl** [comment]
+1 for increasing the timeout it is 1s only

**Comment by janl** [comment]
https://github.com/apache/couchdb/compare/fix/571/increase-test-timeout?expand=1

**Comment by wohali** [comment]
The patch here didn't work - see #583.

**Comment by nickva** [comment]
Took a look at this. Part of shutdown code is in `terminate` callback in `couch_os_daemons` module. In `terminate` each port is sequentially stopped. When stopping, it spawns an os process to run "kill -9 <pid>" then port is also closed with "port_close". Forking another process and the sequential part could take a while I suppose. In this particular case we can probably wrap the test teardown code iin a try/except and then if cleanup fails issue an `exit(OsDPid, kill)` signal.

However speaking of timing, ran this on my laptop (5 year old Thinkpad, 1.9Ghz, Ubuntu 17.04) and the `should_spawn_multiple_daemons.` test finishes in `[0.006 s]` seconds. From the log above I see it finished in `[0.607 s]` on our test runner. That's over a 100x slowdown. It's not scientific, of course, but even so seems like a significant difference. Wonder if there is any way to guarantee a minimum performance profile in the test runners, or least abandon a test run if we see it's running at the speed of a pocket calculator.

**Comment by wohali** [comment]
Look at the rest of the test run logfile - most of the tests complete pretty speedily, certainly not 100x slower. We just have occasional slowdowns, I guess, possibly related to process execution. The environment is largely out of our control, unless Cloudant is prepared to donate hosts for full control by the ASF on which we can run our Dockerized tests.

If the entire test run takes > 45 minutes, we abort the test run. Our tests should complete in 20 minutes. I think that's enough safeguarding.

**Comment by nickva** [comment]
Yap, obviously it's not a sustained 100x slowdown but there are either random spikes or like you said related to specific operations (forking, reading from disk, socket stuff maybe...).

Besides getting dedicated hosts with predictable performance profile wonder if Travis has anything to mitigate this. Say if test fails retry one more time. Or take the best of 5 runs.

**Comment by wohali** [comment]
Travis doesn't do "best of 5" unless you explicitly enable it. And to my mind that's just sweeping the problem under the rug.....

**Comment by wohali** [comment]
Haven't seen this again in a bit. Closing for now...
