### ISSUE TITLE
Futon logout works on Firefox but not Chrome

### ISSUE THREAD

**Issue by harshschoolengg** [apache/couchdb#585]
I am not able to log out from Futon interface in chrome. When I click on logout link nothing happens. I am able to successfully login/logout from Futon in Firefox.

As there was no response after clicking the logout link, I could not mark any error from chrome dev console. 

But there was an unusual observation while reloading the futon. Some database links responded with 404 error in chrome console. I have attached pics of the error in dev console below.

![image](https://user-images.githubusercontent.com/13298419/26876420-b3cb9838-4ba3-11e7-8cf5-1abf366af469.png)

**EDIT**: When I cleared all storage site data from chrome dev tools> application > clear storage, everything started working normally. I don't know why this issue has arisen in chrome.

**Comment by wohali** [comment]
I'm afraid that Futon is no longer supported. You will want to upgrade to CouchDB 2.0 and the new UI in that, Fauxton.
