### ISSUE TITLE
keynot

### ISSUE THREAD

**Issue by agsci2017** [apache/couchdb#594]
## Feature request:
1. Add keynot feature(keynot="zinc")
2. Add keynot list support(keynot=["zinc","copper"])

## Example:
http://mydatabase.com/screws/_design/design/_view/bycost?keynot="zinc"

## Expected Behaviour
view produces results, where key is not equal to "zinc" (only brass, copper screws)

**Comment by wohali** [comment]
You can do this right now very easily with two queries. Each query would use `startkey` and `endkey` to access the entire range of keys just before and just after the key you are wanting to exclude.

**Comment by janl** [comment]
This is not likely to move forward without a PR, and there might still be opposition to the feature then (just setting expectations here for anyone going to attempt this. Added needhelp label, reopen when PR exists.
