### ISSUE TITLE
Create a Helm chart to deploy CouchDB using Kubernetes

### ISSUE THREAD

**Issue by kocolosk** [apache/couchdb#609]
## Expected Behavior
`helm install stable/couchdb` should stand up a working CouchDB deployment in my Kubernetes environment.

## Current Behavior
Installing CouchDB in Kubernetes is currently a very manual task. Many of our users are starting to adopt Kubernetes in their environments and are working through these details themselves.

## Possible Solution
See https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md for the process to add a new chart to the Helm repository.

**Comment by wohali** [comment]
If you're coming to "thumbs up" the comment above, that "needhelp" label means we could use a PR here.

Please propose something and we'll be glad to support you in the process.

**Comment by kocolosk** [comment]
Here's a rudimentary working chart:

https://github.com/kocolosk/charts/tree/couchdb-statefulset

Lots more that could be done to allow for a greater degree of configuration, etc. but the basic `helm install ./incubator/couchdb` will deploy a connected 3 node cluster. The cluster auto-connectivity depends on a sidecar container that I wrote up here:

https://github.com/kocolosk/couchdb-statefulset-assembler

Would be great to get any help from the interested parties here, or even just details about how you'd want to use this chart.

**Comment by kocolosk** [comment]
PR submitted upstream: https://github.com/kubernetes/charts/pull/2964

**Comment by wohali** [comment]
@kocolosk do we still need this issue, or is everything being taken care of over in kubernetes/charts#2964 ?

If there's a desire to add this to the documentation after that PR lands, that can go over in apache/couchdb-documentation instead of here.

**Comment by kocolosk** [comment]
Yes I think it makes sense to close this one @wohali
