### ISSUE TITLE
default max_document_size is inconsistent between documentation and default.ini

### ISSUE THREAD

**Issue by targos** [apache/couchdb#613]
Documentation for the max_document_size setting claims it is 4 GB: http://docs.couchdb.org/en/2.0.0/config/couchdb.html#couchdb/max_document_size
But in practice it is 64 MB: https://github.com/apache/couchdb/blob/2f539e003c88b8c76c42a39e6c53b9e61bc783f8/rel/overlay/etc/default.ini#L11

Which one is correct?

## Your Environment

* Version used: 2.0.0
* Operating System and version (desktop or mobile): CentOS 7 64-bit

**Comment by wohali** [comment]
I don't think the documentation is trying to show what the default value is, in the inset; it's just trying to show how you'd change the value in your own `local.ini` file. For instance, scrolling up it shows a sample setting for the `util_driver_dir` directory that is clearly not the default value.

64MB is the correct default value.
