### ISSUE TITLE
Support stable and update options with mango queries

### ISSUE THREAD

**Issue by garrensmith** [apache/couchdb#621]
`stable` and `update` options give Mango queries more flexibility in terms of when the results set is updated and whether a fixed replica set is used.

**Comment by janl** [comment]
can you explain the difference to our view options and why we wanna differ here?

**Comment by garrensmith** [comment]
This isn't different to view options. Its updating to support the new view options. Stale is deprecated see https://github.com/apache/couchdb-couch-mrview/commit/459a548f269b00bf2d2ace0

**Comment by janl** [comment]
I don’t see from that discussion that `stale` is deprecated.

**Comment by janl** [comment]
I don’t see a deprecation, but a unilateral removal of stale=ok, which has not been flagged as 2.0 BC break which is terrible to find a year later :/ — I propose we re-introduce stale=ok as an alias to the combination of `stable` and `update` it represents, and make that also available on Mango.

**Comment by rnewson** [comment]
it was not removed, just embellished.

**Comment by janl** [comment]
@rnewson thanks for the heads up, I’m seeing https://github.com/apache/couchdb-couch-mrview/commit/459a548f269b00bf2d2ace0#diff-0dce740f95201eba18c70634c3ba6dcbL506 now.

My point then remains, `stale` is not deprecated and should be added to Mango the same way.

**Comment by garrensmith** [comment]
Thanks all for finishing this up for me.
