### ISSUE TITLE
EUnit couch_changes_tests failing should_select_with_continuous test due to heartbeats

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#630]
Sometimes this test is failing. This is a new failure unseen prior to about 20 days ago. Feels like a regression.

## Sample Log
```
  module 'couch_changes_tests'
    Changes feed
      Filter _selector
        couch_changes_tests:361: should_select_basic...[0.130 s] ok
        couch_changes_tests:375: should_select_with_since...[0.001 s] ok
        couch_changes_tests:390: should_select_when_no_result...[0.004 s] ok
        couch_changes_tests:401: should_select_with_deleted_docs...[0.010 s] ok
        couch_changes_tests:422: should_select_with_continuous...*failed*
in function couch_changes_tests:'-should_select_with_continuous/1-fun-0-'/1 (test/couch_changes_tests.erl, line 433)
in call from couch_changes_tests:'-should_select_with_continuous/1-fun-3-'/2 (test/couch_changes_tests.erl, line 432)
**error:{assertMatch,[{module,couch_changes_tests},
              {line,433},
              {expression,"Rows"},
              {pattern,"[ # row { seq = 10 , id = << \"doc8\" >> , deleted = false } ]"},
              {value,[]}]}
  output:<<"">>
```

## Instances of failure (both Travis and Jenkins!)
* https://travis-ci.org/apache/couchdb/jobs/240887629
  * https://couchdb-vm2.apache.org/ci_errorlogs/travis-couchdb-240887629-2017-06-08T17%3A55%3A58.796108/couchlog.tar.gz
* https://travis-ci.org/apache/couchdb/jobs/245780770
  * https://couchdb-vm2.apache.org/ci_errorlogs/travis-couchdb-245780770-2017-06-22T13%3A19%3A26.993775/couchlog.tar.gz
* https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/master/43/pipeline/47
  * https://couchdb-vm2.apache.org/ci_errorlogs/jenkins-couchdb-43-2017-06-29T00:26:42.153281/couchlog.tar.gz
* https://travis-ci.org/apache/couchdb/jobs/248840743 (slightly different)
https://couchdb-vm2.apache.org/ci_errorlogs/travis-couchdb-248840743-2017-06-30T16%3A02%3A23.498816/couchlog.tar.gz

Different one above:
```
        couch_changes_tests:459: should_stop_selector_when_db_deleted...*failed*
in function couch_changes_tests:wait_finished/1 (test/couch_changes_tests.erl, line 827)
in call from couch_changes_tests:'-should_stop_selector_when_db_deleted/1-fun-0-'/1 (test/couch_changes_tests.erl, line 469)
**error:{consumer_died,
    [{module,couch_changes_tests},
     {line,829},
     {value,
         {assertion_failed,
             [{module,couch_changes_tests},
              {line,899},
              {value,deleted},
              {reason,"Received unexpected message"}]}}]}
```

**Comment by rnewson** [comment]
coucld this be because the changes feed is no longer totally ordered?

**Comment by rnewson** [comment]
nope, can't be that.

**Comment by rnewson** [comment]
couch_changes_tests:422: should_select_with_continuous...[0.313 s] ok

**Comment by wohali** [comment]
Another instance of this today on master:
* https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/master/47/pipeline/43
  * https://couchdb-vm2.apache.org/ci_errorlogs/jenkins-couchdb-47-2017-07-04T19:45:06.139489/couchlog.tar.gz

```
        couch_changes_tests:422: should_select_with_continuous...*failed*
in function couch_changes_tests:'-should_select_with_continuous/1-fun-0-'/1 (test/couch_changes_tests.erl, line 433)
in call from couch_changes_tests:'-should_select_with_continuous/1-fun-3-'/2 (test/couch_changes_tests.erl, line 432)
**error:{assertMatch,[{module,couch_changes_tests},
              {line,433},
              {expression,"Rows"},
              {pattern,"[ # row { seq = 10 , id = << \"doc8\" >> , deleted = false } ]"},
              {value,[]}]}
  output:<<"">>
```

**Comment by wohali** [comment]
And again:
* https://travis-ci.org/apache/couchdb/jobs/250437167

**Comment by wohali** [comment]
@eiri spied on IRC that these failures both point to heartbeats showing up in the _changes feed, possibly unexpected ones. Good eye! 

Yest case needing to be partially rewritten, perhaps?

**Comment by wohali** [comment]
@nickva do you think your checkin will resolve this?

**Comment by nickva** [comment]
@wohali yeah I think it should resolve it. Let's close it and then we can re-open it if we see it up pop up again.
