### ISSUE TITLE
couch_replicator_scheduler killing "completed normally" replication?

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#644]
## Current & Expected Behavior
Normally the `couch_replicator_use_checkpoints_tests` pass fine. However, we have an unusual failure in a Travis run today. The replication scheduler says it "completed normally", but then it appears it proceeds to KILL it?! Odd.

## Logs
* **Travis**: https://travis-ci.org/apache/couchdb/jobs/250436888#L5400-L5407
* **`couch.log`**: https://couchdb-vm2.apache.org/ci_errorlogs/travis-couchdb-250436888-2017-07-05T17%3A16%3A05.960154/couchlog.tar.gz
* **Useful excerpt**: https://gist.github.com/wohali/0bc580a1edf96205a52df30a72e55ddc

Assigning to @nickva because this feels like a scheduler bug.

**Comment by nickva** [comment]
Sprinkled some ?debug macros on that test and made Travis run it 10 times in a row.

https://github.com/cloudant/couchdb/commit/fb13cf5d92656f11e2f6cd92b1d2868024ec6225

One failure:

  https://travis-ci.org/cloudant/couchdb/jobs/252251466

```
test/couch_replicator_use_checkpoints_tests.erl:77:<0.30989.1>: <-

        test/couch_replicator_use_checkpoints_tests.erl:80:<0.30989.1>: <-

[done in 0.659 s]

test/couch_replicator_use_checkpoints_tests.erl:87:<0.30989.1>: <-

test/couch_replicator_use_checkpoints_tests.erl:80:<0.30989.1>: <-

test/couch_replicator_use_checkpoints_tests.erl:89:<0.30989.1>: <-

test/couch_replicator_use_checkpoints_tests.erl:91:<0.30989.1>: <-

test/couch_replicator_use_checkpoints_tests.erl:93:<0.30989.1>: <-

    *unexpected termination of test process*

::killed

test/couch_replicator_use_checkpoints_tests.erl:50:<0.916.0>: <-

  [done in 5.419 s]

[done in 5.419 s]
```

**Comment by wohali** [comment]
Closing until we see a recurrence of this because of #662.
