### ISSUE TITLE
Why Fauxton make password lowercase?

### ISSUE THREAD

**Issue by bin16** [apache/couchdb#658]
There's a problem in `Fauxton on Apache CouchDB v. 2.0.0`. In replication of Fauxton, `http://user:PASSWORD@host:port/db` will be `http://user:password@host:port/db` when send a request to local couchdb server. The url( include password ) will be lowercase, so that can't be authenticated.

(It's ok in `Futon on Apache CouchDB 1.6.0`)

## Expected Behavior

The password should not be lowercase fully.

## Current Behavior

![](http://img.nulla.top/2017-07-09/103038_imup.png)

## Possible Solution

Fix Fauxton?

## Steps to Reproduce (for bugs)

1. `Fauxton on Apache CouchDB v. 2.0.0`
2. Type a url with a password has uppercase letters.
3. Replica

## Context

![](http://img.nulla.top/2017-07-09/111235_imup.png)

## Your Environment

Windows 10 Pro Insider Preview
Build 16199.rs_prerelease.170513-2252
Fauxton on Apache CouchDB v. 2.0.0
Node.js v8.0.0

**Comment by wohali** [comment]
This has been fixed on master and will be released with CouchDB 2.1.

![mwsnap 2017-07-10 20_39_10](https://user-images.githubusercontent.com/112292/28046205-0c748d66-65b0-11e7-8aa7-31f3b3f51d04.png)

![mwsnap 2017-07-10 20_39_15](https://user-images.githubusercontent.com/112292/28046204-0ab3dedc-65b0-11e7-9dcc-31dfb8e5099b.png)
