### ISSUE TITLE
Lack of tracking for HTTP/2 support

### ISSUE THREAD

**Issue by luanmm** [apache/couchdb#661]
## Expected Behavior

Any information regarding the HTTP/2 feature would be very welcome.

## Current Behavior

I couldn't find anything about HTTP/2 support in CouchDB, not even in the roadmap, blog, etc. The only track is on this thread: http://couchdb-development.1959287.n2.nabble.com/Support-for-HTTP-2-td7604743.html. And it doesn't tell much.

## Possible Solution

Maybe put this on track somehow: in the blog, roadmap or giving it an issue (like this one) to track it.

## Steps to Reproduce (for bugs)

N/A

## Context

CouchDB is a great technology to work with, but there is some features that any team must have knowledge of support to address projects requirements.

## Your Environment

N/A

**Comment by wohali** [comment]
Currently issues on the roadmap for CouchDB are here:

   https://github.com/janl/couchdb-next/issues

from the last CouchDB summit, before this repository started to allow issues to be filed directly against it. We'll start moving these into the GitHub Issues list here, after 2.1 is released.

You can see the very first issue that is open is HTTP/2 support:

    https://github.com/janl/couchdb-next/issues/2

No implementation work has been done yet.

**Comment by luanmm** [comment]
Sorry for the opened issue, then. I really couldn't find any information before your reply. Thank you very much, @wohali.

**Comment by wohali** [comment]
No problem! We're just in the process of moving over from our old JIRA instance to GitHub Issues, and things are a bit scattered at the moment. After 2.1 releases, I'll have a lot more free time to get our roadmap in place here. Thanks for reminding me!
