### ISSUE TITLE
JS delayed_commits: connection refused

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#673]
## Expected Behavior
Test should pass...

## Current Behavior
Has failed a few times in Jenkins now, like this:

```
test/javascript/tests/delayed_commits.js                       
    Error: Failed to execute HTTP request: Failed connect to 127.0.0.1:15984; Connection refused
Trace back (most recent call first):
    
  37: test/javascript/couch_http.js
      ("\"false\"\n")
 468: 127.0.0.1/_config/couchdb/delayed_commits",[object Object])@test/javascript/couch.js
      ("PUT","/_node/node1
 408: test/javascript/couch_test_runner.js
      run_on_modified_server([object Array],(function () {sleep(15000);T(db.
  29: test/javascript/tests/delayed_commits.js
      ()
  37: test/javascript/cli_runner.js
      runTest()
  48: test/javascript/cli_runner.js
```

couch.log shows only:
```
[notice] 2017-07-13T06:25:24.809186Z node1@127.0.0.1 <0.328.0> c9923cec40 127.0.0.1:15984 127.0.0.1 undefined GET / 200 ok 1
```
which is about 1s after the very first entry in the log file. There's no evidence of a PUT.

Jenkins failure:
* https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/jenkins-build-packages/9/pipeline/42

**Comment by wohali** [comment]
Also in Travis:
* https://travis-ci.org/apache/couchdb/jobs/253082338#L5761

**Comment by wohali** [comment]
again: https://travis-ci.org/apache/couchdb/jobs/255399793

**Comment by davisp** [comment]
This and #669 appear to be the server reboot code in dev/run not waiting until the clustered port is up. Theoretically we should be able to change that check here:

https://github.com/apache/couchdb/blob/master/dev/run#L349

And since the clustered port comes up second the local port should be guranteed to be alive. Or we could just add a second check for both to rock our belt and suspenders style.

**Comment by wohali** [comment]
Actually, the variable name is misleading. We're only checking the __clustered__ port. https://github.com/apache/couchdb/blob/master/dev/run#L208-L210

I'll take a closer look.

**Comment by wohali** [comment]
So if that fix I just checked in doesn't work, I'm in favour of just deleting this test. `delayed_commits = true` is a deprecated setting in 2.x, and our harness makes it hard to be deterministic about killing couch fast enough to prevent a flush to disk.

**Comment by janl** [comment]
Would opt for disabling the test for now, if we get around to fix it, we can re-enable. Would only remove if we get rid of the `delayed_commits` code as well.

But definitely disable.

**Comment by wohali** [comment]
I think my most recent fix has fixed this. I'm going to mark as closed for now, and if it recurs, we'll move to disable the test.
