### ISSUE TITLE
Test failure in couch_db_mpr_tests

### ISSUE THREAD

**Issue by nickva** [apache/couchdb#695]
```
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed

    [done in 3.409 s]

  [done in 3.552 s]

module 'couch_db_mpr_tests'

  multi-part attachment tests

    couch_db_mpr_tests: couch_db_mpr_test_...*timed out*

    undefined
```

No log file: `COUCHAUTH credentials unavailable! Unable to upload logfiles.`

**Comment by wohali** [comment]
Nothing to go on here. I've reviewed the test case, and despite it doing the create/delete/create the exact same named DB thing which it shouldn't do, I don't see anything that specifically could make this fail.

Will issue a PR to fix the create/delete/create cycle issue. And moving out of Milestone 2.1.0 unless this recurs.
