### ISSUE TITLE
Query view with stale = ok does not work

### ISSUE THREAD

**Issue by nicolelovecoding** [apache/couchdb#719]
## Expected Behavior
it should return the data in the db I am querying

## Current Behavior
It returns empty array

## Steps to Reproduce (for bugs)
1, Set up a CouchDb running locally.
2, Try to query a view by:
```
var db = new PouchDB('http://admin:admin@localhost:5984/dbname');
db.query('design_name/view_name', {
      stale: 'ok',
      limit: limit,
      skip: skip,
      include_docs: true,
      reduce: false
    });
```

## Context
I am writing a test for my project which needs to set up db locally and get data from it. The query sentence with stale = 'ok' actually works well with the remote cloudant database. But when I set up the CouchDb locally, it does not work. 

## Your Environment

* Version used:v. 2.0.0
* Browser Name and version:Chrome
* Operating System and version (desktop or mobile): Mac

**Comment by wohali** [comment]
There is a difference between the Cloudant offering and your local CouchDB. Cloudant have a "view warming" service that automatically builds views for you in the background. CouchDB doesn't offer this functionality.

You have to build your view at least once, by querying it *without* the `stale=ok` option. Once you have done this once, subsequent queries can be made with `stale=ok`.
