### ISSUE TITLE
Call to _changes fail with couchdb behind nginx reverse proxy

### ISSUE THREAD

**Issue by jahtalab** [apache/couchdb#723]
## Expected Behavior
It should provider changes feed behind nginx

## Current Behavior
GET request to /db/_changes?style=all_docs fail with "Connection Refused" when made by nginx to couchdb server even though getting all_docs succeed 

## Your Environment
Using official couchdb Docker image

* Version used: version 2
* Browser Name and version: Chrome 59

**Comment by wohali** [comment]
See here for configuration settings for nginx to make changes feeds work: https://cwiki.apache.org/confluence/display/COUCHDB/Nginx+as+a+proxy
