### ISSUE TITLE
ddoc_cache test failing with time out

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#734]
* https://travis-ci.org/apache/couchdb/jobs/259978849
  * https://couchdb-vm2.apache.org/ci_errorlogs/travis-couchdb-259978849-2017-08-01T22:53:26.550316/couchlog.tar.gz
```
module 'ddoc_cache_lru_test'
  ddoc_cache_lru_test: check_not_started_test...[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
[0.102 s] ok
  ddoc_cache_lru_test: check_lru_test_...[0.004 s] ok
  ddoc_cache_lru_test: check_lru_test_...[0.001 s] ok
  ddoc_cache_lru_test: check_lru_test_...[0.421 s] ok
  ddoc_cache_lru_test: check_lru_test_...*timed out*
  undefined
```

**Comment by eiri** [comment]
I'm not 100% sure, but this might be a side effect of calls for `_design/_auth` going through the cache (and crashing, because of missing `_users` db).

Also noted that `make clean` and `make eunit apps=ddoc_cache suites=ddoc_cache_lru_test` _always_ crashing with timeout, but second run passes.

**Comment by wohali** [comment]
Haven't seen this in months - closing it out.
