### ISSUE TITLE
support (Zstandard?) dictionary compression

### ISSUE THREAD

**Issue by TojNALvViV** [apache/couchdb#736]
I am using CouchDB to store a large number of relatively small documents, usually between 50 and 150 bytes each. Things work fine, but I noticed that despite running compaction and having compression enabled ("snappy"), a backup of my data directory still compressed 4:1.

Looking at the shard files it seems that CouchDB is struggling to compress the documents because each of them is small.

Would it be possible to support some kind of dictionary compression, where "dictionary" documents could be added to a database? These could then be passed to a compressor which supports dictionary compression, like Zstandard. I imagine this could lead to significant storage savings, especially given that most users store documents with frequently recurring JSON property names, which are currently duplicated a (very) large number of times in storage.

I suppose that eventually it might be possible to automate this sort of compression, but allowing users to specify dictionary/template documents seems like a reasonably small, useful stepping stone along that path.

**Comment by wohali** [comment]
Our compression system is already pluggable - we support none, snappy, and zlib deflate. (Have you tried using deflate?)

Pull requests for new compression systems are welcome - why not try your hand at writing one and submitting a PR? I don't think anyone in the core team is going to have any bandwidth for this for a long while yet.

**Comment by TojNALvViV** [comment]
I haven't tried deflate, but I think the key thing here is enabling dictionary compression, as opposed to using any particular kind of compressor.

Thank you for those kind words of encouragement - I took a look at the source but am afraid that I didn't make any progress even determining where to begin. Again, I think the challenges here will all relate to enabling a dictionary compression mode (how/if to specify a dictionary, how that dictionary gets stored/maintained, etc.) rather than simply adding another compression algorithm. Coming up with a good design for that is something that I think really does need the attention of a core team member, or at least someone with a thorough understanding of CouchDB's design.

Sorry I can't be of more help here. :(
