### ISSUE TITLE
CouchDB 2.0 version indexing getting timeout for records more than 100k records

### ISSUE THREAD

**Issue by sureshsargar** [apache/couchdb#737]
## Expected Behavior
 CouchDB shouldn't timeout if we set  os_process_timeout =5000000 and indexing should built for 1.2 Lakhs  JSON Document within this time.

## Current Behavior
CouchDB indexing get timeout while accessing  using Java API ,where as same error message we could see on fauxton Web console also.

Error on Fauxton as well Java Exception:
{"error":"timeout","reason":"The request could not be processed in a reasonable amount of time."}

## Possible Solution
 solution is if we specified timeout parameter it should consider before getting timeout. whereas observation is it's not considering this parameter value.

## Steps to Reproduce (for bugs)

Load 1.2 records and create multiple views(5-6) under one design document  with emiting timestamp as key and required attribute as value. Indexing will start and it will timeout.

e.g 
emit(doc.meta.lastUpdated, {_id:doc._id,_rev:doc._rev,PatientID:PatientID,status:doc.status,priority:doc.priority,description:doc.description,start:doc.start,end:doc.end,minutesDuration:doc.minutesDuration,created:doc.created,comment:doc.comment});

## Context
we are trying to fetch couch data based on Document type  and processing for our use case. plan is will move maching records into DataLake (Relational DB)  and then built datamart out of it.

## Your Environment

* Couch 2.0
* Chrome
* Ubuntu 16.04 /Windows 10.
* Link to your project:

**Comment by rnewson** [comment]
Hi,

I think you are complaining about the time it takes to build a new view over 100,000 documents? This will take some time but the index is persisted to disk. Once built, queries will return very quickly. Any new docs will cause an incremental (small) update and queries will still be fast.

the os_process_timeout setting is for each time we evaluate javascript. In the case of view building, it would be how long it takes to run the 'map' function of your view. So you really don't need it to be so high. The default of 5000 ms is usually sufficient for view building but it's common to increase it modestly.

**Comment by rnewson** [comment]
There's a separate parameter for how long couchdb 2.0 will wait to process a request, under [fabric] and called request_timeout.

**Comment by wohali** [comment]
@sureshsargar Please let us know if this resolves your problem.

**Comment by sureshsargar** [comment]
@rnewson The problem is for first time itself it's getting failed with timeout error. i mean to say it won't able to complete indexing process. 

regarding request_timeout parameter i am looking into default.ini where under [fabric ] i couldn't find request_parameter. below are the entries present in default.ini , Are you referring the same or something different?

; [fabric]
; all_docs_concurrency = 10
; changes_duration = 
; shard_timeout_factor = 2
; uuid_prefix_len = 7

**Comment by rnewson** [comment]
Can you see the "indexer" job in GET /_active_tasks? It should be updated frequently as the build progresses.

**Comment by sureshsargar** [comment]
@rnewson  Thanks for your quick response on this.

Regarding index,Yes i could see indexer process but as soon as it reaches to 60-70 % it gives timeout error which i have posted earlier. from fabric section by default these all parameter are disabled. so which parameter should i enable?

the one more option i will try out tomorrow to make GET request on _design/<doc>/_request which will help me whether indexer is running or not based on that i can processed further. but confusion is during wait time if couch gives timeout then there is some issue i believe in Couch DB.
my expectation is for first run it might take longer time as no of documents are more but it should not timeout.

i will share my observation on tomorrow.

**Comment by sureshsargar** [comment]
@rnewson  we tried with fabric parameter,but no success. problem is when there is more than 100k records of similar type and if i want to create a view and access the same obvious indexing get triggered and it will almost make couchDB unresponsive.  i have to restart couchDB and then it will resume indexing from that point. restarting CouchDB is not feasible solution with above scenario.

Can i get more document information about Fabric parameter which you suggested?

**Comment by wohali** [comment]
Please provide any errors from your couchdb.log that relate to this issue. We can't help diagnose any errors if we don't see them.

It is understood that big views will take a long time to calculate the first time.

**Comment by rgaidjr** [comment]
Hi guys,  

how was this issue resolved?  I have similar experience with CouchDB 2.1.1,  I freshly replicated about 18 million documents, and when I trigger the indexing, it seems to process only 1.5 million "changes" at a time, and I have to keep on retriggering.  I thought it will complete in one trigger, although it takes time.

**Comment by wohali** [comment]
If your indexer job is crashing, there will be something in your couch.log file to help diagnose the problem. The original reporter never got back to us with their specifics as to what might be the problem, so we closed the ticket.

Please don't hijack other tickets - if you have logfile info to go on, please open a new ticket.

Locking.
