### ISSUE TITLE
Download link to macOS version 2.1.0 not working on http://couchdb.apache.org/#download

### ISSUE THREAD

**Issue by georglind** [apache/couchdb#743]
Sorry, but I could not find a better place to report this. If you know who to write, please tell me.

The download link for couchDB version 2.1.0 to macOS is not working on the main download page: http://couchdb.apache.org/#download. 

Modifying the hyperlink it was possible to access the 2.0.0 version, but no luck with 2.1.0.

Thanks.

**Comment by wohali** [comment]
Thanks for the report. We had to upload a new version and it got placed in the wrong directory.

Please try again, you should be able to access the download now.

Sorry for the inconvenience!
