### ISSUE TITLE
Different last_seq when calling changes, with a limit

### ISSUE THREAD

**Issue by mmihira** [apache/couchdb#748]
I'm querying the changes feed using the python library, and I intend to paginate through the changes
by setting the since parameter equal to the last_seq of the previous changes call. I would like to see all the changes.

` r = view('xx/xx', since=0, limit=10, feed='longpoll', include_docs=True)`

For curiosity I did the above call several times, and the results had a different 'last_seq' each time.
Though calling it enough times and the 'last_seq' will start repeating. 

What's happening here ? And will my approach work ?

## Expected Behavior
I would expect the 'last_seq' to be deterministic with each call ?

**Comment by wohali** [comment]
This is normal for a sharded cluster of CouchDB nodes. The actual last_seq returned in CouchDB 2.x contains additional information, including which shard/node in the system you are talking to.

You should treat the _changes token as opaque.
