### ISSUE TITLE
Age time calculate results are not updated in the couchdb view

### ISSUE THREAD

**Issue by wonderfuljamesjin** [apache/couchdb#755]
Hi

I need calculate the time age days based on the couchdb document : doc.lastupdate with current day, I defined the couchdb map view as following, I did not know why the results not update/refresh everyday? like the doc.lastupdate =2017-08-16 23:15:1, but today it still see the results as 0 age day? only after I change the view and save it, the result can be taken effect as expected, I know there is a setting in couched stale=update_after, but it is not working,  please help figure out the issue, thanks a lot

```
function(doc) {
    if (doc.type) {
       new_date = doc.lastupdate;
      var date_arr = new_date.split(" ");
      var date_aar2 = date_arr[0];
      date_aar2 = new Date(date_aar2.replace(/-/g, "/"));
      date_aar1 = new Date();
      var days = date_aar1.getTime() - date_aar2.getTime();
      var age = parseInt(days / (1000 * 60 * 60 * 24));
      emit(date_aar2,age);
       }
   }
```

**Comment by wohali** [comment]
This is not a bug with CouchDB. Please take your question to our users@couchdb.apache.org mailing list.

You can subscribe to the list by sending an email to user-subscribe@couchdb.apache.org.

**Comment by wonderfuljamesjin** [comment]
hi @wohali
thanks, and what do you mean it is not a bug with CouchDB?

**Comment by touy** [comment]
I have a similar problem , newer doc could not be in the result of the view 
_view/byIMEIGPSYEARMONTHDATE?&key=[[2018,5,27],"027029927506"]&limit=1&reduce=false

but it could show any result on 2018,5,11 
this day  I made a compact and back up ,but event I restore the data to other server the result of 2018,5,27 still not being shown , what Is the real problem here

**Comment by wohali** [comment]
@wonderfuljamesjin @touy GitHub issues is for bug reports, not for usage questions. This doesn't look like an actual bug in the software, but rather something that can be handled by our user mailing list or IRC/Slack channel.

**Comment by touy** [comment]
yes, today I recheck my code, then found that I put {docs:arr} to a single insert function not a bulk function, it was my mistake and took me days to fix it ,
