### ISSUE TITLE
Race condition in couch_mrview_ddoc_updated_tets

### ISSUE THREAD

**Issue by davisp** [apache/couchdb#757]
I've seen this assertion fail locally:

https://github.com/apache/couchdb/blob/master/src/couch_mrview/test/couch_mrview_ddoc_updated_tests.erl#L106

The reason is that it appears the query succeeds before the design doc update message kills the indexer. We should add a meck synchronization point so that we can ensure that the process is always alive when the message is sent.

**Comment by mayya-sharipova** [comment]
PR for this issue was +1ed, but one mango test fails in Travis. This test will be fixed separately by @tonysun83

**Comment by eiri** [comment]
Fixed by #764

**Comment by eiri** [comment]
Fixed by #764
