### ISSUE TITLE
Compaction fails due to a file corruption

### ISSUE THREAD

**Issue by sajeeval** [apache/couchdb#758]
We have a couch database which is 3.5G in size. Whenever compaction is initiated (automatically or scheduled) it fails, and log files suggest that is due to a file corruption. 
## Expected Behavior
Ideally compaction should be successful, regardless of how it is invoked.

## Current Behavior

As of now compaction fails with following error and database continues to grow.
```
[Thu, 17 Aug 2017 05:01:18 GMT] [info] [<0.1704.0>] Starting compaction for db "mydb"
[Thu, 17 Aug 2017 05:01:18 GMT] [info] [<0.1745.0>] 127.0.0.1 - - POST /mydb/_compact 202
[Thu, 17 Aug 2017 05:01:18 GMT] [error] [<0.1704.0>] ** Generic server <0.1704.0> terminating 
** Last message in was {'EXIT',<0.1971.0>,
                               {file_corruption,<<"file corruption">>}}
** When Server state == {db,<0.1703.0>,<0.1704.0>,<0.1971.0>,
                            <<"1502945833413845">>,<0.1705.0>,<0.1701.0>,
                            <0.1707.0>,
                            {db_header,6,979677,0,
                                {3446674981,{23249,141097,705848231},50545772},
                                {3446676970,164346,12782565},
                                {3446689924,[],8484},
                                287,3151060956,1178745538,1000},
                            979677,
                            {btree,<0.1701.0>,
                                {3446674981,{23249,141097,705848231},50545772},
                                #Fun<couch_db_updater.10.21234455>,
                                #Fun<couch_db_updater.11.21234455>,
                                #Fun<couch_btree.5.131744168>,
                                #Fun<couch_db_updater.12.21234455>,snappy},
                            {btree,<0.1701.0>,
                                {3446676970,164346,12782565},
                                #Fun<couch_db_updater.13.21234455>,
                                #Fun<couch_db_updater.14.21234455>,
                                #Fun<couch_btree.5.131744168>,
                                #Fun<couch_db_updater.15.21234455>,snappy},
                            {btree,<0.1701.0>,
                                {3446689924,[],8484},
                                #Fun<couch_btree.3.131744168>,
                                #Fun<couch_btree.4.131744168>,
                                #Fun<couch_btree.5.131744168>,nil,snappy},
                            979677,<<"mydb">>,
                            "/var/lib/couchdb/mydb.couch",
                            [#Fun<couch_doc.8.104915127>],
                            [{<<"admins">>,
                              {[{<<"names">>,
                                 [<<"mydbSYNCUSER54CB0F41">>]},
                                {<<"roles">>,[<<"admin">>]}]}},
                             {<<"readers">>,
                              {[{<<"names">>,
                                 [<<"mydbSYNCUSER54CB0F41">>]},
                                {<<"roles">>,[<<"reader">>]}]}}],
                            1178745538,
                            {user_ctx,null,[],undefined},
                            nil,1000,
                            [before_header,after_header,on_file_open],
                            [{user_ctx,
                                 {user_ctx,<<"support">>,
                                     [<<"_admin">>],
                                     <<"{couch_httpd_auth, cookie_authentication_handler}">>}}],
                            snappy,nil,nil}
** Reason for termination == 
** {file_corruption,<<"file corruption">>}
```

## Steps to Reproduce (for bugs)
This is easy to reproduce when we already have a database with a corrupted document. But we really need to find why there is a corruption at the first place.

## Context

Since compaction is failing, database size continues to grow. This affect the performance and user experience

## Your Environment

* Version used:1.6.1
* Operating System and version (desktop or mobile): Ubuntu 14.04

**Comment by sajeeval** [comment]
This issue is visible when
1. Compaction is running
2. Duplicate the database using _replicate
3. When we use _bulk_docs to create a new database using the original

However, 
1. We can see the document using curl commands. 
2. We can get all revisions using curl commands.

**Comment by sajeeval** [comment]
Couch log is attached.
[couch_error.txt](https://github.com/apache/couchdb/files/1234192/couch_error.txt)

**Comment by sajeeval** [comment]
Our primary concern is to find the root cause for this corruptions.

**Comment by wohali** [comment]
I'm sorry to hear you are experiencing this.

Does your server show any disk failure or error messages? You can find these in `/var/log/messages` and in the output of the command `sudo dmesg`.

**Comment by sajeeval** [comment]
Hi, 
Let me get back to you on this.
Regards,
Sajeeva.

**Comment by sajeeval** [comment]
Hi wohali, 
We didn't experience any disk failures. dmesg log is attached. 
[dmesg.log.gz](https://github.com/apache/couchdb/files/1238450/dmesg.log.gz)

**Comment by sajeeval** [comment]
We experience the same issue in few other environments. I will update this ticket with those information soon.

**Comment by wohali** [comment]
Did you ever run out of disk space on these hosts?

**Comment by sajeeval** [comment]
Hi, 
We do a lot of modifications and deletions on our databases, and those needs regular compactions and purging. 
We have scheduled compaction process to be executed from 2.30 to 6.30 and we have scheduled purging process outside of that window. 

What normally happens is that since compaction fails due to the corruptions, database continues to grow and that leads to low disk space. 

I will share log files of other incidents too.

**Comment by sajeeval** [comment]
Hi,
Here is another incidents where compaction fails to run. 
[compaction_error.txt.gz](https://github.com/apache/couchdb/files/1240876/compaction_error.txt.gz)

**Comment by wohali** [comment]
Have you ever hit 100% disk space utilization (0 free space) on the nodes hosting these databases? This could have lead to database corruption.

**Comment by sajeeval** [comment]
Nope, we haven't hit 100% in the history. We have alerts in place which send notifications whenever it reaches 80%. 
Thanks.

**Comment by sajeeval** [comment]
Hi,
Is there any way to interpret what is in the error log? It just seem to be unreadable. 
[couch_error.txt](https://github.com/apache/couchdb/files/1262906/couch_error.txt)

**Comment by wohali** [comment]
The error is clear - your database has file corruption. The binary data there is showing the nodes in the btree, but a byte-by-byte analysis is not something anyone on the project right now has time to complete.

The most likely scenarios for this are that you are in a virtualised environment where the disk goes away, you have `delayed_commits` set to `true` and a disk is intermittently failing (lesson: ALWAYS set `delayed_commits` to `false`!), or you are using network-attached storage (such as EBS) and the volume has become corrupted. If you're in a cloud/hosted environment, you may want to check with your hosting provider to determine if anything can be done to guarantee disk performance. Another possibility is failing RAM that caused a bit-flip, or (yes, really) cosmic rays doing the same. The typical safeguard for this in production is to only run on servers with ECC RAM.

CouchDB 1.6.1 has been running in the field for many years on hundreds of thousands of servers, and there are no known issues that definitively cause corruption in databases aside from the well-known scenarios described above.

Your best options are:

1. Restore the database from backup prior to when file corruption occurred. (You are backing up your server, aren't you? 😉 )
2. Write a custom replication to read documents from the database and skip documents that fail. You may not be able to use the `/{db}/_changes` feed for this if there is corruption in the sequence; try using `/{db}/_all_docs` if this is true
3. [Neighbourhoodie](https://neighbourhood.ie/) provides a professional (paid) CouchDB database recovery service when databases have been corrupted if you are completely unable to recover the data yourself. You will need to provide them with a zip/tar of the database directory for this service.

**Comment by wohali** [comment]
One last comment - you mention purging. Do you mean use of the actual `/{db}/_purge` endpoint, or just document deletion? As the warning in the documentation states, this is an endpoint of last resort. It's possible that use of `/{db}/_purge` for anything other than the occasional deletion may have introduced corruption -- this is a usage scenario the CouchDB team doesn't support.

> [Purging a document](http://docs.couchdb.org/en/1.6.1/api/database/misc.html?highlight=purge) from a database should only be done as a last resort when sensitive information has been introduced inadvertently into a database. In clustered or replicated environments it is very difficult to guarantee that a particular purged document has been removed from all replicas. Do not rely on this API as a way of doing secure deletion.
