### ISSUE TITLE
replicate couchdb

### ISSUE THREAD

**Issue by linoy13** [apache/couchdb#770]
Hello
I am new to the field of the couchDB and created a database under my username.
When I try to replicate a database to another computer on the same network under the username of my colleague it fails.
  My question is whether this can be done through a fauxton interface or that other interfaces should be used?

What I tried to do was:
replication-->source: local --> target: new remote db-->                                                                                  -->https://colleague_username:colleague_password@colleagueIP:5984/db name

it says "running" but my colleague do not see it on her computer.

All settings are according to the directory of the official website.
I'm probably doing something wrong or trying something that's just impossible.

Thanks for the helpers.

**Comment by wohali** [comment]
You deleted most of the form for the issue so what we need to know is missing:

1. Version of CouchDB on your and your colleague's machine
2. What browser & version on your machines
3. Did you replicate using Fauxton or cURL?
4. Can you take a screenshot or provide the exact command you ran?

**Comment by linoy13** [comment]
1. Version of CouchDB- 2.1.0
2. Chrome
3.Fauxton

Thanks

**Comment by wohali** [comment]
> Can you take a screenshot of your creation of the replication in Fauxton?

**Comment by linoy13** [comment]
![replication screenshot](https://user-images.githubusercontent.com/31275163/29744181-443b2328-8aa8-11e7-8aa1-15a63e26b25d.png)

**Comment by garrensmith** [comment]
Once you click start replication then click back on the replication link. You should have a list of replications. Does any errors appear? You should be able to click on the error to give you more details on what is happening.

**Comment by linoy13** [comment]
![1](https://user-images.githubusercontent.com/31275163/29772716-a627a682-8c02-11e7-9da5-23b54f10267e.PNG)
![2](https://user-images.githubusercontent.com/31275163/29772727-b04fb744-8c02-11e7-9657-1dacf4bdbb33.PNG)

**Comment by garrensmith** [comment]
Is the port correct on the target? It is using port 80?

**Comment by linoy13** [comment]
the port we using is 5984.

**Comment by garrensmith** [comment]
Ok, you need to specify it in the replication. So the remote url needs to be:

http://USERNAME:PASSWORD@ip-address:5984/DB_NAME

**Comment by linoy13** [comment]
I tried it
still not working.
![default](https://user-images.githubusercontent.com/31275163/29780873-0842cb40-8c20-11e7-8825-40036e4b3c05.PNG)

**Comment by linoy13** [comment]
I am on 192.168.1.10
And my colleague on 192.168.1.18

**Comment by wohali** [comment]
Try changing replication source from "Local database" to "Remote database" and specify the database address as `http://admin:password@127.0.0.1:5984/dbname` . See if this works?
