### ISSUE TITLE
_dbs.couch keeps growing when purging -> compacting -> recreating DBs

### ISSUE THREAD

**Issue by heikomat** [apache/couchdb#772]
The file `var/lib/couchdb/_dbs.couch` always keeps growing, it never shrinks, even when purging and compacting databases. Last time i left my application alone for three weeks, and the `_dbs.couch` grew to 37 GB. Fauxten showed, that the CouchDB only contains up to 60 Documents, but this file still keeps growing, until it fills all the space available

## Expected Behavior
When purging + compacting a database, it should free up disk space

## Current Behavior
no matter what i try, the `_dbs.couch` never shrinks in size

## Steps to Reproduce
1. create a database and put some documents into it
2. purge that database
3. create a new database, with the same name and put some documents into it
4. purge that database
5. rinse and repeat (a lot of times)

from time to time, try compacting that database to free up disk space. this didn't work for me

## Context

- At any given moment, my CouchDB has at max 4 Databases with a total of about 60 documents
- my node application [purges](http://docs.couchdb.org/en/2.0.0/api/database/misc.html#db-purge) (using [pouchdbs destroy](https://pouchdb.com/guides/compact-and-destroy.html#destroying-a–database)) and recreates these databases periodically (some of them every two seconds, others every 15 minutes)
- The databases are always recreated with the newest entries
- The reason for purging the databases, instead of deleting their documents is, that i'd otherwise have a huge amount of deleted documents, and my web-client can't handle syncing all these deleted documents
- after a couple of weeks, the PI this was running on had no more disk space left, and the application stopped working

I tried the following things:
- running everything on an x86 machine (osx)
- running couchdb without docker (because of [this info](https://stackoverflow.com/questions/36969395/docker-container-keeps-growing/36969502#36969502))
- using couchdb 2.1
- running compaction manually (which didn't do anything)
- googling for about 3 days now

The result is always the same

## Your Environment
* Version used: 2.0.0
* Operating System and version (desktop or mobile): Rapsberry PI 3 with docker ([this](https://hub.docker.com/r/matthiasg/rpi-couchdb/) base image)
* Link to your project: this is a private project, i unfortunately can't provide a link

I asked [this question on stackoverflow](https://stackoverflow.com/questions/45826795/why-does-couchdbs-dbs-couch-keep-growing-when-purging-compacting-dbs) yesterday, and someone suggested that this sounds like a potential bug

**Comment by nickva** [comment]
@heikomat curious, have you tried compacting the _dbs db itself?

**Comment by rnewson** [comment]
try `curl localhost:5986/_dbs -XPOST -Hcontent-type:application/json`

**Comment by rnewson** [comment]
For explanation, the _dbs database is a meta-database. It records the locations of all the shards of your clustered databases, so it needs compacting separately. You can enable the compaction daemon to do this for you, and we enable it by default in the recent 2.1.0 release.

**Comment by heikomat** [comment]
@nickva @rnewson yeah! this did it! compacting the `_dbs` database and then restarting the docker container cleared up all the space! :)

@rnewson i appreciate the info. I tried googleing what exactly that file is, without success. Knowing that it is an actual couch-database, and what it does is useful information!

what config do i need to set, to enable the comaction-daemon in CouchDB 2.0.0?

**Comment by heikomat** [comment]
@nickva @rnewson one of you may now claim the points on stackoverflow by answering the question, as i will accept it

**Comment by rnewson** [comment]
add this to the end of your local.ini file and restart couchdb.

```
[compactions]
_default = [{db_fragmentation, "70%"}, {view_fragmentation, "60%"}]
```

**Comment by heikomat** [comment]
@rnewson i wanted to ask what exactly this config does, but then i found it here: http://docs.couchdb.org/en/2.0.0/config/compaction.html?highlight=db_fragmentation#compaction-daemon-rules

just leaving this here for future visitors of this issue

**Comment by rnewson** [comment]
cool, good thought.
