### ISSUE TITLE
Error status zero, Index shutdown by monitor notice for db

### ISSUE THREAD

**Issue by GeorgeAppleton** [apache/couchdb#776]
## Expected Behavior
Syncing with my couchDB locally works perfectly fine but trying to do so remotely throws strange errors and fails

## Current Behavior
Currently the following error is returned to my client when I try to access my db

`{"code":"ETIMEDOUT","status":0,"result":{"ok":false,"start_time":"2017-08-24T10:31:20.296Z","docs_read":0,"docs_written":0,"doc_write_failures":0,"errors":[],"status":"aborting","end_time":"2017-08-24T10:31:30.305Z","last_seq":0}}`

And my couchDB logs give me

```
2017-08-24T10:28:15.136000Z couchdb@localhost <0.17927.42> -------- Index shutdown by monitor notice for db: shards/80000000-9fffffff/_replicator.1503391828 idx: _design/_replicator
[info] 2017-08-24T10:28:15.139000Z couchdb@localhost <0.17927.42> -------- Closing index for db: shards/80000000-9fffffff/_replicator.1503391828 idx: _design/_replicator sig: "3e823c2a4383ac0c18d4e574135a5b08" because normal
[info] 2017-08-24T10:29:53.868000Z couchdb@localhost <0.52.0> -------- alarm_handler: {set,{system_memory_high_watermark,[]}}
[info] 2017-08-24T10:30:53.885000Z couchdb@localhost <0.52.0> -------- alarm_handler: {clear,system_memory_high_watermark}
[info] 2017-08-24T10:32:14.843000Z couchdb@localhost <0.22959.42> -------- Opening index for db: shards/80000000-9fffffff/_replicator.1503391828 idx: _design/_replicator sig: "3e823c2a4383ac0c18d4e574135a5b08"

```

## Possible Solution
I honestly have no idea why this bug is occurring, it has been confusing the hell out of me for weeks

## Steps to Reproduce (for bugs)
No idea, I thought I was doing everything normally, set up the system tables using single node setup. Created a user dbreader with standard details (login works fine), although I do notice that I can't create members for databases for some reason, it say they're added when I add them but it doesn't actually add them. I can't access any of my databases remotely at all. CORS is enabled and accepting from *. Bind addresses are set to 0.0.0.0

## Context
Makes the database unusable for testing my app on mobile devices

## Your Environment
I'm using pouchdb within phonegap. I've tested this bug from multiple windows computers and android devices with the same results. CouchDB is hosted on my windows computer which I use for development.

I hope the error messages mean something to someone here and can be helpful, I'm lost.

**Comment by wohali** [comment]
Sounds like a configuration issue. Those are normal lines in the CouchDB log, not errors.

Root cause that replication fails is that you can't access CouchDB from off-machine. You should be able to, from another computer. hit http://<your-server>:5984/ in a browser or with curl and see a response.

You do NOT want to bind the [httpd] (port 5986) interface to 0.0.0.0. This is a huge security risk. Only bind the [chttpd] (port 5984) interface to 0.0.0.0.

Also, try disabling CORS for now. You can re-enable it once you're able to see CouchDB from another machine.

**Comment by GeorgeAppleton** [comment]
Hi wohali,

> Root cause that replication fails is that you can't access CouchDB from off-machine. 

That was the whole problem

Yeah I know about the security risk for 5986 being bound to 0.0.0.0, I was just trying stuff out. The config error never got fixed, no idea what the problem was or is. Doesn't matter now anyway since I have the production database up and working just fine so I'm using that for testing until launch. This issue already gave me enough headaches and it was likely just something wrong with my machines config since other couchdb setups I've done work just fine.

**Comment by AzfaarQureshi** [comment]
Hi,

I think I'm having a similar issue where the following snippet is repeatedly posted to the logs:

```logs
[info] 2018-10-30T15:38:32.533128Z nonode@nohost <0.32529.1> -------- Index shutdown by monitor notice for db: shards/80000000-9fffffff/_replicator.1540909992 idx: _design/_replicator
[info] 2018-10-30T15:38:32.534371Z nonode@nohost <0.32529.1> -------- Closing index for db: shards/80000000-9fffffff/_replicator.1540909992 idx: _design/_replicator sig: "3e823c2a4383ac0c18d4e574135a5b08" because normal
[info] 2018-10-30T15:41:30.620214Z nonode@nohost <0.4769.2> -------- Opening index for db: shards/80000000-9fffffff/_replicator.1540909992 idx: _design/_replicator sig: "3e823c2a4383ac0c18d4e574135a5b08"
```

>Root cause that replication fails is that you can't access CouchDB from off-machine. You should be able to, from another computer. hit http://:5984/ in a browser or with curl and see a response.

it was mentioned in an earlier comment that it could be a configuration issue. I can connect to couchdb using localhost (`curl http://127.0.0.1:5984/_utils/#verifyinstall` returns no error) however I cannot connect from outside the VM. 

Which configuration parameters could I be missing? Any help would be much appreciated, thanks :)

**Comment by wohali** [comment]
@AzfaarQureshi That logging in the logfile is *normal*.

You need to change your address binding; CouchDB binds to only 127.0.0.1 by default.

Find the `[chttpd]` section in your `etc/local.ini` file and update as follows:

```ini
[chttpd]
;port = 5984
bind_address = 0.0.0.0
```

This will bind CouchDB's clustered port to all interfaces on your machine.
