### ISSUE TITLE
Remove GET /_log documentation (endpoint deprecated)

### ISSUE THREAD

**Issue by olivenvrac** [apache/couchdb#779]
## Expected Behavior
I want to read the log with the URL of the server, but it doesn't work
can anybody else give me a solution or can telle me wht's wrong in my conf or URL or anything else ? 

## Current Behavior
 when i send a get on the url : http://user:mdp@serveur:port/_log
have got this return :
{"error":"not_found","reason":"Database does not exist."}

I tried with the node : 
http://user:mdp@serveur:port/_node/nodename/_log
have got this return : 
{"error":"not_found","reason":"missing"}

## Context
the log file "couchdb.log" is OK and the messages are writting correctly in it.
the rights on the log seems to be good : -rwxr-x---
configuration in the .ini file is : 
[log]
file = ./var/log/couchdb.log
writer = file

## Your Environment
Version  CouchDB : 2.0.0
OS : RHEL 7
client : Curl 7.19.7

**Comment by wohali** [comment]
I believe this endpoing moved to the `/_node/<nodename>/_log` endpoint. Your nodename will depend on the `-name` setting in your `vm.args` file.

**Comment by olivenvrac** [comment]
Thank's for the reply wohali.
I thought the same thing, but it doesn't work either with this path : 
http://user:mdp@serveur:port/_node/<nodename>/_log
i got the nodename in the vm.args or the url http://user:mdp@serveur:port/_membership wich is the same thing.
I don't understand why it doesn't work
i verify the configuration to and restart CouchDB : 
section [httpd_global_handlers] i'v got the option _log and the associate  value {couch_httpd_misc_handlers, handle_log_req}
It's sure that the documentation is not right or not sufficiently explicit.
an other idea ?

**Comment by olivenvrac** [comment]
précision : my request is correctly made with a admin user

**Comment by wohali** [comment]
My mistake. It looks like this endpoint has been removed in 2.x. Most likely this is because our logging backend now supports things like syslog and rsyslog directly, meaning that there may not even be a persistent storage mechanism through which the log can even be retrieved.

I'll reopen this ticket as a reminder for us to remove documentation for the `_log` endpoint and add it to the list of breaking changes for 2.x.

**Comment by olivenvrac** [comment]
You'r welcome. Thanks for the rapidity of your responses
So, i renounce to use  this feature even if it should work in version 2.0 And I still do not understand why it doesn't

**Comment by wohali** [comment]
Oh, the documentation was already updated with v2.0 docs:

```
whatsnew/2.0.rst:* The ``/_log`` endpoint was removed.
```

Closing this issue.
