### ISSUE TITLE
Filter documents on _changes feed with selector yields to wrong result

### ISSUE THREAD

**Issue by orolle** [apache/couchdb#780]
I use a complex selector query to filter complex documents via _find and _changes feed (since=0). Both results should contain same documents.

Selector
Line: "$gte": 1000
```
  {
    "selector": {
      "_id": {
        "$gte": "ServiceReport_",
        "$lte": "ServiceReport~"
      },
      "$or": [
        {
          "detail.invoices": {
            "$elemMatch": {
              "netwr_sum": {
                "$gte": 1000
              }
            }
          }
        }
      ]
    },
    "limit": 999999999
  }
```

Document  (simplified from original doc)
Line: "netwr_sum": 992.02
```
{
  "_id": "ServiceReport_123456",
  "description": {
    "desc": "bla bla",
    "value": 3.14
  },
  "detail": {
    "equipment": {
      "type": "BBB"
    },
    "serviceReport": {
      "sr": 123456
    },
    "invoices": [
      {
        "field1": 456457,
        "field1": "M",
        "netwr_sum": 992.02,
        "cur": "EUR"
      }
    ],
    "positions": [
      {
        "posnr": 1,
        "arktx": "Article 54"
      },
      {
        "posnr": 2,
        "arktx": "Article 44"
      }
    ],
    "message": "bla"
  }
}
```

## Expected Behavior
Should not return the document above. _find behaves as expected / correctly.

## Current Behavior
_changes returns above document. This is wrong.

## Steps to Reproduce (for bugs)
1. Insert document above in database
2. run _find and get empty result
3. run _changes and get wrong result

## Context
I use the _changes with since parameter to find the delta of newly created / changed documents and filter with the mango query to extract only the interesting documents for further processing.

## Your Environment
* Version used: couchdb 2.1.0, git branch master, commit 83a5ac5b358a7a8b32ed092ddde32c2676859bb1
* Browser Name and version: LightCouch http://www.lightcouch.org/ 0.1.9-SNAPSHOT & Fauxton
* Operating System and version (desktop or mobile):  Ubuntu 14.04

**Comment by willholley** [comment]
@orolle I can't reproduce this locally on master. I tested your filter with `"$gte": 1000` and the document is not returned. Changing it to `"$lte": 1000`, the document is returned. Also note that the document above isn't valid JSON (duplicate invoices.field1).

Can you post a full reproduction including `curl` commands to create/insert the document?

**Comment by orolle** [comment]
I could not reproduce it with curl. Thanks a lot for this fast support!

**Comment by orolle** [comment]
I found the bug in my code. Its not a couchdb issue.
You can close this bug.
Thanks a lot!
