### ISSUE TITLE
[Question] upgrading PPA couch 1.6 to 2.1

### ISSUE THREAD

**Issue by andreyvk** [apache/couchdb#787]
Hi, 

Are there any guidelines on how to upgrade existing couch 1.6 installation to couch 2.1 if I was using a PPA from https://launchpad.net/~couchdb/+archive/ubuntu/stable?

Please, just correct me if im wrong, that I could just install 2.1 over 1.6 using [installation guidelines](http://docs.couchdb.org/en/master/install/unix.html#installation-on-unix-like-systems) and then use `couchup` to migrate. Or should I uninstall 1.6 first and then install 2.1 and use `couchup`?

**Comment by wohali** [comment]
You should be able to just upgrade to the 2.1 packages and use `couchup` to migrate your databases. 

The new packages were designed for upgrade via `apt` or `apt-get`, which will uninstall 1.6 and install 2.1 in a single step. Further, the 2.1 packages still store databases at `/var/lib/couchdb` so your databases should be present for a `couchup` based migration.
