### ISSUE TITLE
CouchDB 2.1 unable to restart after a crash

### ISSUE THREAD

**Issue by mgesmundo** [apache/couchdb#789]
I use CouchDB in a ee test for a browser app that sync a PouchDB with a CouchDB.

## Expected Behavior
Running several times the test CouchDB run normally.

## Current Behavior
After a while CouchDB crashes. If I try to restart it crashes after seconds.

## Possible Solution
Restart the Mac.

## Context
This is the last entries of the log file:

[error] 2017-09-04T17:47:28.643449Z couchdb@localhost emulator -------- Error in process <0.2568.0> on node 'couchdb@localhost' with exit value: {{badmatch,{error,enoent}},[{couch_compaction_daemon,abs_path,1,[{file,"src/couch_compaction_daemon.erl"},{line,526}]},{couch_compaction_daemon,free_space_rec,2,[{file,"src/couch_compaction_daemon.erl"},{line,517}]},{couch_compaction_daemon... 
[error] 2017-09-04T17:47:28.644509Z couchdb@localhost <0.2566.0> -------- gen_server couch_compaction_daemon terminated with reason: {compaction_loop_died,{{badmatch,{error,enoent}},[{couch_compaction_daemon,abs_path,1,[{file,"src/couch_compaction_daemon.erl"},{line,526}]},{couch_compaction_daemon,free_space_rec,2,[{file,"src/couch_compaction_daemon.erl"},{line,517}]},{couch_compaction_daemon,can_db_compact,2,[{file,"src/couch_compaction_daemon.erl"},{line,327}]},{couch_compaction_daemon,maybe_compact_db,3,[{file,"src/couch_compaction_daemon.erl"},{line,164}]},{couch_compaction_daemon,'-compact_loop/1-fun-0-',3,[{file,"s..."},...]},...]}}
  last msg: {'EXIT',<0.2568.0>,{{badmatch,{error,enoent}},[{couch_compaction_daemon,abs_path,1,[{file,"src/couch_compaction_daemon.erl"},{line,526}]},{couch_compaction_daemon,free_space_rec,2,[{file,"src/couch_compaction_daemon.erl"},{line,517}]},{couch_compaction_daemon,can_db_compact,2,[{file,"src/couch_compaction_daemon.erl"},{line,327}]},{couch_compaction_daemon,maybe_compact_db,3,[{file,"src/couch_compaction_daemon.erl"},{line,164}]},{couch_compaction_daemon,'-compact_loop/1-fun-0-',3,[{file,"src/couch_compaction_daemon.erl"},{line,141}]},{couch_server,'-all_databases/2-fun-0-',4,[{file,"src/couch_server.erl"},{line,273}]},{filelib,do_fold_files2,8,[{file,"filelib.erl"},{line,184}]},{couch_server,all_databases,2,[{file,"src/couch_server.erl"},{line,262}]}]}}
     state: {state,<0.2568.0>,[]}
[error] 2017-09-04T17:47:28.644854Z couchdb@localhost <0.2566.0> -------- CRASH REPORT Process couch_compaction_daemon (<0.2566.0>) with 0 neighbors exited with reason: {compaction_loop_died,{{badmatch,{error,enoent}},[{couch_compaction_daemon,abs_path,1,[{file,"src/couch_compaction_daemon.erl"},{line,526}]},{couch_compaction_daemon,free_space_rec,2,[{file,"src/couch_compaction_daemon.erl"},{line,517}]},{couch_compaction_daemon,can_db_compact,2,[{file,"src/couch_compaction_daemon.erl"},{line,327}]},{couch_compaction_daemon,maybe_compact_db,3,[{file,"src/couch_compaction_daemon.erl"},{line,164}]},{couch_compaction_daemon,'-compact_loop/1-fun-0-',3,[{file,"s..."},...]},...]}} at gen_server:terminate/7(line:804) <= proc_lib:init_p_do_apply/3(line:237); initial_call: {couch_compaction_daemon,init,['Argument__1']}, ancestors: [couch_secondary_services,couch_sup,<0.201.0>], messages: [], links: [<0.2374.0>], dictionary: [], trap_exit: true, status: running, heap_size: 987, stack_size: 27, reductions: 2819
[error] 2017-09-04T17:47:28.645534Z couchdb@localhost <0.2374.0> -------- Supervisor couch_secondary_services had child compaction_daemon started with couch_compaction_daemon:start_link() at <0.2566.0> exit with reason {compaction_loop_died,{{badmatch,{error,enoent}},[{couch_compaction_daemon,abs_path,1,[{file,"src/couch_compaction_daemon.erl"},{line,526}]},{couch_compaction_daemon,free_space_rec,2,[{file,"src/couch_compaction_daemon.erl"},{line,517}]},{couch_compaction_daemon,can_db_compact,2,[{file,"src/couch_compaction_daemon.erl"},{line,327}]},{couch_compaction_daemon,maybe_compact_db,3,[{file,"src/couch_compaction_daemon.erl"},{line,164}]},{couch_compaction_daemon,'-compact_loop/1-fun-0-',3,[{file,"s..."},...]},...]}} in context child_terminated
[error] 2017-09-04T17:47:28.645854Z couchdb@localhost <0.2374.0> -------- Supervisor couch_secondary_services had child compaction_daemon started with couch_compaction_daemon:start_link() at <0.2566.0> exit with reason reached_max_restart_intensity in context shutdown
[error] 2017-09-04T17:47:28.645990Z couchdb@localhost <0.202.0> -------- Supervisor couch_sup had child couch_secondary_services started with couch_secondary_sup:start_link() at <0.2374.0> exit with reason shutdown in context child_terminated
[error] 2017-09-04T17:47:28.646164Z couchdb@localhost <0.202.0> -------- Supervisor couch_sup had child couch_secondary_services started with couch_secondary_sup:start_link() at <0.2374.0> exit with reason reached_max_restart_intensity in context shutdown
[error] 2017-09-04T17:47:28.646213Z couchdb@localhost <0.384.0> -------- Supervisor received unexpected message: {'DOWN',#Ref<0.0.0.2567>,process,<0.414.0>,killed}

[info] 2017-09-04T17:47:28.646263Z couchdb@localhost <0.7.0> -------- Application couch exited with reason: shutdown

## Environment

* Version used: 2.1.0
* Browser Name and version: Firefox 55.0.3
* Operating System and version: MacOS Sierra 10.12.6

**Comment by willholley** [comment]
I think this is the same issue as https://github.com/apache/couchdb/issues/732; in turn, a result of https://bugs.erlang.org/browse/ERL-343. Check whether you have any devices with spaces in their mount points - ejecting them should fix this.

**Comment by mgesmundo** [comment]
Thank you @willholley! I unmounted all devices with a space and now CouchDB works fine as usual.
All the best.
