### ISSUE TITLE
binary_to_term/1 unknown_error : badarg at high rate request

### ISSUE THREAD

**Issue by Tienipia** [apache/couchdb#794]
## Story
When I try to request too fast to server(like over 1000req/sec), sometimes server send me 500 Interner Server Error and server log under 'Error log'. It doesn't big issue to running server but it's little bit annoying, cause I need to re-request to server.

## Possible Solution
According to Erlang official documents, using [binary_to_term/1](http://erlang.org/doc/man/erlang.html#binary_to_term-1) under untrusted source is not recommend. Officail recommend to use [binary_to_term/2](http://erlang.org/doc/man/erlang.html#binary_to_term-2) to prevent DoS attack or high load situation.

## Environment
* Linux couchdb-local 4.10.0-33-generic #37-Ubuntu SMP Fri Aug 11 10:55:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* v. 2.1.0-f72820910
* 4 core / 4GB memory

## Error log
`[error] 2017-09-06T08:28:43.948227Z couchdb@192.168.135.194 <0.22970.339> 2e191baa82 req_err(2175836054) unknown_error : badarg
    [<<"erlang:binary_to_term/1">>,<<"fabric_view_changes:do_unpack_seqs/2 L415">>,<<"fabric_view_changes:send_changes/6 L145">>,<<"fabric_view_changes:go/5 L66">>,<<"chttpd:process_request/1 L295">>,<<"chttpd:handle_request_int/1 L231">>,<<"mochiweb_http:headers/6 L91">>,<<"proc_lib:init_p_do_apply/3 L247">>]`

**Comment by wohali** [comment]
I doubt the issue is erlang:binary_to_term/1.

If you are trying to handle >1000 req/sec you might need more RAM. Have you tried this on a bigger machine?

**Comment by janl** [comment]
In addition, it would be great to hear what request(s) exactly are causing this.

The stack trace here mentions fabric view changes, so there is some cluster coordination going on, under load this could be cause by a timeout or something tripping up the message receiver using `binary_to_term/1`, but it’s not that we are parsing input from an untrusted source there, so the point about `binary_to_term/2` is probably a red herring.

Please re-open with extra info, thanks!
