### ISSUE TITLE
Upgrade of 1.6.1 to fix NSSM issue?

### ISSUE THREAD

**Issue by ramotswa** [apache/couchdb#795]
Hello All,
We are using CouchDB 1.6.1 and have recently upgraded to a Windows 10 OS. 
~~For better or~~ for worse, we are stuck with a device that is only 32bit capable (and so the OS is x86). 
We have come across the NSSM issue (as per [this issue](https://github.com/apache/couchdb/issues/508)) and see that that has been fixed in CouchDB 2.1.0. 
Having looked for a x86 version of 2.1.0 I see that you state that this isn't available (and won't be). 
So; are you thinking of fixing the NSSM issue in 1.6.1 and release a 1.6.2 version which would be x86?

Additionally, if that is not the case - is it possible to build 2.1.0 from source for a x86 environment?

Many thanks,

Toby

**Comment by wohali** [comment]
You should just be able to copy over the new nssm.exe to a 1.6.1 install and fix it that way.

I don't have bandwidth to re-release 1.6.1 right now, but you can try compiling it yourself. Similarly there are reasons why an x86 build of 2.x is not forthcoming, but you can try building it yourself.

**Comment by ramotswa** [comment]
Thanks @wohali  - when you say copy nssm.exe over, am I just dropping it into my C:/Program Files/Apache Software Foundation/CouchDB/bin (?) folder? I can't find an existing nssm.exe to replace so unsure where to put it.

**Comment by wohali** [comment]
Sorry, I flaked out. 1.6.1 doesn't rely on nssm.exe at all, it was prior to the rework of the service. What problem are you running into?

**Comment by ramotswa** [comment]
Same as the issue linked; that the service doesn't automatically start in
windows 10. Was working fine for windows 8.1, but after fresh install of
1.6.1 on 10 and checking the 'install as a setting and start' and then a
device restart the service hasn't started (although it's set to automatic).

**Comment by ramotswa** [comment]
For now we have just added a scheduled task on windows 10 to run a quick `net start "CouchDB` call to start the service on every log on. Any additional hints as how to make it work properly would be appreciated, but we're ok with this workaround for now. Happy to close.

**Comment by wohali** [comment]
Thanks, gonna close for now. Appreciate the workaround.
