### ISSUE TITLE
Polling interval not configurable

### ISSUE THREAD

**Issue by Gedos** [apache/couchdb#809]
Good morning. It seems like the polling frequency of a continuous replication rule isn't configurable at all. Checking the logs, it looks like the target is checking the source for document changes every 5 seconds. No matter what I try to change, it just doesn't seem to deviate from this 5 second rule. Is this 5 second polling interval intended as an unchangeable variable or am I missing something?

**Comment by wohali** [comment]
Continuous replication doesn't poll. The replicator sits on a `_changes` feed that publishes changes to the database as they occur. There is no introduced delay, but changes may not be published on the feed instantaneously.
