### ISSUE TITLE
Debian Buster package missing

### ISSUE THREAD

**Issue by drasko** [apache/couchdb#819]
Current Debian Testing is codenamed Buster. Distro is missing for .deb package download: https://apache.bintray.com/couchdb-deb/dists/

**Comment by wohali** [comment]
We will only release a package for this distribution once it hits stable. Sorry.

**Comment by wohali** [comment]
No, you're mistaken. jessie was stable until a month ago and is now old-stable. The current release is stretch, for which we will be releasing a package shortly.

Our intention is to release binaries only for long-term support releases only once they are released, i.e. Ubuntu 14.04/16.04 LTS and Debian 8/9. If you want to use a testing branch, you are more than welcome to build from scratch using our well-defined development process.

**Comment by drasko** [comment]
Yes, true. OK, thanks.

Problem is however that it does not build on OTP20. I forced it, it looks that it is working (for now :)).

**Comment by wohali** [comment]
Hi Uche @uogbuji , 

Buster aka testing is not a fully supported release at this time. Again, when it becomes stable, we'll have an answer - which will likely mean that we provide libmozjs185 for buster as we do for CentOS 6.

Until then you will need to compile and install libmozjs185-dev yourself.

**Comment by ceremcem** [comment]
FYI: My current workaround is that I created an LXC container from my current distro[*](https://github.com/aktos-io/lxc-to-the-future), downgraded it to stretch, installed CouchDB.

**Comment by wohali** [comment]
Packages for debian stretch are now available.
