### ISSUE TITLE
Allow urlencoded '+' characters in _scheduler/jobs/<job_id> field

### ISSUE THREAD

**Issue by nickva** [apache/couchdb#825]
Since replication IDs could have `+` characters in them (they might look like `2abc+create_target+continuous` for example), the ID has to be URL encoded when specified as part of a URI. Otherwise '+' signs will be decoded into spaces and on the server side it will look like `2abc create_target continuous`. 

As a convenience it is possible to unambiguously accept both versions, and thus make URL encoding on the client optional. In other words, client could specify `2abc%2Bcreate_target%2Bcontinuous` or or `2abc+create_target+continuous`. On the server the former will be decoded as `2abc+create_target+continuous` and the latter - `2abc create_target continuous`. Then spaces can be turned into `+`-s since a replication ID generated by server will never have space characters in it.

**Comment by eiri** [comment]
I'm against of breaking with [URI RFC](https://tools.ietf.org/html/rfc3986#section-2.2) for convenience and in my experience encoding ambiguity in general leads to nothing but mess and confusion. If replication ID scheme is hard to work with we probably should just change that scheme.

**Comment by nickva** [comment]
@eiri how does this break the URI RFC?

**Comment by eiri** [comment]
Plus is sub-delim reserved character. RFC's stating: 
> If data for a URI component would conflict with a reserved character's purpose as a delimiter, then the conflicting data must be percent-encoded before the URI is formed.

It seems to me that "unambiguously accept both versions, and thus make URL encoding on the client optional" is a suggestion to do exact opposite of that, or do you mean something different here?

**Comment by nickva** [comment]
+ can be considered sub-delim because it separates the base replication ID from the extensions. For example replication checkpoints use only the base part but not the extension. So parsing out bits of the ID is practical and probably already used by user code out there.

In other words replication ID is really a compound ID and we just accept both the + delimited version or the space delimited ones.

**Comment by eiri** [comment]
You really got me confused here with what exactly you are proposing. At first I've read this as a suggestion to take `+` in URL as a literal + symbol, hence my comment on breaking RFC. Now, after rereading, I see that you are suggesting to make replicator's URI into _not_ unique resource allocator, i.e. make `"2abc%2Bcreate_target%2Bcontinuous"`, `"2abc+create_target+continuous"` (and also `"2abc%20create_target%20continuous"` by accident, right?) to point to the same document.

This still feels wrong, to be honest. Interchangeable delimiters in resource identification already sounds as unnecessary complication and confusion with encoding\representation of such things (imagine whole number of possible mixes: ""2abc+create%20target%2Bcontinuous"`) seems problematic. Again, if it is only about convenience then let's change that plus to something not requiring encoding.

Also, anecdotical, reading around gave me a notion that in web's URL `+` requires encoding only in query, not in path, but I can't find RFC to back this up.

**Comment by nickva** [comment]
> ""2abc+create%20target%2Bcontinuous"`

Replication ID format is not arbitrary though.  This is possible exactly because `2abc+create%20target%2Bcontinuous` is not valid replication ID.

Changing the plus sign might work, however since the ID is compound (made of parts) there are probably user written scripts would split the ID. For example if they inspect the checkpoints documents where only the base part is used.

**Comment by eiri** [comment]
`2bc+create%20target%2Bcontinuous` is not valid replication ID, but valid _representation_ of replication ID if we'd go with your suggestion of treating both `+` and spaces as a valid delimiter.

**Comment by nickva** [comment]
Yap it would be a different representation of the same replication.

> Also, anecdotical, reading around gave me a notion that in web's URL + requires encoding only in query, not in path, but I can't find RFC to back this up.

Yap, but mochiweb  decodes `+` in path as a space, probably because it reuses the code used for `application/x-www-form-urlencoded`. So if we switched to a different server the code the converting `+` to space would never be called. 

In other words, this is mostly about bypassing a mochiweb peculiarity. Note in https://tools.ietf.org/html/rfc3986#section-3.3 that the path can contain sub-delims (which include `+`). 

```
segment-nz-nc = 1*( unreserved / pct-encoded / sub-delims / "@" )
                    ; non-zero-length segment without any colon ":"
```

But mochiweb doesn't pass `+` to the application correctly there and decodes it to a space.

**Comment by eiri** [comment]
Right. And you are suggesting to fix this by, depending on perspective, using non-standard encoder which treats `+`, `%2B` and `%20` all as the same "plusOrSpace" symbol, or, from an other angle, by making replication ID into non-unique identificator from http clients point of view.

Well, if you see all the consequences and still think this is a good idea I don't know if I can convince you otherwise, but read [this saga](https://issues.apache.org/jira/browse/COUCHDB-2748) as an illustration how messy and confusing hacking URL encoding could get.
