### ISSUE TITLE
Avoid uncompressing document bodies just to get the size

### ISSUE THREAD

**Issue by nickva** [apache/couchdb#829]
Noticed during compaction we decompress document bodies to get their size.

https://github.com/apache/couchdb/blob/master/src/couch/src/couch_db_updater.erl#L1084

But it seems we don't have to, as uncompressed size is part of the compression binary format:

http://erlang.org/doc/apps/erts/erl_ext_dist.html

Snappy also has a method to get uncompressed sizes:

https://github.com/apache/couchdb-snappy/blob/master/src/snappy.erl#L51

**Comment by janl** [comment]
Good find. I’ll have a PR for this shortly, basic test results are promising: 10-20% speed improvement in CPU and wall time.

**Comment by janl** [comment]
@nickva would have been great to have had that PR referenced first. On the plus side, my patch looks eerily similar.

**Comment by nickva** [comment]
This was fixed, close it.
