### ISSUE TITLE
Add couch_stats tracking back to couch_log

### ISSUE THREAD

**Issue by davisp** [apache/couchdb#832]
Turns out I forgot to add couch_stats tracking to the new couch_log implementation. Shouldn't take more than a few minutes to add. I'll not pony up on this one in case someone wants to pick it up as low hanging fruit for learning Erlang and/or contributing to Couch.

**Comment by janl** [comment]
@davisp quick note about what the feature does?

**Comment by davisp** [comment]
Forgot to respond, this is just a matter of adding the couch_stats calls for the stats already defined here:

https://github.com/apache/couchdb/blob/master/src/couch_log/priv/stats_descriptions.cfg

So basically just look at any existing couch_stats usage from another app (mem3 and rexi are both straightforward examples) and insert the calls as appropriate for couch_log.

**Comment by jiangphcn** [comment]
@davisp Hi Paul, let me complete this to avoid pending of this for longer time. Would you please review https://github.com/apache/couchdb/pull/1064? Thanks in advance.

**Comment by eiri** [comment]
Implemented in #1064
