### ISSUE TITLE
Mango python test suite doesn't run under Python 3

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#834]
https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/master/82/pipeline

Our CentOS 6 build runs under Python 3, because it's annoying to get an up-to-date Python 2 on CentOS 6 but not annoying to get a Python 3.

There are a number of syntax errors that need to be resolved pronto. master will continue to fail on Jenkins until they do.

@tonysun83 @garrensmith can you take a look here? The error log for the centos 6 build is pretty explicit as to where the errors are. `2to3` will also highlight these for you.

**Comment by tonysun83** [comment]
@wohali: I'm on it.

**Comment by tonysun83** [comment]
https://github.com/apache/couchdb/pull/839/
