### ISSUE TITLE
View is taking long time for first request on 70 GB documents and impacting on couch DB server

### ISSUE THREAD

**Issue by jayachandra02** [apache/couchdb#836]
Hi All,

In our organization we recently(about 3 months ago) started using couchDb (Apache CouchDB 1.5.0) to fulfill requirement. As first part we have created one database and started storing documents in the couchdb. After that we added one view to access records using this. Which was fine working as expected with query filter. 

**As per couchDb documentation when views are accessed for the first time it takes time to create indexs on database documents**. In our first view it has taken time (max 10 mins) on top of  2 millions documents with size of 3 GB.

When we added new view recently and trying to access the first time it was taking long time and also effected other views(not sure but gone down).  Now  database size increased to 70 GB and has 8.5 millions records. 

Is there any way to do this index offline with out effecting on couchDb or taking dump doing indexing locally and re importing back to database ? 

And we are also planning to remove old documents form couch db please help us how can we do this ?
I found only document wise. I want delete bulk wise with filter query like "delete from database where document.date < 'till date to purge' "

Appreciate your help here.

-Jaya

**Comment by wohali** [comment]
This is not a CouchDB bug. This tracker is for bugs only.

You should ask this question on our user mailing list (user@couchdb.apache.org) or our IRC/Slack channels.
