### ISSUE TITLE
Couchdb 2 firewall settings from documentation not restricting ports for cluster communication

### ISSUE THREAD

**Issue by drunksaint** [apache/couchdb#842]
i'm trying to setup a couchdb 2 cluster with the firewall setup as mentioned in http://docs.couchdb.org/en/latest/cluster/setup.html#make-couchdb-use-the-open-ports

## Expected Behavior

If i am understanding this correctly, the 2 couchdb nodes should be able to communicate with each other if just this port range is open to each other in the system firewall.

## Current Behavior

The 2 nodes in the cluster aren't able to communicate if the firewall is restricted to the ports 9100-9200. But they work fine if the firewall is disabled. On looking at the ports on both nodes that are being used to communicate, the couchdb processes on both machines are using ports in the >30k range despite having the configuration mentioned in the documentation link i've mentioned above.

I've restarted both couchdb processes after updating the sys.conf file. And verified that this is indeed the file being used by looking at the config file parameter present in the ps aux for the couchdb process.

## Steps to Reproduce (for bugs)

1. Setup 2 couchdb nodes in cluster mode and add both machines to the same cluster
2. Enable system firewall to allow only ports 9100-9200 open on both machines to the other machine
3. Edit sys.conf as mentioned in the cluster setup page on both machines
4. Restart both couchdb instances
5. check /_membership on one machine. it doesn't show that both nodes are connected to the same cluster. adding a database/doc on one machine doesn't show up on the other machine in fauxton.
6. disable system firewall. now /_membership shows both machines connected and the db and docs appear on both machines.

## Your Environment

* Version used: 2.1.0
* Operating System and version (desktop or mobile): ubuntu 16.04

**Comment by wohali** [comment]
Erlang also needs port 4369 open between machines. This is used by the Erlang port mapper daemon (epmd) which is used to determine which of the ports (9100-9200 are used for each connecting node.

**Comment by wohali** [comment]
FYI this is in the documentation you linked to already, at the top of the page:

> Erlang uses TCP port 4369 (EPMD) to find other nodes, so all servers must be able to speak to each other on this port. In an Erlang Cluster, all nodes are connected to all other nodes. A mesh.
