### ISSUE TITLE
Fuzzy, aggregation and other cool query functions

### ISSUE THREAD

**Issue by natcohen** [apache/couchdb#857]
Databases are not only used to store data, they are used to query it very quickly. IMHO one of the weakest point of CouchDB vs MongoDB (even though they have different functions) is querying. Is there a plan in order to catch up with MongoDB large set of query functions (https://docs.mongodb.com/manual/reference/operator/query/)? Such as fuzzy or aggregation?

**Comment by wohali** [comment]
This is a really broad request for a single "bug" report. We can't provide any meaningful response here.

If you're looking to have a discussion with the developers on this point, please bring it to our mailing list, `user@couchdb.apache.org`.

New options available right now include rich querying using full-text search (Lucene query style) via the clouseau/dreyfus addons, and geospatial sesarch via the hastings addon. Lots of people are able to get the rich querying they need from these.

If you're specifically asking about Mango, we explain in our documentation:

>The general API exposes a set of actions that are similar to what MongoDB exposes (although not all of MongoDB's API is supported). These are meant to be loosely and obviously inspired by MongoDB but without too much attention to maintaining the exact behavior.

**Comment by natcohen** [comment]
@wohali Thanks for the answer... I sent an email to the provided address but didn't get any feedback. I don't really know what to expect (email response or anything?).

I don't want to continue this discussion here if it's not the appropriate "location" but for the record, I think that CouchDB's query system has a lot of room for improvement and fuzzy/lookup would be the natural next step. I just wanted to see where to track these new features.

**Comment by natcohen** [comment]
@wohali Sorry to come back with this but I've tried to send on the pony mail without success... any chance you can direct me to the right place?

**Comment by wohali** [comment]
Your email didn't come through, probably because you weren't subscribed.

Subscribe to the mailing list first by emailing user-subscribe@couchdb.apache.org then try sending your notice.

**Comment by natcohen** [comment]
Thanks!
