### ISSUE TITLE
Enable index on write

### ISSUE THREAD

**Issue by brahmos** [apache/couchdb#864]
## Expected Behavior
We want to enable index on write, is there a config option to do this.

## Current Behavior
Currently it's showing the legacy behavior, which is index on read.

## Context

We are using Cloudant and we want to use Couch 2.1 as a possible in-house solution mostly to be used as a live backup.
Cludant does index on write, and we want to make sure Couch 2.1 does the same.
## Your Environment

* Couch DB version: CouchDB 2.1.0
* Operating System: Ubuntu 14.04.3, AWS image

**Comment by rnewson** [comment]
Hi. The component that updates views when databases change is not a part of CouchDB, it's a proprietary component of the Cloudant platform.
