### ISSUE TITLE
CouchDB crash 

### ISSUE THREAD

**Issue by mkaliyannan** [apache/couchdb#865]
* Operating System : Ubuntu 14.04.
* Version :  Apache CouchDB 1.6.0

it's crashed in middle: ( couldn't find the cause)

[Wed, 04 Oct 2017 01:09:42 GMT] [error] [<0.98.0>] {error_report,<0.31.0>,
                       {<0.98.0>,std_error,
                        {mochiweb_socket_server,297,
                            {acceptor_error,{error,accept_failed}}}}}
[Wed, 04 Oct 2017 01:09:42 GMT] [error] [<0.12352.1891>] {error_report,<0.31.0>,
                             {<0.12352.1891>,std_error,
                              [{application,mochiweb},
                               "Accept failed error","{error,emfile}"]}}
[Wed, 04 Oct 2017 01:09:42 GMT] [error] [<0.12352.1891>] {error_report,<0.31.0>,
                          {<0.12352.1891>,crash_report,
                           [[{initial_call,
                              {mochiweb_acceptor,init,
                               ['Argument__1','Argument__2','Argument__3']}},
                             {pid,<0.12352.1891>},
                             {registered_name,[]},
                             {error_info,
                              {exit,
                               {error,accept_failed},
                               [{mochiweb_acceptor,init,3,
                                 [{file,"mochiweb_acceptor.erl"},{line,34}]},
                                {proc_lib,init_p_do_apply,3,
                                 [{file,"proc_lib.erl"},{line,240}]}]}},
                             {ancestors,
                              [couch_httpd,couch_secondary_services,
                               couch_server_sup,<0.32.0>]},
                             {messages,[]},
                             {links,[<0.98.0>]},
                             {dictionary,[]},
                             {trap_exit,false},
                             {status,running},
                             {heap_size,376},
                             {stack_size,27},
                             {reductions,271}],
                            []]}}

**Comment by mkaliyannan** [comment]
Any suggestions ?

**Comment by wohali** [comment]
` "Accept failed error","{error,emfile}"]}}`

This means that the OS is denying CouchDB the ability to open more files/sockets.

Advice to fix is here: http://docs.couchdb.org/en/latest/maintenance/performance.html?highlight=ulimit#maximum-open-file-descriptors-ulimit

Ubuntu 14.04 doesn't use systemd so you'll want to follow the PAM/init script changes.

**Comment by mkaliyannan** [comment]
Thank you so much ! Appriciated.
