### ISSUE TITLE
why not use pure javascript/nodejs to develope database?

### ISSUE THREAD

**Issue by anlexN** [apache/couchdb#870]
i see pouchdb is successor about database. i hope apache couchdb team could use pure javascript/nodejs to make some effort to it.
i found erlang syntax is not wonderful. it's not modern language. i hate it.
i review couchdb and erlang offsite documention, there are not enough reson to necessarily to use erlang to develope database.
lastly, Ecmascript is fully stable , because every year, new Ecmascript is released. and also nodejs is linux foundation project, it's team is very word hard.

**Comment by wohali** [comment]
You're welcome to reimplement CouchDB on your own in a different language.

PouchDB can also use new contributors.
