### ISSUE TITLE
httpsd refusing to access any system DBs

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#871]
## Expected Behavior
1. enable httpsd:
```
[daemons]
httpsd = {chttpd, start_link, [https]}
[ssl]
; cert stuff goes here
```
2. `curl https://localhost:6984/_membership` and see the cluster membership.

## Current Behavior
1. enable httpsd:
```
[daemons]
httpsd = {chttpd, start_link, [https]}
[ssl]
; cert stuff goes here
```
2. `curl https://localhost:6984/_membership` and see an error. Same thing is true for `/_users` for instance.

Other references: https://stackoverflow.com/questions/41194127/couchdb-permissions-over-https

## Your Environment
* Version used: master
* Browser Name and version: curl
* Operating System and version (desktop or mobile): Debian 8

**Comment by wohali** [comment]
Never mind, this was misconfiguration.

**Comment by matikbird** [comment]
How did you get it working?

I get connection refused when I try to enable SSL from local.ini (I don't want to use HAProxy).
