### ISSUE TITLE
how to shutdown couchdb v2.1.0 and how to make couchdb v2.1.0 live reload after delete database and file changes?

### ISSUE THREAD

**Issue by anlexN** [apache/couchdb#873]

**Comment by wohali** [comment]
I don't know what you're asking here.

**Comment by anlexN** [comment]
- shut down couchdb server
- couchdb server(localhost:5984) auto reloads after some database update, delete and any more.

**Comment by wohali** [comment]
Shutdown couchdb server: Just kill it. It's crash-proof. `kill -1` or `kill -9` are fine.

No need to restart couchdb server after updating a database, deleting it, etc.

**Comment by anlexN** [comment]
"kill -1 or kill -9", how to do it. i'm windows x64 platform. @wohali

**Comment by wohali** [comment]
Stop the Windows Service from the Services control panel.

**Comment by anlexN** [comment]
@wohali, can i make friend with you? i follow your twitter
