### ISSUE TITLE
Make q configurable for peruser dbs, default to 1

### ISSUE THREAD

**Issue by janl** [apache/couchdb#875]
At the moment, couch_peruser-managed databases are created with the default `q` value (8 is the CouchDB default, but users might change that). Now, in a peruser system, we recommend lower `q` because of all the file-descriptor overhead with larger `q` when peruser dbs are traditionally small-ish.

I think it’d be great to be able to tell the peruser module to use a different default `q` for peruser-managed databases, and I suggest we make that default `1` because that’s a sensible real-world default. For users that want to benefit from higher `q` values for peruser-databases, they could enable it.

I’d suggest this addition to the `couch_peruser` config section:

```diff
[couch_peruser]
; If enabled, couch_peruser ensures that a private per-user database
; exists for each document in _users. These databases are writable only
; by the corresponding user. Databases are in the following form:
; userdb-{hex encoded username}
enable = false
; If set to true and a user is deleted, the respective database gets
; deleted as well.
delete_dbs = false
+; set a default q value for peruser-created databases that is different form
+; cluster / q
+; +q = 1
```

**Comment by jiangphcn** [comment]
@janl HI Jan, trying to address this PR via https://github.com/apache/couchdb/pull/1030. Would you like to review or route it to somebody else?

**Comment by janl** [comment]
code merged, closing, the docs issue is referenced above
