### ISSUE TITLE
/_all_docs with keys=[] on _users using POST or GET returns error not_found for valid keys

### ISSUE THREAD

**Issue by clariontools** [apache/couchdb#878]
## Expected Behavior

Expected _all_docs request with keys=[] using either POST or GET to return matches with response for valid _users _id when admin-only databases, such as  _users  when accessed with admin's privileges.

## Current Behavior

When requesting _all_docs with valid keys=[] from _users  when accessed with admin's privileges, each key in the request is returned with the response "error": "not_found".  all_docs with keys=[] works as expected on non-admin-only databases, so it appears to affect at very least the _users db and possibly all admin-only dbs when accessed with admin privileges.

## Steps to Reproduce (for bugs)

1. Gather one or more _id key(s) from your _user db
2. With the key(s) do a POST or GET with the keys hitting the _all_docs endpoint.
3. Example with GET .../_users/_all_docs??keys=["org.couchdb.user:jan"] and/or POST with the appropriate JSON object as per _all_docs documentation.
4. The interesting thing is that a GET with ../_users/_all_docs?key="org.couchdb.user:jan" (not keys with array but single key) does "get" the job done.

## Context

Trying to validate multiple _users ids (keys) exist with a single call, also be able to take the validated _users and call bulkDocs to update each user.

## Your Environment

* Version used: CouchDB 2.0
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by janl** [comment]
Can’t reproduce in 2.1. Marking as fixed.

**Comment by clariontools** [comment]
@janl - Thank you, if have also just confirmed, this issue is fixed in 2.1, but still exists in 2.0 for all those that stumble into this please be advised.  Cannot confirm if the issue was isolated to 2.0 as I have tested in any older releases.
