### ISSUE TITLE
Distribution for arm

### ISSUE THREAD

**Issue by MishUshakov** [apache/couchdb#885]
## Expected Behavior
Package will be installed on arm using apt and/or aptitude

## Current Behavior
Can't install couchdb for Raspberry PI(Raspbian stretch) using apt or aptitude(I even tried to install jessie version, the error stays the same)

```
sudo aptitude install couchdb

y 'https://apache.bintray.com/couchdb-deb jessie InRelease' doesn't support architecture 'armhf'
No candidate version found for couchdb   
Unable to apply some actions, aborting
```

```
apt update
N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'https://apache.bintray.com/couchdb-deb jessie InRelease' doesn't support architecture 'armhf'
```

## Possible Solution
Build and upload distribution for armhf with support for Debian stretch.

## Context
I had very hard time compiling Erlang on raspberry pi to build couchdb(gone wrong). I love the database and want to keep using it everywhere, even on my raspberry

## Your Environment

* Version used: latest
* Operating System and version (desktop or mobile): Raspbian GNU/Linux 9.1 (stretch) armv7l

**Comment by wohali** [comment]
At present, Apache Infrastructure don't have an arm build machine for us on which to build distributions.
