### ISSUE TITLE
Building CouchDB on arm64-v8a

### ISSUE THREAD

**Issue by DQvsRA** [apache/couchdb#892]
I'm trying to run CouchDB on my Odroid C2 (arm64)
After "./configure" I run "make release" but it gives me an error 

## Current Behavior
![image](https://user-images.githubusercontent.com/442111/31650424-8ea31262-b317-11e7-89ca-d1d8b916e04e.png)

## Your Environment
Linux odroid64 3.14.79-116 #1 SMP PREEMPT Tue Sep 26 01:19:06 BRT 2017 aarch64 aarch64 aarch64 GNU/Linux

**Comment by kxepal** [comment]
Seems like the [`-m64` is not supported](https://bugzilla.redhat.com/show_bug.cgi?id=713685) by ARM build toolchain. Try to remove it or replace with analogue. As @wohali [saild](https://github.com/apache/couchdb/issues/885#issuecomment-335514010) we don't have ARM's in our infra to test and support builds for them. 

However, any contributions to fix that are welcome! Happy hacking!

**Comment by koleto** [comment]
Just manage to comile on Linaro ARMv8.

1. Open the file ~/apache-couchdb-2.1.0$ vim src/rebar/src/rebar_port_compiler.erl
2. Remove the '-m64' flag from Line 608 and 609. The output should be:
`     %% Linux specific flags for multiarch
     {"linux.*-64$", "CFLAGS", "$CFLAGS"},
     {"linux.*-64$", "CXXFLAGS", "$CXXFLAGS"},
     {"linux.*-64$", "LDFLAGS", "$LDFLAGS"},` 

3. Recompile rebar:   cd src/rebar
`./bootstrap`

4. Rebuild couchdb: 
`make release`

**Comment by janl** [comment]
That means this needs to be fixed in rebar, not CouchDB. cc @davisp any opinions?

**Comment by wohali** [comment]
If it's a rebar problem, we should look at the rebar3 change using paul's [enc](https://github.com/davisp/erlang-native-compiler) and make this patch over there.

**Comment by koleto** [comment]
But unfortunately after I was able to build couchdb, there are still some issues with the replication and views on ARMv8.

**Comment by wohali** [comment]
Sounds like JavaScript didn't build correctly. You will need `libmozjs185` specifically, and it MUST be built 32-bit -- see https://bugzilla.mozilla.org/show_bug.cgi?id=589735 and https://bugzilla.mozilla.org/show_bug.cgi?id=577056 for the gory details.

**Comment by wohali** [comment]
Based on https://github.com/apache/couchdb-pkg/issues/24 if we just pull in the very last changes to rebar (v2) from https://github.com/rebar/rebar we should be able to fix this problem. We just need to be sure to keep @davisp's patch in the `2.6.0-couchdb` branch around, assuming it's not already patched upstream.

Would still like to see us move to proper rebar - will file that as a new ticket.

**Comment by janl** [comment]
closing in favour of https://github.com/apache/couchdb/issues/1428
