### ISSUE TITLE
Consider error messages or host resolution in Bind IP configuration.

### ISSUE THREAD

**Issue by wyc** [apache/couchdb#896]
## Expected Behavior

I expect the node configuration screen to allow me to enter hostnames such as `localhost` or `my-server.domain.com`. Instead, it crashes the application.

## Current Behavior

The application crashes, as in https://pastebin.com/rNSeTrtK

## Possible Solution

Either:
- Add an error message from the server letting the client know that it's a faulty configuration. Perhaps this could also be a frontend-only check.
- Implement hostname resolution at the server end in addition to checks for bad input.

## Steps to Reproduce (for bugs)

1. Open Fauxton
2. Click the settings icon
3. Configure a single node
4. Populate field, with `localhost` in the Bind IP field
5. Submit

## Context

From chat:
```
171710 < wayne> i'm experiencing crashing when i go to the settings menu option in fauxton and click "configure a single node"
171804 < wayne> i've yet to pull logs, in process of doing that
171925 < wayne> https://pastebin.com/rNSeTrtK
171951 < wayne> and yikes, it looks like the password gets leaked in the logs
172037 < wayne> did i miss a step?
172106 < wayne> i can work on excavating the erl.dump from the container if it would help
172319 <+rnewson> 'invalid_bind_address' is a problem
172329 <+rnewson> you need to specify an ip address, not a name
172353 < wayne> ah got it. no host resolution
172413 < wayne> could this be a good issue to open? it would improve the user experience
172441 < wayne> maybe an error message from the server or even consider implementing host resolution
```

## Your Environment

* Version used: 2.1
* Browser Name and version: Chromium
* Operating System and version (desktop or mobile): Desktop
* Link to your project: N/A

**Comment by janl** [comment]
+1, this would be a great addition for a first-time contributor. Wanna work on a PR? Happy to help get you started.

**Comment by wyc** [comment]
Thanks for your response. Sure, happy to attempt a resolution with tests.

**Comment by wohali** [comment]
@janl What needs to be done here to move forward?

**Comment by janl** [comment]
Closing in favour of https://github.com/apache/couchdb/pull/1439
