### ISSUE TITLE
connect to couchdb {"error":"error","reason":"eacces"}

### ISSUE THREAD

**Issue by bruceforlearn** [apache/couchdb#898]
Hello All,

I install a V1.6.1 couchdb on centos7.3
there is a issue occurred as blow:

[root@localhost /]# curl 10.42.149.16:5984
{"couchdb":"Welcome","uuid":"5bf4831eb34af53276e6dbf516d87962","version":"1.6.1","vendor":{"version":"1.6.1","name":"The Apache Software Foundation"}}

[root@localhost ~]# curl localhost:5984
{"couchdb":"Welcome","uuid":"263a82f03e188a88855f95a2cb9770f0","version":"1.6.1","vendor":{"version":"1.6.1","name":"The Apache Software Foundation"}}

[root@localhost ~]# curl -X PUT http://localhost:5984/_config/admins/admin -d '"admin"'
{"error":"error","reason":"eacces"}

[root@localhost /]# curl -X PUT http://10.42.149.16:5984/_config/admins/admin -d '"admin"'
{"error":"error","reason":"eacces"}

local.ini
[httpd]
port = 5984
bind_address = 0.0.0.0

I tried google many times but failed 

please help 

thank you

**Comment by wohali** [comment]
eacces means your file permissions are wrong. Check wherever you installed couchdb, and ensure that the *.ini files are writeable by the CouchDB user.

You will want to check the same for your data directory too.

**Comment by bruceforlearn** [comment]
@wohali
thank you
