### ISSUE TITLE
Compaction daemon should prioritise based on gains

### ISSUE THREAD

**Issue by calonso** [apache/couchdb#909]
## Expected Behavior

Compaction daemon, when selecting which shard to compact, should prioritise based on biggest gains.

## Current Behavior

Compaction daemon just picks one shard that fulfils the configured threshold

## Context

Trying to have my cluster healthy I have to manually trigger compactions in order to keep disk space safe. I'd like compaction daemon to help me by picking those shards that will make the biggest impact.

## Your Environment

* Version used: 2.1.0
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Ubuntu Trusty
* Link to your project: cabify.com

**Comment by janl** [comment]
+1

Should be not too hard a fix, the main compaction daemon loop is working off of _all_docs: https://github.com/apache/couchdb/blob/master/src/couch/src/couch_compaction_daemon.erl#L129

The code to calculate the biggest-benefeacting database can be scavenged from here: https://github.com/apache/couchdb/blob/master/src/couch/src/couch_compaction_daemon.erl#L318-L323

With both of these entry points, the algorithm in compact_loop should now:
1. calculate size info for all dbs/shards into a sorted table
2. top of the table entry gets compacted
3. GOTO 1.

Bit of handwaving about views. Two options:

1. views just go into the main list of things that can be compacted and biggest-benefit views just go on top, like a database would.
2. when calculating database fragmentation, include the view fragmentation as well, and then compact the database and its views (with or without the parallel option as it does now), as a batch before moving on to the next.

My gut feel 1. is what makes a little more sense, but I would take 2. if the PR is easier and leave 1. for a later patch.

@calonso wanna give this a shot?
