### ISSUE TITLE
Boolean values ​​are not displayed in a table form.

### ISSUE THREAD

**Issue by iigum** [apache/couchdb#924]
Boolean values ​​are not displayed in a table form.
![ss0000](https://user-images.githubusercontent.com/33146290/32092073-a0158f58-baff-11e7-980c-23764786bfe6.png)

**Comment by garrensmith** [comment]
Thanks for reporting that. We have just landed a fix for it.

All misspelling thanks to my iPhone.
________________________________

**Comment by janl** [comment]
Fixed with https://github.com/apache/couchdb-fauxton/pull/1001
