### ISSUE TITLE
Confusing error message for bad index creation

### ISSUE THREAD

**Issue by flimzy** [apache/couchdb#927]
I attempted to create an index, with a mal-formed `fields` value:

    curl -v -X POST http://admin:abc123@localhost:6002/foo/_index -H 'Content-Type: application/json' -d '{"index":{"fields":"foo"}}'

And got the following error message:

    {"error":"invalid_sort_json","reason":"Sort must be an array of sort specs, not: <<102,111,111>>"}

I would expect that:

1. `<<102,111,111>>` be replaced with something human-readable.  Even just `foo` in this case would be an improvement.
2. it would refer to the `fields` key by name, rather than `Sort`.

## Your Environment

CouchDB/2.1.0 (Erlang OTP/17)

**Comment by janl** [comment]
@flimzy good find! Wanna attempt a PR?

Code location is here: https://github.com/apache/couchdb/blob/d0445f53a837db374e56eb59ede63694ed6e4c33/src/mango/src/mango_error.erl#L330

What you are seeing is a so-called Erlang binary. In particular, it is a three-byte binary with the decimal ascii values of `f`, `o` and `o`.

The problem now is that the format specifier `~w` is meant for [Erlang atoms](http://erldocs.com/current/stdlib/io.html?i=0&search=io:format#format/1) or roughly an 8-bit ascii string, not a binary.

There are two options now.

1. typecast the binary into a list (that in this case will map to the `~w` specifier with [`binary_to_list()`](http://erldocs.com/current/erts/erlang.html?i=0&search=binary_to_list#binary_to_list/1)

2. change the format specifier to something that can render the binary into the string, namely [`~s`](http://erldocs.com/current/stdlib/io.html?i=0&search=io:format#format/1).

One challenge arises, and that’s something you can play with: what if the bad sort specifier is not a string, but a JSON structure? Then the above solutions would show some different gobbledygook, or they might not. It might be worth trying a few different ones and see which solution gets you closest to a satisfactory result. If you are looking at solution #2, [check out the other format specifies](http://erldocs.com/current/stdlib/io.html?i=0&search=io:format#format/1), especially `~p`.

Let us know if you have any questions :)

**Comment by flimzy** [comment]
Thanks for the info, @janl. I'm happy to try to tackle this, but don't know if I'll have time in the short term.

**Comment by bgottlob** [comment]
@janl I can give this a shot if no one else is currently looking at this.

**Comment by janl** [comment]
closing in favour of https://github.com/apache/couchdb/pull/1310
