### ISSUE TITLE
verify CouchDB failed Installation windows 10 after upgrade

### ISSUE THREAD

**Issue by wa1gon** [apache/couchdb#928]
## Expected Behavior

Verify success fully

## Current Behavior
Verify failed with error: error,{error,{conn_failed,{error,eaddrnotavail...

## Context
Can't replicate database

## Your Environment

* Version used: 2.1
* Browser Name and version: Chrome 61
* Operating System and version (desktop or mobile): Windows 10 Creator Desktop

**Comment by wohali** [comment]
`eaddrnotavail` means whatever address you're trying to bind to, doesn't exist. By default Windows 2.1 binds to address 127.0.0.1. Have you disabled your loopback interface?

**Comment by wa1gon** [comment]
I reinstalled and the problem went away.  Installed on other systems without problem.
