### ISSUE TITLE
Enable temporary views in CouchDB 2.x

### ISSUE THREAD

**Issue by rpiaggio** [apache/couchdb#932]
## Expected Behavior

The same behavior as in version 1.x, albeit with the potential speedup provided by sharding.

## Current Behavior

Temporary index queries fail (not implemented in version 2).

## Your Environment

We use CouchDB to store data in a survey-like system, where we store hundreds of variables for each document. For statistical analysis purposes, we allow ad-hoc queries, where any of these variables and be counted or used for filters.

We understand that temporary indexes force a reindex of the entire DB when they are invoked. In our case, this is mitigated by:
* Very few users are allow to perform these analyses, and they don't do it often.
* These users are warned about the impact of the queries.
* It can be performed on a replica instead of the main database (replication is one of the points where CouchDB shines after all).

We understand that temporary indexes were disabled because can be abused and degrade performance significantly, but we cannot create regular indices for the millions of combinations of variables that we use. At the moment, the only viable alternate solution that we can think of is creating a regular index for every query and then deleting it after a while. (We would like to keep the functionality of 1.x where subsequent queries return results immediately after the first query, we suspect that some form of caching is probably going on.)

Because of the perils of temporary views, maybe they can be disabled by default but an option can be providedn to enable them.

We are currently unable to upgrade to version 2.x because of this limitation.

**Comment by wohali** [comment]
Sorry, temporary views are not coming back.

Have you considered using Mango selectors on `_changes` feeds? You'll get the same behaviour that you're looking for (one-time use filters), and the convenient output structure of a _changes feed which is easily parsed by your client code.

http://docs.couchdb.org/en/latest/api/database/changes.html#selector

The same syntax is supported for replication by specifying your selector directly in a _replicator document.

**Comment by rpiaggio** [comment]
Thank you @wohali for your quick response.

We had not considered using the `_changes` feed for this but after looking at it, it does not seem that it will provide the functionality we require:

* Our analysis queries all involve a `reduce` function. There does not seem to be a way to assign a key to documents in the `_changes` feed so that we can perform the `reduce` function manually. Furthermore, we don't want to transfer all documents over the wire (or even their ids), this would be too much when all we need is a summary (the result of the `reduce`).

* Mango queries are somewhat limited for our needs. A common operation we perform in documents involves iterating over some of its (object-typed) properties, look for a common property in them, and then extract the max or min value. JS `map` based filtering can be applied in the `_changes` feed by using the `_view` parameter, but this implies having a `_view` created already with the `map` function.

We are fans of CouchDB are will not move away from it, but we are disappointed to see this feature removed and being forced to redesign our analysis module, which is a core feature of our system. We do accept any suggestions for alternatives to implement our required functionality in 2.x, besides creating and deleting "permanent" views.

We also kindly request the development team to reconsider re-enabling temporary views in future versions of CouchDB.

**Comment by wohali** [comment]
FYI there is work in progress to add reduce functionality to Mango. Hopefully this will support your needs in the future.

**Comment by rpiaggio** [comment]
Thank you! I don't know if we will able to reduce all our map logic into Mango, but it's worth a try. Definitely looking forward to seeing reduce with Mango.
