### ISSUE TITLE
How can restart couchdb automatically following with a kill request

### ISSUE THREAD

**Issue by wonderfuljamesjin** [apache/couchdb#941]
Recently we had problem that once the app process is killed, couch db was not restarted which is requiring a manual restart.  Is there way that restarting couchdb automatically following with a kill request? thanks

**Comment by wonderfuljamesjin** [comment]
@rnewson can you also advise me this question, thank you

**Comment by wohali** [comment]
Use any sort of supervisor you want to ensure CouchDB is restarted after a kill. Options include:

* runit
* systemd
* supervisord
* a bash script you write with a while loop in it

and more I am not thinking of off the top of my head.
