### ISSUE TITLE
Support newer SpiderMonkey release?

### ISSUE THREAD

**Issue by ArchangeGabriel** [apache/couchdb#946]
Currently, CouchDB requires SpiderMonkey 1.8.5, which is quite old and has numerous security issues and for this reason is considered for removal in some distros (at least ArchLinux).

Would it be possible to upgrade to version 24, 38 or 52 of SpiderMonkey?

Thanks!

**Comment by wohali** [comment]
Not easily, no. 1.8.5 is the last version that supports the bare anonymous function format that we currently use for design documents. Any upgrade would break compatibility with existing design documents.

This has been discussed heavily before, see here: 
https://issues.apache.org/jira/browse/COUCHDB-1603
https://issues.apache.org/jira/browse/COUCHDB-1602
https://issues.apache.org/jira/browse/COUCHDB-1397

A more interesting path forward is:
https://github.com/dmunch/couch-chakra

but more work needs to be done. This was discussed on the dev@couchdb mailing list in 2017:
https://lists.apache.org/thread.html/e1be7c8de8826e551483638f185eccec9f80ab53ebac0b0e3d8307d0@%3Cdev.couchdb.apache.org%3E

**Comment by leonaves** [comment]
I don't know if I've followed some of those threads incorrectly, but is [this person](https://issues.apache.org/jira/browse/COUCHDB-1397?focusedCommentId=13199747&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13199747) correct in their statement:

> it is the people writing
> ```json
> {"map": "var d=1; function(doc)
> { emit(doc._id, d); }"}
> ```
> that should find their code not working, as they are using undocumented features.

Breaking undocumented features isn't a breaking change. I accept that a large number of users may rely on this, but resisting changes that break things you never promised to stay working for the sake of existing users is pretty short sighted IMO, especially given the growing ES6+ community.

**Comment by wohali** [comment]
Pull requests welcome.
