### ISSUE TITLE
GET /_scheduler returns 405

### ISSUE THREAD

**Issue by flimzy** [apache/couchdb#953]
Observe:

```
$ curl -v -X GET http://admin:abc123@localhost:6002/_scheduler
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 6002 (#0)
* Server auth using Basic with user 'admin'
> GET /_scheduler HTTP/1.1
> Host: localhost:6002
> Authorization: Basic YWRtaW46YWJjMTIz
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 405 Method Not Allowed
< Server: CouchDB/2.1.0 (Erlang OTP/17)
< Date: Wed, 01 Nov 2017 21:20:11 GMT
< Content-Type: application/json
< Content-Length: 64
< Cache-Control: must-revalidate
< Allow: GET,HEAD
< 
{"error":"method_not_allowed","reason":"Only GET,HEAD allowed"}
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```

Same essential behavior observed when substituting `GET` with `HEAD`, or when requesting a specific (non-existent) URL below the `/_scheduler/` path, i.e.:  `/_scheduler/foo`.

## Expected Behavior
I would expect a valid response, or a 404 if the endpoint isn't supported.

## Current Behavior
405 status (method not allowed), with the error message:

    {"error":"method_not_allowed","reason":"Only GET,HEAD allowed"}

## Possible Solution
I believe this is just a matter of returning the wrong error code; 404 is probably appropriate.

## Steps to Reproduce (for bugs)
See above

## Your Environment
CouchDB 2.1.0 official docker image.

**Comment by nickva** [comment]
I think the idea was to reserve _scheduler for the future to return replication stats or summary. But it hasn't been implemented yet.

Yeah 404 might make more sense here. Especially if we say "only GET/HEAD allowed" but then those method don't do anything.

**Comment by nickva** [comment]
This one was fixed
