### ISSUE TITLE
CouchDB 2.1 Cluster doesn't replicate the data across

### ISSUE THREAD

**Issue by epappas** [apache/couchdb#963]
I am trying to create a couchDB cluster, by trying to replicate the steps from 
the docs [1] but it seems the actual result differs from my expectation. Whilst 
by following these steps the Nodes discover each other, and they understand that
they are in a cluster mode, they don't replicate the data across. So when I'm 
creating a new Database on one of the nodes, the others never get an update. 
Same behaviour if the database has a document.

[1] http://docs.couchdb.org/en/latest/cluster/setup.html

## Expected Behavior

I'm Expecting that in a cluster mode, CouchDB should replicate the data (in an 
eventual consistency manner) across the participated nodes, when such update is
taking place to any node of the cluster.

So when I'm creating a document in one of the nodes, I should be able to query 
another node of the cluster, in order to fetch the document that I have just 
created (time delay is accepted).

## Current Behavior

The cluster get created apparently successfully, but the nodes don't get updated
when new documents are created into the nodes of the cluster. The node though 
that receives the call creates the document locally with success

## Possible Solution

Somehow, the nodes need to be have consistent state. I'll need to dig deeper to 
figure how.

As a followup, I will try to trace the network between the nodes, to see if 
there is any information actually been exchanged.

The fact that the nodes are not listed under the `all_nodes` list, but only 
under the `cluster_nodes` list of the `/_membership` endpoint seems to be giving
away a clue.

## Steps to Reproduce (for bugs)

Some ENV variables for example context

```
SIZE="3"
ADMIN_USER="admin"
ADMIN_PASSWORD="secure_password"
COUCHDB_COOKIE="yummy_cookie"
COUCHDB_SECRET="spooky_secret"
IP="10.100.20.xxx" # where xxx is the IP of the Host
NODES="10.100.20.1 10.100.21.2 10.100.22.3" # the IPs of all three Nodes
COORDINATION_NODE="10.100.20.1"
```

I am running my Docker image as such; (FYI the `/mnt` directory points to an EBS)

```
sudo docker run -d \
    --name=couchdb \
    --restart always \
    --net=host \
    -p 15984:15984 \
    -p 25984:25984 \
    -p 35984:35984 \
    -p 15986:15986 \
    -p 25986:25986 \
    -p 35986:35986 \
    -p 5984:5984 \
    -p 5986:5986 \
    -p 4369:4369 \
    -p 9100:9100 \
    -v /mnt/couchdb/data:/opt/couchdb/data \
    -e NODENAME="$IP" \
    -e COUCHDB_COOKIE="$COUCHDB_COOKIE" \
    -e COUCHDB_SECRET="$COUCHDB_SECRET" \
    apache/couchdb:2.1.0
```

Then on Each Node (3 of them) I run;

```
curl -X POST \
    -H "Content-Type: application/json" \
    http://127.0.0.1:5984/_cluster_setup \
    -d "{
        \"action\": \"enable_cluster\",
        \"username\": \"$ADMIN_USER\",
        \"password\": \"$ADMIN_PASSWORD\",
        \"bind_address\": \"0.0.0.0\",
        \"port\": 5984,
        \"node_count\": $SIZE,
        \"singlenode\": false
    }"

# Execute only in the coordination node
if [ $IP = $COORDINATION_NODE ]
then
    for node in $NODES
    do
        curl -X POST -H "Content-Type: application/json" \
            "http://$ADMIN_USER:$ADMIN_PASSWORD@127.0.0.1:5984/_cluster_setup" \
            -d "{
                \"action\": \"enable_cluster\", 
                \"bind_address\": \"0.0.0.0\", 
                \"username\": \"$ADMIN_USER\", 
                \"password\": \"$ADMIN_PASSWORD\",
                \"port\": 15984, 
                \"node_count\": $SIZE,
                \"remote_node\": \"$node\", 
                \"remote_current_user\": \"$ADMIN_USER\", 
                \"remote_current_password\": \"$ADMIN_PASSWORD\"
            }"
    done
fi

curl -X POST \
    -H "Content-Type: application/json" \
    "http://$ADMIN_USER:$ADMIN_PASSWORD@127.0.0.1:5984/_cluster_setup" \
    -d '{"action":"finish_cluster"}'

for node in $NODES
do
    curl -X PUT "http://$ADMIN_USER:$ADMIN_PASSWORD@$IP:5986/_nodes/couchdb@$node" -d {}
done
```

Now if you create a document in the node 10.100.20.1, the others two never get 
the update.

## Context

- I have tried to netcat the ports from within the running docker containers, and they seem to be succeeding
- the `netstat` in the host machine seems to have the ports active and listening
- The `/_membership` has such a result: (eg for node 10.100.20.1)

```
{
    "all_nodes": [
        "couchdb@10.100.20.1"
    ],
    "cluster_nodes": [
        "couchdb@10.100.20.1",
        "couchdb@10.100.20.2",
        "couchdb@10.100.20.3"
    ]
}
```

## Your Environment
CouchDB 2.1.0, (docker image: apache/couchdb:2.1.0)
Host machine: Ubuntu xenial
Platform: AWS, private subnet

Ideas? thanks!

**Comment by epappas** [comment]
Update: By monitoring the traffic in the port 9100 [1], I saw that the nodes are propagating their updates across to the cluster nodes, though the updates are still missing from their state, the new documents are only stored in the node that first received the request.

[1] `sudo ngrep -d any port 9100` on each node

**Comment by wohali** [comment]
Why are you doing the final loop with the document PUTs to 5986? Those shouldn't be needed, the cluster setup wizard should do everything for you. You shouldn't need to expose port 5986 at all.

Can you include a sample of you creating a database and a document (through port 5984, of course) and how it fails?

**Comment by epappas** [comment]
Hey,

About exposing the port was me going crazy :), So I did as you asked;

- Run the docker image to every host (3 of them)
- then on each non-cordination node I executed;

```
curl -X POST \
    -H "Content-Type: application/json" \
    http://127.0.0.1:5984/_cluster_setup \
    -d "{
        \"action\": \"enable_cluster\",
        \"username\": \"$ADMIN_USER\",
        \"password\": \"$ADMIN_PASSWORD\",
        \"bind_address\": \"0.0.0.0\",
        \"port\": 5984,
        \"node_count\": $SIZE,
        \"singlenode\": false
    }"

curl -X POST \
    -H "Content-Type: application/json" \
    "http://$ADMIN_USER:$ADMIN_PASSWORD@127.0.0.1:5984/_cluster_setup" \
    -d '{"action":"finish_cluster"}'
```

- In the Coordination node I also executed this loop, sending a `finish_cluster` call

```
for node in $NODES
    do
        curl -X POST -H "Content-Type: application/json" \
            "http://$ADMIN_USER:$ADMIN_PASSWORD@127.0.0.1:5984/_cluster_setup" \
            -d "{
                \"action\": \"enable_cluster\", 
                \"bind_address\": \"0.0.0.0\", 
                \"username\": \"$ADMIN_USER\", 
                \"password\": \"$ADMIN_PASSWORD\",
                \"port\": 15984, 
                \"node_count\": $SIZE,
                \"remote_node\": \"$node\", 
                \"remote_current_user\": \"$ADMIN_USER\", 
                \"remote_current_password\": \"$ADMIN_PASSWORD\"
            }"
    done
```

Then I waited 30 sec and executed:

```
curl -X PUT "http://$ADMIN_USER:$ADMIN_PASSWORD@$IP:5984/testdb" -d '' 
# returned {"ok":true}

curl -X PUT "http://$ADMIN_USER:$ADMIN_PASSWORD@$IP:5984/testdb/foo" -d '{"_id": "foo"}'
# returned {"ok":true,"id":"foo","rev":"1-967a00dff5e02add41819138abb3284d"}

sleep 30

for node in $NODES
do
    curl -X GET "http://$ADMIN_USER:$ADMIN_PASSWORD@$node:5984/testdb/foo"
done
# returned
# {"_id":"foo","_rev":"1-967a00dff5e02add41819138abb3284d"}
# {"error":"not_found","reason":"Database does not exist."}
# {"error":"not_found","reason":"Database does not exist."}
```

The first that it succeeded, was the node that I sent the PUT request.

**Comment by epappas** [comment]
About the Nodes, isn't that what the doc suggests [1]?

[1] http://docs.couchdb.org/en/2.1.0/cluster/nodes.html

**Comment by epappas** [comment]
So the issue was due to my mix misuse of ports httpd (5986) vs chttpd (5984). This can close now.

**Comment by wohali** [comment]
For others: never, ever, ever use port 5986 for *_ANYTHING_* other than when the docs explicitly tell you to use port 5986.

**Comment by hitesh-smit** [comment]
> So the issue was due to my mix misuse of ports httpd (5986) vs chttpd (5984). This can close now.

Can you please highlight where to use 5984 and where to use 5986. I am also facing this issue.

**Comment by wohali** [comment]
Unless the docs tell you to use port 5986, assume port 5984. 5986 is used to manually move shards between nodes or to manually add/remove nodes from a cluster when not using the cluster setup wizard. That's it.

To set up a cluster, follow the documentation, especially the section on the Cluster Setup Wizard:

http://docs.couchdb.org/en/latest/setup/cluster.html

The **entire setup process only uses port 5984**.

If you're not successful following the documentation, file a new bug over at https://github.com/apache/couchdb-documentation/issues .
