### ISSUE TITLE
`make dist` on a tag doesn't pick up tag revision #

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#967]
Rather than special handling of `COUCH_RC=# make dist` it would be better if `make dist` could pull the tag from the current checkout and use that instead. Then the release process for RCs as well as real releases could just be to git tag && make dist.

Investigate what it would take to make that happen.

/cc @janl

**Comment by janl** [comment]
Closing in favour of https://github.com/apache/couchdb/pull/1437

**Comment by wohali** [comment]
Right, @dch fixed that on our 2.1.2 branch in a nice way. Thanks Dave!
