### ISSUE TITLE
GET /db/_all_docs?update_seq=true missing 'offset' and 'update_seq' when 'keys' also provided

### ISSUE THREAD

**Issue by dharders** [apache/couchdb#969]
## Expected Behavior

A `GET /db/_all_docs?update_seq=true&keys=["aValidKey"]` should return 
```javascript
{
  total_rows: X,
  rows: [{id: "aValidKey", ...}],
  offset: Y,
  update_seq: "Z-ABC..."
}
```
## Current Behavior

Instead it returns
```javascript
{
  total_rows: X,
  rows: [{id: "aValidKey", ...}]
}
```
i.e. it is **missing 'offset' and 'update_seq'** when 'keys' also provided.

**NOTE:** this is also true for `POST`

## Possible Solution

Specifying `key` instead of `keys` produces the desired behavior so possibly check that code path

i.e.  `GET /db/_all_docs?update_seq=true&key="aValidKey"` works as expected

## Steps to Reproduce (for bugs)

1. 
```javascript
 curl -X PUT "localhost:5984/testdb"
```
2. 
```javascript
curl -X POST -H "Content-Type: application/json" -d '{"docs": [{"_id": "doc1"}, {"_id": "doc2"}]}' "localhost:5984/testdb/_bulk_docs"
```
3.
```javascript
curl -X GET 'localhost:5984/testdb/_all_docs?update_seq=true&keys=\["doc1"\]'
```
4. Response is missing `offset` and `update_seq`
5. Below response is as expected when using `key` instead of `keys`
```javascript
curl -X GET 'localhost:5984/testdb/_all_docs?update_seq=true&key="doc1"'
```
6. Response should contain `offset` and `update_seq` as expected
7. POST is also not returning `offset` and `update_seq`
```javascript
curl -X POST -H "Content-Type: application/json" -d '{"keys": ["doc1"]}' 'localhost:5984/testdb/_all_docs?update_seq=true'
```
## Context

Noticed this bug when putting together a PR to add a feature to PouchDB (see [PouchDB issue 6230](https://github.com/pouchdb/pouchdb/issues/6230), i.e. missing `update_seq` option in allDocs API)

## Your Environment

* Version used: CouchDB v2.1.0
* Browser Name and version: curl, Chrome 61.0.3163.100 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Windows 10 64-bit Desktop

**Comment by jiangphcn** [comment]
@dharders I have issued one PR  #1085 to address your issue. Currently, it is under review process.

**Comment by dharders** [comment]
Awesome work! Thanks @jiangphcn 😄

**Comment by jiangphcn** [comment]
hey @dharders, when performing review on PR #1085, we found that  
- although we can return offset and update_seq like  https://github.com/apache/couchdb/pull/1085#issuecomment-357793594, it looks that this doesn't make more sense to caller. In non-sharding environment, the returned update_seq and offset during _all_docs is precise and stable. Instead, in sharding environment, offset is just a minimal offset on one of the db for one of the keys, not necessary first or last one, and update_seq is different depending on what shards return.
- from Paul and Eric's comments, you can read more details https://github.com/apache/couchdb/pull/1085#issuecomment-357793594.

So we want to check with you whether you would like couchdb to modify document to remove update_seq or offset statement in current context,  or modify codes to return null for them when _all_docs is called in sharing environment. 

cc @davisp @eiri

**Comment by dharders** [comment]
Hi @jiangphcn 

Thanks for the follow-up! I've [replied directly to your PR](https://github.com/apache/couchdb/pull/1085#issuecomment-357843147)

**Comment by wohali** [comment]
Looks like this merged, so I'm closing. If you build from master and see the bug is still present, please reopen.
