### ISSUE TITLE
2.1.1 fails to open databases after upgrade

### ISSUE THREAD

**Issue by wohali** [apache/couchdb#972]
This is a pre-emptive bug against which we can de-duplicate issues that get filed in the future.

"When starting up my CouchDB after upgrading from 2.0.0 or 2.1.0 to 2.1.1, I get either a `No DB shards could be opened.` error in couch.log, or a "This database failed to load" error in Fauxton."

The fix:

Edit your `etc/vm.args` file and change the line that reads `-name couchdb@127.0.0.1` to `-name couchdb@localhost`.

This is outlined in our release notes here: http://docs.couchdb.org/en/2.1.1/whatsnew/2.1.html#upgrade-notes

>When upgrading from 2.x to 2.1.1, if you have not customized your node name in vm.args, be sure to retain your original vm.args file. The default node name has changed from couchdb@localhost to couchdb@127.0.0.1, which can prevent CouchDB from accessing existing databases on the system. You may also change the name option back to the old value by setting -name couchdb@localhost in etc/vm.args by hand. The default has changed to meet new guidelines and to provide additional functionality in the future.
> If you recieve errors in the logfile, such as internal_server_error : No DB shards could be opened. or in Fauxton, such as This database failed to load. you need to make this change.

**Comment by natevw** [comment]
Here's a sample of what this might look like in the logs:

```
[error] 2017-11-08T00:26:55.849333Z couchdb@127.0.0.1 <0.259.0> -------- Error opening view group `_auth` from database `shards/40000000-5fffffff/_users.1497652572`: {'EXIT',{{badmatch,{error,read_failure}},[{couch_mrview,get_info,2,[{file,"src/couch_mrview.erl"},{line,332}]},{couch_compaction_daemon,maybe_compact_view,3,[{file,"src/couch_compaction_daemon.erl"},{line,253}]},{couch_compaction_daemon,maybe_compact_views,3,[{file,"src/couch_compaction_daemon.erl"},{line,227}]},{couch_compaction_daemon,'-compact_loop/1-fun-0-',3,[{file,"src/couch_compaction_daemon.erl"},{line,141}]},{couch_server,'-all_databases/2-fun-0-',4,[{file,"src/couch_server.erl"},{line,278}]},{filelib,do_fold_files2,8,[{file,"filelib.erl"},{line,185}]},{filelib,do_fold_files2,8,[{file,"filelib.erl"},{line,195}]},{couch_server,all_databases,2,[{file,"src/couch_server.erl"},{line,267}]}]}}
```

It also makes external HTTP requests return 500 responses like:

```
{"error":"internal_server_error","reason":"No DB shards could be opened.","ref":123456789}
```

**Comment by CristianG540** [comment]
i'm having this error and i think is related with this issue 
![image](https://user-images.githubusercontent.com/1929796/32555755-9efa4ad0-c46b-11e7-95ec-4c154966846b.png)

**Comment by MtDalPizzol** [comment]
Already updated **vm.args** and still facing this. Here's the logs:

```
[notice] 2017-11-08T15:33:52.716998Z couchdb@127.0.0.1 <0.1989.1> -------- Failed to ensure auth ddoc _users/_design/_auth exists for reason: read_failure
[error] 2017-11-08T15:34:21.377307Z couchdb@127.0.0.1 <0.238.0> -------- Error opening view group `_auth` from database `shards/40000000-5fffffff/_users.1509985194`: {'EXIT',{{badmatch,{error,read_failure}},[{couch_mrview,get_info,2,[{f$
[error] 2017-11-08T15:34:21.398207Z couchdb@127.0.0.1 <0.238.0> -------- Error opening view group `_replicator` from database `shards/80000000-9fffffff/_replicator.1509985194`: {'EXIT',{{badmatch,{error,read_failure}},[{couch_mrview,get$

```

**Comment by wohali** [comment]
This is not a catch-all ticket for "My personal upgrade to 2.1.1 didn't work". I am locking this issue down to further replies.

If you need help with your specific upgrade scenario, please first reach out to our [mailing list](http://couchdb.apache.org/#mailing-lists) or our [Slack/IRC channel](http://couchdb.apache.org/#chat) before filing a ticket here.
