### ISSUE TITLE
update_seq of a view is set to zero after compaction

### ISSUE THREAD

**Issue by ondra-novak** [apache/couchdb#984]
After compaction of the view, update seq of the view  (not _info) is reset to zero.

## Expected Behavior

Update_seq ought to persist

## Current Behavior

Update_seq is reset to zero during or after compaction

## Possible Solution

fix it

## Steps to Reproduce (for bugs)

1. create view
2. feed with some data
3. check update_seq and remember (&update_seq=true)
4. compact the view
5. now check the update_seq again

## Context

I am trying to create stream of changes which is initialized from the view. Common scenario is:
1) query view and update_seq 
2) monitor changes from the update_seq returned by the view

## Your Environment
{"couchdb":"Welcome","version":"2.1.1","features":["scheduler"],"vendor":{"name":"The Apache Software Foundation"}}

## Example of result
total_rows":500,"offset":0,"update_seq":"**0-g2wAAAABaANkABFjb3VjaGRiQDEyNy4wLjAuMWwAAAACYQBuBAD_____amEAag**","rows":[
{"id":"o.1eDpbvT74bkV0ux7HrHg","key":1510482931,"value":null},
{"id":"o.1eDpc1T74elEZ4Lp59Ye","key":1510482937,"value":null},
{"id":"o.1eDpc1T74faGIb297jKL","key":1510482938,"value":null},
{"id":"o.1eDpc2T74idp04YSOhCE","key":1510482938,"value":null},
{"id":"o.1eDpc2T74k1tnW9z3SJy","key":1510482938,"value":null},
{"id":"o.1eDpc3T74l5srIbkwVh7","key":1510482939,"value":null},
{"id":"o.1eDpc3T74n1Wvr3NYkT0","key":1510482939,"value":null},
{"id":"o.1eDpc3T74oXJoxyzxEQ1","key":1510482939,"value":null},
{"id":"o.1eDpc3T74pJq9HJIZyVb","key":1510482939,"value":null},
{"id":"o.1eDpc3T74qe0oR5Jw4nb","key":1510482940,"value":null},
{"id":"o.1eDpc4T74rltlVYBI5xH","key":1510482940,"value":null},
{"id":"o.1eDpc4T74sd8kD1RVSTf","key":1510482940,"value":null},
{"id":"o.1eDpc4T74tSaZlqIg6Px","key":1510482940,"value":null},
{"id":"o.1eDpc4T74uKmSg0OlANd","key":1510482940,"value":null},

## IMPORTANT NOTE

This bug was not fixed from the 1.6!

**Comment by wohali** [comment]
Functionality was added back into 2.x with this commit:

https://github.com/apache/couchdb/commit/dc5cca804132266edec7a62cb2ca6b36cfadab27

by @rnewson .

This test validates that the update_seq is preserved across a compaction through the use of `GET /{db}/{ddoc}/_info`:

https://github.com/apache/couchdb/blob/master/test/javascript/tests/view_compaction.js

A worked example from the original poster. Note that `GET /{db}/{ddoc}/_info` returns the correct `update_seq` value, less the encoded cluster state, and that after a subsequent PUT to the database, the view's `update_seq` is still out of sync with the `GET /{db}/{ddoc}/_info` value:

```bash
$ curl -s http://localhost:5984/skimdb/_design/byName/_view/new-view?update_seq=true | head -1
{"total_rows":27371,"offset":0,"update_seq":"27385-g1AAAAC3eJzLYWBgYMlgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFOSA5BMqv___39WEgODVCYepXksQJLhAJD6D1UuHYVHeSJDkj3M2AkEjW2AGLsfrHxZFgBRADIY","rows":[

$ curl -s http://localhost:5984/skimdb/_design/byName/_info
{"name":"byName","view_index":{"updates_pending":{"minimum":0,"preferred":0,"total":0},"waiting_commit":false,"waiting_clients":0,"updater_running":false,"update_seq":27385,"sizes":{"file":20550176,"external":784774,"active":1567075},"signature":"e6a4d6491aa0b877b4c15653f5fc27c3","purge_seq":0,"language":"javascript","disk_size":20550176,"data_size":784774,"compact_running":false}}

$ curl -X POST -H "Content-type: application/json" http://localhost:5984/skimdb/_compact/byName
{"ok":true}

$ curl -s http://localhost:5984/skimdb/_design/byName/_view/new-view?update_seq=true | head -1
{"total_rows":27371,"offset":0,"update_seq":"0-g1AAAACreJzLYWBgYMlgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFMeC5BkaABS____35-VyEBQ7QGI2v_41SY5A
MmkeoLqEhmS7CGKsgANHi-y","rows":[

$ curl -s http://localhost:5984/skimdb/_design/byName/_info
{"name":"byName","view_index":{"updates_pending":{"minimum":0,"preferred":0,"total":0},"waiting_commit":false,"waiting_clients":0,"updater_running":false,"update_seq":27385,"sizes":{"file":1331732,"external":782314,"active":1449787},"signature":"e6a4d6491aa0b877b4c15653f5fc27c3","purge_seq":0,"language":"javascript","disk_size":1331732,"data_size":782314,"compact_running":false}}

$ curl -X PUT http://localhost:5984/skimdb/foo2 -d '{}'
{"ok":true,"id":"foo2","rev":"1-967a00dff5e02add41819138abb3284d"}

$ curl -s http://localhost:5984/skimdb/_design/byName/_view/new-view?update_seq=true | head -1
{"total_rows":27372,"offset":0,"update_seq":"6762-g1AAAACueJzLYWBgYMlgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFOSA5BMqv___39WEgODVBYepXksQJLhAJD6D1KeyIBHbSJDkj1BRRADGyAG7geqzQIAwGowNw","rows":[

$ curl -s http://localhost:5984/skimdb/_design/byName/_info
{"name":"byName","view_index":{"updates_pending":{"minimum":0,"preferred":0,"total":0},"waiting_commit":true,"waiting_clients":0,"updater_running":false,"update_seq":27386,"sizes":{"file":1333905,"external":782327,"active":1449906},"signature":"e6a4d6491aa0b877b4c15653f5fc27c3","purge_seq":0,"language":"javascript","disk_size":1333905,"data_size":782327,"compact_running":false}}
```

**Comment by wohali** [comment]
Paraphrasing a response that has been given before:

The update sequence values in CouchDB are opaque. In CouchDB 1.x, they were integers but, in Cloudant and 2.x, the value is an encoding of the sequence value for each shard of the database.

In both CouchDB and Cloudant, `_changes` and the view info will return a "seq" value with every row that is guaranteed to return newer updates if you pass it back as "since". _In cases of failover, that might include changes you've already seen._

So, the correct way to read changes since a particular update sequence is this;

    call /dbname/_changes?since=
    read the entire response, applying the changes as you go
    Record the last_seq value as your new checkpoint seq value.

Do not interpret the two values, you can't compare them for equality. You can, if you need to, record any "seq" value as you go in step 2 as your current checkpoint seq value. The key thing you cannot do is compare them.

Potential workaround:
You cannot use a view as a _changes feed, but you *can* [apply a filter function to a _changes feed](http://docs.couchdb.org/en/2.1.1/api/database/changes.html#get--db-_changes), which may help your use case. You can also use the [new Mango selector](http://docs.couchdb.org/en/2.1.1/api/database/changes.html#selector) which has significantly better performance than map-reduce views for this purpose. (I have personally seen 10x better performance with Mango selectors.)

**Comment by wohali** [comment]
Also for reference, please see https://issues.apache.org/jira/browse/COUCHDB-2849 which discusses why this is a problematic request and unlikely to be fixed anytime soon. Essentially, each copy of each view shard will have its own `update_seq` value...

**Comment by ondra-novak** [comment]
I don't understand, my english is not good.

Is this really WAI?
````
$ curl -s http://localhost:5984/skimdb/_design/byName/_view/new-view?update_seq=true | head -1
{"total_rows":27371,"offset":0,"update_seq":"0-g1AAAACreJzLYWBgYMlgTmEQTM4vTc5ISXIwNDLXMwBCwxygFFMeC5BkaABS____35-VyEBQ7QGI2v_41SY5A
MmkeoLqEhmS7CGKsgANHi-y","rows":[
````

**Comment by ondra-novak** [comment]
What is purpose of update_seq for the view? Has it some meaningful use?

Until 1.6. it was good reference to find offset in _changes stream. Because there is no way to monitor changes in a particular view. 

Please stop suggesting Mango selectors. I have database with 100 mil records, where 99% are filtered out. "Full-row" scan through the changes take hours - milliseconds using the view).

**Comment by ondra-novak** [comment]
> Also for reference, please see https://issues.apache.org/jira/browse/COUCHDB-2849 which discusses why this is a problematic request and unlikely to be fixed anytime soon. Essentially, each copy of each view shard will have its own update_seq value...

The new seqId  is several bytes long (still trying to figure why)

Is it really to hard to put there list of update_seqs from each node? 

My suggestion: [3587,3257,2325,3422]

Or with a better node addressing
```
{"node-name":update_seq,"node-name":update_seq,"node-name":update_seq,"node-name":update_seq}
```

It is impossible in general, or it is impossible only for current developers?

**Comment by rnewson** [comment]
I can't immediately think why the seq wouldn't be preserved across view compaction. I'm testing locally now.

**Comment by wohali** [comment]
Thank you @rnewson.

@ondra-novak Insulting the project you're asking for help from isn't going to get this resolved any faster. We have a [Code of Conduct](https://couchdb.apache.org/conduct.html) here at Apache CouchDB. Please think twice before posting comments of this sort in the future.

No one said it's impossible. We said that the value is opaque. There is no current well-defined use case where the contents of the token need to be parsed by clients, including your proposed use case.

**Comment by ondra-novak** [comment]
I feel that you only just trivialize the bug, or trying to play a game "the bug is on your side"

no, you have a bug in your code. The bug will there with me or without me. 
You don't understand meaning of the issue tracker
You need help, not me. I want to help you, I want you to have a bugfree code, ... production ready and shining,

Be grateful, please. 

End of offtopic, back to the issue.

What is purpose of the updae_seq? Why is ok to reset it during compaction? From my point of view, it is bug,

**Comment by rnewson** [comment]
It's probably a bug, yes. we'll look into it. (there's no such as bugfree code, and couchdb has been production 'ready' for many years). Adjust your attitude please.

**Comment by wohali** [comment]
Locking this ticket to updates.

**Comment by ondra-novak** [comment]
Thank you very much. If you need help, testing, investigating etc, please let me know.

**Comment by janl** [comment]
@ondra-novak Vice President of Apache CouchDB here. Formal notice to check your attitude and wording. I’m not seeing a language barrier here, you’re being offensive towards two of the project’s most prolific contributors. Even if it were casual contributors, this is a terrible strategy for getting your problems solved and is a clear violation of our code of conduct that you are hereby being reprimanded for.

Fair warning: our next enforcement level is temporary banning you from project communications.

You easiest step now is leave this be and wait for the bug to be addressed.

You best step now is to recognise that you’ve been in the wrong and apologise.

If you want to take this off-public, feel free to email private@couchdb.apache.org for a formal CoC handling.

**Comment by rnewson** [comment]
I'm observing some odd behaviour around the reported update_seq when I compact a view shard, so I believe this is a legitimate bug. I'm not spending more of my Sunday night finding the problem, though. It's real, so triage is complete.

**Comment by janl** [comment]
Closing in favour of https://github.com/apache/couchdb/pull/1434

Thank you for the report!
