### ISSUE TITLE
'Replication' menu not shows all replications

### ISSUE THREAD

**Issue by danikp** [apache/couchdb#992]
## Expected Behavior

If looking 'Replication' menu at 'Replicator DB Activity' tab, I expect to see all replications existing in _replicator database

## Current Behavior

Can see only 99 rows

## Possible Solution

show all replications having document in _replicator database (with or without pagination)

## Steps to Reproduce (for bugs)

1. add more than 100 replication documents to _replicator databse
2. open Fauxton
3. go to Replication->Replicator DB activity
4. there is only 99 rows shown

## Your Environment

* Version used: 2.1.1
* Browser Name and version: any
* Operating System and version (desktop or mobile): any
* Link to your project: https://fieldintech.com/

**Comment by popojargo** [comment]
Perhaps this should be moved to https://github.com/apache/couchdb-fauxton

**Comment by danikp** [comment]
you are right, moved to apache/couchdb-fauxton#1022
closing here
