### ISSUE TITLE
Mac OSX 13 2.1.1 build still uses -name couchdb@localhost in included vm.args

### ISSUE THREAD

**Issue by sinitean** [apache/couchdb#993]
Current macOS 10.6+ zip on download site still uses localhost in vm.args

## Expected Behavior

According to release nodes vm.args now uses "-name couchdb@127.0.0.1"

## Current Behavior

 it is still set to: 
"-name couchdb@localhost"

## Possible Solution

maybe provide similar to local.ini a way to create a local vm.args that is not overwritten during upgrades.

## Steps to Reproduce (for bugs)

1. Remove old install: delete couch from app folder, delete preferences and local.ini in user's Library/Preferences folder, delete CouchDB folder from user's Library/Application Support/ folder
2.Download 2.1.1 for macOS (10.6+) using link on couchdb.apache.org
3. Follow installation instruction and install couch.
4. Go to /Applications/Apache\ CouchDB.app/Contents/Resources/couchdbx-core/etc/ 
and open vm.args and you find -name couchdb@localhost

## Context

Would like a clean install because after last upgrade to 2.1.1 replication and writes wouldn't work any longer. I also had and see every couple of seconds chttpd_auth_cache errors in the logs.
(I will raise a separate issue on the chttpd_auth_cache error and replication not working. )

I think besides commenting that the setting needs to be changed from prior default, it would be quite helpful to provide a suggested path to move an existing install from the couchdb@localhost to the new recommended couchdb@127.0.0.1 config. 
In general, it would be helpful to have a recommended approach to move from one ip to another. 

Currently, the solution that comes to my mind, is to remove an existing install completely, install fresh, specify the desired ip (whether 127.0.0.1 or another ip), adjust all settings*   and then replicate the content from another install.

* adjusting the settings and where local settings go could also need some documentation, at least for the Mac. 
I should be able to re-use prior setting files as an alternative to using Fauxton. This works on Unix like platforms but the OS X install has gone through non documented changes (or at least I couldn't find any) and it isn't obvious. Before 2.1 settings were stored under the etc sub folder in the the Library/Application Support couch dir. Now there is a settings file in the Library/Preferences folder. Or maybe it was always there but i didn't notice it. 
There is also a local.ini within the Application/CouchDb package which will or will not be overwritten during upgrades? It doesn't seem to be used when saving local settings.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by janl** [comment]
This is intentional, so upgrades of existing systems work.

> maybe provide similar to local.ini a way to create a local vm.args that is not overwritten during upgrades.

That is my plan, but I don’t know when I get to that. You are welcome to help: https://github.com/janl/couchdb-mac-app

**Comment by sinitean** [comment]
I was pointing it out because it differs from the Unix build where it is set to 127.0.0.1.
As for the local vm.args alongside the one that is distributed, I was suggesting it as a cross platform thing not mac specific. 
Is there a recommendation how to change the setting in an existing system? Let’s say if I want to switch my install from localhost to 127.0.0.1?
Right now, I would remove the existing couchdb, install a new one and then replicate. Is there a better way?
