### ISSUE TITLE
View_index_dir is ignored in 2.1.1-1

### ISSUE THREAD

**Issue by sklassen** [apache/couchdb#994]
The xenial Ubuntu default.ini has the database_dir and view_index_dir set to ./data if you change view_index_dir to say ./index and create directory with correct permissioning, restart couchdb, the index direct remains empty. Indexes are created in the data directory.

**Comment by wohali** [comment]
You should never ever edit default.ini, it will be overwritten on upgrade.

Instead, try placing a file named `/opt/couchdb/local.d/index.ini` with the following contents:

```
[couchdb]
view_index_dir = ./index
```

and see if it works.

Reopen if this does not solve your problem.
