### ISSUE TITLE
How to avoid epmd binding 4369 on public interface (if possible at all)

### ISSUE THREAD

**Issue by ArchangeGabriel** [apache/couchdb#999]
I’m running a single node instance of couchdb. I’ve recently realized that couchdb is starting epmd which bind on 4369.

As they are no reasons for anything from the outside to connect to epmd, I would like to limit epmd binding to localhost.

## Expected Behavior
epmd should bind only on 127.0.0.1:4369 on single node instance.

## Current Behavior
epmd binds on ::4369.

## Possible Solution
I would be fine for a configuration option if doing that automatically on single node setup is not doable.

## Steps to Reproduce (for bugs)
1. Install couchdb.
2. Configure it for single node setup.
3. Run `lsof -i tcp:4369` as root, with sudo or whatever gives you the correct rights.
4. Observes something like this:
```
epmd     481 couchdb    3u  IPv4  16031      0t0  TCP *:epmd (LISTEN)
epmd     481 couchdb    4u  IPv6  16032      0t0  TCP *:epmd (LISTEN)
```

## Context
I want to avoid uselessly opened ports on my server.

## Your Environment
* Version used: 2.1.1
* Browser Name and version: N/A
* Operating System and version (desktop or mobile): ArchLinux
* Link to your project: N/A

**Comment by wohali** [comment]
This is an Erlang function, not a CouchDB one.

`export ERL_EPMD_ADDRESS=127.0.0.1` before launching CouchDB (and epmd) to limit epmd to bind to localhost only.

You could also launch epmd yourself with the above setting before launching CouchDB if you preferred.

Documentation here: http://erlang.org/doc/man/epmd.html

**Comment by ArchangeGabriel** [comment]
Thanks, this helped a lot.

**Comment by ArchangeGabriel** [comment]
Sorry to bother you again but I can’t find any information about a second Erlang process belonging to couchdb, `beam.smp`. It apparently also binds on public interfaces:
```
COMMAND  PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
beam.smp 476 couchdb   13u  IPv4  14000      0t0  TCP *:43301 (LISTEN)
```
Do you know if I can avoid that?

**Comment by ArchangeGabriel** [comment]
@wohali Any idea what controls the address/port this `beam.smp` is binding on?

**Comment by ArchangeGabriel** [comment]
Apparently, adding an argument such as `[{kernel,[{inet_dist_use_interface,{127,0,0,1}}]}].` to erlang invocations should solve it. This is [a proposed answer for RabbitMQ](https://serverfault.com/questions/235669/how-do-i-make-rabbitmq-listen-only-to-localhost), but I’m not sure how I can pass this to CouchDB. Would adding a line like this in `vm.args` work:
```
-kernel inet_dist_use_interface 127.0.0.1
```
?

**Comment by ArchangeGabriel** [comment]
This proposed fix is maybe too specific to RabbitMQ since kernel is apparently the name of some of their component.

Can someone tell me were in the code the beam.smp process is started? Or is it started by epmd itself?

**Comment by daftaupe** [comment]
@ArchangeGabriel : you have to add this line to `vm.args` so that `beam.smp` listen on `127.0.0.1` 

`-kernel inet_dist_use_interface {127,0,0,1}`

**Comment by ArchangeGabriel** [comment]
@daftaupe Thank you so much!

**Comment by ArchangeGabriel** [comment]
So just to be sure, with the 3.2.2 release both settings are now the default and unnecessary?

**Comment by ArchangeGabriel** [comment]
After a simple testing, the `ERL_EPMD_ADDRESS=127.0.0.1` bit is still required even with 3.2.2. Is that expected? I could see the addition of the `vm.args` bit in the 3.2.1 to 3.2.2 diff, but nothing regarding `epmd` bidding. Is that correct? What should do distro packagers then? Set this variable by default?

**Comment by ArchangeGabriel** [comment]
So that part of the fix is indeed solved at packaging level, thanks to @janl for pointing to https://github.com/apache/couchdb-pkg/pull/92/files on oss-security.

**Comment by Catlike14** [comment]
I'm trying to set `inet_dist_use_interface` to my private IP in order to use `epmd` through a dedicated interface in a clustered setup, but the process results to be bound to 0.0.0.0 instead.

**Comment by rnewson** [comment]
please open a new issue, this issue is resolved.
